### ISSUE TITLE
Getting model counts from Searchkick.search

### ISSUE THREAD

**Issue by chrisjcha** [ankane/searchkick#1004]
Hello,

I have 2 models: Position, Candidate.

I'm trying to get model counts after doing the following multi search for example:

```
@results = Searchkick.search(
     "rails",
      page: params[:page], 
      per_page: PER_PAGE,
      index_name: [Position, Candidate],
      fields: ['skill', 'location', 'description', 'first_name', 'last_name'],
      highlight: {tag: '<mark>'}
```

I'm getting the expected search results and total count of all results, but how do I get the total counts for each model Position and Candidate?

Thanks!

**Comment by ankane** [comment]
Hey @chrisjcha, `@results.results` will return an array, and from there you can use the same approach you would use to count elements in an array.

**Comment by chrisjcha** [comment]
Here's the solution I found just now:
`aggs: {terms: {field: '_type'}}`

This returns the terms with each bucket and doc_count.

Thanks!
