### ISSUE TITLE
When search document fields have dots, queries don't works.

### ISSUE THREAD

**Issue by raphaelcuba** [ankane/searchkick#1006]
I've trouble to search an email in my index. Supposing that i've an account with email address and index it, the search below never returns the document expected. Has anyone ever experienced this? My temp solution is generate a md5 hash and index this value.

```ruby
 def search_data
    {
      # other data...
      account_email: email.downcase
    }
  end
```

```ruby
search = Account.search '*', where: { account_email: 'emailofcustomer2017@email.com' }
search.total_count # => 0
```

Gemfile.lock
```
searchkick (2.3.1)
elasticsearch (5.0.4)
  elasticsearch-api (= 5.0.4)
  elasticsearch-transport (= 5.0.4)
elasticsearch-api (5.0.4)
  multi_json
elasticsearch-transport (5.0.4)
```

Ruby version: 2.3.4

**Comment by rafaelsales** [comment]
Can you paste how you're using the `searchkick` macro as well?
Querying just `Account.search('*').total_count` returns > 0 in this case?

**Comment by raphaelcuba** [comment]
Not now @rafaelsales, i don't have here now the complete code here. But it's not my first time using this gem and I never had a problem.

I did this test `Account.search('*').total_count` before open this issue and total count is > 0.

**Comment by ankane** [comment]
Hey @raphaelcuba, I can look into it if you can create a failing test case. I haven't heard of this issue before, so I suspect it's related to your app/data.

**Comment by ankane** [comment]
Cleaning up stale issues
