### ISSUE TITLE
About possible portability to Hanami

### ISSUE THREAD

**Issue by AlexVKO** [ankane/searchkick#1008]
Hey guys,

I've been using SearchKick for quite some time, especially when I need product searching.

But currently I'm working on a company that uses Hanami, and one of the possible things that I could do is adapt Searchkick for Hanami.

So, before diving into the code, I'd like to know from you guys, how complex it would be, and what is the possible challenges.

thank you!

**Comment by ankane** [comment]
Hey @AlexVKO, I'm not very familiar with Hanami, so don't have a great answer.
