### ISSUE TITLE
async: { wait: true } doesn't seems to be working

### ISSUE THREAD

**Issue by alienxp03** [ankane/searchkick#1012]
I created a method to reindex all data and I want to wait till the reindex finish so I can promote the new index. However it doesn't seems to be working well

```ruby
index_name = self.reindex(async: { wait: true }, refresh_interval: '30s')[:index_name] #a
self.search_index.promote(index_name, update_refresh_interval: true) #b
self.search_index.clean_indices #c
```

1. `async: { wait: true }` does not wait till the reindex finished. I'm using Sidekiq, so what I noticed is that by the time it got to line #b, the reindexing is not yet done, but it was in the `busy` queue in Sidekiq instead. So I ended up promote the new index too early, and delete the old ones too early too

2. I also notice that `async: { wait: true }` doesn't work in Rails console. Running it as a `rake task`, Searchkick does wait till it queue everything. When I rake the same thing in console, the async method seems to be ignored

**Comment by alienxp03** [comment]
Upon checking with Redis, `Searchkick::ReindexQueue.new(index_name).length` is using code below:

```
Searchkick.with_redis { |r| r.llen(redis_key) }

where `redis_key` is `searchkick::reindex_queue:person_index`
```

However, manually changing and query using code below will produce the right queue size:

```
Searchkick.with_redis { |r| r.scard(redis_key) }

where `redis_key` is `searchkick::reindex_queue:person_index:batches`
```

Is that the cause of the bug, o am I using any unsupported gems? Current redis version is 4.0.2

**Comment by ankane** [comment]
Hey @alienxp03, I'm unable to reproduce the issue. The reindex queue you mention in the 2nd comment is not used with the `async: {wait: true}` option (it's used when you have `callbacks: :queue`).

**Comment by ankane** [comment]
Also, you don't need to manually promote and clean indices with the the `async: {wait: true}` option.

**Comment by alienxp03** [comment]
Thanks for the feedback @ankane. I am currently using `:queue` callbacks. Or does it mean `async: {wait: true}` is only for `callbacks: :async`? This is my final code, which is different than the one in the README, but seems to be working ok now. `async: {wait: true}` seems to be inconsistent for me. Sometimes it does wait synchronously, sometimes it just skip and do it asynchronously and that leads to Searchkick promote the index too early.

```ruby
index_name = reindex(async: true, refresh_interval: '30s')[:index_name]

loop do
  queue_size = Sidekiq::Queue.new('searchkick').size
  sleep 5
  break if queue_size.zero? # Might increase a little bit, depends on how it goes on prod
end

search_index.promote(index_name, update_refresh_interval: true)
search_index.clean_indices
```

**Comment by ankane** [comment]
`async: {wait: true}` is completely independent from the callbacks. It is only concerned with the full reindex. I don't think there's an actual issue (just a possible misunderstanding), so going to close.
