### ISSUE TITLE
Sort only by filtered objects

### ISSUE THREAD

**Issue by tehPlayer** [ankane/searchkick#1013]
Hello,

Assuming we are searching over Forest, which has Trees as one-to-many association.

```
{
  id: 1,
  trees: [{
    id: 1,
    height: 15,
    type: 1
  }, {
    id: 2,
    height: 5,
    type: 2
  }, {
    id: 3,
    height: 7,
    type: 2
  }]
}, {
  id: 2,
  trees: [{
    id: 4,
    height: 10,
    type: 2
  }, {
    id: 5,
    height: 5,
    type: 1
  }, {
    id: 6,
    height: 7,
    type: 1
  }]
}, {
  id: 3,
  trees: [{
    id: 7,
    height: 10,
    type: 1
  }, {
    id: 8,
    height: 8,
    type: 2
  }, {
    id: 9,
    height: 7,
    type: 2
  }]
}

```

How can I sort by `trees.height` but only for `trees.type == 2`?

I'm using default mapping. I already tried `where: {'trees.type' => 2}, order: {'trees.height' => {order: :desc}}`, however it takes all the time the first tree in association.

In example above, i would like to have following order of Forests: `2, 3, 1`

**Comment by ankane** [comment]
Hey @tehPlayer, I'd recommend sorting in-memory for this. I'm not sure there's a built-in way with Elasticsearch.
