### ISSUE TITLE
callbacks: false is not working

### ISSUE THREAD

**Issue by hamdibayhan** [ankane/searchkick#1015]
I am using `callbacks: false` like the following but it is not working.  When I was add a people, new record was indexing why?

```
searchkick callbacks: false, filterable: [:student_id], word_middle: People::SEARCH_WORD
```

**Comment by ankane** [comment]
Hey @hamdibayhan, I don't think it's an issue with Searchkick, but feel free to submit a failing test case if you think otherwise.
