### ISSUE TITLE
Can not find association record when using where with Searchkick.

### ISSUE THREAD

**Issue by utkarshrai003** [ankane/searchkick#1016]
I have two models - Person and Company. Definition for them is given below - 

class Person < ApplicationRecord
  searchkick
  scope :search_import, -> { includes(:company) }

  belongs_to :company

  def search_data
    {
      email: email.try(:downcase),
      city: city.try(:downcase),
      zip: zipcode,
      state: state.try(:downcase),
      company: self.company.try(:name).try(:downcase) || ""
    }
  end
end

class Company < ApplicationRecord
  searchkick

  has_many :people
end

I am trying to get the person record for a particular company. I have added company key in the search_data method in Person model.
I am trying to do something like this - 
**Person.search("*", fields: [:company], where: {company: 'Anderson Law Firm'})**

But it returns nil. While if I try to query like this - 
**Person.search('Anderson Law Firm', fields: [:company])**
I get the desired result.

Any help would be appreciated.

**Comment by ankane** [comment]
Hey @utkarshrai003, the where option is case sensitive. Try removing the downcase, reindexing, and searching again, or change your where option to use the downcase version.

**Comment by utkarshrai003** [comment]
thanks @ankane. It worked by changing the where option to downcased version.
