### ISSUE TITLE
Elasticsearch Bool Query 

### ISSUE THREAD

**Issue by sureshvignesh** [ankane/searchkick#1018]
Is there any possibility to integrate Elasticsearch's _bool_ query?

**Comment by ankane** [comment]
Hey @sureshvignesh, can you give an example of what you'd like to do?

**Comment by srebalaji** [comment]
Hi @ankane,
Like this one https://www.elastic.co/guide/en/elasticsearch/guide/current/bool-query.html

**Comment by sureshvignesh** [comment]
Same as @srebalaji  mentioned!

**Comment by Schwad** [comment]
@ankane what are your thoughts? Do you feel that @srebalaji gave a satisfactory response to your question?

**Comment by ankane** [comment]
It's still not exactly clear what the ask is. I'm familiar with bool queries, as Searchkick already uses them in some places if you check out the code. I'm curious to hear an example of what people are trying to do with it that can't be done today. I have some ideas, but want to confirm.

**Comment by Schwad** [comment]
@ankane okay - @srebalaji @sureshvignesh are you able to clarify this a bit more with a concise example? :)

**Comment by ankane** [comment]
Cleaning up stale issues

**Comment by pkmital** [comment]
Hi @ankane thanks for the brilliant package.  I'd like to search across different indices, filtering differently for each index, and paginate the results.  Something like: https://stackoverflow.com/questions/21753021/elasticsearch-global-search-different-filter-on-multiple-indexes - is this possible?
