### ISSUE TITLE
Model.reindex - > Could not convert [_all.index] to boolean"}]

### ISSUE THREAD

**Issue by noeldelgadom** [ankane/searchkick#1025]
This is the first time I use searchkick. I followed the 'Getting Started' instructions and got stuck trying to reindex my models. I opened the rails console and ran

> User.reindex
> Item.reindex
> List.reindex

On all three occasions I got an error that looks like this:

>Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Could not convert [_all.index] to boolean"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Could not convert [_all.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Could not convert [_all.index] to boolean","caused_by":{"type":"illegal_argument_exception","reason":"Failed to parse value [analyzed] as only [true] or [false] are allowed."}}},"status":400}

**Comment by ankane** [comment]
Hey @noeldelgadom, what version of Searchkick are you on?

**Comment by noeldelgadom** [comment]
gem 'searchkick', '~> 1.3'

**Comment by ankane** [comment]
You're on a pretty old version. Upgrading to the latest version should fix it.

**Comment by noeldelgadom** [comment]
That's embarrassing ha. Thanks for the help @ankane. I upgraded to 2.4 and that solved it. 
Btw... I got the 1.3 version from googleing 'ruby gem searchkick'

My first result was 
https://rubygems.org/gems/searchkick/versions/1.3.0

When it should be 
https://rubygems.org/gems/searchkick

Interesting

**Comment by chai2** [comment]
I was on 2.3, and upgrading to 2.4 fixed it. Thanks @ankane
