### ISSUE TITLE
How to run exact query matching (Case insensitive)

### ISSUE THREAD

**Issue by sp2410** [ankane/searchkick#1027]
Hi all! I am a working elastic search and stuck with a problem:

 I am implementing an elasticsearch search method using searchkick. My settings in Book model are as follows:

```
#elastic search settings:
  searchkick 

 def search_data
    attributes.merge(
      title: title,
      last_name: author(&:last_name),
      publisher_name: publisher(&:name),
    )
end

```
Book model relationships is as follows:

```
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher

  has_many :book_formats
  has_many :book_reviews
  
  has_many :book_format_types, :through => :book_formats
end
```

My search is as follows:

`self.search(query, fields: [:title, {publisher_name: :exact}, {last_name: :exact}]).records   `

However, if I am running rspec tests over factories, I am getting results which tells me exact is not working. For example:
```
author1 = create(:author, first_name: "Kate", last_name: "White")       
publisher1 = create(:publisher, name: "HarperCollins")
book1 = create(:book, title: "The Secrets You Keep: A Novel", author_id: author1.id, publisher_id: publisher1.id)

publisher3 = create(:publisher, name: "Pamela Dorman Books;")
author3 = create(:author, first_name: "Shari", last_name: "Lapena")  
book3 = create(:book, title: "Couple Next Door", author_id: author3.id, publisher_id: publisher3.id)


author4 = create(:author, first_name: "Lauren", last_name: "Graham")       
publisher4 = create(:publisher, name: "Ballantine Books")
book4 = create(:book, title: "Someday, Secrets Someday, Maybe", author_id: author4.id, publisher_id: publisher4.id)


author5 = create(:author, first_name: "Fictious", last_name: "Secrets")       
publisher5 = create(:publisher, name: "Ballantine Books")
book5 = create(:book, title: "Fictious Book 1", author_id: author5.id, publisher_id: publisher5.id)

author9 = create(:author, first_name: "Lauren", last_name: "xyz")       
publisher9 = create(:publisher, name: "Secrets halo")
book9 = create(:book, title: "Cool Book", author_id: author9.id, publisher_id: publisher9.id)
```
Rspec query:

`expect(Book.search_instead_with_elastic_search('Secrets')).to match_array([book1, book4, book5, book9]) passes. But if I have specified for exact, why is "Secrets halo" being considered? book 9 should not be included in my results.`

I want query to search title and match like sql contains - %query%. But, I want author last name to be exact, and publisher last name to be exact as well as per the query. 

That means, A publisher name of "Anna Secrets" should not be considered, same with last name but a title as such can be considered for a search term "Secrets"

I also tried:
self.search(query, where: [{last_name: /\b"#{query}"\b/},{publisher_name: /\b"#{query}"\b/},{title: /\b"#{query}"\b/}]).records

but that doesn't work as well.

Will really appreciate your help :)

**Comment by kamillamagna** [comment]
For future reference, Github Issues are for reporting bugs and development issues. Your problem is better suited for somewhere like searchkick's [StackOverflow](https://stackoverflow.com/questions/tagged/searchkick) tag.

I solved this problem on my app by using `match: :phrase` for fields with multi-word queries. Maybe that would work for you?

**Comment by ankane** [comment]
Thanks @kamillamagna 👍
