### ISSUE TITLE
Is it possible to use parent-child relationships in searchkick?

### ISSUE THREAD

**Issue by kouyaf77** [ankane/searchkick#1029]
I could define mapping by using custom mapping.
https://github.com/ankane/searchkick/blob/master/README.md#advanced-mapping

But I don't understand how to create document in child index type with searchkick.

**Comment by ankane** [comment]
Hey @kouyaf77, Searchkick isn't designed for this use-case. You're probably better off using elasticsearch-ruby directly.

**Comment by fatkodima** [comment]
@ankane, sorry I'm not super familiar with searchkick internals, but should it be hard/possible to implement this? And if possible, will this PR be accepted?

**Comment by ankane** [comment]
@fatkodima I haven't worked with parent-child relationship, so not sure. For a PR to be accepted, it'd need to add significant benefit and limited complexity, but I don't have a great idea of either right now.
