### ISSUE TITLE
multi_search with sort over model that has no records raises NoMethodError

### ISSUE THREAD

**Issue by rafaelsales** [ankane/searchkick#1032]
```ruby
class Model < ActiveRecord::Base
  searchkick
end

def multi_search
  Searchkick.multi_search([Model.search('*', execute: false, order: { created_at: :asc })])[0].results
end

Model.reindex

multi_search
# raises NoMethodError: undefined method `[]' for nil:NilClass
# .../gems/searchkick-2.3.2/lib/searchkick/results.rb:190:in `hits'

Model.create
multi_search # runs ok
```

This only happens when order is present.

**Comment by ankane** [comment]
Hey @rafaelsales, thanks for the report. I added a test case for this, but it's passing.

Commit: https://github.com/ankane/searchkick/commit/fc62c49a9e76c75e97181cdb1760fc4303c6809f
Build: https://travis-ci.org/ankane/searchkick/builds/308816036

**Comment by rafaelsales** [comment]
Adding a `Product.reindex` before that will cause the issue:

```ruby
  def test_no_records
    Product.reindex
    products = Product.search("*", order: {created_at: :asc}, execute: false)
    assert Searchkick.multi_search([products])[0].results
  end

  1) Error:
MultiSearchTest#test_no_records:
NoMethodError: undefined method `[]' for nil:NilClass
    /Volumes/data/ws/searchkick/lib/searchkick/results.rb:190:in `hits'
    /Volumes/data/ws/searchkick/lib/searchkick/results.rb:29:in `results'
    /Volumes/data/ws/searchkick/test/multi_search_test.rb:41:in `test_no_records'
```

BTW, I really expect an error here, but not `NoMethodError`, so this other test is expected:
```ruby
  def test_no_records_2
    Product.reindex
    exception = assert_raises { Product.search("*", order: {created_at: :asc}) }
    assert_equal exception.class, Searchkick::InvalidQueryError
    assert_match /No mapping found for \[created_at\]/, exception.message
  end
```

I would just expect the same exception when using multi_search

**Comment by ankane** [comment]
Ah, I see the issue. It's throwing an error. As the docs state:

> Errors are not raised as with single requests. Use the error method on each query to check for errors. Also, if you use the below option for misspellings, misspellings will be disabled.

Instead of the `NoMethodError`, we should probably have a custom error if you try to access results when there's an error.

**Comment by ankane** [comment]
It now throws a `Searchkick::Error` with a better description on master. Big thanks for helping debug 💯

**Comment by rafaelsales** [comment]
Perfect - Thanks!
