### ISSUE TITLE
Different results when using 'where' and keyword

### ISSUE THREAD

**Issue by hashwin** [ankane/searchkick#1036]
I am trying to do a general search using a record ID as a keyword.

This works fine when using a 'where' clause.
```
irb(main):034:0> Lead.search('*', where: {id: '16317'}).count
  Lead Search (5.8ms)  curl http://localhost:9200/leads_development/_search?pretty -d '{"query":{"bool":{"must":{"match_all":{}},"filter":[{"term":{"_id":"16317"}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'
  Lead Load (0.7ms)  SELECT "leads".* FROM "leads" WHERE "leads"."id" = 16317
=> 1
```
But this fails when using the ID as a keyword.
```
irb(main):035:0> Lead.search('16317', fields: [:id]).count
  Lead Search (5.7ms)  curl http://localhost:9200/leads_development/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"id.analyzed":{"query":"16317","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"id.analyzed":{"query":"16317","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"id.analyzed":{"query":"16317","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"id.analyzed":{"query":"16317","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'
=> 0
``` 

Any ideas on how I can get this to work?

**Comment by abhinaykumar** [comment]
Ideally if you want to query based on `id` or some boolean field then you should be using `where` and searchkick would just work fine. using `field` to query records based on `id` doesn't look like a good approach though but it should still work.

* How does your `search_data` method looks like in `Lead` model? 
* Also, do you have this line: `searchkick word_start: [ :id ]` set in `Lead` model ?

**Comment by hashwin** [comment]
Hi @abhinaykumar 
The reason I want to do it is because I have a general search field where I do not know which field the user is referring to.
But yes, I did not have word: [:id] set up, adding that fixed the problem, thanks!
