### ISSUE TITLE
Immediate Sync with Specific Attributes

### ISSUE THREAD

**Issue by okashino** [ankane/searchkick#1038]
Is there a way to select specific attributes that if changed, the immediate sync process is triggered?

Use case: I have a model with many attributes that change frequently, and I don't want to refresh the index everytime one of those attributes change as the record is saved. Only specific attributes affecting the index should trigger the immediate sync.

**Comment by ankane** [comment]
Hey @okashino, check out "Reindex conditionally" in the readme.

**Comment by okashino** [comment]
Awesome! thanks for the quick response. I will try it out.
