### ISSUE TITLE
Pass `suggest: true` to the search method for suggestions

### ISSUE THREAD

**Issue by fandyd** [ankane/searchkick#1042]
Im having the issue with suggestions with no data in the index, index has been build

> result = Product.search('*', suggest: true)
> result.size
> 0
> result.suggestions.present?

RuntimeError: Pass `suggest: true` to the search method for suggestions
	from /Users/fd/app/vendor/bundle/ruby/2.3.0/gems/searchkick-2.4.0/lib/searchkick/results.rb:81:in `suggestions'

**Comment by ankane** [comment]
Hey @fandyd, thanks for reporting 👍  Fixed on master.
