### ISSUE TITLE
Prevent plural term to be suggested while searching singular, and vice versa

### ISSUE THREAD

**Issue by fandyd** [ankane/searchkick#1048]
I need a little bit of help. Apparently the suggestion work is returning singular term while searching for plural term and vice versa. How do i prevent this to happen?

```
> result = Product.search('wheelchairs', suggest: true)
> result.suggestions
> [
>    [0] "wheelchair"
> ]
>
> result = Product.search('wheelchair', suggest: true)
> result.suggestions
> [
>    [0] "wheelchairs"
> ]

**Comment by ankane** [comment]
Hey @fandyd, Searchkick doesn't provide a way to do this, so you'll need to manually filter them from the suggestions returned. A quick and dirty way would be:

```ruby
query = "wheelchairs"
suggestions = ["wheelchair", "other"]
suggestions = suggestions.reject { |s| s.include?(query[0..-2]) }
```

**Comment by Schwad** [comment]
@fandyd do you feel happy with your answer/resolution to this issue?

**Comment by fandyd** [comment]
Not really, but i manage to do a work-around by using a custom field with custom analyzer and custom query suggest
