### ISSUE TITLE
ENV["ELASTICSEARCH_URL"]

### ISSUE THREAD

**Issue by claeusdev** [ankane/searchkick#1050]
ENV["ELASTICSEARCH_URL"]= "https://es-domain-1234.us-east-1.es.amazonaws.com"

is the assigned URL a defined or i need to add my own environment name? 
Thanks
![elastic](https://user-images.githubusercontent.com/17507528/34561346-71786030-f141-11e7-8615-899ca9711553.png)

**Comment by ankane** [comment]
Hey @claeusdev, when in doubt, give it a shot. It'll be much faster than waiting for an answer online.
