### ISSUE TITLE
search_import does not work

### ISSUE THREAD

**Issue by makeapp007** [ankane/searchkick#1052]
When I create a user whose role is not "a" and then search, I can get that user. Shouldn't I get that user?
But when I explicitly call People.reindex, I can not get that user any more.

This is what I write:

```
People.rb
scope :search_import, ->{where(role:"a")}
def should_index?
  role
end
def search_data
  {
    username: username,
    description:description,
    role:role,
  }
end
```

**Comment by mikelkew** [comment]
As far as I'm aware the should_index? method should be an instance method that returns true or false. Try using `role == 'a'` and see if that works..

**Comment by makeapp007** [comment]
Works. Thank you!

**Comment by ankane** [comment]
Thanks @mikelkew 👍
