### ISSUE TITLE
Rails 5.2.0 ActiveStorage .with_attached_images

### ISSUE THREAD

**Issue by tobiasfeistmantl** [ankane/searchkick#1056]
ActiveStorage uses the `.with_attached_images` storage to load images with the records and to prevent N+1 queries.

Eg:
```
def index
    # Use the built-in with_attached_images scope to avoid N+1
    @messages = Message.all.with_attached_images
end
```
=> [ActiveStorage Docs](https://github.com/rails/rails/tree/master/activestorage)

Maybe this method should be integrated like the `.includes` method?

**Comment by ankane** [comment]
Hey @tobiasfeistmantl, great idea 👍  I added a more general method for this on master.

```ruby
Message.search "something", scope_results: ->(r) { r.with_attached_images }
```

**Comment by tobiasfeistmantl** [comment]
Thanks @ankane!
