### ISSUE TITLE
Documentation References Many Queries That Rely On '_all'

### ISSUE THREAD

**Issue by weilandia** [ankane/searchkick#1057]
Since Elasticsearch 6 disables the `_all` field by default, should all the queries in the documentation make `fields` explicit?

Also, how would you feel about having default `fields` optionally set on each model?

**Comment by ankane** [comment]
Hey @weilandia, thanks for bringing this up. Feels like it’ll make things less clear if it’s added to every example. There’s a default_fields option you can specify on the model. Maybe changing the first example in the docs to that will suffice.

**Comment by weilandia** [comment]
Whoops, missed the `default_fields` option in the docs.  Yep, that sounds like it'll work.
