### ISSUE TITLE
Parallel Indexing Takes Down Index

### ISSUE THREAD

**Issue by gidfs** [ankane/searchkick#1060]
I have a cron job to periodically reindex all Searchkick models. However, it appears to be deleting some of the indexes before the new one is actually promoted. 

` Searchkick.models.each do |model|
      index_name = model.reindex(async: {wait: true}, refresh_interval: "30s")[:index_name]
      model.search_index.promote(index_name, update_refresh_interval: true)
end`

Do you recommend doing this differently?

**Comment by ankane** [comment]
Hey @gidfs, you can pass `clean: false` to reindex to avoid this.

**Comment by gidfs** [comment]
Thanks for the reply. 

Pass clean like so? `index_name = Episode.reindex(clean: false, async: {wait: true}, refresh_interval: "30s")[:index_name]`

Im getting this error: `ArgumentError: unknown keyword: clean` on `lib/searchkick/index.rb:217:in `reindex_scope'`

Im on version: searchkick-2.3.1

Thanks again for the help!

**Comment by gidfs** [comment]
Nvm, its `retain: true`. Testing now.

**Comment by ankane** [comment]
My bad, it is `retain: true`.

**Comment by gidfs** [comment]
@ankane, do I need to clean indices manually afterwards?

**Comment by gidfs** [comment]
Actually, both cleaning and not cleaning still took down our indices. Any other suggestions? We're running ES 5.3

**Comment by ankane** [comment]
What do you mean by "took down our indices"?

**Comment by gidfs** [comment]
We've been seeing some pretty bizarre behavior when trying to run the script above. When the reindexing is initiated, it appears to prematurely remove the current indices. So we get errors similar to this one when searching: 

`{
    "errors": "[400] {\"error\":{\"root_cause\":[{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [<attribute>] in order to sort on\",\"index_uuid\":\"<uuid>\",\"index\":\"model-en_<time_stamp>\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":0,\"index\":\"shows-production-en_20180103190152176\",\"node\":\"<node-id>\",\"reason\":{\"type\":\"query_shard_exception\",\"reason\":\"No mapping found for [<attribute>] in order to sort on\",\"index_uuid\":\"<uuid>\",\"index\":\"model-en_<time_stamp>\"}}]},\"status\":400}"
}`

Error persists until the reindexing is completed

**Comment by ankane** [comment]
I’m not sure how to reproduce, so going to close. If you’re still seeing odd behavior, please use the gist in the Contributing Guide to repro.
