### ISSUE TITLE
User Lower Function in where condition

### ISSUE THREAD

**Issue by vishalTatvaSoft** [ankane/searchkick#1065]
@ankane 
How can i use postgres lower function in searchkick's where condition 

I have below query which is working fine 

`klass.search(@params[:query], fields: [:name,:category_name],where: {or: [[{available_cities_name: "New Yo"},{available_cities_short_name: "NY"}]]}).hits
`
Now i want to use lower function but i am getting syntax error
`
 klass.search(@params[:query], fields: [:name,:category_name],where: {or: [[{"lower(available_cities_name) = ?", "New Yo"},{"lower(available_cities_short_name) = ?", "ny"}]]}).hits`

I am getting below syntax error, 

> SyntaxError: unexpected '}', expecting end-of-input
> e_cities_name) = ?", "New Yo"},{"lower(available_cities_shor
> 

Can somebody tell me how to user lower function in searchkick ?

**Comment by sondnm** [comment]
@vishalTatvaSoft your hash syntax is completely incorrect. Please correct your syntax before asking any questions.
And in my understanding, `where` clause in searchkick is only syntactic sugar for elasticsearch query, not for SQL query. So you actually can't use ActiveRecord where syntax as searchkick params.
