### ISSUE TITLE
Issue with Multi Model Search

### ISSUE THREAD

**Issue by pushpalata-c** [ankane/searchkick#1068]
We are facing issue related to Global Search, after upgrading the version of searchkick from 1.3.3 to 2.0.0.

The search gives weird results
Example:
Document present with field1 = "We're Thrilled To Announce"

If we search with "Thrilled To Announce" then results are shown
But if we do an exact search no results are returned.
Also, many combinations of field1 do not work.

Below is the Search
Searchkick.search(search_test, fields: ["field1^10", "field2^5", "field3^3"],
          index_name: [Model1, Model2, Model3, Model4],
          indices_boost: {Model1 => 15, Model2 => 12, Model3 => 9, Model4 => 7},
          where: {status: true, is_valid: true},
          load: false,
          page: params[:page],
          per_page: 10)

Thanks in advance.

**Comment by abhinaykumar** [comment]
How does your `search_data` method looks like? Also, what parameter are you passing to searchkick?: ex: `searchkick word_start: [ :field.....]`

**Comment by pushpalata-c** [comment]
Hi Abhinay,

Below are the search_data method and searchkick definition we are using,

searchkick index_name: "indexname_v1", callbacks: false
def search_data
 {
  id: id,
  name: title,
  slug: nil,
  description: Nokogiri::HTML.parse(body).text,
  tag_name: nil,
  model_id: self && self.model.present? ? self.model.typeable_id : nil,
  model_type: self && self.model.present? ? self.model.typeable_type : nil,
  start_date: self && self.start_date? ? start_date : Time.zone.now - 1.years,
  end_date: self && self.end_date? ? end_date : Time.zone.now + 100.years,
  status: self && self.status == 'D' ? false : true,
  draft: self && self.draft? ? draft : false
 }
end

Above format is same for all the searchable Models

Thanks

**Comment by abhinaykumar** [comment]
what query are you running to get an exact result?, are you using a field specific one or some other ways?

**Comment by pushpalata-c** [comment]
Below is our Query for getting result (exception is that we should get partial as well as exact result)

Searchkick.search("search_test", fields: ["name^10", "description^5", "tag_name^3"],
index_name: [Model1, Model2, Model3, Model4],
indices_boost: {Model1 => 15, Model2 => 12, Model3 => 9, Model4 => 7},
where: {status: true, is_valid: true},
load: false,
page: params[:page],
per_page: 10)

Thanks

**Comment by abhinaykumar** [comment]
so I think you are missing couple of things here, starting from model
you should have something like 
```
# i am not sure but probably you dont need to pass `index_name` here
searchkick callbacks:false, word_start: [:name, :description,...] #all the fields you want this search to be run on
```
then to your search query(`match` keyword is missing), 
```
Searchkick.search("search_test", fields: ["name^10", "description^5", "tag_name^3"],
index_name: [Model1, Model2, Model3, Model4],
indices_boost: {Model1 => 15, Model2 => 12, Model3 => 9, Model4 => 7},
where: {status: true, is_valid: true}, match: :word_start,
load: false,
page: params[:page],
per_page: 10)
```

**Comment by pushpalata-c** [comment]
Thank you Abhinay, I will apply these changes and see if works

I have one query, previously we have not added **:word_start** still it was working correctly
The problem started after searchkick upgrade

**Comment by abhinaykumar** [comment]
> I have one query, previously we have not added :word_start still it was working correctly
> The problem started after searchkick upgrade

Yes, this is very strange to me. sorry but i don't have any explanation for that. may be i haven't used `searchkick` to that extent.

**Comment by ankane** [comment]
Hey @pushpalata-c, be sure to do a full reindex after the upgrade. If you're still having issues, please follow the instructions in the new [Contributing Guide](https://github.com/ankane/searchkick/blob/master/CONTRIBUTING.md).
