### ISSUE TITLE
Single Table Inheritance with namespace model bug

### ISSUE THREAD

**Issue by yuanping** [ankane/searchkick#1071]
Something wrong with model in namespace:

`
class Animal
  include Mongoid::Document
  field :name

  searchkick inheritance: true
end

class Dog < Animal
end

class Zoo::Cat < Animal
end

Dog.create name: 'pp'
Zoo::Cat.create name: 'mm'

Dog.search '*'  # is OK
Zoo::Cat.search '*' # no result
`

**Comment by ankane** [comment]
Hey @yuanping, I'm unable to reproduce. Can you follow the instructions to recreate in the new contributing guide? https://github.com/ankane/searchkick/blob/master/CONTRIBUTING.md

**Comment by yuanping** [comment]
Sorry, probabyly because I used the custom analyzer.
