### ISSUE TITLE
Partial reindex don't work for new fields

### ISSUE THREAD

**Issue by fidalgo** [ankane/searchkick#1072]
Hi!
After having the records indexed, I've created a new field on the `search_data` and after trying to reindex it with:

`ResearchReport.reindex(:industry_ids)`

I've got the following message:

```
{"count":500,"exception":["NoMethodError","undefined method `industry_ids' for #\u003cResearchReport:0x00000010328290\u003e"],"exception_object":"undefined method `industry_ids' for #\u003cResearchReport:0x00000010328290\u003e"}
```

But if try with an already existent field, it works.

If this is the expected behaviour, how to add the new field?

**Comment by sondnm** [comment]
@fidalgo can you post your `search_data` method.
This exception is raised because you didn't define a method named `industry_ids` and call it as an argument of `reindex`. Please refer to this document https://github.com/ankane/searchkick#partial-reindexing

**Comment by ankane** [comment]
Thanks @sondnm 👍

**Comment by fidalgo** [comment]
Thanks @sondnm , but I've solved it by adding a new method with the required fields and then do a merge on an existent method. This way I had the method `industry_ids` defined and indexed.
