### ISSUE TITLE
Custom Reindex background worker

### ISSUE THREAD

**Issue by Xosmond** [ankane/searchkick#1079]
Is there any way to change the background worker for reindex? I had to monkey patch and then create my worker because I needed to change the tenant.

Also you should specify on the README that the queue used is <app_name>_searchkick and not the default.

**Comment by ankane** [comment]
Hey @Xosmond, there isn't a way to change the background worker. Please submit a PR for any recommended updates to the readme.

**Comment by MrHubble** [comment]
@Xosmond if you're still looking into this you might be able to reindex conditionally to use your own custom background worker:

````rb
class Product < ApplicationRecord
  searchkick callbacks: false

  # add the callbacks manually
  after_commit :reindex, if: -> (model) { model.previous_changes.key?("name") }

  def reindex
    MyCustomJob.perform_later(self.id)
  end
end
````

https://github.com/ankane/searchkick#reference

**Comment by Xosmond** [comment]
Oh, I just redefined the worker search kick used. Thanks same.
