### ISSUE TITLE
Analyzers works faulty on some words

### ISSUE THREAD

**Issue by nsantiago2719** [ankane/searchkick#1084]
Hi,

I used searchkick for a while but I noticed that somethings wrong on some words like `university` and `engineering`. I tested using the code below:
```
MyModel.search_index.tokens("university", analyzer: "searchkick_index")
#=>["univers"]
MyModel.search_index.tokens("engineering", analyzer: "searchkick_index")
#=>["engin"]
``` 

I haven't solved the issue yet but would love to know how to help solving this issue.

**Comment by ankane** [comment]
Hey @nsantiago2719, this is due to stemming. What issues are you seeing because of it?

**Comment by nsantiago2719** [comment]
Hi @ankane, not really sure if I got your question well but I always got a 0 result on searches if entered those keywords. I think it does affect the way the search work. Which is really make sense to me now because it changes from `university` to `univers`.

**Comment by ankane** [comment]
Try it with `analyzer: "searchkick_search"` and it should match.

**Comment by nsantiago2719** [comment]
I tried using the analyzer `searchkick_search` but it's still giving me `univers`.

**Comment by nsantiago2719** [comment]
Hi @ankane, we tried some analyzers and the analyzer `searchkick_autocomplete_search` works well. My question is how does this affect the search in general? Does it have a big difference with other analyzers?

**Comment by ankane** [comment]
If the `searchkick_search` or `searchkick_search2` tokens match the `searchkick_index` tokens (as it does with `university` and `engineering`), then the search is a match and results are returned.

If you think you've found an issue, please follow the instructions for recreating in the Contributing Guide.

**Comment by nsantiago2719** [comment]
Will close this for now until I found the real issue why it's returning a result.
