### ISSUE TITLE
New feature: option to exclude search_import scope for partial indexing

### ISSUE THREAD

**Issue by leanhdaovn** [ankane/searchkick#1087]
When doing partial reindexing, sometimes we only need to update a single attribute (or a few of them). Then it doesn't make much sense to preload all the associations as in whole record reindex.

- Suggestion 1: add an option to exclude `search_import` scope.
- Suggestion 2: allow setting up custom scope for each partial search data

**Comment by ankane** [comment]
Hey @leanhdaovn, makes sense to me. What do you think of having a `scope` option on the reindex method that defaults to search_import?

```ruby
Product.reindex(:some_method, scope: :some_scope)
```

**Comment by leanhdaovn** [comment]
looks good @ankane 👍

**Comment by ankane** [comment]
Added on master. Thanks for the idea @leanhdaovn

**Comment by leanhdaovn** [comment]
Awesome! Thanks @ankane :)
