### ISSUE TITLE
Partial reindex don't work for a record with a Symbol method name

### ISSUE THREAD

**Issue by fidalgo** [ankane/searchkick#1095]
I've been playing around to migrate from 2.4 to 3.0.1 and faced the following issue:

If I try to do a Partial reindex on the model with 
`Model.reindex(:partial_data)` it works, but if I do:

`Model.find(1).reindex(:partial_data)` it will fail with the message:
```
ActiveJob::SerializationError: Unsupported argument type: Symbol
from /bundle/gems/activejob-5.1.4/lib/active_job/arguments.rb:71:in `serialize_argument'
```
Also if I use `where(id: 1)` it will work.

**Comment by ankane** [comment]
Hey @fidalgo, thanks for reporting 👍 Fixed on master.
