### ISSUE TITLE
Individual record reindex with async enabled

### ISSUE THREAD

**Issue by fidalgo** [ankane/searchkick#1101]
Hi,

I suspect that under the tests with async callbacks and where activejob jobs are inlined we should be able to update a record and get the callbacks executed right away, meaning we have the new information in ES.

I've found that, unless I'll do a a Full reindex with `Model.reindex` I cannot get the updated information. Also I've tried to get an failing test, but it's failing before the proof.

I've created a small PR with the updated tests, that I would expect to pass. I've used the Animal class, because it's setup to use async callbacks, i've confirmed that we have ActiveJob defined.

Here is the PR: https://github.com/fidalgo/searchkick/pull/1

**Comment by ankane** [comment]
Hey @fidalgo, your tests are searching the wrong model. Check the argument list of `assert_search`.

**Comment by fidalgo** [comment]
@ankane I've updated the tests in a separate commit, under the same PR, and after enabling the callbacks it fails.

**Comment by ankane** [comment]
It looks like you also made some additional changes, like `store_names` to `Animal.first.update(name: "animal c")`. You need to call `Animal.seach_index.refresh` afterwords, as outlined in the test documentation. Going to close as I don't have bandwidth to help w/ implementation issues.

**Comment by fidalgo** [comment]
@ankane sorry for bugging you, but even after adding the index refresh the test fails. I've updated the PR in case you want to take a look.

**Comment by ankane** [comment]
There are more mistakes in the test that's failing, but you should be able to figure it out with some debugging.
