### ISSUE TITLE
Unexpected Error when indexing Geospatial Searches

### ISSUE THREAD

**Issue by luke-hawk** [ankane/searchkick#1103]
First, thanks for the great work on searchkick – I really appreciate it! 

When indexing a Geospatial Search I keep on getting the same error and I can't reconstruct where it comes from nor can I find the error in any of the past issues. So I set up my model according like to the docs like:

```ruby
class Hotel < ApplicationRecord
  searchkick locations: [:location]

  def search_data
    attributes.merge location: {lat: latitude, lon: longitude}
  end
end
```
...but always keep on getting the same error when reindexing: 

```
Searchkick::Error: Cannot index a field with name: id
```
Any idea what might be the problem here? Cheers! :-)

**Comment by ankane** [comment]
Hey @luke-hawk, make sure the `search_data` method does not return an attributed name `id`.

**Comment by luke-hawk** [comment]
I don't really get it to be totally honest! With the `search_data` method as it is above, `attributes.merge` will merge the `Hotel` attributes with `location`. So when I do `Hotel.first.search_data` it will of course return the `id`(hotel_id) as the first attribute? 

P.S.: this is the first time I'm working with searchkick ;-)

**Comment by ankane** [comment]
Hey @luke-hawk, it looks like the examples are out of date. Fixed now. Sorry about that.

**Comment by cars10** [comment]
Why is the `id` field excluded though? Is this change related to elasticsearch 6?

**Comment by ankane** [comment]
Not related to ES6. The record id isn't taken from `search_data` (and has never been), but was silently ignored in earlier versions of Searchkick.
