### ISSUE TITLE
Search across multiple models

### ISSUE THREAD

**Issue by andreasantarl** [ankane/searchkick#1105]
Hi,

I'm working on a search feature with multiple filters that need to search multiple models. For example, I have College and State models that are joined. I'd like to be able to search the College model for a specific campus setting and search the State model for a specific state. I'd like the query to use an AND operator, instead of an OR, but so far, I can only find information on using an OR [in previous issues](https://github.com/ankane/searchkick/issues/904). Thus far, what I've come up with is:
`@results = College.search "*", index_name: [College, State], where: {_and: [{_type: "college", campus_setting: 21}, {_type: "state", state: "Massachusetts"}]}`

But this doesn't return any results, even though I can directly query my database and get results.  

In SQL, my query would look like: 
```
SELECT * FROM colleges c
INNER JOIN states s
ON c.state_id = s.id
WHERE c.campus_setting = 21 AND s.state = 'Massachusetts';
```

Is there another way I can write this search, or is this feature unavailable?

Thank you!

**Comment by ankane** [comment]
Hey @andreasantarl, please check out the Contributing Guide.
