### ISSUE TITLE
undefined method `record_data' with debug: true

### ISSUE THREAD

**Issue by fenec** [ankane/searchkick#1106]
When I run a query with debug `Model.search('test', debug: true)` I get `undefined method 'record' for #<Searchkick::Index:0x>`

this part here:
https://github.com/ankane/searchkick/blob/5667c9544a8f1c294cf1cdf4f22e2bb0d613737f/lib/searchkick/query.rb#L138

And indeed, there's no such method on `searchkick_index`

I use latest 3.0.2 version

**Comment by ankane** [comment]
Hey @fenec, thanks for reporting 👍 Fixed on master.
