### ISSUE TITLE
SearchKick with Pundit

### ISSUE THREAD

**Issue by stephendolan** [ankane/searchkick#1107]
Hi there,

Thank you for the fantastic library. I've been digging for a while now and just can't seem to determine the best way to search from an existing set of records. One very common example of this would be for users of the [Pundit](https://github.com/varvet/pundit) library, where you want to restrict the data that users can see.

Say I have a model named `User`, and my Pundit scopes it so that unless you are an admin user, you can only see users that are active. Is there a way to use SearchKick such that I don't have to define the `User.active` in both the Pundit scope **and** the SearchKick `scope_results` option? It's not too big of a deal for only one scope, but if I'm scoping out many more records for many different user roles this will get tedious and unmaintainable.

Ideally, I could write something more simple like `policy_scope(User).search('Stephen')`. I've read through issues like https://github.com/ankane/searchkick/issues/140, but it seems like the last comment regarding Pundit scopes wasn't really acknowledged.

**Comment by ankane** [comment]
Hey @stephendolan, you can apply the Pundit scope in scope_results to keep things DRY. There’s not a good way to make the example you gave work.

**Comment by stephendolan** [comment]
@ankane ,

Thanks for the very quick response! Is there any way to get an `ActiveRecord::Relation` from SearchKick instead of just an array of records?

I keep coming across StackOverflow posts like [this](https://stackoverflow.com/questions/26002833/rails-elasticsearch-named-scope-search) that reference both a `records` and `results` method for a SearchKick search, but `records` seems not to be defined any more.

**Comment by ankane** [comment]
Hey @stephendolan, Searchkick doesn't provide a way to do this - `scope_results` is the closest thing. You can do what the `records` method was doing by first querying Elasticsearch to get the record ids that match the search term and then passing them to ActiveRecord.

**Comment by Shkrt** [comment]
@stephendolan Pundit is not coupled to the database persistense layer, so we can easily use it with Searchkick. For example:
```ruby
where_hash = { published: true }
where_hash = Admin::PostPolicy::ElasticScope.new(@user, where_hash).resolve
Post.search(@query,
                    fields: ['title^100', 'description'],
                    select: [:id, :title, :rubric, :text],
                    where: where_hash,
                    load: :false)
```

and in the Pundit policy we should just apply filters according to our policies:

```ruby
class Admin::PostPolicy::ElasticScope
  def initialize(user, scope)
    @user = user
    @scope = scope
  end

  def resolve
    if @user.has_role? :admin
      scope.merge(type: { not: 'Opinion' })
    elsif user.has_any_role?(:releasing_editor, :editor)
      scope.merge(engine_id: user.engine_ids, type: { not: 'Opinion' })
    elsif user.has_role?(:commenter)
      scope.merge(engine_id: user.engine_ids, type: 'Opinion')
    end
  end
end
```

Obviously, `merge` in the above example is not ActiveRecord merge, but plain hash merge, thus we just modifying `where_hash` variable.

**Comment by stan74fr** [comment]
Hi Guys. How could we make a request for ways to have pundit compatible with searchkick? 
Like @stephendolan , I am struggling (even if i know that he found some workarounds). Currently, I am retrieving nicely my scope with pundit policy_scope(Post) but everything is broken when I am doing policy_scope(Post).search(query)   ... i get back all then out-of-scope articles..
