### ISSUE TITLE
Searchkick advanced search pagination

### ISSUE THREAD

**Issue by lucasmpereira** [ankane/searchkick#1108]
Hi, 

Someone know how to solve the pagination question with a custom search? According to the documentation, when you use a custom query, searchkick will ignore all the other options but at least the pagination should work for both searchs IMO.

**Comment by lucasmpereira** [comment]
Great 

@ankane do you have some idea when this will be released with the gem? Sorry to asking this but will help a lot with some projects I'm working right now.

**Comment by lucasmpereira** [comment]
Thanks @ankane and sorry for not be able to help solve this.

**Comment by ankane** [comment]
Merged to master.

**Comment by dongtong** [comment]
@ankane Hi, I installed latest master branch, but it does not work, Could you verfiy it?

```
Loading development environment (Rails 5.1.4)
irb(main):001:0> result = Customer.search(body: {"query":{"bool":{"must":[{"match":{"name":{"query":"OLSEN"}}}]}}}, page: 1, per_page: 20)
ArgumentError: Options incompatible with body option: page, per_page
```

**Comment by andrewyoo** [comment]
@dongtong I just tried it out and it works for me.  Check you `Gemfile.lock` and make sure you got the lastest revision.

````
GIT
  remote: https://github.com/ankane/searchkick.git
  revision: 1ac07f945a40fad850d7a96e89aba930d6c28bb8
  specs:
    searchkick (3.0.2)
      activemodel (>= 4.2)
      elasticsearch (>= 5)
      hashie
````
