### ISSUE TITLE
Incorrect Ordering by name or price results

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [ankane/searchkick#1109]
Hi,
I'm using searchkick on Rails app, and everything is working fine except ordering by name & price, i always get incorrect results for example products starts with B come before A ....

here's my search_data
```
json = {
      id: id,
      name: name,
      description: description,
      active: available?,
    }
```

and an example 

```
Spree::Product.search(
      '*',
      fields: [:name],
      load: false,
      order: {name: :desc},
      where: { active: true},
    )
```

my name & price mapping is 

```
"name"=>
          {"type"=>"keyword",
           "fields"=>{"analyzed"=>{"type"=>"text", "analyzer"=>"searchkick_index"}, "word_start"=>{"type"=>"text", "analyzer"=>"searchkick_word_start_index"}},
           "ignore_above"=>30000},
         "price"=>{"type"=>"float"}
```

any help about how to fix this issue ?!
Thanks!

**Comment by ankane** [comment]
Hey @AhmedAliIbrahim, please follow the Contributing Guide.

**Comment by AhmedAliIbrahim** [comment]
I've upgraded to V3 but now i can't find result.records ! so how can i get the result ?!
