### ISSUE TITLE
How to get rid of this error in production which is happening only some of the times?

### ISSUE THREAD

**Issue by Vishnu-Prakash** [ankane/searchkick#1111]
`A Searchkick::InvalidQueryError occurred in search#index:

[400] {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[match] analyzer [searchkick_search] not found"`

**Comment by ankane** [comment]
Hey @Vishnu-Prakash, this error happens when you query an index before running `Model.reindex`. I’d investigate how you’re creating indexes, but don’t think this is an issue with Searchkick.
