### ISSUE TITLE
Searchkick 3.0.2 parallel reindexing issue with async: {wait: true}

### ISSUE THREAD

**Issue by yataghan** [ankane/searchkick#1112]
Hello to everyone!
I am experimenting with Parallel reindexing described in this section https://github.com/ankane/searchkick#parallel-reindexing

and came across with an issue when next code is interpreting
```
Searchkick.redis = Redis.new
MyModel.reindex(async: {wait: true})
```
with an error 

> Jobs queued. Waiting...
> NoMethodError: private method `batches_left' called for #<Searchkick::BulkIndexer:0x007feebfc145c0>

and technically there is a code line
https://github.com/ankane/searchkick/blob/0fed3037e9d6b58fb11bc5075898741784696d91/lib/searchkick/index.rb#L305

which call method `Searchkick.reindex_status` and then
https://github.com/ankane/searchkick/blob/17c9adae455fb600f847351b0f4ab15d87ad1092/lib/searchkick.rb#L171
we can see `batches_left ` method invocation and then https://github.com/ankane/searchkick/blob/0fed3037e9d6b58fb11bc5075898741784696d91/lib/searchkick/index.rb#L212

here we can see the problem in this method
https://github.com/ankane/searchkick/blob/master/lib/searchkick/bulk_indexer.rb#L159
which is private. 

Does somebody know something about it? 

Thanks in advance.

**Comment by ankane** [comment]
Hey @yataghan, thanks for reporting 👍 Fixed on master.
