### ISSUE TITLE
give access to flags for regexp queries

### ISSUE THREAD

**Issue by xxx** [ankane/searchkick#1117]
Hi,

We ran into an issue today due to Ruby and Lucene having different flavors of regular expressions.
Lucene has a few extra characters that it can recognize (`# @ & < >  ~`), which it does by default. This can cause surprising behavior, because these characters makes it through Ruby's `Regexp.escape` untouched, but then still have their special behavior in the search itself.

The following test case shows what I mean.

```ruby
  def test_special_regexp
    store_names ["Product <A>", "Item <B>"]
    assert_search "*", ["Product <A>"], where: {name: {regexp: "Pro.+<"}}
  end
```
[The recognition of these characters can be controlled](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#_optional_operators), but that config is not currently exposed via Searchkick.

Exposing `flags` seems to be the clearest way to handle this one, and wouldn't require any API breakage.

**Comment by ankane** [comment]
Hey @xxx, thanks for reporting 👍 I think it makes sense to disable the optional operators when a Ruby regex is passed. We could also have `regexp` accept a hash with `value` and `flags` keys, although not sure this would be used much. In general, regexes with Elasticsearch should be avoided, as they are very inefficient compared to token searching.

**Comment by xxx** [comment]
@ankane either works for me. thanks!
