### ISSUE TITLE
Deprecation warning on Elasticsearch 6.2.3

### ISSUE THREAD

**Issue by jbwl** [ankane/searchkick#1119]
I'd like to report two deprecation warnings for ES 6.2.3

First:
`[WARN ][o.e.d.a.c.NGramTokenFilterFactory] Deprecated big difference between max_gram and min_gram in NGram Tokenizer,expected difference must be less than or equal to: [1]`

This warning is caused by a difference between max and min > 1. If a higher difference is indeed wanted, there is a new setting to allow it (and get rid of the deprecation warning):

>The index level setting index.max_ngram_diff controls the maximum allowed difference between max_gram and min_gram. 

From: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenizer.html

Second:
`[WARN ][o.e.d.i.a.ShingleTokenFilterFactory] Deprecated big difference between maxShingleSize and minShingleSize in Shingle TokenFilter,expected difference must be less than or equal to: [3]`

Similar to the first one, there is a new index level setting to allow differences higher than 3 if needed.

Explained here: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-shingle-tokenfilter.html

**Comment by ankane** [comment]
Awesome, thanks @jbwl for the detailed report and solutions 💯

**Comment by jbwl** [comment]
Thanks for the quick fix!
