### ISSUE TITLE
Boolean aggregation returning unusable search condition

### ISSUE THREAD

**Issue by bbugh** [ankane/searchkick#1120]
Firstly, thank you for this exceptional gem. We switched from sunspot recently and this is vastly better designed, and also way better than the official elasticsearch gem. Cheers to you! 🍻

We've run into an issue with boolean aggregations. 

```ruby
> Model.filter.aggregations['boolean_column']
=> {"doc_count_error_upper_bound"=>0,
 "sum_other_doc_count"=>0,
 "buckets"=>[{"key"=>0, "key_as_string"=>"false", "doc_count"=>2725}, 
             {"key"=>1, "key_as_string"=>"true", "doc_count"=>516}]}
```

^ the important takeaway here is that the aggregate is returning `0` for "false" and `1` for "true". At this point, we render all of the aggregations to the search page, not caring about type. That's a-ok. When the user clicks on one of the boolean aggregations, that condition is added to the next search query. However, when trying to do a condition search, like so:

```ruby
> Model.search('*', where: { boolean_column: '0' }) # comes directly from the aggregate key value
=> ... "caused_by":{"type":"illegal_argument_exception","reason":"Can't parse boolean value [0], 
expected [true] or [false]"}}}]},"status":400}
```

^ We get this error. 

So the aggregate value we're receiving from searchkick is invalid to use as a search.

**Comment by ankane** [comment]
Hey @bbugh, it looks like you should use `key_as_string` instead. Searchkick doesn't do any transformation to bucket values.

**Comment by bbugh** [comment]
Oh, dang. I'd been looking at the aggregates for so long I missed the `key_as_string`, and there it is in my own example code. 😊Thanks!
