### ISSUE TITLE
[match] analyzer [searchkick_word_search] not found

### ISSUE THREAD

**Issue by thrawn** [ankane/searchkick#1127]
what typically causes this type of error? i find similar problems but no root cause answers or solutions. latest searchkick with elasticsearch 6.0
thank you

```
MESSAGE    [400] {
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "[match] analyzer [searchkick_word_search] not found",
        "index_uuid": "k5iZHXV4RS2-UaHv4-Y0-g",
        "index": "index_20180414042538201"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "index_20180414042538201",
        "node": "p-CbfFaOSEmEnxf0z2ndnQ",
        "reason": {
          "type": "query_shard_exception",
          "reason": "[match] analyzer [searchkick_word_search] not found",
          "index_uuid": "k5iZHXV4RS2-UaHv4-Y0-g",
          "index": "index_20180414042538201"
        }
      }
    ]
  },
  "status": 400
}
```

**Comment by ankane** [comment]
Hey @thrawn, you need to do a full reindex with `Model.reindex`. I've updated the error message to be friendlier.

**Comment by thrawn** [comment]
hi @ankane 

reindexing does fix this, but is there an issue with using async/latest searchkick/elasticsearch 6.0? previously, the manual reindexing wasn't necessary but now that's the only way to stop the error from happening...

**Comment by ankane** [comment]
Please use the gist in the Contributing Guide if you think there's an issue.
