### ISSUE TITLE
[Idea] Freely select the analyzer

### ISSUE THREAD

**Issue by ogidow** [ankane/searchkick#1128]
Hi, @ankane

Searchkick is following `searchkick_search` `searchkick_search2` `searchkick_autocomplete_search` `searchkick_word_search` analyzer.
but, I would like to use more analyzers, When trying to realize complicated searches.

So, will you be able to use the analyzer according to the field name in the search.

For example
when searching on the `hoge.searchkick_other_search` field, searchkick uses searchkick_other_search analyzer on searching

thank you

**Comment by ankane** [comment]
Hey @ogidow, thanks for the suggestion 👍 You can accomplish this with a custom mapping and custom searching. Are there specific analyzers you'd like to add?

**Comment by ogidow** [comment]
Thank you for your reply
I know what can be accomplish by that method.

I would like to use more analyzer on default searching
because,  I already searched using `searchkick_search` `searchkick_search2` `searchkick_autocomplete_search` `searchkick_word_search` with dis_max query.
And I want to add another custom analyzer to that query

so, I want to change [this line](https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L331) to 
```rb
analyzer = field =~ /\.word_(start|middle|end)\z/ ? "searchkick_word_search" : "searchkick_#{field.split(".").last}_search"
```

If this change is difficult, I use custom searching.

thank you

**Comment by ankane** [comment]
Hey @ogidow, I think you should use custom searching for this.
