### ISSUE TITLE
Issue with edit_distance

### ISSUE THREAD

**Issue by Vishnu-Prakash** [ankane/searchkick#1130]
Hi,

For this query,
`Product.search('material', fields: [:name], misspellings: { edit_distance: 1 })`
It contains results matching 'maternity'. The Levenshtein edit distance is 3 between the words 'material' and 'maternity' but is showing up in results.

Thanks!

**Comment by ankane** [comment]
Hey @Vishnu-Prakash, they have an edit distance of 1 after stemming is applied.

**Comment by Vishnu-Prakash** [comment]
I'd appreciate if you'd tell me the way to disable stemming

**Comment by ankane** [comment]
#803
