### ISSUE TITLE
process_queue_job - ArgumentError

### ISSUE THREAD

**Issue by Bpless** [ankane/searchkick#1131]
I'm on 2.4.0. The redis queue of instance IDs is being set correctly by the queue callback. However, when I run

> Searchkick::ProcessQueueJob.perform_later(class_name: "Product")

The delayed job throws an error:

```
ArgumentError: wrong number of arguments (1 for 0)
	from /Users/myuser/.rvm/gems/ruby-2.2.1/gems/searchkick-2.4.0/lib/searchkick/process_queue_job.rb:5:in `perform'

```

I believe that I've set the adapter for DelayedJob correctly (async callbacks do work).

> Searchkick::ReindexV2Job.queue_adapter = :delayed_job

Am I missing something obvious here?  Is this due to the fact that ProcessQueueJob inherits from ActiveJob::Base and is not compatible with the DelayedJob adapter?

**Comment by ankane** [comment]
Hey @Bpless, only the latest version of Searchkick is supported. Please use the gist in the Contributing Guide to report issues.
