### ISSUE TITLE
Add sync as an option to the reindex mode

### ISSUE THREAD

**Issue by fidalgo** [ankane/searchkick#1133]
Hi!
Currently the reindex modes are: true, nil, :async, :queue
https://github.com/ankane/searchkick/blob/98f8b77ff9cd4793a409e19747539571f297fe01/lib/searchkick/record_indexer.rb#L11

When we want to have a _sync_ reindex, we need to write this `Model.reindex(mode: true)` which is not a best way to describe we want to do a reindex synchronously.

My suggestion is to add an `:sync` keyword to flag it.

**Comment by ankane** [comment]
Hey @fidalgo, great idea 👍 I added `:inline` as an alias for `true` (consistent with ActiveJob's naming of `:inline` and `:async` adapters).
