### ISSUE TITLE
Cannot exclude ids in similar search

### ISSUE THREAD

**Issue by jrgns** [ankane/searchkick#1139]
There's a [TODO item](https://github.com/ankane/searchkick/blob/9ddaf36992088373374f995e2eda32e8625028a6/lib/searchkick/index.rb#L162) to do a deep merge on the options for the similar search:

```ruby
      # TODO deep merge method
      options[:where] ||= {}
      options[:where][:_id] ||= {}
      options[:where][:_id][:not] = record.id.to_s
      options[:per_page] ||= 10
      options[:similar] = true
```

This means developers can't use the `{ where: { _id: { not: [] } } }` filter, since it always revers back to only excluding the current document:

```ruby
product.similar(fields: [:description], where: { _id: { not: [1, 2, 3] } })
```
The above code will result in the following filter:

```json
filter":[{"bool":{"must_not":{"term":{"_id":"4"}}}}]
```

**Comment by ankane** [comment]
Hey @jrgns, thanks for reporting 👍 Fixed on master.

**Comment by jrgns** [comment]
@ankane Awesome, thanx!
