### ISSUE TITLE
Use set over list on ReindexQueue#push

### ISSUE THREAD

**Issue by dvmonroe** [ankane/searchkick#1141]
First, thanks for all your work @ankane ❤️ 

Curious what you're thoughts were behind storing record ids in a list vs a set at: https://github.com/ankane/searchkick/blob/17c9adae455fb600f847351b0f4ab15d87ad1092/lib/searchkick/reindex_queue.rb#L12

Time complexity? Something else?

It threw me a little when I used the length method like so:

```ruby
User.search_index.reindex_queue.length
```
And it was greater than the number of actual User records that had been updated in our db and eventually reindexed (due to a few records being updated twice within an x amount of time).

Is this worth a PR?

**Comment by dvmonroe** [comment]
Thanks @ankane. I gotcha. Perhaps I'm pulling at straws but the api seems less than ideal given a scenario like so:

```ruby
# app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id 
#  likes

Post < ApplicationRecord
  # unrealistic batch size for demo purposes
  searchkick callbacks: :queue, batch_size: 5
end
```

Suppose a Post record gets updated everytime a user hits "like" via the UI (replicated in pry):
```pry
> (0..50).each { |i| Post.first.update(likes: i) };
> Post.search_index.reindex_queue.length
50
> $redis.lrange("searchkick:reindex_queue:posts", 0, 4)
["1","1","1","1","1"] # these are the ids that will rpop on Searchkick::ReindexQueue#reserve
```

```pry
lib/searchkick/process_batch_job.rb#perform
> Searchkick.load_records(Post, ["1","1","1","1","1"]).length
1
```
**Main isssues**
1)  I'd want a cron job to handle the reindex once I have x number of unique post records in the queue but the current searchkick api wouldn't tell me that

2) In this scenario, `Searchkick::ProcessQueueJob.perform_later(class_name: "Post")` would reindex my first Post record 10 times. But the searialized JSON of the Post record wouldn't be any different in each of those elastic api _bulk calls.

**Potential solution**

Only queueing the post once would appear to be more performant for the ES writes (via a set (sadd) and/or ordered set (zadd))

Perhaps, I'm missing the benefit of being able to queue the same record multiple times and/or I'm making mountains out of molehills i.e this would see very little/no performance benefits on the ES cluster in which case - feel free to close!

Thanks again.

**Comment by ankane** [comment]
Sets don't preserve the ordering (no longer a queue), and ordered sets are less efficient to add - `O(log(N))` vs `O(1)`. If the same id shows up multiple times in the same batch, the record is only reindexed once. Overall, I think the approach Searchkick currently uses is the best option (a performant queue, with potential for duplicates).
