### ISSUE TITLE
Geospatial Searches Query take within value from database

### ISSUE THREAD

**Issue by vishalTatvaSoft** [ankane/searchkick#1142]
Hello

I used below query for geospatial search in my appliaction/
`Store.search("*", fields: [:name], where: ({location: {near: {lat: 37.7775581, lon: -122.4317452}, within: 200mi"}}))`

Now i want to take within value from Database like i have one table in stores, and there is one field delivery_within . i want to take within value from that column, it will be multiple

I used geocoder gem in my application and to overcome this issue i need to define column_name instead of any fix value like below 

`Store.near([37.7775581, -122.4317452], :delivery_within, :order => false)`

How can i do this query in searchkick ? i checked wiki but couldn't find out much about geospatial query.

Thanks!

**Comment by ankane** [comment]
Hey @vishalTatvaSoft, please check out the Contributing Guide.

**Comment by vishalTatvaSoft** [comment]
@ankane Update my issue, can you please take look ?
