### ISSUE TITLE
Problem boosting "exact" matches

### ISSUE THREAD

**Issue by TKB21** [ankane/searchkick#1145]
I have a scenario where I would like to search by a restaurant dish's tag names and the name of the dish as it appears on the menu. I'd like the tag names to take precedence overall.  Right now I only want to match the exact name of the tag. So "short ribs" results should show over "ribs" results. Strangely this setup is not working:

```
Dish.search('ribs', {
  fields: [{'tag_names^10': :exact}, :name],
  where: {
    location: {
    near: { lat: 37.7882062, lon: -122.4353033 },
    within: "5mi"
    }
  },
  order: {
    _geo_distance: {
      location: "37.7882062, -122.4353033", 
      order: "asc",
      unit: "mi"
    }
  }
})
```

With the above, dishes with the tag _short ribs_ still show over dishes with _ribs_ tags. I checked the docs but it appears the `boost_by` pair only works with numerical values. I should also note that by removing the `:name` field entirely the search results show correctly. Is there something I'm missing here?

**Comment by ankane** [comment]
Hey @TKB21, boosting effects the search score, but you're ordering by distance instead of by score (default). Use the `explain: true` option to see why results are ordered a certain way.

**Comment by TKB21** [comment]
Thanks for the clarification @ankane. With this in mind would I still be able to incorporate a dish's wilson score in conjunction with proximity? Just trying to wrap my head around how sorting works with this gem.
