### ISSUE TITLE
Idea - Can we do geospatial searches query take `within` value from database

### ISSUE THREAD

**Issue by vishalTatvaSoft** [ankane/searchkick#1146]
Hello

I used below query for geospatial search in my appliaction/
`Store.search("*", fields: [:name], where: ({location: {near: {lat: 37.7775581, lon: -122.4317452}, within: 200mi"}}))`

Now i want to take within value from Database like i have one table in stores, and there is one field delivery_within . i want to take within value from that column, it will be multiple

I used geocoder gem in my application and to overcome this issue i need to define column_name instead of any fix value like below 

`Store.near([37.7775581, -122.4317452], :delivery_within, :order => false)`

I checked wiki but couldn't find out much about geospatial query. May be this feature don't provided by searchkick ?  Can we do geospatial query in this way ?

Thanks!

**Comment by ankane** [comment]
Dup of #1142
