### ISSUE TITLE
Relevance is broken and inconsistency of results

### ISSUE THREAD

**Issue by Vishnu-Prakash** [ankane/searchkick#1147]
Hi,

When I run the same search query continuously, the sorting order is changing and some results are not appearing sometimes and there is also duplication among results sometimes. The sort is based on the score given by searchkick.

After doing significant research, I've got to know that I need to add `?search_type=dfs_query_then_fetch` to search requests. I'll appreciate if you could tell me how to do that using searchkick.

I am pleased to give more specific details if I missed anything. 

Thanks!

**Comment by ankane** [comment]
Try searching the readme for `dfs_query_then_fetch`.
