### ISSUE TITLE
Force Reindex with Record Ids instead of Min/Max

### ISSUE THREAD

**Issue by earoberson** [ankane/searchkick#1151]
Hey @ankane 

I'm trying to reindex a model that has a non-sequential primary key `id`, but the primary key _is_ numeric.

I'm looking at: https://github.com/ankane/searchkick/commit/58af0f694baeca9e2e6b28a758c950894dc9078d

The issue I'm facing is that the number of jobs created when async reindexing becomes extremely large and often doesn't cover more than a handful of actual records since a range of 1000 sequential ints could potentially cover only 2-3 ids. 

Is there a way to force creating a reindex job with record_ids instead of a min and max id?

Right now, the hack is to raise an ActiveRecord::StatementInvalid error in `minimum` and everything works well.

**Comment by ankane** [comment]
Closing so discussion is only in one place (PR)
