### ISSUE TITLE
Multiple search terms with more than one word each

### ISSUE THREAD

**Issue by luke-hawk** [ankane/searchkick#1153]
Hi @ankane,

is there any way to search with multiple terms within the same index? I'm looking to do something as the following: 

`FruitCake.search(["apple pie", "carrot cake"], operator: "or", fields: [:name], match: :text_start)`

So basically, I have search terms which consist of multiple words (_AND_ operator) and I would like to be able to use an _OR_ operator to combine those terms. Also, I need those terms to partially match the searched field, so that "apple pie" matches "apple pie with whipped cream".

I was able to get a working solution using `multi_search` but since I need to have up to 12 search terms to deliver **one total result** it seems quite hacky as it will run 12 queries.  

Is there a way to **either** solve my issue with an _OR_ operator or to get a total result from `multi_search` with only one query?

**Comment by ankane** [comment]
Hey @luke-hawk, you'll need to use write a custom query to do this right now. See https://github.com/ankane/searchkick#advanced-search
