### ISSUE TITLE
STI inheritance problem

### ISSUE THREAD

**Issue by afunction** [ankane/searchkick#1155]
I have 3 activerecord models

```ruby
class Orderable < ActiveRecord::Base
   has_soft_deletion default_scope: true
   searchkick(inheritance: true, callbacks: async)
end

class Cart < Orderable
   default_scope { ...... }
end

def Order < Orderable
      default_scope { ...... }
end
```

In my case, when user purchase `Cart` will transfer to `Order` 

```ruby
def cart_to_order(cart)
   Cart.transaction do
      # do something
      cart.update!(type: 'Order')
   end
end
```

Then Searchkick will send a job to execute reindex job, example below:

```ruby
Searchkick::ReindexV2Job.perform_later('Cart', 123, nil)
```

At this time the cart had been transfer to `Order` so `model.unscoped.find(id)` will throw `ActiveRecord::RecordNotFound` then delete index.
```ruby
def perform(klass, id, method_name = nil)
      model = klass.constantize
      record =
        begin
          if model.respond_to?(:unscoped)
            model.unscoped.find(id)
          else
            model.find(id)
          end
        rescue => e
          # check by name rather than rescue directly so we don't need
          # to determine which classes are defined
          raise e unless RECORD_NOT_FOUND_CLASSES.include?(e.class.name)
          nil
        end

      unless record
        record = model.new
        record.id = id
      end

      RecordIndexer.new(record).reindex(method_name, mode: :inline)
end
```

I tried to solve this problem in my project, add reindex myself.

```ruby
def cart_to_order(cart)
   Cart.transaction do
      # do something
      cart.update!(type: 'Order')
   end
   Order.find(cart.id).reindex(async: true)
end
```

so it will send twice reindex job to sidekiq

```ruby
Searchkick::ReindexV2Job.perform_later('Order', 123, nil)
Searchkick::ReindexV2Job.perform_later('Cart', 123, nil)
```

then I found out other problem,  sidekiq is too fast, if sidekiq execute `Order reindex`  before  `Cart reindex` finally the index will disappear. 

I think `ReindexV2Job` should use `model.superclass`  to query. or maybe you will have better solutions.

Sorry, I’m not good at English.

**Comment by ankane** [comment]
Hey @afunction, unfortunately, I don't understand the issue, or how #1158 fixes it. Please use the gist in the Contributing Guide to recreate.

**Comment by MrHubble** [comment]
@afunction I also don't completely understand the issue but a few thoughts:

>At this time the cart had been transfer to Order so model.unscoped.find(id) will throw ActiveRecord::RecordNotFound then delete index.

If you're removing the data from your `cart` and adding it to your `order` then wouldn't the correct action to delete the `cart` index as you no longer want users to search for a `cart` that does not exist?

Also, if you're going to try to reindex yourself then I think you should turn off automatic syncing. ie: `searchkick callbacks: false`

**Comment by ankane** [comment]
Cleaning up stale issues
