### ISSUE TITLE
Async wait: true never finishes (number of batches does never decrease)

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#1159]
Hi Ankane,

Using Model.reindex(async: {wait: true}), I get a countdown in my console letting me know the # of batches remaining.

The problem is the batches # never goes down. I'm watching the jobs get processed in Sidekiq and they all finish fine, but the # of batches stays the same indefinitelly. 

I first encountered this in production, and I then managed to reproduce it in development as well. 

I'm on 2.5.0, don't know if it's still supported and/or what info you might need to debug this.

Thanks again for this nice gem!

**Comment by ankane** [comment]
Hey @feliperaul, 2.5.0 is no longer supported. I'd try upgrading to the latest version to see if that fixes it.

**Comment by feliperaul** [comment]
@ankane thanks, will do as soon as I can and re-open!
