### ISSUE TITLE
Chards and replicas

### ISSUE THREAD

**Issue by jujudellago** [ankane/searchkick#1164]
Hi,

I am upgrading some search features previously built on top of the basic elasticsearch-model and elasticsearch-rails gems.

So far I am able to replicate all the search features previously developped, but one thing I don't get is the chards and replicas settings, that doesn't seem to have configuration options.

The only issues I found related to the topic were about re-indexing problems
for example https://github.com/ankane/searchkick/issues/1074

I feel like I am missing something..... is searchkick always using the default 5 chard 1 replicas in all situations ? 

thanks

**Comment by ankane** [comment]
Hey @jujudellago, you can set any of the Elasticsearch settings with:

```ruby
class Product < ApplicationRecord
  searchkick settings: {number_of_shards: 3}
end
```
