### ISSUE TITLE
should_index? question/comments

### ISSUE THREAD

**Issue by michelson** [ankane/searchkick#1167]
Hi @ankane 

I'm integrating this awesomeness and I found that `should_index?` will remove the indexed record. This seems not quite right. I see that this is made by design but the `should_index?` naming does not reflects that the indexed record will be destroyed. I think that `should_index?` method should be used to determine if the record should be indexed or not, but not to be removed.

meanwhile I will use this to remove the index when needed 😄 

does  this make sense to you ?

best!

**Comment by ankane** [comment]
Hey @michelson, the `should_index?` method indicates whether or not a record should exist in the search index, which is why it removes records when `should_index?` is `false`. Can you explain your use case more?

**Comment by michelson** [comment]
Hi @ankane , thanks for your reply.
well , my use case is a model with some virtual attributes that respond to the activerecord `changes` method. In my previous implementation I've used a method that checks the `changes` or `saved_changes` method and triggers a record reindex only if the attributes from a "whitelist" are changed. Sometimes when there are not whitelisted attributes on the `changed` then the reindex is skipped.
Also I've overload the `delete!` method in order to handle soft deletes. Then on a `after_delete` the record should be reindexed too.

Something in the line of:

```ruby

   after_commit ->{self.handle_index_on_create }, on: :create
   after_commit ->{ index_with_fields_check }, on: :update

  def handle_index_on_create
    if should_reindex_inline? 
      reindex_async 
    else
      reindex(mode: :inline)
    end
  end

  def index_with_fields_check
    if (WHITELIST_INDEX_COLUMNS & saved_changes.keys).any?
      deleted? ? reindex(mode: :inline) : reindex_async 
    end

  end

```

**Comment by ankane** [comment]
I'm not sure I fully understand how the `should_index? method ties into the example, but if you're customizing the reindexing and `should_index?` is interfering with what you want, you can always avoid it.

**Comment by michelson** [comment]
indeed, it's not used at all
