### ISSUE TITLE
Cannot order by integer

### ISSUE THREAD

**Issue by pawneetdev** [ankane/searchkick#1168]
Elasticsearch version 2.3.0

I am unable to sort by integer field. I have mapped my field as integer as following:

```
searchkick merge_mappings: true, mappings: {
    model_name: {
        properties: {
            application_id: {type: "integer"}
        }
    }
}
```

When I try to run the following query, it does not return sorted values.

```
Model.search("*", :order => {"application_id" => :desc}, limit: 10, load: false)
```

**Also, I have removed application_id from filterable as I was getting 'ignore_above" error (Refer: [Issue #870](https://github.com/ankane/searchkick/issues/870))**

**Comment by ankane** [comment]
Hey @pawneetdev, custom mappings can interfere with Searchkick functionality, so I won't be able to help debug issues with them. If it's an issue without custom mapping, please use the gist in the contributing guide to reproduce.
