### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [ankane/searchkick#1171]
Hi @ankane .. I'm graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. Mirza zulfan

**Comment by ankane** [comment]
Hey @mirzazulfan, I really appreciate the offer ❤️ but don't feel the need to add logos to my projects right now.

**Comment by mirzazulfan** [comment]
Thank for your response sir..!!
