### ISSUE TITLE
Cache last reindexed record id in redis to make resume more efficient

### ISSUE THREAD

**Issue by leanhdaovn** [ankane/searchkick#1172]
At the moment, we can resume the interrupted reindex process. However, it uses `total_docs` as a relative base to compare the record id against. When the ids in DB are not continuous or not start from 1, this approach would be very inefficient.

Suggestion: cache the last indexed id in redis and pick up right at that point when resuming reindex.

**Comment by ankane** [comment]
Hey @leanhdaovn, thanks for the suggestion. While the `total_docs` approach may cause some records to be reindexed again, it doesn't require any external dependencies like Redis. I think it makes sense to keep it simple.
