### ISSUE TITLE
.records method is missing on Searchkick 3.0

### ISSUE THREAD

**Issue by michelson** [ankane/searchkick#1173]
Hi @ankane , how are you

I've upgraded searchkick version from 2.5 to 3.1.0. I've found that the `.records` method from Serchkick::Results is missing in this version. This was intended  ? right now the getter for activerecord from the results is the `.results` but it only returns an Array of AR records but no a `ActiveRecord_Relation`. 
it would be nice to have this method back. If that is not possible what do you recommend to build active relation from searchkick repsonse ? 

I'm using something like this right now:

```ruby

current_user.posts.visible.where(id: searchkick_response.results.map(&:id))

```
Thanks!

**Comment by ankane** [comment]
Hey @michelson, I'm good, thanks. This was an experimental method that was purposefully removed in Searchkick 3. The method didn't maintain the ordering of the records, which confused people. The pattern you're using above is how I would do it.

**Comment by michelson** [comment]
i remember seen the same issue on elasticsearch-model , one way to handle de correct order of records was implementing an scope for that. we are using this in out implementation:

```ruby

    def find_ordered(ids, id_name)
      sanitized_id_string = ids.map {|id| connection.quote(id)}.join(",")
      return self if ids.blank?
      where("#{id_name}"=> ids).order("FIELD(#{id_name}, #{sanitized_id_string})")
    end

```

**Comment by ankane** [comment]
There are ways around it, but 99% of the time, I'd recommend making sure all the data you need to query is in Elasticsearch. Someone is welcome to write another gem for this functionality, but it's not a pattern I'll endorse right now.

**Comment by michelson** [comment]
100% agree, but in any case it would be nice that results returns a ActiveRelation in order to not query database twice like the example above. In that case using `results.to_a` will return collection as array

**Comment by ankane** [comment]
You'll want to use `load: false` in your search query to prevent it from hitting the database twice.

```ruby
results = Post.search("ruby", load: false)
current_user.posts.visible.where(id: results.map(&:id))
```

However, I recommend doing this instead:

```ruby
Post.search("ruby", where: {user_id: current_user.id, visible: true})
```

Results are ordered (and paginated if you do that) correctly.
