### ISSUE TITLE
Deprecated docs for advanced search?

### ISSUE THREAD

**Issue by brunoocasali** [ankane/searchkick#1180]
Hi, thanks for the awesome library!

To use the advanced search is not a requirement to setup a custom mapping right? Because I've just reindexed and tried a advanced query:

```rb
[6] pry(#<Search::Base>)> Product.search body: { match: { name: "milk" } }

Searchkick::InvalidQueryError: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [match].","line":1,"col":10}],"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [match].","line":1,"col":10},"status":400}
from /usr/local/bundle/gems/searchkick-3.1.0/lib/searchkick/query.rb:195:in `handle_error'
[7] pry(#<Search::Base>)>
```
Then I think the docs are deprecated?

https://github.com/ankane/searchkick#advanced-search (following this topic).

Thanks!

**Comment by ankane** [comment]
Hey @brunoocasali, I fixed the example (was missing `query` part). What do you mean by deprecated?

**Comment by brunoocasali** [comment]
No worries, it's because I executed the example and it doesn't work, so I thought is about something like that! 

Thanks for the quickly response @ankane ! 💃

**Comment by ankane** [comment]
Thanks for letting me know it was broken :)
