### ISSUE TITLE
Pass `suggest: true` to the search method for suggestions

### ISSUE THREAD

**Issue by liang3404814** [ankane/searchkick#1181]
Hi, I'm having the issue with `suggestions` raising `Pass suggest: true to the search method for suggestions` when there is no data to be indexed, however index has been built.

Products.count => 0
Products.reindex
result = Product.search('some words', suggest: true)
result.suggestions => `Pass suggest: true to the search method for suggestions`

This reads similar to https://github.com/ankane/searchkick/issues/1042 but I'm on 3.1.0 already.

(it looks like https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb#L86 tries to handle the situation for when `term` is "*", but not for other cases)

**Comment by liang3404814** [comment]
Hi @ankane ,

Thanks for the response. I think I have followed the suggestions section. Here is the gist:
https://gist.github.com/liang3404814/348003675c9a9e88d2e1bde5e42d05c5

**Comment by ankane** [comment]
Hey @liang3404814, unfortunately, that gist is not runnable. Please follow the format of the gist in the Contributing Guide. Also, there's no such thing as `match: :suggest`, so that could be the problem.

**Comment by liang3404814** [comment]
@ankane Looks like `match: :suggest` is causing it. Was looking at source code (`searchkick_suggest_index`) when I wrote it. Thanks.
