### ISSUE TITLE
Deleting records async with routing, how does that work?

### ISSUE THREAD

**Issue by Arjeno** [ankane/searchkick#1182]
Hi guys! I'm using routing and everything is processed asynchronously. I've noticed errors where it would give me `"type"=>"routing_missing_exception"`. It seems that when you delete something it would be unaware of routing because it instantiates a new record and manually sets the id without setting the route.

https://github.com/ankane/searchkick/blob/109baa87ad2dbad590456d83d599099d5c72e319/lib/searchkick/process_batch_job.rb#L13
https://github.com/ankane/searchkick/blob/80459c4edd2d24be4b0c4b988f5aa7f9525b9baf/lib/searchkick/reindex_v2_job.rb#L29

Thoughts?

**Comment by ankane** [comment]
Thanks for digging into this 👍 You're right, Searchkick isn't able to handle this right now. I think it'll need to pass the `search_routing` to these jobs for this to work.

**Comment by ankane** [comment]
Fixed the `callbacks: :queue` case on `routing_queue` branch. Need to figure out a good separator between id and routing so minimize chance incorrect splits.
