### ISSUE TITLE
Request cache enforcing

### ISSUE THREAD

**Issue by andresbravog** [ankane/searchkick#1188]
Request cache in ES is very picky on what to cache, just complex indexes or aggregations gets cached, making request cache size normally 0 in most of the indexes.

According to [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html), there is an option to add `?request_cache=true` parameter to the query URL in order to enforce the request to be cached. Depending on the usage of your index this might be really helpful.

Forget me if that option is already available, I couldn't find it.

Is there any easy way to enforce this with Searchkick?

**Comment by ankane** [comment]
Check out request parameters in the readme.

**Comment by andresbravog** [comment]
yup! thanks that works.
