### ISSUE TITLE
[Idea] Support native ES date datatype

### ISSUE THREAD

**Issue by diego-silva** [ankane/searchkick#1190]
Hi,

I was wondering if there is a reason for searchkick to store dates as regular text (or maybe I'm doing something wrong) instead of the native `date` type from ES…

I recently had a problem where I was filtering by a date range but my timezone was not being correctly applied and I ended up tracking it down to it being stored as a text…

Should date support be added? Or am I missing something?

**Comment by mikelkew** [comment]
Hi @diego-silva, in the indexes in the app I'm working on at the moment, DateTime attributes are being automatically cast as the native `date` type in ES, enabling us to filter them correctly in a query, e.g. `where: {live_at: {lte: Time.current}}`. However, when working with the query results, or a single document, the dates are represented as strings, as that is how they are sent in the JSON response from ES.

I confirmed that the mapping type was set to `date` by running `curl -XGET '#{es_host}:9200/#{index_name}?pretty' which will show the mappings for each field in the index.

Not sure why they wouldn't be using the native `date` type in your index though, unless perhaps your `search_data` configuration in your model is converting your dates to strings before indexing?

**Comment by diego-silva** [comment]
@mikelkew Thanks for your reply, I went ahead and tried here locally and realized that my date field was being set as `filterable` but that should only be used for strings according to the docs 🤦‍♂️

https://github.com/ankane/searchkick#filterable-fields
