### ISSUE TITLE
Reindexing parses excluded fields.  serialized JSON field fails parsing

### ISSUE THREAD

**Issue by abdalafer** [ankane/searchkick#1191]
Hi everyone, so I have come across an issue. 
In my rails project there is a model called Order.

These are the Order declarations related to searchkick:
```
searchkick index_prefix: Rails.application.class.parent_name.downcase, searchable: [:id, :user_name, :second_user_name],match: :word_middle, batch_size: ES_BATCH_SIZE
```

`serialize :summary, JSON`
  
The issue is, when I run `Order.reindex`, it fails with the following error:

``` 
Order Import (7274.8ms)  {"count":200,"exception":["Searchkick::ImportError","{\"type\"=\u003e\"mapper_parsing_exception\", \"reason\"=\u003e\"failed to parse [summary.detail.start_time]\", \"caused_by\"=\u003e{\"type\"=\u003e\"illegal_argument_exception\", \"reason\"=\u003e\"Invalid format: \\\"2:00PM\\\" is malformed at \\\":00PM\\\"\"}} on item with id '40'"],"exception_object":"{\"type\"=\u003e\"mapper_parsing_exception\", \"reason\"=\u003e\"failed to parse [summary.detail.start_time]\", \"caused_by\"=\u003e{\"type\"=\u003e\"illegal_argument_exception\", \"reason\"=\u003e\"Invalid format: \\\"2:00PM\\\" is malformed at \\\":00PM\\\"\"}} on item with id '40'"}
Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [summary.detail.start_time]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"2:00PM\" is malformed at \":00PM\""}} on item with id '40' 
```

The situation is that, its parsing a JSON field and its considering some values to be invalid.
I do not have this `summary` field in the `search_data` and I do not want to include it in the indexing. 

So how come its parsing it?
How can I prevent this field from being used with searchkick?
If theres no way around it, what is suggested in regarding to not failing the json parsing?
	
Thank you in advance.

Rails 5.0.1
ElasticSearch 5.5
`gem 'searchkick', '>=2.1.1'`

**Comment by mikelkew** [comment]
Only the fields in your `search_data` method should be being indexed. Have you written your own custom `search_data` method to override the default behaviour of indexing all attributes? If you run `order.search_data.keys` on an Order instance, are you sure that the "summary" field isn't there?

**Comment by abdalafer** [comment]
Thank you for the response. In the model I have a search_data function declared with a list of fields, but it does not include the summary. 

However when I do `@order.search_data.keys` I do see the `summary` field. 

Do you have any suggestions on what could be adding `summary`?

**Comment by mikelkew** [comment]
Hmm, not really sure why that would be happening unless perhaps your `search_data` method hasn't been defined properly. Just to be sure, my normal approach to this is to include the following in the model (customise the field names etc as needed):

```ruby
INDEXED_FIELDS = %w[
  field_name_1
  field_name_2
  field_name_3
].freeze

def search_data
  as_json(only: INDEXED_FIELDS)
end
```
or, if you also have some custom fields:
```ruby
def search_data
  as_json(only: TOURS_FIELDS).merge(search_data_fields)
end

def search_data_fields
  {
    custom_field_1:  method_1,
    custom_field_2: method_2
  }
end
```

If you're already doing something equivalent to that then I'm not too sure what would be causing it.

**Comment by abdalafer** [comment]
Thank you again for the response, this issue could be closed, the search_data function was including the entire attributes list.
