### ISSUE TITLE
ArgumentError (wrong number of arguments (given 1, expected 0))

### ISSUE THREAD

**Issue by JohnMTrimbleIII** [ankane/searchkick#1192]
I'm having an issue similar to #934. 

I upgraded from searchkick (3.0.2) to searchkick (3.1.1). Nothing else has changed and I keep running into the ArgumentError. 

I am running Elasticsearch 6.2.4 and running development on localhost.

When I attempt to reindex a collection I get this error: 
` VideoGame.published.reindex`
  VideoGame Import (60.4ms)  {"count":43,"exception":["ArgumentError","wrong number of arguments (given 1, expected 0)"],"exception_object":"wrong number of arguments (given 1, expected 0)"}

When I attempt to reindex a single record: 
`VideoGame.last.reindex`
  VideoGame Store (1.4ms)  {"id":290,"exception":["ArgumentError","wrong number of arguments (given 1, expected 0)"],"exception_object":"wrong number of arguments (given 1, expected 0)"}

When I attempt to search: 
`VideoGame.search("witcher")`

ArgumentError (wrong number of arguments (given 1, expected 0))

My gemfile.lock looks like the following: 
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.6)
      actionpack (= 5.1.6)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.6)
      actionpack (= 5.1.6)
      actionview (= 5.1.6)
      activejob (= 5.1.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.6)
      actionview (= 5.1.6)
      activesupport (= 5.1.6)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.6)
      activesupport (= 5.1.6)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.1.6)
      activesupport (= 5.1.6)
      globalid (>= 0.3.6)
    activemodel (5.1.6)
      activesupport (= 5.1.6)
    activerecord (5.1.6)
      activemodel (= 5.1.6)
      activesupport (= 5.1.6)
      arel (~> 8.0)
    activesupport (5.1.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    ancestry (3.0.2)
      activerecord (>= 3.2.0)
    arel (8.0.0)
    autoprefixer-rails (9.1.4)
      execjs
    aws-eventstream (1.0.1)
    aws-partitions (1.102.0)
    aws-sdk-core (3.25.0)
      aws-eventstream (~> 1.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-kms (1.7.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sdk-s3 (1.17.1)
      aws-sdk-core (~> 3, >= 3.21.2)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.3)
    bcrypt (3.1.12)
    bindex (0.5.0)
    bootstrap (4.0.0)
      autoprefixer-rails (>= 6.0.3)
      popper_js (>= 1.12.9, < 2)
      sass (>= 3.5.2)
    builder (3.2.3)
    byebug (10.0.2)
    capybara (2.18.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (>= 2.0, < 4.0)
    carrierwave (1.2.3)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      mime-types (>= 1.16)
    carrierwave-aws (1.3.0)
      aws-sdk-s3 (~> 1.0)
      carrierwave (>= 0.7, < 2.0)
    chart-js-rails (0.1.6)
      railties (> 3.1)
    childprocess (0.9.0)
      ffi (~> 1.0, >= 1.0.11)
    closure_tree (6.6.0)
      activerecord (>= 4.1.0)
      with_advisory_lock (>= 3.0.0)
    cocoon (1.2.11)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    connection_pool (2.2.2)
    crass (1.0.4)
    devise (4.5.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    domp (0.0.7)
    elasticsearch (6.1.0)
      elasticsearch-api (= 6.1.0)
      elasticsearch-transport (= 6.1.0)
    elasticsearch-api (6.1.0)
      multi_json
    elasticsearch-transport (6.1.0)
      faraday
      multi_json
    erubi (1.7.1)
    et-orbi (1.1.6)
      tzinfo
    execjs (2.7.0)
    faker (1.9.1)
      i18n (>= 0.7)
    faraday (0.12.2)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (0.12.2)
      faraday (>= 0.7.4, < 1.0)
    fastimage (2.1.3)
    feedjira (2.2.0)
      faraday (>= 0.9)
      faraday_middleware (>= 0.9)
      loofah (>= 2.0)
      sax-machine (>= 1.0)
    ffi (1.9.25)
    figaro (1.1.1)
      thor (~> 0.14)
    font-awesome-rails (4.7.0.4)
      railties (>= 3.2, < 6.0)
    fugit (1.1.6)
      et-orbi (~> 1.1, >= 1.1.6)
      raabro (~> 1.1)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    hashie (3.5.7)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    httparty (0.16.2)
      multi_xml (>= 0.5.2)
    i18n (1.1.0)
      concurrent-ruby (~> 1.0)
    impressionist (1.6.1)
      nokogiri (~> 1)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jmespath (1.4.0)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jwt (1.5.6)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    mechanize (2.7.6)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (>= 1.17.2)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (>= 2.5.2)
      nokogiri (~> 1.6)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    method_source (0.9.0)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2018.0812)
    mini_magick (4.8.0)
    mini_mime (1.0.1)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    multi_json (1.13.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    net-http-digest_auth (1.4.1)
    net-http-persistent (3.0.0)
      connection_pool (~> 2.2)
    nio4r (2.3.1)
    nokogiri (1.8.4)
      mini_portile2 (~> 2.3.0)
    ntlm-http (0.1.1)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.8.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-facebook (5.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    omniauth-twitch (0.2.0)
      omniauth-oauth2 (~> 1.1)
    orm_adapter (0.5.0)
    pg (0.21.0)
    popper_js (1.14.3)
    public_suffix (3.0.3)
    puma (3.12.0)
    raabro (1.1.6)
    rack (2.0.5)
    rack-protection (2.0.3)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.1.6)
      actioncable (= 5.1.6)
      actionmailer (= 5.1.6)
      actionpack (= 5.1.6)
      actionview (= 5.1.6)
      activejob (= 5.1.6)
      activemodel (= 5.1.6)
      activerecord (= 5.1.6)
      activesupport (= 5.1.6)
      bundler (>= 1.3.0)
      railties (= 5.1.6)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.1.6)
      actionpack (= 5.1.6)
      activesupport (= 5.1.6)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.1)
    random_user_agent (1.0.0)
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    redis (4.0.2)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    rolify (5.2.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.2)
    rufus-scheduler (3.5.2)
      fugit (~> 1.1, >= 1.1.5)
    sass (3.5.7)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sax-machine (1.3.2)
    searchkick (3.1.1)
      activemodel (>= 4.2)
      elasticsearch (>= 5)
      hashie
    selenium-webdriver (3.14.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.2)
    sidekiq (5.2.1)
      connection_pool (~> 2.2, >= 2.2.2)
      rack-protection (>= 1.5.0)
      redis (>= 3.3.5, < 5)
    sidekiq-scheduler (3.0.0)
      redis (>= 3, < 5)
      rufus-scheduler (~> 3.2)
      sidekiq (>= 3)
      tilt (>= 1.4.0)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tinymce-rails (4.8.2)
      railties (>= 3.1.1)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.18)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webrobots (0.1.2)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    with_advisory_lock (4.0.0)
      activerecord (>= 4.2)
    xpath (3.1.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  ancestry
  bootstrap (~> 4.0.0)
  byebug
  capybara (~> 2.13)
  carrierwave
  carrierwave-aws
  chart-js-rails
  closure_tree
  cocoon
  coffee-rails (~> 4.2)
  devise
  domp
  faker
  fastimage
  feedjira
  figaro
  font-awesome-rails
  httparty
  impressionist
  jbuilder (~> 2.5)
  jquery-rails
  kaminari
  listen (>= 3.0.5, < 3.2)
  mechanize
  mini_magick
  nokogiri
  omniauth
  omniauth-facebook
  omniauth-twitch
  pg (~> 0.18)
  puma (~> 3.7)
  rails (~> 5.1.4)
  random_user_agent
  redis
  rolify
  sass-rails (~> 5.0)
  searchkick
  selenium-webdriver
  sidekiq
  sidekiq-scheduler
  spring
  spring-watcher-listen (~> 2.0.0)
  tinymce-rails
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

RUBY VERSION
   ruby 2.5.0p0

BUNDLED WITH
   1.16.4

**Comment by ankane** [comment]
Hey @JohnMTrimbleIII, can you add the full backtrace?

**Comment by JohnMTrimbleIII** [comment]
net-http-persistent (3.0.0) lib/net/http/persistent.rb:505:in `initialize'
faraday (0.12.2) lib/faraday/adapter/net_http_persistent.rb:22:in `new'
faraday (0.12.2) lib/faraday/adapter/net_http_persistent.rb:22:in `net_http_connection'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
faraday (0.12.2) lib/faraday/adapter/net_http.rb:33:in `call'
searchkick (3.1.1) lib/searchkick/middleware.rb:9:in `call'
faraday (0.12.2) lib/faraday/rack_builder.rb:141:in `build_response'
faraday (0.12.2) lib/faraday/connection.rb:386:in `run_request'
elasticsearch-transport (6.1.0) lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
elasticsearch-transport (6.1.0) lib/elasticsearch/transport/transport/base.rb:266:in `perform_request'
elasticsearch-transport (6.1.0) lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
elasticsearch-transport (6.1.0) lib/elasticsearch/transport/client.rb:131:in `perform_request'
elasticsearch-api (6.1.0) lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
searchkick (3.1.1) lib/searchkick/indexer.rb:18:in `perform'
searchkick (3.1.1) lib/searchkick/logging.rb:126:in `perform'
searchkick (3.1.1) lib/searchkick/indexer.rb:11:in `queue'
searchkick (3.1.1) lib/searchkick/bulk_indexer.rb:43:in `bulk_index'
searchkick (3.1.1) lib/searchkick/index.rb:125:in `store'
searchkick (3.1.1) lib/searchkick/logging.rb:28:in `block in store'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
searchkick (3.1.1) lib/searchkick/logging.rb:27:in `store'
searchkick (3.1.1) lib/searchkick/record_indexer.rb:54:in `reindex_record'
searchkick (3.1.1) lib/searchkick/record_indexer.rb:35:in `reindex'
searchkick (3.1.1) lib/searchkick/model.rb:78:in `reindex'
activesupport (5.1.6) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.6) lib/active_support/callbacks.rb:260:in `block in conditional'
activesupport (5.1.6) lib/active_support/callbacks.rb:511:in `block in invoke_after'
activesupport (5.1.6) lib/active_support/callbacks.rb:511:in `each'
activesupport (5.1.6) lib/active_support/callbacks.rb:511:in `invoke_after'
activesupport (5.1.6) lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport (5.1.6) lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
activerecord (5.1.6) lib/active_record/transactions.rb:343:in `committed!'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:93:in `block in commit_records'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:93:in `each'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:93:in `ensure in commit_records'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:93:in `commit_records'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:178:in `block in commit_transaction'
/Users/treytrimble/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:168:in `commit_transaction'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:207:in `block in within_new_transaction'
/Users/treytrimble/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
activerecord (5.1.6) lib/active_record/transactions.rb:210:in `transaction'
activerecord (5.1.6) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
activerecord (5.1.6) lib/active_record/transactions.rb:308:in `block in save'
activerecord (5.1.6) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
activerecord (5.1.6) lib/active_record/transactions.rb:307:in `save'
activerecord (5.1.6) lib/active_record/suppressor.rb:42:in `save'
app/controllers/concerns/controller_draftable.rb:47:in `update'
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
searchkick (3.1.1) lib/searchkick/logging.rb:209:in `process_action'
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:155:in `handle'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:106:in `block (2 levels) in start'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:96:in `each'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:76:in `start'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/lib/nack/server.rb:12:in `run'
/Users/treytrimble/Library/Application Support/Pow/Versions/0.6.0/node_modules/nack/bin/nack_worker:4:in `<main>'

**Comment by ankane** [comment]
It looks like net-http-persistent 3.0 is not compatible with that version of Faraday. https://github.com/lostisland/faraday/commit/f8892b13019b08c7b27f6db00bf672e6ada702f2

**Comment by JohnMTrimbleIII** [comment]
I can confirm. 

gem 'net-http-persistent', '~>2.9'

Fixes my issue. Should there be a warning somewhere in the docs?

**Comment by ankane** [comment]
Think it's too uncommon for that
