### ISSUE TITLE
ES deprecation warnings with Searchkick 3.1.1

### ISSUE THREAD

**Issue by jbwl** [ankane/searchkick#1193]
Hi,

I'd like to report some deprecation warnings again. This is shown when doing a search with Searchkick 3.1.1 querying ES 6.3.2:

`[WARN ][o.e.d.s.a.InternalOrder$Parser] Deprecated aggregation order key [_term] used, replaced by [_key]`

which is described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

and

`[WARN ][o.e.d.c.ParseField       ] Deprecated field [inline] used, expected [source] instead`

there is some discussion here: https://github.com/olivere/elastic/issues/627

Thank you!

**Comment by ankane** [comment]
Hey @jbwl, are you seeing these when you run the Searchkick tests or somewhere else? If it's somewhere else, can you use the gist in the Contributing Guide to reproduce?

**Comment by jbwl** [comment]
I am seeing these in my ES production logs when searching with Searchkick.
I have tried to setup the gist but running on incompatibilities on my dev machine. I'll try later on again.

**Comment by ankane** [comment]
Sounds good. fwiw, I found (and fixed) instances of those in tests, but not in the actual library code.

**Comment by ankane** [comment]
Just found those deprecated patterns in the docs and fixed. You'll likely need to update your application code, as they are just values Searchkick passes directly to Elasticsearch.

**Comment by ankane** [comment]
Hey @jbwl, any update?
