### ISSUE TITLE
How to modify cutoff frequency

### ISSUE THREAD

**Issue by audiolion** [ankane/searchkick#1194]
Hey 👋,

thanks for this lib! We are using searchkick as a fast search on a list of names. However, due to the common terms frequency (0.001), it seems like common phrases like 'he' or 'be' are filtered out of results. So when a search query is `b` you might get a list like `Bob, Ben, Bella`, but when you type the next character `be` you only get `Bob`. I think this is because it is ignoring the results starting with `be` as common phrases.

Is there a way to modify the cutoff frequency? Or are we using searchkick in the wrong way here?

This would seem to be a way to do it:

```ruby
Searchkick.model_options = {
  cutoff_frequency: 0.5
}
```

but this is not an allowed keyword

**Comment by ankane** [comment]
Hey @audiolion, can you try recreating the behavior with [this gist](https://gist.github.com/ankane/f80b0923d9ae2c077f41997f7b704e5c)?

Right now, the only way to change the cutoff frequency is to [modify the query generated by Searchkick](https://github.com/ankane/searchkick#advanced-search).

**Comment by audiolion** [comment]
Hey so it looks like this was a combination of issues. First off, our search data includes `first_name, last_name, phone_number`. What was happening was `b` was interpreted as a misspelling with an edit distance close enough to a digit that happened to be in `Bob, Ben, Bella`'s `phone_number`.

So we are trying to turn off misspellings for the `phone_number` field, and turn on `:word_start` for the `first_name` and `last_name` fields.

As a result, our search looks like:

```ruby
Contact.search(
      'be',
      fields: [
        { first_name: :word_start },
        { last_name: :word_start },
        { phone_number: :word_middle },
      ],
      misspellings: { fields: %i[first_name last_name] },
      limit: 5
    )
```

This seems to be what we want, though we get an error on the `misspellings` piece, `All fields in per-field misspellings must also be specified in fields option`, maybe we have to define it as:

```ruby
misspellings: { fields: [:first_name, :last_name] },
```

instead?

**Comment by ankane** [comment]
Field misspellings weren't compatible with that way of specifying fields. On master, you can do:

```ruby
misspellings: {fields: [{first_name: :word_start}, {last_name: :word_start}]}
```

**Comment by ankane** [comment]
Actually, think what you tried previously is more intuitive, so the latest master supports that instead of the above.

```ruby
misspellings: {fields: [:first_name, :last_name]}
```

**Comment by audiolion** [comment]
Awesome, we are doing the `misspellings: { fields: %i[first_name last_name] }` syntax and it is working well. I think the issue was we had

```ruby
searchkick :word_start [:first_name, :last_name]
```

defined on the ActiveRecord model and switching it to 

```ruby
searchkick :word_start %i[first_name :last_name]
```

fixed it

**Comment by audiolion** [comment]
Oops, above `:` was just a typo.
`[:a, :b] == %i[a b]` is what I thought, I am probably just not understanding the error that we got. It potentially was an issue where we had updated the code but not reindexed.

**Comment by ankane** [comment]
Sounds like everything is working now, so closing out
