### ISSUE TITLE
Model.reindex(async: {wait: true}) get stuck at Batches left: 1

### ISSUE THREAD

**Issue by sojan-official** [ankane/searchkick#1195]
calling `Model.reindex(async: {wait: true})` from rails c  get stuck with the message 
```
Batches left: 1
Batches left: 1
Batches left: 1
```

i tried passing  both 
```
Searchkick.redis = Redis.new
Searchkick.redis = Sidekiq.redis {|con| con }
```

our sidekiq queue is name `search_reindex`

**Comment by ankane** [comment]
Hey @sojan-official, which version of Searchkick are you on? One cause of this was fixed a few releases back.

**Comment by sojan-official** [comment]
@ankane  its searchkick (2.5.0)

**Comment by ankane** [comment]
Upgrading to the latest version should fix it.

**Comment by sojan-official** [comment]
@ankane occurring in searchkick-3.1.2 too

**Comment by phuong1492** [comment]
Same here
im using  searchkick (2.5.0)
