### ISSUE TITLE
Can we implement  like query functionality in searchkick using autocomplete typeahead

### ISSUE THREAD

**Issue by kashiftufail** [ankane/searchkick#1199]
Hi,

   I am using searchkick for searching, and now i want to implement like query functionality in sql. Below is code of my controller method

             render json:    Item.search(params[:query], {
                fields: ["name"],
                match: :word_start,
                limit: 10,
                load: false,
                misspellings: {below: 5}
              }).map(&:name)

In Item model just
 
                       searchkick word_start: [:name]                        

And there is records in my DB with word "toyota". But when i search word "toy", there is no record. If i chnage "match: :word". Then on searching "toyota" as a results there are some records with "toyota" word. I want to implement  fetch records from DB just like "like" query do in sql.

Is it possible?

Above functionality should do, But it is not working.

Please help

Thanks

**Comment by ankane** [comment]
Hey @kashiftufail, be sure to do a full reindex after updating options. If that doesn't work, please use the gist in the Contributing Guide to reproduce.
