### ISSUE TITLE
Field data changing during runtime

### ISSUE THREAD

**Issue by jgoodall628** [ankane/searchkick#1206]
Hi all,
I am receiving this error on production: 

[400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."}]

When i run reindex the model in question, the issue goes away. But then it will randomly come back without any deployments or any other tasks being run. Is there a way to have the field data be changed during runtime that would cause this?

elasticsearch (6.1.0)
elasticsearch-api (6.1.0)
elasticsearch-transport (6.1.0)
searchkick (2.2.1)

Thanks so much for your help!

**Comment by mikelkew** [comment]
Have you tried updating to the latest searchkick version and reindexing? 2.2.1 is a pretty old version and quite a number of improvements/fixes have been made since then.

**Comment by jgoodall628** [comment]
I am calling the reindex in a delayed job maybe that is related?

`Product.delay.reindex`

This is in my product model: 
`  searchkick word_start: [:name], searchable: [:name], filterable: [:id, :location_id, :business_id, :category_id, :category_name, :sub_category_ids, :sub_category_names, :name, :color_ids, :shared_business_ids, :marketplace_shared, :storefront_shared, :rented_count, :quantity]`

**Comment by mikelkew** [comment]
What type of search is causing the error? Is it a normal text query, or an aggregation? If the latter, aggregations are [not recommended on text fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#before-enabling-fielddata).

**Comment by jgoodall628** [comment]
It is a normal text query

**Comment by xxx** [comment]
We're actually seeing this as well, with normal text queries. It's only shown up in our staging environment so far. We have to fully delete the index, then rebuild it, to resolve the error. (for anyone seeing this in the future, `Model.search_index.delete; Model.reindex`.) I'm currently rebuilding the index for the third time in about 2 weeks, though we've had many more deploys and reindexes that that in the meantime.

We're on ES 6.4.1, with Searchkick 3.1.2.

**Comment by ankane** [comment]
Next time this happens, capture the ES mapping and ES settings before you reindex and compare it with the ES mapping and ES settings after you reindex. It seems like something is affecting it. In general, you should only need to do a full reindex when you:

- install or upgrade searchkick
- change the search_data method
- change the searchkick method

**Comment by xxx** [comment]
@ankane what's the right way to get the mapping and settings?

**Comment by ankane** [comment]
The ES docs should have it.

**Comment by ankane** [comment]
Cleaning up stale issues
