### ISSUE TITLE
search for soft-deleted(unscoped) users doesn't work

### ISSUE THREAD

**Issue by prativapokhrel** [ankane/searchkick#1208]
I have a feature to soft-delete users, and you can access them by using the unscoped method 
User.unscoped.all
However, searching for those records doesn't work. Here's how I am doing it: 
User.unscoped.all.search search_param, aggs: [:name] 

Is this expected or is there a way to solve this ? 
I am using an older version of searchkick - 2.1.1 ; do I need to be on the latest one to resolve this?

**Comment by ankane** [comment]
Hey @prativapokhrel, you'll need to upgrade to the latest version and do:

```ruby
Product.search "query", scope_results: ->(r) { r.unscoped }
```
