### ISSUE TITLE
Error on reindexing using Wordnet file with ES 6

### ISSUE THREAD

**Issue by jfalk** [ankane/searchkick#1209]
When reindexing in ES >= 6 with a WordNet file I get the error below:

```
{
   "error":{
      "root_cause":[
         {
            "type":"illegal_argument_exception",
            "reason":"failed to build synonyms"
         }
      ],
      "type":"illegal_argument_exception",
      "reason":"failed to build synonyms",
      "caused_by":{
         "type":"parse_exception",
         "reason":"Invalid synonym rule at line 2",
         "caused_by":{
            "type":"illegal_argument_exception",
            "reason":"term: physical entity analyzed to a token (physicalentity)with position increment != 1 (got: 0)"
         }
      }
   },
   "status":400
}
```

Looks like a user already reported this once in the ES issues, but it was never moved here and I'm currently running into the same thing. The cause is pretty thoroughly documented there.

https://github.com/elastic/elasticsearch/issues/27798

**Comment by ankane** [comment]
Hey @jfalk, thanks for reporting 👍 I'm able to reproduce, but not sure exactly how to fix it. If you have any ideas, let me know.

**Comment by ankane** [comment]
Removed Wordnet docs from readme. It'll no longer be supported going forward. Feature readers are welcome to submit a PR to get this working again.
