### ISSUE TITLE
Skipping index generation for Searchkick-enabled Model

### ISSUE THREAD

**Issue by matteoredz** [ankane/searchkick#1210]
Hi, we have an issue with Searchkick. We have a resource being indexed by another application, and the index name is fixed. We need Searchkick to access that index. We already managed to avoid the model being indexed (by setting should_index to false)
if we use the `index_name` option, Searchkick will append a timestamp to that
Will it still be able to access our existing index or is there anything else to do to achieve that?

**Comment by ankane** [comment]
Hey @matteoredz, can you provide more details about what you're seeing? Searchkick doesn't append a timestamp to the index name when searching.

**Comment by matteoredz** [comment]
Hi @ankane, the index structure is `model_name_timestamp` but I've an index injected from an external web app structured ad `my_index_name` without timestamp.

In my main application I've mapped `self.index_name` to match the index name injected by the other app.

My question is: Is there any - documented - way to skip indexing from Searchkick (which would generate `my_index_name_timestamp`) and use it as read-only using this gem?

**Comment by ankane** [comment]
You can turn callbacks off with `callbacks: false`, but someone could always reindex manually. The best way would be to give [read-only access](https://www.elastic.co/guide/en/x-pack/current/authorization.html) with X-Pack or your hosted provider.

**Comment by matteoredz** [comment]
Ok, at this stage I've overrided the rake task:

`
Searchkick.models.delete_if { |model| model.read_only_index? }.each do |model|
        puts "Reindexing #{model.name}..."
        model.reindex
end
`
