### ISSUE TITLE
Searchkick.models not returning all search enabled models

### ISSUE THREAD

**Issue by archonic** [ankane/searchkick#1211]
I have a multitenant application where search is working, but right now I have to manually reindex whenever a new account is created. I'd like to automate that.

On the account model, I have an after_create method with:
```
def create_tenant
  Apartment::Tenant.create(subdomain)
  Apartment::Tenant.switch(subdomain) do
    Searchkick.models.each{ |model| p model; p "-----" }
    Searchkick.models.each{ |model| model.reindex(import: false) }
  end
end
```

This will output:
```
User(...)
"-----"
AccountsUser(...)
"-----"
```

But if I have this:
```
def create_tenant
  Apartment::Tenant.create(subdomain)
  Apartment::Tenant.switch(subdomain) do
    Document
    Issue
    Searchkick.models.each{ |model| p model; p "-----" }
    Searchkick.models.each{ |model| model.reindex(import: false) }
  end
end
```

The output will be:
```
User(...)
"-----"
AccountsUser(...)
"-----"
Document(...)
"-----"
Issue(...)
"-----"
```

This could be an artifact of how Apartment works and not a Searchkick bug. Is there a way to ensure Searchkick knows about all the models without explicitly calling the model classes? I'm scoping my index names like this:

document.rb
```
include SchemaSearchable
...
searchkick word_start: [:name], index_name: tenant_index_name, callbacks: :async, settings: { blocks: { read_only: false } }
```

schema_searchable.rb:
```
module SchemaSearchable
  extend ActiveSupport::Concern

  module ClassMethods
    def tenant_index_name
      -> { [Apartment::Tenant.current.downcase, model_name.plural, Rails.env].join("_") }
    end

    def public_index_name
      -> { [Apartment::Tenant.default_tenant.downcase, model_name.plural, Rails.env].join("_") }
    end
  end
end
```

**Comment by ankane** [comment]
Hey @archonic, this is due to Rails lazy loading models in development. You can tell it to load all the models with:

```ruby
Rails.application.eager_load!
```

**Comment by archonic** [comment]
It was in the test environment but eager_load was still false. Confirmed that the models were present when enabled. Thanks!
