### ISSUE TITLE
How can I get the search term frequency in the resultset.

### ISSUE THREAD

**Issue by amzurtechnologies** [ankane/searchkick#1212]
How can I get the information on the result set of the number of times the search term occurs in the indexed fields of any record?

`results  = Product.search "Mercedes", misspellings: false`

Say there are 3 products matched with the search keyword "Mercedes". Is there any method or way to know how many times the term occurred in different fields like 3 times(if 1 time in title and 2 times in description)

**Comment by ankane** [comment]
Hey @amzurtechnologies, if Elasticsearch supports it, you can use Advanced Search (see readme) to get it, but Searchkick doesn't provide any helpers for this.
