### ISSUE TITLE
How to filter by year from a date field?

### ISSUE THREAD

**Issue by caecity43** [ankane/searchkick#1213]
There is a Date field in search_data. 

I want to filter by year from this field.

like this SQL:

```sql
SELECT * FROM movies WHERE YEAR(released_at) = '2018';
```

and I received the url params looks like `&year=2018,2017,2011`

```sql
SELECT * FROM movies 
    WHERE YEAR(released_at) = '2018' OR 
        YEAR(released_at) = '2017' OR 
        YEAR(released_at) = '2011' ;
```

**Comment by mikelkew** [comment]
For future reference, @ankane prefers that questions like this are asked on StackOverflow.

The easiest way to do this would be to add a new `release_year` field to your [search_data](https://github.com/ankane/searchkick#indexing) and then reindex your Model (I would recommend as an integer to allow gte/lte queries if needed), e.g. `release_year: movie.released_at.year`

That way you could then perform your query above as:
```ruby
Movie.search('*', where: {release_year: params[:year].map(&:to_i)}, load: false)
```

**Comment by caecity43** [comment]
@mikelkew Great, Thank you, I will add `release_year` field.

**Comment by ankane** [comment]
Thanks @mikelkew
