### ISSUE TITLE
Check if record in DB is indexed by searchkick

### ISSUE THREAD

**Issue by thejazz15** [ankane/searchkick#1214]
I noticed there is a method to retrieve the document from ES for an associated record in Rails.
`p = Product.last`
`Product.searchkick_index.retrieve(p)`
Is this the only way or is there a method to check if a record in your Rails DB is indexed in your ES index?

**Comment by ankane** [comment]
Hey @thejazz15, that method works. You can also check multiple ids like:

```ruby
indexed_ids = Product.search("*", where: {id: ids}, load: false).map(&:id)
```

**Comment by thejazz15** [comment]
Cool thanks @ankane
