### ISSUE TITLE
advanced search doesn't work

### ISSUE THREAD

**Issue by tbaraniecki** [ankane/searchkick#1218]
Hello! 
Such a great gem! 
searchkick v.3.1.0

Using default mapping in model.

Default search gives me results.
`products = Product.search('*', fields: ["name"])`

But using advanced search, it gives me no results. 
`products = Product.search body: {query: {match: {name: "*"}}}`

Thanks in advance!

**Comment by ankane** [comment]
Hey @tbaraniecki, glad you like Searchkick, but please read the Contributing Guide before creating issues (this isn't the right place to get help with your code).
