### ISSUE TITLE
No handler for type [keyword] 

### ISSUE THREAD

**Issue by loganh0522** [ankane/searchkick#1220]
I have recently started to get a reindex error in my production environment. I have not been able to replicate in my local env. 

Any help is much appreciated. 

Error: 

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [profile_w_titles]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [candidate]: No handler for type [keyword] declared on field [profile_w_titles]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [profile_w_titles]"}},"status":400}

**Comment by ankane** [comment]
Hey @loganh0522, as a general development best practice, when something works locally but not in production, it's good to figure out what's different between the two environments (for instance, is the Elasticsearch version the same, etc).

Also, please check out the Contributing Guide for where to get help. If you do some digging and find it's a Searchkick bug, feel free to open a new issue with specifics.
