### ISSUE TITLE
Exact match on a where clause with a list

### ISSUE THREAD

**Issue by joegaudet** [ankane/searchkick#1223]
Hey,

Just trying to figure out how to express a where clause that says a list of indexed ids is an exact match, searchkick comes with affordances for in / all"

```ruby
where: {
  user_ids: [25, 30],         # returns in the search if user ids contains 25 OR 30
  user_ids: {all: [1, 3]},    # returns in the search if user_ids contains 25 AND 30
}
```

Looking for this 

```ruby
{
  user_ids: {eq: [1, 3]},    # returns in the search if user_ids is exactly 25 AND 30
}
```

**Comment by joegaudet** [comment]
Would be happy to do one up, just want to make sure that it is something
supported by elastic search beforehand, are you aware if it is?


I was browsing through the query code and I think I know where it would go.

**Comment by ankane** [comment]
That's something you'll need to look into.

**Comment by joegaudet** [comment]
Fair enough
