### ISSUE TITLE
Filter with multiple ranges with 2 columns

### ISSUE THREAD

**Issue by petermumford** [ankane/searchkick#1227]
Hi, I'm trying to create multiple ranges with 2 columns. I know multiple ranges can be achieved from this issue #979 but I need it to work with 2 columns.

In my model I have a `min_age` and `max_age`. The user can select multiple ages to filter from, for example: the options are _10,11,12,13,14,15,16,17,18_ and the user selects 11, 13 and 16. How would I filter the model from the selected options? 

Also, I think I need to change the selected options to a range so the above would become, 10-11, 12-13 and 15-16 so the range filter can work by using the `gt` and `lt` args. However, maybe a range filter won't work for this?

**Comment by ankane** [comment]
Hey @petermumford, check out the Contributing Guide for where to get help.
