### ISSUE TITLE
Reindex:all fails, reindex CLASS= invidually works

### ISSUE THREAD

**Issue by rene-demonsters** [ankane/searchkick#1228]
I've recently upgraded the setup of our staging servers and I'm running into a strange issue when I try to reindex our applications. I've tried 2 different setups, one of them is giving issues.

Setup 1: Docker with Kubernetes, managed by Rancher 2. Elastic Search has been deployed as a HELM chart and is backed by Local Node Path volumes for Persistent storage. (Meaning there is only 1 copy of the data)
Setup 2: Setup 1: Docker with Kubernetes, managed by Rancher 2. Elastic Search has been deployed as a HELM chart and is backed by Rancher Longhorn for Persistent storage. (Meaning it replicates stuff between the 3 servers).

So my issues is that when I run `rake searchkick:reindex:all` for an application on setup 1, everything indexes just fine in one go. However when I try to do the same thing, for the same application, database etc. on setup 2, it will randomly stop at a certain class and spit out the following error:

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cards_staging_20190215135627944/fHDjadJfTPKpcvdH6PLiHw] already exists","index_uuid":"fHDjadJfTPKpcvdH6PLiHw","index":"cards_staging_20190215135627944"}],"type":"resource_already_exists_exception","reason":"index [cards_staging_20190215135627944/fHDjadJfTPKpcvdH6PLiHw] already exists","index_uuid":"fHDjadJfTPKpcvdH6PLiHw","index":"cards_staging_20190215135627944"},"status":400}
/usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
/usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:323:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/usr/local/bundle/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-6.1.0/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/usr/local/bundle/gems/elasticsearch-api-6.1.0/lib/elasticsearch/api/actions/indices/create.rb:86:in `create'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:16:in `create'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:202:in `create_index'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:269:in `reindex_scope'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/index.rb:195:in `reindex'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/model.rb:59:in `searchkick_reindex'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/tasks.rb:23:in `block (4 levels) in <main>'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/tasks.rb:21:in `each'
/usr/local/bundle/gems/searchkick-3.1.2/lib/searchkick/tasks.rb:21:in `block (3 levels) in <main>'
/usr/local/bundle/gems/bugsnag-6.10.0/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchkick:reindex:all
(See full trace by running task with --trace)
```

The strange part however, is that when I reindex each class 1 after the other using `rake searchkick:reindex CLASS=ClassName`, I can get through all the classes for each application. It doesn't fail. The way the replication of Longhorn containers shouldn't matter, I think, but since it's a "resource_already_exists" error I figured it would be good to mention.

I'm lost as to why this exception might come to be. I figure searchkick:reindex:all would be the same as running each class manually 1 after the other, but there does seem to be a difference.

Version information:
Searchkick: v3.1.2
ElasticSearch: v6.6.0

Let me know if any more information is needed.

**Comment by ankane** [comment]
Hey @rene-demonsters, unfortunately, debugging Rancher Longhorn is out of the scope of support I can offer.

**Comment by rene-demonsters** [comment]
I can understand that. But maybe you could give me some insight on any
potential differences between reindex all and manually initiating each
class?

The strange thing is that it's not consistent at which class it happens. On
the other application I was reindexing it kept flip flopping between 2
classes, but I had no such issue when initiating manually. My suspicion
would be some kind of race condition at this point.

**Comment by ankane** [comment]
The code is here: https://github.com/ankane/searchkick/blob/master/lib/tasks/searchkick.rake
