### ISSUE TITLE
Disabling Misspellings Doesn't Seem to Work

### ISSUE THREAD

**Issue by tridnguyen** [ankane/searchkick#1231]
I have `misspellings: false` when searching for the word "indeterminate", but I keep getting results back that contain "determined".  I've also tried `edit_distance: 0` and `below: 0`. The search I'm using and the curl output are as follows:

```
[141] pry(main)> Requirement.search('indeterminate',
[141] pry(main)*   fields: [{ body: :phrase }],
[141] pry(main)*   load: false,
[141] pry(main)* misspellings: false).count
  Requirement Search (18.2ms)  curl http://localhost:9200/requirements_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"dis_max":{"queries":[{"match_phrase":{"body.analyzed":{"query":"indeterminate","boost":10,"analyzer":"searchkick_search"}}},{"match_phrase":{"body.analyzed":{"query":"indeterminate","boost":10,"analyzer":"searchkick_search2"}}}]}},"timeout":"11s","size":10000,"from":0}'
77
```

If I query ActiveRecord directly, I only get 3 results:
```
[143] pry(main)> Requirement.where('body like ?', '%indeterminate%').count
   (110.7ms)  SELECT COUNT(*) FROM "requirements" WHERE (body like '%indeterminate%')
3
```

I've also tried indexing . with `:word` and `:word_middle`, am I missing something?

Any insight is appreciated, thanks.

**Comment by ankane** [comment]
Hey @tridnguyen, please try the suggestions in the debugging section of the readme, and if that doesn't explain it, use the gist in the Contributing Guide to reproduce.

**Comment by tridnguyen** [comment]
@ankane thanks I actually tried the suggestions in the debugging section, but couldn't figure it out.  I ended up just using a where with a regular expression match to get the results I wanted.
