### ISSUE TITLE
Adding filter/where in geohash_grid aggregation

### ISSUE THREAD

**Issue by fandyd** [ankane/searchkick#1233]
Hi,

I have successfully using body_options to do geohash_grid aggregation, however since im using smart_aggs is false, so i need to filter this manually for this specific aggregation, is there a way to do that?

here is my query so far:
```
Product.search( '*',
{
  :where => {
    :active => true,
  },
  :page => 1,
  :per_page => 12,
  :smart_aggs => false,
  :suggest => true,
  :body_options => {
    :aggs => {
      "location_clusters" => {
         :geohash_grid => {
           :field => "locations",:precision => 9
          }
       }
    }
  }
})
```

**Comment by ankane** [comment]
Hey @fandyd, check out the Contributing Guide for where to get help with your code.
