### ISSUE TITLE
Reindexing not working 

### ISSUE THREAD

**Issue by anandshrivastavatech** [ankane/searchkick#1234]
//model
    searchkick word_start: [:name],
    suggest: [:name, :description, :farm_name, :farm_description]

when I am running command Spree::Product.reindex getting the below error

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [spree/product : {_routing={}, dynamic_templates=[{string_template={mapping={ignore_above=30000, type=keyword, fields={analyzed={analyzer=searchkick_index, index=true, type=text}}}, match_mapping_type=string, match=*}}], properties={farm_description={ignore_above=30000, type=keyword, fields={analyzed={analyzer=searchkick_index, index=true, type=text}, suggest={analyzer=searchkick_suggest_index, index=true, type=text}}}, name={ignore_above=30000,

**Comment by ankane** [comment]
Hey @anandshrivastavatech, what version of Elasticsearch are you on? I believe I've seen that error with ES7 beta1, which Searchkick doesn't support yet. If that's not the case, please use the gist in the Contributing Guide to recreate the issue.

**Comment by anandshrivastavatech** [comment]
Yes you are correct after downgrade the version of elasticsearch to 6 the issue has been resolved. Thanks
