### ISSUE TITLE
Can't make proper sub-aggregation

### ISSUE THREAD

**Issue by piskovoy-dmitrij** [ankane/searchkick#1236]
Hello, 
I faced troubles using searchkick.
I have an Object User, that has fields: id, last_name, address. I want to select ids of all Users that have same last_name and address. 

Reading documentation I can't figure out is it possible to do with this library and if yes at what direction I need to dig. 

Thanks in advance!

**Comment by ankane** [comment]
Hey @piskovoy-dmitrij, check out the Contributing Guide for where to get help.
