### ISSUE TITLE
Result of search is showing only on first request

### ISSUE THREAD

**Issue by navid-farjad** [ankane/searchkick#1237]
I have Elasticsearched 6.6.1 installed on my server working along Searchkick gem in my ruby on rails application.

On my product model i added "active" Boolean column which has default true value.

I re indexed all the models with rake searchkick:reindex:all RAILS_ENV=production and i search trough my product model in controller like this:
```
Product.search(
      q,
      fields: SEARCHES_FIELDS,
      where: args,
      order: { created_at: :desc },
      page: page,
      per_page: per_page,
      includes: %i[holder]
    )
```
and args contains active: true
```
  def retrieve_args
    args = {}
    args[:created_at] = { gte: Date.parse(date_range[:from]) } unless date_range[:from].nil?
    args[:created_at] = { lte: Date.parse(date_range[:to]) } unless date_range[:to].nil?
    args[:active] = true
    args
  end
```
If i remove args[:active] = true response contains expected results. this code is working perfectly on my local host in development environment but when i run it on my server in production mode and running rake searchkick:reindex:all RAILS_ENV=production , the first request has correct response but if i request again response is empty like this:
```
{
    "total_pages": 0,
    "next_page": null,
    "posts": []
}
```
I know this is not the fault of my code as its working on local host but i do not know why i am getting empty response after first request on production server?
i reinstalled Elasticsearch and gems but it didnt help.

**Comment by ankane** [comment]
Hey @navid-farjad, check out the Contributing Guide for where to get help with your code. If you think it's an issue with Searchkick, use the gist in the Contributing Guide to reproduce.

**Comment by navid-farjad** [comment]
@ankane i just moved to elastic cloud and my problem solved. you where right it was elastic search issue. thank you for your help and thank you for your great gem.
