### ISSUE TITLE
[Idea] Support 'lenient' mode for synonyms

### ISSUE THREAD

**Issue by DanielHeath** [ankane/searchkick#1238]
As of elasticsearch 6, synonyms which stem to the same word cause an error when creating an index. 

The new 'lenient' option restores the previous behaviour of silently ignoring them.

EG: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-graph-tokenfilter.html

**Comment by ankane** [comment]
Hey @DanielHeath, do you have an example Searchkick config that causes the error?

**Comment by DanielHeath** [comment]
searchkick(
      synonyms: [["cooperate", "co-operate"]]
    )

**Comment by ankane** [comment]
Thanks. I think synonyms will change significantly with Elasticsearch 7 (and therefore Searchkick 4), so want to hold off on synonyms changes until then.

**Comment by DanielHeath** [comment]
They've already changed significantly as of ES 6. I'd be happy to contribute a patch (I'd expect 4-6 lines of code change) to make ES6 + searchkick useable with synonyms.

**Comment by ankane** [comment]
Sure, happy to take a look if you want to do that.

**Comment by ankane** [comment]
Hey @DanielHeath, tried to reproduce with Elasticsearch 6.0, 6.7 and 7.0, but no luck.

**Comment by DanielHeath** [comment]
Randomly enough, I had just started working on this. No longer wanted or just closing stale issues?

**Comment by ankane** [comment]
I'd say both at this point, since I wasn't able to reproduce.
