### ISSUE TITLE
Duplicate Records on pagination

### ISSUE THREAD

**Issue by usamanasirqb** [ankane/searchkick#1239]
Hi Everyone, 
I am currently facing issues with **pagination** of searchkick. I have like 10000 records of my Book Model and I use pagination with ajax and built in **Kaminari integration of searchkick**. Here is the code of my Book search

```
def set_books_by_keyword keyword, operator = "or"
    Book.search(keyword.presence || "*",
      page: params[:page],
      per_page: 10,
      fields: ["title^10", "asin", "standard_identifier", "author^5"],
      exclude: ["E-Book", "Ebook"],
      suggest: true,
      order: ([{publication_date: ( params[:publication_filter].presence || :desc) }, { price: (params[:price_filter].presence || :desc) }] if filter_params?),
      operator: operator,
    )
  end
```

Here is the video to the issue, I went upto page 04 where this problem occured. 

`https://www.useloom.com/share/7d4c41ae10994b3bba691ab67fcbe478`

**Comment by ankane** [comment]
Hi @usamanasirqb, check out the Contributing Guide for where to get help and how to report issues.

**Comment by usamanasirqb** [comment]
@ankane thank you for the swift response of this issue but I think this is a bug thats why I created the issue on this repo. Can you please guide me how to solve it or report it the better way?

**Comment by ankane** [comment]
Check out the Contributing Guide for how to report bugs.
