### ISSUE TITLE
Misspelling request does not take into account body changes

### ISSUE THREAD

**Issue by jfloff** [ankane/searchkick#1244]
According to #661 If too few results are returned with no misspellings a second search is performed.

What I found is that if we have changes to the body with the yield block,
```
Item.search(text, options) do |body|
   ...
end
```

the second query its not taking into account the changes to the body that we defined in the yield block, only the first query is.

**Comment by ankane** [comment]
Hey @jfloff, thanks for reporting 👍 Fixed on master.
