### ISSUE TITLE
Mapping with nested field for instance method 

### ISSUE THREAD

**Issue by VoTaiTri** [ankane/searchkick#1248]
i have trouble like below
i have 3 model A, B, C
A has_many B
B has_many C
B have field `field_b`
B have instance method `abc` to get id list of C for each B
i use elasticsearch for A
i added mappings with nested for B inside A 
elasticsearch can search with `field_b`, it's ok 
but i can't to use mapping to search with `abc` from A
@ankane can i mapping to search with it?
anyone help me, many thanks

**Comment by ankane** [comment]
Hey @VoTaiTri, check out the Contributing Guide for where to get help.
