### ISSUE TITLE
Object.similar throws routing_missing_execption

### ISSUE THREAD

**Issue by pawneetdev** [ankane/searchkick#1249]
Judgement model

```
class Judgement
    searchkick highlight: [:raw_data], word_start: [:title], routing: true, settings: { number_of_shards: 2  }

    def search_routing
        court_id
    end
end
```

Query executed

```
j = Judgement.first
j.similar(fields: [:title], routing: 6)
```

Exception encountered

> Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"routing_missing_exception","reason":"routing is required for [judgements_production_20190307044912345]/[judgement]/[1]","index_uuid":"_na_","index":"judgements_production_20190307044912345"}],"type":"routing_missing_exception","reason":"routing is required for [judgements_production_20190307044912345]/[judgement]/[1]","index_uuid":"_na_","index":"judgements_production_20190307044912345"},"status":400}

I also ran the following command
```
j = Judgement.first
j.search_routing
```
It returned the routing id successfully
> 6

**Comment by ankane** [comment]
Hey @pawneetdev, thanks for reporting 👍 Just added support for routing to the `similar` method on master.
