### ISSUE TITLE
Misspellings not working with partial match

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#1250]
HI! Tested at master@d44d2f6 (per contributing guide).

Given the model `Location`, the goal is to have a working **autocomplete**. 

For that, we should use `word_start` as per the readme.

```
class Location < ApplicationRecord

searchkick(
    searchable: [
      :city
    ],
    word_start: [
      :city
    ]
  )
```

I have a Location instance with `city.name = Ilhabela` (no spaces).

The following returns a match (which is expected, since it's an exact search):

`Location.search("Ilhabela", fields: [{city: :word_start}]).results => match!`

Searching for `Ilha` returns a match, showing word_start is working:

`Location.search("Ilha", fields: [{city: :word_start}]).results  => match!`

But searching for `Ilha Bela` (with a space in the middle, which is a misspelling) returns a match **only if the partial match _word_start_ is not included**:

`Location.search("Ilha Bela", fields: [{city: :word_start}]).results  => no match`

`Location.search("Ilha bela", fields: [:city]).results => match!`

I think this demonstrates a bug, since misspellings is working without `:word_start`, but stops working as soon as `:word_start` partial match is added. 

This is the curl generated **without word_start**, I can see fuzziness in both of them, so I don't know what really is making them different:

```
curl http://localhost:9200/locations_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"dis_max":{"queries":[{"match":{"city.analyzed":{"query":"Ilha bela","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"city.analyzed":{"query":"Ilha bela","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"city.analyzed":{"query":"Ilha bela","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"city.analyzed":{"query":"Ilha bela","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"timeout":"11s","_source":false,"size":10000,"from":0}'
```

This is the curl generate with word_start:

```
curl http://localhost:9200/locations_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"dis_max":{"queries":[{"bool":{"must":{"bool":{"should":[{"match":{"city.word_start":{"query":"Ilha bela","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}},{"match":{"city.word_start":{"query":"Ilha bela","boost":1,"operator":"and","analyzer":"searchkick_word_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"should":{"match":{"city.analyzed":{"query":"Ilha bela","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}}}}]}},"timeout":"11s","_source":false,"size":10000,"from":0}
```

**Comment by feliperaul** [comment]
Here they are, side by side:

![image](https://user-images.githubusercontent.com/743879/55689016-0b1cb100-5956-11e9-81a0-05a821f54587.png)

**Comment by ankane** [comment]
Hey @feliperaul, whitespace is used for tokenization, so it's treated differently than other characters for the purposes of misspellings. `Bela` does not match the start of any word, which is why it's not matching any results when the space is present.

**Comment by feliperaul** [comment]
Thanks @ankane for the usual quick response. 

Before I close this, for future reference, any idea how it would be possible to achieve the desired result (`Ilha Bela` returning `Ilhabela` for an autocomplete, which must use `word_start`)?

**Comment by ankane** [comment]
You'll likely need to update the analyzers (and may need to add a 2nd search analyzer like the default search). Check out Searchkick's default analyzers to see how they handle the whitespace challenge.

**Comment by feliperaul** [comment]
Thank you!
