### ISSUE TITLE
Model.reindex fails after upgrading to elasticsearch 6.3.0

### ISSUE THREAD

**Issue by jnimety** [ankane/searchkick#1252]
```
NoMethodError:
  undefined method `get_aliases' for #<Elasticsearch::API::Indices::IndicesClient:0x000000000d381d48>
  Did you mean?  get_alias
# /home/jnimety/.rvm/gems/ruby-2.5.0@control/gems/searchkick-3.1.2/lib/searchkick/index.rb:104:in `all_indices'
# /home/jnimety/.rvm/gems/ruby-2.5.0@control/gems/searchkick-3.1.2/lib/searchkick/index.rb:114:in `clean_indices'
# /home/jnimety/.rvm/gems/ruby-2.5.0@control/gems/searchkick-3.1.2/lib/searchkick/index.rb:265:in `reindex_scope'
# /home/jnimety/.rvm/gems/ruby-2.5.0@control/gems/searchkick-3.1.2/lib/searchkick/index.rb:195:in `reindex'
# /home/jnimety/.rvm/gems/ruby-2.5.0@control/gems/searchkick-3.1.2/lib/searchkick/model.rb:59:in `searchkick_reindex'
```

**Comment by mikelkew** [comment]
The latest 6.3.0 version of `elasticsearch-ruby` seems to have removed that method, hopefully unintentionally.

For now the easiest fix is to restrict the version with `gem 'elasticsearch', '~> 6.2.0'` and hopefully they'll restore that method in a future release - it seems to still be there in their master branch.

**Comment by brunodarshan** [comment]
Have a closed issue in `elasticsearch_ruby` project repo. That explains what the method was changed to `alias` https://github.com/elastic/elasticsearch-ruby/issues/509#issuecomment-439877605

**Comment by ankane** [comment]
Thanks @jnimety, @mikelkew, and @brunodarshan! From my testing, `get_alias` and `get_aliases` return the same response. Will push a new release once tests are green.

**Comment by CaioBianchi** [comment]
Has there been any progress on this issue?
