### ISSUE TITLE
Context around why Searchbox doesn't work

### ISSUE THREAD

**Issue by NRauh** [ankane/searchkick#1256]
The [deploying to Heroku section](https://github.com/ankane/searchkick#heroku) in the readme mentions that Searchbox doesn't work with Searchkick.

However, I was able set it up basically the same way as Bonsai, and don't seem to be having any problems.

I'm only doing pretty simple searching right now, but I haven't gotten any errors, and everything is being indexed right. So I'm wondering if the issues around Searchbox were around some features not working, or if it just flat out didn't work?

**Comment by ankane** [comment]
Hey @NRauh, I don't recall what the issue was. You can try running the test suite on it to see if it fully works now.

**Comment by NRauh** [comment]
I was going to try running the tests using it, then realized I wouldn't be able to, since the add on limits how many indices I can have, and I'm not able to upgrade it just to run the tests.

I noticed these constraint to the API in the documentation for Searchbox:

> Index refresh times and shard/replica counts can not be modified.

> Additionally, all administrative features of ElasticSearch are restricted from the API.

Just thought I'd mention that in case those would limit Searchkick, but I'm assuming they won't.

I'll close this issue since there's not much that can be done.
