### ISSUE TITLE
Searchkick works on console, but not on website [production]

### ISSUE THREAD

**Issue by Hiagulsho** [ankane/searchkick#1257]
The search works fine in development, but when testing the live website, searching throws an error:

`Searchkick::InvalidQueryError (Bad mapping - run Question.reindex)`

I've ran Question.reindex manually several times to no avail, it's still throwing the same error.
This is the search on the controller:

`Question.search @search_string, fields: [:title, :content], page: params[:page], per_page: 5`

Running just `Question.search @search_string, fields: [:title, :content]` works normally in the production console.

The Question model has no further configuration, just the `searchkick` function.

Searchkick logs contains this error:

```
All shards failed for phase: [query]
org.elasticsearch.index.query.QueryShardException: [match] analyzer [searchkick_search] not found
```

What's the difference in the production environment that's causing the problem?

Rails 6.0.0.beta3
ElasticSearch 7.0.0
Searchkick 4

**Comment by ankane** [comment]
Hey @Hiagulsho, this doesn't sound like an issue with Searchkick. Please check out the Contributing Guide for how to report issues and where to get help.
