### ISSUE TITLE
No benefit of using load: false, if active record relation is required

### ISSUE THREAD

**Issue by SumraYasmin** [ankane/searchkick#1258]
Hi @ankane
Related to this issue https://github.com/ankane/searchkick/issues/1173.
Currently I am using load: false with searchkick 3.1.1 but I need active record relation after searching because I have declared paths in rails views based on records. Now If I get all ids form results and then query model for records, load false seems useless. Please guide me.

**Comment by SumraYasmin** [comment]
Currently I am using load: false  with searchkick 3.1.1 but I need active record relation after searching because I have declared paths in rails views based on records. Now If I get all ids form results and then query model for records, load false seems useless. Please guide me.

**Comment by ankane** [comment]
Hey @SumraYasmin, check out the Contributing Guiding for how to file an issue.
