### ISSUE TITLE
Get suggestions limited to given filters?

### ISSUE THREAD

**Issue by tomas** [ankane/searchkick#1261]
Hi @ankane,

I'm trying out Searchkick and it works beautifully. However, I'm trying to get suggestions for a given search query that contains filters (e.g. `where: { account_id: 123 }`) but unfortunately the suggestions I get include keywords for items that are not available using the same filters. 

Is there any way I can limit the suggestions to results that match the same filters I'm giving in the first place? 

Thanks in advance

**Comment by ankane** [comment]
Hey @tomas, see #1183

**Comment by tomas** [comment]
Gotcha! Thanks
