### ISSUE TITLE
"reindex(resume: true)" does not work if model primary key isn't ID column.

### ISSUE THREAD

**Issue by taufek** [ankane/searchkick#1264]
I have a model that its primary key column is `uuid`. So when I tried to run `MyModel.reindex(resume: true)` I'm getting below error

```
D, [2019-05-28T01:22:41.029643 #53549] DEBUG -- :   MyModel Load (3.1ms)  SELECT  `my_models`.* FROM `my_models` WHERE (id > 30) ORDER BY `my_models`.`uuid` ASC LIMIT 5
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'id' in 'where clause': SELECT  `my_models`.* FROM `my_models` WHERE (id > 30) ORDER BY `my_models`.`uuid` ASC LIMIT 5
```

**Comment by ankane** [comment]
Hey @taufek, the `resume` option only works with numeric primary keys right now (and has the name `id` hard-coded). Happy to accept a PR to get it working with `uuid` columns and those not named `id`. Here's the relevant section of code: https://github.com/ankane/searchkick/blob/a763e06675b0273f6b3e8cef9ce700cb4aaf2895/lib/searchkick/bulk_indexer.rb#L27

**Comment by ankane** [comment]
Cleaning up issues, but feel free to submit a PR.
