### ISSUE TITLE
How to call a batch reindex from model

### ISSUE THREAD

**Issue by brunoocasali** [ankane/searchkick#1265]
Hi, @ankane 

After searching the README and code, I've pretty sure that is there a way to reindex data, inside the `BulkIndexer` but which is not accessible from the public API...

My problem is: 
I have many models in the app with more than 10m rows, but that rows not follow 1, 2, 3, but 1, 49, 87 and goes on... Because we have so many deletions and this breaks the auto increment... 

When I run a reindex with `Question.reindex(async: true, full: true)`, i've the reindex in batches but that batches counts each batch based on a fixed number and the maximum id of the model. This creates a ton of jobs that will do anything like:

```rb
[{"job_class"=>"Searchkick::BulkReindexJob", "job_id"=>"29849376-6c94-496c-adb4-84150958475f", "provider_job_id"=>nil, "queue_name"=>"searchkick", "priority"=>nil, "arguments"=>[{"class_name"=>"Question", "index_name"=>"questions_production_20190528013031810", "batch_id"=>405, "min_id"=>404047, "max_id"=>405046, "_aj_symbol_keys"=>["class_name", "index_name", "batch_id", "min_id", "max_id"]}], "executions"=>0, "locale"=>"pt-BR"}]
```

Looking for a way to deal with it, I've just found the solution in the line: https://github.com/ankane/searchkick/blob/master/lib/searchkick/bulk_indexer.rb#L32 

But I have no ideia how to call this directly from de `Model.reindex` way.

Sorry if i misunderstood the README but I'm pretty sure about that is not accessible, Let me now if could be a new feature or a PR I'm really excited to contribute to this project :D 

Thanks for the awesome gem!

**Comment by ankane** [comment]
Hey @brunoocasali, you should be able to fork the gem and change this line to `elsif false` to do what you want:

https://github.com/ankane/searchkick/blob/a763e06675b0273f6b3e8cef9ce700cb4aaf2895/lib/searchkick/bulk_indexer.rb#L99

Right now, I don't think it's common enough to add an option for.

**Comment by brunoocasali** [comment]
@ankane you remember you I fall into this condition? (without forcing it). Or this piece of code is a "unreachable zone" ?

**Comment by ankane** [comment]
There's not a good way to change the behavior of that conditional without forking it.

**Comment by BliZZ4RD** [comment]
Hi @ankane, I can't figure out why we need all these checks. If **starting_id** is a Numeric we also can use **.find_in_batches**. It will save us from creation a ton of blank background jobs if we could replace this code:
```
      if scope.respond_to?(:primary_key)
        # TODO expire Redis key
        primary_key = scope.primary_key

        starting_id =
          begin
            scope.minimum(primary_key)
          rescue ActiveRecord::StatementInvalid
            false
          end

        if starting_id.nil?
          # no records, do nothing
        elsif starting_id.is_a?(Numeric)
          max_id = scope.maximum(primary_key)
          batches_count = ((max_id - starting_id + 1) / batch_size.to_f).ceil

          batches_count.times do |i|
            batch_id = i + 1
            min_id = starting_id + (i * batch_size)
            bulk_reindex_job scope, batch_id, min_id: min_id, max_id: min_id + batch_size - 1
          end
        else
          scope.find_in_batches(batch_size: batch_size).each_with_index do |batch, i|
            batch_id = i + 1

            bulk_reindex_job scope, batch_id, record_ids: batch.map { |record| record.id.to_s }
          end
        end
      else
```
with #1277
