### ISSUE TITLE
total_count is maxed to 10_000

### ISSUE THREAD

**Issue by nicovak** [ankane/searchkick#1269]
Hi @ankane

Elasticsearch 7.0 changed a default behavior https://github.com/elastic/elasticsearch/pull/37466 so for results over 10_000 `total_count` will always be 10_000 (same as `size` method)

To keep the old behavior If I understood It right, we have to use `track_total_hits` options in request.
https://github.com/elastic/elasticsearch-ruby/blob/edf22b632b0867806560383598a5a35f4ee7f7e1/elasticsearch-api/lib/elasticsearch/api/actions/search.rb

I tried with

```ruby
MyModel.search('*', body: {track_total_hits: true})
```

It works like before, do you think we should always keep it as default in `Searchkick` gem ?

Without `track_total_hits`

![Without](https://i.imgur.com/rmvitz8.png)

With `track_total_hits`

![With](https://i.imgur.com/WLCpzAC.png)

Thanks!

**Comment by ankane** [comment]
Hey @nicovak, making it the default seems reasonable to me (so the behavior is more intuitive and consistent with previous versions). Feel free to submit a PR.

Out of curiosity, what's the difference in response times for the two queries?

**Comment by nicovak** [comment]
It is very strange, if you look on my screens we have the `took` value in `@response` and result with `track_total_hits` set to `true` is `0`.

My first need was to display the total of object in my index and the total of an aggregation search query. I think It will be more efficient to use `count` API  [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html) and [elasticsearch-ruby class](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/count.rb)

After a reflection maybe we should keep the Elasticsearch behavior. I will keep digging and maybe do a PR.

**Comment by ankane** [comment]
Thinking about it more, I think we should keep the default ES behavior for now. From the issue referenced above:

> I chose 10,000 as the default because that's also the number we use to limit pagination. This means that users will be able to know how far they can jump (up to 10,000) even if the total number of hits is not accurate.

It's a bit unintuitive (as is limiting results to 10,000), but I agree it makes more sense for pagination.
