### ISSUE TITLE
[Idea] Flag that warns if (second) misspellings query was triggered

### ISSUE THREAD

**Issue by jfloff** [ankane/searchkick#1273]
What do you think about having a "flag" on the results, indicating that the second misspellings query was triggered? 

This could be useful if we want to display some warning to the end-user, or just do some analytics on the queries that were misspelled the most.

Thank you,

**Comment by ankane** [comment]
Hey @jfloff, there's currently a `misspellings?` method on search results you can use for this.

```ruby
products = Product.search("aple", misspellings: {below: 5})
products.misspellings?
```

**Comment by jfloff** [comment]
Neat! Thanks!
