### ISSUE TITLE
No automatique mapping on Elastic search 7.1.1 

### ISSUE THREAD

**Issue by jeremygachet** [ankane/searchkick#1274]
Hi,

Thanks a lot for your excellent work. 
Unfortunatly, I even have a small issue. 
I'm on Elastic cloud on the 7.1.1 elastic search version. 

When I launch an index, the mapping is not taking into account. 
I had the same issue while moving from the 6.x to the version 7.0 and you fixed it before I was able to open an isue ;) .

Has an exemple, with the same code in the 7.0 I could have a field like that : 
    
```
      "step_label": {
        "type": "keyword",
        "fields": {
          "analyzed": {
            "type": "text",
            "analyzer": "searchkick_index"
          }
        },
        "ignore_above": 30000
      }
```

in the 7.1.1 it became the default one : 
```
      "step_label": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
```

It has the same behabiour with async: true or not. 

And when I try to add a specific mapping with  merge_mappings: true
The manually added mapping is the only one to be really added like if the automatique mapping did not worked at all

Thanks you in advance for your help!

**Comment by ankane** [comment]
Hey @jeremygachet, please use the gist in the Contributing Guide to reproduce.

**Comment by jeremygachet** [comment]
Hello @ankane I don't really understand what you await for me with this gist. 
Do I need to modify the code and execute it in my project ? 

I just updated to the master, and it works well without the asynch: true parameters
But If I synch with async: true, then I have the default ES mapping in my index. 

I had the exact same behavior when I moved between the es 6.x to 7.0
 
Is theire a command to mannually init the mapping before launching reindex ?

**Comment by ankane** [comment]
@jeremygachet you'll want to fork the gist and update it to demonstrate the issue. After you download it, you can run it with `ruby searchkick_repro.rb`. I just updated it to work with `async: true`.

**Comment by jeremygachet** [comment]
Hello, I got no issue anymore this morning after a bundle update.

**Comment by ankane** [comment]
Great, please try upgrading in the future before creating an issue, as mentioned in the Contributing Guide.
