### ISSUE TITLE
Hashie + Rails 6 #except compat

### ISSUE THREAD

**Issue by philipbjorge** [ankane/searchkick#1275]
Hi Ankane,
I understand if you want to close this one right away (I see you don't have much interest in moving away from hashie per #944 and #370).

When updating to Rails 6, `except` broke with hashie/searchkick which caused some of our app/specs to fail:
https://github.com/intridea/hashie/issues/476
https://github.com/intridea/hashie/issues/449

We've resolved this issue by patching in the old implementation, but it seems like this sort of regression will probably happen again in the future.

```
class Hash
  def except(*keys)
    dup.except!(*keys)
  end
end
```

Is it possible to get plain old hashes back from searchkick so we don't have to worry about compat issues?

**Comment by ankane** [comment]
Hey @philipbjorge, I have the same thoughts at #944. You can use the `response` method if you want to deal with hashes and avoid Hashie.

**Comment by philipbjorge** [comment]
@ankane -- If we access the `response` attribute, I believe that skips out on a lot of hit processing, yes?

I suppose maybe we could override `def results` in our application to do something like...

```
    def results
      @results ||= super.map(&:to_hash)
    end
```

**Comment by ankane** [comment]
It does a little processing, but yes, you could also call `to_hash` on the Hashie object to get a hash.
