### ISSUE TITLE
Update query options before execution

### ISSUE THREAD

**Issue by mengqing** [ankane/searchkick#1278]
Hi,

Trying to see how it is possible to update search options before execution.

eg: Following doesn't work
```
query = Foobar.search("*", execute: false, where: { id: 1 })
query.options[:where].merge!(id: 2)
query.execute
```

Is there anyway to update `query.body` automatically after `options` changed?

**Comment by mengqing** [comment]
I tried `query.send(:prepare)` which seemed to work, but is just wondering if there is another way of doing this without executing a private method

**Comment by ankane** [comment]
Hey @mengqing, there's not an official way to update options (by design). I'd recommend waiting until after the options are fully constructed before passing them to the `search` method.
