### ISSUE TITLE
RecordIndexer API Change?

### ISSUE THREAD

**Issue by philipbjorge** [ankane/searchkick#1279]
Hi @ankane,
We have a system right now where we are...

1. Performing full side by side reindexes
2. Processing changes from a queue into the primary aliased index

We would like to update step 2 and have it index into all indices associated with a model so that any changes get put into both the primary aliased index and the new index that is being built on the side.

On our side of things, we could implement this really cleanly with a backwards-compatible change to the `RecordIndexer` interface...

```
module Searchkick
  class RecordIndexer
    def initialize(record, index)
      @record = record
      @index = index || record.class.searchkick_index
    end
  end
end
```

Another nice change to the API, but not strictly necessary as we can use the RecordIndexer directly, would be to the `model#reindex` method...

```
def reindex(index = nil, method_name = nil, **options)
  RecordIndexer.new(self, index).reindex(method_name, **options)
end unless method_defined?(:reindex)
```

On our side of things, this enables the following:

```
record = model.find_or_initialize_tombstone(id)
all_indices_for(model).each do |index|
  record.reindex(index = index)
end
```

Is this a change you would accept to the project?

**Comment by ankane** [comment]
Hey @philipbjorge, I've considered adding full support for reindexing into multiple indexes. How is the `all_indices_for` method implemented?

**Comment by philipbjorge** [comment]
```
def all_indices_for(model)
  model.search_index.all_indices(unaliased: true)
      .map { |idx_name| Searchkick::Index.new(idx_name, **model.searchkick_options) }
end
```

**Comment by ankane** [comment]
Thanks. Re API change: Since `RecordIndexer` isn't a public API, it'd be best to make the change to the `reindex` method (`reindex(index: some_index)`). However, I think it'll introduce complexity that'll need to be dealt with when adding full support, so I'd prefer to hold off on the change for now.

**Comment by philipbjorge** [comment]
@ankane — I’m thinking we’ll monkey patch this in and keep an eye on diffs to watch for breaking changes.

Is there anything I can do to help aid in getting full support in place/going?

**Comment by archonic** [comment]
I think a public RecordIndexer API could help me as well. I'm using Apartment and I'm looking for a way to have one index for resources that are stored across all tenants. I was thinking something like this should work but RecordIndexer looks to be difficult to overwrite.

```
class Resource < ApplicationRecord
  searchkick word_start: [:name], index_name: document_index_name, callbacks: :async

  def self.reindex(method_name = nil, **options)
    Apartment::Tenant.each do |tenant|
      Apartment::Tenant.switch(tenant) do
        super(method_name, options)
      end
    end
  end
end
```

**Comment by ankane** [comment]
Just fyi, in Searchkick 5 (just released), you can do:

```ruby
Product.search_index(name: "other_index").reindex([product1, product2])
# or
Product.search_index(name: "other_index").reindex(Product.where(active: true))
```

(also, there were significant changes to the `RecordIndexer` class)

Feel free to create a new issue if you have any feedback / there's more to discuss.
