### ISSUE TITLE
[Idea] Partial match below - just like misspellings

### ISSUE THREAD

**Issue by jfloff** [ankane/searchkick#1283]
Would it make sense to have a partial matches `below` keyword, like there is for misspellings? 

`Product.search "fresh honey", operator_below: {operator: "or"; below: 5}`

This would first search `fresh AND honey` and then if there are fewer than 5 results, a 2nd search is performed with opertor `OR`

**Comment by ankane** [comment]
Hey @jfloff, makes sense to me if you want to put together a PR. It should probably trigger after `misspellings` below. I also think we can reuse the existing `operator` option instead of creating a new `operator_below`.

**Comment by jfloff** [comment]
I will take a jab at the PR :)

Regarding the option, how should we approach the `default` vs the `below` operator then? How about this? 
`Product.search "fresh honey", operator: { default: "AND", below: { "OR" : 5 " } }`

**Comment by ankane** [comment]
I'm thinking we can just do `operator: {below: 5}`. It should always go from `AND` to `OR`.

**Comment by jfloff** [comment]
Hi there, Just a heads up that at the moment I'm a bit swamped with work in other areas. Just feel free - if you don't want to keep the issue open - to close the issue, and then when I'm done with the new feature I will just submit a PR.

**Comment by ankane** [comment]
👍
