### ISSUE TITLE
Multiple AND queries with nested OR queries

### ISSUE THREAD

**Issue by hashwin** [ankane/searchkick#1284]
Hi,

I was wondering whether it's possible to do something like:
Let's say I have 2 fields A and B. The result I need is this:
(A = 1 or A > 5) and (B = 10 or B < 5)

Right now it only seems possible to pass OR queries into the _or value. 

If not currently possible, maybe one option is to allow something like:
```
Model.search('*', where: { a: { _or: [1, {gt: 5}]}, b: { _or: [10, { lt: 5 }]}})
```

**Comment by ankane** [comment]
Hey @hashwin, it's not documented, but there's also an `_and` operator you should be able to use for this.

```ruby
where = {
  _and: [
    {_or: [{a: 1}, {a: {gt: 5}}]},
    {_or: [{b: 10}, {b: {lt: 5}}]}
  ]
}
Model.search('*', where:
```

**Comment by hashwin** [comment]
Perfect, thanks a lot @ankane. Would be helpful to others with the same question if this was in the docs.
