### ISSUE TITLE
ES 7.2, Model.reindex failed

### ISSUE THREAD

**Issue by OKaderka** [ankane/searchkick#1287]
Update from ES 6.8 to ES 7.2 (hosted by elastic cloud)
searchkick 4.0.2
ruby 2.6.0
rails 5.2.3
postgres 

Console: Model.reindex failed:
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [153] contains an unknown parameter [_indexme]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [153] contains an unknown parameter [_indexme]"},"status":400})

**Comment by ankane** [comment]
Hey @OKaderka, please use the gist in the Contribute Guide to reproduce.

**Comment by OKaderka** [comment]
I close it und will wait ;-)
There are different behaviours now. 

I changed local ES to 7.2 now , and i get 
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"},"status":400})

Same Code on cloud version 7.2 (ES):
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [153] contains an unknown parameter [_indexme]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [153] contains an unknown parameter [_indexme]"},"status":400})

I dont know where the field "_indexme" is coming from????

Elastic 6.8 with searchkick 3 is working on Local and Production, with no errors.

rake test with local 7.2:
Running against Elasticsearch 7.2.0
-- create_table(:products)
   -> 0.0140s
-- create_table(:stores)
   -> 0.0004s
-- create_table(:regions)
   -> 0.0003s
-- create_table(:speakers)
   -> 0.0003s
-- create_table(:animals)
   -> 0.0003s
-- create_table(:skus, {:id=>:uuid})
   -> 0.0003s
-- create_table(:songs)
   -> 0.0002s
Run options: --seed 19004

# Running:

........SS.S.S................................S.................[searchkick] WARNING: Records in search index do not exist in database: 63
....................S.......S.........................................SSSSSSS.......S....DEPRECATION WARNING: ActionView::Base instances should be constructed with a lookup context, assignments, and a controller. (called from new at /Users/olafkaderka/development/searchkick/test/pagination_test.rb:93)
.............[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
....[searchkick] WARNING: Case-insensitive flag does not work with Elasticsearch
...[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch
.................S....S...............................S......................................................................................SS.SS.....[searchkick] WARNING: Records in search index do not exist in database: 532, 533, 534, 535
...[searchkick] WARNING: Passing child models to models option throws off hits and pagination - use type option instead
............[searchkick] WARNING: Passing child models to models option throws off hits and pagination - use type option instead
[searchkick] WARNING: Records in search index do not exist in database: 20
[searchkick] WARNING: Passing child models to models option throws off hits and pagination - use type option instead
[searchkick] WARNING: Passing child models to models option throws off hits and pagination - use type option instead
..........[searchkick] WARNING: Records in search index do not exist in database: 10
...
Fabulous run in 49.856842s, 7.0602 runs/s, 11.4929 assertions/s.
352 runs, 573 assertions, 0 failures, 0 errors, 22 skips

**Comment by bbugh** [comment]
I'm having this same issue suddenly with Bonsai, because their sandbox forces the latest version, which is 7.2 Our production is on 6.x which is working fine. I assume our searchkick version doesn't support the latest version, but this seems like it could cause issues with version mismatches...

@OKaderka did you figure this out?
