### ISSUE TITLE
[idea] Searchkick::Query#or

### ISSUE THREAD

**Issue by DanielHeath** [ankane/searchkick#1289]
I propose being able to call `#or` on a `Searchkick::Query`, passing in a second query; this would return anything that matches both.

This would produce a really nice DSL for generating more complex behavior.

**Comment by ankane** [comment]
Hey @DanielHeath, thanks for the suggestion. Query objects have a lot of complexity (suggestions, aggregations, etc), so I think it'd be difficult to combine them this way. Can you explain your use case a bit more?

**Comment by DanielHeath** [comment]
Hmm, I can see that being trickier. 

I was finding it quite hard to build more complex queries, but wasn't using aggregation or suggestions. I ended up using multi-search and merging the results ruby-side (meaning results aren't interleaved, but I didn't need that in my case).

**Comment by ankane** [comment]
Yeah, multi-search is better for that case.
