### ISSUE TITLE
Possibility using negation for term like

### ISSUE THREAD

**Issue by bestwebua** [ankane/searchkick#1291]
Hi, Andrew! Thanks for the awesome gem!!! I have a question with ```like``` using. Is it possible (maybe in next releases) use negation for ```like```?:

```ruby
Model.search(where: { some_column: { not: { like: '%query%' }})
```
Call with this params raises error:
```ruby
# Searchkick::InvalidQueryError: [400]
{
  "error":{"root_cause": [
    {
      "type":"parsing_exception",
      "reason":"[term] query does not support [like]",
      "line":1,
      "col":102
    }
  ],
  "type":"parsing_exception",
  "reason":"[term] query does not support [like]",
  "line":1,
  "col":102},
  "status":400
}
```

Of course, possible to reach the same behaviour using ```_not```:
```ruby
Model.search(where: { _not: { some_column: { like: '%query%' }}} )
```
Thank you!

**Comment by ankane** [comment]
Hey @bestwebua, it's a bit confusing, but `not` is actually "not equal/not in" whereas `_not` is negation of a condition. Is there a reason you'd prefer a new syntax over the existing one?

**Comment by bestwebua** [comment]
And now I'm confused) The both calls return the same result.
```ruby
User.search(where: {_not: {id: [4302, 4303]}}).results == User.search(where: {id: {not: [4302, 4303]}}).results
=> true
```
With the new syntax is possible more clear composing params for ```.search``` method, like in example below:
```ruby
def predicate_resolver(predicate, value)
  {
    EQUAL => value,
    NOT_EQUAL => { not: value },
    CONTAINS => { like: "%#{value}%" },
    NOT_CONTAINS => { not: { like: "%#{value}%" }}
  }[predicate]
end
```

**Comment by ankane** [comment]
That's expected. `not(id in X) == id not in X`. I'm not convinced another syntax is needed.

**Comment by bestwebua** [comment]
It's just suggestion. Your gem works like a charm. Thanks!
