### ISSUE TITLE
[Activerecord] Error indexing a record prevents it being saved

### ISSUE THREAD

**Issue by DanielHeath** [ankane/searchkick#1295]
I recently ran into an issue where my ES cluster ran into a serious error and returned an error for all writes. 

This was awkward, since it meant search results stopped updating. 

However, even worse, it caused all database writes on searchable models to raise an exception! Users couldn't even log in (since that updates the last_login_at field, triggering a reindex of the record).

I'd prefer to provide an error handler in the searchkick configuration and have all errors sent there instead. Does that sound like a reasonable approach?

For instance:

```
class User
  searchkick error_handler SearchkickErrorHandler.new
end

class SearchkickErrorHandler
  def handle(exception)
    # Notify ops, or something
  end
end
```

**Comment by ankane** [comment]
Hey @DanielHeath, thanks for the great description. It seems like error handling could be useful for callbacks (Elasticsearch errors for `inline`, Active Job errors for `async`, and Redis errors for `queue`). For manual calls to reindex, I think it's still desirable to raise an error.

You should be able to accomplish this now with:

```ruby
class User
  searchkick callbacks: false

  after_commit :reindex_with_error_handling

  def reindex_with_error_handling(*args)
    reindex(*args)
  rescue => e
    # handle error
  end
end
```

Similar to your suggestion, we could do something like:

```ruby
class User
  searchkick rescue_callbacks: ->(e) { ... }
end
```

**Comment by ankane** [comment]
Cleaning up issues
