### ISSUE TITLE
Failed to parse content to map: Duplicate field

### ISSUE THREAD

**Issue by pawneetdev** [ankane/searchkick#1299]
I am using the **master branch** and I am unable to reindex when using **custom mapping**. It has stopped working after the last few commits. I am getting the following error.

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Duplicate field 'name'\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@31008853; line: 1, column: 5137]"}},"status":400}`

When I set merge_mapping to false, it just works fine.

**Comment by ankane** [comment]
Hey @pawneetdev, please use the gist in the Contributing Guide to reproduce. Also, which version was it working on?

**Comment by pawneetdev** [comment]
Hey @ankane! Fixed the issue. Turns out gem 'oj' conflicts when using custom mapping. Removed the gem, everything seems to work fine.
