### ISSUE TITLE
Elastic Dump Types

### ISSUE THREAD

**Issue by jondavidchristopher** [ankane/searchkick#1300]
Hi there, 

I am using this to move some ES data around:

https://github.com/taskrabbit/elasticsearch-dump

I believe that I would need to move:

analyzer
mapping
type

for their "types" in order to bring everything that searchkick creates from one ES cluster to another. Can you let me know if I am missing anything? I am intentionally leaving out alias because it looks like it may not be needed if you name the index correctly.

Thanks in advance!

**Comment by ankane** [comment]
Hey @jondavidchristopher, I haven't worked with that tool, so not really sure. Let us know what you find out.

**Comment by jondavidchristopher** [comment]
@ankane I couldn't get this to work even when copying all types. What tools do you guys use for data replication of ES? For example if you want to mirror production to staging?
