### ISSUE TITLE
Rails 6: searchkick:reindex:all does nothing, but Model.reindex works

### ISSUE THREAD

**Issue by bbugh** [ankane/searchkick#1301]
Hi! 👋

Since upgrading to Rails 6, our `searchkick:reindex:all` command does nothing or  reindexes only one model. Manually forcing a single class via `rake searchkick:reindex CLASS=Model` does work, though.

I've compared to the latest `develop` branch that the Rails 6 branched off of yesterday, and it's working fine. We haven't changed anything with searchkick since Rails 6.

**Issue**

Running `searchkick:reindex:all` does not behave as expected.

- review and staging: just prints `Reindex complete`
- local development: reindexes `Project`, then says `Reindex complete`. We have 5 indexed models. 
    - the one model that is reported to be reindexed works as expected 

The settings for each model are identical because they're all using the same `include Searchable` module that sets up searchkick. 🤷🏽‍♂️ The callbacks (when updating a model) are working fine, it appears that just the rake task is broken.

**Reproduction steps**

1. Run `rake searchkick:reindex:all`, it appears to not do anything
1. I confirmed that the index actually is not present by opening the console and doing `Model.search`, which raises a missing index error.
2. I tried to manually reindex with `Model.reindex` and that worked.
3. `Model.search` then succeeds and the index is present.
1. I delete the index with `curl`, and repeat the process.

**Problem source?**

It appears to me that the `Rails.application.eager_load!` in the `reindex:all` task isn't working as expected. 

https://github.com/ankane/searchkick/blob/07108c0b6d5893052ff09b25660388166df89701/lib/tasks/searchkick.rake#L18-L20

```
» rails c
[1] pry(main)> Searchkick.models
=> [Project (call 'Project.connection' to establish a connection)]
```

**Comment by ankane** [comment]
Hey @bbugh, it looks like it's due to this issue: https://github.com/rails/rails/issues/37006

I've pushed a fix to the `eager_load` branch, but want to see what happens with Rails before merging it. https://github.com/ankane/searchkick/compare/eager_load

**Comment by bbugh** [comment]
Thank you for the very fast and helpful reply! That does seem to be the issue. 🙏

```
[1] pry(main)> Searchkick.models
=> [Project (call 'Project.connection' to establish a connection)]

[2] pry(main)> Rails.application.eager_load!
=> nil

[3] pry(main)> Searchkick.models
=> [Project (call 'Project.connection' to establish a connection)]

[4] pry(main)> Zeitwerk::Loader.eager_load_all
=> [#<Zeitwerk::Loader:0x00007fc595cae088 ...> 

[5] pry(main)> Searchkick.models
=> [Project (call 'Project.connection' to establish a connection),
 Model2 (call 'Model2.connection' to establish a connection),
 Model3 (call 'Model3.connection' to establish a connection),
 Model4 (call 'Model4.connection' to establish a connection)]
```

**Comment by ankane** [comment]
Unfortunately, there hasn't been any movement on the Rails side, so decided to merge. Will add a conditional later to only apply the fix to affected versions of Rails 6. Thanks again for reporting @bbugh!

**Comment by bbugh** [comment]
My hero! Thank you for all of the awesome stuff you do, @ankane!

**Comment by bbugh** [comment]
Confirmed working, thank you!
