### ISSUE TITLE
Proposal: add matching "models" API for indices_boost

### ISSUE THREAD

**Issue by latortuga** [ankane/searchkick#1302]
With the release of v4, the API for `index_name` changed to `models`. I assume this is just a cosmetic change because it looks like the old name is still supported and no functionality related to it looks changed. However, the API option for `indices_boost` was not updated to match and I think it would be a good fit. You can even see how you updated the docs [here](https://github.com/ankane/searchkick/commit/7ce0440ab4f2fdd02a52b2bcf42fb4f90e668667#diff-04c6e90faac2675aa89e2176d2eec7d8R1497) but not the related API.

Here's my proposed update to match:

```
# current
Searchkick.search "milk", models: [Product, Category]
indices_boost: {Category => 2, Product => 1}

# proposed
Searchkick.search "milk", models: [Product, Category]
models_boost: {Category => 2, Product => 1}
```

**Comment by ankane** [comment]
Hey @latortuga, happy to make `models_boost` an alias for `indices_boost` for consistency. Feel free to submit a PR.

**Comment by ankane** [comment]
Cleaning up issues, but PR comment still stands
