### ISSUE TITLE
Nested fields in searchable?

### ISSUE THREAD

**Issue by kapso** [ankane/searchkick#1306]
I have a model `Product` which will have a `title` column that is basically a hash to localize the title in any language. The title can be localized in any language. So something like this -

```ruby
product = Product.create(title: { en: "This is an Apple" })
```

Is is possible to pass a nested field to `searchable:`? I tired the following, but doesn't work. Since I dont know what all languages the title will get localized in, I need a dynamic way to manifest the nested languages.

```ruby
class Product < ApplicationRecord
  searchkick callbacks: false, searchable: ['title.*']
end
```

**Comment by kapso** [comment]
@ankane any way to do this? thanks.

**Comment by ankane** [comment]
Hey @kapso, Searchkick has very limited support for nested fields, so you'd need to use custom mapping and searching to do this.
