### ISSUE TITLE
Model.reindex CLASS=Model error

### ISSUE THREAD

**Issue by trungnemo** [ankane/searchkick#1307]
Hi SearchKick Dev
I deploy the Elastic Point at amazon ES
After i set the initialized successfully, i run the command to build the index for my type, i got the error i do not know, please help me. 

class IpAgent < ApplicationRecord
   searchkick
   
   def search_data
      {
        address: address
      }
    end
end

"
IpAgent.reindex CLASS=IpAgent
  IpAgent Load (631.6ms)  SELECT "ip_agents".* FROM "ip_agents" ORDER BY "ip_agents"."id" ASC LIMIT $1  [["LIMIT", 1000]]
  IpAgent Update (1267.3ms)  {"count":229,"exception":["TypeError","IpAgent(id: integer, refid: string, name: string, address: string, created_at: datetime, updated_at: datetime, status: integer) **is not a symbol nor a string**"],"exception_object":"IpAgent(id: integer, refid: string, name: string, address: string, created_at: datetime, updated_at: datetime, status: integer) is not a symbol nor a string"}
Traceback (most recent call last):
        1: from (irb):1
TypeError (IpAgent(id: integer, refid: string, name: string, address: string, created_at: datetime, updated_at: datetime, status: integer) is not a symbol nor a string)

"

**Comment by ankane** [comment]
Hey @trungnemo, check out the Contributing Guide for where to get help.
