### ISSUE TITLE
FORBIDDEN/12/index read-only / allow delete (api)

### ISSUE THREAD

**Issue by zoegod911** [ankane/searchkick#1312]
This comment fixes the issue, but it happens again after every .reindex call.

is there any config file, where I can set this permanently?

```
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
```
source: https://benjaminknofe.com/blog/2017/12/23/forbidden-12-index-read-only-allow-delete-api-read-only-elasticsearch-indices/

_Originally posted by @salihsagdilek in https://github.com/ankane/searchkick/issues/1040#issuecomment-354158085_

**Comment by ankane** [comment]
Hey @zoegod911, my guess is this is configurable, but you'd need to check the Elasticsearch docs.

**Comment by zoegod911** [comment]
So in my `/etc/elasticsearch/elasticsearch.yml` file:

`index.blocks.read_only_allow_delete: nil`

I have that set under the long commented out config info. I still get: 

```
Searchkick::ImportError at /products

{"type"=>"cluster_block_exception", "reason"=>"index [products_development_20190920003420003] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"} on item with id '1220'
```

Whenever I create a Product project, only was around is to comment out my `searchkick` call in my model and uncomment after creation. Happens a ton on seeding too.

**Comment by zoegod911** [comment]
Fixed: I did the cURL command after setting `index.blocks.read_only_allow_delete: nil` in my `/etc/elasticsearch/elasticsearch.yml` and reindex'd.

No recurring `Searchkick::ImportError` after reindexes or model creates, any longer!
