### ISSUE TITLE
Start word with single character searching issue in searchkick

### ISSUE THREAD

**Issue by viral85** [ankane/searchkick#1314]
Hi Searchkick,

I have using this plugin with elastick search and getting issue. Issue is:

If I type 'a' and hit search, I got this from rails console:

curl http://localhost:9200/offers_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"bool":{"should":[{"dis_max":{"queries":[{"bool":{"must":{"bool":{"should":[{"match":{"name.word_start":{"query":"A","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}},{"match":{"name.word_start":{"query":"A","boost":1,"operator":"and","analyzer":"searchkick_word_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"should":{"match":{"name.analyzed":{"query":"A","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}}}}]}}]}},"timeout":"11s","_source":false,"size":10000}'

and after that I found the following keyword as highlighted:
"Semi Automatic and automatic Die-Cutters"
's' insead of 'a'. Let me know if you're getting the same or provide any idea about the same.

Thanks

**Comment by ankane** [comment]
Hey @viral85, if you think you've found a bug with Searchkick, please use the gist in the Contributing Guide to reproduce.

**Comment by ankane** [comment]
Closing due to no response
