### ISSUE TITLE
How to boost first for a field, and then by recency?

### ISSUE THREAD

**Issue by metalelf0** [ankane/searchkick#1315]
Hi, I'm trying to build a pretty standard `Post` search, and my scenario is the following: I want to search in some indexed fields (boosting the title), and then boost results by recency.

My query is the following: 

```
Post.search(
  "query_string",
  fields:  ["title^2", "parsed_excerpt", "parsed_body", "post_date", "author.name", "category.name"],
  boost_by_recency:  post_date: { scale: "7d", decay: 0.5 }}
)
```

This doesn't work as expected, as it seems the recency boost overweights the `title` field boost, so that I do have a list of recent posts, but the string is matched regardless in the post title and the other fields. I played with boost values, but neither raising the title boost to `^10` or adding a lower factor to the recency boost seems to do the trick.

Am I doing anything wrong here? Is it a matter of tuning weights, or is there anything else I need to know? Let me know if you want to see the query debug output.

Thanks in advance, and keep up the great work!

**Comment by metalelf0** [comment]
I've written a ES query that seems to work, but I can't get it working in Searchkick:

```
{
  "query": {
    "function_score": {
      "query": {
        "multi_match" : {
          "query" : "search term",
          "fields": ["title.analyzed^3", "parsed_excerpt.analyzed^2", "parsed_body.analyzed"]
        }
      },
      "functions": [
        {
          "exp": {
            "post_date" : {
              "origin": "2019-09-26",
              "offset": "7d",
              "scale" : "30d"
            }
          }
        }
      ],
      "boost_mode" : "sum"
    }
  },
  "_source": ["title", "parsed_excerpt", "post_date"]
}
```

Any help about translating this to Searchkick?

**Comment by ankane** [comment]
Hey @metalelf0, you can use explain to breakdown the scoring: https://github.com/ankane/searchkick#debugging-queries. Also, you can use the `body` option to pass a query directly to ES (if `boost_by_recency` isn't doing what you expect).
