### ISSUE TITLE
Cannot boost by combination of multiple fields

### ISSUE THREAD

**Issue by jamesformica** [ankane/searchkick#1317]
Hi SearchKick,

We have some complicated boosting logic as part of our query and have hit a limitation that we wanted to verify. We have multiple boosting factors based on single fields, however we have a new requirement to add a new boost based on two fields. 

For example we've been looking for something like the following pseudo code:
```
boost_where { fields: [field1 = 'abc', field2 = 'def'], factor: 10000}
```

The underlying elastic search query would look something like:

```
{
  "query": {
    "function_score": {
      "functions": [{
        "filter": [{
          "bool": {
            "must": [
              { "term": { "field1": true } },
              { "term": { "field2": "something" } }
            ]
          }
        }],
        "weight": 10000
      }],
      "score_mode": "sum"
    }
  }
}
```

Is this currently possible in SearchKick?
I understand we can add a new field to our indexed data which is a combination of the two fields and query against that, however, we are trying to avoid doing so.

Appreciate any help, cheers.

**Comment by ankane** [comment]
Hey @jamesformica, this isn't possible without writing a custom query right now, but happy to review a PR for it.

**Comment by ankane** [comment]
Cleaning up issues, but the comment above still stands
