### ISSUE TITLE
Latest Faraday breaks searchkick

### ISSUE THREAD

**Issue by pacMakaveli** [ankane/searchkick#1320]
Hi ankane,

You probably now this since you've fixed it on master. But just wanted to make it obvious since it took me a couple of hours to figure out why it wasn't working.

faraday 0.16.2 breaks searchkick `Model.reindex` and `Model.searchkick_index.delete` from what I've experienced so far. `Modal.find().reindex` works find though.

```
2.6.1 :001 > Collection.reindex
Traceback (most recent call last):
        1: from (irb):1
FrozenError (can't modify frozen String)
2.6.1 :002 >
```

Master seems to force faraday `0.15.4` which, as I said, works fine.
Can we please maybe have a 4.0.2 release? Some people might get stuck with the same issue.

Thanks!

**Comment by ankane** [comment]
Hey @pacMakaveli, Faraday just released 0.17.0 which fixes the issue: https://github.com/lostisland/faraday/releases/tag/v0.17.0
