### ISSUE TITLE
Using Searchkick in non-rails project

### ISSUE THREAD

**Issue by drop-harsh** [ankane/searchkick#1321]
Hi,

We are having a little unique case, where we have ruby(2.6.3)-Sinatra(2.0.5) application using activerecord(5.2.3) and sidekiq(4.2.10). Wondering if there is a way we can use Searchkick somehow? As of now, I keep getting this error `Harshly handling: Active Job not found`

Thanks for helping!

**Comment by ankane** [comment]
Hey @drop-harsh, Searchkick can be used without Rails, but you'll need to install Active Job if you want to use any features that use background jobs.
