### ISSUE TITLE
[Idea] Nested Query DSL

### ISSUE THREAD

**Issue by danielwheeler1987** [ankane/searchkick#1323]
Howdy, Recently worked on a project where we need to fork searchkick and add strong nested query support. I wanted to reach out to see if this is something you thought we could add to master? The query support we created looked something like this...

```ruby
{
    ":_and"=>[
      {
        "nested"=>{
          "path"=>"additional_search_data.completed_content",
          "where"=>{
            "content_id"=>"ae4112a0-8882-49ed-b176-863023c916c5"
          }
        }
      },
      {
       "nested"=>{
          "path"=>"additional_search_data.completed_content",
          "where"=>{
            "content_id"=>"7f58153a-8519-42de-9747-d048905b8c79"
          }
        }
      }
    ],
    "active"=>true
  }
```

Doing so allowed us to quick spin up queries without having to write the entire query via the ES dsl.

**Comment by ankane** [comment]
Hey @danielwheeler1987, in general, I'm hesitant to add support for nested queries since it's only needed for limited cases and it'll add a lot of complexity to support it throughout the library. Can you explain your use case a bit more?

**Comment by danielwheeler1987** [comment]
@ankane, yes. The user case would allow the usage of constructing complex multiple nested queries and determining the boolean operation to determine results for such queries. Previously, without the changes I made to ensure we could handle multiple nested behavior... The boolean operation (bool/must) was not being constructed in the ES query as I assumed it would.

**Comment by ankane** [comment]
Hey @danielwheeler1987, that use case is pretty abstract. Can you explain it in terms of a real-world application? "we have an application for X that uses nested fields to store Y data..."

**Comment by ankane** [comment]
Closing due to no response
