### ISSUE TITLE
`Model.reindex(async: true)` calls includes when enqueueing jobs

### ISSUE THREAD

**Issue by dhnaranjo** [ankane/searchkick#1325]
Hello! So, I've got a model that I'm indexing with info from like... 11 associations. I noticed that when I call `Model.reindex(async: true)` that it queries all of the `include`'d associations, even though it's only taking the IDs and passing them to my job queue.

It looks like this line:
https://github.com/ankane/searchkick/blob/6e6e921314ce9f9af47719ff003373cebc9007a0/lib/searchkick/bulk_indexer.rb#L30
might resolve the issue in the case of non-full but still async reindex jobs.

The app I'm working on is unfortunately currently not on a supported Rails version (sigh), so I'm just gonna chug along as it is, but I think it would be a nice fix for users that could benefit from a new version.

Thanks for y'alls efforts.

**Comment by ankane** [comment]
Thanks @dhnaranjo, nice find and thanks for the detailed explanation. Fixed on master. It's just one line, so you might be able to backport in a fork.
