### ISSUE TITLE
Integration with Ahoy

### ISSUE THREAD

**Issue by ACPK** [ankane/searchkick#1326]
I have successfully integrated Searchkick with Searchjoy. After doing so, I found that Searchjoy assocates searchs to users using a user_id. 

@ankane - Based on your experience with Searchjoy and Ahoy, do you have any recommendations on integrating searchjoy with Ahoy besides replacing user_id with visit_token or visitor_token?

**Comment by ankane** [comment]
Hi @ACPK, the `user_id` -> `visit/visitor_token` change is the only one I can think of.
