### ISSUE TITLE
Support for multi-fields

### ISSUE THREAD

**Issue by thejazz15** [ankane/searchkick#1328]
Elastic Search suggests the use of [multi-fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) to index the same field in different ways for different purposes. A basic example - A field could be mapped as a `text` field for `full-text search`, and as a `keyword` field for `sorting`.

A custom mapping of this would look like:
```
{
  "mappings": {
    "properties": {
      "name": {
        "type": "text",
        "fields": {
          "raw": { 
            "type":  "keyword"
          }
        }
      }
    }
  }
}
```

And a query would look like the following:
```
GET my_index/_search
{
  "query": {
    "match": {
      "name": "Jim" 
    }
  },
  "sort": {
    "name.raw": "asc" 
  }
}
```

Does Searchkick provide a way to do this? How does the `search_data` function work with `name.raw` and `multi-fields` in general?

(ElasticSearch v6.2.4)

**Comment by ankane** [comment]
Hey @thejazz15, Searchkick uses multi-fields internally. Take a look at the mapping to see how it's structured. There's no difference when passing data to Elasticsearch for multi-fields, so `search_data` just works.

To customize fields fully, you'll need to use a custom mapping.

**Comment by thejazz15** [comment]
Appreciate the prompt response. I did take a look at the custom mapping and I have been using it.
Let's say this was my mapping:
```
{
  "mappings": {
    "properties": {
      "name": {
        "type": "text",
        "fields": {
          "raw": { 
            "type":  "keyword"
          }
        }
      }
    }
  }
}
```

And my `search_data` function looks like this:
```
def search_data
  {
    "name" => name,
    "name.raw" => name
  }
end
```

On Reindexing, it would result in these errors.
> Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"Could not dynamically add mapping for field [name.raw]. Existing mapping for [name] must be of type object but found [text]."}

Where am I going wrong here?

**Comment by ankane** [comment]
Hey @thejazz15, unfortunately, I don't have the bandwidth to help with app-specific issues. Check out the Contributing Guide for where to get help.
