### ISSUE TITLE
No handler for type [keyword] declared on field

### ISSUE THREAD

**Issue by minosahu31** [ankane/searchkick#1330]
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [address]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [property]: No handler for type [keyword] declared on field [address]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [address]"}},"status":400}
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:206:in `__raise_transport_error'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/base.rb:327:in `perform_request'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-7.3.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-api-7.3.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/elasticsearch-api-7.3.0/lib/elasticsearch/api/actions/indices/create.rb:82:in `create'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/searchkick-4.0.0/lib/searchkick/index.rb:16:in `create'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/searchkick-4.0.0/lib/searchkick/index.rb:207:in `create_index'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/searchkick-4.0.0/lib/searchkick/index.rb:274:in `reindex_scope'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/searchkick-4.0.0/lib/searchkick/index.rb:200:in `reindex'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/searchkick-4.0.0/lib/searchkick/model.rb:59:in `searchkick_reindex'
	from (irb):57
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/ubuntu/.rvm/gems/ruby-2.4.1/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'

**Comment by minosahu31** [comment]
While running **Property.reindex** file. Please help me to get out of this.

**Comment by ankane** [comment]
Hey @minosahu31, if you think you've found a bug, please use the gist in the Contributing Guide to reproduce.

**Comment by minosahu31** [comment]
Resloved th issue. It is because of using old elasticsearch ( 2.3.1 ) version. Upgraded (6.8) and working fine.
