### ISSUE TITLE
Possible to boost by lower number?

### ISSUE THREAD

**Issue by adambedford** [ankane/searchkick#1336]
It looks like boosting works by giving a boost to documents where the value in the boosted field is bigger. e.g. The readme example of `orders_count`.

Is it possible to invert this and boost documents where the value in the boosted field is lower. For example, measuring average response time of a contractor in a marketplace and boosting those who respond faster.

**Comment by ankane** [comment]
Hey @adambedford, one option is to index the inverse of the field (`1.0 / field_value`). There's also a report of `boost_by_distance` working for non-location fields (https://github.com/ankane/searchkick/issues/241#issuecomment-256975965) (lower is better), but this isn't something I've tried or is tested.

**Comment by adambedford** [comment]
Thanks @ankane, that's a great idea. Given that we'll now be dealing with large decimal numbers, can you confirm that we'll need to use the `mappings` option with the `searchkick` macro...and consequently will need to construct an ES query directly with the `body` option? Is there a way to specify a field type without having to bypass the 'magic' of searchkick and go directly to ES for the query?

**Comment by ankane** [comment]
You'll need to use a custom mapping to override field types. If the custom mapping isn't too different, you can likely still use Searchkick to construct the query, but you'll have to experiment.
