### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadGateway

### ISSUE THREAD

**Issue by SanMane** [ankane/searchkick#1339]
I recently migrated to **searchkick** from **elasticsearch-rails** considering how easy searchkick is to operate. 

After migration I am facing below issue in my production(heroku); I am not facing any issues in my local as well as on staging(identical to prod).

`Elasticsearch::Transport::Transport::Errors::BadGateway: [502] <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> </body> </html>`

Maybe this issue is occurring because Elasticsearch is running out of memory? Where do I start with this issue? 

Since its production I cant enable the debug mode also theres no definite way to reproduce it. I am using **Bonsai** service on heroku.

**Comment by ankane** [comment]
Hey @SanMane, unfortunately, don't have the bandwidth to help with issues related to hosted providers. I'd try contacting the service provider directly.
