### ISSUE TITLE
Reindexing large batches asynchronously

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#1340]
Assuming model `Product` has `searchkick callbacks: :async`, what's the recommended performant way to reindex a large batch of records that, however, are only a subset of the entire Product catalog?

If we use Parallel reindexing (`Product.reindex(async: true)`), after we promote the index_name we are actually replacing the entire index, so it can only be used when it's desired to reindex the entire Product catalog. 

`Product.where(query).reindex` will reindex those records sequentially and not use background jobs. 

`Product.where(query).find_each{|product| product.reindex }` will use background jobs, but it has to loop through every single record first to create a job.

Am I missing an alternative?

**Comment by ankane** [comment]
Hey @feliperaul, it sounds like you have a good understanding of the options that Searchkick provides. I think the best way is to create a background job that runs `Product.where(query).reindex`.

**Comment by feliperaul** [comment]
@ankane Thank you!
