### ISSUE TITLE
total_count limited to max_result_window (10k) (again)

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#1341]
Ankane, I'm reopening this discussion because I think the current behavior is terrible for user experience, and the other issues are closed and I can't comment on them. The fact I'm the third one opening an issue about it is telling. It's biting people. 

Before upgrading to ES 7:

```
Property.search("*").total_count
=> 56047
```

After upgrading:
```
Property.search("*").total_count
=> 10000
```

In my humble opinion, this is just ... plain **wrong**. I'd even go as far as calling it a bug. Also, there's no warning about what's going on, no log message in development, no info on the documentation on `results.total_count`, also no info on why this happens and how to fix it. 

I see ElasticSearch as a search gem to make ES search engine much more user friendly, so I think you should set sane defaults even when ES doesn't (like they definitely haven't here). 

I don't even know how to fix this, I already have `max_result_window` set to 20000 and it still returns 10000; I also tried using `limit`, to no avail:

```
[17] development (main)> Property.search("*", limit: 20000).total_count
=> 10000
```

**This is a very simple requirement: to know the total amount of records.** 

It's used in pagination and now it's broken `(showing 1 to 30 of 10.000 records)`, when in reality we have 5x more records.

**Comment by feliperaul** [comment]
Also, I tried passing `body: { track_total_hits: true }`, but it raises `Options incompatible with body option: where, order`, so it's pretty much unusable for any query considering it's not compatible with `where` and `order`.

**Comment by ankane** [comment]
Hey @feliperaul, thanks for the feedback. As the other issues have mentioned, there's [a reason](https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html) this is the behavior. I agree it's not very intuitive and Searchkick should make things intuitive when possible, but this setting could have an impact on the availability of Elasticsearch, which is why this decision was originally made.

I've addressed one of your concerns by updating the documentation. I'd also be open to considering changing this in the next major version (when ES 8 comes out) if benchmarks show that this shouldn't really be an availability concern.

Also, please be less negative when participating in the community going forward. Phrases like "plain wrong" aren't helpful for a productive discussion.

**Comment by feliperaul** [comment]
@ankane First of all... you're totally right. Reading back my comment now it _clearly_ shows needless negativity. I'm deeply sorry by this. Thanks for calling me on it, I'm not like that. 

It's not an excuse, but I was *really* not having a good day yesterday and it ended up being reflected in this post. 

Having said that, the documentation change is great. Allow me just give you my 2c: I think the wording on the `Advanced Search` could be a little clearer. I digged through it yesterday and found the `body` option, but missed the `body_options` option.

My suggestions:

Where it currently reads:
```
Advanced Search
And use the body option to search:
```

I would write something like:
```
Advanced Search
Use the `body` option if you want to entirely replace the body of the ElasticSearch query with your payload:
```

And where it currently reads:
```
To modify the query generated by Searchkick, use:
```

I would write something like:
```
However, if you want to keep the query payload generated by Searchkick, but make modifications on it before it gets sent to ElasticSearch, provide a hash to the `body_options` param (we'll merge it with ours):
```

I'm not a native english speaker so that's just a draft 😬

Lastly, thanks again for the amazing work on this and your other gems, and I apologize again for the tone of the first post.

**Comment by ankane** [comment]
No worries, I appreciate the apology. Will take a look at the wording/suggestion for the advanced search section when I have a chance.
