### ISSUE TITLE
Where Null Data

### ISSUE THREAD

**Issue by muhrizkiakbar** [ankane/searchkick#1342]
Hi, im trying to where date with null data, but ive got nothing data.
How to fix this, thanks

`@m_sukus=MSuku.search( '*' , where: { discarded_at: nil }, load: true , debug: true , page: params[:page], per_page: 30)`

**Comment by ankane** [comment]
Hey, @muhrizkiakbar, `where: {field: nil}` is the correct way to query null data. Please check out the Contributing Guide for where to get help.

**Comment by muhrizkiakbar** [comment]
> Hey @muhrizkiakbar, `where: {field: nil}` is the correct way to query null data. Please check out the Contributing Guide for where to get help.

i was do that, please see my code 
field = discarded_at
