### ISSUE TITLE
Specify Default Shards and Replicas on a per environment basis

### ISSUE THREAD

**Issue by dydx** [ankane/searchkick#1345]
Heya,

Currently trying to solve a small issue I'm having where the default Sharding and Replication exceeds a limit placed by Bonsai for ephemeral clusters.

It appears that for environments outside of `test`, Searckick asks for 5 Shards and 1 Replica.

It also appears that this is can be modified in the model, which is nice:

```
class Product < ApplicationRecord
  searchkick settings: { number_of_shards: 3, number_of_replicas: 2 }
end
```

What I am interested in is whether or not these default settings can be modified in an environment file or in an initializer.

Something like the following comes to mind:

config/environments/staging.rb
```
  Searchkick.config do |c|
    c.number_of_shards = 1
    c.number_of_replicas = 0
  end
```

That just globally modifies the default when I want to do so.

Is something like this doable?

I have tried using `model_options` similarly to how it is described in the Reference section of the Readme:

```
  Searchkick.model_options = {
    number_of_shards: 1,
    number_of_replicas: 0
  }
```

But I am met with the following error:

```
NoMethodError: undefined method `model_options=' for Searchkick:Module
```

**Comment by ankane** [comment]
Hey @dydx, `model_options` is the preferred way to do this (`settings` should be the top-level key). You probably need to upgrade Searchkick if it's not available.

**Comment by dydx** [comment]
Nice! That got it.

```
  Searchkick.model_options = {
    settings: {
      number_of_shards: 1,
      number_of_replicas: 0
    }
  }
```
