### ISSUE TITLE
Request preference

### ISSUE THREAD

**Issue by hashwin** [ankane/searchkick#1346]
Hi @ankane,

How do I set the shard preference for a request?
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#request-body-search-preference

I can't seem to any reference to it in searchkick, getting ```ArgumentError: unknown keywords: preference```

**Comment by ankane** [comment]
Check out `request_params`.

**Comment by hashwin** [comment]
Thanks, @ankane .
I tried it, but I don't see the parameter in the query.
It shows this:
```Lead Search (44.0ms)  curl http://localhost:9200/leads_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":...```

Is this the real query or just a representation of it? I guess I would like to see all the params that are being sent, including the routing_id which I  can't currently see as well.

**Comment by ankane** [comment]
It's just a representation to make debugging easier for developers. It looks like it doesn't include `request_params` - will fix that.
