### ISSUE TITLE
Searchkick::InvalidQueryError after upgrading

### ISSUE THREAD

**Issue by archonic** [ankane/searchkick#1347]
On Sidekiq 3.x and ES 6.x, the following was working:

```
Import.search(
  "import",
  fields: [{ id: :exact }, :document_names]
).results
```

After upgrading to Searchkick 4.x and ES 7.x, it's raising `Searchkick::InvalidQueryError`. It seems to have a problem with `{ id: :exact }` mixed with the other items in the array. I can have just `{ id: :exact }` or `:document_names` in fields but not both.

**Comment by ankane** [comment]
Hey @archonic, can you use the gist in the Contributing Guide to reproduce?

**Comment by ankane** [comment]
Closing due to no response
