### ISSUE TITLE
Filter association with white spaces and special characters

### ISSUE THREAD

**Issue by ahmadabdelhalim** [ankane/searchkick#1348]
Hi, 
I'm trying to filter "products" by "department_name" but the thing is that the department name is usually something like "Sports & Kids", so whenever I try to filter by the entire sentence, I don't get anything. Is there's a way to handle special characters and white spaces?

**Comment by ankane** [comment]
Hey @ahmadabdelhalim, can you use the gist in the Contributing Guide to reproduce the issue?

**Comment by manusalgueiro** [comment]
Could it work to have an auxiliary hash that contains [ special_character : equivalent_word ] (i.e. '&' for 'and') replace the character for the value and then filter the sentence or, if it does not mean a word just delete it?

**Comment by ankane** [comment]
@manusalgueiro Thanks for the suggestion but I'm not sure I understand the original issue. Going to close until there's a gist to reproduce.
