### ISSUE TITLE
Searchkick::InvalidQueryError (Bad mapping - run Customer.reindex):

### ISSUE THREAD

**Issue by matthewford** [ankane/searchkick#1351]
Hi,

We've been running for a few months without any issues, but yesterday and today we ran into an issue where the index was getting corrupted and breaking.

The error we see is: 

     Searchkick::InvalidQueryError (Bad mapping - run Customer.reindex):

Versions we are running: 
* searchkick (3.1.2)
* ES v6.5.1

We have a nightly reindex task run so there should be a new index each day, however we are needing to completely reindex again once we hit this issue.

The error isn't easily reproducible, I was wondering if anyone else has run into this issue, or would upgrading help?

Thanks.
 
---
Searchkick settings:

```
  searchkick callbacks: false, word_start: [:first_name, :last_name, :full_name, :responsible_customer_name]

  def search_data
    {
      id: id,
      first_name: first_name,
      last_name: last_name,
      full_name: full_name,
      group_id: group_id,
      organisation: organisation,
      responsible_customer_name: responsible_customer.try(:name),
      dob: dob,
      dob_string: dob.to_s
    }
  end
```

**Comment by matthewford** [comment]
I've tried to upgrade searchkick and elasticsearch to the latest releases, but now I see the following error:

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [customer : {_routing={}, dynamic_templates=[{string_template={mapping={ignore_above=30000, type=keyword, fields={analyzed={analyzer=searchkick_index, index=true, type=text}}}, match_mapping_type=string, match=*}}], properties={full_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, last_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, first_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, responsible_customer_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}}}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [customer : {_routing={}, dynamic_templates=[{string_template={mapping={ignore_above=30000, type=keyword, fields={analyzed={analyzer=searchkick_index, index=true, type=text}}}, match_mapping_type=string, match=*}}], properties={full_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, last_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, first_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, responsible_customer_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}}}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [customer : {_routing={}, dynamic_templates=[{string_template={mapping={ignore_above=30000, type=keyword, fields={analyzed={analyzer=searchkick_index, index=true, type=text}}}, match_mapping_type=string, match=*}}], properties={full_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, last_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, first_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}, responsible_customer_name={ignore_above=30000, type=keyword, fields={word_start={analyzer=searchkick_word_start_index, index=true, type=text}, analyzed={analyzer=searchkick_index, index=true, type=text}}}}}]"}},"status":400}
`

**Comment by matthewford** [comment]
Looks similar to this issue https://github.com/ankane/searchkick/issues/1234

**Comment by ankane** [comment]
The first issue sounds like it's due to multiple reindexes running at once. See https://github.com/ankane/searchkick/issues/1316 for more details and ways to address.

The second sounds like a version mismatch between Searchkick and Elasticsearch (similar to issue you mentioned above).

**Comment by matthewford** [comment]
Thanks, we'll look at using import to keep the records in sync. Odd we're using a Heroku scheduler, there is a chance it ran before the deployment and ran twice.

**Comment by ankane** [comment]
Added a safety check on master to prevent the `Bad mapping` error.

**Comment by ankane** [comment]
Cleaning up stale issues
