### ISSUE TITLE
Issue searching string with numbers

### ISSUE THREAD

**Issue by sheilacodonnell** [ankane/searchkick#1352]
Hello,

I am attempting to search by a field called `iata_number` which is a string of numbers, ex: "123456". The search is not returning any results. I am able to search other string fields on the model like name and email with no problems. Any ideas? Thanks!

Model
```
class Agency < ActiveRecord::Base
  searchkick callbacks: :queue,
    settings: { number_of_shards: 1, number_of_replicas: 1 },
    word_start: [:iata_number]

  def search_data
    {
      iata_number: iata_number
    }
  end

end
```

Controller
```
  def create
    @search = Agency.search(params[:q],
      fields: [:iata_number],
      match: :word_middle,
      page: params[:page] || 1,
      per_page: params[:per_page],
      load: false
    )
    respond_with @search
  end
```

**Comment by ankane** [comment]
Hey @sheilacodonnell, it looks like there's `word_start` in the model but `word_middle` in the search method. If that doesn't solve it, please use the gist in the Contributing Guide to reproduce.

**Comment by ankane** [comment]
Cleaning up issues
