### ISSUE TITLE
[Idea] Support for "Parallel Reindexing using reindex(async: true) on non-integer primary columns"

### ISSUE THREAD

**Issue by bharathramM** [ankane/searchkick#1354]
Hi,

 We have an application which contains around 10L records.

Now we need to do a bulk reindexing as the data we stored has a larger set of modifications.

As per the documents, we are trying to do a parallel reindexing.  But it didn't work with our case.
The below command we used for reindexing.
`reindex(async: true)`

After analyzing the source code, we have found that parallel reindexing will work only if the primary column is an integer.  In our case, the column data type is non-integer (UUID).

Could you please suggest to us how to proceed with our case.

Thanks!

**Comment by ankane** [comment]
Hey @bharathramM, looking at the code, non-integer ids should be supported: https://github.com/ankane/searchkick/blob/4e4d831e5d6eaf1a213d9bf806f274f0d3cb4604/lib/searchkick/bulk_indexer.rb#L111-L115

What error message are you seeing?

**Comment by bharathramM** [comment]
Hi @ankane, the issue is with `reindex(resume: true)`
When we are using `reindex(async: true)` it interrupted due to some unavoidable circumstances, while trying to resume it by using `reindex(resume: true)` below-mentioned error occurred.

`ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  operator does not exist: uuid > integer
LINE 1: ...xxxx".* FROM "xxxx" WHERE (id > 0) ORDER...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT  "xxxx".* FROM "xxxx" WHERE (id > 0) ORDER BY "xxxx"."id" ASC LIMIT $1`

**Comment by ankane** [comment]
Hey @bharathramM, didn't see anything about `resume` in the original description, but check out #1264.
