### ISSUE TITLE
Re-Indexing via Queue

### ISSUE THREAD

**Issue by aximuseng** [ankane/searchkick#1355]
I am trying to set-up indexing via `queue`:

https://github.com/ankane/searchkick#queuing

to me the documentation is not clear:

> Then, set up a background job to run.
> 
> Searchkick::ProcessQueueJob.perform_later(class_name: "Product") 

Do I add this as a call back method in the model?  If so what do I name it?

**Comment by ankane** [comment]
Hey @aximuseng, in most cases, you'll want to use a scheduler to schedule to job at a regular interval (like every minute). This will allow the queue to build up so it can be efficiently processed at once.

**Comment by aximuseng** [comment]
Ahhh... ok so that sits in the background and when you run that action it clears the internal Searchkick queue.

So I just ran that from the console:

```
[5] pry(main)> Searchkick::ProcessQueueJob.perform_later(class_name: "Location")
Enqueued Searchkick::ProcessQueueJob (Job ID: 5d5c791d-913f-46d1-8c14-3f6665c7d869) to Sidekiq(searchkick) with arguments: {:class_name=>"Location"}
=> #<Searchkick::ProcessQueueJob:0x00007feb0685a108 @arguments=[{:class_name=>"Location"}], @executions=0, @job_id="5d5c791d-913f-46d1-8c14-3f6665c7d869", @priority=nil, @provider_job_id="d2dc901723f7d9a2e60263de", @queue_name="searchkick">
```

but the job seems to be stuck in the queue (over 5 minutes now).  Sidekiq and Redis are running.  Thoughts before I start looking into Sidekiq / Redis issues?

**Comment by ankane** [comment]
I'd make sure Sidekick is configured to process the `searchkick` queue.

**Comment by aximuseng** [comment]
🤦‍♂️ had sidekiq running in another rails app folder.

Side issue now - I am using active_record_multi tenant.  I need to set my tenant somehow.  The Aprtment gem worked great for this.  One big downside now for switching.
