### ISSUE TITLE
Conflicts with Maginalia Gem

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1358]
I found the index job has conflicts with https://github.com/basecamp/marginalia gem

<img width="829" alt="Screenshot 2020-01-14 17 08 55" src="https://user-images.githubusercontent.com/2749593/72424404-e5fc7f00-37c0-11ea-8d32-b6ca46a2cc56.png">

The error message is quite ambiguous, I wonder does anyone know where to look at ? 🤔

**Comment by ankane** [comment]
Hey @berniechiu, looks like this error was fixed in Marginalia: https://github.com/basecamp/marginalia/pull/95.

**Comment by berniechiu** [comment]
Nice thanks!
