### ISSUE TITLE
Searchkick deploy to Heroku with AWS

### ISSUE THREAD

**Issue by rctneil** [ankane/searchkick#1361]
Hi,

I've deployed my super tiny app to the free tier on Heroku and need to get Elastic Search working. I have followed the readme for AWS but I get the following error:

> Faraday::ConnectionFailed: Failed to open TCP connection to es-domain-1234.us-east-1.es.amazonaws.com:443 (getaddrinfo: Name or service not known)

What setup is required at AWS's end? I'm a complete novice in regards to ES and I only use iSearchkick for a very basic search in my app.

Any further information would be greatly appreciated.

Neil

Update:  I've actually managed to get it to connect but now i get this error:

> Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[0031c5e6467af91b3cc93ccc153dd3a6][x.x.x.x:9300][indices:admin/create]"}],"type":"illegal_argument_exception","reason":"Token filter [searchkick_index_shingle] cannot be used to parse synonyms"},"status":400}

Any thoughts?

**Comment by ankane** [comment]
Hey @rctneil, glad you got it to connect. Can you post the solution so others can see it?

For the `cannot be used to parse synonyms` error, please use the gist in the Contributing Guide to reproduce.

**Comment by ajmiciano** [comment]
Hi, I have some problem here. Any solution?

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Token filter [searchkick_index_shingle] cannot be used to parse synonyms"}],"type":"illegal_argument_exception","reason":"Token filter [searchkick_index_shingle] cannot be used to parse synonyms"},"status":400}`
