### ISSUE TITLE
[Idea] A more efficient :async reindex for partial indexes.

### ISSUE THREAD

**Issue by TruRooms** [ankane/searchkick#1362]
We have run into an issue where we would only like to partially index a model.

Using the `:async` in conjunction with `should_index?`, we were seeing that every record was being queued to the worker, which would then make a determination on whether to index.

For the volume of records that should not be indexed, it was creating a lot of excess load for our worker processes.

The kludge that we came up with is below. It basically imparts the logic of `should_index?` before the record is enqueued.

```
searchkick callbacks: false

after_save :enqueue_index, if: :should_index?

def enqueue_index
  if self.respond_to?(:search_routing)
      routing = self.search_routing
    end

    Searchkick::ReindexV2Job.perform_later(
      self.class.name,
      self.id.to_s,
      nil,
      routing: routing
    )
end
```

**Was this the best way forward** and would you be open to a PR implementing this functionality?

**Comment by ankane** [comment]
Hey @TruRooms, that approach looks fine if the value of should_index never changes for a record. I don’t want to support more indexing patterns right now, but I appreciate the PR thought.
