### ISSUE TITLE
Reliable Re-indexing

### ISSUE THREAD

**Issue by yagudaev** [ankane/searchkick#1364]
At work, we do re-indexing automatically every time we deploy a new version of the app. We saw some errors and started looking into how indexing works.

Searchkick Pro mentioned the ability to do reliable reindexing. However, the link to Searchkick Pro has been removed and I can't find it anywhere. This leads me to believe it is no longer being offered.

https://ankane.org/introducing-searchkick-pro

Reading a little about zero down-time deploys with Elastic Search it talks about using index aliases. So my question is, does Elastic Search 7 offers this by default now? If so, does searchkick now use this feature and therefore does reliable indexing by default?

**Comment by ankane** [comment]
Hey @yagudaev, Searchkick has always used the alias method recommended by Elasticsearch, but it isn't perfect, as explained by the blog post. Unfortunately, Searchkick Pro is no longer available, and there aren't plans to merge it into Searchkick, as it adds some complexity.

On a separate note, I'd highly discourage reindexing on every deploy, and reserve it for the following situations: https://github.com/ankane/searchkick#to-reindex-or-not-to-reindex
