### ISSUE TITLE
Searchkick, time series data, and daily multiple indexes

### ISSUE THREAD

**Issue by wflanagan** [ankane/searchkick#1366]
I've searched through the history and documentation and StackOverflow, but haven't found a good answer to a problem we've had for more than a week now on our staging server.

We recently migrated from Cassandra to Postgres/ES. We have a LOT of data that comes in on a daily basis, and our best guess (according to our ES person) is that we should have a daily index for this table (we'll call it "mentions").  

But, for the life of me, I can't seem to figure out how to correctly configure Searchkick to make this work.

If we set in the model the index name to a daily index name: 

````
index_name: -> { "#{name.tableize}_#{Rails.env}_#{Time.now.utc.strftime("%y%m%d"}" }
````

When we do a query, we can't seem to access anything but the current day's data. 

When we set it to, nothing, or to this:

````
index_name: -> { "#{name.tableize}_#{Rails.env}" },
````
We will, after a day, start getting an error.

````
Searchkick::ImportError: {"type"=>"illegal_state_exception", "reason"=>"index and alias names need to be unique, but the following duplicates were found [mentions_production (alias of [mentions_production/gHd9x__hRWe3H6Q1Slx_9w])]"} on item with id '65783'
````

How do you configure to write into a daily index, but query the entire alias/group?

I'm sure this isn't a bug in SearchKick, but rather a "documentation" bug. But, I'd assume this is a pretty common setup.. not sure why we can't make it work. ES version is 7.5.1.

**Comment by ankane** [comment]
Hey @wflanagan, you can likely make it work, but Searchkick isn't designed for this use case. I'd recommend using the Elasticsearch client directly.

**Comment by wflanagan** [comment]
@ankane Thanks for the feedback. 

So, I guess I'm somewhat confused then. Do most people keep their entire database in 1 index in ES? I thought that generally speaking, doing that was a really bad practice if it's of any size?

**Comment by ankane** [comment]
By default, Searchkick uses 1 index per model. It looks like you're trying to do time-based partitioning. You can pass `index_name` to the `search` method to specify a different index to search, which may work with your first code example. Check out the Contributing Guide for where to get additional help.
