### ISSUE TITLE
Rendering a partial

### ISSUE THREAD

**Issue by matthewford** [ankane/searchkick#1368]
Hi,

I'm looking to render a partial with a collection of results.

`= render partial: 'result', collection: @orders
`

However, on Rails 5.2, I'm getting the following error:
```undefined method `param_key' for nil:NilClass```

I assume this is due to not having ActiveModel::Naming included in the searchkick results? Any ideas on how to resolve this?

Thanks!

**Comment by ankane** [comment]
Hey @matthewford, calling `to_a` should give you can array of records, which you can pass to `collection`.

**Comment by matthewford** [comment]
Hey, I seem to already have an array of `[#<Searchkick::HashWrapper _id="296780"`  items.

**Comment by matthewford** [comment]
Actually I think the issue was the partial was calling dom_id, which was trying to call AR naming methods.
