### ISSUE TITLE
Will running searchkick in multiple rails apps on the same machine clobber each other?

### ISSUE THREAD

**Issue by benlieb** [ankane/searchkick#1369]
We have multiple branches of the same app running in different git worktrees and ports on the same machine for staging. 

Will the indexing in one app affect the others? And if so, is there a way to configure each app/port to have it's own index?

Thanks for the great work!

**Comment by ankane** [comment]
Hey @benlieb, you can use `index_prefix` to use separate indexes for each branch.

**Comment by benlieb** [comment]
@ankane That did it thanks. Might be worth adding some info about that (more detail I mean) to the readme.
