### ISSUE TITLE
import_scope does not create correct index

### ISSUE THREAD

**Issue by milani** [ankane/searchkick#1371]
It is hard to reproduce the issue with code due to concurrency difficulties but it is easy to grasp:

The `reindex` method in the `index.rb` has two kinds of branches:
1. `reindex_scope` branch: it is called when doing a full-reindex. At some point, it calls `create_index` function which creates the index with correct settings and mappings.
1. `import_scope` branch: If for any reason I call reindex on a relation without doing a full-reindex, it never calls `create_index` and elasticsearch creates a mapping from `search_data`. This does not always match the defined mappings. I ran into this issue when removing and creating the index in a thread and indexing documents in another thread.

Is this on purpose? Can we call `create_index` if index does not exist? Or can we at least make sure it fails without creating an index on the fly?

**Comment by ankane** [comment]
Hey @milani, that's the intended behavior. You can disable automatic index creation on your cluster with: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation.
