### ISSUE TITLE
[Idea] Combine the results of multi_search

### ISSUE THREAD

**Issue by KellyBennett** [ankane/searchkick#1372]
Hello, 
I have a issue similar to https://github.com/ankane/searchkick/issues/951#issue-240770836

The answer there suggests that multi_search is somewhat interchangeable with [Multi-Model](https://github.com/ankane/searchkick#multiple-models) search, however, in my case that's not quite true.

Say you have some index (Brands, for example), and a ProductVariants index where each document represents a specific size/price/etc variation of a Product.
To make the ProductVariants index useful, I need to collapse on "product.id". For this reason, I can't simply use the Multiple-Model approach and must use Multi-Search. 

⛔️ `Searchkick.search( "<query>", aggs: [:whatever], models: [Brand, ProductVariants], body_options: {collapse: { field: "product.id" }}`

But something like this will work:
```
brand_query = Brands.search("<query>", aggs: [:name], execute: false)
product_query = ProductVariants.search( "<query>", aggs: [:whatever], execute: false, body_options: {collapse: { field: "product.id" }}
Searchkick.multi_search([brand_query, product_query])
```

If multi-search gave me back a combined result set, I could do something like
```
results =  SearchKick.multi_search(brand_query, product_variant_query)
…
aggregations = results.aggs
```

**Comment by ankane** [comment]
Hey @KellyBennett, thanks for the suggestion. I don't think there's a standard way to combine results from multi-search, so I think it's better left to each application.
