### ISSUE TITLE
 undefined method  for #<Elasticsearch::Model::Response::Result:0x00007f57001e5bf0> 

### ISSUE THREAD

**Issue by mices** [ankane/searchkick#1373]
The objects returned don't have their associations In the code below although u equates to a single user with addresses rails complains the object  addresses are undefined

<h3><%= (t 'search_results_for') %> <%= @terms %></h3>
<ul>
 <% @users.each do |u| %>
  <li> 
  	<%= link_to "#{u.first_name} #{u.middle_name} #{u.last_name}", page_path(name: u.name) %>
    <%= "     " %>
        <% ua=u.addresses.where("current=?", true) %>
		<% if ua.country=="US" %>
			<%= ua.city %>, <%= ua.state %> <%= ISO3166::Country.find_country_by_alpha2(ua.country) %>
		<% else %>
			<%= ua.city %>, <%= ISO3166::Country.find_country_by_alpha2(ua.country) %>
		<% end %>
  </li>
 <% end %>
</ul>

**Comment by ankane** [comment]
Hey @mices, it looks like you're using `elasticsearch-model` instead of Searchkick.
