### ISSUE TITLE
Reindexing active record subset not removing index entry if should_index? false

### ISSUE THREAD

**Issue by pplant** [ankane/searchkick#1375]
Hi,

for resource saving reasons I'm trying to reindex only a subset of records. Since the nature of the records allows to unpublish single entries I have a should_index? function that is returning false if a record gets unpublished. When running a full reindex after a unpublish event the record disapears from the index however when running a reindex over a subset not. Is this a wanted behaviour?

**Comment by ankane** [comment]
Hey @pplant, can you use the gist in the Contributing Guide to demonstrate the issue?
