### ISSUE TITLE
Searchkick results custom ordering results based on named scope of active record

### ISSUE THREAD

**Issue by seemalakishore** [ankane/searchkick#1376]
I have an active record model configured with searchkick.

class Interview < ActiveRecord::Base

default_scope {order("start_time DESC")}  //default sorting based on start time which is a date time column

DEFAULT_STATUS_ORDER = [
    "Scheduled",
    "Completed",
    "Cancelled",
    "In Progress",
    "Suspended"
  ]

scope :sorted_by_status, -> (order=DEFAULT_STATUS_ORDER) do
    case_body = order.each_with_index.map{|status, i| "WHEN status=\"#{status}\" THEN #{i}"}.join("\n")
    reorder("CASE #{case_body} ELSE #{order.size} END")
  end   // Named scope to sort the interview records to group and order based on status field in a custom ordering

end

How can I apply the sort_by_status scope to order the searchkick results as required.

The scope works fine with Active Record querying.

**Comment by ankane** [comment]
Hey @seemalakishore, check out the Contributing Guide for where to get help.
