### ISSUE TITLE
how do i show associations of result objects

### ISSUE THREAD

**Issue by mices** [ankane/searchkick#1377]
Sorry to have to ask for help in here I asked this question on SO https://stackoverflow.com/questions/60068983/how-do-i-implement-associations-in-searchkick but nobody answered yet and a comment by user gaotam seems to deter others from answering

<h3><%= (t 'search_results_for') %> <%= @terms %></h3>
<ul>
 <% @users.each do |u| %>
  <li> 
  	<%= link_to "#{u.first_name} #{u.middle_name} #{u.last_name}", page_path(name: u.name) %>
    <% ua=u.addresses.where("current=?, limit: 1", true)  %>
		<% if ua.country=="US" %>
			<%= ua.city %>, <%= ua.state %> <%= ISO3166::Country.find_country_by_alpha2(ua.country) %>
		<% else %>
			<%= ua.city %>, <%= ISO3166::Country.find_country_by_alpha2(ua.country) %>
		<% end %>
  </li>
 <% end %>
</ul>

**Comment by ankane** [comment]
Hey @mices, I'm sorry you haven't received a good answer yet, but the issue tracker is reserved for bugs and feature discussions.
