### ISSUE TITLE
Filter use a ActionController::Parameters.new object failed.

### ISSUE THREAD

**Issue by zw963** [ankane/searchkick#1382]
## reproduce

Following is a example for describe this issue:

```rb
filter = {user_id: '6183270', dtend: {gte: start_date+1.day}, dtstart: {lte: end_date}}
```
Following code working well.

```rb
result = Booking.search('*', fields: [
      :confirm_number, :user_name, :user_email,
      :house_name, :house_address
    ], where: filter, debug: true)
```

Elasticsearch Query
curl http://localhost:9200/bookings_test/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"bool":{"must":{"match_all":{}},"filter":[{"term":{"user_id":"6183270"}},{"range":{"dtend":{"from":"2020-03-02T00:00:00.000+09:00","include_lower":true}}},{"range":{"dtstart":{"to":"2020-03-31T23:59:59.999+09:00","include_upper":true}}}]}},"timeout":"11s","_source":false,"size":10000}'

But if use this code from Rails controller, pass a ActionController::Parameters object into instead of a hash, will failed.

```rb
params = ActionController::Parameters.new(filter)
result = Booking.search('*', fields: [
      :confirm_number, :user_name, :user_email,
      :house_name, :house_address
    ], where: params, debug: true)
```

Searchkick::InvalidQueryError: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] query does not support [gte]","line":1,"col":108}],"type":"parsing_exception","reason":"[term] query does not support [gte]","line":1,"col":108},"status":400}

## Workaround

For now, the only working solution is:

```
params.permit!
filter = params.to_h.deep_symbolize_keys
# use filter as where condition working.
```

## Following is my version info:

 searchkick (4.1.1)
Rails 5.2.3

**Comment by ankane** [comment]
Hey @zw963, thanks for reporting! This type of query is supposed to throw an error to prevent users from changing operators by default. Otherwise, code like:

```rb
User.search("*", where: {user_id: params[:user_id]})
```

could be changed to a not query, regex query, prefix query, or any other operator, which I think would surprise most developers.

I've also pushed an update to raise an error before the query is sent to Elasticsearch.

**Comment by zw963** [comment]
Hi, we reproduce this issue on production, even, it never raised any exception,
which confused me a lot, because it just not working as expected, and return wrong result.

Following is process:

1. We  accept params in controller
2. We invoke params.permit! in controller
3. We pass params directly as where filter.
4. this error was ignored silently, get wrong error!

But, wired,  when test this parameters issue in test, it always raise error.

```rb
    x =  ActionController::Parameters.new(
      {user_id: '6183270', dtend: {gte: start_date+1.day}, dtstart: {lte: end_date}}
    )

    x.permit!

    result = Booking.search('*', fields: [
      :confirm_number, :user_name, :user_email,
      :house_name, :house_address
    ], where: x, debug: true)
```

```sh
Error:
BookingSearchTest#test_booking_search:
Searchkick::InvalidQueryError: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[term] query does not support [gte]","line":1,"col":108}],"type":"parsing_exception","reason":"[term] query does not support [gte]","line":1,"col":108},"status":400}
    test/models/booking_search_test.rb:83:in `block in <class:BookingSearchTest>'
```

**Comment by zw963** [comment]
Another wired things,  x.permit! and then pass x as where filter, it working my local laptop rails development env ... but not working on production.

**Comment by ankane** [comment]
Hey @zw963, can you use the gist in the Contributing Guide to reproduce?

**Comment by zw963** [comment]
Sorry for late,  there is no context for reproduce this issue, 

thank you for help, i will try reproduce it when use searchkick next time.
