### ISSUE TITLE
Number of results before misspellings 

### ISSUE THREAD

**Issue by jfloff** [ankane/searchkick#1384]
Hi,

Is it possible to know how many results were returned before the 2nd misspellings query was triggered?

Thanks,

**Comment by ankane** [comment]
Hey @jfloff, there’s not a way to get this info, but you can manually perform a search without misspellings and again with them to get it.

**Comment by jfloff** [comment]
Would you be open for a quick PR with that attribute? Something like `before_misspellings_count`?

**Comment by ankane** [comment]
Can you explain your use case for it? My initial thought is it's not common enough to add.

**Comment by jfloff** [comment]
On our specific case we were wondering how many times we have results in the first one vs results in the second search. Its more for the analytics team to look at how many items are needed (when we indeed have no results) vs when we have low quantity (we only got 2/3 results).

**Comment by GMolini** [comment]
Hi. I would also very much like this feature. Also it would be great to have a list of the "corrected terms" that provided the results. (although I dont know if this is possible) It would be to do something like: We couldnt find any results for X, showing results for Y

**Comment by ankane** [comment]
Hey @jfloff, sorry for the very long delay. The use case and naming makes sense to me, so feel free to submit a PR if you're still using Searchkick.

@GMolini I'm not aware of a way to get the corrected terms, but feel free to submit a PR if you know of a way.
