### ISSUE TITLE
Single index for multiple Models?

### ISSUE THREAD

**Issue by mjfrey** [ankane/searchkick#1386]
Is there a way to have a single index for multiple models?  I have a multi-tenant application with a lot of models / data and am concerned this will generate many shards / indexes.

**Comment by ankane** [comment]
Hey @mjfrey, you might be able to hack it, but Searchkick is designed to have one index per model.

**Comment by mjfrey** [comment]
@ankane thanks for the response.  Is this best practice?  To have an index per model?  I am new to Elasticsearch so sorry for the naive questions. 

Even without using searchkick I see that Elasticsearch-model uses the same approach.  An index per model.  

By doing this does it not aside from creating many indexes -- skew the score for terms since each index scores itself?

**Comment by ankane** [comment]
Check out the Contributing Guide for a better place to get help with those questions.
