### ISSUE TITLE
Nested query does not appear to work

### ISSUE THREAD

**Issue by james-reading** [ankane/searchkick#1389]
In my `Retailer` class I have:

```
searchkick  searchable: ['products.name']
```
and
```
def search_data
  {
    products: products.active.pluck(:name).map { |name| { name: name } }
  }
end
```

Now say I have a `Retailer` with 2 products: one with a name of 'Bread roll' and another with a name of 'Sausage meat'.

I then search for 'sausage roll':
```
Retailer.searchkick('sausage roll', fields: ['products.name'])
```

I do not expect the retailer to match, but it does. How can I make it so that a multi-word ('and' operator) query is scoped so that all words must match a specific nested product?

I have tried a custom mapping:

```
  mappings: {
      retailer: {
        properties: {
          products: {
            type: "nested"
          }
        }
      }
    }

```

But this results in:

```
#<Searchkick::InvalidQueryError: Bad mapping - run Retailer.reindex>
```

I am on v3.1.3

**Comment by aximuseng** [comment]
Same issue here.

The manual states this (https://github.com/ankane/searchkick#nested-data):

> **Nested Data**
> 
> To query nested data, use dot notation.

`    User.search "san", fields: ["address.city"], where: {"address.zip_code" => 12345}`

This simply doesn't work or the example given needs more qualification.

In my case I have `ExpenditureItem` which belongs_to: `Expenditure` so I try this:

`    ExpenditureItem.search("*", where: { "expenditure.budget_id": '2'})`

which results in nothing.  I know in my `search_data` I can set:

`    budget_id: expenditure.budget_id`

but from the example it seems the entire point is to be able to complete quick and easy nested searches.

Am I missing something here?

**Comment by ankane** [comment]
@james-reading I believe a custom mapping + `merge_mappings: true` should work for your case.

@aximuseng Not sure I fully follow your example, but you still need to add associations to `search_data` if you want to query on them.

**Comment by ankane** [comment]
@james-reading On further investigation, you'll need to use a custom query as well that includes `nested` (was hoping Elasticsearch would handle it automatically). https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html

I started a `nested` branch (https://github.com/ankane/searchkick/compare/nested) to experiment. Overall, it's easy to declare a field as nested for indexing, but more work to make these fields automatically work with the `fields` and `where` options.
