### ISSUE TITLE
[Idea] Async reindex + Partial reindex functionalities 

### ISSUE THREAD

**Issue by yataghan** [ankane/searchkick#1391]
Working on decreasing reindex time of my project's entity so async reindex were added and it works good. 

`Work.reindex(async: { wait: true }, refresh_interval: '30s')`

Than i found that there is a feature that is called Partial Reindex(https://github.com/ankane/searchkick#partial-reindexing) that might help to decrease reindex time as well 
We have a class
```
class Work
  def search_data
    {
      id: id,
      description: description
    }.merge additional_search_fields
  end
   
  def additional_search_fields
    {
      additional_description: additional_description
    }
  end
end
```
but when i try something like 
`Work.reindex(:additional_search_fields, async: { wait: true }, refresh_interval: '30s')`

async functionality stop working. Do i understand it correct that it was made intentionally or nobody tried something like this?

1. Here all options(including async) are excluded from params when we provide `method_name` https://github.com/ankane/searchkick/blob/648d2ef7541b875b3cf8e62a17306c28145c8704/lib/searchkick/index.rb#L191

2. And looks like async reindex doesn't support partial reindex as well 
https://github.com/ankane/searchkick/blob/648d2ef7541b875b3cf8e62a17306c28145c8704/lib/searchkick/bulk_indexer.rb#L85

**Comment by ankane** [comment]
Hey @yataghan, thanks for reporting. The `async` option was only intended for a full (non-partial) reindex, but:

1. It shouldn't silently ignore options
2. It should be able to be extended to support partial reindexing (without `wait: true`)

For now, I'll update it to throw an error when extra options are passed. I'm planning to do a major refactor of reindexing before Searchkick 5, and should be able to include this.
