### ISSUE TITLE
boost_where not

### ISSUE THREAD

**Issue by adamgamble** [ankane/searchkick#1394]
Is it possible to do a boost_where not?

i.e. I want to boost all results where id is not 705206.

I've tried boost_where: {:_not {id: 705206, factor: 10}} and boost_where: {id: {not: [705206], factor: 10}}

Neither of these seem to do what I want.  Ultimately i'm trying to negative boost a result. Any ideas?

**Comment by aleksclark** [comment]
I believe the correct syntax is:
`id: [{value: {not: [31,123]}, factor: 20}]`

**Comment by adamgamble** [comment]
You’re right. This works. Thanks!
