### ISSUE TITLE
Elasticsearch 7.5 support?

### ISSUE THREAD

**Issue by NicoSa** [ankane/searchkick#1396]
Hi,

we are trying to upgrade our project to Ruby 2.7.0 however we are finding problems with Searchkick when we do that. We think the reason for this might be that only Elasticsearch-Ruby 7.5 supports Ruby 2.7.0 but currently Searchkick works with 7.4.

Could we be seeing issues there? When is Searchkick going to support Elasticsarch-Ruby 7.5?

Thanks!

**Comment by ankane** [comment]
Hey @NicoSa, Searchkick works fine with Elasticsearch 7.5. https://travis-ci.org/github/ankane/searchkick/builds/663745404.

If you're running into a specific error, please use the gist in the Contributing Guide to reproduce.

**Comment by NicoSa** [comment]
Hey @ankane, I think the problem is Ruby 2.7.0 though. Are you able to verify that Searchkick works with Elasticsearch on Ruby 2.7.0 ?

**Comment by ankane** [comment]
It works on Ruby 2.7 as well.

**Comment by NicoSa** [comment]
Ok, must be some other issue then. I'll get back to you if I can trace it down to Searchkick. So far so good, thank you @ankane !
