### ISSUE TITLE
Period in Conversions

### ISSUE THREAD

**Issue by gidfs** [ankane/searchkick#1398]
Hi,

This tripped me up a bit today. We have conversions set up, and one of our frequent queries has a `.` in it. This converted the mapping into a nested property, which caused a number of errors. I think it might be an ElasticSearch issue, but thought you might want to be aware. 

for eg) `conversions: { "red vs. blue": 100 }` was converted into a mapping `red vs: {  properties: { blue: { type: "long" } } }`

**Comment by ankane** [comment]
Hey @gidfs, make sure your model has `searchkick conversions: [:conversions]` and has been reindexed.

**Comment by gidfs** [comment]
@ankane - yup it does. the issue was specific to the period. I just filtered it out and it works correctly now.

**Comment by ankane** [comment]
I just it tried it locally and it doesn't create extra nesting when properly configured. Please use the gist in the Contributing Guide to reproduce if you're seeing something different.

**Comment by gidfs** [comment]
Closing this issue. No idea wtf I did to get ES into the state it was in, but I'm no unable to reproduce. 

In case anyone comes back to this. Our environment was on ES 6.8 and Seachkick 4.1.0
