### ISSUE TITLE
Use of named scopes

### ISSUE THREAD

**Issue by ezuhaib** [ankane/searchkick#140]
My model defines a scope `published` so that `Post.published.all` returns all published posts. Is it possible to use searchkick on it? because I'm unable to do so.

```
Post.published.search('*')
```

**Comment by abevoelker** [comment]
It looks like the gem has since been updated to use the official elasticsearch gem - is this still an issue?  I have a scope that looks like this:

```ruby
class Product
  def self.include_subscriptions_count
    joins(
     %{
       LEFT OUTER JOIN (
         SELECT b.product_id, COUNT(*) subscriptions_count
         FROM   subscriptions b
         GROUP BY b.product_id
       ) a ON a.product_id = products.id
     }
    ).select("products.*, a.subscriptions_count")
  end
end
```

But not sure how I'd use it after a few tries:

```
>> Product.search("*").records.include_subscriptions_count
NoMethodError: undefined method `records' for #<Searchkick::Results:0x0000000668ba90>
>> Product.search("*").include_subscriptions_count
NoMethodError: undefined method `include_subscriptions_count' for #<Searchkick::Results:0x0000000670e7b0>
>> Product.include_subscriptions_count.search("*")[0].subscriptions_count
NoMethodError: undefined method `subscriptions_count' for #<Product:0x000000065cfae8>
```

**Comment by ACPK** [comment]
@ankane - In 0.6.1, Searchkick moved to elasticsearch-ruby so I'm assuming this issue can now be closed based on your previous comment?

**Comment by cireficc** [comment]
@ACPK Well scopes still don't work in SearchKick, which is unfortunate, so I'm gonna say *don't close this*.

**Comment by ayghor** [comment]
just in case, what if someone did:

`Foo.all.where.not(bar: 'baz')`

or

`Foo.all.where(Foo.arel_table[:foo].lt(Time.now))`

or perhaps

`Foo.all.where('foo != 'baz' OR foo < ?', Time.now)`

?

yes, some cases could be supported, but _i have a bad feeling about this..._

it could be done by tediously inspecting and translating teh poorly documented arel structures, but it would not account for raw sql. and notice how much more readable raw sql is than arel magic.

suppose now that someone is using pundit to filter stuff that teh user can see, liek:

`policy_scope(Foo.all).search('stuff')`

it would be ok for those _supported cases_, but others would be vulnerable. and it would be so easy to make this that i just did.

plz dont
<3

**Comment by ankane** [comment]
Hey @ezuhaib, I agree this will be tedious and likely error prone. Going to close.
