### ISSUE TITLE
Convention for deleting test indicies?

### ISSUE THREAD

**Issue by archonic** [ankane/searchkick#1400]
My app is multi-tenant and creates a new index for every model in every workspace. The max number of indicies is 1000, and this tends to get hit over time just running rspec locally. It would be best if there was something to add to spec_helper.rb to clean up test indicies after the suite.

Right now I run `docker-compose run web curl -X DELETE elasticsearch:9200/*_test_*`. Is there an API for index deletion within Searchkick? If not I think it would be a good addition. That would let people write something like this:

```
config.after(:suite) do
  Searchkick.delete_indices("*_test_*")
end
```

That feature would also be useful to clean up indicies of deleted workspaces or removed models over time, programatically.

**Comment by ankane** [comment]
Hey @archonic, you can delete a single index with `Product.search_index.delete`. For multiple indices/wildcards, you can use the Elasticsearch client directly with `Searchkick.client`. I appreciate the suggestion, but I'm not sure an additional method is needed.

**Comment by archonic** [comment]
`Product.search_index.delete` is good! I'm not sure how to use `Searchkick.client` to delete indices with a wildcard however. Once I verify everything is working as intended I could put together a PR with rspec documentation additions.
