### ISSUE TITLE
Configure multiple ES Clients

### ISSUE THREAD

**Issue by MMatero** [ankane/searchkick#1402]
Hi,

I'm in a situation where I'd like to have 2 different ES clients configured in my rails app. I'm wondering if this is at all possible in searchkick. This could be on the searchkick object itself or configured at a particular model. Essentially what I'd like to do is have 1 of my models be tracked in ES-client-2 while the rest are tracked in ES-client-1. 

I've found this issue(#897) from a few years ago but it's unclear if anything came of it.

**Comment by ankane** [comment]
Hey @MMatero, there's not currently a way to use different clients for different models. Since this isn't a common case, I'm hesitant to support the extra complexity, but can review a PR if you find an easy way to make it work.
