### ISSUE TITLE
searchkick not updating queue after run_callbacks is called on model. 

### ISSUE THREAD

**Issue by RSR312-206** [ankane/searchkick#1403]
Hello- 

I am runnung into an issue - and not sure if it's Searchkick or maybe I misunderstand the expected behavior. 

I am using a `:queue` for my callbacks in my `Document` model. Everything is working as expected - the configuration automatically sends every record to be indexed to Redis, and I have a job scheduled which runs `Searchkick::ProcessQueueJob` every minute. 

The issue I'm running into is this: when we import documents into the database (and skip callbacks and validations) I still want to get those records pushed into my redis queue. I have a background job which runs callbacks after an import has been done. (This setup is to trigger things like logging, pushing to searchkick etc). It looks like this:

```
def perform(klass, ids, callback)
    records = klass.constantize.where(id: ids)
    records.in_batches(of: 50) do |batch|
      batch.each { |r| r.run_callbacks callback.to_sym }
    end
end
```
It's used this way:
`BullkActionCallbackWorker.perform_async("Document", doc_ids, "create")`

I was assuming that when the callbacks were run, on the document record in this job, that it would trigger Searchkick, but it does not. Using this `run_callbacks` pattern, I can confirm that Searchkick is called successfully on `:update`, however it seems that `create` and/or `save` is not updating redis.
 
Here's a repro of this: https://gist.github.com/RSR312-206/bd3c8727030e6c5aa8ae3ab553b875d9

Thanks, 
Rachel

**Comment by ankane** [comment]
Hey @RSR312-206, `run_callbacks` doesn't run `after_commit` callbacks, which is what Searchkick uses. You can use `r.reindex` to push items to Redis.

**Comment by RSR312-206** [comment]
Okay - so there's no way to push them to my queue instead of updating directly with `reindex`?

**Comment by ankane** [comment]
I believe `reindex` should push the the queue if your model has `callbacks: :queue`. Otherwise, you can use `reindex(mode: :queue)`.

**Comment by RSR312-206** [comment]
Okay, great! Thanks for that clarification. I'll close this issue.
