### ISSUE TITLE
Get aggregation from a list of records only.

### ISSUE THREAD

**Issue by alis-khadka** [ankane/searchkick#1405]
I using searchkick along with solidus gem. 
I have indexed the 'Product' table, which is associated with 'Taxon' table. 
taxon has many products.
So, taxon.all_products gives a active record colllection of product.
I am trying to build aggregation to only the list of products from taxon.all_products.

**Comment by ankane** [comment]
Hey @alis-khadka, you can pass the product ids as a `where` condition. Please check out the Contributing Guide for where to get additional help.
