### ISSUE TITLE
Question about ActiveJob Uniqueness

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1406]
While reading the source code from
https://github.com/ankane/searchkick/blob/3fe0141c25608e5819ccee2c9a046f2d46fdc475/lib/searchkick/record_indexer.rb

I wonder do we verify uniqueness in the job queue since if we put the `reindex` in the callbacks of different associations, we might have duplicates indexing in the async job queue 🧐?!

**Comment by ankane** [comment]
Hey @berniechiu, not sure I fully understand the question, but Searchkick doesn't try to ensure async reindex jobs are unique.

**Comment by berniechiu** [comment]
Oh, I meant for the optimized performance while enqueuing. Should we allow another same job to be enqueued while the previous one hasn't been completed? 😌

**Comment by ankane** [comment]
I think that's fine. Tracking uniqueness would add its own overhead and complexity.
