### ISSUE TITLE
Eagerload Multiple Tables

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1407]
Hi @ankane , I wonder if it's possible to eager multiple tables since we can do this in Rails

Like the example here `subscription: :plan`
```ruby
Company.includes(:balance, subscription: :plan).each { ... }
```

But not sure how we can achieve this in `Searchkick`, the description doesn't say much here

```ruby
Product.search "milk", includes: [:brand, :stores]
```

Thanks!

**Comment by ankane** [comment]
Hey @berniechiu, you can do:

```ruby
Product.search "milk", includes: [:balance, {subscription: :plan}]
```

**Comment by berniechiu** [comment]
Thx a lot!
