### ISSUE TITLE
[Discuss] What is the best way to reindex a big table but still keep zero downtime.

### ISSUE THREAD

**Issue by zw963** [ankane/searchkick#1408]
For now, AFAIK, i have to create a refresh new index in another new elasticsearch new instance, and then, switch to use that new instance in ruby app, that cause a extra overhead, yes, we have to at least start up two ES instance, one for update, e.g.  use "**bundle exec rake searchkick:reindex CLASS=Booking"**, and another for serve our user,  when  rake task done, we can switch to use it use `ENV["ELASTICSEARCH_URL"]`.

But,  we can many index in one ES instance, right?

is there possible to create two `Booking model` search index at same ES instance?

e.g.  current exist a index named: `bookings_production_20200419225747435`,  it used by searchkick serve to our user, can we create a new index, e.g. `bookings_production_20200419225748888`, but, keep old index still serve to our user?
when new index done, we can switch to use it, and delete old index manually.

Thank you very much

**Comment by ankane** [comment]
Hey @zw963, I'm not sure I fully understand the situation, but:

1. Searchkick doesn't currently support multiple ES instances. See https://github.com/ankane/searchkick/issues/1402.

2. The current zero downtime indexing approach does what you describe in the 2nd part.

Unfortunately, I don't have the bandwidth to help with app-specific situations, so please check out the Contributing Guide for where to get help if you have additional questions on this.

**Comment by zw963** [comment]
@ankane , so sorry for my bad english.

My question is really about following explain, how to do that??

> The current zero downtime indexing approach does what you describe in the 2nd part.

Following is our kibana for searchkick, it current search  `Booking` use `bookings_production_20200419230451379`, but if we do full reindex on `Booking`, can will cause our user can not find out correct booking, right?

Please see following screenshot. Thank you!

![image](https://user-images.githubusercontent.com/549126/79727454-fface580-831e-11ea-9ea2-ef754ce927dc.png)

**Comment by ankane** [comment]
All reindexing in Searchkick is zero downtime. The old index is used while the new index completes, and then it switches over. You can read about the approach here:  https://www.elastic.co/guide/en/elasticsearch/guide/2.x/index-aliases.html

**Comment by zw963** [comment]
> All reindexing in Searchkick is zero downtime. The old index is used while the new index completes, and then it switches over. You can read about the approach here: https://www.elastic.co/guide/en/elasticsearch/guide/2.x/index-aliases.html

Oh, thank you, for double confirm again, we just need run `bundle exec rake searchkick:reindex class=Booking`,  searchkick will handle all things about change alias to point to new index, right?

Another one question, If new booking was created when we reindexing, those new booking if will
missing?

Thank you.

**Comment by aristotll** [comment]
> > All reindexing in Searchkick is zero downtime. The old index is used while the new index completes, and then it switches over. You can read about the approach here: https://www.elastic.co/guide/en/elasticsearch/guide/2.x/index-aliases.html
> 
> Oh, thank you, for double confirm again, we just need run `bundle exec rake searchkick:reindex class=Booking`, searchkick will handle all things about change alias to point to new index, right?
> 
> Another one question, If new booking was created when we reindexing, those new booking if will
> missing?
> 
> Thank you.

@zw963 I encounter similar problems.  Do these questions have answers?

**Comment by zw963** [comment]
@aristotll , it use ES alias feature, both old and new all exists when do reindex .
