### ISSUE TITLE
Indexing Strategy for Multiple/Single Model

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1409]
Hi, @ankane 

Thanks for helping out!

I have a question for the `README.md` guide here where https://github.com/ankane/searchkick#indexing

```ruby
class Product < ApplicationRecord
  belongs_to :department

  def search_data
    {
      name: name,
      department_name: department.name,
      on_sale: sale_price.present?
    }
  end
end
```
I suppose it'll have a association reindex with it
```ruby
class Department < ApplicationRecord
  has_many :products

  after_commit :reindex_product

  def reindex_product
    products.find_each(&:reindex) # I'm not sure if this is the best way to keep product index in sync because of the loooooop~~
  end
end
```

I wonder if the line `products.find_each(&:reindex)` is efficient or not because we're just reindexing the duplicate values associated to the products indices?

While it can be easily done with a single SQL join like `Product.joins(:department).where(department: { name: "some_name" }`, I wonder is it possible to have `Product` and `Department` indexes separated, and query to return the results of the products like the above SQL statement 🤔

```ruby
class Product < ApplicationRecord
  belongs_to :department

  def search_data
    {
      name: name,
      on_sale: sale_price.present?,
      department_id: department_id
    }
  end
end

class Department < ApplicationRecord
  has_many :products

  def search_data
    { name: name }
  end
end
```
I would like to have a query in elasticsearch reflects the one here but I'm not sure how we can achieve this though `Product.joins(:department).where(department: { name: "some_name" }`

Or we just do a separated search ? `Product.search('*', where: { department_id: [Department.search(....)....] }`

**Comment by ankane** [comment]
Hey @berniechiu, Elasticsearch doesn't support traditional joins.
