### ISSUE TITLE
Merge mappings with indifferent access

### ISSUE THREAD

**Issue by allanohorn** [ankane/searchkick#1410]
When you set `merge_mapping: true` the `mappings` hash you provide must use symbols / strings corresponding to how Searchkick sets up its mapping.

For example, the beginning of our mapping* looks like this:
```{:properties=>{"name"=>{:type=>"text", :index=>false, :fields=>{:analyzed=>{:type=>"text", :index=>true, :analyzer=>:searchkick_index},```

The field name is stored as a string, so if we wanted to merge the mapping we had to provide a hash interspersed with corresponding strings and symbols
```{:properties => {'name' => {:fields ...}```

Fix would be to fix this line 453 `mappings = mappings.symbolize_keys.deep_merge(custom_mapping.symbolize_keys)`
Might need to use `JSON.parse(JSON[h], symbolize_names: true)` per discussion here https://stackoverflow.com/questions/24927653/how-to-elegantly-symbolize-keys-for-a-nested-hash

*Only found out what my mapping was by editing the gem file `index_options.rb` and printing it out, not sure if there is a better way

**Comment by ankane** [comment]
Hey @allanohorn, can you use the gist in the Contributing Guide to reproduce? You can get the mapping with `Model.search_index.mapping`.

**Comment by ankane** [comment]
Closing due to no response

**Comment by nickgal** [comment]
Hey @ankane, I believe I have run into the same issue. Here's a gist showing the inconsistency between mapping key types. https://gist.github.com/nickgal/0df7e1579f7a51f4bea0f1f24be0182d

Output:
```
> ruby searchkick_repro.rb 
Searchkick version: 4.3.1
Elasticsearch version: 7.7.0
-- create_table(:products)
   -> 0.0021s
"Str key mapping:"
{"type"=>"keyword", "boost"=>2.0, "fields"=>{"analyzed"=>{"type"=>"text", "analyzer"=>"searchkick_index"}, "word_start"=>{"type"=>"text", "analyzer"=>"searchkick_word_start_index"}}, "ignore_above"=>30000}
"Sym key mapping:"
{"type"=>"keyword", "boost"=>2.0}
"Are they the same? false"
```

Hope this helps and sorry if this should be a new issue.

**Comment by ankane** [comment]
Thanks @nickgal, agree strings and symbols should behave the same in this context. I'm not sure what the best behavior is (possibly an error), as an individual field should only use Searchkick settings or custom settings, not both. Will leave the current behavior for now, as I don't want to make any changes until Searchkick 5, as it's possible people are relying on the current behavior.

**Comment by allanohorn** [comment]
@ankane Sorry for dropping the ball here, was having some problems setting up the gist and forgot to circle back to it. Thanks @nickgal!

Reading through the documentation for [Adanced Mapping](https://github.com/ankane/searchkick) it wasn't totally clear to me that I shouldn't be using Searchkick settings & custom settings for an individual field. I thought you would do a deep merge where any attributes that were specified would override the Searchkick ones. I think just updating the Readme with a note should be enough.

**Comment by ankane** [comment]
This is fixed in Searchkick 5 (just released). Thanks again for reporting @allanohorn and the gist @nickgal!
