### ISSUE TITLE
Bulk Index not respecting Batch Size?

### ISSUE THREAD

**Issue by njt1982** [ankane/searchkick#1413]
Hi,

We have some code in a rake like this:

```
Searchkick.callbacks(:bulk) do
  # Do some sync work across a LOT of models in here
end
```

The models all have a batch size set.

However at the end of the rake task we're getting this:
`Elasticsearch::Transport::Transport::Errors::RequestEntityTooLarge: [413] {"Message":"Request size exceeded 10485760 bytes"}`

It looks like bulk mode ignores batch sizing?

When you do callbacks, it seems to call perform after yielding (on line 155):
https://github.com/ankane/searchkick/blob/622f5bff82b317fc1a0d429627ae5efaad271c90/lib/searchkick.rb#L141-L163

This appears to just dump all queued items into a request...
https://github.com/ankane/searchkick/blob/622f5bff82b317fc1a0d429627ae5efaad271c90/lib/searchkick/indexer.rb#L14-L26

Can we bulk update in batches?

**Comment by ankane** [comment]
Hey @njt1982, the `batch_size` option is for `Model.reindex` rather than `Searchkick.callbacks(:bulk)` (which isn't model-specific). I don't think it's common enough to add an option like `Searchkick.callbacks(:bulk, batch_size: 1000)` right now, but you should be able to fork/override `Searchkick::Indexer` to get this behavior.

**Comment by njt1982** [comment]
Hi @ankane  - thanks for the response...

So the problem is AWS 😉

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#network-limits

For a lot of instances, the network limit is hard-set to 10Mib. For our case, when bulk-indexing a significantly large changeset of data, we easily break that limit. For example, just 50,000 items would limit us to around 200 bytes per item.

We're currently reworking this piece of code to collect ID's and then to a:

    Model.where(id: id_collection).reindex(async: true)

(this does seem to respect the batch limit)

... but it would have been so much more convenient to just wrap the bulk block around the entire "sync" task and let Elastic deal with accepting a tonne of data (it has internal reindex queueing, IIRC). Even if we do have to chunk it into 100 or 1000 sized batches...

So is the suggestion right now to fork the Indexer to make it "chunk" the items in that perform method?

**Comment by ankane** [comment]
Yes. You could also break up your indexing code into batches so you don't need to fork it.

```ruby
records.each_slice(100) do |batch|
  Searchkick.callbacks(:bulk) do
    # reindex batch
  end
end
```

**Comment by njt1982** [comment]
Thank @ankane  - breaking up the code to avoid forking isn't trivial; There are outer loops and inner loops and it's the inner loop that generates the queue based on several factors (an API response, the "diff" on API data vs stored model data, etc)... It's feasible the API could return 50,000 items and none need reindexing on this pass; equally they all could.

I quite like the idea of modifying the queue method:
https://github.com/ankane/searchkick/blob/622f5bff82b317fc1a0d429627ae5efaad271c90/lib/searchkick/indexer.rb#L9-L12

So something like:

```
perform unless Searchkick.callbacks_value == :bulk && @queued_items.size < 1000
```

(I mean... technically the queued_items could still be >10Mb at this point, but that's harder to check without serializing them on every queue call?)

**Comment by ankane** [comment]
Sounds good.
