### ISSUE TITLE
Boost field of one model only

### ISSUE THREAD

**Issue by rctneil** [ankane/searchkick#1414]
This is my search line:

@results = Searchkick.search query_string, models: [Coaster, Park, Ride, Album], where: where, aggs: [:type], misspellings: {edit_distance: 1}, match: :word_start, load: true

Each of the four models I have listed has a "name" field, how can I boost the 'name' field of just one model but not the others?

**Comment by ankane** [comment]
Hey @rctneil, you'd need to use the Elasticsearch DSL / [advanced search](https://github.com/ankane/searchkick#advanced-search) for this.
