### ISSUE TITLE
Index not found exception when using parallel testing in Rails 6

### ISSUE THREAD

**Issue by anhari** [ankane/searchkick#1415]
I'm running into this when `parallelize(workers: :number_of_processors)` is set in `test/test_helper.rb` of a Rails 6 app using the default testing stack.

I have this at the bottom of my `test_helper.rb` and I'm calling `Question.reindex` after spinning up some questions in a test via FactoryBot.

``` ruby
Question.reindex
Video.reindex
Post.reindex
Searchkick.disable_callbacks
```

```jsonc
// Elasticsearch::Transport::Transport::Errors::NotFound: [404]
{ 
  "error":  {
    "root_cause": [
      {
        "type":"index_not_found_exception",
        "reason":"no such index [questions_test_20200430174908471]" ,
        "index_uuid":"OhfJeNovQESqiRa7PeZcWw",
        "index":"questions_test_20200430174908471"
      }
    ],
    "type":"index_not_found_exception",
    "reason":"no such index [questions_test_20200430174908471]",
    "index_uuid":"OhfJeNovQESqiRa7PeZcWw",
    "index":"questions_test_20200430174908471"
  },
  "status": 404
}
```

edit - Sorry I just saw this option `Searchkick.index_suffix = ENV["TEST_ENV_NUMBER"]` and tried using it, but I'm not sure I understand how it works.

**Comment by ankane** [comment]
Hey @anhari, I updated the instructions for parallel testing in Rails 6. https://github.com/ankane/searchkick#parallel-tests

When running tests in parallel, you want isolated data stores for each process so they don't interfere with each other. Active Record handles this automatically for your databases by setting up `test-database-0`, `test-database-1`, etc ([docs](https://guides.rubyonrails.org/testing.html#parallel-testing)). Setting the `index_suffix` handles this for Searchkick.

**Comment by anhari** [comment]
Thanks @ankane that really cleared things up for me! Thanks for this lovely gem :)
