### ISSUE TITLE
aggs for has_many association attributes

### ISSUE THREAD

**Issue by aximuseng** [ankane/searchkick#1417]
I have a model similar to a typical 'orders' model:

```
# == Schema Information
#
# Table name: orders
#
#  id             :bigint           not null, primary key
#  date       :datetime
class Order < ApplicationRecord
   has _many :order_items
end
```

```
# == Schema Information
#
# Table name: order_items
#
#  id             :bigint           not null, primary key
#  order_id             :bigint
#  category       :string
class OrderItem < ApplicationRecord
   belongs_to :orders
end
```

So imagine various orders with various order_items of fruit, meat, vegetables etc.

I already know how to use aggs to build some basic filters etc:

`    @orders = Order.search("*", aggs: { date: {...} )
`

I know that I can add something like this to search into the related order_items:

```
  def search_data
    attributes.merge({
    item_category: order_items.map(&:category).join(" ")
      })
  end
```
What I am lost on, and is not clear from the docs / searching I have done, is how one would add an agg for this i.e. I want to so see number of orders that have order_items with fruit, meat, vegetables etc.?

**Comment by ankane** [comment]
Hey @aximuseng, please check out the Contributing Guide for where to get help.
