### ISSUE TITLE
Search on a serialized attribute in postgres database

### ISSUE THREAD

**Issue by zainonrails** [ankane/searchkick#1419]
Hi,

I have `Shipment` model with an attribute `tracking_codes` that is serialized to an `Array`. I want to that to be searchable.

`serialize :tracking_codes`

**What I have done**
I have added that attribute to `search_data` and `search_fields` method to index and search.

I have gone through all the issues that had `array` in the title to at least have a hint. 
I have tried using something like:
```
Shipment.search('*', where: { tracking_codes: 123 }).results
Shipment.search('*', where: { tracking_codes: [123] }).results
```
with other combinations but no results.

Let me know if you need more info.

Thanks!

**Comment by zainonrails** [comment]
@ankane Any help would be appreciated.

**Comment by ankane** [comment]
Hey @zainonrails, searching on arrays should work the same as other fields. Unfortunately, I don't have the bandwidth to help with app-specific issues, so check out the Contributing Guide for where to get help.
