### ISSUE TITLE
turn off specific analyzers 

### ISSUE THREAD

**Issue by plasticgit** [ankane/searchkick#142]
I see searchkick comes with tons of awesome search analyzers out of the box. However, my application will not be taking advantage of most of these and was wondering if its possible to turn off certain ones when reindexing. Alternatively, can I pass in a custom settings params while keeping the default mapping that searchkick provides?

Thanks!

**Comment by ankane** [comment]
Closing, as this is pretty old and don't see a strong reason to do it.
