### ISSUE TITLE
Searchkick - Autocomplete with multiple models & fields

### ISSUE THREAD

**Issue by gabrielguerin** [ankane/searchkick#1420]
I am struggling to implement the [autocomplete functionality](https://github.com/ankane/searchkick#instant-search--autocomplete) for multiple models associated to my `Post` model. The search functionality works fine and returns the expected data. My autocomplete method also works fine if I implement it the way it is done in the [documentation](https://github.com/ankane/searchkick#heres-how-to-make-it-work-with-rails) (only for posts' title however). I tried [this answer](https://github.com/ankane/searchkick/issues/53#issuecomment-51884399) but I get an error: `undefined method 'index' for #<Class:0x000000000c9f92f8>'`. Switching `Post.index.name` to `Post.searchkick_index.name` as suggested [here](https://github.com/ankane/searchkick/issues/53#issuecomment-51501600) just throws the same error: `undefined method 'searchkick_index'`.

This is the code I wrote in `posts_controller.rb`:
```
def autocomplete
    render json: Post.search(params[:query],
                             index_name: [
                               Post.searchkick_index.name,
                               Tag.searchkick_index.name,
                               User.searchkick_index.name
                              ],
                             limit: 10,
                             load: false,
                             misspellings: { below: 5 })
end
```

In `post.rb`:
```
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :posts_tags, dependent: :destroy
  has_many :tags, through: :posts_tags

  searchkick word_start: %i[title]

  def search_data
    {
      title: title,
      description: description,
      user: user.full_name
    }.merge(
      tag: tags.map(&:title),
      comments: comments.map(&:description)
    )
  end
end
```

I can't seem to grasp the logic behind Searchkick's gem to make the autocomplete functionality work properly. I have also tried various other options such as:
```
def autocomplete
  render json: Searchkick.search(params[:query],
							     models: [Post, Tag, User],
							     limit: 10,
							     load: false,
							     misspellings: { below: 5 })
end
```
This returns: `undefined method 'searchkick_klass'`. Switching `models` to `index_name` in the above code returns the following error: `Elasticsearch::Transport::Transport::Errors::NotFound [...] "type":"index_not_found_exception","reason":"no such index [Tag]"`.

I want to be able to autocomplete Post's **title**, Tag's **title** & User's **full_name**. How should I change my code?

Thank you in advance!

**Comment by ankane** [comment]
Hey @gabrielguerin, unfortunately, I don't have the bandwidth to help with app-specific issues. Check out the Contributing Guide for where to get help.

**Comment by gabrielguerin** [comment]
Alright no worries, thank you anyway!
