### ISSUE TITLE
Type is always _doc with Searchkick 4.3.1 and ES 7.4

### ISSUE THREAD

**Issue by moxie** [ankane/searchkick#1421]
Hi there,

We're using Searchkick 4.3.1 with ElasticSearch 7.4.x and have noticed all models are now indexed with type `_doc`. This is even though Searchkick appears to still be generating a `:_type` properly for the index. 

Given:
```ruby
class Announcement < ApplicationRecord
  searchkick
end
```

We have the following output:
```
Announcement.searchkick_index.options[:_type].call
=> "announcement"
```

But when we get search results, the hits are coming back with `type: "_doc"`:
```
Announcement.searchkick('test').hits
=> [{"_index"=>"announcements_development_20200527141317316", "_type"=>"_doc", "_id"=>"108111", "_score"=>52.14424},
{"_index"=>"announcements_development_20200527141317316", "_type"=>"_doc", "_id"=>"90441", "_score"=>47.764935},
{"_index"=>"announcements_development_20200527141317316", "_type"=>"_doc", "_id"=>"63721", "_score"=>47.682816},
{"_index"=>"announcements_development_20200527141317316", "_type"=>"_doc", "_id"=>"102031", "_score"=>47.682816},
{"_index"=>"announcements_development_20200527141317316", "_type"=>"_doc", "_id"=>"19071", "_score"=>46.733723}]
```

Where this really manifests as a problem is when we're performing searches across multiple models. Specifically because these multiple model searches would have different `where` conditions per model and we would scope those conditions as follows:
`where({ _or: [{type: '_announcement', active: true}, {type: '_event', upcoming: true} ])`

Now that `type` is always `'_doc'`, these result sets are always empty. I've also tried explicitly using the `_index` name in the `where` but Searchkick returns the index's alias for the following:
```
Announcement.searchkick_index.name
=> "announcements_development" 
```

Is this an issue with Searchkick? Because it seems like still it _should_ be setting the `_type` on the index appropriately. The following article (https://www.elastic.co/blog/removal-of-mapping-types-elasticsearch#mapping-type) under the Elasticsearch 7.x removal notes says:

> 7.x indices which don’t have an explicit type will use the dummy type name _doc.

but should that apply here? Seems like Searchkick would still set the type.

Any help would be appreciated. Perhaps there's another way to scope `where` conditions to a specific index when performing multiple model searches?

**Comment by ankane** [comment]
Hey @moxie, you can't set multiple types for an index in Elasticsearch 7, so Searchkick uses `_doc` to prepare for complete removal in Elasticsearch 8.

To search on different conditions across multiple models, you can use:

```sh
where({_or: [{_index: Announcement.search_index.name, active: true}, {_index: Event.search_index.name, upcoming: true}])
```

starting with Elasticsearch 7.5. For Elasticsearch 7-7.4, you'd need to add a custom type field on `search_data`.

**Comment by moxie** [comment]
@ankane Thanks so much for the tip. For now we reverted to ES 6.8 but I'll keep your comment on my radar the next time we need to move up in the world.

**Comment by tomfast** [comment]
Thanks for the 
```
where({_or: [{_index: Announcement.search_index.name, active: true}, {_index: Event.search_index.name, upcoming: true}])
```

solution. Much appreciated!
