### ISSUE TITLE
Bulk Remove Indexes with should_index?

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1424]
Hi @ankane,

I'm not sure if it's a bug or feature, since I've set `should_index?` under a model

```ruby
class Shipment
  ...
  ...
  ...
  def should_index?
    shipment_state != 'deleted'
  end
end
```

It works properly that indexes are removed with commands like `Shipment.reindex` or `Shipment.find(1).reindex`

But it doesn't seem to work with `ActiveRecord::Relation` with scope this way like

```ruby
# Remove index ids of `deleted` state records
Shipment.where(id: [1, 2, 3]).reindex # Don't see any request to elasticsearch
Shipment.search('*', where: { id: [1] }).results # Still exists
```

Thanks for your help~~

**Comment by ankane** [comment]
Hey @berniechiu, thanks for reporting! I think Searchkick should remove records in this case, but since the current behavior has been around for a long time, I think it's best to keep it until the next major version. I've added this to the Searchkick 5 plan.

**Comment by berniechiu** [comment]
Cool, I could help fix this, will look at the source code later

**Comment by ankane** [comment]
Thanks for offering to help. I'll likely be doing a pretty big refactor of reindexing for Searchkick 5, so probably best to hold off for now.

**Comment by berniechiu** [comment]
I also found that `Shipment.reindex(async: true)` won't work either 😢

**Comment by ankane** [comment]
Full async reindex generates `BulkReindexJob`s, which call `import_or_update`, which selects by `should_index?`. Added a test case for it as well.

**Comment by ankane** [comment]
Hey @berniechiu, this is fixed in Searchkick 5 (just released). Thanks again for reporting!
