### ISSUE TITLE
[Idea] Support nested queries

### ISSUE THREAD

**Issue by anark** [ankane/searchkick#1425]
Hi,
I'm looking into adding support for nested queries to Searchkick.  So you could query data based on multiple attributes of nested data.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html

I was wondering if there was any interest in this feature and if so what would be an ideal API.

**Comment by ankane** [comment]
Hey @anark, can you explain more about your use case for nested queries?

**Comment by ankane** [comment]
Closing due to no response
