### ISSUE TITLE
Searchkick.models not populated in Rails console, test environment

### ISSUE THREAD

**Issue by matt-dutchie** [ankane/searchkick#1426]
Hi -- I've found an issue similar to https://github.com/ankane/searchkick/issues/1301

```
gem "searchkick", "4.3.1"
gem "rails", "~> 6.0.3.1"
```

Whenever I open the Rails console, `Searchkick.models` is an empty array. Running `Rails.application.eager_load!` or `Zeitwerk::Loader.eager_load_all` populates the array appropriately.

This was also affecting our test environment when using RSpec.

The fix from the eager load branch probably just need to be moved from the rakefile to an appropriate place within the source. Happy to cut a PR if you have a suggestion for where it might best live.

**Comment by matt-dutchie** [comment]
Just poking around in the source ;)

**Comment by ankane** [comment]
Good deal 👍 I imagine not everyone will agree, but I think it's best to leave it out of the readme for now (there are also issues with dev reloading) and encourage users to specify models as needed (which won't have either of these issues).
