### ISSUE TITLE
ES deprecation warning: "Loading the fielddata on the _id field is deprecated and will be removed in future versions. If you require sorting or aggregating on this field you should also include the id in the body of your documents, and map this field as a keyword field that has [doc_values] enabled" when ordering by id

### ISSUE THREAD

**Issue by xxx** [ankane/searchkick#1431]
**First**
Search existing issues to see if it’s been reported and make sure you’re on the latest version.

**Describe the bug**
Just updated the ES gems, and am now seeing

```
warning: 299 Elasticsearch-7.6.1-aa751e09be0a5072e8570670309b1f12348f023b "Loading the fielddata on the _id field is deprecated and will be removed in future versions. If you require sorting or aggregating on this field you should also include the id in the body of your documents, and map this field as a keyword field that has [doc_values] enabled"
```

coming from any query that orders by id. We're already including an `id` field in our document `search_data`, but Searchkick [ignores that](https://github.com/ankane/searchkick/blob/0b161d2a3d169143ecc75b9450150fb48aa63b1e/lib/searchkick/query.rb#L871) in `set_order`, leading to the warning.

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Elasticsearch version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Migration.create_table :products do |t|
  t.string :name
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name], order: { id: :desc }).response
```

**Additional context**
Add any other context.

**Comment by ankane** [comment]
Hey @xxx, thanks for reporting. The `id` field has a special meaning in Searchkick for `where` and `order`, so you'll likely want to use a different field name. We could potentially take out the renaming for order in Searchkick 5 if this deprecation warning becomes an error in Elasticsearch 8.

In the past, I've considering adding a warning if `search_data` contained an `id` field, but don't think that's the right move since it should be fine for users who use the Elasticsearch DSL to search.

**Comment by ankane** [comment]
Also, it looks like you can avoid the renaming with `order: [{id: :asc}]`.

**Comment by xxx** [comment]
Hm, ok. I'm not sure when they intend to remove it. This warning is brand new since upgrading to ES gems v 7.8.0. We've had this order in place for years without issue, until now. I guess I'll close this, but this probably comes up again for others. Hopefully google will index it.
