### ISSUE TITLE
Change default number of shards from 5 to 1

### ISSUE THREAD

**Issue by gdomingu** [ankane/searchkick#1432]
Hi there,

I noticed that in Elasticsearch 7.0 the default number of shards on index creation changed from 5 to 1. 
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_index_creation_no_longer_defaults_to_five_shards

Wondering if this is something you have considered changing for the gem to match? 

Thanks!

**Comment by ankane** [comment]
For future readers, Searchkick only sets the number of shards in the test environment (to 1), so it'll use the Elasticsearch default in other environments.
