### ISSUE TITLE
LIKE operator not filtering data as expected

### ISSUE THREAD

**Issue by zainonrails** [ankane/searchkick#1433]
I have gone through the existing related issues on LIKe operator working but those haven't helped me any way.

**Describe the bug**
I am using the `LIKE` filter in `where` to mimic SQL like the behavior of my current application but ES is not picking up the results it should.

**To reproduce**

To be sure I created another Rails App:
Rails: 5.2
Searchkick: latest -> 4.4.1
Elasticsearch: 7.8 (running on docker)

I indexed a model and performed this query.
```ruby
User.search(param[:q], fields: [:name], where: { name:  { like: "%#{param[:q]}%" } })
```
This is as documented. `category: {like: "%frozen%"}, # like`

In my original application I am doing something like:
```ruby
Item.search(params[:q], fields: [:name], where: { name: { like: "%#{param[:q]}%" }},
                                     page: params[:page], per_page: 20, load: false)
```

While using regex for this query I received this warning: `[searchkick] WARNING: Regular expressions are always anchored in Elasticsearch`
Both these approaches did not help me and I am unable to replace my SQL search with ElasticSearch.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Elasticsearch version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Migration.create_table :products do |t|
  t.string :name
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search('te', fields: [:name], where: { name: { like: "%te%" }},
                                     page: 1, per_page: 20, load: false).response
```

**Comment by ankane** [comment]
Hey @zainonrails, please use the code in the issue template to reproduce the issue.

**Comment by zainonrails** [comment]
@ankane Updated.
I hope this would be useful now.

**Comment by ankane** [comment]
Thanks @zainonrails. There are two reasons there are no matches in the example above:

- `te` doesn't match `test` since partial matches aren't configured
- `like` is case-sensitive like in SQL

**Comment by zainonrails** [comment]
I tried the partial matches using the options listed one by one. It did not help. Should I use `operator: 'or'` option?

**Comment by rderoldan1** [comment]
@ankane is there any way to make the `like` condition case insensitive?

**Comment by ankane** [comment]
@zainonrails `:word_start`, `:text_start`, `:word_middle`, and `:text_middle` should all allow `te` to match `test`.

@rderoldan1 added `ilike` in ef30d53687f69d57d327f8c925396a3545814ac2.
