### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::Forbidden: [403] 403 Request throttled due to too many requests

### ISSUE THREAD

**Issue by andreasunterhuber** [ankane/searchkick#1434]
Running the reindex command throws an error: 
`Elasticsearch::Transport::Transport::Errors::Forbidden: [403] 403 Request throttled due to too many requests /_bulk`

Used the following GEMs
* elasticsearch (7.5.0)
* searchkick  (4.4.1)

Server is an AWS ElasticSearch Service with version 7.4 of ES. 

How can we throttle the requests?

**Comment by andreasunterhuber** [comment]
It seems that we can avoid this crash 
* instead of: `PageText.reindex`
* this **works**: `PageText.reindex(async: false, refresh_interval: "480s")` 

But it seems strange to us. Short explanation would be great!

**Comment by ankane** [comment]
Hey @andreasunterhuber, `async: false` is the default and `refresh_interval` doesn't affect the number of requests, so not sure why the 2nd one would work when the 1st doesn't. Also, I haven't heard of request throttling with Amazon Elasticsearch Service and don't see anything when searching for that error message, so not sure what's causing that error. However, I don't think it's anything specific to Searchkick.

**Comment by andreasunterhuber** [comment]
@ankane thanks for your feedback. It was my opinion too. There were just a few reports around and nothing specific about AWS. In fact, playing around with larger indexes i had to increase `refresh_interval: "1200s"` to finish successfully. Strange but it was a solution. Is there any way to reduce the amount of concurrent requests?

**Comment by ankane** [comment]
`Model.reindex` doesn't perform any concurrent requests without `async: true`.
