### ISSUE TITLE
Filterable field is not searchable

### ISSUE THREAD

**Issue by kapso** [ankane/searchkick#1435]
So I started saving a new field (an array of strings) to my existing index but forgot to add it to the `filterable:` list. Halfway through the indexing process, I added that field to the `filterable:` list. I restarted populating my index (without purging it), and the reindexing process is still ongoing, its a 35m document index, so takes time.

But right now when I try to run a filter query on that field, I get this error  -- `Cannot search on field [customer_names] since it is not indexed.`

Thanks for your help.

- Elasticsearch v7.4
- gem 'rails', '6.0.3.2'
- gem 'searchkick', '4.4.1'

**Comment by ankane** [comment]
Hey @kapso, you need to do a full reindex after changing the `filterable` option.

**Comment by kapso** [comment]
@ankane A full index just completed, but still seeing the above issue. Anything else we need to do?

Thanks.

**Comment by kapso** [comment]
@ankane So this time 

- I added a new field to `filterable:` first, the field is called `customer_names_list`
- Re-ran our bulk index process - it loops through a Postgres table and uses - `Model.searchkick_index.bulk_index`

But still seeing the same `not indexed` error on `customer_names_list`. I am wondering anytime you add a new field to `filterable:` you have to first **purge the index**? and then reindex it?

**Comment by rafaelsales** [comment]
@ankane is there a way to avoid a full reindex after adding a field to `searchable`?

I have a huge dataset that takes days to reindex :(
