### ISSUE TITLE
Searckick suggestions method returning empty result

### ISSUE THREAD

**Issue by adept-akanksha** [ankane/searchkick#1439]
I have a Location model with following schema
`create_table "locations", force: :cascade do |t|
    t.citext "locality"
    t.citext "city"
    t.citext "state"
    t.citext "state_short_name"
    t.bigint "country_id"
    t.index ["city", "state", "country_id"], name: "index_locations_on_city_and_state_and_country_id", unique: true, where: "(locality IS NULL)"
    t.index ["country_id"], name: "index_locations_on_country_id"
    t.index ["locality", "city", "state", "country_id"], name: "index_locations_on_locality_and_city_and_state_and_country_id", unique: true
    t.index ["locality", "state", "country_id"], name: "index_locations_on_locality_and_state_and_country_id", unique: true, where: "(city IS NULL)"
    t.index ["state", "country_id"], name: "index_locations_on_state_and_country_id", unique: true, where: "((city IS NULL) AND (locality IS NULL))"
  end`

I have added following searchkick method in location model
`searchkick(
    callbacks: :async,
    suggest: [:locality, :city, :state, :country]
  )

  scope :search_import, -> { includes(:country) }

  def search_data
    {
      locality: locality_index,
      city: city_index,
      state: state_index,
      country: country_index,
    }
  end`

I am trying to run suggest query but I am getting empty options 
`Location.search('United', suggest: true).suggestions`

**Comment by ankane** [comment]
Hey @adept-akanksha, please use the code in the bug report template to reproduce.

**Comment by adept-akanksha** [comment]
@ankane - Can you please share the link of bug report template

**Comment by adept-akanksha** [comment]
@ankane - I have a question, I have a location model like this 
`class Location < ApplicationRecord
  belongs_to :country

  ############## Searchkick methods ##############

  searchkick(
    callbacks: :async,
    suggest: [:locality, :city, :state, :country]
  )

  scope :search_import, -> { includes(:country) }

  def search_data
    {
      locality: locality_index,
      city: city_index,
      state: state_index,
      country: country_index,
    }
  end

  ################################################

  def state_display_name
    if locality.present? || city.present?
      state_short_name.present? ? state_short_name : state
    else
      state.present? ? state : state_short_name
    end
  end

  def country_display_name
    country_name
  end

  def display_name
    [locality, city, state_display_name, country_display_name].select(&:present?).join(', ')
  end

  def country_name
    country&.name
  end

  def country_short_name
    country&.short_name
  end

  def locality_index
    return if locality.blank?
    [
      [locality].select(&:present?).join(', '),
      [locality, city].select(&:present?).join(', '),
      [locality, city, state_short_name].select(&:present?).join(', '),
      [locality, city, state].select(&:present?).join(', '),
      [locality, city, state_short_name, country_short_name].select(&:present?).join(', '),
      [locality, state_short_name].select(&:present?).join(', '),
      [locality, state].select(&:present?).join(', '),
      [locality, state, country_short_name].select(&:present?).join(', '),
      [locality, state_short_name, country_short_name].select(&:present?).join(', '),
      [locality, city, country_short_name].select(&:present?).join(', '),
      [locality, city, state, country_short_name].select(&:present?).join(', '),
      [locality, city, state_short_name, country_name].select(&:present?).join(', '),
      [locality, city, state, country_name].select(&:present?).join(', '),
      [locality, city, country_name].select(&:present?).join(', '),
      [locality, state_short_name, country_name].select(&:present?).join(', '),
      [locality, state, country_name].select(&:present?).join(', ')
    ].reject(&:blank?).uniq
  end

  def city_index
    return if city.blank?
    [
      [city].select(&:present?).join(', '),
      [city, state_short_name].select(&:present?).join(', '),
      [city, state_short_name, country_short_name].select(&:present?).join(', '),
      [city, state, country_short_name].select(&:present?).join(', '),
      [city, state].select(&:present?).join(', '),
      [city, state, country_name].select(&:present?).join(', '),
      [city, state_short_name, country_name].select(&:present?).join(', ')
    ].reject(&:blank?).uniq
  end

  def state_index
    return if state.blank? && state_short_name.blank?
    [
      [state].select(&:present?).join(', '),
      [state_short_name].select(&:present?).join(', '),
      [state, country_name].select(&:present?).join(', '),
      [state_short_name, country_name].select(&:present?).join(', '),
      [state, country_short_name].select(&:present?).join(', '),
      [state_short_name, country_short_name].select(&:present?).join(', ')
    ].reject(&:blank?).uniq
  end

  def country_index
    return if country_name.blank? && country_short_name.blank?
    [
      [country_short_name].select(&:present?).join(', '),
      [country_name].select(&:present?).join(', ')
    ].reject(&:blank?).uniq
  end

  def search_params
    key = case
          when locality.present?
            :locality
          when city.present?
            :city
          when state.present? || state_short_name.present?
            :state
          else
            :country
          end

    { key => [display_name] }
  end
end`

When I try to query `Location.search("United", suggest true).suggestions` then I get empty results. Am I doing something wrong?

**Comment by ankane** [comment]
Unfortunately, I don't have the bandwidth to help with app-specific questions. The new issue page should have the bug report template as well as where to get help.

**Comment by ankane** [comment]
Cleaning up issues
