### ISSUE TITLE
Advanced boolean queries

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#144]
For instance:

```
name like Bob and location like California
```

This also applies to where queries:

```
(name = Bob or location = California) and color = Red
```

**Comment by gustaflindqvist** [comment]
Any plans for this in the roadmap for 2015?

**Comment by seizmo** [comment]
I would also be really interested in this because any type of "Advanced Search" is not really feasible with searchkick right now

**Comment by Yopi** [comment]
:+1: on this feature. :-)

**Comment by MindRave** [comment]
Same here! Big :+1: to this one.

**Comment by jdax** [comment]
:+1:

**Comment by scifisamurai** [comment]
@ankane I noticed the roadmap was updated recently to no longer include "Search multiple fields for different terms" which is similar to https://github.com/ankane/searchkick/issues/45

Has this functionality been added or has it been decided to not pursue this?

**Comment by ankane** [comment]
It sounds like @savayg is working on this from the conversation in #727.

**Comment by feliperaul** [comment]
@ankane I took a lok at #727 and it looks like it just adds a `match: :cross_fields` option, but I dont think it solves this request. It's going to search 'Bob' in 'Location' and 'California' in name as well, right? 

I think this request aims for a way of attaching specific search terms to specific fields, individually.

**Comment by kesha-antonov** [comment]
Need this too +1

**Comment by klebervirgilio** [comment]
👍

**Comment by morozovm** [comment]
+1

**Comment by vkozyrev** [comment]
+1

**Comment by nocivus** [comment]
+1

**Comment by Jeromearsene** [comment]
+1

**Comment by Jeromearsene** [comment]
I'm not sur that is good issue for my question, but I have a similar problem.

I try to reproduce this SQL request:
```sql
select
  id,
  state,
  accepted
from subscriptions
where not ((state='terminated') and (accepted is false))
```

The goal is "_I want all subscriptions where they are no the combinaison **state equal terminated** and **accepted is false**_".

<br>
I've tried some combinaisons:

#### Only accepted where state is not terminated
```ruby
Subscription.search(
        params[:query],
        operator: "or",
        highlight: true,
        limit: 5,
        where: {
          _and: [{
                accepted: false,
                state: {not: 'terminated'}
            }]
        }
)
```

```ruby
Subscription.search(
        params[:query],
        operator: "or",
        highlight: true,
        limit: 5,
        where: {
          _and: [
                accepted: false,
                state: {not: 'terminated'}
            ]
        }
)
```

---

#### Error
> Elasticsearch::Transport::Transport::Errors::BadRequest - [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[exists] unknown token [START_OBJECT] after [field]","line":1,"col":4127}],"type":"parsing_exception","reason":"[exists] unknown token [START_OBJECT] after [field]","line":1,"col":4127},"status":400}:

```ruby
Subscription.search(
        params[:query],
        operator: "or",
        highlight: true,
        limit: 5,
        where: {
          _and: [[{
                accepted: false,
                state: {not: 'terminated'}
            }]]
        }
)
```

> Elasticsearch::Transport::Transport::Errors::BadRequest - [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"[exists] unknown token [START_OBJECT] after [field]","line":1,"col":4199}],"type":"parsing_exception","reason":"[exists] unknown token [START_OBJECT] after [field]","line":1,"col":4199},"status":400}:
```ruby
Subscription.search(
        params[:query],
        operator: "or",
        highlight: true,
        limit: 5,
        where: {
          _and: [[
                {accepted: false},
                {state: {not: 'terminated'}}
            ]]
        }
)
```

An idea @ankane ?

Thank you for the library ;)

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.

**Comment by Jeromearsene** [comment]
@ankane any idea for my question ?
