### ISSUE TITLE
Unable to provide port for elasticsearch_url for parallel reindexing

### ISSUE THREAD

**Issue by 34code** [ankane/searchkick#1441]
**First**
checked

**Describe the bug**
Faraday always tries to connect on port 80 instead of port 9200. I also have an elasticsearch user and pass setup
so the url code should be something like (in config/searchkick.rb): 

```
Searchkick.client_options = {
    url: 'http://user:password@ip.address.com:9200',
    retry_on_failure: true,
    transport_options:
      { request: { timeout: 250 } }
  }
```

#ERROR:
`Faraday::ConnectionFailed: connection refused: ip.address.com:80`

**To reproduce**
__searchkick.rb__

```
Searchkick.client_options = {
    url: 'http://elasticuser:password@ip.address.com:9200',
    retry_on_failure: true,
    transport_options:
      { request: { timeout: 250 } }
  }
```

create jobs (works)
```index = Item.reindex(async: true, refresh_interval: '30s')```

pickup jobs form sidekiq (fails -- defaults to port 80) 

**Additional context**
followed steps for parallel reindexing here:

https://medium.com/rubyinside/asynchronous-elasticsearch-bulk-reindexing-with-rails-searchkick-and-sidekiq-26f2f9aa8513

**Comment by ankane** [comment]
Hey @34code, not sure what would cause that. Searchkick just passes the client options to the elasticsearch-ruby client, so I'd see if you can reproduce there. https://github.com/ankane/searchkick/blob/8efe6b4473be005cf092fe2e820629d3a86fb2e5/lib/searchkick.rb#L58-L62

**Comment by 34code** [comment]
thanks @ankane ! hmm I'll check with the team at elasticsearch-ruby.. this gem handles the auth and setup properly for all other usecases, just not for the parallel reindexing example

**Comment by 34code** [comment]
very strange.. I removed the `url:` field and it began to work as it picks up the same` "ELASTICSEARCH_URL"` env variable.. I was likely setting up the url wrong.
