### ISSUE TITLE
Pagination for Pagy

### ISSUE THREAD

**Issue by matiasmasca** [ankane/searchkick#1443]
Have you plan add support for the pagination gem [Pagy](https://github.com/ddnexus/pagy)?  that have superior performance infront of Kaminari or WillPaginate

**Comment by ankane** [comment]
Hey @matiasmasca, Pagy already supports Searchkick: https://ddnexus.github.io/pagy/extras/searchkick.html

**Comment by ankane** [comment]
Cleaning up issues

**Comment by antarr** [comment]
The link about works fine when searching a single model but not multiple like here
```ruby
Searchkick.search(search_params, models: search_models, page: page, per_page: 10)
```
