### ISSUE TITLE
Is it possible to separate index import queue and normal reindex?

### ISSUE THREAD

**Issue by berniechiu** [ankane/searchkick#1446]
Hi @ankane , thanks for the help

When we do a config change, we need to re-index the whole table
https://github.com/ankane/searchkick#to-reindex-or-not-to-reindex

If we run in async, they seem to share with the same queue `searchkick`

But our application is also config with something like

```ruby
class Product < ApplicationRecord
  searchkick callbacks: :async
end
```

That means in the process of importing the new indexes, we're also jamming background jobs on normal application re-index.
Therefore, I wonder if it's possible to separate the queue for those two? 🤔 Thanks for the help.

**Comment by dvmonroe** [comment]
@berniechiu if say you're performing this from a cron job or the rails console you could just override the [queue_name](https://github.com/ankane/searchkick/blob/master/lib/searchkick.rb#L51)

```ruby
Searchkick.queue_name = :queue_for_bulk_index
Product.reindex(async: {wait: true})
```

**Comment by berniechiu** [comment]
Coool, i see! That's a good idea
