### ISSUE TITLE
SearchkickTimeout

### ISSUE THREAD

**Issue by aximuseng** [ankane/searchkick#1449]
This issue references `SearchkickTimeout = 120`.  I can't seem to find anything that references where you set this.

> I also got the same error in 2.5.0.
> It is time to take a time-consuming case (for example, specifying a huge number of lines of synonym file) when creating index with PUT request.
> 
> In elasticsearch-ruby, host_unreachable_exceptions occurred and retry processing was done.
> 
> https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb#L293
> 
> ```
> rescue * host_unreachable_exceptions => e
>         logger.error "[# {e.class}] # {e.message} # {connection.host.inspect}" if logger
> 
>         connection.dead!
> 
>         if @options [: reload_on_failure] and tries <connections.all.size
>           logger.warn "[# {e.class}] Reloading connections (attempt # {tries} of # {connections.all.size})" if logger
>           reload_connections! and retry
>         end
> ```
> 
> I avoided it by extending the timeout.
> `SearchkickTimeout = 120`

_Originally posted by @motsat in https://github.com/ankane/searchkick/issues/843#issuecomment-384136164_

**Comment by aximuseng** [comment]
Tracked it down - never fails as soon as a I post a issue or Stackexchange a second search finds the answer:

Set in your initializer (I used 120 on my slow temporary system that was giving me issues):

```
Searchkick.timeout = 1
Searchkick.search_timeout = 1

```
https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts#searchkick

**Comment by ankane** [comment]
Great, thanks for sharing what you found @aximuseng!
