### ISSUE TITLE
Trying to set boundary_scanner to "word"

### ISSUE THREAD

**Issue by staycreativedesign** [ankane/searchkick#1451]
Trying to set the boundary_scanner for highlights to "word" and its not working can you shoe me an example of it working?

```
    @articles = Page.search(@search.keywords,
                            limit: 10,
                            fields: [:content, :title],
                            highlight: {
                              boundary_scanner: 'word',
                              fields: [:content],
                              tag: "<strong>",
                              fragment_size: 200,
                            }
                           )

```

**Comment by ankane** [comment]
Hey @staycreativedesign, please create a new issue with the bug report template to make it easier to reproduce (and include the expected output).

**Comment by memsenpai** [comment]
@ankane
I'm see a lot of options not work.
I tried order, boundary_chars, boundary_scanner, type. No one work. Can you check it?
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/highlighting.html

**Comment by 9mm** [comment]
@ankane i have searched wide on this github, how do I just simply highlight only what they have typed? I'm making a realtime searchbox using `word_start`

So if they type "yel" i want the result to highlight "**yel**low bus"
