### ISSUE TITLE
import progress 

### ISSUE THREAD

**Issue by GMolini** [ankane/searchkick#1453]
Right now the gem outputs the following output:

D, [2020-12-17T15:52:46.446109] DEBUG -- :   MyModel Import (88226.3ms)  {"count":10000}, with a batch size of 10000. 

The problem is that if the table is very big, after a while its impossible to know the progress of the import. It would be great if calling reindex first made a count of the total rows of the table, and then besides the count it also printed the progress as a percentage. For example:

D, [2020-12-17T15:52:46.446109] DEBUG -- :   MyModel Import (88226.3ms)  {"count":10000, progress: "13.5%"}

**Comment by ankane** [comment]
Hey @GMolini, thanks for the suggestion. I agree it'd be nice to see progress. My main hesitation is it requires an expensive query to get the total number of records to be indexed.

**Comment by GMolini** [comment]
Maybe it could be an option? Disabled by default, but if you are willing to execute that expensive query then it will show the progress

**Comment by ankane** [comment]
That could work if it doesn't add too much complexity to the code. Happy to look over a PR if you find a simple way to do it.

**Comment by ankane** [comment]
Cleaning up stale issues
