### ISSUE TITLE
Handle data updates during re-indexing

### ISSUE THREAD

**Issue by rohitpaulk** [ankane/searchkick#1456]
👋 Thanks so much for this gem!

**Is your feature request related to a problem? Please describe.**

We deal with a dataset that is big enough to require parallel indexing. The volume of writes are high enough that we end up losing a significant amount of writes _during_ the re-indexing (i.e. when the re-index jobs are still running). When we promote the index after re-indexing, the new index contains data that is stale. All the model update callbacks that ran ended up flushing updates to the old index, and not the new one.

Here's the series of events: 

- "Product A" is indexed in index `products_1`
- A change to search configuration is made, which requires a re-index. `Product.reindex(async: true)` is called.
- When the re-indexing is underway, Product A is updated to be Product A2 (same id, the name changes). This update only updates the product in the old index. The new index contains Product A, but since it is was indexed before the update, the data there remains stale. i.e. New index contains "Product A", old index contains "Product A2".
- After the re-indexing has completed, index `products_2` is promoted.
- `products_2` now has "Product A2" stored with the name "Product A".

**Describe the solution you'd like**

Would it be sufficient to always write to the latest available index, and not the one that the alias points to? That way when the alias is switched over to the new index after re-indexing, all data there should be up-to-date. Data served _during_ re-indexing might be stale, but that temporary staleness seems like a better option that data served _post_ re-indexing being stale forever.

**Comment by ankane** [comment]
Hey @rohitpaulk, thanks for the suggestion. I think you can mostly accomplish this right now by using `callbacks: :async` or `callbacks: :queue` for models, stopping the Searchkick background jobs during reindexing, and starting them again once it completes. This also has the advantage of not losing updates if the reindex fails for some reason.

**Comment by rohitpaulk** [comment]
Sounds reasonable. I'll let you close this (or keep it open if you think it could be handled within searchkick in some form). 

Thanks for the response!
