### ISSUE TITLE
case_insenstive and flags options with regexp

### ISSUE THREAD

**Issue by Jaroost** [ankane/searchkick#1461]
Is there a way to set [```case_insensitive``` and ```flags```](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html) options when searching with a regexp?

**Comment by ankane** [comment]
Hey @Jaroost, the Searchkick syntax doesn't support any flags right now, so you'd have to modify the query generated by Searchkick (see the Advanced Search section in the readme).

It looks like the `case_insensitive` option was recently added in Elasticsearch 7.10. I've added it to the plan for Searchkick 5, as the flag is ignored with a warning right now, so changing this would be a breaking change.

**Comment by rordev-lab** [comment]
Hi @ankane 
Could you please let me know if the above case-insensitive-based searching is available now?
or if you could let me know that how could I get started to change Searchkick query syntex to get it worked? 
Thanks

**Comment by jonowar** [comment]
@rordev-lab I had the same question and was playing around with it and reading the searchkick docs on [Advanced Search](https://github.com/ankane/searchkick#advanced-search) found this method modifying `body_options` to work:

```rb
Product.search(
  "francisco",
  body_options: {
    "query": {
      "bool": {
        "filter":[
          {
            "regexp":{
              "first_name":{
                "value":"J(I|A)M.I?E",
                "flags":"NONE",
                "case_insensitive": true
              }
            }
          }
        ]
      }
    }
  },
  load: false,
  limit: 1
)
```

Which will generate this elasticsearch query:

```
filed_contributions_production/_search
{
  "query":{
    "bool":{
      "should":[
        {
          "dis_max":{
            "queries":[
              {
                "multi_match":{
                  "query":"francisco",
                  "boost":10,
                  "operator":"and",
                  "analyzer":"searchkick_search",
                  "fields":["*.analyzed"],
                  "type":"best_fields"
                }
              },
              {
                "multi_match":{
                  "query":"francisco",
                  "boost":10,
                  "operator":"and",
                  "analyzer":"searchkick_search2",
                  "fields":["*.analyzed"],
                  "type":"best_fields"
                }
              },
              {
                "multi_match":{
                  "query":"francisco",
                  "boost":1,
                  "operator":"and",
                  "analyzer":"searchkick_search",
                  "fuzziness":1,
                  "prefix_length":0,
                  "max_expansions":3,
                  "fuzzy_transpositions":true,
                  "fields":["*.analyzed"],
                  "type":"best_fields"
                }
              },
              {
                "multi_match":{
                  "query":"francisco",
                  "boost":1,
                  "operator":"and",
                  "analyzer":"searchkick_search2",
                  "fuzziness":1,
                  "prefix_length":0,
                  "max_expansions":3,
                  "fuzzy_transpositions":true,
                  "fields":["*.analyzed"],
                  "type":"best_fields"
                }
              }
            ]
          }
        }
      ],
      "filter":[
        {
          "regexp":{
            "first_name":{
              "value":"J(I|A)M.I?E",
              "flags":"NONE",
              "case_insensitive":true
            }
          }
        }
      ]
    }
  },
  "timeout":"16s",
  "size":1
}
```

@ankane searchkick is rad, let me know if I could help by opening a PR for adding this functionality, (I think most of the work would happen around here: https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L1031-L1033)

**Comment by ankane** [comment]
I was originally planning to wait until Searchkick 5 to add this functionality, but think it's probably okay to add it now if you'd like to submit a PR.

**Comment by jonowar** [comment]
PR up with changes here: https://github.com/ankane/searchkick/pull/1510
