### ISSUE TITLE
Ability to choose between types of full-text search queries

### ISSUE THREAD

**Issue by tomcardoso** [ankane/searchkick#1464]
Thanks for this great gem – it was a breeze to tie into a project I'm working on. This feature request was actually previously discussed a couple of years ago, as part of https://github.com/ankane/searchkick/pull/1226, but I'm making the case for it again given some time has elapsed, and because I think it'd be worthwhile to be able to leverage the power of some of the other full-text search query types (particularly `simple_query_string`, which allows for "Google-like" natural search functions that non-techy end-users would be familiar with).

**Is your feature request related to a problem? Please describe.**
While I can technically use the advanced search functionality now, that requires rewriting the entire body of my request in ES's DSL. In doing that, I lose a lot of Searchkick functionality. Most importantly, I can no longer pass an easy list of clauses via `where`. I also can't rely on features like `misspelling: false`, or simple `order`, `limit` or `offset` parameters – everything would have to go through the DSL. It quickly becomes a nightmare if you're trying to dynamically construct a search. The great thing about Searchkick is that it hides a lot of the DSL complexity behind a nice, simple API.

**Describe the solution you'd like**
Perhaps the API could look something like:
```ruby
conditions = { is_active: true }
Product.search("\"Apple Pie\" -cake", query_type: "simple_query_string", where: conditions)
```

I realize there a million different parameters that could be passed to these, but I suppose those could be handled by editing the query body once it's formed after this step?

**Additional context**
This may be a tall ask, but it would be enormously powerful in cases where someone is doing what I'm doing – tying Searchkick into a big, user-facing search bar where a simple API would make tying everything together far easier than having to write hundreds of lines of code to properly construct an ES body object. Thanks for considering this.

**Comment by tomcardoso** [comment]
One other thing I should note – I'm only suggesting this after struggling (mostly unsuccessfully) with constructing complex, programmatically-generated `body` queries that may (or may not) have `where`-type filters, may or may not have custom ordering, etc. The nature of ES syntax makes it an enormous task to generate a queries depending on whether I'm filtering for a value, or against a date range, etc.

**Comment by tomcardoso** [comment]
FWIW, I've written a function to handle adapting the `match` query to a `simple_query_string` one, but it's a bit unseemly. Basically, I've monkey-patched the `Hash` class:
```ruby
module CoreExtensions
  module Hash
    def convert_to_sqs(mapping)
      result = {}
      self.map do |k, v|
        new_v = v.deep_dup
        if (mapping[k])
          # inside `match` query here, so time to rewrite it to `simple_query_string`
          mapped_key = mapping[k]
          inner_key = new_v.keys[0]
          new_v = new_v[inner_key]
          new_v[:fields] = [inner_key]
          new_v[:default_operator] = new_v.delete(:operator)
          if (new_v[:prefix_length])
            new_v[:fuzzy_prefix_length] = new_v.delete(:prefix_length)
          end
          if (new_v[:max_expansions])
            new_v[:fuzzy_max_expansions] = new_v.delete(:max_expansions)
          end
          new_v.delete(:fuzziness)
          result[mapped_key] = new_v
        else
          mapped_key = k
          result[mapped_key] = new_v.kind_of?(Hash) ? new_v.convert_to_sqs(mapping) : new_v
          result[mapped_key] = new_v.collect{ |obj| obj.kind_of?(Hash) ? obj.convert_to_sqs(mapping) : obj } if new_v.kind_of?(Array)
        end
      end
      result
    end
  end
end

Hash.include CoreExtensions::Hash
```

Then:

```ruby
conditions = { is_active: true }
query = Product.search("\"Apple Pie\" -cake", where: conditions, execute: false)
Product.search(body: query.body.convert_to_sqs({ :match => :simple_query_string }))
```

While this does work, it's obviously a bit gross, and there may be some edge cases I haven't accounted for (as you can see, part of that `convert_to_sqs` function is changing some key names around due to inconsistency in ES's API). Though I've managed to get it to work, I still believe having a query selection API of some sort would be worth considering.

**Comment by ankane** [comment]
Hey @tomcardoso, thanks for the suggestion. I still have the same thoughts as https://github.com/ankane/searchkick/pull/1226#issuecomment-461386272 on this one.

**Comment by alipman88** [comment]
Hi @ankane, I'd like to lobby for this as well.

Searchkick's API handles form inputs much more succinctly than ElasticSearch's. Typically (in a Rails app), one can pass a set of search form params directly to `Model.search`. Supposing I want to include a "use simple_query_string" option on my search form, #1226 would enable this without the need to write a bunch of custom logic translating my search form's inputs into radically varying ElasticSearch queries depending on whether the simple_query_string option is selected.

Sure, it's possible to use the advanced search to run a raw ElasticSearch query using `simple_query_string`, but the same can be said for any other option that SearchKick's API simplifies. Just because it's possible with advanced search doesn't feel like a strong reason not to implement this, IMO.

Thanks for the (re)consideration.
