### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadRequest - too_long_frame_exception

### ISSUE THREAD

**Issue by justi** [ankane/searchkick#1468]
I'm using ES Scroll API to retrieve a large amount of data. 

```ruby
results = []
MyModel.search(
      where: {
        ...
      },
      load: false,
      select: %w[field_1 field_2],
      scroll: '1m'
    ).scroll { |batch| results << batch }
```

Searchkick version: 4.3.0
Elasticsearch version: 6.8.9

on scroll method call I get
```
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."}],"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."},"status":400})
```
Maybe change the request type from GET to POST will fix this?

**Comment by ankane** [comment]
Hey @justi, haven't seen that error before. Can you enable logging for the Elasticsearch client:

```ruby
Searchkick.client.transport.logger = ActiveSupport::Logger.new(STDOUT)
```

And paste the output as well as the full stack trace?

**Comment by ankane** [comment]
Should have dug into this more before responding. Looks like changing the request type should fix it. Thanks for reporting and the fix!

**Comment by ankane** [comment]
Did not mean to reopen, but this just went out with a release
