### ISSUE TITLE
Custom Stemmer

### ISSUE THREAD

**Issue by dor6-jul** [ankane/searchkick#1471]
**First**
Search existing issues to see if it’s been discussed.

**Is your feature request related to a problem? Please describe.**
Im need support for a language that does not have native or easy stemming support.
for a solution I need to use a custom payed plugin.
I can do so with custom settings but its a bit of an overkill for just changing the stemmer & other than it i like seach kick default settings and mapping.
also i didn't manage to monkey patch 

**Describe the solution you'd like**
Either allow merge settings like in mapping, which allows to override certain filters or allow for custom stemmer.

**Additional context**
 in the meanwhile this is what I did to use custom stemmer:
 
```
module SearchkickExtensions
  class IndexOptions < Searchkick::IndexOptions
    def generate_settings
      setting = super
      add_hebrew_filter(setting)
      add_hebrew_filter_to_analyzers(setting)
      puts setting
      setting
    end

    private

    def add_hebrew_filter_to_analyzers(settings)
      settings[:analysis][:analyzer].each do |_, value|
        stemmer_index = value[:filter].find_index('searchkick_stemmer')
        if stemmer_index.present?
          value[:filter].insert(stemmer_index + 1, 'hebrew_stemmer')
        end
      end
    end

    def add_hebrew_filter(settings)
      settings[:analysis][:filter][:hebrew_stemmer] = {
        type: "hunspell",
        locale: "he_IL",
        dedup: false
      }
    end
  end
end

Searchkick::IndexOptions = SearchkickExtensions::IndexOptions

```
this is the only way i managed to get monkey patching to work, this is not a good way to monkey patch.
ignore the fact the i use hunspell when there is support for it, in the end i will use different stemmer this was just a test.

**Comment by ankane** [comment]
Hey @dor6-jul, thanks for the suggestion. You should be able to use the `settings` option for this (which is always merged).
