### ISSUE TITLE
custom anlyzers

### ISSUE THREAD

**Issue by dor6-jul** [ankane/searchkick#1473]
**Is your feature request related to a problem? Please describe.**
want to use custom analyzers with fields

**Describe the solution you'd like**
when giving the fields we will also be able to give analyzer per field

**Comment by ankane** [comment]
Hey @dor6-jul, thanks for another suggestion. You should be able to use features in the [Advanced](https://github.com/ankane/searchkick#advanced) section for this.

**Comment by dor6-jul** [comment]
> Hey @dor6-jul, thanks for another suggestion. You should be able to use features in the [Advanced](https://github.com/ankane/searchkick#advanced) section for this.

thank you, yes I can but the idea is i can set a custom matcher and that use it like other analysers searchkick creates.
so i define a matcher random_match and then in the fields i can add { name: :random_match }.

this matcher will allow me to use custom anlyzer

**Comment by ankane** [comment]
It's not something I'd like to support, but you should be able to fork the gem and add it.

**Comment by 9mm** [comment]
@ankane how do you actually add the analyzer? Ive been searching around for several hours to no avail. I'm trying to simply override the list of token filters, leaving everything else alone.

I tried adding a custom analyzer after adding it into settings and it just fails:

```
    mappings: {
      properties: {
        name: {
          type: 'text',
          analyzer: 'cartridge_analyzer',
        }
      },
    },
```

"reason":"unknown parameter [ignore_above] on mapper [name] of type [text]"
