### ISSUE TITLE
searchick reindex returns “Faraday::TimeoutError”,“Net::ReadTimeout”

### ISSUE THREAD

**Issue by RohitVenturit** [ankane/searchkick#1475]
**First**
Search existing issues to see if it’s been reported and make sure you’re on the latest version.

**Describe the bug**
Post.reindex return timeout error as shown here: Post Import (30696.7ms) {"count":135,"exception":["Faraday::TimeoutError","Net::ReadTimeout with #\u003cTCPSocket:(closed)\u003e"],"exception_object":"Net::ReadTimeout with #\u003cTCPSocket:(closed)\u003e"}

**To reproduce**
steps to reproduce: run Post.reindex on console.

```ruby
2.6.1

**Comment by ankane** [comment]
Hey @RohitVenturit, it looks like the connection is timing out. I'd confirm you can connect to Elasticsearch from the machine where you're seeing the error and double check your `ELASTICSEARCH_URL`.

(this is unlikely to be an issue with Searchkick, so going to close - check out the new issue page for where to get additional help)
