### ISSUE TITLE
Parallel Reindexing Not Working

### ISSUE THREAD

**Issue by sloanmamba** [ankane/searchkick#1476]
**Describe the bug**
I am currently trying to setup parallel reindexing for a model that holds a lot of data (~3M records). I would like to promote the index only when the reindex has been completed to best keep my DB and ES in sync but it appears `Model.reindex(async: true)` might not be working correctly.

When I run `Model.reindex(async: true)` it indeeds works but it seems to INSTANTLY promote the index.

**To reproduce**

`Option A`
1.  Configure your model to use Searchkick.
2. Run `Model.search_index.create`
3. Run `Model.reindex`
4. Run `Model.search_index.delete && Model.search_index.create`
5. Run `Model.reindex(async: true)` and you will notice that the model is instantly promoted if you search on it (example: `Model.search 'github'`will search the index even though it has to be promoted. 

`Option B`
1. Simply run `Model.reindex(async: true)` after you have a current index and you will notice that it uses your NEW index.

Note: I noticed the same behaviour  when I run `Model.reindex(async: {wait: true})`

`Running`

```
elasticsearch (7.10.0)
      elasticsearch-api (= 7.10.0)
      elasticsearch-transport (= 7.10.0)
    elasticsearch-api (7.10.0)
      multi_json
    elasticsearch-transport (7.10.0)
      faraday (~> 1)
      multi_json
searchkick (4.4.1)
      activemodel (>= 5)
      elasticsearch (>= 6)
      hashie
redis (4.2.5)
```

ON

```
RUBY VERSION
   ruby 2.7.1p83
rails (6.0.3.4)
BUNDLED WITH
   2.1.4
```

**Additional context**
None at this time but THANK YOU in advance : )

**Comment by ankane** [comment]
Hey @sloanmamba, the promotion will happen at the start if an alias doesn't exist. For option A, `Model.search_index.create` isn't meant to be called directly, since it creates an index instead of setting up an alias as `Model.reindex` does. If you remove steps 2 and 4, the index shouldn't be promoted until all records are imported on the last step.

**Comment by sloanmamba** [comment]
Hi @ankane, you are absolutely correct here!!!!

Honestly, thank you so so much! I really mean it. 

Thanks for all your contributions building so any world-class Rails Gem.

Best wishes my wiz friend.

**Comment by ankane** [comment]
Thanks @sloanmamba!
