### ISSUE TITLE
Support for Count API 

### ISSUE THREAD

**Issue by kapso** [ankane/searchkick#1481]
Add support for Count API - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html

I had asked this question here - https://stackoverflow.com/questions/63002404/searchkick-count-query

**Comment by ankane** [comment]
Hey @kapso, thanks for the suggestion. I've considered this in the past (#632), but don't think it's common enough to support now. You may be able to get similar results with `Model.search("query", limit: 0).total_count`.

**Comment by kapso** [comment]
@ankane thanks, that makes sense. Guessing also need to add `body_options: { track_total_hits: true }`
