### ISSUE TITLE
Plugin System for Data Sources

### ISSUE THREAD

**Issue by daaasbu** [ankane/searchkick#1483]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use data with searchkick that is not via ActiveRecord / Mongoid. In my specific use case, I would like to sync data that is mapped to an API instead of a database but I could imagine it would be nice for other potential data stores as well. 

For this specific use case, using an ActiveRecord supported db does not work because I have business logic that is encapsulated at the API layer for another service that is not written to the db but calculated at request time. So I'm currently in a place where we need to duplicate business logic in the searchkick layer or precompute all business logic and save it to the db. 

**Describe the solution you'd like**

It would be nice to be able to implement an interface or supply a class that implements a simple set of the fetching methods that Searchkick needs. I guess this would be possible if you implemented the ActiveRecord / Mongoid interface but those are both pretty wide interfaces that I imagine have a lot of additional cruft that isn't needed for Searchkick specifically. 

**Additional context**

I imagine this feature is a pretty big lift, so I was wondering if there were any recommendations for accomplishing this in the current Searchkick setup as well. Is my best bet to implement the ActiveRecord interface for my API?

**Comment by ankane** [comment]
Hey @daaasbu, thanks for the suggestion! It's an interesting idea, but prefer not to add the additional complexity right now. The options you mention in the 2nd paragraph seem like the best way to do it with Searchkick, but it may be simpler to use another gem that's designed for that use case.

**Comment by daaasbu** [comment]
@ankane awesome, thanks for the info! Any gems you would recommend particularly?
