### ISSUE TITLE
Passing an array of dates to the boost_by_recency search option

### ISSUE THREAD

**Issue by alipman88** [ankane/searchkick#1484]
I would like to pass an array of dates to the `boost_by_recency` option. To provide a contrived example, let's say I want to find children born near a recent lunar eclipse:

```ruby
@eclipse_dates = ['2020-01-10', '2020-06-05', '2020-07-05', '2020-11-03']
```

I've written the following monkey patch to enable this:

```ruby
module SearchkickQueryExtensions

  def set_boost_by_recency(custom_filters)
    origin = options.dig(:boost_by_recency, :sent_at, :origin)
    return super unless origin.is_a? Array

    origin.each do |o|
      options[:boost_by_recency][:sent_at][:origin] = o
      super
    end
  end

end

class Searchkick::Query
  prepend SearchkickQueryExtensions
end
```

Now, I can run a query like the following:

```ruby
Child.search(
  boost_by_recency: {
    date_of_birth: {
      origin: @eclipse_dates,
      scale: '7d',
      decay: 0.5,
    },
  },
)
```

Does this sound like a useful feature to anyone else? If so, I'm happy to submit something similar as a PR. (I think there's a means of accomplishing the same via custom scoring function, but this might provide a quick solution for those hoping to avoid a dive into the Elasticsearch docs.)

**Comment by ankane** [comment]
Hey @alipman88, thanks for sharing and the suggestion! I'm not sure it's common enough to support, but the patch should be useful to users who need it.
