### ISSUE TITLE
Allow custom search_analyzer for query

### ISSUE THREAD

**Issue by brunosedler** [ankane/searchkick#1488]
I work on an application which has localized contents. The contents for each locale are indexed with same record, so one record for example has the fields `title_en` and `title_de`.  I would like to use different stemmers for those different fields of the record, according to their locale.
 
As far as I could see, I can only pass in one language to the `Searchkick::Model` class. However, I was able to configure custom analyzers via the index settings, and add those via the index mappings to the fields. 

My problem is, that I need the same stemmers at search time, and at index time. Unfortunately at search time the analyzers are hardcoded. I tried overwriting the `searchkick_search` analyzer, but adding multiple stemming filters did not work as I'd like, as some words were stemmed more in one language than the other and therefore no results were found. 

I would like a `search_analyzer` option for the `Searchkick.search` method where I can pass in the name of an analyzer, and have the query use this analyzer additionally to or as a replacement for the default analyzer of the query.

**Comment by ankane** [comment]
Hey @brunosedler, see #1473.
