### ISSUE TITLE
Error when reindexing

### ISSUE THREAD

**Issue by u-akira** [ankane/searchkick#1489]
When I set language: "japanese"  and search_synonyms: "synonyms.txt" and ran reindex, I got a NoMethod  (undefined method `insert` for nil:NilClass).

I think it's because there is no "filter" in searchkick_search2 when I set language: "japanese".

```
"searchkick_search2" : {
     "type" : "kuromoji"
 },
```
https://github.com/ankane/searchkick/blob/a9b57db1ff4dedcac82cc7cf0ebf7d0891d99a6e/lib/searchkick/index_options.rb#L515-L517

I used custom mapping to get around this issue.

**Comment by ankane** [comment]
Hey @u-akira, thanks for reporting! I added a `japanese2` language that supports synonyms and stemming options (will make it the default for `japanese` in Searchkick 5). Also improved the error message if a language doesn't support synonyms yet.
