### ISSUE TITLE
`model_name` throws an error when Searchkick::Results contains multiple models

### ISSUE THREAD

**Issue by nathunsmitty** [ankane/searchkick#1491]
**Describe the bug**
When searching across [multiple models](https://github.com/ankane/searchkick#multiple-models), the returned Searchkick::Results object will throw the following error:

```
*** NoMethodError Exception: undefined method `model_name' for nil:NilClass
```

This is because `klass` is not defined on Searchkick::Results with multiple models. Since `model_name` [depends on `klass`](https://github.com/ankane/searchkick/blob/df1364c890113259f26116389896e941eebbd81d/lib/searchkick/results.rb#L73), an error is raised here when `klass` is not defined.

I first noticed this issue with Kaminari's `page_entries_info`, which relies on `model_name` in order to work.

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Elasticsearch version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end

  create_table :categories do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick
end

class Category < ActiveRecord::Base
  searchkick
end

Product.reindex
Category.reindex
Product.create!(name: "Apple Sauce")
Category.create!(name: "Apple Products")
Product.search_index.refresh
Category.search_index.refresh
results = Searchkick.search "apple", models: [Product, Category]
results.model_name
```

**Additional context**
My suggestion for a fix would be to default to "Result" if `klass` is undefined in Searchkick::Results. Happy to make a PR for this if you'd like. Open to other alternative fixes as well!

This issue is somewhat related to #139.

**Comment by ankane** [comment]
Hey @nathunsmitty, thanks for reporting! `Result` makes sense to me. Happy to review a PR.

**Comment by nathunsmitty** [comment]
Awesome! PR up in #1492

**Comment by ankane** [comment]
PR merged 🎉
