### ISSUE TITLE
Support for a separate environment variable for Bulk reindex

### ISSUE THREAD

**Issue by kapso** [ankane/searchkick#1493]
This could be unique to our case, but here it goes...

We use Heroku for our background Jobs (Sidekiq), and some jobs hit the live Elastic server for some batch queries (Scroll API), but the Bulk Index jobs need to hit the new Elastic server. 

We don't do Bulk Reindex on an existing live server but on a fresh deployment. Right now, once we start Bulk Reindex, we have to Slack communicate to the team to not start any Elastic batch queries, and our reindex takes more than a day, we have ~35m documents to index.

Thinking of possible solutions -- if introducing another environment variable introduces complexity, perhaps passing the URL to the `reindex` method could work?

Thanks for reading.

**Comment by ankane** [comment]
Hey @kapso, thanks for the suggestion, but it's not something I'd like to support.
