### ISSUE TITLE
Use Boolean Operator(mini-language) in where clause

### ISSUE THREAD

**Issue by ZeeshanAslam-tkxel** [ankane/searchkick#1494]
Hi Folks,
I had implement SearchKick in my rails app. That app holds all the feature of searching that a recruiter app can have. I had working on this app for last 2 years and my searching query is written well enough to hold the aggregated data and some conditional clauses as well. Now i want to implement "mini-language"([Boolean query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax)) that was supported by elastic search using `query_string`.

I want to use `query_String` with existing SearchKick query. I know i can use Advanced Search but for this i had to replace my current SearchKick query with ElasticSearch query. I don't want to do that because was the big change for my project which is live and has 1000+ of users and i don't know how it can impact.

I want to adjust `query_string` in seachKick query in some way so that i should not replace with ES query. If you can help me in to figure it out.It will be great.

Looking forward to hear from you.
Thanks

**Comment by ankane** [comment]
Hey @ZeeshanAslam-tkxel, thanks for the suggestion, but it's not something I'd like to support.
