### ISSUE TITLE
Use sorted set for ReindexQueue instead of list

### ISSUE THREAD

**Issue by willcosgrove** [ankane/searchkick#1495]
Would you be interested in a PR to change the Redis data type being used to store the ReindexQueue? It's currently stored in a list, which achieves the need to make sure every item gets processed: push to one end of the list, pop from the other end. But the current implementation is very chatty with Redis. It calls `rpop` in a loop.

https://github.com/ankane/searchkick/blob/6ea0c2fd27dff3d07c06f29356e03fc864680bf3/lib/searchkick/reindex_queue.rb#L16-L22

(It also should probably hold that Redis connection it gets in the `with_redis` block for the entirety of the loop instead of requesting a new connection on each iteration, but that can be addressed separately.)

At first, I thought this would be a good candidate to use the new `count` parameter added to `rpop` in Redis 6.2. But doing that would still potentially require many `rpop` calls because of the deduplication happening by pulling the records off into a set.

Since it doesn't benefit us to store multiples of the same ID to reindex, we can push that set behavior to Redis while maintaining our queue-like access by using a sorted set.

The new implementation would essentially just be:

```rb
def push(record_id)
  Searchkick.with_redis { |r| r.zadd(redis_key, Time.now.to_f, record_id, nx: true) }
end

def reserve(limit: 1000)
  Searchkick.with_redis { |r| r.zpopmin(redis_key, limit) }
    .map { |(id, _score)| id }
end

def clear
  Searchkick.with_redis { |r| r.del(redis_key) }
end

def length
  Searchkick.with_redis { |r| r.zcard(redis_key) }
end
```

And for the work with the reindex refactor, the `push` method can handle multiple records like this:

```rb
def push(*record_ids)
  now = Time.now.to_f
  record_ids.map! { |id| [now, id] }
  Searchkick.with_redis { |r| r.zadd(redis_key, record_ids, nx: true) }
end
```

The reason why you may not want to make this change is that there is extra work involved in figuring out how to handle the upgrade process. I can think of two reasonable options:

1. **Make the upgrade opt-in**
   
   The user would have to now configure what ReindexQueue implementation to use, with the default needing to be the current List implementation.
2. **Make the upgrade mandatory but transparent**
   
   Add additional migration handling code that would detect if the backing key was not a sorted set, and if not would run some code to move the records into a sorted set before continuing.

   In the past when I've done things like this, I will usually include a Redis lua script that is capable of performing a data migration atomically.

I would be happy to submit a PR for this if it's wanted, and once I know how you would want to handle the upgrade problem. And thanks for your work on Searchkick!

**Comment by ankane** [comment]
Hey @willcosgrove, thanks for the suggestion. Check out #1141 for previous discussion about lists vs sorted sets (in short, lists have better performance characteristics for this use case).

I think two improvements we can make to the current implementation based on your post are:

1. Hold the Redis connection for the entire method
2. Use the `count` parameter if Redis version is >= 6.2

Happy to review a PR for them (together or separate is fine).

**Comment by willcosgrove** [comment]
@ankane sorry, I didn't see the previous issue about this 😞

Lists do have the better performance characteristics for appending, but there is still a cost that gets paid when it is loaded into a set. I guess I would just leave this here in case it persuades you:

```
$ ./redis-benchmark -q -r 10000000 -n 10000000 zadd sortedset 10
ele:rand:000000000000
zadd sortedset 10 ele:rand:000000000000: 69898.79 requests per second

[...]

Long story short, sorted sets are fast and keep to be fast even when
you have millions of elements inside.

Cheers,
Salvatore
```
Source: https://groups.google.com/g/redis-db/c/4TAItKMyUEE/m/C_cwqXs22SEJ

---

I'm happy to open a PR for improvement 1. Improvement 2 will, unfortunately, involve needing to check the version of Redis and the redis-rb client. I don't know how you normally handle cases like that, I'll have to go look through the codebase. But improvement 1 seems easy enough to get a PR open for.

**Comment by ankane** [comment]
A few thoughts on 2:

- For the Redis version, we should be able to use a similar approach as the Elasticsearch version
- We can use `call` instead of `rpop` to support older Redis clients (instead of checking its version)
- `reserve` should be able to return duplicate ids (so only a single call is needed with Redis 6.2+)
