### ISSUE TITLE
Searchkick dynamic mapping on JSON object

### ISSUE THREAD

**Issue by acetinick** [ankane/searchkick#1496]
I have a scenario where i have custom fields against records,  and stored in a JSONB format in the database eg.  

The **fields** JSONB column stored on each of my records, which stored values of custom fields 

```
searchkick word_start: [
                 :full_name,
                 :position
               ],
               filterable: [
                 :id,
                 :full_name,
                 :fields
               ],
               deep_paging: true
```

eg. of fields values, where the hash key is the custom field ID row in the database
```
{
  "31": "Andrew", 
  "45": "1"
}
```

I would like to filter these records somehow,  similar to:

where: {
    "fields.31": "Andrew"
}

I been researching and looks that I need to use dynamic mapping in elastic search as per https://dzone.com/articles/custom-field-handling-in-elasticsearch-how-to-batt

Is there a way I can do this with Searchkick somehow?

**Comment by acetinick** [comment]
This is as far as I got, but getting this error

in model:

I index the object into fields



```
 searchkick merge_mappings: true,
               mappings: {
                 properties: {
                   fields: {
                     type: "nested"
                   }
                 }
               },
               searchable: [
                 :full_name
               ],
               filterable: [
                 :id,
                 :full_name
               ]

def search_data
      hash = {
        id: self.id,
        full_name: self.full_name
     }

      hash[:fields] = {}
      self.field_data.each do |key, value|
        hash[:fields]["cf_#{key}".to_sym] = value if value.present?
      end

      hash
    end
```

in my controller

```
Applicant.search("*", where: {
    "fields.cf_5" => "Andrew"
}
```

and i get this error

Searchkick::InvalidQueryError - [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: Cannot search on field [fields.cf_5] since it is not indexed.","index_uuid":"pHvizwQaSR2Jkibrdq1HVg","index":"applicants_development_20210629152538232"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"applicants_development_20210629152538232","node":"sJZuiFSRRQaP2VJfByZiFA","reason":{"type":"query_shard_exception","reason":"failed to create query: Cannot search on field [fields.cf_5] since it is not indexed.","index_uuid":"pHvizwQaSR2Jkibrdq1HVg","index":"applicants_development_20210629152538232","caused_by":{"type":"illegal_argument_exception","reason":"Cannot search on field [fields.cf_5] since it is not indexed."}}}]},"status":400}:

**Comment by RolandStuder** [comment]
@acetinick as discussed in the discord, it cn be done with custom mappings, but forces you to also used advanced search notation, just putting this here for future reference:

## So you need a custom mapping

```ruby
    searchkick merge_mappings: true, mappings: {
      properties: {
        custom_fields: {type: "object", dynamic: true}
      }
    }
```

## But you also need advanced search

Custom mappings require you to use advanced search, so `SomeModel.search(where …)` will actually not yield any results for object queries. So you need to query with pure elastic search notation:

```ruby
SomeModel.search(body: {query: {bool: {filter: [{term: {"custom_fields.year": {value: 1916}}}]}}})
```

@ankane would you be open for a PR to allow using the `object` type, so one could use it with a `.where("custom_fields,year": 1916)` ? Or is there actually some limitation which makes this hard/impossible. I had a look at the codebase, but did not get much farther than creating a failing test case.

**Comment by ankane** [comment]
Nested data [should work](https://github.com/ankane/searchkick#nested-data) without a custom mapping for the `fields` and `where` options (you may need to remove `filterable` and reindex since I'm not sure that option supports nested data).

**Comment by acetinick** [comment]
Yep @ankane the solution was actually to remove all my fitlerable options, after reindex, and then it started working.

Thanks for your help @RolandStuder !

For me it also worked with normal query options such as wherel

**Comment by acetinick** [comment]
@ankane If I remove filterable, i think then it would automatically add ALL fields to the index? correct?  Because I get this error, when trying to reindex, and its because I think its trying to index a text column as a filter,  and this is not something that usually needed,  and should be excluded using the filterable options.

<img width="1181" alt="Screenshot 2021-07-06 at 17 25 54" src="https://user-images.githubusercontent.com/571649/124626722-38cb6a00-de7f-11eb-9b20-60ace77ff584.png">

**Comment by ankane** [comment]
Yeah, all fields are filterable by default. Searchkick has limited support for nested data, so you'll need to flatten it to use the `filterable` option.

**Comment by acetinick** [comment]
Hi @ankane could you clarify what you mean by flatten?

**Comment by ankane** [comment]
Unnest - `{fields: {cf_5: "value"}}` to `{fields_cf_5: "value"}`

**Comment by acetinick** [comment]
Yea this won’t work for Me as we are in multi tenant setup. So is this limitation of this library? I’ll have to resort using elastic search directly?
