### ISSUE TITLE
Dynamic Template is unexpectedly defined in one env but not the other.

### ISSUE THREAD

**Issue by richardsondx** [ankane/searchkick#1497]
**First**

```
Searchkick Version: 2.5.0
Elasticsearch Version: 5.4.3
```

**Describe the bug**

I'm running the exact same query on two environment that have identical Searchkick and Elasticsearch version but I'm getting two different results. It seem that searchkick/elasticsearch is case sensitive in one environment and expect lowercase on the other. I thought that was a config issue but the only location where I found dynamic_template defined was in searchkick code. 
There are no dynamic setting set on my app.  

**To reproduce**

### On my local: 

The search is case-sensitive and able to provide a response when the `add_on_type` is `SuperAddOn` but won't return anything if its `superaddon`. I also noticed a `dynamic_template` in the response.

``
effective_url=http://localhost:9200/add_ons_development/_mapping response_code=200
``

```
  "add_ons_development": {
    "mappings": {
      "add_on": {
        "_all": {
          "analyzer": "searchkick_index"
        },
        "dynamic_templates": [
          {
            "string_template": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "fields": {
                  "analyzed": {
                    "analyzer": "searchkick_index",
                    "index": true,
                    "type": "text"
                  }
                },
                "ignore_above": 30000,
                "include_in_all": true,
                "type": "keyword"
              }
            }
          }
        ],
        "properties": {...
```

### In staging  (remote server):
The search expect lowercase and isn't able to find an item when the `add_on_type` is `SuperAddOn` but it will return one when its lowercase `superaddon`.

There's more than one inconsistency but the one that caught my attention is that  one environment uses dynamic_template (my local env) and the other doesn't. 

``
effective_url=http://my_staging_elasticsearch_server/add_ons_development/_mapping response_code=200
``

query:

```
Addon.search("*", page: 1, per_page: 15, fields: [{:id=>:exact}, :title],  misspellings: {below: 5, edit_distance: 2}, match: :word_start, where: { add_on_type: "SuperAddOn", user_id: "1234", state: ["paid","expired"] }, order: {created_at: :desc})
```

In staging it goes straight to `properties` and there are no dynamic template.
````
{
  "add_ons_staging": {
    "mappings": {
      "add_on": {
        "properties": {
````

**Additional context**
Elasticsearch Query
```
curl http://localhost:9200/add_ons_development/_search?pretty -H 'Content-Type: application/json' -d '{"query":{"bool":{"must":{"match_all":{}},"filter":[{"term":{"add_on_type":"SuperAddOn"}},{"term":{"user_id":"1234"}},{"terms":{"state":["paid","expired"]}}]}},"size":15,"from":0,"sort":{"created_at":"desc"},"timeout":"11s","_source":false}'
````

**Usefull resource**
I found this doc about dynamic template: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html

`You enable dynamic mapping by setting the dynamic parameter to true or runtime` 

The app isn't setting anything like that at runtime. 

What's happening?

**Comment by ankane** [comment]
Hey @richardsondx, it sounds like you need to run `Addon.reindex` on staging. If that doesn't fix it, please use the code in the new issue template to reproduce.

**Comment by richardsondx** [comment]
@ankane  I did try to `reindex` but it didn't work. Can reindexing pass/remove the dynamic template? and Is there a setting for turning off the dynamic template?

**Comment by ankane** [comment]
Check out the Advanced section for how to pass a custom mapping.
