### ISSUE TITLE
Support for filterable with mappable object/nested field

### ISSUE THREAD

**Issue by acetinick** [ankane/searchkick#1499]
Related to #1496 https://github.com/ankane/searchkick/issues/1496

Nested objects are wokring fine when being indexed, however with our production data indexing causing exception with trying to index a text column that is too long.  Below is mapping, with image of exception.

```
searchkick merge_mappings: true,
               mappings: {
                 properties: {
                   custom_fields: {
                     type: "object", dynamic: true
                   }
                 }
               },
               searchable: [
                 :full_name,
                 :email,
                 :resume_text
               ],
               word_start: [
                 :full_name
               ]
```

![image](https://user-images.githubusercontent.com/571649/124694879-685f8e00-dee2-11eb-93a4-412bfe286e8f.png)

However using the filterable option to specify columns fails, and causes another exception saying that the 'custom_fields' column isn't indexed.

 filterable: [
                 :full_name,
                 :email,
                 :custom_fields
               ]

Would be amazing if we can allow support of filterable: [] option along with object types

**Comment by ankane** [comment]
Hey @acetinick, thanks for the suggestion, but it's not something I'd like to support (you can unnest the data as mentioned in #1496).
