### ISSUE TITLE
Redis not configured when using reindex async wait in migration

### ISSUE THREAD

**Issue by acetinick** [ankane/searchkick#1501]
Hi I am trying to run a reindex async wait inside migration but get this redis error when using the wait option.  

Below is the redinex code i have,  which I assume is correct from the documentation. Anyone else come across this?

```
response = Product.reindex(async: {wait: true})
Searchkick.reindex_status(response[:index_name)
```

== 20210713172512 ApplicantReindex4223: migrating =============================
Created index: applicants_development_20210713172806029
Jobs queued. Waiting...
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Redis not configured
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick.rb:190:in `reindex_status'
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick/index.rb:345:in `block in reindex_scope'
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick/index.rb:343:in `loop'
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick/index.rb:343:in `reindex_scope'
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick/index.rb:221:in `reindex'
/usr/local/bundle/gems/searchkick-4.5.0/lib/searchkick/model.rb:64:in `searchkick_reindex'
/usr/src/app/db/migrate/20210713172512_applicant_reindex4223.rb:3:in `change'
/usr/local/bundle/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:828:in `exec_mi

**Comment by ankane** [comment]
Hey @acetinick, check out the readme for how to configure Redis.
