### ISSUE TITLE
Issue in v4.5.1 release: undefined method `any?' for nil:NilClass

### ISSUE THREAD

**Issue by nickcampbell18** [ankane/searchkick#1506]
Apologies, we haven't had time to submit a detailed bug report, but we've had some issues with the [`v4.5.1`](https://github.com/ankane/searchkick/blob/master/CHANGELOG.md#451-2021-08-03) release and were forced to rollback:

```
undefined method `any?' for nil:NilClass

lib/searchkick/process_queue_job.rb:11 block in perform
lib/searchkick/process_queue_job.rb:9 loop
lib/searchkick/process_queue_job.rb:9 perform
app/jobs/process_reindex_queue_job.rb:4 perform
lib/active_job/execution.rb:48 block in perform_now
lib/active_support/callbacks.rb:117 block in run_callbacks
lib/i18n.rb:314 with_locale
lib/active_job/translation.rb:9 block (2 levels) in <module:Translation>
....
```

We're using Redis `v6.2.4`:

```ruby
[1] pry(main)> Searchkick.with_redis { |r| Gem::Version.new(r.info["redis_version"]) }
=> Gem::Version.new("6.2.4")
```

So it looks like the bug is with [this line](https://github.com/ankane/searchkick/blob/4a8315fb98e14f9183a6060be342ae489361522a/lib/searchkick/reindex_queue.rb#L18):

```
Searchkick.with_redis { |r| r.call("rpop", redis_key, limit) }
```

I might have time tomorrow to look into this in more detail, but I hope that helps for now!

**Comment by ankane** [comment]
Thanks @nickcampbell18! Will push out 4.5.2 shortly.
