### ISSUE TITLE
OpenSearch support / Elasticsearch client version pinning

### ISSUE THREAD

**Issue by robsears** [ankane/searchkick#1507]
I'm not seeing any discussion of OpenSearch in the issues or tagged as `[SearchKick]` on StackOverflow, so I thought I'd put it here.

The [latest release](https://github.com/elastic/elasticsearch-ruby/releases/tag/v7.14.0) of the elasticsearch client adds some code that prevents the gem from working with "unsupported" versions of Elasticsearch. "Unsupported" in this context means:

* Any 7.x version of Elasticsearch that is of the "oss" flavor (the Apache 2.0-licensed builds)
* Any version of Elasticsearch prior to 6.x
* OpenSearch (which was previously supported indirectly, as it's just a fork of Elasticsearch 7.10)

Because SearchKick [currently](https://github.com/ankane/searchkick/blob/8b114aa5ef7918c5af84f33317e118ab69ce178a/searchkick.gemspec#L19) calls for a version of the gem equal to or greater than 6, this means that any user with an "oss" build of Elasticsearch 7.x is going to receive a `UnsupportedProductError` exception if they end up with the latest version of the elasticsearch gem.

In the short term, it might be worth adding something like this to the gemspec:

```
spec.add_dependency "elasticsearch", ">= 6", "<= 7.13"
```

Longer term, it would be great if SearchKick was decoupled from Elastic's licensing terms. Amazon has [announced plans](https://aws.amazon.com/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/) to release an Apache 2.0 client that will be compatible with OpenSearch. I suspect that most (if not all) of the Elasticsearch features SearchKick relies on will be present in OpenSearch, and available through their open sourced client. That would make the client cross-compatible with Elasticsearch, while avoiding the license war that's going on. 

It might even make sense, given SearchKick's level of abstraction, to support either Elasticsearch or OpenSearch, whatever the user wants. Ultimately, I think that SearchKick users would benefit from this.

**Comment by ankane** [comment]
Hey @robsears, thanks for bringing this up.

I considered updating the gemspec, but think it's better to allow Elasticsearch users to use the latest version, so added additional instructions to the readme for OpenSearch users instead: https://github.com/ankane/searchkick/commit/6e7ca8c4da994de04e58a8549ac28fc676020b8e.

For Searchkick 5, we can remove the dependency from the gemspec and have users add the client they want to use in their Gemfile.

**Comment by robsears** [comment]
TY!

**Comment by ankane** [comment]
No problem

**Comment by ankane** [comment]
Just fyi, pinned the version in the gemspec since it was also causing issues with the open-source version of Elasticsearch (including Homebrew, AWS, and Bonsai).
