### ISSUE TITLE
Elasticsearch::UnsupportedProductError (The client noticed that the server is not a supported distribution of Elasticsearch.)

### ISSUE THREAD

**Issue by siddhant-mohan** [ankane/searchkick#1509]
**Describe the bug**
Getting this error when using searchkick with elasticsearch on mac.
$ Searchkick version:   searchkick (4.5.2)

$ elasticsearch --version
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
Version: 7.10.2-SNAPSHOT, Build: oss/tar/unknown/2021-01-16T01:41:27.115673Z, JVM: 16.0.2

**To reproduce**

```ruby
Product.reindex
```

**Comment by MMatero** [comment]
I had the same issue, if you are using ES hosted on AWS you might want to add 

gem 'elasticsearch', '< 7.14'

to your gemfile and update. This fixed it for me for now.

**Comment by siddhant-mohan** [comment]
I am running on mac as of now.

**Comment by siddhant-mohan** [comment]
https://stackoverflow.com/questions/68762774/elasticsearchunsupportedproducterror-the-client-noticed-that-the-server-is-no?noredirect=1#comment121523938_68762774

**Comment by wflanagan** [comment]
I agree, this sucks. But, it's 100% not Searchkick.  It's Elastic.co and their decision to make a breaking change on a minor release.

**Comment by tannerbrandt** [comment]
If you are not using elasticsearch on Mac (installed using homebrew), and you are not using opensearch, then making sure that you have the latest version of elasticsearch installed using homebrew is the fix. Running ```brew install elasticsearch``` is only going to install version 7.10.0 of elasticsearch to your mac. Instead, run ```brew tap elastic/tap``` and then ```brew install elastic/tap/elasticsearch-full``` to install version 7.14.0 of elasticsearch. Then run ```brew start elasticsearch-full``` to run elasticsearch in the background of your mac. 

After upgrading, you don't need to add ```gem 'elasticsearch', '< 7.14'``` to your gem file. You can update to the latest version of searchkick and all will be well. 

Again, this isn't the case if you use OpenSearch - for that, you'll have to downgrade elasticsearch for now, exactly as what people have stated above.

**Comment by Nodalailama** [comment]
Hi,

I am using heroku x banzai addon ... and right know my search is not anymore working...
I have mailed banzai to be allowed to get a specific version.
If someone as a temp solution, please tell me.

Could the maintainer of searchkick, which is a super lib, make an update ?

Thank you in advance.

**Comment by Nodalailama** [comment]
Ok. If your are using heroku with banzai and you want to select a specific version ... you need to get a 700 bucks plan. 
So, if you wanna wait searchkick update to support 7.2 then you can add a different addon from heroku.

Thus, don't remove banzai, keep it aside, install searchbox (https://elements.heroku.com/addons/searchbox) with this command: heroku addons:add searchbox:starter --es_version=7.14 then update the "ELASTICSEARCH_URL" env variable with the newly created var "SEARCHBOX_SSL_URL".

And voilà, it's working and you can wait :)

**Comment by ankane** [comment]
I've added `< 7.14` to the gemspec so things work out of the box.

**Comment by clemensg** [comment]
> I've added `< 7.14` to the gemspec so things work out of the box.

I am not sure that's the best solution. I use ElasticSearch 7.14 and now `bundle update` does not update searchkick from 4.5.2 to 4.6.0 due to that dependency..

**Comment by ankane** [comment]
Hmm, yeah, it's not ideal. The two main options (that I can think of) are:

1. Leave the dependency open-ended as was the original plan (#1507). Users who update the `elasticsearch` gem will get an error with Homebrew, AWS, Bonsai, and other open-source distributions. New users will also get an error (although we could add more instructions to the readme for them).
2. Set the dependency to < 7.14 was done in the 4.6.0 release. Things will work out of the box for users who haven't updated to `elasticsearch` 7.14.0 and new users (I imagine this will be most users since it was released 18 days ago). Users who updated to `elasticsearch` 7.14.0 already will need to specify `gem 'searchkick', '>= 4.6'` to get it to update.

The current plan for Searchkick 5 (#1288) is to remove the dependency from the gemspec and have users add the client they want to use in their Gemfile (`opensearch` or `elasticsearch`), so hopefully this isn't an issue for too long.

**Comment by gsar** [comment]
@ankane please revert the `< 7.14` change to searchkick.gemspec. It makes it impossible to use searchkick with the newer elasticsearch versions.

**Comment by Chocksy** [comment]
Another solution would be to add in the initializer this code change:

`elasticsearch.rb`

```ruby
module Elasticsearch
  class Client
    def verify_with_version_or_header(body, version, headers)
      @verified = true
    end
  end
end
```

Code suggested here: https://github.com/elastic/elasticsearch-ruby/issues/1429
