### ISSUE TITLE
Tainted model scope with scoped reindex

### ISSUE THREAD

**Issue by rbviz** [ankane/searchkick#1511]
`search_data` has tainted model scope on relation reindex context

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
end

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick

  def search_data
    attributes.merge(taint: Product.scope_attributes)
  end
end

Product.create!(name: "Test")
Product.create!(name: "Best")

Product.where(name: "Test").reindex # where magic happens
Product.search_index.refresh
p Product.search(load: false).results.pluck(:taint)
```

results: 
```ruby
=> [{"name"=>"Test"}]
```

So any queries performed on `Product` within `search_data` will have a scope of `name: "Test"`.

So let's say we do a count `Product.count`, would be the same as `Product.where(name: "Test").count`. With the only remedy being using `unscope` in application code.

**Comment by ankane** [comment]
Hey @rbviz, thanks for reporting. This should be fixed in the `scope_attributes` branch, but going to wait until Searchkick 5 to merge since it seems like a riskier change (also, I'm planning to make significant changes to the reindex logic for that release).

**Comment by ankane** [comment]
Hey @rbviz, this is fixed in Searchkick 5 (just released). Thanks again for reporting.
