### ISSUE TITLE
Parallelisation instructions: `index_suffix` is ignored if model is loaded before `parallelize_setup` runs

### ISSUE THREAD

**Issue by nickcampbell18** [ankane/searchkick#1512]
**Describe the bug**

I had an issue when following the Rails parallel test instructions. If the model is loaded before the test forking happens (e.g. when the app boots), the `parallelize_setup` block has no effect.

Our controller tests use a DSL for describing the controller (unfortunately I cannot share, but there is an example below), which causes the model to be loaded upfront, including the `searchkick` invocation. This has the unfortunate side effect that the the `index_name` is now cached on `Variant` under [`@@searchkick_index`](https://github.com/ankane/searchkick/blob/a9b57db1ff4dedcac82cc7cf0ebf7d0891d99a6e/lib/searchkick/model.rb#L39). At that point in time, `Searchkick.index_suffix == nil`, so the resultant index name is `variants_test`.

Now, when the test forks and starts executing, all future calls to `Variant.searchkick_index` will retain that old name `variants_test`, rather than re-computing the new name. This means that the tests will collide and try to add/update/delete the same index on the ElasticSearch instance, leading the tests to fail in an unpredictable way.

I'm aware that loading the model before running the tests is stupid & dangerous (e.g. Rails will warn you if an initializer loaded one of your models, it can be unsafe), but nonetheless I would say that this was definitely surprising to me that changing the global properties didn't affect the existing config. It looks to me like the `index_name` calculation is both [pretty cheap](https://github.com/ankane/searchkick/blob/a9b57db1ff4dedcac82cc7cf0ebf7d0891d99a6e/lib/searchkick/model.rb#L25-L32) and easily re-computable at a later time (you could use `Variant.searchkick_options`) - so as a fix I think we could have a hook to rebuild the name, or just calculate the name dynamically when needed?

I'd be happy to submit a PR if you think this is worth fixing. At the moment I'm unable to easily stop loading the model outside of a test execution, so the only other solution I'm considering is making the searchkick index setup lazily executed when trying to call `Variant.reindex` or `Variant.search` (which would hopefully be deep inside a test run).

**To reproduce**

```
$ cat Gemfile.lock  | grep search
elasticsearch (7.13.1)
elasticsearch-api (7.13.1)
elasticsearch-transport (7.13.1)
searchkick (4.6.0)
```

```ruby
# test/test_helper.rb
parallelize_setup do |worker|
  Searchkick.index_suffix = worker
  Variant.reindex
  Searchkick.disable_callbacks
end
```

```ruby
# app/models/variant.rb
class Variant
  searchkick(...)
end
```

```ruby
class VariantsControllerTest < ActiveSupport::TestCase
  open_api do
    get :index do
      parameter name: :kind,
                enum: Variant.kinds # this triggers a Zeitwerk load of app/models/variant.rb, which triggers searchkick setup
  
  end

  test "whatever" do
    Variant.reindex # raises an error on index name collision
  end
end
```

**Comment by yrashk** [comment]
I am experiencing a very similar problem and, as a result, having flaky tests, I assume due to index namespace interference. I would also like to find a good solution to this.

**Comment by nickcampbell18** [comment]
Thanks @yrashk for sharing, very helpful! That's my fallback plan - to fix this problem here without forking the searchkick gem, I've modified our other library to lazily load the code just before the test runs, it looks something like this:

```patch
class_methods do
  def open_api(&block)
-  instance_eval(&block)
+  (@callbacks ||= []) << block
  end
end

+def before_setup
+  while block = self.class.instance_variable_get(:@callbacks)&.shift
+    instance_eval(&block)
+  end
+  super
+end
```

**Comment by ankane** [comment]
Hey @nickcampbell18 and @yrashk, check out [this comment](https://github.com/ankane/searchkick/issues/1437#issuecomment-705235664) for one solution. I've also pushed a change in the `lazy_index_name` branch to only cache the index name the first time it's used rather than when the model is loaded, which should fix it.
