### ISSUE TITLE
Support for Dynamic options for Partial Search

### ISSUE THREAD

**Issue by neeko99** [ankane/searchkick#1513]
In order to safely perform a reindex with no downtime i've come across a use case where dynamic options for partial search would be useful.

Essentially i want to be able to introduce new partial search functionality without breaking the existing functionality whilst reindexing. IE i can reindex one tenant at a time having differing index metadata per tenant.   

I can do part of this with the index_name by using a dynamic name,  meaning i can keep both the old index with the old search options live until the new index with new search options have finished reindexing by using a version against the name

But due to the fact that the partial search keys are constant variables i'm unable to change them on the fly, for example id like o be able to do something like:

`searchkick 
            index_name: -> { index_version.index_name },
            word_start: -> { Thread.current[:tenant_id] == 1? [] : [:name,  :subject] }
            word_middle: -> { Thread.current[:tenant_id]  == 1 ? [:name, :subject] : [] }`

Much in the same vain that lambda's can be used to generate an index name dynamically i wonder if adding support for lambda's in the partial search attributes could be done.

Of course i'm no expert so forgive me if i'm misunderstanding but i suspect a change in here to check to see if the options value responds to `call` would be what's required here. 

https://github.com/ankane/searchkick/blob/0ab2b356ed20c8a00b1dde6dd50e62d1ad620b90/lib/searchkick/index_options.rb#L382

**Comment by ankane** [comment]
Hey @neeko99, thanks for the suggestion. It's an interesting idea, but not something I'd like to support right now. If you decide to fork for your application, I think you'll need to update there as well as `searchkick_options` in `query.rb`.
