### ISSUE TITLE
How we index activestorage images in elasticsearch. I am facing error " searchkick:reindex SystemStackError: stack level too deep"

### ISSUE THREAD

**Issue by SufyanIqbal1622** [ankane/searchkick#1516]
class Product < ApplicationRecord 
  has_many_attached :images 
  searchkick
 end

rake searchkick:reindex CLASS=Product  ✔ Reindexing Product...

rake aborted! SystemStackError: stack level too deep

home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/dynamic_matchers.rb:33:in block in match' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/dynamic_matchers.rb:33:in each' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/dynamic_matchers.rb:33:in find' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/dynamic_matchers.rb:33:in match' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/dynamic_matchers.rb:10:in respond_to_missing?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/relation/delegation.rb:129:in respond_to?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activerecord-6.1.4.1/lib/active_record/relation/delegation.rb:129:in respond_to_missing?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/module/delegation.rb:305:in respond_to?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/module/delegation.rb:305:in respond_to_missing?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:55:in respond_to?' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:55:in as_json' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:175:in block in as_json' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:174:in each' /home/sufyan/.rvm/gems/ruby-3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:174:in as_json'

**Comment by ankane** [comment]
Hey @SufyanIqbal1622, please use the bug report template to reproduce.
