### ISSUE TITLE
Histogram Aggregation with Sort (ORDER) does not seem to work

### ISSUE THREAD

**Issue by andythejswiz** [ankane/searchkick#1517]
**Describe the bug**
Thanks in advance. I am using a date histogram and I am trying to pass in a order_by (i.e. sort) option but it keeps erroring out. The docs mention that ES raw syntax should work

**Expected:**
I would expect this to work:

```
aggs: {  date_histogram: { 
                                    field: :created_at,
                                    calendar_interval: :day,
                                    order: {
                                        total_agg: :desc
                                  } } }
```

**To reproduce**
Try something like this: 

```
Dog.search("white", aggs: {  date_histogram: { field: :created_at, calendar_interval: :day, order: { total_agg: :desc } } })
```

**Additional context**
Thanks again! Go open source community.

**Comment by ankane** [comment]
Hey @andythejswiz, please use the bug report template to reproduce.

**Comment by andythejswiz** [comment]
@ankane - thanks, you are a mench!

Closing for now as I got the following to work for the time being!

For future reference:

```
results = Dog.search("goldendooldle",aggs: { posted_at: {date_histogram: {field: :born_at,calendar_interval: :day,order: {_key: :desc}} }})
```
