### ISSUE TITLE
Unable to connect AWS opensearch/elasticsearch with faraday_middleware-aws-signers-v4 gem (LoadError: cannot load such file -- aws-sdk-core/signers/v4)

### ISSUE THREAD

**Issue by ajayakodi-wm** [ankane/searchkick#1523]
I am trying to use [AWS opensearch](https://us-west-1.console.aws.amazon.com/esv3/home?region=us-west-1#opensearch) using this gem. As per the README document, I added the gem `faraday_middleware-aws-sigv4`. When I try to do `Model.reindex` in rails console then I am getting this error `LoadError: cannot load such file -- aws-sdk-core/signers/v4`

_Note: Looks like the `faraday_middleware-aws-sigv4` gem is not up to date._

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem 'faraday_middleware-aws-sigv4'
end

# Need to add this in the initilizer 
ENV["ELASTICSEARCH_URL"] = "https://es-domain-1234.us-east-1.es.amazonaws.com:443"

Searchkick.aws_credentials = {
  access_key_id: ENV["AWS_ACCESS_KEY_ID"],
  secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region: "us-east-1"
}

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Elasticsearch version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name]).response
```

**Comment by ajayakodi-wm** [comment]
@ankane, Thanks for having a quick look at this issue.

1. There is not much trace, refer the attached screenshot.
<img width="1323" alt="Screenshot 2021-10-19 at 1 22 09 PM" src="https://user-images.githubusercontent.com/88133234/137867511-9fab99da-dc2e-4d1f-bfee-1a24da7ead93.png">

2. It is a require/loading issue with this line. (guess so)

 **File Path:** 
   `/Users/arunkumar/.rvm/gems/ruby-2.7.1/gems/searchkick-3.1.3/lib/searchkick.rb`

 **Code:**
 ```
def self.aws_credentials=(creds)
    begin
      require "faraday_middleware/aws_signers_v4"
    rescue LoadError
      require "faraday_middleware/aws_sigv4"
    end

    @aws_credentials = creds
    @client = nil # reset clien
  end
```
 
 
3. The dependent gem `faraday` used in` faraday_middleware-aws-sigv4` is very old. Most of the rails core gems are using the latest faraday version like `~> 1.8.x`

4. Can't we use this `aws-sdk-signer` [gem](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/Sigv4/Signer.html) ?

**Comment by ankane** [comment]
The code to reproduce script above should use the latest versions of gems, so its stack trace would be useful as well if you're seeing it there.
