### ISSUE TITLE
Support for beginless ranges in where queries

### ISSUE THREAD

**Issue by willcosgrove** [ankane/searchkick#1524]
I was trying to perform a query where a specific field was less than a given value. I knew that endless ranges have been supported in searchkick for a while, so I tried to use a beginless range:

```rb
Model.search(where: { field: (..10) })
```

But this raises an error in the Query class because it tries to call `first` on the beginless range which causes a RangeError.

I patched this feature in to my own fork and I would be happy to open a PR for it if you're interested in supporting this use case. 

I wrote a few different versions, I don't know which one most matches the style and tradeoffs you prefer for this project:

```rb
# A
def expand_range(range)
  expanded = {}
  expanded[:gte] = range.begin if range.begin
  if range.end && !(range.end.respond_to?(:infinite?) && range.end.infinite?)
    expanded[range.exclude_end? ? :lt : :lte] = range.end
  end
  expanded
end

# B
def expand_range(range)
  {
    gte: range.begin,
    (range.exclude_end? ? :lt : :lte) =>
      (range.end unless range.end.respond_to?(:infinite?) && range.end.infinite?),
  }.compact
end

# C
def expand_range(range)
  {
    gte: range.begin,
    (range.exclude_end? ? :lt : :lte) =>
      (range.end unless range.end.respond_to?(:infinite?) && range.end.infinite?),
  }.tap(&:compact!)
end
```

I haven't run benchmarks, but I believe A would be the fastest, but isn't the nicest looking to read to my eye. B is probably my personal preference, but it has an extra Hash allocation to run the `compact`. And C is an optimization of B with the sacrifice of some clarity by the added complexity of the `tap`.

If you're open to this suggestion, I can open a PR and add some tests for this.

**Comment by ankane** [comment]
Hey @willcosgrove, makes sense to me. I think A is the most straight-forward. Here's the test for endless ranges, fwiw:

https://github.com/ankane/searchkick/blob/75250b23c81f152a626bfeaf28c648e8616d8933/test/where_test.rb#L45-L48
