### ISSUE TITLE
Please document how to configure Searchkick to use an API key with the Elastic Enterprise Search

### ISSUE THREAD

**Issue by walterdavis** [ankane/searchkick#1531]
**Is your feature request related to a problem? Please describe.**
Documentation for using a hosted Elastic server includes Basic Auth user:password, but my Elastic Enterprise account only allows API key authentication.

**Describe the solution you'd like**
Please document how to use API Key authentication with Searchkick. If this requires an additional gem or initializer, as in Amazon's hosted search service, please identify which gem(s) and initializers are required.

**Additional context**
This use of Searchkick does not seem to be very popular, and has proven to be very google-proof.

**Comment by ankane** [comment]
Hey @walterdavis, Searchkick doesn't support Elastic Enterprise Search, only Elasticsearch and OpenSearch.

**Comment by walterdavis** [comment]
Does that mean that none of the cloud ElasticSearch products are compatible? How does one configure searchkick to authenticate to an Elasticsearch server that requires a token rather than Basic Auth?

**Comment by ankane** [comment]
Elasticsearch on Elastic Cloud is supported, but I haven't seen it require token auth. If you're able to connect with an `Elasticsearch::Client` from the `elasticsearch` gem, you can create an initializer with:

```ruby
Searchkick.client = Elasticsearch::Client.new(...)
```
