### ISSUE TITLE
elasticsearch 7.16 compatibility (log4j vulnerability)

### ISSUE THREAD

**Issue by fx-diff** [ankane/searchkick#1533]
Hello @ankane 

As per gemspec, the gem is currently compatible with Elasticsearch "< 7.14".

log4j vulnerability is mitigated and fixed in Elasticsearch 7.16.1 and 7.16.2 (https://www.elastic.co/fr/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2).

Could we please get an upgraded version compatible with at least 7.16.1 ?

Thank you.

**Comment by ankane** [comment]
Hey @fx-diff, Searchkick is already compatible with Elasticsearch 7.16. Please use the bug report template if you're seeing any errors.
