### ISSUE TITLE
Default parallel search indexes, with index_suffix, can't be set in Rails 7 with eager_loading=true

### ISSUE THREAD

**Issue by jduff** [ankane/searchkick#1534]
With Rails 7 the default `config/environments/test.rb` has `config.eager_load = ENV["CI"].present?` which would be `true` in a CI environment. Tests are also parallelized by default so you probably are setting the `index_suffix` so the tests don't clobber each other using something like:

``` ruby
  parallelize_setup do |worker|
    Searchkick.index_suffix = "_#{worker}"
  end
```

With this set up Rails is loading the model classes before `parallelize_setup` is called so `index_suffix` (https://github.com/ankane/searchkick/blob/master/lib/searchkick/model.rb#L25) isn't set when the index is defined which causes the parallel tests to clobber each other.

I think a fix for this could be to set `index_suffix` to a proc [here](https://github.com/ankane/searchkick/blob/master/lib/searchkick/model.rb#L31) but I wanted to make sure that would be the correct approach before submitting a patch.

**Comment by ankane** [comment]
Hey @jduff, there's a plan to address this as part of Searchkick 5 (#1288), but check out https://github.com/ankane/searchkick/issues/1512#issuecomment-924467924 for two possible solutions in the meantime.
