### ISSUE TITLE
NGrams for non-english languages (like Japanese)

### ISSUE THREAD

**Issue by nbw** [ankane/searchkick#1535]
Hi there,

I work on a Japanese app and we use kuromoji for indexing/tokenization/etc., but we've noticed certain searches not yielding the results we were expecting. Presumably because of how things are tokenized. 

We have a different app that uses the Elasticsearch gem directly (I _much_ prefer Searchkick, which is why we use it) where we use an ngram analyzer to fill in those gaps and get the result we're looking for. Example setting: 

```ruby
        tokenizer: {
          ngram_tokenizer: {
            type: 'ngram',
            min_gram: 1,
            max_gram: 2,
            token_chars: %w[letter digit symbol]
          }
        },
...
```

Searchkick sets "kuromoji" in [IndexOptions](https://github.com/ankane/searchkick/blob/a9b57db1ff4dedcac82cc7cf0ebf7d0891d99a6e/lib/searchkick/index_options.rb#L226) which overrides the default_analyzer filters. I tried adding a `"searchkick_ngram"` filter with kuromoji (by forking and editing the library itself), but it still didn't work.  

---

To explain by example:

Company A named "レストラン" (resutoran)
Company B named "レストランテスト" (resutorantesuto)

Searching レストラン would yield only Company A, but we were expecting Company B, too. 
Searching レストランテスト would yield Company B.

---

If I'm misunderstanding how ES works or if there's a good solution to this then please let me know. 

I should also say that one _sort of hack_ to this which has helped with results is using `misspellings: {edit_distance: 2}` to soften the results so that `レストランテス` will still match `レストランテスト`

**Comment by ankane** [comment]
Hey @nbw, Searchkick appears to match the expected behavior with `language: "japanese"`.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Elasticsearch version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick language: "japanese"
end

Product.reindex
Product.create!(name: "レストラン")
Product.create!(name: "レストランテスト")
Product.search_index.refresh

p Product.search("レストラン").map(&:name)
# ["レストラン", "レストランテスト"]
p Product.search("レストランテスト").map(&:name)
# ["レストランテスト"]
```

**Comment by ankane** [comment]
It should also work with partial matches/ngrams.

```ruby
class Product < ActiveRecord::Base
  searchkick language: "japanese", word_start: [:name]
end

Product.reindex
Product.create!(name: "レストラン")
Product.create!(name: "レストランテスト")
Product.search_index.refresh

p Product.search("レストラン", match: :word_start).map(&:name)
# ["レストラン", "レストランテスト"]
p Product.search("レストランテスト", match: :word_start).map(&:name)
# ["レストランテスト"]
```

**Comment by nbw** [comment]
Hey @ankane ! I gave fake data as an example, but I should really of shared the exact example we had issues with. It was 

リンカーズ　vs　リンカーズエンジン

リンカーズ would not return results that had リンカーズエンジン

adding misspelling distance of 2 meant we could get some overlap when searching リンカーズエンジン

| search | matching |
| ------ | ----------|
| リンカーズ  | リンカーズ |
| リンカーズエ  | no match |
| リンカーズエン  | no match or [リンカーズ and リンカーズエンジン with a misspelling distance of 2]  |
| リンカーズエンジ  | リンカーズエンジン |
| リンカーズエンジン | リンカーズエンジン |
 
We haven't used `match: :word_start` so that's something we could consider. is there an easy way to set word_start for all fields and what happens when we want word_start for certain fields and a different scheme for others. Apologies, this is starting a whole different discussion. Let me know if I should move this to another thread.

**Comment by ankane** [comment]
Great, glad that'll work. fwiw, you can use different matching for different fields if needed:

```ruby
class Product < ActiveRecord::Base
  searchkick word_start: [:field1], word_end: [:field2]
end

p Product.search(term, fields: [{field1: :word_start}, {field2: :word_end}])
```
