### ISSUE TITLE
BigDecimals are indexed as floats

### ISSUE THREAD

**Issue by nickcampbell18** [ankane/searchkick#1538]
**Describe the bug**

I would like to discuss the behaviour where BigDecimal fields are indexed as floats (this change was applied following https://github.com/ankane/searchkick/issues/57). I think this behaviour is surprising in 2022.

When this change was originally introduced, it was following a new (and also surprising!) Rails behaviour at the time to cast bigdecimals as strings in JSON: https://github.com/rails/rails/issues/6033. Rails had then introduced a configuration flag to disable this behaviour. However, this was Rails 3.x - in more recent releases of Rails that configuration appears to have disappeared, and I believe most users of Rails are now aware that BigDecimal is used in most decimal contexts, and also that BigDecimals are typically cast as strings at the system boundaries.

I encountered this surprising behaviour when debugging an issue where floating point values were being returned as aggregations from ElasticSearch even though they were correctly stored in our database, e.g. `BigDecimal("6.4")` was coming back from ES as `6.4000000095367432`. I initially assumed ES was doing something weird because when debugging `#search_data` in a console, the fields were in the formats I would expect (I now see that this is [silently converted during transmission](https://github.com/ankane/searchkick/blob/df39c269bc91bd8d1307101f238fbe06a98adfc7/lib/searchkick/record_data.rb#L103-L125) by Searchkick). Unfortunately, it is nontrivial to convert this aggregation value back to a BigDecimal because of the inherent loss in precision when working with floats.

I fully understand why the original change was made, and if you intend to work with decimal values as numeric types (e.g. range comparisons) then of course storing them as strings is not an option. In my application we treat them as opaque fields purely for filtering by exact value. However, I think the default behaviour, where all BigDecimals are cast down to floats, is also surprising when compared to most other areas of the Rails ecosystem.

So, I would like to propose some options to make this behaviour less surprising please:

  1. **Document this behaviour in the README, also giving users an escape hatch** (e.g. "cast your BigDecimals to strings manually if you don't want them converted to floats").
  2. **Allow configuring this behaviour globally** (and again, document in the README why you might want to do that). This change would add some configuration complexity, but also allows users to see that there is this hidden behaviour and they can make a conscious choice whether to retain it.
  3. **Remove this behaviour** (although I don't endorse this option because it would be a subtle breaking change, and people who depend on this behaviour would need to manually cast their decimals to floats)
  4. **Some crazy option where you index it twice, both as a string and float** is that even feasible?

@ankane if you're open to any of these, I would happily write a PR. My goal is to help a future person who couldn't immediately see where their BigDecimals became floats at some point. Thanks!

**To reproduce**

1. Have a `:decimal` column in your database
2. Index the object

**Comment by ankane** [comment]
Hey @nickcampbell18, added a note to the readme.

**Comment by nickcampbell18** [comment]
Thanks!
