### ISSUE TITLE
has_many: AND inverse_of: =  Only call searchkick once per model

### ISSUE THREAD

**Issue by jasper502** [ankane/searchkick#1539]
Related to #1480 but would appear to not be the same cause.

I added `inverse_of:` to an existing `has_many` model definition an existing relation that was working fine with SK in both referenced models.  Not throws:

```
/Users/aximus/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/searchkick-4.6.3/lib/searchkick/model.rb:13:in `searchkick': Only call searchkick once per model (RuntimeError)
irb(main):012:0> 

```

This is a Rails 7 app and searchkick (4.6.3), activemodel (>= 5), elasticsearch (>= 6, < 7.14)

I suspect that the `inverse_of` is calling the second SK.  Now I can probably live with removing SK from the `has_many` model but would like to keep that option open.

**Comment by ankane** [comment]
Hey @jasper502, it sounds like the app is loading the model twice, similar to #1480. I'd try adding debugging to see what's going on.

**Comment by jasper502** [comment]
Yes it is - though the `inverse_of` call which should not be the expected outcome.  Searchkick is called in each model once.  

My code runs fine until I add the single `inverse_of` to the `has_many`.  Removing the `inverse_of` OR the Searchkick call from the `has_many` model resolves the issue.

**Comment by ankane** [comment]
`inverse_of` shouldn't cause a model to load twice (and doesn't in a fresh Rails 7 app), so think it may be something specific to your application. Will keep an eye out for similar reports, but I don't think there's anything to change with Searchkick right now.
