### ISSUE TITLE
elasticsearch gets downgraded to pre 7.14

### ISSUE THREAD

**Issue by gsar** [ankane/searchkick#1540]
**First**

It seems an [earlier filed issue](https://github.com/ankane/searchkick/issues/1533#issuecomment-999831211) has been closed without the root cause being addressed correctly.

**Describe the bug**

The searchkick.gemspec requires elasticsearch `< 7.14` which results in my project's Gemfile.lock getting downgraded to elasticsearch 7.13.3 from 7.16.1 when I attempt to upgrade searchkick in my project.  It appears searchkick is compatible with elasticsearch 7.16.1 so shouldn't the gemspec be fixed?

**Comment by ankane** [comment]
Hey @gsar, that's intentional (it looks like you've already seen https://github.com/ankane/searchkick/issues/1509#issuecomment-903323220).

Searchkick 5 (just released) no longer pins the `elasticsearch` gem, so try upgrading if you need a more recent client.
