### ISSUE TITLE
Implementing Typhoeus::Cache breaks Searchkick

### ISSUE THREAD

**Issue by wflanagan** [ankane/searchkick#1541]
We use Typhoeus throughout our application, including for Searchkick.

In an attempt to add Caching (per the instructions on the Github repo), 100% of my Searchkick queries started failing with "index not found." 

To reproduce, add
```
require "typhoeus/cache/rails"
::Typhoeus::Config.cache = ::Typhoeus::Cache::Redis.new($redis, default_ttl: 5.minutes)
```
in an initializer after you've initialized Redis and searchkick/ES.

**Comment by ankane** [comment]
Hey @wflanagan, Searchkick doesn't directly support this, so you'll probably want to add debugging to see what's going on.
