### ISSUE TITLE
Can perform Searchkick::BulkReindexJob and Searchkick::ReindexV2Job using replica database for reads

### ISSUE THREAD

**Issue by jeffblake** [ankane/searchkick#1543]
It would be great if we could configure the indexing jobs to run on a Rails follower database, e.g.:

```
ActiveRecord::Base.connected_to(role: :reading) do
  yield
end
```

https://guides.rubyonrails.org/active_record_multiple_databases.html#using-manual-connection-switching

**Comment by jeffblake** [comment]
An idea: let us configure the job class, so we can subclass `Searchkick::BulkReindexJob`, do various things like wrapping the work in `ActiveRecord::Base.connected_to(role: :reading)` or a Sidekiq Enterprise rate limiter.

**Comment by ankane** [comment]
Hey @jeffblake, thanks for the suggestion. What do you think about making this a model-level option (for more than just jobs)?

```ruby
class Product < ApplicationRecord
  searchkick reindex_role: :reading
end
```

In the meantime, you can use `Module#prepend` to wrap the `perform` method for jobs.
