### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 0..1) after update to ruby 3

### ISSUE THREAD

**Issue by gabrieltrita** [ankane/searchkick#1544]
After upgrading to ruby 3. All my models using the method: Model.search(), stopped working. It always returns the error: ArgumentError: wrong number of arguments (given 2, expected 0..1).

Can anybody help me?
The searchkick declaration is the basic one, for example:

```rb
class Model < ApplicationRecord
   searchkick
   . . .
end
```

thanks!

**Comment by ankane** [comment]
Hey @gabrieltrita, make sure you're on the latest version.

**Comment by ankane** [comment]
If you can use the bug report template (under "New Issue") to reproduce, happy to look into it more.

**Comment by confact** [comment]
@ankane It works in a clean rails 6.1.4.6 app. Not sure what is going on. @gabrieltrita, did you figure out the problem?

**Comment by ankane** [comment]
The stack trace should show where it's occurring. Seems like it may be related to the change in keyword arguments between Ruby 2.7 and 3.0.

**Comment by confact** [comment]
@ankane I found a way to reproduce it, see #1546

**Comment by ACPK** [comment]
I'm hitting the same issue.
