### ISSUE TITLE
Multilevel facets

### ISSUE THREAD

**Issue by thiagodelgado111** [ankane/searchkick#155]
@ankane, i was trying to use multilevel facets with no success on it, i might be missing some doc but i didnt found how could i make it, here follows a sample of multilevel facet:

*index: House*
*facet desired: City name*

`def search_data
 {     
   rooms: rooms.count,      
   locale: addresses.collect{ 
     |a|
     {
       :city => a.city.name <-- HERE,
       :province => a.city.state.code, 
       :neighborhood => a. neighborhood,
       :address => a.address,
       :number => a.number,
       :zip_code => a.zipcode
    }
 }`

So it would gave something like:

*House per city:*
**Newark (2)**
**Austin (3)**

*search.rb*

To accomplish that I'd need to set *locale.city.name* as facet term. But, since you're grabbing facet name from options parameter also, I ended declaring facet name as locale.city.name using it as hash key, like:

`House.search "*", facets : {"locale.city.name" => {}}`

But I don't think that's elegant or the best way to do it, may I contribute with a better solution for that?

Since now, regards and congratz, searchkick is awesome!

**Comment by thiagodelgado111** [comment]
Well, I forgot to close this issue before, sadly I didn't managed to attack this on time, srry

**Comment by ankane** [comment]
Thanks for following up :)
