### ISSUE TITLE
Gem raises `Elasticsearch::UnsupportedProductError` with Elasticsearch 7

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#1550]
Hi Ankane, hope you are doing well. 

**Describe the bug**
I have Elasticsearch 7 installed; the docs state that 7 and 8 are supported, but as soon as I try to `Model.reindex`, I face this exception:

```
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
Elasticsearch::UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product.
from .rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/elasticsearch-8.1.0/lib/elasticsearch.rb:116:in `verify_with_version_or_header'
```

Putting a debugger there, these are the headers/version I'm getting:

```rb
headers
{"content-type"=>"application/json; charset=UTF-8", "content-length"=>"344"}
version
"7.7.1
```

Maybe support for Elasticsearch 7 was dropped and the readme wasn't updated? Because that method uses `Gem::Version.new(version) < Gem::Version.new('8.0.0.pre')`, which will be true when ES is 7. 

Also, `headers['x-elastic-product'] != 'Elasticsearch'` will also be true, because I don't have that key in the `headers` hash. 

Searchkick version: 5.0.2
puts "Server version: #{Searchkick.server_version}" => this raises 

```
curl -XGET 'http://localhost:9200/'
{
  "name" : "x",
  "cluster_name" : "elasticsearch_x",
  "cluster_uuid" : "x",
  "version" : {
    "number" : "7.7.1",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "ad56dce891c901a492bb1ee393f12dfff473a423",
    "build_date" : "2020-05-28T16:30:01.040088Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Thank you!

**Comment by ankane** [comment]
Hey @feliperaul, for the OSS version of Elasticsearch (`"build_flavor" : "oss"`), you'll need to use:

```ruby
gem "elasticsearch", "< 7.14"
```

**Comment by feliperaul** [comment]
@ankane Thank you, it works. It's been a long time since I set up searchkick in a new project, I thought `elasticsearch-oss` was still a thing, apparently it got dropped. Thanks.
