### ISSUE TITLE
Searchkick with custom classes

### ISSUE THREAD

**Issue by ricardopacheco** [ankane/searchkick#1552]
I have a use case where i need to create several different indexes for the same model (`search_data`). Is it possible for me to do something like chewy does? (it uses `index_scope`)

Chewy (example from official doc)

```
class UsersIndex < Chewy::Index
...
index_scope User.active.includes(:country, :badges, :projects)
...
end
```

Sidekiq (I want to know if it's possible)

```
class PoroUserClassActiveIndex
   sidekiq class_name: User.active.includes(:country, :badges, :projects), index_name: active_users
   
   def search_data
    { id: user.id, name: user.name }
   end

   ...
end
```

```
class PoroUserClassInactiveIndex
   sidekiq class_name: User.inactive.includes(:country, :badges, :projects), index_name: inactive_users

  def search_data
    { id: user.id, name: user.name, sensitive_info: user.sensitive_info }
  end

  ...
end
```

The idea would be to decouple the index structure from the models. In some cases, i want to create indexes with sensitive information, and another index with more public information. I understand that I can respect the coupling of sidekiq to activerecord (which makes it powerful), however, I can make it flexible at the project level (when I want to have more than one index per model for example).

Or, am I thinking wrongly?

**Comment by ankane** [comment]
Hey @ricardopacheco, thanks for the suggestion. I considered this for Searchkick in the earlier days, but decided to stick with the current approach for simplicity, which I think still makes sense for the project (even though it doesn't support multiple indexes per model).

**Comment by ricardopacheco** [comment]
@ankane Wouldn't it be the case that I could just pass the ActiveRecord class as an argument in searchkick and everything AR needs to read from this guy? I thought it would be simple, but if it gets complicated in this case, it seems to me that chewy serves this case better than sidekiq when it comes to multiple indices, correct?
