### ISSUE TITLE
Add documentation on how to add conversions on a production index

### ISSUE THREAD

**Issue by zyqxd** [ankane/searchkick#1555]
I feel like the documentation around conversions is a little misleading. 

We have a running production index, adding the `conversions: [:conversions]` option to searchkick errors out so we have to update in steps:

1. Add the field in `#search_data`
2. Add the `conversions` option

From the docs:

```
class Product < ApplicationRecord
  has_many :searches, class_name: "Searchjoy::Search", as: :convertable

  searchkick conversions: [:conversions] # name of field

  def search_data
    {
      name: name,
      conversions: searches.group(:query).distinct.count(:user_id)
      # {"ice cream" => 234, "chocolate" => 67, "cream" => 2}
    }
  end
end
```

> Okay, so we need a hash of strings => integers

I pushed this up, reindex, and then push up the `conversions` option change. Production index crashes

```
[nested] nested object under path [conversions] is not of nested type
```

Turns out, I guess under the hood searchkick converts `{"ice cream" => 234, "chocolate" => 67, "cream" => 2}` into => 
```
[{ "query" => "...", "count" => ... }...]
```

ES will dynamically map all nested fields in an object. This should be kept at a minimum to avoid using excess memory. This seems like a smart solution to avoid too many mapped fields, and perhaps this is a commonly understood pattern of conversion (objects => array). I was not aware of this.

Multiple roll backs, resyncs, and dealing with too many mappings on production, I think I finally fixed it. 

**Describe the solution you'd like**
Update README.md with this; Perhaps add a section guide on how to update your production index;

1. Add `conversions` key in your search data, value `[]`
2. Add `conversions` option to searchkick, then set value to `{key => count}`

**Comment by ankane** [comment]
Hey @zyqxd, added a note about deployment. The trick is to add:

```ruby
Model.search(term, conversions: false) # [] would also work
```

to your search calls until the data is reindexed.

**Comment by zyqxd** [comment]
`conversions: false` does not work:
```
NoMethodError: undefined method `to_sym' for false:FalseClass
```

**Comment by ankane** [comment]
I'm not sure how to reproduce that error, but feel free to use the bug report template to reproduce.
