### ISSUE TITLE
Support Searchkick on model without a table?

### ISSUE THREAD

**Issue by reczy** [ankane/searchkick#1559]
Hey @ankane - thanks so much for your contributions to the ruby/rails ecosystem! I've been using this gem in particular for years now.

I'm looking to migrate 2 tables that I currently have in postgres (one of which uses searchkick) over to dynamodb. I'd like to continue using searchkick without actually pointing it to a real ActiveRecord/postgres table. I'd handle all indexing, updating, and deleting through manual calls to `bulk_index`, `bulk_update`, and `bulk_delete` in custom background jobs.

So... the distilled question (or feature request if not currently possible/recommended) is: can I use Searchkick on a model where I set `self.abstract_class = true` or where I setup a fake/empty table and handle the data population logic on my own? 

On initial inspection, the latter seems to work as expected:

```sql
# in postgres - empty table with just id
DROP TABLE IF EXISTS fakes;
CREATE TABLE fakes (
	id uuid PRIMARY KEY
);
```

```rb
# models/fake.rb

class Fake < ApplicationRecord

  attribute :id, default: -> { SecureRandom.uuid }
  attribute :text, default: -> { SecureRandom.alphanumeric(64) }
  attribute :test

  searchkick callbacks: false

  def search_document_id
    id
  end

  def search_data
    {
      text: text,
    }.merge(search_test)
  end

  def search_test
    {
      test: self.test || SecureRandom.hex(2)
    }
  end
end
```

```rb
>> Fake.reindex
D, [2022-05-10T20:42:51.503684 #45413] DEBUG -- :   Fake Load (0.4ms)  SELECT "fakes".* FROM "fakes" ORDER BY "fakes"."id" ASC LIMIT $1  [["LIMIT", 1000]]
=> true
>> f = Fake.new
=> #<Fake:0x000000010cd955c8 id: "66b83f39-eb1d-433a-ad64-7fd97bcf4f1d", text: "cnO5ApU4ztyXdUeJYueoRnetkF7UR0IkOc2yhtNoHP5bX43Apif3ZCrNZq1LI1ce", test: nil>
>> Fake.searchkick_index.bulk_index([f])
D, [2022-05-10T20:43:03.592215 #45413] DEBUG -- :   Fake Import (64.2ms)  {"count":1}
=> nil
>> Fake.search "*", load: false
D, [2022-05-10T20:43:15.678023 #45413] DEBUG -- :   Fake Search (8.7ms)  fakes_development/_search {"query":{"match_all":{}},"timeout":"11s","size":10000}
=> #<Searchkick::Relation [#<Searchkick::HashWrapper _id="66b83f39-eb1d-433a-ad64-7fd97bcf4f1d" _index="fakes_development_20220510204251296" _score=1.0 _type="_doc" id="66b83f39-eb1d-433a-ad64-7fd97bcf4f1d" test="14ca" text="cnO5ApU4ztyXdUeJYueoRnetkF7UR0IkOc2yhtNoHP5bX43Apif3ZCrNZq1LI1ce">]>
>> f2 = Fake.new(id: "66b83f39-eb1d-433a-ad64-7fd97bcf4f1d")
=> #<Fake:0x000000010cf2cd00 id: "66b83f39-eb1d-433a-ad64-7fd97bcf4f1d", text: "3OBszsR8NCkh47A4Iplq8eyCzRFPQN9B0w5wQDC7eQq8wnB8Ba6pW5DK7RAuviUP", test: nil>
>> Fake.searchkick_index.bulk_update([f2], :search_test)
D, [2022-05-10T20:43:43.814525 #45413] DEBUG -- :   Fake Update (30.8ms)  {"count":1}
=> nil
>> Fake.search "*", load: false
D, [2022-05-10T20:43:46.953504 #45413] DEBUG -- :   Fake Search (15.6ms)  fakes_development/_search {"query":{"match_all":{}},"timeout":"11s","size":10000}
=> #<Searchkick::Relation [#<Searchkick::HashWrapper _id="66b83f39-eb1d-433a-ad64-7fd97bcf4f1d" _index="fakes_development_20220510204251296" _score=1.0 _type="_doc" id="66b83f39-eb1d-433a-ad64-7fd97bcf4f1d" test="b7ce" text="cnO5ApU4ztyXdUeJYueoRnetkF7UR0IkOc2yhtNoHP5bX43Apif3ZCrNZq1LI1ce">]>
```

I'm ok with creating synthetic ActiveRecord records/relations if that's what it takes to "trick" searchkick into thinking it's working with a real table - there's a lot of preprocessing that goes into creating/updating these records anyway.

Any gotchas with this approach? Would you be open to supporting table-less models?

**Comment by ankane** [comment]
Hey @reczy, thanks for the suggestion. I don't think table-less models are common enough to support, but the id-only table approach should work (since `search_data` can be populated from anywhere).

Another direction that might work is creating an Active Record adapter for DynamoDB (since [it supports some SQL](https://aws.amazon.com/about-aws/whats-new/2020/11/you-now-can-use-a-sql-compatible-query-language-to-query-insert-update-and-delete-table-data-in-amazon-dynamodb/)), but I'm not sure how involved it is.

**Comment by reczy** [comment]
Thank you for the response and suggestion. I'll give the adapter a look but I'm guessing I'll likely stick with the empty-table approach if that ends up working. 

I'll report back for others if something ends up working particularly well.

Thanks again!
