### ISSUE TITLE
Unexpected increasing document count

### ISSUE THREAD

**Issue by siannopollo** [ankane/searchkick#1566]
[Related StackOverflow question](https://stackoverflow.com/questions/72453058/aws-opensearch-searchkick-resulting-in-increasing-document-count)

I've looked through past issues and couldn't see anything similar to my situation. I have a Property class in our rails app, each property representing a physical address in the US. We have about 103 million total properties in our database. Our searchkick definition looks like this:

```
class Property
  searchkick word_start: [:full_address], batch_size: 15000,
             locations: [:location], search_synonyms: search_synonyms
  
  def search_data
    {
      full_address: full_address_with_full_state.to_s.downcase,
      state: state.to_s.downcase,
      location: {lat: latitude, lon: longitude}
    }
  end
end
```

We have an import that runs monthly to add new properties and update existing properties, but the import is mostly updates. Unfortunately, each time the import runs it is increasing the total document count by the number of updated properties. The following screenshot shows the increase during each import, even though our total property count doesn't really increase past 103 million.

![mbKeO](https://user-images.githubusercontent.com/5378/172228793-a8c76a51-a9b2-436a-bb10-ef93aebb73f2.png)

During the import we insert any new properties in a single database transaction (so no `after_save` callbacks are invoked), and any updates are individually processed via `property.save`. Here is what that code looks like, along with the relevant searchkick functionality:

```
Searchkick.callbacks(:bulk) do
  new_properties.each(&:reindex)
  
  property_class.transaction requires_new: Rails.env.test? do
    existing_properties.each(&:save)
  end
end
```

Is there anything else I should be doing to prevent this increasing document count? Is there some method I need to call on the index when the import finishes to cleanup any duplicate indexes? I would assume that the updated properties would overwrite existing indices for each property, but that doesn't seem to be the case.

Any help is greatly appreciated.

**Comment by ankane** [comment]
Hey @siannopollo, I'm not sure how Amazon OpenSearch Service is calculating SearchableDocuments, but if you're not seeing duplicates in search, my guess is it may be counting Lucene documents.

**Comment by buffpojken** [comment]
@siannopollo - I'm seeing the exact same issue, where the amount overshoots a known, fixed count of items when using AWS OpenSearch - did you ever manage to find a solution or answer to why that is?
