### ISSUE TITLE
Configure Size of Aggregation Buckets

### ISSUE THREAD

**Issue by sloanmamba** [ankane/searchkick#1568]
**Describe the bug**
Can we set the number of aggregation buckets? I don't see any docs on how to override the default number of aggregation buckets per aggregation type beyond the default of 1,000 items per bucket.

**To reproduce**
Use this code to reproduce when possible:

```
results = Model.search("*", aggs: { first_name: {}, last_name: {} }, body_options: { track_total_hits: true })
aggregations = results.aggs
first_name_aggregation = aggregations['first_name']
size_of_first_name_aggregation_items_in_bucket = first_name_aggregation['buckets'].size
```

`1,000`

Can we override this?

**Additional context**
If not, my model has a lot of logic already, can we add custom ES mapping with search kick mapping logic?

**Comment by ankane** [comment]
Hey @sloanmamba, you can use the `limit` option to increase the size (`aggs: {first_name: {limit: 2000}}`) up to the Elasticsearch [search.max_buckets](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html#search-settings-max-buckets) setting, which is 65,536 by default.
