### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::InternalServerError | java.util.ArrayList cannot be cast to class java.util.Map 

### ISSUE THREAD

**Issue by lentrup** [ankane/searchkick#1569]
**Describe the bug**
Maybe the ORM version used is not sync with the ElasticSearch version?
Thank you for taking a look at this.

**To reproduce**
Use this code to reproduce when possible:

Elasticsearch Engine Version 6.8.23

```ruby
Model.reindex
```

```ruby
# Gemfile
gem 'searchkick'
gem 'elasticsearch'
```
Error:

    Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"class_cast_exception","reason":"class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')"}],"type":"class_cast_exception","reason":"class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')"},"status":500}
    from /app/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'

**Comment by lentrup** [comment]
I fixed this myself . Seems that I needed to downgrade to:
`gem 'searchkick', '~> 4.6', '>= 4.6.3'`

**Comment by ankane** [comment]
Glad you figured it out, and thanks for following up. Pushed a better error message in the last commit (sorry for the noise).
