### ISSUE TITLE
Lack of Kaminari's `per` method support

### ISSUE THREAD

**Issue by mdesantis** [ankane/searchkick#1572]
**Describe the bug**
Kaminari uses `#per` method to set `per_page` value, but Searchkick has a `#per_page` method, not a `#per` one. This breaks Kaminari's integration, especially for third party gems which expect that a`#per` method exists when Kaminari's pagination is used and `#page` is called, e.g.: https://github.com/davidcelis/api-pagination/blob/d173212143f65915c5d1505b2aaa96cc7e93da34/lib/api-pagination.rb#L98

**To reproduce**

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  # uncomment one
  gem "elasticsearch"
  # gem "opensearch-ruby"
  gem "kaminari"
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick
end

Product.reindex
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name]).page(params[:page]).per(params[:per_page]).response
```

**Additional context**

I think that Kaminari should be supported the way Kaminari supports ActiveRecord models: https://github.com/kaminari/kaminari/tree/v1.2.2/kaminari-activerecord I'm open to work on a PR, if willing to be accepted.

**Comment by ankane** [comment]
Hey @mdesantis, the chaining API is experimental, but feel free to submit a PR.
