### ISSUE TITLE
Mutiple search types in same query

### ISSUE THREAD

**Issue by fabn** [ankane/searchkick#1574]
First of all thanks for your excellent gem, it's the best implementation for ES I ever seen.

However I have a simple use case that I think is not supported by current Searchkick API, imagine a simple `Product` model with `id`, `name`, and `sku` as attributes and that it is indexed in this way

```ruby
class Product < ApplicationRecord
  searchkick word_start: [:name], word_middle: [:sku]
end
```

If we want to do a simple query that at same time matches for names and sku I think is unsupported in Searchkick

Imagine a product with `{name: 'Apple Iphone', sku: 'XY'}` and another with `{name: 'Android Galaxy', sku: '123app456'}` and the user searches for `app`, we'd like to match both results. I'm experimenting with [MultiSearch](https://github.com/ankane/searchkick#multi-search) to get this behaviour but I think that a native api in searchkick for this would be a great addition, something similar to:

```ruby
Product.search('app', match: {sku: :word_middle, name: :word_start})
```

Also because results from multisearch are possibly not sorted and you might not be able to get a good relevance sorting.

What do you think?

**Comment by ankane** [comment]
Hey @fabn, you can do:

```ruby
Product.search("app", fields: [{sku: :word_middle, name: :word_start}])
```

**Comment by fabn** [comment]
Awesome thank you very much. Maybe it's worth to add to the doc.

**Comment by ankane** [comment]
Sorry, messed up the syntax. It's:

```ruby
Product.search("app", fields: [{sku: :word_middle}, {name: :word_start}])
```
