### ISSUE TITLE
Support multiple databases

### ISSUE THREAD

**Issue by emersonthis** [ankane/searchkick#1576]
On my local development environment I keep two databases. One has seed data and one is a dump of production data. I switch between them depending on what I'm working on. This system works well, but I have to reindex everything every time I switch, and some of my tables are getting big and take a long time (so it's tedious).

**Describe the solution you'd like**
It would be great if I could configure searchkick to index the two separately so they could live in parallel.

**Comment by ankane** [comment]
Hey @emersonthis, you can set an index prefix to do this:

```ruby
Searchkick.index_prefix = "seed" if some_condition
```

**Comment by emersonthis** [comment]
Very cool! Thanks!!

**Comment by emersonthis** [comment]
@ankane Where would be the best place for that line to live? Should it run once in an initializer?

**Comment by ankane** [comment]
Yes, exactly (assuming you restart the app to switch databases).

**Comment by emersonthis** [comment]
This is very cool! For anyone else that finds this, here's what I ended up doing:

```
# initializer
if ENV.include?('DB_NAME')
    Searchkick.index_prefix = ENV['DB_NAME'] 
    puts "Search index prefix = #{ENV['DB_NAME']}"
end
```

```
# database.yml

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { "default_database_name" } %>
```

Whenever I want to switch to a new database, I just `export DB_NAME=other_database_name` and restart the Rails server. I've only been playing with it for a day, but it seems to work great and already saving me a lot of reindexing hassles.

Thanks for your help figuring this out.
