### ISSUE TITLE
search_index.refresh not working as expected

### ISSUE THREAD

**Issue by emersonthis** [ankane/searchkick#1577]
**Describe the bug**
`search_index.refresh` does not appear to be working as expected. In a controller, we loop over a list and create records before calling ModelName.search_index.refresh. But those new records are not included in the following search results

**To reproduce**

```ruby
class MyModel < ApplicationRecord

  searchkick

  def search_data
    {
      ...
    }
  end
```

```ruby
class MyModelController < App::ApiController

  def import
    my_params[:list].each do |my_model|
      new_m = MyModel.new(my_model)
      new_m.save
    end
    MyModel.search_index.refresh
    render json: { successes: true}, status: :ok
  end
```
Soon after this API call, this controller action is called:

```
def search
  Searchkick.search(
      q,
      models: [MyModel, AnotherModel],
      where: where,
      order: order,
      page: page
    )
```
The new records just created in `#import` are not included in these results.

**Additional context**
This problem does not seem to happen in my local development environment where opensearch is running locally. It happens in the remote Heroku environment where the elastic search instance is accessed remotely via an add-on. 

This StackOverflow question seems to describe the same unexpected behavior: https://stackoverflow.com/questions/72001855/searchkick-how-does-search-index-refresh-work-with-async-callbacks

**Comment by ankane** [comment]
Hey @emersonthis, I'm not sure how to reproduce, but if it's working locally, it seems like something specific to your production environment.

**Comment by emersonthis** [comment]
I think it's the fact that the production elasticsearch instance is being
accessed remotely whereas my local setup is running in the same box. In
other words, I suspect it isn't working in either place but one is fast
enough that it isn't noticeable. Does that make sense?

Can you confirm if search_index.refresh should happen synchronously? Is
this the expected behavior:

```
# something that requires indexing
Whatever.search_index.refresh
puts 'Now index is definitely updated'
```

Or is something else I should be checking to confirm the operation
completed?

**Comment by ankane** [comment]
Yes, refresh happens synchronously. I believe it'll throw an error if the refresh fails, but you can also try checking the return value.

**Comment by pbassut** [comment]
I'm having the same issue. Are we sure this is working as expected?

**Comment by emersonthis** [comment]
We're still struggling with this. At the moment we're dealing with a situation where we insert a large number of records (ex: 4000) then we immediately call `.search_index.refresh`. This is the exact code:
```
    recipient_data = Recipient.insert_all_normalized(recipients, returning: [:id])

    if recipient_data.is_a?(ActiveRecord::Result)
      current_account.recipients.search_index.refresh
```
Immediately afterwards, the next search will not include the new records in the `total_count` and subsequent searches will show the `total_count` increase gradually over the next couple minutes. To me, this looks like `.search_index.refresh` is not happening synchronously.

**Comment by emersonthis** [comment]
Fwiw we are using `body_options: {track_total_hits: true}`

**Comment by emersonthis** [comment]
It turns out that our problem was not the result of `search_index.refresh` running slowly / async. Rather, it wasn't running at all because we were inserting the records using `insert_all`, which doesn't trigger callbacks, and apparently those are needed to initiate indexing for new records.

Calling `.save` on the new records will solve this problem, but it's very slow/expensive if there are many records. We experimented briefly with manually triggering callbacks (ex: `new_record.run_callbacks(:save)` ) but this did not work. At the moment, our best workaround is to call `bulk_index` like this:

      SomeModel.search_index.bulk_index(new_records)
      new_records.search_index.refresh # this is necessary also

 Hopefully this update saves someone else some time. Maybe @ankane has an even better suggestion about to index efficiently after `insert_all`.
