### ISSUE TITLE
Warning 299 when run any test on Rails 7 app

### ISSUE THREAD

**Issue by jeanschdev** [ankane/searchkick#1581]
Hi I am getting the following warning when I run any test

`warning: 299 Elasticsearch-7.17.4-79878662c54c886ae89206c685d9f1051a9d6411 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."`

I added `xpack.security.enabled: true` to my elasticsearch.yml file but don't solve the warning

I have installed elasticsearch-full pack with homebew in a MacBook m1

Rails 7
gem "searchkick"
gem "elasticsearch", "< 7.14"

**Comment by ankane** [comment]
Hey @jeanschdev, setting `xpack.security.enabled: false` will disable the warning.

**Comment by jeanschdev** [comment]
@ankane I did but still have the warning
