### ISSUE TITLE
`after_reindex` callback

### ISSUE THREAD

**Issue by stengineering0** [ankane/searchkick#1585]
**Is your feature request related to a problem? Please describe.**
Some actions must be performed strictly after reindexing, for instance the events publishing.

Let's say that
1. 1st service updates the Article record changing the publish date. At this moment it schedules async reindexing job as well as publishes the event (through the Kafka or whatever) saying that Articles index page (contains today's Articles) is likely changed;
2. 2nd service receives the event and tries to refresh the HTML cache of Articles index page. This way the `articles#index` API call will be fired back to the 1st service where the Articles are living;
3. `articles#index` API endpoint within 1st service relies on ES searching over the Articles and involves the filtering by publish date. At this point Article record can be still not reindexed - because corresponding async reindexing job is still not evaluated. This way endpoint might respond the stale data.

**Describe the solution you'd like**

Let's introduce two `after_reindex` callbacks as follows:

```ruby
class Article
  def after_reindex_params
    saved_changes
  end

  def after_reindex(params)
    published_at_diff = params.dig('published_at')
    return unless published_at_diff

    ArticleUpdatedEvent.publish(published_at_diff)
  end
end
```

This way we will collect the parameters for `after_reindex` callback within generic `after_commit` AR callback (where we still see `saved_changes`), then forward them to `after_reindex` method (through async job parameters if needed). `after_reindex` method will be evaluated strictly after ES reindexing, no matter which callbacks mode (inline, async, whatever) is set.

I'm ready to provide PR once the feature will be accepted in general by code owners )

**Comment by ankane** [comment]
Hey @stengineering0, thanks for the suggestion. Since more complex workflows can be handled with a service / custom code, I don't think a callback is needed.

**Comment by stengineering0** [comment]
@ankane It's not possible to address this issue in a form of service, because we have to affect the deep internals of Searchkick. Saying about `:async` mode, we have to add our custom ReindexingJob in order to accept `after_reindex_params` parameter, then the place where Searchkick schedules the job we have to switch to the new Job class as well as to prepare said `after_reindex_params` params.

From the other hand, described race condition is actual for many applications - as long as event-driven architecture gets strong popularity. Some applications just don't face the problem in a flesh so far, because of low load. May be nice to have generalized solution right out of the box.

As I said we are ready to provide the PR for this feature. If you don't like the feature - what about some refactoring over Searchkick provided by us, in order to achieve the desired functionality in legal (no monkey patches) way?

**Comment by ankane** [comment]
You shouldn't need to touch Searchkick internals for this. For an async job that runs additional code, you can create a custom background job that calls `reindex` and then runs the code.
