### ISSUE TITLE
Global `Searchkick.refresh` mode

### ISSUE THREAD

**Issue by stengineering0** [ankane/searchkick#1586]
**Is your feature request related to a problem? Please describe.**
Sometimes FrontEnd relies on ES search data updated by itself a few moments ago.
For instance let's imagine the User creation UI form. Once submitted it will send POST API call to backend (where the user will be created and reindexed, perhaps asynchronously), and then it redirects to Users index page. If the new user happens to be not reindexed still - it will not appear in the Index page which confuses a lot.

This way we would like to request the instant reindexing by the client when really needed. Possible solution wrapping the Rails controller may look as follows:

```ruby
    module SynchronousIndexing
      extend ActiveSupport::Concern

      included do
        prepend_around_action :synchronous_indexing, if: :synchronous_indexing_requested?
      end

      private

      def synchronous_indexing
        Searchkick.refresh(true) do
          Searchkick.callbacks(:bulk) do
            yield
          end
        end
      end

      def synchronous_indexing_requested?
        request.headers['X-HTTP-SEARCH-INDEX-MODE'] == 'synchronous'
      end
    end
```

The only thing still missing on Searchklick side for this is global `Searchkick.refresh do; end` mode in addition to `Searchkick.callbacks do; end` one.

**Describe the solution you'd like**
Let's introduce the global `Searchkick.refresh() do; end` mode in addition to `Searchkick.callbacks() do; end` one.

I'm ready to provide PR once the feature will be accepted in general by code owners )

**Comment by ankane** [comment]
Hey @stengineering0, thanks for another suggestion. For endpoints that need synchronous reindexing, you can reindex inline and call `Model.search_index.refresh`, so I don't think an additional method is needed.

**Comment by stengineering0** [comment]
@ankane The idea is that any endpoint might be asked to reindex synchronously on demand. So there is no particular `Model` to be refreshed.

Saying even more - there is unpredictable number of records as well as corresponding models which might be affected within endpoint. For example the endpoint will add the role to the user, which triggers the reindexing both on UserRole and User records.

So the requested `Searchkick.refresh(true) do; end` feature does not differ logically from existing `Searchkick.callbacks(:bulk)` feature - but likely these features will supply one another.

As I told we are ready do provide PR for this feature.

**Comment by ankane** [comment]
Thanks for the additional context. I think it may be best as an option on `callbacks`:

```ruby
Searchkick.callbacks(:bulk, refresh: true) do
  # code
end
```

(which can then be passed to `indexer.perform`)

However, I'm not sure this use case is very common, so it's not something I'd like to support right now.
