### ISSUE TITLE
search_timeout not being reflected in muliti-model search?

### ISSUE THREAD

**Issue by geoffharcourt** [ankane/searchkick#1593]
**Describe the bug**

We recently started setting `Searchkick.search_timeout = 1` in our initializer, but we seem to have the occasional search that runs until our requests time out at 25s.

**To reproduce**
We're having trouble reproducing this in a test, but we can see it happen in our Sentry logs. We have `Rack::Timeout` terminating a request, and when it's cut off the last line of application code that's running is a request to Searchkick.

We're running Searchkick 5.0.5, OpenSearch 1.3, and version 2.0.2 of the `opensearch-ruby` gem (plus  2.0.1 of `opensearch-transport`). When we run requests in debug mode, we see that the `timeout` we pass on to OpenSearch is `2s` even though our `search_timeout` is verified as `1`.

Here's an example of the debug output:

```
Unit Search (1.5ms)  units_development/_search {"query":{"bool":{"should":[{"dis_max":{"queries":[{"multi_match":{"query":"job","boost":10,"operator":"and","analyzer":"searchkick_search","fields":["*.analyzed"],"type":"best_fields"}},{"multi_match":{"query":"job","boost":10,"operator":"and","analyzer":"searchkick_search2","fields":["*.analyzed"],"type":"best_fields"}},{"multi_match":{"query":"job","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true,"fields":["*.analyzed"],"type":"best_fields"}},{"multi_match":{"query":"job","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true,"fields":["*.analyzed"],"type":"best_fields"}}]}}]}},"timeout":"2s","_source":false,"size":10000}
```

```
main:0> Searchkick.search_timeout
=> 1
```

It appears that you can't set the timeout to be a fraction of a second, so we're having trouble making a clean test environment reproduction that can exceed the timeout.

**Additional context**
From our OpenSearch metrics it looks like we have enough requests exceeding 1s that we'd expect to see more exceptions in production since we configured `search_timeout`. We're wondering if this is a bug in Searchkick with OpenSearch or if we're doing something wrong. The mismatch between our configured setting and the debug output makes it seem like there's a gap somewhere either in our understanding or in the interface between Searchkick and OpenSearch's Ruby SDK.

**Comment by ankane** [comment]
Hey @geoffharcourt, Searchkick uses `search_timeout` as the timeout on HTTP requests and `search_timeout + 1` as the timeout for the search server. This allows for a reliable timeout for the app (for instance, if there's a network issue) as well as terminating the query on the search server when the app won't be waiting for the results. The search server returns partial results once the timeout is hit, so the one second difference is to ensure the HTTP request times out before the search server.

To test the timeout, you can set the search server URL to:

```sh
ENV["OPENSEARCH_URL"] = "http://10.255.255.1:9200"
```

It seems to be working.

**Comment by geoffharcourt** [comment]
Hi @ankane, thank you for your explanation! 

Everything you've said makes sense. I'm still confused by what we're seeing in our APM on these failing requests. Here's an example of one of the requests that timed out. It's a multi-model search, so multiple requests are made, but it looks like each of the requests is running for longer than the 1s (or 1 + 1s) that should be allowed:

![Screen Shot 2022-10-12 at 8 39 47 PM](https://user-images.githubusercontent.com/319471/195473047-ad26f3f6-079c-4aa8-b271-a0f2fb490ca0.png)

Shouldn't these requests be getting cut off well before the times they are running here? The Faraday requests are going to our OpenSearch cluster and are failing with `Net::ReadTimeout with #<Socket:(closed)>`, but one of them is running for a full ten seconds.

**Comment by geoffharcourt** [comment]
My requests seem to be `POST`s instead of `GET`s, is it possible that the timeout isn't being added because the HTTP verb doesn't match here?

https://github.com/ankane/searchkick/blob/a761740871849cd7e95f1c78cebd1896f698f45c/lib/searchkick/middleware.rb#L6-L9

**Comment by ankane** [comment]
Are you using `Searchkick.multi_search`? It looks like the timeout isn't being set for those requests.

**Comment by geoffharcourt** [comment]
Hi @ankane yes, we are!

**Comment by geoffharcourt** [comment]
I should clarify that we're using `Searchkick.search` but passing in multiple models with the `models` option in case that's different.

**Comment by ankane** [comment]
I removed the verb check like you suggested above. However, I'm not sure why the `timeout` option in the query body didn't cause the request to return earlier (unless there was a network issue between the app and search server).

**Comment by ankane** [comment]
Nevermind, if the error was `Net::ReadTimeout with #<Socket:(closed)>`, then it likely was a network/search server issue.

Just pushed a new release (5.1.0) with the fixes. Thanks for reporting and debugging!

**Comment by geoffharcourt** [comment]
Thank you @ankane for the investigation help and the very quick fixes!
