### ISSUE TITLE
Server hangs after adding Searchkick gem

### ISSUE THREAD

**Issue by davidklsn** [ankane/searchkick#1595]
Having issues running Searchkick and Anycable together.

**What I did**
Added the Searchkick gem in a working application using Anycable. 

**What I expected**
Everything working as normal

**What happened**
Server can't take any requests and just hangs. Nothing in the logs. The client just tries to load the page until I kill the server.

I tried to isolate everything in a new rails project with the same versions. It seems to be an issue when running Anycable-rails together with Searchkick. I can reproduce the issue here: https://github.com/davidklsn/searchkick-anycable-incompatibility

OS: Ubuntu 20.04.5

**Versions**
ruby 3.0.1
rails 7.0.4

searchkick (5.1.0)
anycable (1.2.3)
anycable-rails (1.3.4)
grpc (1.50.0 x86_64-linux)

Any help or guidance with this is highly appreciated! 

Cheers

**Comment by ankane** [comment]
Hey @davidklsn, I'm not sure what would cause this, but I'd recommend forking and adding debugging to see what's going on. If it points to an issue with Searchkick, happy to revisit.

**Comment by davidklsn** [comment]
@ankane yeah, okey! Thank you!
