### ISSUE TITLE
Remove duplicates from ReindexQueue while creating batches

### ISSUE THREAD

**Issue by qdegraeve** [ankane/searchkick#1604]
Hi @ankane ,

I would like to talk about an issue opened in 2018 then close => https://github.com/ankane/searchkick/issues/1141

We are facing a similar issue on our platform. Each night we process large files to update many data in the Database and the central resource get touched each time an association is updated to be sure that it is reindexed. The probleme is that when we finally call the `Searchkick::ProcessQueueJob` at the end of the process, there is a lot of duplicates in the redis list. I mean like a product id can appear something like 1000 times or more. 

Maybe there is a implementation issue but after digging into the code of Searchkick, we thought it would be great to remove all duplicate ids once added in a batch (maybe with a config option ?) so that for small batches like what we do (200) there is not too much jobs spawn uselessely.
Something like : 

```ruby
        Searchkick.with_redis do |r|
          while record_ids.size < limit && (record_id = r.rpop(redis_key))
            record_ids << record_id
            r.lrem(redis_key, count, record_id) if option_is_activated?
          end
        end
```

I would be glad to discuss about this idea or to hear why it is a bad idea.

Thanks in advance
Quentin

**Comment by ankane** [comment]
Hey @qdegraeve, thanks for the suggestion, but I still have the same thoughts as https://github.com/ankane/searchkick/issues/1141#issuecomment-388576914.

For a job like the one you've described, I'd recommend disabling callbacks and keeping track of the ids separately if needed, then doing a bulk reindex at the end.
