### ISSUE TITLE
Dynamic mappings

### ISSUE THREAD

**Issue by apuntovanini** [ankane/searchkick#1605]
**Is your feature request related to a problem? Please describe.**
If I pass a method to the `mappings:` it raises an error `custom_mappings = (options[:mappings] || {}).deep_symbolize_keys` because :mappings is a symbol.

**Describe the solution you'd like**
Each model may have custom fields in our app, we know these fields' kinds (single-select, date, etc.) and we know how to map them to search type (text, boolean, etc.). But it seems not possible right now to pass a method to mappings.

**Comment by ankane** [comment]
Hi @apuntovanini, thanks for the suggestion. There can only be one mapping per model, so it's not something I'd like to make dynamic.

**Comment by apuntovanini** [comment]
Thanks @ankane for the clarification, I thought I may reach the same goal though, using `.search` and specify fields types where needed
Thanks!
