### ISSUE TITLE
Bulk reindex with async key does not update processing status in redis.

### ISSUE THREAD

**Issue by Fattaf** [ankane/searchkick#1608]
**Describe the bug**
Currently, we are using version 5.1.1.
OpenSearch 2.3 as a search server.

After update from the version 4.6.3. Our `full_reindex_job` suddenly stopped applying the updates during the reindex.
Looks like `BulkReindexJob` does not call `batch_completed` properly.

Our code: 
```
 module HQ
  module Accounts
    class ReindexAccountsJob < ApplicationJob
      REFRESH_INTERVAL = '60s'

      queue_as :sync
      unique :until_executed, lock_ttl: 2.hours, on_conflict: :log

      def perform(in_async_batches: true)
        metadata = Repo::Account.order(id: :desc).reindex(async:  in_async_batches, wait: true, full: true, refresh_interval: REFRESH_INTERVAL)

        Repo::Account.search_index.promote(metadata[:index], update_refresh_interval: true)
      end
    end
  end
end
```
We spotted that `Searchkick.reindex_status(metadata[:index])` just never completed.

**Comment by ankane** [comment]
Hey @Fattaf, I'm not able to reproduce. I'd recommend forking and adding debugging to see what's going on. Happy to reopen it points to an issue with Searchkick.

**Comment by Fattaf** [comment]
Spotted the problem, we moved to the `OpenSearch` recently, but accidentally left `elasticsearch` gem in the project. 
We changed it to the `opensearch-ruby` gem and everything worked.
Maybe, it will be help to somebody too.
