### ISSUE TITLE
Request for adding "highlight_query" option to the highlighting

### ISSUE THREAD

**Issue by eliasbaixas** [ankane/searchkick#1609]
Hello Searchkick team,

I have a search on a site where users  often just filter by facet using '*' as the search query. 
The facets are usually person-names or location-names, but since those are filtered in the WHERE clause and not used in the query, they do not get highlighted.

This could be easily implemented if the highlight option supported highlight_query, as I understand it, it lets you highlight other terms not included in the search query.

Do you think that would be useful for the project ?
is there another way I can add the highlight_query to the highlight option using Searchkick ?

Best,

Elias

**Comment by ankane** [comment]
Hey @eliasbaixas, you can use `body_options` for this:

```ruby
Product.search("*", highlight: true, body_options: {highlight: {highlight_query: {match: {"name.analyzed" => {query: query}}}}}).highlights
```
