### ISSUE TITLE
Add Support for Redis-Client

### ISSUE THREAD

**Issue by sirwolfgang** [ankane/searchkick#1610]
With Sidekiq 7 dropping Redis and Connection Pool support infavor of the newer Redis-Client gem, I am working on trying to reduce the number of Redis Pools and types of errors that we have running in our application. 

Redis-Client is being developed to replace `redis` with an eye on future compatibility by binding commands to `.call` instead of the ruby method, and comes with a built in pooler. ie `.get(...` becomes `.call('GET', ...`

Can we add support for `redis-client`? Looks like only needs changes in a few places.

**Comment by ankane** [comment]
Hey @sirwolfgang, thanks for the suggestion. Added in the commit above (note the `redis-client` gem depends on `connection_pool`).
