### ISSUE TITLE
Support for dense vector field type

### ISSUE THREAD

**Issue by diasks2** [ankane/searchkick#1615]
ElasticSearch now has the [dense vector field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html) and [nearest neighbor search](https://www.elastic.co/blog/introducing-approximate-nearest-neighbor-search-in-elasticsearch-8-0).

There seem to be a lot of parallels with the work you have done with [pg_vector](https://github.com/pgvector/pgvector) and the [neighbor gem](https://github.com/ankane/neighbor). I'm wondering if it is on the road map to have some sort of native support for vector search built into the searchkick or if you would just recommend using a custom mapping? Or is there already another way currently supported in searchkick?

**Comment by ankane** [comment]
Hey @diasks2, you can use a custom mapping for this: https://gist.github.com/ankane/bdc64ff58b452651348fbe990b8252c6

**Comment by ankane** [comment]
Added an OpenSearch example as well
