### ISSUE TITLE
typhoeus error

### ISSUE THREAD

**Issue by 9mm** [ankane/searchkick#1623]
**Describe the bug**

Typheous fails with the following error when reindexing

```
Faraday::Error: :typhoeus is not registered on Faraday::Adapter
from /Users/zesty/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/faraday-2.7.4/lib/faraday/middleware_registry.rb:57:in `lookup_middleware'
```

**To reproduce**

1. add `tyhpoeus` to gemfile
2. bundle install
3. call Thing.reindex
4. The error will occur

I am using latest ruby, latest rails, latest typhoeus, latest searchkick.

**Comment by ankane** [comment]
Hi @9mm, I'm not sure how to reproduce. Please use the bug report template when possible.

**Comment by 9mm** [comment]
Do you mean you tried and couldn't reproduce it? Or that I just didnt provide enough info. Sorry about that.

I noticed that if I add the following to the gemfile, the error disappears:

```
gem 'faraday-typhoeus'
```

So perhaps its how searchkick is using faraday? I'm not sure, but this is a fresh rails project. There's nothing fancy about it, I just followed the instructions of adding typheous (which I love and use a lot) and searchkick generated errors when attempting to establish a connection. By adding the other gem (which isnt mentioned in searchkick readme) it appears to work ok

**Comment by 9mm** [comment]
Not sure if this helps:

https://github.com/lostisland/faraday/issues/761#issuecomment-1505578020
