### ISSUE TITLE
Synonym raises "completely eliminated by analyzer"

### ISSUE THREAD

**Issue by 9mm** [ankane/searchkick#1624]
**First**
[x] Search existing issues to see if it’s been reported and make sure you’re on the latest version.

**Describe the bug**
I added the following synonym:

```
    search_synonyms: [
      ...,
      ['x', '×'],
    ]
```

And reindexing raises:

```
{"type":"illegal_argument_exception","reason":"term: × was completely eliminated by analyzer"}
```

I'm trying to get it so all the following are the same:

```
1x1
1 x 1
1×1
1 × 1
```

I found this issue: https://stackoverflow.com/questions/72315212/elastic-search-synonym-completely-eliminated-by-analyzer

Which makes it seem like its related to min gram length, but when I look at the default options of searchkick it looks like its already set to 1.

**To reproduce**
Use this code to reproduce when possible:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem 'elasticsearch', '< 7.14'
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.string :name
  end
end

class Product < ActiveRecord::Base
  searchkick **{
    search_synonyms: [
      ['x', '×'],
    ],
  }
end

Product.reindex
Product.create!(name: "Test")
Product.search_index.refresh
p Product.search("test", fields: [:name]).response

```

**Comment by ankane** [comment]
Hi @9mm, `×` is removed by the [standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-tokenizer.html), which is why you're seeing that error from the search server. You can use `gsub("×", "x")` in `search_data` to get around this.
