### ISSUE TITLE
Search response doesn't return custom field at top level

### ISSUE THREAD

**Issue by aashishpsaini** [ankane/searchkick#1630]
When we set model name in search_data method as a field, and when we query using Searchkick.search("query"), the response doesn't contain field containing model name. However [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html) describes to define it as replacement for type field.

**To reproduce**
Contrived example using the standard example:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", require: "active_record"
  gem "activejob", require: "active_job"
  gem "sqlite3"
  gem "searchkick", git: "https://github.com/ankane/searchkick.git"
  gem "elasticsearch", "7.17"
  gem 'redis'
end

puts "Searchkick version: #{Searchkick::VERSION}"
puts "Server version: #{Searchkick.server_version}"

ActiveRecord::Base.establish_connection adapter: "sqlite3", database: ":memory:"
ActiveJob::Base.queue_adapter = :inline

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.string :first_name
    t.string :last_name
    t.string :gender
  end
end

class User < ActiveRecord::Base
  searchkick

  def search_data
    {
      model_name: self.class.name.underscore,
      first_name: first_name,
      gender: gender,
      search_data_indexed_at: Time.now.utc
    }
  end
end

Searchkick.redis = Redis.new
User.create!(first_name: "Johnie", last_name: "Lee", gender: "Male")
User.create!(first_name: "Chris", last_name: "Gross", gender: "Male")
User.reindex
a = Searchkick.search("Chris")
puts a.response
=> {"took"=>301, "timed_out"=>false, "_shards"=>{"total"=>111, "successful"=>111, "skipped"=>0, "failed"=>0}, "hits"=>{"total"=>{"value"=>1, "relation"=>"eq"}, "max_score"=>6.931472, "hits"=>[{"_index"=>"users_development_20230421154655422", "_type"=>"_doc", "_id"=>"2", "_score"=>6.931472}]}}

```

**Additional context**
Note: Since Elasticsearch was updated to >7.14, mapping was removed and in the search response `_type` was returned as `doc` for all documents, In their migration guide, it was mentioned you can pass in custom fields to get it returned, but its not working via Searchkick. Please provide solution.

**Comment by ankane** [comment]
Hi @aashishpsaini, use the `select` option to control which fields are returned (or `load: false` to get all the fields).

**Comment by aashishpsaini** [comment]
Thanks @ankane It helped. I can see it works in development, however in minitest suites, it's not returning all fields, do we have to do any different configuration for tests?
