### ISSUE TITLE
new option to ignore search_import

### ISSUE THREAD

**Issue by memsenpai** [ankane/searchkick#1632]
After defining the search_import, every time I reindex, it is automatically used and there is no way for me to skip it, even when my scope only has 1-2 records.
Currently, I can also solve the problem by writing additional logic checks in search_import, but I think it would be great if you could support it.
I hope we have an option that can limit the minimum number of records to use search_import, or we can skip it.

`.reindex(search_import: false)`
`.reindex(search_import_when: 10)`

**Comment by ankane** [comment]
Hi @memsenpai, can you share more about why you want to skip it?

**Comment by memsenpai** [comment]
@ankane 
When the default scope is very small or just 1, using "include" for preload doesn't really help and will make everything worse.

**Comment by ankane** [comment]
Hi @memsenpai, I don't really understand how it makes things worse, but you can call reindex on individual records to skip it.

```ruby
Searchkick.callbacks(:bulk) do
  Product.where(...).map(&:reindex)
end
```

**Comment by abdul-wahab-qbatch** [comment]
@ankane & @davidwparker do we have any update regarding this?  This is causing a lot of queries that are not required in partial reindexing.
