### ISSUE TITLE
Configure client_type per index

### ISSUE THREAD

**Issue by Earlopain** [ankane/searchkick#1633]
I currently use elasticsearch but plan to migrate to opensearch in the future. I want to gradually move indicies to opensearch but at the moment it looks like I can use either elastic or opensearch, not both at the same time.

I would be willing to implement this myself if you'd consider merging it.

**Comment by ankane** [comment]
Hi @Earlopain, thanks for the suggestion. I don't want to support the additional complexity right now, but you could create a fork to use for migrating.

**Comment by Earlopain** [comment]
Using a fork somehow didn't cross my mind. That will suit my needs just fine. Perhaps I'll link it here when I got something.
