### ISSUE TITLE
Search with misspellings on certain field.

### ISSUE THREAD

**Issue by andreikarabitski** [ankane/searchkick#164]
Hello, 
do I have a possibility to search on several fields defined in index with misspellings disabled, but certain field with enabled misspellings? I guess I have to create custom mapping for that field?

**Comment by sweetmandm** [comment]
Here's my hacky workaround in the meantime. Heads-up that this is deadline-mode-code 😂 It's probably specific to the queries I'm making. Thanks for pointing `execute: false` & `query.body`!

I haven't really grokked the elasticsearch docs but I noticed that (with mostly-default searchkick queries anyway) leaving misspellings enabled results in two extra query body entries vs. adding `misspellings: false`. This code just tries to remove the two extra entries that look like they were added to handle misspellings, and it seems to be working for me.
```
  def run
    q = Product.search("Test", fields: [:title, :description], execute: false)
    disable_misspellings!(q.body, ["title.analyzed"])
    q.execute
  end

  def disable_misspellings!(query_body, keys)
    return unless query_body.dig(:query, :dis_max, :queries)

    # Remove any query containing at least one of misspelling_params
    misspelling_params = [
      :fuzziness,
      :prefix_length,
      :max_expansions,
      :fuzzy_transpositions
    ]

    keys.each do |key|
      items = query_body[:query][:dis_max][:queries]
      query_body[:query][:dis_max][:queries] = items.reduce([]) do |acc, item|
        match_params = item.dig(:match, key).try(:keys) || []
        if (match_params & misspelling_params).any?
          # This looks like a misspelling query! don't include it in 'acc'
          acc
        else
          acc.append(item)
        end
      end
    end
  end
```
