### ISSUE TITLE
Explicit synonyms do not work

### ISSUE THREAD

**Issue by Hugo-Trial** [ankane/searchkick#1647]
[Explicit mapping for synonym](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html) do not work ie.
sea biscuit, sea biscit => seabiscuit

**To reproduce**
Using that type of synonym will make all the synonyms being ignored

**Comment by ankane** [comment]
Hi @Hugo-Trial, please use the bug report template to reproduce.
