### ISSUE TITLE
Add documentation for client_options

### ISSUE THREAD

**Issue by hunterbmiller** [ankane/searchkick#1648]
First of all, thanks for this awesome gem!

When doing the initial setup, I had a hard time configuring my different environments. Once I looked through the code and noticed `client_options`, it solved my issues immediately. 

I propose adding documentation of this to the `Deployment` section of the `README.md` - I'd be happy to do it, but I thought I would propose it here first.

**Comment by ankane** [comment]
Hi @hunterbmiller, thanks for the suggestion! Added in the commit above.
