### ISSUE TITLE
named query search example (_name)

### ISSUE THREAD

**Issue by 2ge** [ankane/searchkick#1650]
Hi

I would like to debug some queries, I need to use named queries as described here:
https://opster.com/guides/elasticsearch/search-apis/named-queries/

I did my best, but I can not get this working, no example exist how to use this using searchkick.

Thank you for any help.

**Comment by ankane** [comment]
Hi @2ge, check out the [Advanced Search](https://github.com/ankane/searchkick#advanced-search) section for how to modify a query, and see the new issue page for where to get additional help.
