### ISSUE TITLE
Scoped include in search_import not being loaded

### ISSUE THREAD

**Issue by GMolini** [ankane/searchkick#1652]
Ive got a model like this one

```ruby
class MyModel < ApplicationRecord

  scope :search_import, -> { includes(
    :ordered_b) }

  has_many :a

  has_many :ordered_b, -> { order(creation_date: :desc).includes(:d,:e,:f).limit(50) }, through: :a, source: :b


  def search_data
   {
    bs: ordered_b.map{|b| b.title}
   }
  end
end
```

The thing is, if I do the `scope :search_import, -> { includes( :ordered_b) }` the has many relation is not being loaded, and search_data is empty. If I dont do it, reindexing takes longer because it needs to do the query for each object, but the resulting object has the correct data loaded to elastic.

I dont know if its a bug or is just that doing that kind of scoped import is not supported. I cannot import the whole :b relationship because in some instances Ive got too many records and run out of memory

Thanks

**Comment by ankane** [comment]
Hi @GMolini, please use the bug report template to reproduce.
