### ISSUE TITLE
Default index name doesn't use UTC time

### ISSUE THREAD

**Issue by adzienis** [ankane/searchkick#1657]
**First**
Didn't see any directly mentioning this specific issue

**Describe the bug**
Searchkick creates new indices with a name using this format: https://github.com/ankane/searchkick/blob/master/lib/searchkick/index.rb#L260C6-L260C6. 

It uses a `Time.now` that defaults to whatever the currently used timezone on the machine is. This is fine for machines that already are using UTC as the timezone (like any provisioned machines), but will default to a developer's timezone (because they probs don't use UTC). 

At least in my situation, this popped up when I was setting up very specific scenarios where VCR's were failing because the CI/CD index names weren't matching Timecop'ed index names.

**To reproduce**
Reindex any model.

Note that the default time in the index name is the time in your zone but not UTC.

```
model.reindex
Searchkick.client.indices.resolve_index(name: "#{model.searchkick_index.name}*")
```

Example, I am currently in EST/New York, and I just reindexed this at 10:59 EST. Note the default time is for 10:59 AM EST, and not 3:59 PM UTC (15:59):
![Screenshot 2023-11-11 at 10 59 11](https://github.com/ankane/searchkick/assets/7027362/f21f6f22-7c0e-4ac4-9c30-f5ec2bb13799) The full index name, if we were defaulting to utc, should be `jobs_development_20231111155904921` (UTC) rather than `jobs_development_20231111105904921` (EST)

Let me know if this makes sense or if this is intended. This could also be solved by explicitly setting the index name, but I'd prefer to use the defaults if possible.

Appreciate the work done in creating and maintaining Searchkick.

This could be solved in a oneliner to switch to using `Time.now.utc`

**Comment by ankane** [comment]
Hi @adzienis, thanks for reporting, but I don't see a strong reason to change this.
