### ISSUE TITLE
minor issue when when doing a full reindex in queue mode

### ISSUE THREAD

**Issue by goromlagche** [ankane/searchkick#1658]
**Describe the bug**
Not necessarily a bug, but there are some gotchas when trying to do a full reindex with queue mode,

e.g. 
```
Product.reindex(mode: queue)
Searchkick::ProcessQueueJob.perform_later(class_name: "Product")
```
Does not work as intended.

this does
```
Product.reindex(mode: queue)
Searchkick::ProcessQueueJob.perform_later(class_name: "Product", index_name: "new_product_index_with_timestamp")
```

My guess is 
https://github.com/ankane/searchkick/blob/a68267718cbd30db322b8edc7a878978eb6906cc/lib/searchkick/record_indexer.rb#L51 in here index is the raw index. `reindex_queue.send(:redis_key)` will return `new_product_index_with_timestamp`

But when process queue job pulls in the data 
https://github.com/ankane/searchkick/blob/a68267718cbd30db322b8edc7a878978eb6906cc/lib/searchkick/process_queue_job.rb#L11
it uses alias.

It will be good to update to fix the code path to always use alias name. Or update the readme with a note.

**Comment by ankane** [comment]
Hi @goromlagche, thanks for reporting. Full reindex doesn't support `:queue` mode, so you'll want to use `:async` mode instead. Added a warning in the commit above and will change to an error in Searchkick 6.
