### ISSUE TITLE
Make "Searchkick.search" for multi-model searches work with Rails low-level caching

### ISSUE THREAD

**Issue by 34code** [ankane/searchkick#1659]
**First**
Done. researched existing issues.

**Is your feature request related to a problem? Please describe.**
The problem I have is slow search queries. Sometimes more than 5-10 seconds (esp. single keyword searches). The solution I want is acceleration of search queries using caching. I think rails low level caching with solid-cache is a good fit. However, the object generated by Searchkick.search(query, params) is always unique even for the same query and same params, thus busting the cache.. 

**Describe the solution you'd like**
I would like the ability to cache multi-model search results returned by searchkick using solid-cache for improved performance.

**Additional context**
Another StackOverflow question about the same issue: https://stackoverflow.com/questions/77636414/how-can-i-cache-the-results-returned-by-searchkick-in-rails-using-low-level-cach
A ChatGPT dialogue about the same issue: https://chat.openai.com/share/a54d0100-4ec8-4952-af30-286495da68a4

**Comment by 34code** [comment]
I think I can accomplish what I need using `multi-search` instead of `Searchkick.search` ... I lose the feature to boost certain models but im ok with that if it results in sub second searches for repeated searches.

e.g.

```
products = Product.search("snacks")
coupons = Coupon.search("snacks")
Searchkick.multi_search([products, coupons])
```

Then I can cache each of the lines above..

**Comment by ankane** [comment]
Hi @34code, you can currently use:

```ruby
results =
  Rails.cache.fetch(["search", query]) do
    Searchkick.search(query, models: [Product, Category]).load # or to_a, response, etc
  end
```

**Comment by 34code** [comment]
hmm, seems like search is still running on subsequent request.. I can see this in my logs:

```
 Search (7107.5ms)  com_walmart_items_development, another_model, etc ...
```

Here is my search (using some additional features like highlights etc)

```Searchkick.search(@search, track: {user_id: @user_id}, misspellings: {edit_distance: 2, below: 5, prefix_length: 3}, aggs: multi_aggs, suggest: [:title, :alt_title], models: @models, where: {category: @category}, per_page: 10, page: @page, fields: ["barcode^1" ,"title^5", "alt_title^2", "description"], boost_by: {price_count: {factor: 2}}, indices_boost: @boost, highlight: {tag: '<span class="bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-yellow-300 border border-yellow-300">'}).load```

**Comment by 34code** [comment]
My bad, I was using @models within the key which was comprised of a set of ActiveRecord models.. It wasn't a good choice of `cache_key`.. both `.load` and `.to_a` at the end are working well.
