### ISSUE TITLE
Why is `_script` filters commented out in the source code? Possible to add support for scripts?

### ISSUE THREAD

**Issue by fabioxgn** [ankane/searchkick#1660]
I'm trying to write a query that compares 2 dates, and my understanding is that I need to use a script filter something like:

```ruby
Model.search(
  '*',
  where: { status: 'something', _script: "return doc['a'].value.getMillis() > doc['b'].value.getMillis()" },
)
```

This works and generates a valid filter query if I uncommented the code from here: https://github.com/ankane/searchkick/blob/74fd743f47eea99bfb33cf9339dccfc8ca4f5fc0/lib/searchkick/query.rb#L911

Any reason for this code to be commented out?

**Comment by fabioxgn** [comment]
There's also an unmerged PR from last year, so I'm not that only one that needs this: https://github.com/ankane/searchkick/pull/1600

@ankane do we need anything to get that PR merged? I can also send a PR if this requires more changes, but just uncommenting that code works for me.

**Comment by ankane** [comment]
Added support in the commit above.
