### ISSUE TITLE
Clarify use of ActiveRecord `where` in `search_import`

### ISSUE THREAD

**Issue by JasonBarnabe** [ankane/searchkick#1667]
[The readme explains `search_import` as such](https://github.com/ankane/searchkick#indexing):

> To eager load associations, use the `search_import` scope.
> (...)
> By default, all records are indexed. To control which records are indexed, use the `should_index?` method together with the `search_import` scope.

Now an obvious extrapolation here would be to add `where` to `search_import` to eliminate records that should not be indexed. This is a suggestion also present in some issues like #1503.

I've tested this out and it does work to eliminate records, but there is one major caveat - if a record is already indexed, then updated such that the `where` in `search_import` no longer matches it, *the record remains in the index*.

For example:

```ruby
class User
  searchkick
  scope :search_import, -> { where.not(name: 'Jason') }

  def should_index?
    name != 'Jason'
  end
end

user = User.create(name: 'Fred')
# (User gets indexed)

user.update(name: 'Jason')
# (User remains in index!)
```
Removing `search_import` in the above example fixes the issue.

I'm not sure if this is intended functionality, but if it is, this should be documented - for example by saying that `where` should only added to `search_import` if the record will never be updated so that it shouldn't be indexed.

**Comment by ankane** [comment]
Hi @JasonBarnabe, this was updated in 2022 in d6abba8d2e3fe4e11b9fedd8865491634316d48b.
