### ISSUE TITLE
Unable to load dynamic synonyms with Elastic

### ISSUE THREAD

**Issue by danjebs** [ankane/searchkick#1669]
When calling `MyModel.search_index.reload_synonyms`, I receive the error `Searchkick::Error (Requires non-OSS version of Elasticsearch)`

In Sentry, I see a nested error - this was caught and the above message was displayed instead
```
Elasticsearch::Transport::Transport::Errors::MethodNotAllowed: [405] {"error":"Incorrect HTTP method for uri [/reviews_reviews_development/_reload_search_analyzers] and method [GET], allowed: [POST]","status":405}
```

Digging into searchkick/lib/index.rb, I (thought I) found the problem code on line 196, where GET is used instead of POST:
```ruby
def reload_synonyms
  if Searchkick.opensearch?
    client.transport.perform_request "POST", "_plugins/_refresh_search_analyzers/#{CGI.escape(name)}"
  else
    raise Error, "Requires Elasticsearch 7.3+" if Searchkick.server_below?("7.3.0")
    begin
      client.transport.perform_request("GET", "#{CGI.escape(name)}/_reload_search_analyzers")
    rescue => e
      raise Error, "Requires non-OSS version of Elasticsearch" if Searchkick.not_allowed_error?(e)
      raise e
    end
  end
end
```

But if I try to run that command in Rails console, I get an exception about the request body being required.
```
irb(main):039:0> Searchkick.client.transport.perform_request("POST", "#{CGI.escape(Reviews::Review.search_index.name)}/_reloa
d_search_analyzers")
Traceback (most recent call last):
        2: from (irb):38
        1: from (irb):39:in `rescue in irb_binding'
Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400})
```

I don't see anywhere it is being set in `reload_synonyms()`, so I'm unsure exactly how to format this. But - it does seem like there is a bug here, nonetheless.

My `searchkick` definition is simple:
```ruby
class Reviews::Review < ApplicationRecord
  ...
  searchkick callbacks: false, search_synonyms: "elastic/review_synonyms.txt"
  ...
end
```

Where I have config/elastic/review_synonyms.txt
```
food,naminam
turtle,tortoise,tortoises,turtles
```

I am running:
* Searchkick version: 5.0.4
* Elastic version: 7.10.2 (hosted on Bonsai)

**Comment by ankane** [comment]
Hi @danjebs, that functionality is only available with the non-OSS version of Elasticsearch.
