### ISSUE TITLE
Add Semantic Search support

### ISSUE THREAD

**Issue by nhorton** [ankane/searchkick#1671]
Per your ideas list, Semantic Search support would be really helpful.

We have rolled our own version at Unsupervisedcom inside our source, and we spend a lot of time tweaking it right now. The biggest issue is that most of the higher-level helpers, particularly ones like the Pagy extensions, don't play nicely with our custom efforts to do this, and it is problematic. Getting a base implementation in Searchkick that other things like Pagy could then start integrating over time would be very helpful.

I would be glad to share some of the code we have for this right now, or if you (@ankane ) have an architecture you have in mind for how to integrate it in that you want to share, we could even try to flesh it out using some of our code.

**Comment by nhorton** [comment]
@ankane - hey, I was wondering if you had any thoughts on this. Note that we have been using Opensearch for our work, but I have noticed that you are doing a ton with PGVector recently - if there was a recipe for doing semantic and traditional search purely over Postgres, that would be quite cool too.

**Comment by ankane** [comment]
Hi @nhorton, can you share more about what this might look like? Nearest neighbor search is already possible ([docs](https://github.com/ankane/searchkick?tab=readme-ov-file#nearest-neighbors)).

**Comment by ankane** [comment]
Added a new option for [nearest neighbor search](https://github.com/ankane/searchkick/?tab=readme-ov-file#nearest-neighbor-search), as well as examples for [semantic](https://github.com/ankane/searchkick/?tab=readme-ov-file#semantic-search) and [hybrid search](https://github.com/ankane/searchkick/?tab=readme-ov-file#hybrid-search).
