### ISSUE TITLE
Make it also possible to set track_total_hits to an integer

### ISSUE THREAD

**Issue by zuccamia** [ankane/searchkick#1672]
### Problem description
For our search, we are currently allowing users to instantly download a list of the search results data if the total count is less than 10,000 hits. Since Elasticsearch has the same default limit, users now can download any time but with the inaccurate number of results. We would like to be able disable downloading in the case the total hits are more than 10,000. 
I am aware of the option to use `body_options: {track_total_hits: true}`, which accurately counts all matches but can be costly for query that match lots of documents. I would like to be able to set `track_total_hits` to count until a customized limit (in our case simply 10,001) to help control the impact on performance.

Elasticsearch already has [the option](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/search-your-data.html#track-total-hits) to set `track_total_hits` to an integer that I think would be nice to support with Searchkick's querying like SQL (which is really nice!), without having to use advanced query.

### Possible solution
Set the `payload[:track_total_hits]` to the value passed in `body_options[:track_total_hits]` instead of `true` in [`Searchkick::Query#prepare`](https://github.com/ankane/searchkick/blob/239c1781c66b075854c1d353d993cc26d8f1f7de/lib/searchkick/query.rb#L543)

```ruby
if track_total_hits?
	payload[:track_total_hits] = body_options[:track_total_hits]
end
```

Happy to open a PR if you think this is reasonable! Thank you.

**Comment by ankane** [comment]
Hi @zuccamia, you should be able to pass it to `body_options` (the next line in `Searchkick::Query#prepare` will override `true`).

```ruby
Product.search("query", body_options: {track_total_hits: 10001})
```

**Comment by zuccamia** [comment]
My apologies — I’m not sure how I missed the next line in `Searchkick::Query#prepare` 🤦 . Thanks for pointing it out!
