### ISSUE TITLE
Share indexes across environments?

### ISSUE THREAD

**Issue by antarr** [ankane/searchkick#1674]
I have a database that is shared across production and staging. Is it possible to configure searchkick, to use a single index for both staging and production?

**Comment by ankane** [comment]
Hi @antarr, you can use the same `ELASTICSEARCH_URL`/`OPENSEARCH_URL` across environments and either set the index name directly on the model (`searchkick index_name: "my-index"`) or set `Searchkick.env` so it's the same in both environments (since it's included in the default index name).
