### ISSUE TITLE
Add support search_pipeline for OpenSearch client

### ISSUE THREAD

**Issue by tamcv** [ankane/searchkick#1675]
`opensearch-ruby` client supports the search_pipeline as `client.search(search_pipeline: 'my_pipeline', body: {})`

**Comment by ankane** [comment]
Hi @tamcv, you should be able to use the client (`Searchkick.client`) directly to create/manage pipelines, and use `request_params` for search:

```ruby
Product.search(request_params: {search_pipeline: "my_pipeline"}, body: {})
```
