### ISSUE TITLE
model.indexed? as method for checking if a particular row has been indexed already?

### ISSUE THREAD

**Issue by 34code** [ankane/searchkick#1685]
**First**
Searched 

**Is your feature request related to a problem? Please describe.**
I ETL data into postgres and then run `Model.reindex` periodically. I created a materialized view to capture only recent inserts based on `created_at` populated during ETL. I would like to have an `is_indexed` column that reflects whether something has been indexed into ES already, so as to only pickup items to index which have not been indexed already.

**Describe the solution you'd like**
In order to populate the column I think I would need a method from searchkick that lets us know if that record has been indexed already? Is there a way to introspect the index to retrieve the IDs of postgres model indexed?

**Additional context**
Nice to have. Sometimes a record might have been indexed already but is stale. In this case comparing `indexed_at` and the record's `created_at` might be required..

**Comment by 34code** [comment]
I think I may have found the answer through `.methods` on `Model.search_index`..

So doing a `Model.search_index.search_id(i)` where `i` is an active record record object.. should return the id of the item if it exists in the search_index.. Otherwise, it will return: `"000000000000"`..

I think I can work with this..

**Comment by ankane** [comment]
Hi @34code, you can use `Model.search_index.retrieve(record)` for this.
