### ISSUE TITLE
exists: false acts like exists: true

### ISSUE THREAD

**Issue by JasonBarnabe** [ankane/searchkick#1686]
[The README](https://github.com/ankane/searchkick?tab=readme-ov-file#querying) documents the query option:

```ruby
store_id: {exists: true},      # exists
```

This seems to imply that you could do:

```ruby
store_id: {exists: false},      # does not exist
```

However, [the code](https://github.com/ankane/searchkick/blob/6ce2f6a0e7e45f74a30f1733ce7a8aa5681970f2/lib/searchkick/query.rb#L1009-L1010) seems to not care at all what value is passed; it always does an "exists" check.

It would be good to support `exists: false`, and/or raise an error on unexpected values for `exists`.

Working alternative is to use `_not: { store_id: {exists: true} }`.

**Comment by ankane** [comment]
Hi @JasonBarnabe, thanks for reporting. Added a warning for non-`true` values in the commit above, and will change to an error and add support for `exists: false` in Searchkick 6.
