### ISSUE TITLE
FloatDomainError when paginating past max_result_window

### ISSUE THREAD

**Issue by JasonBarnabe** [ankane/searchkick#1687]
searchkick 5.3.1
will_paginate 4.0.1

In #1445, it was reported that a "Searchkick::InvalidQueryError: Result window is too large" exception occurred when trying to paginate past 10,000 results, and the solution provided was to set `max_result_window: 10000` to avoid exceptions.

When I set this and try out a request that paginates too far, I do seem to avoid that error, but I instead get a "FloatDomainError: Infinity" exception. 

```
Searchkick::Results#total_pages searchkick (5.3.1) lib/searchkick/results.rb, line 114
Searchkick::Relation#method_missing activesupport (7.1.3.4) lib/active_support/core_ext/module/delegation.rb, line 333
#<Class:0x00007fd6476ceec0>#will_paginate will_paginate (4.0.1) lib/will_paginate/view_helpers.rb, line 73
#<Class:0x00007fd6476ceec0>#will_paginate will_paginate (4.0.1) lib/will_paginate/view_helpers/action_view.rb, line 33
```
In `total_pages`, `per_page` is giving a value of 0. This method is being called because will_paginate is still trying to render pagination on the response (perhaps naively).

I don't see why `per_page` would give a 0 in this case and not allow the pagination to still be rendered.

**Comment by ankane** [comment]
Hi @JasonBarnabe, fixed in the commit above.
