### ISSUE TITLE
bug report: settings (mappings) not respected with index is created via `Relation#reindex` instead of `Model#reindex`

### ISSUE THREAD

**Issue by andreynering** [ankane/searchkick#1693]
Hey there!

We're using Searchkick v5.3.1 with OpenSearch v2.11.0.

I'm currently testing a new index. While I'm just testing, I want to index only part of the table because this table is huge and it'd take a lot of time to index it completely. I found a bug on tried to do that.

We have a setting similar to this:

```ruby
searchkick callbacks: false,
           mappings: {
             dynamic: 'strict',
             properties: {
               account_id: { type: 'keyword' },
               foobar: { type: 'flat_object' },
               # many other fields
             }
```

Assume the index was not previously created, or was deleted.

If I call `Model.reindex` the expected happen:

- A `index_name_${timestamp}` index is created
- `index_name` as an alias
- Definitions are respected (`foobar` is an `flat_object`)

Though, if I call `Model.where(account_id: account.id).reindex`, the following happen:

- An index named `index_name` is created
- There is no alias
- Definitions are not respected. `foobar` is not created as a `flat_object` and OpenSearch tried to add keys inserted into `foobar` to the mapping, which we want o avoid.

**Comment by ankane** [comment]
Hi @andreynering, you need to call reindex on the model to set up the index correctly. If you only want to reindex a subset of records for testing, you can use:

```ruby
Model.reindex(import: false)
Model.where(account_id: account.id).reindex
```

**Comment by andreynering** [comment]
Hey @ankane,

Any reason on why we need to do that? From a UX point of view, that's counterintuitive. Why couldn't `Model.where(account_id: account.id).reindex` also create the index correctly?

**Comment by ankane** [comment]
`Relation.reindex` would need to perform an additional API request on each call to check if the index is set up, which would be expensive.
