### ISSUE TITLE
Term filter on nested Sort possible?

### ISSUE THREAD

**Issue by jbwl** [ankane/searchkick#1700]
Hi,

I'm wondering if this option for sorting is supported (the readme says "all of the sorting options are supported") yet? If so, I'm having a hard time getting the searchkick query syntax right:

What I am trying to do is described here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#_nested_sorting_examples

Specifically I am trying to write this example in Searchkick syntax:

```ruby
response = client.search(
  body: {
    query: {
      term: {
        product: 'chocolate'
      }
    },
    sort: [
      {
        'offer.price' => {
          mode: 'avg',
          order: 'asc',
          nested: {
            path: 'offer',
            filter: {
              term: {
                'offer.color' => 'blue'
              }
            }
          }
        }
      }
    ]
  }
)
```

The nested sort itself does work fine with Searchkick, but I need to filter the association I am sorting on a term.

Thank you!

**Comment by ankane** [comment]
Hi @jbwl, see the new issue page for where to get help (the `body` option is passed directly to the search server).

**Comment by pldavid2** [comment]
Hello @jbwl did you find the solution? I'm struggling with the same issue, can't make nested sort to take into account the association filter.

**Comment by pldavid2** [comment]
> > Hello [@jbwl](https://github.com/jbwl) did you find the solution? I'm struggling with the same issue, can't make nested sort to take into account the association filter.
> 
> Like suggested, I'm just using elasticsearch JSON in the body.

Thank you, I was using elasticsearch JSON but only on the _order_ clause, to keep using the _where_ searchkick conditions. Order works but without filtering by the nested term.

Will try the _body_ clause although i understand i will not be able to use the searchkick _where_ conditions anymore.
