### ISSUE TITLE
Suggestions for nested fields

### ISSUE THREAD

**Issue by russellbrown** [ankane/searchkick#172]
I love that this gem supports "did you mean" suggestions, but so far I can only get it to generate suggestions on root fields. Is there a way to make it work with nested fields?

Suppose my indexed data looks something like:

```
def search_data
  as_json only: [:id], include: { category: { only: [:name] }}
end
```

Can searchkick generate suggestions based on the category name?  I've tried the following but neither of them seem to work:

```
class Article < ActiveRecord::Base
  searchkick suggest: [:category => :name]
end

class Article < ActiveRecord::Base
  searchkick suggest: ["category.name"]
end
```

The only way I've been able to achieve the desired outcome is by adding a custom `category_name` method on the `Article` model and including it in the `as_json` output and the searchkick `suggest:` option, but if there's a way to do it without this extra method it would be preferable.

Thanks again, and great gem.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
