### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by russellbrown** [ankane/searchkick#173]
Are there any plans to implement lazy loading so that ElasticSearch isn't queried until an instance variable representing the query is referenced in the view?  Currently, the ElasticSearch query is executed as soon as `.search()` is invoked in the controller, therefore any fragment caching in the view is not as effective as it could be.

**Comment by fabn** [comment]
Now that 1.0 is out, is there any plan for this? It would be a great improvement for this awesome gem.

**Comment by ankane** [comment]
On master, you can do:

```ruby
@products = Product.search("*", execute: false) # returns Searchkick::Query
@products.each { ... } # call to Elasticsearch, returns Searchkick::Results
```

Maybe this should be a global option as well.
