### ISSUE TITLE
Facets on nested fields

### ISSUE THREAD

**Issue by russellbrown** [ankane/searchkick#174]
Similar to #172, is there any way to use a nested field as a facet?  Supposing my data is indexed using the following structure:

```
def search_data
  as_json only: [:id], include: { category: { only: [:name] }}
end
```

I can't seem to do a faceted search like this:

```
@articles = Article.search params[:q], facets: [:category]
```

The only working solution I've got so far is to create a `category_name` instance method on the Article model, include it in `search_data` and then use is in the faceted query like `facets: [:category_name]` but it seems a bit cumbersome.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
