### ISSUE TITLE
Any way to search case insensitive, or to change the analyzer?

### ISSUE THREAD

**Issue by jakcharlton** [ankane/searchkick#177]
AFAIK to do a case insensitive search in ES requires a lowercase analyser ... Can this be done on a global level, short of mapping individual fields?

**Comment by edslocomb** [comment]
Three-year Bump?

Case-insensitive search is what most of our clients seem to want.

**Comment by ankane** [comment]
@jakcharlton Search is case-insensitive. `where` option is case-sensitive (just like SQL).
