### ISSUE TITLE
Index created but cannot search by fields

### ISSUE THREAD

**Issue by tdi** [ankane/searchkick#185]
I am using searchkick 0.7.1 and tested with ES 1.0.3 and 1.1.0, in both cases index is created but I cannot search by field, neither via REST API or searchkick from ROR. 
I can only search by *, i.e. User.search '*', or `http://HOST/users_development/_search.` 

What I did was get a User model, searchkick enabled. `rake searchkick:reindex class=User`. 

The mapping created is:

```
 {"users_development_20140417174741792":{"mappings":{"_default_":    {"index_analyzer":"default_index","dynamic_templates":[{"string_template":{"mapping":{"type":"multi_field","fields":{"analyzed":{"index":"analyzed","type":"string"},"{name}":{"index":"not_analyzed","type":"string"}}},"match":"*","match_mapping_type":"string"}}],"properties":{}},"user":{"index_analyzer":"default_index","dynamic_templates":[{"string_template":{"mapping":{"type":"multi_field","fields":{"analyzed":{"index":"analyzed","type":"string"},"{name}":{"index":"not_analyzed","type":"string"}}},"match":"*","match_mapping_type":"string"}}],"properties":{"$oid":{"type":"string","index":"not_analyzed","fields":{"analyzed":{"type":"string"}}}}}}}}
```

_stats shows 

```
"indexing":{
"index_total":19,
 "index_time_in_millis":184,
 "index_current":0,
 "delete_total":1,
 "delete_time_in_millis":0,
  "delete_current":0
  },
```

It works when created indexes by hand or with a plugin river mongo. If you need more info I am able to provide. I suspect that the mapping created by searchkick is wrong. For example:

curl -XGET http://HOST/users_development/user/field/username is empty, and should be indexed.

**Comment by netwire88** [comment]
Mongoid 4 changed how it uses BSON. How should I change the `search_data` method to instruct SearchKick to import an id as a string instead of an object? 
```
I'd like:
:group_id=>'54be7f0dbc9da1504c000007'
instead of
:group_id=>BSON::ObjectId('54be7f0dbc9da1504c000007')
```
I tried `.to_s` on `group_id` in `search_data` but that didn't work.

**Comment by ankane** [comment]
@netwire88 Be sure reindex after the change.  Also, please create a new issue if you have any follow up so we're not spamming @tdi
