### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by plasticgit** [ankane/searchkick#187]
is there a way to take advantage of custom document routing on searches as outlined here http://www.elasticsearch.org/blog/customizing-your-document-routing/ ?

**Comment by bogdanovich** [comment]
+1
This video describes how routing could increase performance in user data flow
http://www.elasticsearch.org/videos/big-data-search-and-analytics/

**Comment by ankane** [comment]
Now possible thanks to @bogdanovich
