### ISSUE TITLE
dynamically control index name

### ISSUE THREAD

**Issue by trungpham** [ankane/searchkick#200]
It would be nice if we can dynamically tell searchkick which index to use at indexing time and at querying time.

Something like

```
class Model
  searchkick index_name: :index_name

  def index_name
     return self.galaxy_name
  end
end

Model.search "*", index_name: 'milky_way' #limit searching within the milky way galaxy.
```

**Comment by mmahalwy** [comment]
+1 on this

**Comment by ankane** [comment]
You can now pass a proc to the `index_name` option.

**Comment by mmahalwy** [comment]
Thanks @ankane !!

**Comment by xiaoxuez** [comment]
how to do in indices query with this?
