### ISSUE TITLE
Order by "id"

### ISSUE THREAD

**Issue by incorvia** [ankane/searchkick#203]
I notice that if you try and pass an order by "id" searchkick converts the field that it orders on to "_id".  While this may work for some people it doesn't work for my company as we actually have an "id" field that we need to order on.  Is there a reason that searchkick needs to make this assumption for the user?  

https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L198

**Comment by codener** [comment]
I have experienced a similar issue with Searchkick 0.8.5. My application was passing `order: { 'id' => 'desc' }` to the `search` method, which was completely ignored. Instead, it returned records almost randomly, each request in a new order.

A workaround (at least in 0.8.5) is to wrap the order parameter in an array: `order: [{ 'id' => 'desc' }]`, which will skip the rewrite of `id` and thus sort properly.

I do not know much about Searchkick or Elasticsearch, but it seems like it's a bad idea to sort by `_id`, as per this document: [Elasticsearch _id field](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html).

**Comment by ankane** [comment]
The `_id` field is a string, so it can't be sorted as an integer without scripting (which is disabled in current versions of ES by default). We made the decision to treat `id` and `_id` the same early on, so devs will need to use a different field name if they want to sort.
