### ISSUE TITLE
parallel search queries

### ISSUE THREAD

**Issue by trungpham** [ankane/searchkick#209]
Support firing multiple search queries at the same time.

If query 1 takes 200ms to complete and query 2 takes 300ms complete, then searching sequentially will require 500ms total to complete.

If we had a way to leverage the underlaying http transport such as Curb which already supports making parallel http requests, then at the worst case scenario, it should only take 300ms for both queries to come back.

suggested interface

```
results = Model.multi_search [query_args_1, query_args2, query_args3]
results.each do |result|
  puts result.hits
end
```

**Comment by ankane** [comment]
Multi search is now supported: https://github.com/ankane/searchkick#multi-search
