### ISSUE TITLE
Use 'and' / 'or' or similar in search query

### ISSUE THREAD

**Issue by andersennl** [ankane/searchkick#213]
Hi, I'm already using searchkick but now want to add "advanced" features. I think they are called search filters/operators? I searched in the docs but couldn't find anything. What I'm thinking of are for instance search queries like "my query -without_this +but_with_this", but also 'AND' / 'OR' functionality. I hope it's clear what I mean? Is this doable with this gem? Thanks!

**Comment by azrielh** [comment]
Hi, Was this feature released in version 1.0?

**Comment by ankane** [comment]
No, it wasn't.  No immediate plans for it.

**Comment by ankane** [comment]
Closing as dup of #97 - still not possible.
