### ISSUE TITLE
Synonyms not working

### ISSUE THREAD

**Issue by rctneil** [ankane/searchkick#214]
I have searchkick enabled on my model like so:

  searchkick synonyms: [["dauling", "dualing"],
                        ["dualing", "dueling"],
                        ["uk", "united kingdom"],
                        ["disney", "disneyland"],
                        ["disneyland", "disneysea"],
                        ["4d", "4th Dimension"]],
             word_start: [:name, :park_name, :model, :layout],
             word_end: [:name, :park_name, :model, :layout]

But synonyms don;t seem to be working. When I do a search for them, I don;t get any results back?

Word, start and ends work fine though.

Any ideas?

**Comment by williamweckl** [comment]
Does not work for me either. 

Using Searchkick 1.0.3, Elasticsearch 2.1.0.

**Comment by ankane** [comment]
Thanks for the great examples @williamweckl. Fixed on master.

**Comment by williamweckl** [comment]
Thank you!

**Comment by MK-42** [comment]
If I understood the previous discussion correctly, I need to put stemmed strings into the `synonyms`-field?
I have a csv-file that i would like to use as synonyms. Is there a way to stem them all according to the same rules that searchkick uses? That would be neat.
