### ISSUE TITLE
Faraday::TimeoutError: Net::ReadTimeout when reindexing

### ISSUE THREAD

**Issue by jeffquach** [ankane/searchkick#222]
Hi,

When I try to reindex my data it keeps on giving me an error saying:

"Faraday::TimeoutError: Net::ReadTimeout"

I've gotten this error twice when running: "Product.reindex" and "Product.reindex" within a rake task

Does anybody know what I can do to get rid of this problem?

Thanks!

**Comment by diogolmenezes** [comment]
I had this problem and when my calculate indices manually, everything went back to work

`rake searchkick:reindex:all`

or if you want item by item

```
Product.reindex
User.reindex

```
