### ISSUE TITLE
Search nested objects

### ISSUE THREAD

**Issue by gustaflindqvist** [ankane/searchkick#223]
How far away is functionality as search nested objects? Is there a way to do it anyway, workaround?

**Comment by samur-vonq** [comment]
+1

**Comment by raphaelcuba** [comment]
This issue refer to this feature?
https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-query.html

**Comment by ankane** [comment]
This is now possible: https://github.com/ankane/searchkick#nested-data
