### ISSUE TITLE
Default synonyms

### ISSUE THREAD

**Issue by adelevie** [ankane/searchkick#232]
Hi, thanks for writing this awesome gem. We're finding it quite useful at [18F](https://18f.gsa.gov).

I see that searchkick makes it easy to hook in custom synonyms, but I'm wondering if "regular" synonyms are getting indexed by default? And if not, how would I get them working? I know ES provides native synonym indexing--I'm just wondering if searchkick utilizes this feature.

**Comment by ankane** [comment]
Cleaning up issues.
