### ISSUE TITLE
Facets not updated when using where method 

### ISSUE THREAD

**Issue by sennor** [ankane/searchkick#236]
Example this: 
`@products = Product.search "#{params[:search]}", where: {brand: params[:brand]}, facets: [:new_price, :brand, :category_name], smart_facets: true, suggest: true, highlight: true, per_page: 20`

Returns the same facets as this search: 
`@products = Product.search "#{params[:search]}", facets: [:new_price, :brand, :category_name], smart_facets: true, suggest: true, highlight: true, per_page: 20`

I would expect the facets to be different.

**Comment by SachinGoyal** [comment]
It shows wrong facets count as smartfacets not working on where conditoins


Property.search params[:query], where: conditions , facets: {bedrooms: {ranges: bedroom_ranges} ,price: {ranges: price_ranges},bathrooms: {ranges: bath_ranges},area: {ranges: floor_ranges}} , smart_facets: true

My elasticsearch Version is 1.5.1

Smartfacets are not working in that query .

**Comment by jaredcwhite** [comment]
I can confirm this issue, and I can modify the data that gets passed to elasticsearch so that it does return the correct facet count for the where conditions. There are missing where conditions being added to the facet filters.

**Comment by SachinGoyal** [comment]
Thanks for your suggestion
Its working in that way

**Comment by hyfen** [comment]
In addition to using ```smart_facets:true```, try using a where condition hash with string keys instead of symbols. ie. ```where: {"condition" => "value"}```
