### ISSUE TITLE
Support for boosting results by recency?

### ISSUE THREAD

**Issue by cdimartino** [ankane/searchkick#241]
Hi,

I've been trying to get this to work in searchkick for some time now, and continue to fail :(

I have a corpus of about 600K news articles indexed that I need to search and boost the results based on recency.  I've attempted numerous combinations of boosting (using the various boost_ methods) on date_added etc but to no avail.  The only solution that worked was to use the sort methods, but that ended with very un-relevant search results at the top because they were more recent.

Any hints?  I dont doubt that ES can handle it...  just not sure how to communicate it to it!

**Comment by peddinti** [comment]
I tried using this but i am getting the following error:
Unknown field [create_time]

Is this because my field is a DateTime instead of Date? does this only work for DateFields?

**Comment by mahemoff** [comment]
Via #300, I found this can be done directly using boost_by_distance. It works for any range related data, including durations, not just physical distance.

```
Order.search 'coffee', boost_by_distance: {
  field: :ordered_at,
  function: :gauss,
  origin: Time.now,
  scale: '1w',
  offset: '0',
  decay: 0.5
}
```

(Note I have date fields indexed as Time type, not sure if it will work w/ standard Rails timestamps.)

**Comment by zerokol** [comment]
@mahemoff , thanks, your discovery was amazing!

**Comment by mahemoff** [comment]
Thanks @zerokol.

Note that `boost_by_distance` doesn't support a list arg (unlike `boost_by`, which can take a list or a hash), so you can only boost by one variable this way. If you want to boost by more than one distance factor (e.g. boost by both age and date of last publication), you would still need the workarounds posted earlier in this thread.

Hopefully `boost_by_distance` will accept a list in the future.

**Comment by ankane** [comment]
Happy to accept a `boost_by_recency` option to make this easier for people.

**Comment by Tybot204** [comment]
:+1: to adding a custom Searchkick option for this. I have a situation where I need to boost by both location and time. My application has a list of events with locations and times which need to be "sorted" by both attributes simultaneously.

No one cares about events starting in 5 minutes on the other side of the world or events starting in 5 years next door!

**Comment by pplant** [comment]
Is there a way to add a scale factor to 

Order.search 'coffee', boost_by_distance: {
  field: :ordered_at,
  function: :gauss,
  origin: Time.now,
  scale: '1w',
  offset: '0',
  decay: 0.5
}

kind of hash?

**Comment by pplant** [comment]
A brief review of the library code revealed that this is not possible yet. Therefore I implemented an easy way to achieve this and created a pull request [https://github.com/ankane/searchkick/pull/1028](url)

**Comment by TechCanuck** [comment]
https://github.com/ankane/searchkick/pull/1028 - the previous link didn't work

**Comment by bbugh** [comment]
To confirm for anyone else reading this, you can use Rails timestamps just fine. The example above scale unit ("w") raises an error, so we just use "7d" instead. This works great for us:

```ruby
boost_by_distance: {
  field: :created_at,
  origin: Time.current,
  scale: '7d',
  decay: 0.5,
  factor: 1500
}
```

**Comment by ankane** [comment]
https://github.com/ankane/searchkick/commit/2fd44addd3ba4d72468469b7782158323a6e666f
