### ISSUE TITLE
multi-index vs. multi-model searches: what are they and how to

### ISSUE THREAD

**Issue by mitchell370** [ankane/searchkick#244]
Apologies for the beginner question. I'm new to rails (and programming). I asked this on stackoverflow to not much success. 

I have read several docs about multi-index searches for searchkick. I have a general confusion regarding multi-index vs. multi-model searches. I don't know if multi-index allows for multi-model searches or if they are different things?

I have a basic marketplace model. Devise for users. Users can create listings. Each listings shows: user_name (which is from user model); product_name, product_description, product_price (all from listing_model).

I have been successful in setting up searchkick to search for product names. It's working great.

Here is my issue: I want to allow users to search by user name too. I'm struggling with adding user_name to be able to be searched. I'm confused how to integrate the user model to the searches, mainly because the way devise is set up. I don't have a page that shows a list of all my users among other pages that are needed to set up the searchkick page. I've seen some pages that discuss multiple indexes on search and I've tried the solutions they've posted, as well as the documentation on searchkick, but I think I'm missing some required components to my user model (because of devise).

I've tried this solution https://github.com/ankane/searchkick/issues/74 but it gives me an undefined method for "users"

I would appreciate any info on how to add the ability to search for user_name from my devise to my current model that searches product_name on my listing model

**Comment by khacluan** [comment]
thanks :+1:

**Comment by ankane** [comment]
Cleaning up issues
