### ISSUE TITLE
Migrate Facets to use Aggregations

### ISSUE THREAD

**Issue by ajturner** [ankane/searchkick#247]
It appears that [ElasticSearch facets are deprecated](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-facets.html) and they suggest moving instead to [use aggregations](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations.html)

Noting that SearchKick should move to deprecate the `facets:` option and provide interface and examples to aggregations.

**Comment by ankane** [comment]
Added in 1.0.
