### ISSUE TITLE
Unsure about reindex and when it should be used

### ISSUE THREAD

**Issue by jakcharlton** [ankane/searchkick#251]
I have a MongoID backed system, and largely dynamic attributes (via search_data, via serialized_hash) was doing a fine job - it seems to get all the custom attributes we have on our models (at least well enough for a general search)

Apparently randomly I just got an error on save of a Contact with:

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":"MapperParsingException[failed to parse [emails]]; nested: ElasticsearchIllegalArgumentException[unknown property [_id]]; ","status":400}
```

This was the first time I had added "emails" to that record, but others had them already - I had never set "emails" on that record to be another type which is what all the ES documentation suggests is at fault

To solve that I had to use Contact.reindex - Contact.find(id).reindex just re raised the exception

Is this some weird occurrence cause in my dev environment, or are there cases where data that is empty on one index (as emails were here) can get wrongly mapped?  Or am I looking in the wrong place?

I considered pushing indexing to Sidekiq so that I could catch exceptions outside the user flow and then force a reindex on the Model but this seems a lot of workaround if this error isn't a normal possible path

Any thoughts?

**Comment by ankane** [comment]
Cleaning up issues
