### ISSUE TITLE
Search in multiple models and other features

### ISSUE THREAD

**Issue by Linuus** [ankane/searchkick#257]
Hi

I use Tire, in Rails, today I want to upgrade to Elasticsearch 1.0 so I either have to migrate to the elasticsearch gems or Searchkick. I have some questions though.

1. Multiple models.
Can I search multiple models at the same time and get a mixed list of results ordered by their score?
I.e. I search for "Foo" and I get both `User` and `Article` mixed in the results. (We do this today using `Tire.search`)

2. Search multiple indexes in one request.
I want to search multiple indexes and have it return results grouped by its type, ordered by the score.
Essentially the same as above but it returns the results grouped. This should be done in _one_ request. (We use `Tire.multi_search` for this today)

3. No loading of ActiveRecord records
I don't want to load my AR records. I just want to use the data returned from ES as that is faster than loading the data from the application DB as well.

4. Does Searchkick in fact have Elasticsearch 1.x support?

Are these features supported today?

**Comment by pushmatrix** [comment]
Any update on this?

**Comment by ericraio** [comment]
Any update on this?

**Comment by jessiahr** [comment]
It looks like this has been added to Searchkick

```
Searchkick.search "milk", index_name: [Product, Category]
```

Just above here in the docs -> https://github.com/ankane/searchkick#large-data-sets

**Comment by MrHubble** [comment]
https://github.com/ankane/searchkick#multiple-indices

**Comment by ankane** [comment]
Yes, added.
