### ISSUE TITLE
Strange highlighting behaviour

### ISSUE THREAD

**Issue by chumakoff** [ankane/searchkick#265]
If a searched word is found two times in a text, then the searchkick highlights these two words and all other words between them. For example, when I search the word _'hello'_ in the text _'...hello world hello...'_, the highlighted result is _'...<em>hello world hello</em>...'_, but I expect that it should be _'...<em>hello</em> world <em>hello</em>...'_. How to avoid this strange behaviour ?

**Comment by jatska** [comment]
The same thing happens for me (searchkick 0.8.5).

In my model:
```
class Localization < ActiveRecord::Base
...

  scope :search_import, -> { includes(:category) }

  searchkick highlight: [:content]

  def search_data
    {
      title: title,
      content: content,
      lang: lang
    }
  end
```

Controller query: 
```
 @results = Faq::Localization.search params[:q]
         fields: [:title, :content],
         highlight: true
```
And in view:
```
- @results.with_details.each do |result, details|
  %div{
    %h4= link_to result.title, category_path(result.category)
    %span
      = details[:highlight][:content].html_safe
```

**Comment by cabouffard** [comment]
@jacekgrzybowski I am having the same issue, how have you fixed it?

**Comment by chumakoff** [comment]
I just started using this https://github.com/ankane/searchkick#highlight   It works fine.
