### ISSUE TITLE
Support for multi tenancy

### ISSUE THREAD

**Issue by tommi-lew** [ankane/searchkick#268]
Hi @ankane , I'm currently using Apartment gem for a multi tenancy app. Can searchkick support multi tenancy? By default, I can see that it is overwriting indexes whenever the reindexing runs in different tenants.

**Comment by Xosmond** [comment]
@tiagoamaro thank you. @ankane please think about this. This feature would make a great advance for big software solution.

**Comment by ankane** [comment]
Support for multi-tenancy has improved since 2014 :) Check out https://github.com/ankane/searchkick#multi-tenancy
