### ISSUE TITLE
Searchkick boost exact matches

### ISSUE THREAD

**Issue by scottmascio2115** [ankane/searchkick#269]
I have 15,000 courses and I would like to boost the title of each class so exact matches of a class are boosted above everything else.

When I do Course.seach_kick('theory of interest' , 1) The correct search is returned with the course 'theory of interest' as the first result.

However, when I do Course.search_kick('theory of interest 3618', 1)
3618 being the catalog_number, no results are returned. I expected the theory of interest course to be returned, and returned first. It seems the search is looking for the complete string 'theory of interest 3618' be included in the title of the course.

I understand 'and' is the default operator, Is it a requirement that I have to use the 'or' operator? I am hesitant to use the 'or' operator because of the unexpected results.

Thanks, I really enjoy using the gem.

search method:

def self.search_kick(query, page)
  search(query,
         fields: ["title^10", "description", "crse_id", "subject", "catalog_number" ],
         facets: [:subject],
         misspellings: false,
         page: page,
         per_page: 20
         )
end

def search_data
  {
    title: title,
    description: description,
    crse_id: crse_id,
    subject: subject,
    catalog_number: catalog_nbr
  }
end

**Comment by ankane** [comment]
Cleaning up issues

**Comment by oyeanuj** [comment]
@ankane Sorry to restart a discussion on a closed issue, but I was trying to solve the same problem and can't find the right way to set up the query as well. Any pointers would be much appreciated :)

If searching for 'wheat bread', lets say, I'd would want the following order, without giving up phrase matching:
1. wheat bread.
2. whole wheat bread.
3. ancient wheat bread.

At this point, 'wheat bread' shows up below a couple of other results.

@xldenis @emilyemoss if you did manage to solve this, I'd appreciate if you could share the solution!

**Comment by ankane** [comment]
Hey @oyeanuj, I added a basic test for this and it may work as is. I'd recommend doing an explain to see how it's scored: https://github.com/ankane/searchkick#debugging-queries

**Comment by oyeanuj** [comment]
@ankane That was helpful. I'll dig in to the `explain` option and see why they might be scored differently on my end.

However, I added a couple of cases to the test suite which I imagined would pass but fail - (where the term matches the first word exactly) https://github.com/ankane/searchkick/pull/804. 

Can you take a look to see if that is the expected result for you? Currently, those cases are failing.

**Comment by ankane** [comment]
Not sure I follow the intended behavior. The exact match shows up first in both examples, but it sounds like you're asking for something else.

**Comment by oyeanuj** [comment]
I should have clarified that the next question was connected but different from the first question. In the following:

```rb
store_names ["Wheat Bread", "Whole Wheat Bread", "Wheat Bread From Mars"]
assert_order "wheat bread", ["Wheat Bread", "Wheat Bread From Mars", "Whole Wheat Bread"], match: :phrase
```

Would you expect "Wheat Bread From Mars" to show up before the "Whole Wheat Bread" because it is matching the initial phrase?

Thanks for your patience on this!

**Comment by ankane** [comment]
Elasticsearch's phrase match just means the words show up in the same order - "wheat", then "bread". It doesn't score based on how close to the front of the word the match is.

**Comment by oyeanuj** [comment]
@ankane Got it, thank you for the clarification! :) I'll get back to analyzing the `explain` statement.
