### ISSUE TITLE
Reindex of 40,000+ documents getting time-out error [Faraday::TimeoutError: Net::ReadTimeout]

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#286]
I'm reindexing a table and getting a TimeoutError.  The indexing is working (I can see the document count increasing until the error occurs).  The error happens 5-30 minutes into the re-indexing.  I've tried changing Searchkick.timeout to 120 but it doesn't help.

irb(main):025:0> Job.reindex
Faraday::TimeoutError: Net::ReadTimeout
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /app/vendor/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /app/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /app/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
	from /app/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
... 11 levels...
	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `block in instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `instrument'
	from /app/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.3/lib/searchkick/logging.rb:46:in `import_with_instrumentation'
	from /app/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.3/lib/searchkick/reindex.rb:64:in `block in searchkick_import'
	from /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/relation/batches.rb:76:in `find_in_batches'
	from /app/vendor/bundle/ruby/2.1.0/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/relation.rb:70:in `find_in_batches'
	from /app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.5/lib/active_record/querying.rb:8:in `find_in_batches'
	from /app/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.3/lib/searchkick/reindex.rb:63:in `searchkick_import'
	from /app/vendor/bundle/ruby/2.1.0/gems/searchkick-0.8.3/lib/searchkick/reindex.rb:32:in `reindex'
	from (irb):25
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
	from /app/bin/rails:4:in `require'

**Comment by gbarillot** [comment]
Thanks, solved my problem using a RDS postgres instange on AWS

**Comment by mninaut** [comment]
@zealot128 ty

**Comment by ankane** [comment]
Cleaning up issues.

**Comment by diogolmenezes** [comment]
I had this problem and when my calculate indices manually, everything went back to work

`rake searchkick:reindex:all`

or if you want item by item

```
Product.reindex
User.reindex

```

**Comment by alishahpakneeds** [comment]
Reindexing Project...
rake aborted!
Faraday::TimeoutError: Net::ReadTimeout

Net::ReadTimeout: Net::ReadTimeout

IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block

Tasks: TOP => searchkick:reindex:all
(See full trace by running task with --trace)
