### ISSUE TITLE
Inconsistent Analyzer Configuration

### ISSUE THREAD

**Issue by granolocks** [ankane/searchkick#306]
Hello, I am having a problem with searchkick. We are not customizing our implementation extensively but experiencing a strange issue where in some random and inconsistent situations the searchkick analyzers seem to removed from an index causing things like facets to be tokenized improperly.

In the situations where facets are rendering improperly the ES settings look like the following: 

```
irb(main):006:0>  puts JSON.pretty_generate(JSON.parse(`curl -XGET $ELASTICSEARCH_URL/clients/_settings`))                                                                                                                                     
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166  100   166    0     0   7157      0 --:--:-- --:--:-- --:--:--  7545
{
  "clients_20141015183217396": {
    "settings": {
      "index": {
        "uuid": "o3_3xwIWR_OnfQXzKlrIxw",
        "number_of_replicas": "2",
        "number_of_shards": "5",
        "version": {
          "created": "1010299"
        }
      }
    }
  }
}
```

This issue will come and go on different models with seeming total randomness.
We are using Searchkick 0.8.3 & ES 1.3.4

**Comment by ankane** [comment]
Hey @granolocks, sorry this was never follow up on. Feel free to reopen with more examples if it's still happening in the latest version.
