### ISSUE TITLE
Incremental indexing vs bulk indexing?

### ISSUE THREAD

**Issue by rajatgarg79** [ankane/searchkick#307]
Now that we have 17 million products, indexing takes a long time and if it gets interrupted for any reason, our users suffer.

Is there a way to do say, Product.reindex(:id>100000) - such that data is added to same index vs creating a new index for it?

Any pointers will be greatly appreciated.

**Comment by Chocksy** [comment]
@rajatgarg79 Have a look at this gist also: https://gist.github.com/Chocksy/6efa4833989f51e46fca

**Comment by ankane** [comment]
For future readers, there's now a `resume` option if your reindex is interrupted.
