### ISSUE TITLE
Accessing nested models with identically named fields

### ISSUE THREAD

**Issue by jmwelch** [ankane/searchkick#314]
Hi y'all,

Phenomenal gem, I have a few functionality questions!

Suppose I have the following nested models:

``` ruby
class Student < ActiveRecord::Base
  searchkick
  def search_data
    {
      name: name
      city: city,
      plan: student_plan
    }
  end
  has_one :student_plan
end

class StudentPlan < ActiveRecord::Base
  belongs_to :student
end
```

`Student.first.search_data` yields:
`=> {:name=>"John", :city=>"Atlanta", :plan=>#<StudentPlan id: 1, city: "Los Angelos", state: "California", country: "USA", student_id: 1>}`

`Student.search "*", where:{city:"Atlanta"}` gives me the correct student.
`Student.search "*", where:{state:"California"}` gives me the correct student.
`Student.search "*", where:{city:"Los Angeles"}` does not return anything.

I'm assuming this is because there are two `city` fields being indexed. So my question is how do I reference the correct `city`? Can I do something like:
`Student.search "*", where:{plan:{city:"Los Angeles"}}`
Or am I going to have to define the mapping per field in the associated model? Like the following:

``` ruby
def search_data
    {
      name: name,
      city: city,
      student_plan_city: plan.city,
      plan: student_plan
    }
end
```

<hr>

Also, for my second question, is there a way to change the search function to implement the query string query functionality from ES? So that searches like:
`quick brown`
`quick OR brown`
`"quick brown"`
adjust the operator between them?

Thanks so much!

**Comment by Neodelf** [comment]
Hi, @ankane !
>https://github.com/ankane/searchkick/issues/314#issuecomment-61438213
>nested searches aren't supported yet.

This feature doesn't work still?
I need search in `belongs_to` model with `:word_middle` option.
Thanks!
