### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#326]
It looks like search queries are case _sensitive_ by default. (Using 0.8.5)

``` ruby
results = Model.search('*', order: {label: :asc})
results.map(&:label)
#=> ["FIFID", "WWWWW", "souf", "structure", "xj123"]
```

Wondering what the best way to add this option is? I see a page in the [ES docs describing how to create an analyzer for case sensitive search](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/sorting-collations.html#case-insensitive-sorting), but I'm not sure how that maps to Searchkick world.

**Comment by SxDx** [comment]
Any news on how to accomplish this?

**Comment by tyler-vincent** [comment]
Wondering this as well. We're fine with case sensitive search but the results should really be sorted case insensitive.

**Comment by edslocomb** [comment]
Bump - most of our clients seem to want case-insensitive search/result-ranking

**Comment by ankane** [comment]
For clarity for future readers:

1. Search is case-insensitive.
2. Ordering is case-sensitive. Make it case-insensitive requires indexing an extra field as documented in the Elasticsearch link above. This is not something I'd like to support, so I'd suggest using custom mapping/searching if you need this.
