### ISSUE TITLE
Search on Array

### ISSUE THREAD

**Issue by confact** [ankane/searchkick#329]
Hi!

I used elasticsearch to search on a array in a document. I wrote station_songs.name to search on every artist name. And similar for the song title. How can i do this with Searchkick?

I do this now:

```
@search = Station.search params[:search], fields: [{name: :word_start}, {website: :word_start}, {station_songs.name: :word_start}]
```

And it fails of course on station_songs.name.

Is this possible to do?

**Comment by williamweckl** [comment]
+1

**Comment by rishijain** [comment]
I think you need to index data using the `search_data` method like this

```
def search_data
  {
    station_songs_names: station_songs.collect(&:name)
  }
end
```

and should also set the field `station_songs_name` in mappings.

**Comment by chamnap** [comment]
@rishijain, can you explain how to `put station_songs_name` in mappings?

**Comment by ankane** [comment]
Cleaning up stale issues
