### ISSUE TITLE
Does Searchkick support using Regex queries?

### ISSUE THREAD

**Issue by vnu** [ankane/searchkick#330]
I am trying to do some regex searches on few particular fields.
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html

I tried regex in options, but looking through your code seems like its not currently supported.

**Comment by diasks2** [comment]
+1 This would definitely be a cool addition.

**Comment by ankane** [comment]
Just added basic support. Remember that regular expressions much match the entire string in Elasticsearch.

```ruby
Product.search "test", where: {color: /.+ blue/}
```

Let me know how it goes.

**Comment by diasks2** [comment]
Works well. Thanks for adding this.

**Comment by acebruins** [comment]
@ankane I've tried that but doesn't work :(

`Provider.search params[:q], where: {location: /.+ jakarta/}`
