### ISSUE TITLE
Could I configure the analyzer while querying ?

### ISSUE THREAD

**Issue by alChaCC** [ankane/searchkick#333]
Since, our visitor usually use "Traditional Chinese" as search term.  I need to optimize the search results.

Below is my Product model 

```
searchkick merge_mappings: true, mappings: {
    product: {
      properties: {
        product_cname: {type: "string", analyzer: "cjk"},
        product_ename: {type: "string", analyzer: "cjk"},
        product_description: {type: "string", analyzer: "cjk"}
      }
    }
  }, autocomplete: ['product_cname', 'product_ename']
```

And below is my search method in product model 

```
def self.searchkick(query,sort,page)
    search "#{query}",
    order: [{"#{sort}" => "#{sort == "product_price_min"? 'asc' : 'desc'}".to_sym},{_score: :desc }], 
    page: page, 
    per_page: 5
end
```

then here is how the query post to server

```
curl http://localhost:9200/products_development/_search?pretty -d '{"query":{"dis_max":{"queries":     [{"match":{"_all":{"query":"高絲 專櫃","operator":"and","boost":10,"analyzer":"searchkick_search"}}},  {"match":{"_all":{"query":"高絲 專櫃","operator":"and","boost":10,"analyzer":"searchkick_search2"}}},  {"match":{"_all":{"query":"高絲 專  櫃","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search"}}},  {"match":{"_all":{"query":"高絲 專  櫃","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search2"}}}]}},"si  ze":5,"from":50,"sort":[{"product_urcosme_exp":"desc"},{"_score":"desc"}],"fields":[]}' 
```

However, the results are weird, some products not related to "雅詩蘭黛", but still show in the results.

I think the problem might related to  analyzer

Since using searchkick_search2, it will cut words to 4 words.

```
Product.searchkick_index.tokens("雅詩蘭黛", analyzer: "searchkick_search2")
 => ["雅", "詩", "蘭", "黛"]
```

So, I want to change the analyzer to "CJK". 

```
 Product.searchkick_index.tokens("雅詩蘭黛", analyzer: "cjk")
 => ["雅詩", "詩蘭", "蘭黛"]
```

I try to configure it like these 

1:  

```
 def self.searchkick(query,sort,page)
    search "#{query}",
    order: [{"#{sort}" => "#{sort == "product_price_min"? 'asc' : 'desc'}".to_sym},{_score: :desc }], 
    page: page, 
    per_page: 5, execute: false
    query.body[:query] = { "analyzer" => "cjk"}
    query.execute 
end
```
1.   query = search "#{query}",
         order: [{"#{sort}" => "#{sort == "product_price_min"? 'asc' : 'desc'}".to_sym},{_score: :desc }], 
         page: page, 
         per_page: 5, execute: false
         query.body[:query] = { 
                               filtered: {
                                 query: {
                                   bool: {
                                     must: [
                                       multi_match: {
                                         query: query,
                                         type:  "cross_fields",
                                         fields: ['product_cname', 'product_ename','product_description','product_keyword'],
                                         operator:   "and", 
                                         analyzer:   "cjk"
                                       }
                                     ],
                                   should: [
                                     { match: { "product_description" =>  query}},
                                     { match: { "product_keyword" => query }}
                                   ]
                                   }
                                 }
                               }
                            }
         query.execute

But both are not working ~~

So, How can I do that ?

**Comment by ankane** [comment]
Cleaning up issues. For future readers, see #488.
