### ISSUE TITLE
Can't Reindex Models when using UUIDs as primary key

### ISSUE THREAD

**Issue by ejlax** [ankane/searchkick#336]
rake searchkick:reindex CLASS=User throws:

ActiveRecord::StatementInvalid: PG::Error: ERROR:  operator does not exist: uuid >= integer

This occurs when UUIDs are the primary key (:id) for models.

FullTrace:
ActiveRecord::StatementInvalid: PG::Error: ERROR:  operator does not exist: uuid >= integer
LINE 1: ...LECT  "users".\* FROM "users"  WHERE ("users"."id" >= 0) ORDE...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT  "users".\* FROM "users"  WHERE ("users"."id" >= 0) ORDER BY "users"."id" ASC LIMIT 1000

PG::Error: ERROR:  operator does not exist: uuid >= integer
LINE 1: ...LECT  "users".\* FROM "users"  WHERE ("users"."id" >= 0) ORDE...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by ankane** [comment]
Cleaning up issues. Thanks for reporting back with your solution. If you have any more updates know that you've been running it for a while, let us know!
