### ISSUE TITLE
Query Builder in searchkick

### ISSUE THREAD

**Issue by dealshook** [ankane/searchkick#338]
How can I join different where clauses query builder style in searchkick

@product = Product.all

```
unless request.end_date.nil?
    @product = @product.search, where('created_at <= ?', request.end_date)
end 

unless request.max_price.nil?
    @product = @product.search, where('price <= ?', request.max_price)
end 

@product
```

If request has just one parameter it goes well, if it has both " request.max_price" and "request.end_date" it throws an error

**Comment by ankane** [comment]
Hey @dealshook, sorry this wasn't responded to. For future readers, you can use:

```ruby
where = {}
unless request.end_date.nil?
  where[:created_at] = {lt: request.end_date}
end

# more conditions

Model.search(term, where: where)
```
