### ISSUE TITLE
Completing an interrupted reindex

### ISSUE THREAD

**Issue by sebular** [ankane/searchkick#342]
I'm running into some issues with reindexing a very large dataset.  I've got about 6.5 million records and about 35 attributes getting indexed for each record.  This takes multiple days to reindex, and though I'm attempting to reduce the number of attributes to improve speed, this is what I've got to work with at the moment.

The problem is that when I run `rake searchkick:reindex CLASS=Product` the ruby process keeps using more memory until the OS finally decides to kill it.  Memory leak issues aside, this has consistently interrupted my reindex at about 6 million, relatively close to the finish line.

So I wrote a small script to finish indexing the .5 mil remaining records, which lets me pass in a starting point:

``` ruby
namespace :searchkick do
  desc "maybe reindex without running out of memory?"
  task :altindex, [:start_index, :batch_size] => :environment do |t, args|
    count = Product.count
    start = args[:start_index].to_i
    step = (args[:batch_size] || 1000).to_i
    puts "Starting reindex at #{start} with batch size of #{step}..."
    (start..count).step(step) do |i|
      begin
        range = (i..(i+(step - 1)))
        product_list = Product.where(:id => range)
        product_list.each { |p| p.reindex }
        puts range
      rescue
      end
    end
  end
end
```

This worked except for a new problem I didn't see coming: every Product that got indexed by this method was placed in a new named elasticsearch index.  So if I look at the ES indices list, I have something like this:

```
green open products_production_20141201190220281      5 1  643053 0   3.2gb   1.6gb
green open products_production_20141201192854738      5 1 5950000 0  23.4gb  11.7gb
```

And now when I try to search, only the products from the smaller index are returned.  The slightly older, larger index seems like it's being ignored entirely.

It seems like I have a few ways to attack this.  Should I try to create an elasticsearch script to manually merge the two indices?  Should I just try to run the entire reindex using my method, which doesn't seem to have the same memory leak issue as `searchkick:reindex`, but which I'm pretty sure runs more slowly?  Or would it be more productive to focus on reducing the amount of data getting indexed so that the process runs faster?

In a related question, once this is in production I don't intend to do a full reindex very often.  In terms of reindexing individual records, how do I know if calling Product.find(x).reindex is going to use the existing products_production index, or if it's going to create a new index?

**Comment by ankane** [comment]
Cleaning up issues. For future readers, a few things have improved since this was created.

1. Searchkick now has a `resume: true` option for reindexing
2. `Model.where(some_conditions).reindex` reindexes into the existing index instead of creating a new one
