### ISSUE TITLE
searchkick 0.8.5, mongoid 4, Searchkick::Results returns empty array

### ISSUE THREAD

**Issue by Prabandham** [ankane/searchkick#345]
The latest searchkick 0.8.5 with mongoid 4  returns results as empty array, 

I guess the reason is because in the results.rb (https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb) the 'results_query',
 'records' respond to all of these (:primary_key, :all, :queryable and :unscoped).

**Comment by ankane** [comment]
Cleaning up issues
