### ISSUE TITLE
Ignore apostrophe

### ISSUE THREAD

**Issue by edorgeville** [ankane/searchkick#346]
Hi, 
Is it possible to ignore apostrophe ? So the search for "information" returns the result named "Livre d'information".
Thanks ! :octocat:

**Comment by mengqing** [comment]
You'll need to use the word_delimiter token filter
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html

Just setup a custom analyzer with that filter

**Comment by th3m4ri0** [comment]
Will try and report back ! :) Thanks.

**Comment by jimmybaker** [comment]
Any news here? If this worked, can you post how you set this up with search kick? Are there options for providing that to searchkick?

**Comment by jimmybaker** [comment]
I'm having a similar issue when someone searches "Men's Shirts" I get nothing but searching "Mens Shirts" returns results. If anyone has a good fix for this (other than modifying the query passed in), I would love to see it.

**Comment by th3m4ri0** [comment]
Can't quite remember if I applied the fix, the code changed a lot in the meantime. I am no longer working on the website from back then but seeing the current code in the model: 
```ruby
 searchkick  language: "French",
                word_middle: [:title],
                fields: ["title^10", "authors^5", "secondary_authors^4", "body^2"]
```   
It's been a long time (2 years ha!) since I opened this issue, I can't quite remember what happened since.

**Comment by ankane** [comment]
Cleaning up stale issues
