### ISSUE TITLE
Associations are not synced to the index automatically

### ISSUE THREAD

**Issue by scrol** [ankane/searchkick#352]
Fields in the Model are getting indexed and sync automatically with the db when updated, created or deleted but associated fields are not automatically indexed. When reindexed associated fields are synchronised.

Model: event.rb
== Schema Information

Table name: events

 id                    :integer          not null, primary key
 title                 :string(255)
 webpage               :string(255)
 description           :text
 startdate             :date
 enddate               :date
 deadline_date         :date
 deadline_webpage      :string(255)
 global_scope          :boolean
 registration_webpage  :string(255)
 online                :boolean
 series                :string(255)
 non_monetary_benefits :boolean
 fee_startvalue        :string(255)
 fee_endvalue          :string(255)
 currency              :string(255)
 created_at            :datetime
 updated_at            :datetime
 event_type            :integer

def search_data
      as_json  
      attributes.merge(
        city_name: address.try(:city).try(:name),
        city_id: address.try(:city).try(:id),
        country_id: address.try(:city).try(:state).try(:country).try(:id),
        country_name: address.try(:city).try(:state).try(:country).try(:name),
        country_filter: address.try(:city).try(:state).try(:country).try(:name),
        sector_ids: sub_sectors.map(&:sector_id).uniq,
        sub_sector_names: sub_sectors.map(&:name),
        function_ids: sub_functions.map(&:function_id).uniq,
        sub_function_names: sub_functions.map(&:name),
        tag_ids: tag_uses.map(&:tag_id),
        tag_names: tags.map(&:name),
        organiser_ids: organiser_uses.map(&:organiser_id),
        organiser_names: organisers.map(&:name),
        scope_countries: scope_countries.map(&:country_id),
        scope_country_names: countries.map(&:name),
        guest_names: persons.map(&:name)
      )
    end

Event.search_data results:

 => {"id"=>1, "title"=>"Event 1", "webpage"=>"", "description"=>"", "startdate"=>Sun, 23 Nov 2014, "enddate"=>Sun, 23 Nov 2014, "deadline_date"=>Sun, 30 Nov 2014, "deadline_webpage"=>"", "global_scope"=>nil, "registration_webpage"=>"", "online"=>nil, "series"=>nil, "non_monetary_benefits"=>nil, "fee_startvalue"=>"0", "fee_endvalue"=>"50", "currency"=>"$", "created_at"=>Sun, 23 Nov 2014 11:04:24 UTC +00:00, "updated_at"=>Sun, 23 Nov 2014 11:04:24 UTC +00:00, "event_type"=>1, :city_name=>"Aboud Ben Ayed", :city_id=>1, :country_id=>1, :country_name=>"Algeria", :country_filter=>"Algeria", :sector_ids=>[], :sub_sector_names=>[], :function_ids=>[], :sub_function_names=>[], :tag_ids=>[], :tag_names=>[], :organiser_ids=>[], :organiser_names=>[], :scope_countries=>[], :scope_country_names=>[], :guest_names=>[]}

**Comment by cesargomez89** [comment]
this is not working for me
when I reindex my associations in this way:
```ruby
  def update_indexes
    profiles.reindex
    cats.reindex
  end
```

Only is working when I reindex everything

```ruby
  def update_indexes
    Profile.reindex
   Cat.reindex
  end
```
