### ISSUE TITLE
Partial match not working for phone number field

### ISSUE THREAD

**Issue by sansarp** [ankane/searchkick#353]
When the query is specified as given below i.e provided with the exact phone number(10 characters) match then searchkick gives the result.
User.search("9898989898", fields: [{first_name: :word_start}, :middle_name, :last_name, :phone_number])

But when partial query is provided i.e without exact match i.e say "9898" is only specified then no search result is obtained.
The query is in string format for first_name, middle_name and last_name whereas numeric for phone_number. It works perfect for first_name case. In my model file i have included this:
searchkick word_start: [:first_name], autocomplete: [:first_name] 
as i need auto suggestion as per name basis and it should work when phone_number is supplied as well.

@ankane  Can you please help me out to figure out what i am missing.

**Comment by sansarp** [comment]
I did this in user model 
searchkick word_start: [:first_name, :middle_name, :last_name, :email, :phone_number]

In search method
User.search(search_term, fields: [{first_name: :word_start}, {middle_name: :word_start}, {last_name: :word_start}, {phone_number: :word_start}, {email: :word_start}]) where search_term is a query term supplied by user

This worked fine when search for the phone_number(9898989898 in database for the newly created user) with query term 9898 is supplied for a significant number of times (say 10 times and by this time the phone_number might have higher weightage, dont know exactly :-) ). I am wondering why it gives result for the first_name only but takes time for phone_number field.

Is that the problem of indexing? @ankane I am puzzled here. 
Thank you for your time going through my problem. :-)

**Comment by jbmyid** [comment]
Its not working properly for me.
Have indexed the phone no. as string.
When i search full phone no. it gives result, but not partially. When i search with 9 digit it woks. Dont know exactly what to do.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
