### ISSUE TITLE
Retain x number of indexes on swap.

### ISSUE THREAD

**Issue by incorvia** [ankane/searchkick#356]
At my company, we ran into an issue that caused a partially created index to be swapped into production. Since old indexes are deleted on swap, we had to do a full-reindex to recover which took half an hour. Our thinking going forward is we'd like to perform the reindex and save the last non-aliased index and delete all others.  

Obviously SearchKick does not support this. It seems that in order to support it some modifications would be needed to be made to the logic near here:

https://github.com/ankane/searchkick/blob/master/lib/searchkick/index.rb#L139

Probably would need to sort the non-aliased indexes by date before deleting old indexes and delete all but x number which could be set in a setting like:

  searchkick retain: 1

Would such a feature / approach be welcomed?

**Comment by incorvia** [comment]
@ankane, thanks for addressing my issues.. While I don't think that (retain: true) is really what I was hoping, I'd say retain: :previous is.. what I was hoping for.. I'm not sure why this would be confusing:

Product.reindex(retain: previous) # indexes: [A] (Initial, nothing to retain)
Product.reindex(retain: previous) # indexes: [A,B] (swaps, and retains A)
Product.reindex(retain: previous) # indexes: [B,C] (swaps, and retains B)

For me I'd just be ok with retain_previous: true.. but perhaps you'd prefer retain: true, false, or :previous? thoughts?

**Comment by ankane** [comment]
In some circumstances, people may not want to clean indices at all, so I was thinking that option should be included in this feature as well.

**Comment by incorvia** [comment]
@ankane, I'm certainly ok with that.. before we proceed.. Would you be ok exposing this option to the rake task as well via an ENV?

**Comment by ankane** [comment]
See #381
