### ISSUE TITLE
Document filtering by nil

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#357]
I'd like to be able to use a where clause to filter out `nil` values for a key, like this:

``` ruby
Item.search('*', where: { item_type_id: nil })
```

This should be possible with [Elasticsearch syntax](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-missing-filter.html), but I'm not sure how to do it with searchkick Might be a good addition to the README!

**Comment by mehulkar** [comment]
Actually, I'm not sure if searchkick even supports this.

**Comment by mehulkar** [comment]
@mengqing I don't have a test, but in my setup, it didn't generate the right query. We are manually manipulating the query body anyway, so I did it manually. I'll try to write a test sometime this week to prove me right or wrong.

**Comment by kashifnaseer** [comment]
How we can do partial matching (SQL uses like % Wildcard  )... any idea ?
eg: 
Item.search('*', where: { name: 'TV %' }). 
it should pull all the items having TV in their names

**Comment by mehulkar** [comment]
@kashifnaseer you should use an analyzer on the name field so it gets indexed in pieces. Then you'll be able to search like this: `Item.search('TV', fields: [:name])`. You can use an analyzer like this:

```ruby
class Item < ActiveRecord::Base
  searchkick merge_mappings: true, mappings: {
    item: {
      properties: {
        name: {type: "string", analyzer: "searchkick_word_search"},
      }
    }
  }
end
```

This is probably not relevant to this issue though.

**Comment by saurabhbhatia** [comment]
```Model.search("*", where: { field: {not: nil} }``` or ```Model.search("*", where: { field: nil }``` works out of the box.

**Comment by cbernaut** [comment]
`Profile.search("*", where: { salary_avg: nil })` generates the following error:

> Searchkick::InvalidQueryError: [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[_mukcLvBTHGBwrX8hqd7ww][profiles_test_20150823151135325][0]: SearchParseException[[profiles_test_20150823151135325][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"missing":{"field":"salary_avg","existence":true,"null_value":true}}]}}},"size":100000,"from":0,"fields":[]}]]]; nested: NullPointerException; }]","status":400}

whereas `Profile.search("*", where: { salary_avg: nil })` does not.

**Comment by ankane** [comment]
@cbernaut having trouble reproducing. can you add a failing test case?

**Comment by cbernaut** [comment]
Will do!

Bryan Liff
Minerva Group PSC <http://minerva-group.com>
+1 (212) 901-5252 x121

<http://minerva-group.com>

**Comment by ankane** [comment]
Cleaning up issues

**Comment by Sohair63** [comment]
Empty string works but `nil` does not.

```ruby
res = User.search("*", where: { confirmed_at: { not: '' } } )
r.any?
 => true


res = User.search("*", where: { confirmed_at: { not: nil } } )
r.any?
 => false 

```
