### ISSUE TITLE
Combining Filters and Boosts

### ISSUE THREAD

**Issue by jmwelch** [ankane/searchkick#359]
It appears as if using `fields: ["<field_name>"]` doesn't affect the query filters. For example:

``` ruby
filter = {
  or: [
    [ {apple_count: 3}, {orange_count: 3} ]
  ]
}
Basket.search '*', where: filter, fields: ['apple_count^1000', 'orange_count']
```

doesn't do as expected. I'd like to return all Baskets that have either 3 apples or 3 oranges, or both! But I'd like to return the Baskets that have exactly 3 apples first.

Any way to do this?

I tried using `boost_where`, but unfortunately my scenario is a bit more complicated than apples and uses arrays. I would like to do something like this:

``` ruby
filter = { fruit_origin: ['Honduras', 'Argentina', 'Brazil', ... ] } # plus many more countries
Fruit.search '*', where: filter, boost_where: { fruit_origin: ['Honduras', 'Argentina'] }
# fruit_origin is an indexed array of places that fruit originates from
```

and have it return all Fruits that originated in South America, but return those originating in Argentina and Brazil.

Thanks for an incredible gem!

**Comment by ankane** [comment]
It sounds like `boost_where` is what you want, but if that doesn't work, you'll probably need to write your own ES query.
