### ISSUE TITLE
Compatible with api-pagination gem

### ISSUE THREAD

**Issue by 7h3kk1d** [ankane/searchkick#360]
Unless I'm missing something searchkick doesn't seem to be compatible with [api-pagination](https://github.com/davidcelis/api-pagination). 

I get the following error in my controller.

```
NoMethodError (undefined method `page' for #<Searchkick::Results:0x007fc2b7762470>):
  app/controllers/persons_controller.rb:59:in `search'
```

I can try to make a pull request if given a little direction.

**Comment by ankane** [comment]
Currently, you can do array pagination with api-pagination:

```ruby
paginate json: Product.search("test").results
```

But unfortunately there's not an easy way make it work with ES pagination right now.

**Comment by Leoxxid** [comment]
Thanks, this help me @ankane :D
