### ISSUE TITLE
Document filtering by  like % Wildcard

### ISSUE THREAD

**Issue by kashifnaseer** [ankane/searchkick#363]
I'd like to be able to use a where clause to filter out records on the basis of LIKE  % Wildcard. How i can do this in SearchKick ?

SELECT \* FROM Customers WHERE City LIKE 'guj%';

**Comment by bogdanovich** [comment]
```ruby
searchkick  word_start: [:city]
```
and then

```ruby
Customer.search 'guj', fields:[{city: :word_start}]
```

**Comment by ankane** [comment]
Thanks for taking this one @bogdanovich
