### ISSUE TITLE
searchkick:reindex:all does not work

### ISSUE THREAD

**Issue by mattgibson** [ankane/searchkick#365]
I'm running this command as a rake task from the command line and it reports success (but no output other than that). However, no models get reindexed. If I run the Rails console and then run `ModelName.reindex` from there, then it works.

This is for a new machine that's running elasticsearch.

**Comment by ankane** [comment]
Hey Matt, what version of Rails are you on?

**Comment by ankane** [comment]
Cleaning up issues
