### ISSUE TITLE
search_data method definition before searckick adding

### ISSUE THREAD

**Issue by valerykalashnikov** [ankane/searchkick#366]
Hi, I already using searchkick and found that if I run searchkick after search_data method definition, it is impossible to control what data indexed because it is indexing every field. I found it using searchkick in a rails concerns and it wasn't obviously for the first sign. Maybe it would be better to notice users about it in a readme indexing section (there is no searchkick definition at all) ?

**Comment by ankane** [comment]
Hey Valery, thanks for reporting.  This is now fixed on master.

**Comment by monkbroc** [comment]
I just ran into this today too when using searchkick in a concern. Thanks for fixing @ankane :+1:
