### ISSUE TITLE
Remove Hashie

### ISSUE THREAD

**Issue by waynehoover** [ankane/searchkick#370]
Hello,

I read @schneems excellent article [Hashie Considered Harmful - An Ode to Hash and OpenStruct](http://www.schneems.com/2014/12/15/hashie-considered-harmful.htm) and then was sad to see Hashie used in this excellent gem.

I understand that its being called [once](https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb#L49), to return the results.

Would you be open to removing it? Can you explain why it was added as a dependency to begin? It might be worth our while to consider removing it for at the very least performance reasons. Thoughts? Concerns?

**Comment by waynehoover** [comment]
So I went ahead and created a forked version without Hashie. I got all the tests to pass, there was just 3 tests I had to change, I think they are even more clear now actually. I'm still not sure if this will break anything with real world apps, would love some feedback. Here where the changes made to get tests to pass without Hashie:

https://github.com/waynehoover/searchkick/commit/f72899f70c736e42c9af15d55bdf8ed644147510

**Comment by willcosgrove** [comment]
:+1:

**Comment by demersus** [comment]
+1 Hashie::Mash doesn't behave like regular ruby objects, and i've had to create some workarounds in my app to account for this.

**Comment by ankane** [comment]
I don't see a strong reason for moving away from Hashie, so going to close.
