### ISSUE TITLE
execute:false ignored when using a custom query

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#371]
The following query:

Job.search query:{:match=>{"_all"=>{:query=>"java"}}}, execute:false

returns results and doesn't show the query.  Using "execute:false" should always return the query as it will be submitted to the ES server.

Why would you want to see the query when you are specifying it yourself?  Because sometimes you want to combine a custom query with a where clause (or some other clause) and it would be nice to see how Searchkick combines them.

For example, in this query: 

Job.search query:{:match=>{"_all"=>{:query=>"java"}}}, where:{error:'fubar'}, execute:false

it appears that searchkick properly combines the where clause with the query clause.  But it would be nice to see the specifics of exactly how they are combined.

**Comment by ankane** [comment]
Hey @dsandber, not sure I follow, but feel free to reopen with more explanation.
