### ISSUE TITLE
function_score with with ES 1.3+

### ISSUE THREAD

**Issue by netwire88** [ankane/searchkick#372]
Hi,
I followed the directions on https://github.com/ankane/searchkick/issues/178 to create `function_score` so as to enabled randomized scoring on results in the example below. However, while the results are sorted randomly, it doesn't follow the `fields` limitation. 

```
query = Product.search 'XXX', fields: ['name'], limit: 20, execute: false
    query.body[:query] = {function_score:{ random_score: { seed: Time.now.hash.to_s } } }
    query.execute
```

However, if I change the search to `Product.search 'XXX', fields: ['name'], limit: 20`, the search works and limits to searching in `name` field. Any thoughts? I wasn't sure if this a bug on my side or change in ES since the original post was done.

**Comment by ankane** [comment]
The code above replaces the fields and limit.  You probably want to merge your query with the body instead.
