### ISSUE TITLE
Reindex performance?

### ISSUE THREAD

**Issue by netwire88** [ankane/searchkick#373]
Hi,
Does `reindex` use ES bulk import? For example, I'm importing 100,000 records (via Mongoid) and am using `batch_size = 200`. I'm not importing any related models, but it's taking about 10 seconds per 200 records. In production we have over 2M records, so that won't scale. I saw this issue https://github.com/ankane/searchkick/issues/334 but I think the only refers to models with associations? Is this the expected performance or something I'm doing wrong? My `search_data` only contains a few fields that are all stored within the record itself (i.e. Mongoid document):

```
  def search_data
    as_json {
      name = name,
      description = description,
      in_stock = in_stock,
      sku = sku,
      merchant_name = merchant_name,
      merchant_id = merchant_id
    }
  end
```

**Comment by ankane** [comment]
Yeah, `reindex` uses the bulk import API.  There are a few places to check for bottlenecks:

- database queries - typical if you reference associations and don't use the `search_import` scope (n + 1 queries)
- Elasticsearch resources - monitor CPU and memory (a likely culprit from your description)
- network performance - less likely, but could be connectivity issues between your Rails app and the database or Elasticsearch
