### ISSUE TITLE
Issue when using :word_start on several fields

### ISSUE THREAD

**Issue by Florent2** [ankane/searchkick#374]
The following test fails

```ruby
  def test_partial_on_second_of_several_fields
    store [
      {name: "Eggplant", color: "violet"},
    ]
    assert_search "vio", ["Eggplant"], fields: [name: :word_start, color: :word_start]
  end
```

while this one passes:

```ruby
  def test_partial_on_first_of_several_fields
    store [
      {name: "Eggplant", color: "violet"},
    ]
    assert_search "vio", ["Eggplant"], fields: [color: :word_start, name: :word_start]
  end
```

I was expecting the partial to search whatever is the order of attribute in the `fields` options. Maybe I am missing something?

Here is my forked test file containing these tests: https://github.com/Florent2/searchkick/commit/c288c83ab19b9a334c5ff6b14fade06466b83d09

**Comment by ankane** [comment]
Hey Florent, the syntax is slightly off. Try: `[{color: :word_start}, {name: :word_start}]`

**Comment by Florent2** [comment]
Thanks! Indeed, was a syntax error of mine, sorry for the disturbance. Would you accept a PR for the README showing an example of this syntax for partial matches on multiple fields?
