### ISSUE TITLE
Find in several fields

### ISSUE THREAD

**Issue by carlinoseldepi** [ankane/searchkick#375]
Hi, i've a doubt. 

It's possible make a query that find X words in field A and Y words in field B?

My case:
Relation betweens models:
       TweetInfo (*) ----------- (1) Tweet (*) ---------- (1) TweetUser
 **TweetInfo** belongs_to **Tweet**. **Tweet** has_many **TweetInfo**
 **Tweet** belongs_to **TweetUser**. **TweetUser** has_many **Tweet**

In elastic search i index model TweetInfo and its info related.

class **TweetInfo**
    searchkick

```
def search_data
{
  ### tweet_info
  sentiment: sentiment,
  favourite: favourite,
  deleted: deleted,
  published_at: published_at,
  ### tweets
  tweet_id: tweet.id,
  tweet_text: tweet.text,
  ### tweet_user
  tweet_user_id: tweet.tweet_user.id,
  tweet_user_screen_name: tweet.tweet_user.screen_name,
  tweet_user_description: tweet.tweet_user.description,
  tweet_user_location: tweet.tweet_user.location
}
```

  end

end

I want for example find IDs of TweetInfo who contains:
- positive in field **twwet_info.sentiment**

AND/OR
- 'madrid' in field **tweet_user.description**
- 'es' in field **tweet_user.location**
  
  AND / OR
- '#development #ror #rubyonrails' in field **tweet.text**  --> this three words are not neccesary in this order

It's possible in one searchkick-query??

results = TweetInfo.search(...) 

Thanks

**Comment by gustaflindqvist** [comment]
+1

**Comment by jmcastel** [comment]
+1

**Comment by ankane** [comment]
Searchkick doesn't support this. You'll need to write a custom ES query.
