### ISSUE TITLE
Searchkick fails silently when no mappings are found

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#376]
Elasticsearch doesn't create a mapping if all the keys of the indexed records are `nil`. And when you try to use those mappings, it throws an exception. 

However, `searchkick` is smart and doesn't fail, I'm not sure this is good behavior:

For example:

```ruby
query_body = {:query=>{:match_all=>{}}, :sort=>[{:sort_design_users=>{:order=>"desc"}}], :from=>0, :size=>100}

# do the searchkick way
Project.search(query_body)
#=> returns records, does not fail

# do more advanced way
new_query = Project.search('*', execute: false)
query.body = query_body
query.execute
#=> parse failure, no mapping found
```

**Comment by ankane** [comment]
To make the commands equivalent, change the first command to:

```ruby
Project.search(body: query_body)
```

**Comment by mehulkar** [comment]
Ah, you're probably right about this. 
In that cases, should `Project.search(query_body) throw an exception or something? That's basically a bogus query right?

**Comment by ankane** [comment]
For legacy reasons, the `query` option is accepted, but `sort`, `from`, and `size` are silently ignored.  Probably makes sense throw an exception for invalid options.

**Comment by mehulkar** [comment]
Makes sense. I guess we should close this then.
