### ISSUE TITLE
Searching Papertrail versions

### ISSUE THREAD

**Issue by rctneil** [ankane/searchkick#377]
Hello,

I have searchkick setup perfectly for searching one of my models. I have recently added PaperTrail to the model for versioning reasons.

It is quite an odd use can of versioning as versions for this model are only created when a physical event happens therefore a version is created on demand.

Due to the above, I wish versions of this model to be searchable and appear in my search result listings.

I am getting confused about how to add these versions to the search index for SearchKick to search on?

I basically need to access each version, reify it and add it to the index.

Any thoughts on how this could be achieved?

**Comment by ankane** [comment]
Cleaning up issues.
