### ISSUE TITLE
Make two queries in the same request.

### ISSUE THREAD

**Issue by bgvo** [ankane/searchkick#378]
Hi!

This question might have been already covered in other issue, but I'm not capable of finding it.

I have a collection of Items, in which I have "books" and "videos":

``` ruby
    {
        "_id" : ObjectId("5461c8f4426f727f16ba0600"),
        "name" : "Pursuit of Happiness",
        "dst" : "video",
        "detail" : {
            "director" : [ 
                "Mahmoud Chavoushi"
            ]
    },
    {
        "_id" : ObjectId("5461c8f4426f727f16ba0600"),
        "name" : "Bee",
        "dst" : "book",
        "detail" : {
            "author" : [ 
                "Mahmoud Chavoushi"
            ]
    }
```

I would like to make a Search query so that I get separated results on the same query:
- Books: Query for "name" field of items where `dst: "book"`.
- Videos: Query for "name" field of items where `dst: "video"`.

I always could make two separate searches, but making just one request and retrieving separate results would be ideal. 

Is this possible?

Thanks a lot in advance.

**Comment by ankane** [comment]
You can now use [multi search](https://github.com/ankane/searchkick#multi-search) for this.
