### ISSUE TITLE
Searchs without stemming?

### ISSUE THREAD

**Issue by carlinoseldepi** [ankane/searchkick#379]
It's possible to do searches in elasticsearch without stemming (with complete word)?

In my case, in spanish language for elasticsearch 'sensaciones is like 'sensacional' because the stem of both words is 'sensacion'.

I try many options: exact_word, misspelling => false, .... and always give me wrong results because includes 'sensaciones' and 'sensacional'

There are any solution for this? Or elasticsearch always work with the stem of the words?

**Comment by carlinoseldepi** [comment]
@ankane ??

**Comment by PoslinskiNet** [comment]
I have a similar problem. Did anyone managed to disable stemming for certain queries (exact match queries)?

**Comment by ankane** [comment]
You'll need to write a custom mapping to remove stemming.  There's no easy way to do it with Searchkick.  You'll need to use the Elasticsearch DSL.
