### ISSUE TITLE
multi-index search

### ISSUE THREAD

**Issue by liberatiluca** [ankane/searchkick#38]
Searchkick should support multi-index search.

I have overcome this by using:

```
Model1.search("thequery", index_name: [Model1.index.name, Model2.index.name, Model3.index.name])
```

it works ok, but it's just wrong to have to do this.

Maybe the starting point can be #36?

**Comment by Madumo** [comment]
Is it possible to specify an includes option for each model type doing a multisearch that way?

**Comment by axilaris** [comment]
Hi,
I'm a beginner with rails

`Model1.search(params[:query], index_name: [Model1.searchkick_index.name, Model2.searchkick_index.name])`

I tried using it like this but all the results comes only from Model1. Is there anyway to get results from both models.

Both models have different attributes.

**Comment by norhm** [comment]
Hi,
I'm a beginner with rails

`Model1.search(params[:query], index_name: [Model1.searchkick_index.name, Model2.searchkick_index.name])`

I tried using it like this but all the results comes only from Model1. Is there anyway to get results from both models.

Both models have different attributes.

**Comment by tomav** [comment]
:+1:

**Comment by RyanSnodgrass** [comment]
The solution I have found comes from using the `Searchkick` class as my method
```ruby
# app/models/foo.rb
class Foo
  searchkick
  def search_data
    { name: name }
  end
  def name
  end
end

# app/models/bar.rb
class Bar
  searchkick
  def search_data
    { name: name }
  end
  def name
  end
end
```
```
> Foo.reindex
> Bar.reindex
```
```ruby
results = Searchkick.search('query')
```
Be aware this searches every index and field.

---

If you want to search just specific fields
```ruby
# update the `search_data` method to contain your other field
# app/models/foo.rb
class Foo
  searchkick
  def search_data
    { name: name,
      description: description }
  end
  def name
  end
  def description
  end
end
```
```
> Foo.reindex
```
```ruby
# you can then define which fields to search
results = Searchkick.search('query', fields: ['name', 'description'])

# Cool part is, if one model/index has a field the others don't, searchkick will still work as expected
results = Searchkick.search('query', fields: ['name', 'description', 'unique_field'])

# if you want to boost a certain field, put a carrot to power
results = Searchkick.search('query', fields: ['name^10', 'description'])
```

**Comment by MrHubble** [comment]
This feature was added to the documentation in July: https://github.com/ankane/searchkick/commit/bd12de702bbe38fa660e8156ad1d8b7bfa30bb25

I'm unsure when the code was implemented.

Does anyone know if it's possible to search multiple indices (ie `Searchkick.search "milk", index_name: [Product, Category]`) and apply different `order` and `limit` to the different indices?

**Comment by ankane** [comment]
@MrHubble You'll need use multi search instead if you want different `order`s and `limit`s.

**Comment by ankane** [comment]
Closing this issue as multi-index search is now supported. Please create a new issue if I missed anything or there are future questions.

**Comment by apuntovanini** [comment]
@ankane Sorry to bother, but how can I sort results by _score in a multi_search example?
```
user_results = User.search(
  "*",
  limit: 20,
  execute: false
)
organization_results = Organization.search(
  "*",
  limit: 40,
  execute: false,
  order: { updated_at: :desc}
)
Searchkick.multi_search([user_results, organization_results])
```
I'd like to see organizations with higher score before than users. Thanks in advance

**Comment by ankane** [comment]
You'll need to do this in Ruby. Also, as mentioned in the comment above, please create a new issue for new questions so the 15 other subscribers to this issue aren't spammed.
