### ISSUE TITLE
Naming collision with `reindex` when using Algolia with Searchkick

### ISSUE THREAD

**Issue by timraymond** [ankane/searchkick#384]
At my company, we use Algolia to provide autocomplete functionality and Searchkick to provide search results from Elasticsearch. Unfortunately, both gems define a `reindex` method on the models to reindex the associated index for that model. Algolia checks for the existence of a `reindex` method on the model before aliasing its own `Model.algolia_reindex` method as `Model.reindex`. Searchkick, however, defines `reindex` regardless, stomping the other implementation's alias if it went first.

My proposal is to basically do the same thing Algolia does. Rename `Model.reindex` to `Model.searchkick_reindex` and conditionally alias it if it hasn't already been defined. This at least makes it possible to use `searchkick_reindex` to differentiate them if there are conflicts. Would a patch to add this be desired? Let me know what you think.

**Comment by ankane** [comment]
Thanks for the suggestion @timraymond!

**Comment by cmalpeli** [comment]
Just ran into this - so thanks so much for adding this!
