### ISSUE TITLE
Reindexing not working for remote DB.

### ISSUE THREAD

**Issue by ajeetsk** [ankane/searchkick#385]
I am using ES/Searchkick with RoR, indexing is working fine on my local "ubuntu" system where application, ES and DB all are on the same system. But when I run the same on my staging "ubuntu" servers where app and ES are on one box and db on another - reindexing is not working.

$ rake searchkick:reindex CLASS=Specialty
Could not find class: Specialty
$

Please help me understand if anything is needed whilw working with remote db. I am not able to find any relevant online resource.

Thanks,
Ajeet

**Comment by ankane** [comment]
The location of the database shouldn't affect reindexing.  Make sure the `Specialty` model exists on your staging server.
