### ISSUE TITLE
Explanation of default search-kick queries/analyzers

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#388]
It would be great if the default Searchkick conversion to ElasticSearch query could be more fully explained in the documentation.  Here's what I've been able to deduce so far from the sample query and expansion that follows.

It seems that an exact search is boosted ten times over an inexact search.  A query is always done using both searchkick_search and searchkick_search2 analyzers.  The difference between them (as seen in lib/searchkick/reindex.rb) seems to be the inclusion of the 'searchkick_search_shingle' analyzer.  

That is defined as:

`
        searchkick_search_shingle: {
                type: "shingle",
                token_separator: "",
                output_unigrams: false,
                output_unigrams_if_no_shingles: true
              },
`

But I'm at a loss for what that actually does.  The comment above it ( # lucky find http://web.archiveorange.com/archive/v/AAfXfQ17f57FcRINsof7 ) points to  a quote by John Witherspoon.

Boosting a field by X seems to multiply both the inexact and exact query boosts by X.

`Order.search 'fubar', fields:['field1^2', 'field2'], execute:false`

yields:

`
  {:query=>
    {:dis_max=>
      {:queries=>
        [{:match=>{"field1.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>20, :analyzer=>"searchkick_search"}}},
         {:match=>{"field1.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>20, :analyzer=>"searchkick_search2"}}},
         {:match=>
           {"field1.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>2, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search"}}},
         {:match=>
           {"field1.analyzed"=>
             {:query=>"fubar", :operator=>"and", :boost=>2, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search2"}}},
         {:match=>{"field2.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>10, :analyzer=>"searchkick_search"}}},
         {:match=>{"field2.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>10, :analyzer=>"searchkick_search2"}}},
         {:match=>
           {"field2.analyzed"=>{:query=>"fubar", :operator=>"and", :boost=>1, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search"}}},
         {:match=>
           {"field2.analyzed"=>
             {:query=>"fubar", :operator=>"and", :boost=>1, :fuzziness=>1, :max_expansions=>3, :analyzer=>"searchkick_search2"}}}]}},
   :size=>100000,
   :from=>0,
   :fields=>[]},
`

**Comment by ankane** [comment]
Great idea, would love to do this when I have some time.

**Comment by hooopo** [comment]
:+1 for this.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
