### ISSUE TITLE
Searches with special characters (#, @, ...)

### ISSUE THREAD

**Issue by carlinoseldepi** [ankane/searchkick#390]
I have indexed many tweets. When i found words that contains # (or @) character elasticsearch return me tweets with and without # (or @).

For instance if i want get all tweets with the hashtag #searchkick it return me all tweets with the word searchkick (with and without #), but i only want words that are hashtag #searchkick 

There are some configuration in the gem that permits include this special characters in the search?

This web http://www.fullscale.co/blog/2013/03/04/preserving_specific_characters_during_tokenizing_in_elasticsearch.html 
explains that elasticsearch removes special characters, but it's possible manage the default behavior. Is this possible with the gem?

Thanks

**Comment by carlinoseldepi** [comment]
Anyone had this problem?????

**Comment by carlinoseldepi** [comment]
@ankane ??

**Comment by ankane** [comment]
@carlinoseldepi You can use a custom mapping and settings to do this. Unfortunately, I don't time to explain more at the moment

**Comment by avra911** [comment]
@carlinoseldepi, try something like:
```ruby
  searchkick mappings: {
    search: {
      properties: {
        query: {type: "string", analyzer: "keyword", index: "not_analyzed"}
      }
    }
  }
```
in your model

**Comment by ankane** [comment]
Cleaning up issues. If someone wants to take a stab at adding this functionality to the gem, happy to accept a PR.
