### ISSUE TITLE
Filtering on an array of values is encoded inefficiently 

### ISSUE THREAD

**Issue by dsandber** [ankane/searchkick#391]
doing a :

`where:{company_id:[1,2,3,4]}`

is encoded as:

`filter=>{:and=>[{:or=>[{:term=>{:company_id=>1}}, {:term=>{:company_id=>2}}, {:term=>{:company_id=>3}}, {:term=>{:company_id=>4}}]}]},`

rather than:

`filter=>{:in=>{:company_id=>[1,2,3,4}}`

for huge arrays this can make a significant difference in the size of the query string sent, and hence the execution time. 'in' is a synonym for 'terms', apparently.

**Comment by ankane** [comment]
Nice catch, thanks @dsandber!

**Comment by dsandber** [comment]
You are a machine, Andrew :)
