### ISSUE TITLE
connect_timeout=() does not exist for Typhoeus::Request class

### ISSUE THREAD

**Issue by yurgon** [ankane/searchkick#393]
Hi, I cant reindex afte install gem Typhoeus

rake searchkick:reindex CLASS=Film
rake aborted!
NoMethodError: undefined method `connect_timeout=' for #<Typhoeus::Request:0x007f8a00777f90>
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/adapter/typhoeus.rb:104:in`configure_timeout'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/adapter/typhoeus.rb:47:in `request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/adapter/typhoeus.rb:22:in`perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/adapter/typhoeus.rb:14:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in`build_response'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in`block in perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in`perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in`perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in`get_aliases'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:42:in `clean_indices'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.5/lib/searchkick/reindex.rb:13:in`reindex'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.5/lib/searchkick/tasks.rb:10:in `block (2 levels) in <top (required)>'
Tasks: TOP => searchkick:reindex
(See full trace by running task with --trace)

**Comment by yurgon** [comment]
Any ideas?

**Comment by ankane** [comment]
What versions of Faraday and Typhoeus are you on?

**Comment by yurgon** [comment]
Typhoeus 0.7.1
Faraday 0.9.1

**Comment by ankane** [comment]
Searchkick works with those versions.  Be sure your Elasticsearch server is running and `ENV["ELASTICSEARCH_URL"]` is set correctly.

**Comment by ankane** [comment]
Nevermind, I'm seeing the error now too.  Will investigate further.

**Comment by ankane** [comment]
Able to reproduce the error if `require "typhoeus/adapters/faraday"` is not included in an initializer.  I'd check if it's that.

https://github.com/ankane/searchkick#performance

**Comment by yurgon** [comment]
I included now an recive new error:

Faraday::TimeoutError: request timed out
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/adapters/faraday.rb:92:in `block in request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:128:in `block in execute_callbacks'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `map'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/callbacks.rb:127:in `execute_callbacks'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/operations.rb:35:in `finish'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/easy_factory.rb:129:in `block in set_callback'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `each'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/ethon-0.7.2/lib/ethon/easy/response_callbacks.rb:65:in `complete'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/ethon-0.7.2/lib/ethon/easy/operations.rb:25:in `perform'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/operations.rb:16:in `run'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/cacheable.rb:18:in `run'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/block_connection.rb:31:in `run'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/stubbable.rb:25:in `run'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/request/before.rb:26:in `run'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/adapters/faraday.rb:68:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/typhoeus-0.7.1/lib/typhoeus/adapters/faraday.rb:58:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.7/lib/searchkick/index.rb:138:in `clean_indices'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.7/lib/searchkick/index.rb:151:in `reindex_scope'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.7/lib/searchkick/model.rb:47:in `reindex'
/Users/yurgon/.rvm/gems/ruby-2.0.0-p481@railstutorial_rails_4_0/gems/searchkick-0.8.7/lib/searchkick/tasks.rb:10:in `block (2 levels) in <top (required)>'

**Comment by aparreno** [comment]
I have the same issue. Some times it happen, some time it doesn't, but I can't find out why it's happening

**Comment by shilpi230** [comment]
I am facing this issue on all my builds(both on server and local build copies). Can anyone point me to a solid solution?

**Comment by swaathi** [comment]
I have the same issue. I am unable to perform any actions, since all my posts are indexed with Elasticsearch when they are created. I included `require "typhoeus/adapters/faraday"` in an initializer, and now it says `ETHON: performed EASY effective_url=http://localhost:9200/_aliases response_code=0 return_code=couldnt_connect total_time=0.004836
Faraday::TimeoutError: request timed out`, but my Elasticsearch server is up and running.

**Comment by swaathi** [comment]
I created an initializer called "elasticsearch.rb" and added this,
```
require "faraday"
require "typhoeus/adapters/faraday"
Searchkick.client = Elasticsearch::Client.new(hosts: ["127.0.0.1:9200", "127.0.0.1:9201"], retry_on_failure: true)
```

And it magically worked! Hope this helps.

**Comment by chriswoodrich** [comment]
@swaathi Thanks, manually requiring faraday and the adapter solved this for me.

**Comment by mastertechrv** [comment]
@swaathi Thanks that worked!

**Comment by dcdieci** [comment]
@swaathi I can confirm it to work on on osx 10.11.3 with elasticsearch 2.3.3 in a rails 5 project

**Comment by fenixping** [comment]
@swaathi Thanks. It is works fine.

**Comment by ankane** [comment]
Cleaning up issues. `typhoeus/adapters/faraday` is now automatically required when `typhoeus` is detected, fwiw.
