### ISSUE TITLE
Defining custom analyzers

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#395]
I'm not sure I understand how to define a custom analyzer. I know that in my mappings I can refer to a string name of an existing analyzer, but is there a public API for defining my own?

**Comment by mehulkar** [comment]
ping @ankane

**Comment by ankane** [comment]
Hey @mehulkar, you can use the `settings` option to define analyzers.

**Comment by mehulkar** [comment]
@ankane could you give me an example of how to define an analyzer/tokenizer/filter? I'm not sure how/where they get registered, since the settings are supposed to refer to their "logical / registered name" as noted here:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html

**Comment by mehulkar** [comment]
I've tried adding the custom analyzer to the options passed to `searchkick` in my model under the `settings` key and also inline inside properties.

**Comment by totallymike** [comment]
@mehulkar You can do

```ruby
searchkick settings: {
             analysis: {
               analyzer: {
                 my_analyzer: {...}
               }
             }
```

**Comment by piclez** [comment]
Hello, I defined my custom analyzer like above, but how to make the search use this custom analyzer after reindexing?

**Comment by paranoicsan** [comment]
@piclez you can use custom analyzer like so (model `Post` with field `body`):
```
mappings: {
  posts: {
    properties: {
      body: {
          type: 'string',
          index: 'analyzed',
          'analyzer': 'custom_lengh_analyzer'
      }
    }
  }
}
```

**Comment by rishijain** [comment]
@paranoicsan Can you have a look at https://github.com/ankane/searchkick/issues/623 ?
