### ISSUE TITLE
'where' query unpredictability

### ISSUE THREAD

**Issue by speasley** [ankane/searchkick#398]
I'm experiencing unpredictability with 'where' queries.

When I do a wide-open search with `Story.search q` searchkick returns results three results: two where `visible` equals false and **one** where `visible` equals true.

When I try to narrow the results with `Story.search q, where: {visible: true}` the search comes up empty, even though I'm expecting **one**, based on what the first search returned.

This is what shows up in the console on the second version:
`
Parameters: {"utf8"=>"✓", "query"=>"take"}
  Story Search (16.7ms)  curl http://localhost:9200/stories_development/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"take","operator":"and","boost":10,"analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"take","operator":"and","boost":10,"analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"take","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"take","operator":"and","boost":1,"fuzziness":1,"max_expansions":3,"analyzer":"searchkick_search2"}}}]}},"size":36,"from":0,"filter":{"and":[{"term":{"visible":true}}]},"suggest":{"text":"take","title":{"phrase":{"field":"title.suggest"}}},"fields":[]}'
`

I'm wondering if anything is amiss with: `{"term":{"visible":true}}`. According to the README, I think I'm going about this correctly.

Edit: I've also tried `Story.where( "statuses_mask = ? AND visible = ?", 4, true ).search "#{q}", suggest: true, misspellings: {distance: 1}, page: params[:page], per_page: 36` without success. No matter where I have those `where` params, they are ignored.

**Comment by ilovemysillybanana** [comment]
did you ever find a fix? I'm having issues with where as well. Says method is undefined for this code:

@users = User.search(params[:search]), where: {available: true} I've tried placing the where in front as well and it's not helping.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to create a test case to reproduce if it's still a problem.
