### ISSUE TITLE
Is it possible to have both stemming and partial match?

### ISSUE THREAD

**Issue by Florent2** [ankane/searchkick#399]
Stemming no longer works when I enable partial match.

For instance in the searchkick tests when I change [this line](https://github.com/ankane/searchkick/blob/5f5715d32da56ae7cce20bfebb723afd7021b079/test/match_test.rb#L60)

``` ruby
assert_search "milks", ["Milk", "Whole Milk", "Fat Free Milk"]
```

to 

``` ruby
assert_search "milks", ["Milk", "Whole Milk", "Fat Free Milk"], fields: [{name: :word_start}]
```

the test now fails.

Same with misspelling handling (applying the same change on [this line](https://github.com/ankane/searchkick/blob/5f5715d32da56ae7cce20bfebb723afd7021b079/test/match_test.rb#L67) makes the test fail too).

Am I missing something, or maybe it is a limitation of searchkick or elasticsearch (could not find anything about it online though)?

**Comment by ankane** [comment]
There's no ES limitation. This was just a decision on how partial mapping for Searchkick was designed.
