### ISSUE TITLE
Searchkick: manually remove index of a record

### ISSUE THREAD

**Issue by kashifnaseer** [ankane/searchkick#400]
I have soft deletion on a model. when user removes any record, it updates it (NOT DESTROY).afte_update call back is called and it doesn't remove the index.

How i can manually remove index associated to specific Record ?

**Comment by ankane** [comment]
Hey @kashifnaseer, you can add a `should_index?` method to your model.

```ruby
class Product
  def should_index?
    deleted_at.nil?
  end
end
```

And run a full reindex - `Product.reindex`.

**Comment by kashifnaseer** [comment]
hey @ankane, will try it out but following code also helped me to fix it.  Thanks 
```ruby               
   Product.searchkick_index.remove(@product)

**Comment by ankane** [comment]
@kashifnaseer that will manually remove the record, but it will be re-added if the item is saved again (and you haven't disabled callbacks) or you do a full reindex.
