### ISSUE TITLE
reindex only the associated data

### ISSUE THREAD

**Issue by cesargomez89** [ankane/searchkick#401]
this is not working for me.

when I reindex my associations in this way:

```ruby
  def update_indexes
    profiles.reindex
    cats.reindex
  end
```

Only is working when I reindex everything

```ruby
  def update_indexes
    Profile.reindex
    Cat.reindex
  end
```

I don't know if I'm doing something wrong
Thanks in advice.

**Comment by sharshenov** [comment]
Be careful with `reindex` method.
* If you call it on a single model - model data wiil be updated in ES index
* If you call it on class/association - existing ES index will be replaced with new one containing data from this class/association scope only.

Actually there is PR(https://github.com/ankane/searchkick/pull/348) for Readme to methion this behaviour. So I suggest you to read this [text](https://github.com/ankane/searchkick/pull/348/files).

**Comment by ankane** [comment]
@cesargomez89 you can do:

```ruby
  def update_indexes
    Profile.searchkick_index.import profiles
    Cat.searchkick_index.import cats
  end
```

**Comment by radiofrequency** [comment]
data i add to the index using .import doesn't appear when i try a text_start query?  Only after i do a full reindex do they show up.

**Comment by cesargomez89** [comment]
Thanks guys, reindex was working well.
I was indexing an old version of the profile... caching issues

```ruby
  def update_indexes
    Cat.searchkick_index.import cats
    if profile.present?
      profile.reload
      profile.reindex
    end
  end
```

sorry for the delayed answer
