### ISSUE TITLE
Reindex not working

### ISSUE THREAD

**Issue by meandkareem** [ankane/searchkick#402]
trying to migrate from tire gem and get this error on reindex 

```
 Elasticsearch::Transport::Transport::Errors::BadRequest: [400] 
.....lib/elasticsearch/api/actions/indices/exists_alias.rb:43:in `exists_alias'
```

**Comment by saurabhbhatia** [comment]
Can you elaborate as to how your mapping looks like ?

**Comment by ankane** [comment]
Cleaning up issues

**Comment by chrishough** [comment]
I am getting the same error @meandkareem, how did you solve this?
