### ISSUE TITLE
Difference between text_start and word_start

### ISSUE THREAD

**Issue by netwire88** [ankane/searchkick#403]
Hi,
I'm a noob to ES, I tried searching for difference between `text_start` and `word_start` but couldn't find any. Any quick thoughts?

**Comment by ankane** [comment]
`cheerios` matches `honey nut cheerios` for `word_start`, but not `text_start`.

`honey` matches both.

**Comment by MrHubble** [comment]
@ankane thanks for the clarification. Is there any documentation regarding these different methods? I tried http://www.rubydoc.info/gems/searchkick but couldn't find anything on `text_start`

**Comment by ankane** [comment]
All of the documentation is in the readme. It's a bit sparse for `text_start` and related options.
