### ISSUE TITLE
Partial with Attributes

### ISSUE THREAD

**Issue by kobaltz** [ankane/searchkick#404]
Let's say I have a `User Model` that has the following attributes.

```
first_name
last_name
city
state
```

I know that the User that I'm searching for has the `last_name` of `Kobaltz` and that they live in the state `Kentucky`.

I could form the search as

`User.search(where: {{last_name: 'Kobaltz'},{state: 'Kentucky'}})1 and it returns the result.

However, what if I only knew part of the `last_name`? How would you change the search to allow partial matches on specific attributes.

So in this example, if I know that the 

`last_name STARTS WITH 'Kob'`
`state EQUALS 'Kentucky'`

**Comment by ankane** [comment]
Hey @kobaltz, you'd want to use [partial matching](https://github.com/ankane/searchkick#partial-matches) for this.
