### ISSUE TITLE
Support for date_histogram / geo distance facets

### ISSUE THREAD

**Issue by jeremymarc** [ankane/searchkick#408]
Im trying to execute a date_histogram facet. 

My request looks like:
{"query":{"match_all":{}},"size":100000,"from":0,"facets":{"histo":{"date_histogram":{"field":"created_at","interval":"month"}}},"fields":[]}'

Is it a way I can do that with searchkick?

**Comment by courtenay** [comment]
@jeremymarc  I'm too busy right now to make a PR but here's how I did it - had to extract to lib,

```
diff --git a/lib/searchkick/query.rb b/lib/searchkick/query.rb
index 4b9daa6..b3fb803 100644
--- a/lib/searchkick/query.rb
+++ b/lib/searchkick/query.rb
@@ -286,6 +286,13 @@ module Searchkick
                   size: size
                 }
               }
+            elsif facet_options[:date_histogram]
+              payload[:facets][field] = {
+                date_histogram: {
+                  field: field,
+                  interval: facet_options[:date_histogram][:interval]
+                }
+              }
             else
               payload[:facets][field] = {
                 terms: {
```
and do Foo.search facets: { created_at: { date_histogram: { interval: 'month' }}}}

**Comment by st0012** [comment]
My PR #516 should add support for this.

**Comment by ankane** [comment]
Cleaning up issues
