### ISSUE TITLE
query from form

### ISSUE THREAD

**Issue by remon** [ankane/searchkick#411]
How can I get the queries from search form and use it with searchkick 
 have these method to get the basic filtering and getting the profiles , what I want is to filter using search form 
```
totalblocks =[1,8,9]
myid =2
Profile.search"*",where:{
          user_id: {not: totalblocks},
           id: {not: myid},
           online:true  
      }
````

**Comment by ankane** [comment]
@remon First create the form - the [Getting Rails with Rails](http://guides.rubyonrails.org/getting_started.html) guide is a good place to start.  In your search action, you can pass the values provided by the user into the search method.

**Comment by ankane** [comment]
Cleaning up issues
