### ISSUE TITLE
Double Quotes

### ISSUE THREAD

**Issue by beweinreich** [ankane/searchkick#413]
Has anyone managed to use double quotes in searching?

For example, if I searched for the following: `Red Delicious "Apple"` it would have two requirements:

1) _Apple_ must be in the search result
2) _Red_ and _Delicious_ are optionally required

I read through Exact Matches https://github.com/ankane/searchkick#exact-matches and understood it as being able to match a field exactly. However, I'd like a portion of the query to match exactly, while the rest is optional.

**Comment by ankane** [comment]
Hey @beweinreich, you'll need to construct a custom query to do this.

**Comment by beweinreich** [comment]
Sounds good. Thanks.
