### ISSUE TITLE
Order mixed with pagination yields correct block of records, sorted by ID

### ISSUE THREAD

**Issue by totallymike** [ankane/searchkick#414]
Title pretty much states the problem.  I have a large collection that we'd like to sort by a timestamp and paginate.  Imagine it looks like this:

```json
[
  {"id": 1, "timestamp": "March 1, 2015"},
  {"id": 2, "timestamp": "March 2, 2015"},
  {"id": 3, "timestamp": "March 3, 2015"},
  {"id": 4, "timestamp": "March 4, 2015"},
  {"id": 5, "timestamp": "March 5, 2015"}
]
```

Of course the actual format of the data is different.  It's typed like that because I'm typing hypothetical data.  Pretend it's stored correctly.

Now the issue is that if, say, I request the records paginated by blocks of two ordered by `"timestamp": "desc"`, it will give me something like this:

```json
[
  {"id": 4, "timestamp": "March 4, 2015"},
  {"id": 5, "timestamp": "March 5, 2015"}
]
```

Note that it yields the correct collection of records, but ordered by `id`, rather than descending timestamp.

If my understanding is correct, this is because the list of records is fetched from ElasticSearch, and then the *actual* records are fetched from Postgres, with a query something like this:

```sql
SELECT * FROM my_records WHERE id IN [4, 5];
```

Is there a way, without manually reconstructing the SQL query to use the same ordering logic as the ES query, to request the data in the order one would expect it to be?  Perhaps I'm missing something entirely.

**Comment by totallymike** [comment]
For what it's worth, it seems that my theory is correct:

Logs:
```
curl http://<ipaddr>:9200/indexing/stuff/_search?pretty -d '{"query": {"match_all": {}}, "size": 20, "from": 9540, "sort": {"created_at": "desc"}, "fields":[]}'
```

followed by

```sql
SELECT "my_table"."*" FROM "my_table" WHERE "my_table"."id" IN (<the ids from the ES search>)
```

I sanitized a number of filter parameters from the ES request body that have to do with faceting, but are also somewhat sensitive.

**Comment by ankane** [comment]
@totallymike Searchkick maintains the Elasticsearch ordering - not in SQL but in Ruby.  If Elasticsearch is returning results in the incorrect order, there is most likely something off with your query or how the data is indexed.

**Comment by totallymike** [comment]
That might be so.  Do you have any ideas as to how to poke ElasticSearch for clues?

`{"sort": {"created_at": "desc"}` seems pretty unambiguous for ordering the data coming back from ES

**Comment by totallymike** [comment]
Reproducing the query with `curl` demonstrates that the data is coming back from ES in the same order that my Rails endpoint is sending it.  I'd say the problem is somewhere on our end, and I'll close this issue.
