### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] No handler found for uri

### ISSUE THREAD

**Issue by aman199002** [ankane/searchkick#415]
I am using searchkick latest version '0.8.7' and elasticsearch version '0.90.0'.  When i try to index data using User.reindex, it gives following error:

```
[5] pry(main)> User.reindex
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] No handler found for uri [/_alias/users_development] and method [GET]
from /Users/aman/.rbenv/versions/2.2.0/gemsets/thon-web/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
```

But its working fine with version '0.8.5'. Is there any change in latest version. Do i need to upgrade my elasticsearch version.

**Comment by ankane** [comment]
You'll need to upgrade Elasticsearch to use the latest Searchkick. Searchkick 0.6.3 is the last version to officially support Elasticsearch below 1.0.

**Comment by aman199002** [comment]
Thanks it worked !!

**Comment by geekazoid** [comment]
I'm experiencing the same issue, but with searchkick `0.8.7` and ElasticSearch `1.4.2`, but only in the CI environment. Have any idea?

**Comment by ankane** [comment]
If you're getting the exact same error, I'd double check that your CI environment is running the correct version.

**Comment by geekazoid** [comment]
ElasticSearch version (sorry, it was `1.4.1`)

```
$ curl -XGET $WERCKER_ELASTICSEARCH_URL
{
  "status" : 200,
  "name" : "Arachne",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.1",
    "build_hash" : "89d3241d670db65f994242c8e8383b169779e2d4",
    "build_timestamp" : "2014-11-26T15:49:29Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}
```
And `Using searchkick 0.8.7` in bundler's output.

Getting this error:

```
Failure/Error: LiveBeefLot.reindex
     Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] No handler found for uri [/_alias/live_beef_lots_test] and method [GET]
```

**Comment by peddinti** [comment]
Hi i am getting a similar error and i am using elastic search ver 1.5

my searchkick version is 0.9 ... i am getting the following error ..

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] No handler found for uri [/profiles_development/profile] and method [PUT]

**Comment by akbarbin** [comment]
I got same error too.

**Comment by Geetakokate** [comment]
I got same error too. With Elastic search version 1.0.15 and search kick version 1.1.2.

**Comment by Geetakokate** [comment]
I got same error with elastic search 1.0.15 and search kick  1.1.2

**Comment by ankane** [comment]
Cleaning up issues

**Comment by abhinaykumar** [comment]
getting the same issue with latest elasticsearch version
```
{
  "name" : "3alTEf-",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "crboP69eQpyJfW4g4n-VgQ",
  "version" : {
    "number" : "5.6.3",
    "build_hash" : "1a2f265",
    "build_date" : "2017-10-06T20:33:39.012Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```
Any idea how to resolve this issue:
`$ rake searchkick:reindex CLASS=Course`

```
rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] No handler found for uri [//courses_development_20171026104819752] and method [PUT]
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/searchkick-2.3.2/lib/searchkick/index.rb:14:in `create'
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/searchkick-2.3.2/lib/searchkick/index.rb:184:in `create_index'
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/searchkick-2.3.2/lib/searchkick/index.rb:233:in `reindex_scope'
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/searchkick-2.3.2/lib/searchkick/model.rb:70:in `searchkick_reindex'
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/searchkick-2.3.2/lib/searchkick/tasks.rb:9:in `block (2 levels) in <top (required)>'
/Users/abhinay/.rbenv/versions/2.3.1/gemsets/videoken/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchkick:reindex
(See full trace by running task with --trace)
```

**Comment by mayureshmayur** [comment]
I was getting the same error

2.4.4 :016 > Meeting.reindex
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [name]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [meeting]: No handler for type [keyword] declared on field [name]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [name]"}},"status":400}
	from (irb):16

**Comment by mayureshmayur** [comment]
I was getting same error as below:

`2.4.4 :016 > Meeting.reindex
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [name]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [meeting]: No handler for type [keyword] declared on field [name]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [keyword] declared on field [name]"}},"status":400}
	from (irb):16`

As per my Gemfile.lock

`139        dotenv (= 2.4.0)
  140        railties (>= 3.2, < 6.0)
  141:     elasticsearch (6.0.2)
  142:       elasticsearch-api (= 6.0.2)
  143:       elasticsearch-transport (= 6.0.2)
  144:     elasticsearch-api (6.0.2)
  145        multi_json
  146:     elasticsearch-transport (6.0.2)
  147        faraday
  148        multi_json
  ...
  467      searchkick (3.1.0)
  468        activemodel (>= 4.2)
  469:       elasticsearch (>= 5)
  470        hashie
  471      selenium-webdriver (3.12.0)`

I needed elastic search >=5 installed was 2.3.1.

So I installed 6.4.0.

[https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-16-04](url)

Followed above for installation. 
My issue got resolved.
