### ISSUE TITLE
Weight search keywords

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#417]
Hi,

I have a bunch of keywords i want to query the model with and want to weight each of them. How can i achieve that with searchkick? in other words i am looking at a way to do custom scoring function or something on those lines

**Comment by ankane** [comment]
@peddinti Searchkick does not provide a shortcut for this, so you'll need to use the Elasticsearch DSL. https://github.com/ankane/searchkick#advanced

**Comment by peddinti** [comment]
Thanks! do you have any an example on how i could use this .... i have the following
tag1 weight1
tag2 weight2

i want to weight each of these tags based on this.

**Comment by ankane** [comment]
This sounds similar to how Searchkick does conversions.  Try looking at that code.
