### ISSUE TITLE
reindex:all generates syntax error

### ISSUE THREAD

**Issue by campgurus** [ankane/searchkick#419]
I am trying to allow search by tags created with the acts-as-taggable-on gem.

I have this in my model:

  def search_data
    tag_name: tags.map(&:name)
  end

the error is 
Syntax error, unexpected ':', expecting keyword_end
      tag_name: ^ tags.map(&:name)

**Comment by ankane** [comment]
@campgurus Try:

```ruby
def search_data
  {tag_name: tags.map(&:name)}
end
```

**Comment by campgurus** [comment]
That worked - thanks!
