### ISSUE TITLE
Indexing multiple tables/models to one index?

### ISSUE THREAD

**Issue by juicyJ** [ankane/searchkick#423]
Is it possible have multiple models reindex to a single index? I have two models, ModelA and ModelB, where I both set: 

searchkick index_name: 'model_a_and_b', settings: { number_of_shards: 1}

but when I ran ModelA.reindex and ModelB.reindex, the elasticsearch index only ended up having the documents from ModelB. any better strategy to go about this? thanks!

**Comment by naiyt** [comment]
@juicyJ did you figure out how to do this? We would also like to do something similar.

**Comment by juicyJ** [comment]
@naiyt 

here was basically the quick and easy workaround for our needs that allowed us to reindex 2 diff models into the same index.

Where ModelA and ModelB had the same index name, we had nightly sidekiq job that essentially did this:

```ruby
ModelA.where("QUERY").find_in_batches do |batch|
  ModelA.searchkick_index.import(batch)
end

ModelB.where("QUERY").find_in_batches do |batch|
  ModelB.searchkick_index.import(batch)
end
```

**Comment by naiyt** [comment]
Thanks for your help @juicyJ!

**Comment by josh-m-sharpe** [comment]
Is there a way to accomplish this using a current version of searchkick AND not blowing away searchkick's use of aliases to accomplish background index refreshes?

**Comment by hendricius** [comment]
@juicyJ thanks, that helped. In my case I used a UNIONed table with uuids and ids. I couldn't use the regular `reindex` method.
