### ISSUE TITLE
big text column

### ISSUE THREAD

**Issue by krim** [ankane/searchkick#424]
I have a big article and then i reindex - i get an error:
{"error":"IllegalArgumentException[Document contains at least one immense term in field=\"prepare_body\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[60, 112, 32, 115, 116, 121, 108, 101, 61, 34, 116, 101, 120, 116, 45, 97, 108, 105, 103, 110, 58, 32, 114, 105, 103, 104, 116, 59, 34, 62]...', original message: bytes can be at most 32766 in length; got 79151]; nested: MaxBytesLengthExceededException[bytes can be at most 32766 in length; got 79151]; ","status":500}

How i can fix this?

**Comment by ankane** [comment]
Hey @krim, sorry for not following up until now. This is no longer an issue in ES 2.2+. For earlier versions, you can use the [filterable option](https://github.com/ankane/searchkick#filterable-fields) to exclude the large field from being indexed as a single "immense" term.

**Comment by Shkrt** [comment]
Seeing the same issue after updating to 2.2.1 (was 2.1.1). `Product.reindex` throws exception, that was described above. But if I do `Product.find(112312).reindex`, no exception thrown. Solved only by downgrading back to 2.1.1

**Comment by ankane** [comment]
Hey @Shkrt, this is likely due to #850. Does one of your records contain a long text field with a bunch of unicode characters? You can use `searchkick ignore_above: 256` to restore the previous behavior.
