### ISSUE TITLE
searchkick_index_options no longer overrideable

### ISSUE THREAD

**Issue by robbi5** [ankane/searchkick#429]
In https://github.com/ankane/searchkick/commit/67f3e9b5f11f1608feca39c28dc0ef7eac6a2020 (included in Searchkick >= 0.8.6) you moved the `searchkick_index_options` from the Model (extends Reindex) to Index.
This removed the ability to override the index options in the model.

I used this in 
https://github.com/robbi5/kleineanfragen/blob/6a4046e3279bbaed255284b8bf5dc7482fabbd0e/app/models/paper.rb#L11-L21 to remove the `not_analyzed` field. That seems to be required for big text fields like in #427, #424 and #343.
```
class << self
  alias_method :old_searchkick_index_options, :searchkick_index_options

  def searchkick_index_options
    o = old_searchkick_index_options
    # remove index: "not_analyzed"
    o[:mappings][:_default_][:properties]['contents'][:fields].delete('contents')
    o
  end
end
```

Is there any way to reintroduce overriding of `searchkick_index_options` in a way thats used by Index#create_index?

Thanks in advance :)

**Comment by krim** [comment]
Have you got any solutions?

**Comment by krim** [comment]
No ideas?

**Comment by kris** [comment]
+1

**Comment by CaseKey** [comment]
Are there any other solutions to indexing large strings?

**Comment by ankane** [comment]
The previous behavior should be restored on the index_options branch.

Ideally, we can come up with a better approach for large strings - probably a new `searchkick` option.

**Comment by kris** [comment]
I'd love for a good solution for the large string option. I have huge articles that are being indexed, and the content field is used for the similar content functionality, so I have to keep that field indexed so I can get similar content.

**Comment by ankane** [comment]
Just fyi, this is now on master.

**Comment by adisos** [comment]
@ankane 

Please, could you please share there solution for big text fields?

**Comment by ankane** [comment]
Added an `only_analyzed` option on master for this (needs a better name).

```ruby
searchkick only_analyzed: [:big_text_field]
```
