### ISSUE TITLE
Function_score overriding previous scores

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#431]
Hi,

I am using a function score to do a decay the score based on when it was created. But however using that seems to be overriding the other scores before applying the function scores.

Using this query 
query = Job.search "*", execute: false, where: {live: true,
                                                    schools: {all: [school_handle]},
                                                    majors: {all: [major_key]},
                                                    _id: {not: applied_job_ids}},
                       # matching skills and company name is most important. Then Title then location.
                       fields: ["skills^10", "company^10", "title^5", "location^2", "description", "company_overview"],
                       # boosting popular jobs
                       boost_by: [:view_count],
                       boost_where: {_all: boost},
                       limit: result_count

gives me scores around 9.0+ and then when i try to decay it with time
query.body[:query][:function_score].merge!({
                                                   functions: [
                                                       exp: {
                                                           create_dttm: {
                                                               scale: '180',
                                                               offset: '60d',
                                                               decay: 0.1
                                                           }
                                                       }
                                                   ],
                                                   score_mode: "sum",
                                                   boost_mode: "sum"
                                               })
    results = query.execute

the scores now become 2.0. it seems the previous score are now no longer taken into consideration. how can i solve this?

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
