### ISSUE TITLE
Matching '&' when searching with 'and'

### ISSUE THREAD

**Issue by bgvo** [ankane/searchkick#434]
Hi,

I have a record with title "Planes, Trains & Automobiles" (a field which is indexed).

I want to search for 'Planes, Trains and Automobiles' ('and' instead of '&') and hit the record. 

What can I do to make this happen?

Thanks.

**Comment by ankane** [comment]
Hi Borja, just added this feature - happens automatically if you use the master branch.

**Comment by ankane** [comment]
You'll need to reindex for it to work.

**Comment by bgvo** [comment]
Awesome! Thanks :)
