### ISSUE TITLE
Autocomplete from beginning of the each token

### ISSUE THREAD

**Issue by AlexanderEkdahl** [ankane/searchkick#44]
Sorry for creating so much fuzz here but I'm really liking your library and only wan't it to be even become better. Just like you clarified in #41 autocomplete and partial does not work in conjunction. However this is a feature I would very much have and thats why I created a new issue for it.

Typing "2% Mi" should trigger "2% Milk" but so should the query "Mil" and "Milk 2". I'm currently splitting the token but that messes with multiword queries. How exactly would such an index look like and still all? Am I better of using tire directly?

**Comment by bmcdaniel11** [comment]
@rjewell2200 how are you reindexing each time? I was using the rake task 
`rake searchkick:reindex:all`, which doesn't appear to be working. I opened the rails console within my project (rails c) and ran `MyModel.reindex`, and after that my word_start was giving me results.
