### ISSUE TITLE
How to index and query facets with nested associations?

### ISSUE THREAD

**Issue by npearson72** [ankane/searchkick#440]
Is there a way to get something like:

```
{ features: { color: [:red, :yellow, :blue], size: [:small, :large] }}
```

I have a Feature model that belongs_to: `Product`, `FeatureKey`, `FeatureValue`

So a `product` can have many `features`, each of which consist of one `feature_key` and one `feature_value`

```
FeatureKey#name # => 'color'
FeatureValue#name # => 'red'
```

Is this possible?

Thanks!

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
