### ISSUE TITLE
Advance Search limit does not work

### ISSUE THREAD

**Issue by rizalmuthi** [ankane/searchkick#441]
Hi
I really love this gem, I am using it on my current project.
Anyway, I wanna use the advance search wanted to limit the result, it seems did not work or maybe I did wrongly.

Basically this is my code:

```
body = { lotsofcodes here}
user = User.search(body: body)  # this works fine and returns all the records
user.count # 100

I have tried this

user = User.search(body: body, limit: 5) # does not work
user.count # Still 100
```

Any idea this is valid bug or I did wrongly to use the function to limit the result ?

Thanks

**Comment by ankane** [comment]
@rizalmuthi can you write a failing test case for this?  All the current limit tests are passing.

**Comment by ankane** [comment]
Cleaning up issues.
