### ISSUE TITLE
searchkick test mapping problem

### ISSUE THREAD

**Issue by rizalmuthi** [ankane/searchkick#442]
Hi

I have project with searchkick and I wanna test it.
So basically I have Product class and I added the searchkick on this class
The product has the following columns/fields:
- title
- description
- price
- timestamps

The problem is, whenever I run rspec, i got this error on the test search 

```
nested: QueryParsingException[[products_test_20150511134819600] Unknown field [created_at]];
```

I did include this code before run Product.search

```
    Product.reindex
    Product.searchkick_index.refresh
```

And I manually check the mapping on the elastichsearch for it, it turns out that it only has the field name which I dont have it on the Product table. But if I check on the photos_development, the mappings are correct.

 I am not sure whats happening. could you help me on this matters

Thanks

**Comment by codydotio** [comment]
+1 seeing this as well

**Comment by realadeel** [comment]
You probably need custom mappings. We saw the same thing: development picked up the correct mappings but test environment did not. We use index a number of fields that are not db columns for the model, for example fields from associated tables.

We ended up having to merge custom mappings into what searchkick produced. Something like this:

  searchkick word_middle: [
      :order_number,
      :serial_no
    ], merge_mappings: true, mappings: {
      model_name: {
        properties: {
          "archived": {
            "type": "boolean"
          },
          "company_id": {
            "type": "long"
          },
          "region_id": {
            "type": "long"
          },
        }
      }
    }

cc @ankane

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
