### ISSUE TITLE
Delete index?

### ISSUE THREAD

**Issue by netwire88** [ankane/searchkick#443]
Can I use searchkick to delete an index? Elastic Search recommended something like `curl -XDELETE 'http://localhost:9200/twitter/'` where `twitter` is the index name. However, which searchkick, I don't know which index names to use.

**Comment by ankane** [comment]
You can do `Searchkick.client.indices.delete(index: name)`.

**Comment by fschwahn** [comment]
It took me a moment to find the name of the index, so as a timesaver (for example model `Profile`):
```ruby
Searchkick.client.indices.delete(index: Profile.searchkick_index.name)
```

**Comment by ankane** [comment]
Fwiw, you can now also do:

```ruby
YourModel.search_index.delete
```

**Comment by fschwahn** [comment]
Even better 👍

**Comment by paulodeon** [comment]
I think that would be `YourModel.searchkick_index.delete`

**Comment by ankane** [comment]
Either will work (I personally prefer the former)
