### ISSUE TITLE
Searching multiple specific fields in the same query

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#45]
I need to be able to pair search terms with specific fields. For example

``` ruby
Person.search(where: {name: "Bob", location: "CA"})
```

The other solution would be to have some way of concatenating results so that we could do something like this:

``` ruby
Person.search("Bob", fields: [:name]).search("CA", fields: [:location])
```

The third way seems to be to perform two separate searches and attempt to concat/merge the two, but I don't see any methods for that to work. I could concat just the results from each search like this:

``` ruby
Person.search("Bob", fields: [:name]).results + Person.search("CA", fields: [:location]).results
```

But then I lose some other info.

Is there a good way to do this?

**Comment by vmvwebworks** [comment]
I need something for filter with something like
```
def value_field_query
 params[:hit_points] || "*"
end
@things = Thing.search query_name_value, fields: [:name], match: :word_start, where: {value_field: value_field_query]}
```
This must match the result or return all if the param comes empty. How?
