### ISSUE TITLE
word_start on every fields

### ISSUE THREAD

**Issue by Uelb** [ankane/searchkick#452]
Is it possible to enable the word_start or the text_start search on every fields ? I want to do autocompletes on any field of the search data. Is there a default configuration or something like this ?

**Comment by Uelb** [comment]
And if not ? How can I enable word_start on nested fields ?

**Comment by sandeepravi** [comment]
Did you figure out how to do this with a setting? Or a minor change in the gem?

btw @ankane, if we have word_start default on every field, it would also have to index :word in addition to :word_start, right?

**Comment by ankane** [comment]
Searchkick 1.1 makes this easier.

```ruby
class Product < ActiveRecord::Base
  searchkick match: :word_start
end
```

Reindex and search with:

```ruby
Product.search params[:query], fields: ["name^10", "description"]
```

**Comment by sandeepravi** [comment]
Excellent!

**Comment by MayankSG** [comment]
Excellent! +1
