### ISSUE TITLE
word_start on array field with highlighting

### ISSUE THREAD

**Issue by sandeepravi** [ankane/searchkick#453]
I have a problem where I have a word_start on an array field and I need highlighting as well but the highlighting does not seem to work.

```
Class Product
  searchkick word_start: [:normal, :array_field],
                    highlight: [:normal, :array_field]
end
```

then,

```
Product.search params[:term], highlight: {:fields => {:array_field => { :fragment_size => 25 }}}
```

So, this returns results but the highlight in empty. Is there a way to do a word_start on array fields with proper highlighting?

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
