### ISSUE TITLE
Range query doesn't work for :id field 

### ISSUE THREAD

**Issue by bogdanovich** [ankane/searchkick#458]
Searchkick converts id to _id which is incorrect, because id field could be a long value and _id is always a string.

``` ruby
def where_filters(where)
  filters = []
  (where || {}).each do |field, value|
  field = :_id if field.to_s == "id"  # why??
```

``` ruby
# returns nothing
Model.search("test", where: { id: { gt: 123455 }})
```

Current code generates the following query  that returns nothing 
`{"range":{"_id":{"from":1099511627779,"include_lower":false}}}`

It should generate the following query to return proper results
`{"range":{"id":{"from":1099511627779,"include_lower":false}}}`

**Comment by ankane** [comment]
Going to close. No plans to change how `id` is handled right now.
