### ISSUE TITLE
Inconsistent behaviour between development and production

### ISSUE THREAD

**Issue by tommi-lew** [ankane/searchkick#464]
I'm wondering if anyone had came across this situation, where the same search query returns different results on development and production.

Query: `Model.search('keyword', fields: [{attribute: :text_start}])`

In development: returns results
In production: returns nothing
- Ensured both are using 1.4.4
- Although database table is not completely the same, had ensured records with the same `label` attribute exist on both environment
- In development, runs on the same machine
- In production, using a managed instance on Bonsai
- Attempted to fix the situation by deleting all indices and rebuilding the index. Did this on both environments to ensure consistency.

**Comment by ankane** [comment]
Cleaning up issues. This seems like an issue with differences between environments rather than Searchkick.
