### ISSUE TITLE
Fix doc: when use string, the suggestion feature doesn't works

### ISSUE THREAD

**Issue by raphaelcuba** [ankane/searchkick#468]
The documentation is outdated. The feature "suggestions" says a String is used, but expects a Symbol.

PR: https://github.com/ankane/searchkick/pull/444

**Comment by ankane** [comment]
Hi @raphaelcuba, I can't reproduce. Can you create a failing test case?

**Comment by raphaelcuba** [comment]
Hi @ankane, I tried to replicate and it worked right. I do not work over the project I found this error. You can close the issue and the pr.

Thanks!

**Comment by ankane** [comment]
Thanks for following up.
