### ISSUE TITLE
Searching and joining multiple fields

### ISSUE THREAD

**Issue by agustaf9** [ankane/searchkick#469]
So I have 3 fields in the database I want to search. First name, middle name and last name. Lets say I have 3 names in the database:
* John Joe Smith
* John Joe Doe
* John Joe Snow

When searching for john all the results show up but as soon as I push space all the results disappear.

I have a method called full_name that looks like this:

    def full_name
      "#{first_name} #{middle_name} #{last_name}"
    end
Here's what the search method in my controller looks like:

    render json: Person.search(params[:query],
    fields: [{first_name: :text_start}, {last_name: :text_start}, {middle_name: :text_start}],
    where:{active:true},
    limit: 5).map {|person| {name: person.full_name, value: person.id}}

Here is what my model looks like:

    searchkick text_start: [:first_name, :middle_name, :last_name]

    def search_data
      as_json only: [:first_name, :last_name, :middle_name, :active]
    end

How can I search from all three fields at once?

**Comment by agustaf9** [comment]
See the bonus question here for more information.
http://stackoverflow.com/questions/30994009/twitter-typeahed-0-11-1-only-showing-one-result/31095631#31095631

**Comment by abevoelker** [comment]
I'd index `full_name` and let Elasticsearch do the work for you (this is its bread and butter after all). If your users don't need to search by the exact first, middle, or last name, you could just remove those from the index entirely:

```
searchkick text_start: [:full_name]

def search_data
  as_json only: [:full_name, :active]
end
```

...

```
render json: Person.search(params[:query],
fields: [{full_name: :text_start}],
where:{active:true},
limit: 5).map {|person| {name: person.full_name, value: person.id}}
```

If your users don't need to search for inactive users, you could also implement `should_index?`, which would allow you to remove `:active` from the `search_data` method and the where clause in your query (inactive people just won't be put in the index, so you don't have to filter).

**Comment by agustaf9** [comment]
Thank You! That worked.

**Comment by agustaf9** [comment]
Does my fullname method need to be self.fullname ?

**Comment by agustaf9** [comment]
I fixed it. For some reason `as json only[:full_name]` didn't work. I had to do `{full_name: full_name}`. I also changed it from text_start to text_middle to get people called by their middle name.

**Comment by ankane** [comment]
@agustaf9 You can do `as_json(only: [:active], methods: [:full_name])` as well.

**Comment by agustaf9** [comment]
Ill try that, thank you.
