### ISSUE TITLE
How should the configuration look like for a multi node server

### ISSUE THREAD

**Issue by daande** [ankane/searchkick#470]
I have a development server that acts as the web server and database (1 machine).  For production I have two separate servers one for the webserver and another for the database.  How would you configure elastic search / searchkick for this type of scenario?

**Comment by ankane** [comment]
Hi Dane, you can to set your `DATABASE_URL` to point to your database server and your `ELASTICSEARCH_URL` to point to your Elasticsearch server.

**Comment by daande** [comment]
Would it be more efficient to run the elasticsearch server on the same machine as the database or the webserver?

**Comment by ankane** [comment]
Since performance can depend on a number of factors, the best way to find out would be to test it out on both.

**Comment by daande** [comment]
So create a file in config/initializers/elasticsearch.rb 

In that append:

ENV["ELASTICSEARCH_URL"] = "ip of the elasticsearch server"
ENV["DATABASE_URL"] = "ip of the database server"

Then restart the webserver and run:

RAILS_ENV=production rake searchkick:reindex:all

**Comment by daande** [comment]
I tried the above and that worked.  Thanks for your help @ankane.  Closing this issue!
