### ISSUE TITLE
Having an issue with Draper 

### ISSUE THREAD

**Issue by hoasung01** [ankane/searchkick#471]
def index
       if params[:query].present? 
        @jobs = Job.search(params[:query], page: params[:page]).decorate
      else
        @jobs = Job.all.page(params[:page]).decorate
      end
    end

> undefined method `decorate' for #<Searchkick::Results:0x0000000bda7018>

**Comment by ankane** [comment]
@hoasung01 Unfortunately, I'm not familiar with Draper, but Searchkick does not provide a `decorate` method.

**Comment by hoasung01** [comment]
thanks @ankane
Is there any way to customize or add this method to Searchkick?

**Comment by ankane** [comment]
Looking at the Draper documentation, you can try:

```ruby
@jobs = JobDecorator.decorate_collection(Job.search(params[:query], page: params[:page]).results)
```

**Comment by hoasung01** [comment]
thanks alot @ankane

**Comment by chrise86** [comment]
Sorry to drag up an old issue, but I'm facing the same problem now. The problem is that by doing what @ankane suggests above, you are returned an array instead of an `ActiveRecord::Association`.
