### ISSUE TITLE
Searchkick 1.0

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#474]
[Branch](https://github.com/ankane/searchkick/tree/1.0)

Breaking ideas

- [x] transpositions by default
- [ ] do not use conversions by default
- [ ] do not stem conversions by default
- [x] misspellings for partial matches by default
- [ ] min prefix of 2 for misspellings by default
- [ ] do not use natural log by default for boosts
- [ ] large default fragment size for highlighting
- [x] lazy searching
- [ ] use `default_mappings` instead of `merge_mappings` and default to `true`
- [x] raise dangerous reindex operations (unless flag is passed - `danger: true`)
- [ ] remove load option (no need with lazy loading - how to handle fields)

Probably not

- [ ] make `word_start` the default

Non-breaking ideas (no need to wait to release)

- [ ] prefix reserved terms in `where` clause with underscore (`_not`, `_gt`, etc) and allow them to be nested for more powerful boolean operations
- [ ] make it easier to update synonyms
- [ ] manage process of reindexing with millions of records
- [x] aggregations
- [ ] bulk indexing
- [ ] kaminari pagination
- [x] change `language` option to `stemmer`
- [x] document results object
- [ ] document word_start, text_start, etc
- [ ] default synonyms
- [ ] support for nested objects
- [x] prefix methods with searchkick & alias
- [ ] perform mapping update if possible without reindex
- [ ] debug method to show `search_data`, mapping, indexed data, etc
- [ ] add highlighted methods
- [ ] cross field searches

**Comment by jonathansimmons** [comment]
:+1:  for kaminari pagination.

**Comment by sanjitsaluja** [comment]
@ankane Do you know if 1.0 is close to release? I'm starting work on a new project would like to use 1.0, if possible.

**Comment by ankane** [comment]
Cleaning up issues
