### ISSUE TITLE
How make the search return all indexed fields?

### ISSUE THREAD

**Issue by samur-vonq** [ankane/searchkick#476]
A search on searchkick returns only the id of indexed entity. 
Example:
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "webshop_v1_channels_development_20150716101258847",
      "_type" : "channel",
      "_id" : "471",
      "_score" : 1.0
    }, {
      "_index" : "webshop_v1_channels_development_20150716101258847",
      "_type" : "channel",
      "_id" : "905",
      "_score" : 1.0
    }  ]
  }
}

Is it possible to force searchkick to return all indexed fields or specific ones?

Best

**Comment by ankane** [comment]
With `load: false`, all fields are returned.  If you still want to load models, you can use `select: true`.
