### ISSUE TITLE
losing sync at least 3 times a week

### ISSUE THREAD

**Issue by magicmarkker** [ankane/searchkick#477]
Hi, I have a multi tenant app that uses searchkick for searching users, and at least three times a week it becomes out of sync and the search throws a `undefined method 'each' for nil:NilClass` If I run the same code in console, it returns properly.

    def search
      params[:page] ||= 1
      params[:keyword] ||= "*"
      @users = User.active
      @users = @users.search(params[:keyword], operator: "or", fields: [{firstname: :word_start}, {lastname: :word_start}, {email: :word_start}, {companyname: :word_start}, {additional_text: :word_start}, {board_title: :word_start}, {userclass: :word_start}] ) rescue nil
    end
I followed the instructions on the setup page, and this is my user.rb file.

    searchkick word_start: [:firstname, :lastname, :email, :companyemail, :companyname, :additional_text, :board_title, :userclass, :phone, :companyphone], settings: {number_of_shards: 1}

      def search_data
        as_json only: [:firstname, :lastname, :email, :companyemail, :companyname, :additional_text, :board_title, :userclass, :phone, :companyphone]
      end

**Comment by ankane** [comment]
@magicmarkker the problem is `nil` is returned on an exception.  You can probably `rescue []` to fix, but I'd recommend reporting or logging the original error to see what's actually wrong.
