### ISSUE TITLE
serialize response to array

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#479]
Hi i have two models both using searchkick. However for one of them if i do 

results = Profile.search "c++" 
results.to_a => i am getting list of all Profile objects 
However for the second model, it gives me an empty array. The hits in the response however is non empty. so 

results = Review.search "word"
results.to_a is [] and results.hits is not empty.

Both the models are setup identically with custom search_data. I am not sure why .to_a is not working in the second model. I have tried Review.reindex multiple times and it doesn't appear to be helping

**Comment by peddinti** [comment]
ping...

**Comment by ankane** [comment]
...pong :)

**Comment by peddinti** [comment]
hehe ... LOL! any comments on the issue :D

**Comment by ankane** [comment]
If `hits` is populated but `to_a` is not, Searchkick most likely can't find the records in the database.  Can you see what database query it triggers and run it by hand?

**Comment by peddinti** [comment]
Thanks ankane! i found the issue. it seems that model.reindex is creating index but as you said it is not creating record or link to database because database has record. the problem turns out that elastic search was throwing exception when saving the object as the id for that object was missing so that is why the results are not coming.

Thanks again!
