### ISSUE TITLE
Duplicate results and memory usage

### ISSUE THREAD

**Issue by junhanamaki** [ankane/searchkick#48]
Hi.

I've run into two problems and couldn't solve them, so I'm hoping you could help me:

1 - I'm getting duplicate results for (from what I can see) every search, meaning that if I do a Model.search("<name>") it will return an array with repeated results (duplicate objects with the same id). I've tried Model.reindex, Model.tire.index.refresh, Model.clean_indices and nothing seems to solve this issue. The best I can tell for now is that I have two indices for the same model (), created on different dates. How did this happen, and how can I solve this?

2 - How much memory should elasticsearch be consuming? I'm indexing a table with something like 300 lines by 7 attributes and it's already consuming 400MB, I'm afraid that this could easily blow up when the application starts to get heavy usage.

Thank you for any help regarding these issues, and also for the awesome gem.

Best regards.

**Comment by jbmyid** [comment]
I was having same issue, was getting duplicate entries. We indexed the user and it had one STI model.
Fixed with type while search.

eg. User.search(where: {id: [1]}, type: User)

hope someone will find this usefull

**Comment by joe1chen** [comment]
@jbmyid We were seeing this as well when a STI model was indexed.  Adding the `type` parameter to the search fixed the issue. Thanks for the workaround.  In my opinion this is a bug with Searchkick.  You shouldn't have to know to add the `type` to the search for STI models.

**Comment by ankane** [comment]
Hey @joe1chen, can you create test case for what you're expecting? https://github.com/ankane/searchkick/blob/master/test/inheritance_test.rb
