### ISSUE TITLE
Removing default 'extend' hooks from the base 'searchkick' require file

### ISSUE THREAD

**Issue by jfelchner** [ankane/searchkick#481]
I think that including searchkick into _every single_ model in my application is a bit of overkill.  That, and the user should be able to opt out of that behavior if they need something custom.

I think that telling people that they need to add an initializer (or having a generator that does so) to extend the `Callbacks` and having people put `extend Searchkick::Model` in the models that they want to extend is not too much to ask and makes the functionality that has been mixed into the class explicit.

https://github.com/ankane/searchkick/blob/master/lib/searchkick.rb#L70-L72

**Comment by ankane** [comment]
Hey @jfelchner, thanks for the input. I don't think adding an additional method to each model is overkill, so closing as "won't fix".

**Comment by jfelchner** [comment]
@ankane but what is the point if I know I'm not going to use it for searching?  The only thing it can do is cause problems.
