### ISSUE TITLE
Using Searchkick/Sidekiq to Update Index on Heroku Results in Issues

### ISSUE THREAD

**Issue by taylor-a-barnette** [ankane/searchkick#483]
First off, I love this gem *and* its documentation. Great work! Second, I'm new to ElasticSearch, so bear with me. My question is regarding async updates of ElasticSearch on Heroku. Hopefully this will provide clarity to others out there as well as I couldn't find any answers on the web about it.

I've deployed my app to H using the add-on SearchBox, and I am using Sidekiq to schedule reindexing to keep my index updated. Code is below. When I first deploy the code (i.e., no indices exist), everything works: an index is created and data is added as you would expect. However, when my app tries to reindex 5 minutes later to keep things updated, SearchBox tells me I am trying to create too many indices. So my quesiton is: I thought reindex updated the index? Does it actually create a new one? If it does, then how would I update? It appears the only way to update (asyncly) an index is by using ActiveJob as you point out in the documentation - but does that use the reindex method as well? In other words would SearchBox tell me the same thing, or does implementing the code you provide for ActiveJob *not* reindex? Thanks in advance for any help!

Sidekiq worker
```
class ReindexSearch
	include Sidekiq::Worker
	include Sidetiq::Schedulable
	recurrence { minutely }

	ReindexSearch.perform_async

	def perform
		ActiveRecord::Base.connection_pool.with_connection do
			ActsAsTaggableOn::Tagging.reindex
		end
	end
end
```
Model I've Applied Searchkick To:
```
module ActsAsTaggableOn
	class Tagging < ::ActiveRecord::Base
		searchkick
		searchkick callbacks: :async

		def search_data
			{
				id: id,
				tag_id: tag_id,
				taggable_id: taggable_id,
				taggable_type: taggable_type,
				created_at: created_at,
				tag: {
					name: tag.name
				},
				taggable: {
					title: self.get_title # see get_title method documentation above
				}
			}
		end
	end
end
```

**Comment by ankane** [comment]
Hi Taylor, Searchkick requires two indices per model during a reindex.  It creates a new index, imports all records, and swaps the alias.

**Comment by ankane** [comment]
Cleaning up issues. SearchBox offers 2 indices in the [free plan](https://elements.heroku.com/addons/searchbox), so you should be able to use Searchkick with it.

**Comment by taylor-a-barnette** [comment]
The reply on Jul 28th was really helpful, and I should've said as much earlier. Thanks, and thanks very much for Sidekiq, it's indispensable!
