### ISSUE TITLE
rspec clean elastic search?

### ISSUE THREAD

**Issue by netwire88** [ankane/searchkick#486]
Hi,
I'm writing some rspec tests to use with searchkick. In my `spec_helper.rb`, I currently use `DatabaseCleaner` to clear my database. How do I clear my ElasticSearch instance? 

Also, what's the best practice for ES testing? Do you create another ES instance and point the spec_helper.rb to a separate ENV['ELASTICSEARCH_URL'] than `http://localhost:9200`?

Here's part of my `spec_helper.rb`:

```
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
    Capybara.javascript_driver = :webkit
  end
  config.before(:each) do
    Rails.cache.clear
    DatabaseCleaner.start
  end
  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

**Comment by Mavvie** [comment]
Hey, a few things I learned about testing with Searchkick.

1. You don't need a separate elasticsearch instance. I'm just using a fresh install and it keeps the test, dev, and production data namespaced separately.
2. Before using any `search` calls, but after creating the rows+relations, call these two methods on your model:
```Ruby
    Product.reindex
    Product.searchkick_index.refresh # don't forget this
```
3. Don't worry! I found it extremely simple to get it to work in tests. Here's an example test I have in a project: https://gist.github.com/Mavvie/98d7c505286d7cf03590
`ProductSearch.new` is a wrapper around `Product.search()`.

Is there any specific reason for you to clear your ES instance between test runs that you can't handle in a `before` block in your test?

**Comment by netwire88** [comment]
Thanks @mavvie. Great answer. I have a few (probably too simple) questions. How do you keep the ES namespace separate? I currently use 'redindex', how's that different from 'searchkick_index.refresh', and why would I need both?

**Comment by Mavvie** [comment]
To keep the ES namespaces separate, just make sure the RAILS_ENV is different. Searchkick handles the rest.

```sh
$ rails c development
> Product.searchkick_index.name
   => "products_development"

$ rails c test
> Product.searchkick_index.name
   => "products_test"
```

The `searchkick_index.name` is what it uses as a namespace to communicate with elasticsearch.

I have no idea what the `refresh` does (I think something about shards or the more advanced features maybe). Maybe @ankane can shed some light on this function? 

I found this https://github.com/ankane/searchkick/blob/f8714d22778e450a5eacd0e4acbca000142b1812/lib/searchkick/index.rb#L22-L24 , but don't see why it's necessary.

Cheers

**Comment by Mavvie** [comment]
Also, the author wrote this stackoverflow answer on a similar question: http://stackoverflow.com/a/21816442/2566016

**Comment by vinchi777** [comment]
Im having this in my rspec tests.
```
Faraday::Error::ConnectionFailed: getaddrinfo: nodename nor servname provided, or not known
```
Also if I try to use Webmock which block external requests Im seeing this.
```
Real HTTP connections are disabled. Unregistered request: PUT http://ip-10-84-65-243.ec2.internal:9200/rets_properties_test/rets_property/55c87d60b612c0d602000006 with body '{"address1":"test","city_state_zip":"Austin, TX 1234"}' with headers {'Accept'=>'*/*', 'Content-Type'=>'application/x-www-form-urlencoded', 'User-Agent'=>'Faraday v0.8.9'}
```

Is searchkick using a remote server for the test environment?

**Comment by netwire88** [comment]
Thanks @Mavvie, that makes a lot of sense. That's why sometimes I get odd test results and it goes away when I run again, the `refresh` will hopefully fix that.

**Comment by Mavvie** [comment]
Glad I could help!
