### ISSUE TITLE
Using body for advanced search nullifies where clause

### ISSUE THREAD

**Issue by ericsteen** [ankane/searchkick#487]
If I do an advanced search with searchkick for elasticsearch-rails like so:

    products = Activity.search body: {query: {bool: {must: [{ range: { min_age: {lte: 5} } }, { range: { max_age: {gte: 3} } } ] } } }, where: { category: "Programs", start_time: '2015-07-22' }

... the where clause is not being applied. Is this to be expected? Must I use body to achieve all of my queries? Is there a way to get around this in searchkick?

slow log output: 

 `[2015-07-29 21:03:53,369][INFO ][index.search.slowlog.query] [ES Dev] [activities_development_20150729165655530][2] took[21.1ms], took_millis[21], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"bool":{"must":[{"range":{"min_age":{"lte":5}}},{"range":{"max_age":{"gte":3}}}]}}}], extra_source[],`

**Comment by igorbelo** [comment]
yes, this is the expected behavior...
when the `body` option is passed, searchkick just ignores all other options.
(See the line)[https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L58]

**Comment by ankane** [comment]
Correct, this is the expected behavior.  I've added a note to the readme.
