### ISSUE TITLE
Regexp is not supporting case insensitive searches

### ISSUE THREAD

**Issue by swaathi** [ankane/searchkick#491]
I'm trying to use regex's to enhance my serach. Everything works well when the user types out the matching word in the exact format (uppercase/lowercase). The same issue occurs even when giving the `/i` option. Is there something specific I should do to allow regex case-insensitive searches?

Typing the exact case,

![screen shot 2015-08-05 at 5 46 46 pm]
(https://cloud.githubusercontent.com/assets/5551587/9085390/fbc50c08-3b99-11e5-8c90-a949e4d7af88.png)

Typing lowercase, 

![screen shot 2015-08-05 at 5 46 37 pm](https://cloud.githubusercontent.com/assets/5551587/9085399/0d06c9a2-3b9a-11e5-89e6-a3fec62db87d.png)

**Comment by igorbelo** [comment]
As far as I know, it's not possible even directly in ElasticSearch.
An ugly workaround could be to put `facebook` word variations into an `or` filter...something like:
```
Company.search("be", where: { or: [[{ short_desc: /.*facebook.*/ }, { short_desc: /.*Facebook.*/ }]] })
```

Let me know if it works for you

**Comment by swaathi** [comment]
That's too bad. Thanks for helping out. But unfortunately, my problem needs it to be completely case-insensitive. 😔
