### ISSUE TITLE
callbacks are not working when using sidekiq in inline mode with rspec

### ISSUE THREAD

**Issue by gudata** [ankane/searchkick#493]
I have
Before filter: 

```
StreamEntry.destroy_all
StreamEntrySearch.new.delete_index
Sidekiq::Testing.inline!
```

the test

```
stream_entry = create_stream_entry
StreamEntry.reindex
delete :destroy, id: stream_entry.id
```

after that we expected to be deleted from the index but it isnt.

We have put debug messages in all the Reindex modules, but no one triggers. 

Is there something which is not playing well with sidekiq?

**Comment by ankane** [comment]
Cleaning up old issues. Feel free to reopen if this is still relevant.
