### ISSUE TITLE
Suggest not working

### ISSUE THREAD

**Issue by chrise86** [ankane/searchkick#494]
I have a `Postcode` model with `postcode` and `slug` attributes. When using:

    # models/postcode.rb
    searchkick suggest: ['postcode']

    def search_data
      {
        postcode: postcode,
        slug: slug
      }
    end

    # controller
    @results = Postcode.search params[:pc], suggest: true

I get:

    Searchkick::InvalidQueryError

Further down the stack trace I see:

    ElasticsearchIllegalArgumentException[No mapping found for field [postcode.suggest]];

 Any ideas?

**Comment by lmorais** [comment]
+1

**Comment by ankane** [comment]
Be sure to run `Postcode.reindex` after changing `searchkick` options.

**Comment by chrise86** [comment]
Yep, first thing I did :)

**Comment by ankane** [comment]
I'm not sure what it could be. Can you try writing a failing test case for it?

**Comment by endorfin** [comment]
+1

```
{
name: "Merlin",
cluster_name: "elasticsearch_endorfin",
version: {
number: "2.1.0",
build_hash: "72cd1f1a3eee09505e036106146dc1949dc5dc87",
build_timestamp: "2015-11-18T22:40:03Z",
build_snapshot: false,
lucene_version: "5.3.1"
},
tagline: "You Know, for Search"
}
```

**Comment by ankane** [comment]
Cleaning up issues.  If it's still a problem, please try adding a failing test case, as I'm not able to reproduce.

**Comment by endorfin** [comment]
Solution for the problem: restart your application
