### ISSUE TITLE
field_value_factor modifier

### ISSUE THREAD

**Issue by samur-vonq** [ankane/searchkick#498]
Hi all, 
Is there any way to specify the field_value_factor modifier in the boost_by parameter?

Example:
boost_by: {orders_count: {factor: 10, modifier: sqrt}}

Currently, the searchkick seems to use the ln2p as a default modifier.

Any help will be appreciated.

**Comment by ankane** [comment]
@samur-vonq not currently, but sounds useful. Feel free to submit a pull request.

**Comment by TrevorHinesley** [comment]
Is it possible to do this similar to the workaround here?

https://github.com/ankane/searchkick/issues/241

**Comment by ankane** [comment]
This was added in 2.5.0.
