### ISSUE TITLE
Skip loading from database

### ISSUE THREAD

**Issue by navaneeth** [ankane/searchkick#501]
I have a `Product` model and i have indexed all the fields that I need. Now when I do

```ruby
products = Product.search term
puts products.first # DB queries are fired here
```

I have even tried with `load: false` and getting the same behavior. Is there a way to map searchkick results directly to the model so that no queries are fired. 

In the same model, I also have a method which looks like the following:

```ruby
require 'json'
class Product < ActiveRecord::Base
	searchkick autocomplete: ['title', 'brand'], callbacks: :async
	scope :search_import, -> { includes(:product_offers) }

	def lowest_offer
		if @lowest_offer.nil?
			@lowest_offer = product_offers.order(:selling_price).first
		end
		@lowest_offer
	end

	def lowest_offer=(offer)
		@lowest_offer = offer
	end
end
```

`lowest_offer` is also indexed. So I'd assume when I get results from search, it should set the `lowest_offer`. This is also not happening. 

Any idea to fix this?

**Comment by igorbelo** [comment]
You can access the `hits` hash directly:
```ruby
products.hits
```

**Comment by ankane** [comment]
Also, `load: false` will not load records from the DB (unless you have other code in your application which does).

**Comment by navaneeth** [comment]
Works well.
