### ISSUE TITLE
Passing in Ranges with an upper bound of Infinity should work as expected

### ISSUE THREAD

**Issue by jfelchner** [ankane/searchkick#502]
Sometimes you allow users to generate ranges and sometimes you don't require them to specify and upper bound.  In which case in Ruby, you would do something like:

``` ruby
Range.new(my_starting_input, Float::INFINITY)
```

When `searchkick` sends this over to ElasticSearch, it sends it over like this:

``` json
{
  "auction_price_cents": {
    "from": 0.0,
    "include_lower": true,
    "to": Infinity,
    "include_upper": true
}
```

Which throws a parsing error.  If `Infinity` is passed in, it should know to exclude the upper bound.

**Comment by ankane** [comment]
Thanks Jeff, feel free to submit a pull request.

**Comment by gerrywastaken** [comment]
@jfelchner @ankane Maybe it should just convert Float::INFINITY to "Infinity" and -Float::INFINITY to "-Infinity" as elasticsearch supports this. Any issues with that approach?

**Comment by ankane** [comment]
@gerrywastaken Seems like it should work. Happy to accept a PR.
