### ISSUE TITLE
Model.reindex performance

### ISSUE THREAD

**Issue by navaneeth** [ankane/searchkick#507]
I have a Product model with 50million products. If i have to regenerate the index, when I do, `Product.reindex`, it takes long time. So I was wondering is there a smarter way to recreate the index for such huge data?

I was thinking about iterating over products and queuing each `product.reindex` to background sidekiq workers so that products gets re-indexed concurrently.

**Comment by ankane** [comment]
See my comment here https://github.com/ankane/searchkick/issues/334#issuecomment-65186188

**Comment by ankane** [comment]
Cleaning up issues
