### ISSUE TITLE
"NameError","uninitialized constant Jobboard::Position"

### ISSUE THREAD

**Issue by vigneshrams** [ankane/searchkick#508]
Hi,

I am trying to add index only for particular fields in my DB. But i am not able to index it.  I get below error,

{"id":1,"exception":["NameError","uninitialized constant Jobboard::Position"]}

def search_data
    {
      Position: Position,
      Job_company: Job_company
    }
  end

What am i Missing ? 

Thanks

**Comment by ankane** [comment]
Hi @vigneshrams, it looks like `Position` is not defined in your app.

**Comment by vigneshrams** [comment]
Position is column in my DB which i want to index. How do i define it ? Help me on this please.


Thanks

**Comment by ankane** [comment]
Try:

```ruby
def search_data
{
  position: position,
  job_company: job_company
}
end
```

assuming, job_company is also a column in your database.

**Comment by ankane** [comment]
Or if the column is capitalized, I believe you can do:

```ruby
def search_data
{
  position: attributes["Position"],
  job_company: attributes["Job_company"]
}
end
```

**Comment by vigneshrams** [comment]
Yep i tried that already but didn't help. I get the error again.

**Comment by vigneshrams** [comment]
ok let me try this, 
def search_data
{
  position: attributes["Position"],
  job_company: attributes["Job_company"]
}
end 

and let you know.

Thanks

**Comment by vigneshrams** [comment]
That solved the problem. Thanks a lot

**Comment by ankane** [comment]
Great, glad it's working.
