### ISSUE TITLE
Sarchkick issue: A and (B or C)

### ISSUE THREAD

**Issue by rdlh** [ankane/searchkick#510]
Hi!

I use searchkick for a long time from now, and i love it.
**I have this query:**

```rb
City.search(@query, where: {
  activated: true,
  available: true,
  or: [
    [
      { country_id: [92, 95] },
      { admin_code_id: [922, 927] }
    ]
  ]
}).
```

But i think the where hash is not good, because the thing i want to do is:

`activated` **AND** `available` **AND** **(**`country_id` **IN** `[92, 95]` **OR** `admin_code_id` **IN** `[922, 927]`**)**

Is that actually possible with the `searchkick` gem ?

Thanks in advance, Rémi

**Comment by ankane** [comment]
Unfortunately, advanced boolean logic is pretty limited right now with the `where` option.  You'll need modify the query generated by Searchkick, as [documented here](https://github.com/ankane/searchkick#advanced-search).

**Comment by ankane** [comment]
Cleaning up issues
