### ISSUE TITLE
Expose curl request string on Searchkick::Results instances

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#512]
Really useful for debugging if I can do:

```ruby
results = MyClass.search('*')
results.request_details_as_curl
```

Any thoughts on this?

**Comment by ankane** [comment]
Sounds reasonable.  How about `to_curl`?

**Comment by mehulkar** [comment]
`response.to_curl` seems weird? maybe a more appropriate solution would be to implement `to_curl` on the Query object and give Response objects a reference to the Query object? It might be unnecessary bloat for the response object though.

**Comment by ankane** [comment]
Unfortunately, `MyClass.search('*')` doesn't return a request object (which is the plan for Searchkick 1.0).

**Comment by ankane** [comment]
On master, you can do:

```ruby
query = MyClass.search("*", execute: false)
query.to_curl
```

**Comment by mehulkar** [comment]
nice!
