### ISSUE TITLE
Filtering by multiple ranges on the same key

### ISSUE THREAD

**Issue by mehulkar** [ankane/searchkick#514]
Using the filtering by ranges feature for the first time. It looks like this doesn't work:

``` ruby
MyModel.search('*', where: {priority: 0..20, priority: 70..100})

# or with lte,gte
MyModel.search('*', where: priority: {lte: 20, gte: 70})

# or with multiple keys:
MyModel.search('*', where: priority: {lte: 20}, priority: {gte: 70} })

# or as an array
MyModel.search('*', where: priority: [{lte: 20}, {gte: 70}] })
```

I haven't looked at the query generation for a while, do you think this should be straightforward? Or is there another way to do this that i'm not trying?

**Comment by mehulkar** [comment]
We might be able to adapt [this line](https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L477-L479)

```ruby
          if value.is_a?(Range)
            value = {gte: value.first, (value.exclude_end? ? :lt : :lte) => value.last}
          end
```

to accommodate more than one range filter. At first glance, I don't think there's anything in ES that will prevent this

**Comment by ankane** [comment]
You can use or for this.

```ruby
where: {or: [
  [{priority: 0..20}, {priority: 70..100}]
]
```

**Comment by mehulkar** [comment]
Oh, the `or` key is used to "or" a set of options, not as an "or" to the rest of the where clause? 
Heh, I definitely understood that wrong.
