### ISSUE TITLE
removing old data from index

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#515]
I am having elastic search over data and as data gets old, i want to remove it from index to conserve the index size as the old data will never be surfaced to user (the application is like a recommendations where recent items are boosted and users cant search for old data).

One solution is to use the date in should_index? function but it only works if i try to save that object again in future. if the object is not modified, the index continues to stay. 

So is there a way i can set a expiry time on a document ?

**Comment by ankane** [comment]
It looks like you can use a custom mapping to [add a ttl](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html), but I've never tried it.

**Comment by peddinti** [comment]
Hi i have tried it the following way (my .rb file has)
searchkick merge_mappins: true, mappings: { feed_items: {_ttl: {enabled: true, default: '180d'}}}

FeedItems.reindex works good. But search is failing. it says 
nested: QueryParsingException[[feed_items_development_20151007085928849] [match] analyzer [searchkick_search] not found];

any idea why?

**Comment by ankane** [comment]
Looks like a slight misspelling: `merge_mappins` => `merge_mappings`.

**Comment by ankane** [comment]
Cleaning up issues
