### ISSUE TITLE
Search results does not sort by score when specifying order and boost_where together

### ISSUE THREAD

**Issue by toyray** [ankane/searchkick#517]
When specifying `order` together with `boost_where`, the returned result does not take into consideration the boosted scores. This is due to the `order` clause overwriting the default descending `_score` sort order.

Below is the test case for this scenario

```ruby  
def test_boost_where_with_order
    store [
      {name: "Tomato A"},
      {name: "Tomato B", color: "red"},
      {name: "Tomato C", color: "green"}
    ]
    assert_first "tomato", "Tomato B", boost_where: {color: { value: "red", factor: 100 }}
    assert_first "tomato", "Tomato B", boost_where: {color: { value: "red", factor: 100 }, 
order: ["_score", { name: :desc }]}
    # Setting explicit order fails because no longer sorting by score first
    assert_first "tomato", "Tomato B", boost_where: {color: { value: "red", factor: 100 }, 
order: [{name: :desc}]}
  end
```

I'm currently working around this issue in our application by prepending `'_score'` in our `order` array whenever we have a `boost_where` condition.

I'm unsure if this should be handled within the application or in Searchkick itself as I don't know the implications of modifying a user-specified `order` clause for the other boosting conditions since we only use `boost_where`.

**Comment by ankane** [comment]
Hey Roy, this is the expected behavior.

**Comment by toyray** [comment]
@ankane, thanks for the clarification! Closing this then since it's a non-issue :grinning:
