### ISSUE TITLE
Smart facets not applying where conditions to facet filter of the same name

### ISSUE THREAD

**Issue by jaredcwhite** [ankane/searchkick#519]
Seems to be a problem with line 314 of query.rb:

``` ruby
facet_options.deep_merge!(where: options.fetch(:where, {}).reject { |k| k == field } ) if options[:smart_facets] == true
```

The reject method there is removing the where conditions for a facet filter of the same name. So if you do where: {color: "blue"} and apply smart facets, and one of the facets is color, it won't actually add that color condition to the facet filter, and thus you will get an incorrect color count.

I changed the line to this:

``` ruby
facet_options.deep_merge!(where: options.fetch(:where, {})) if options[:smart_facets] == true
```

and that works. I can submit a PR for this but I'm concerned that the reject method is there for some other reason I don't currently understand. Anyone else run into this issue? (I found a few closed issues that maybe touched on it, such as #236 )

**Comment by igorbelo** [comment]
it's the expected behavior of `smart facets`.
the `reject` method allows us to select multiple terms of the same field.
it's like a checkbox: "I want to count the docs where color equals to `blue` OR `red`".

if you don't want this, you should not pass the `smart_facets: true` option.
(Take a look)[http://distinctplace.com/2014/07/29/build-zappos-like-products-facets-with-elasticsearch/]

**Comment by jaredcwhite** [comment]
@igorbelo Thanks for the link there. I can see that use case, but I can also see my use case where a selected option shouldn't kick that field out of the facet filtering. Seems like that should be something that's configurable. Anyway, I appreciate the explanation!

**Comment by zspencer** [comment]
I'm in a similar boat to @jaredcwhite; 

Consider the following use case:

I have a flavors field that is an array: `["Sweet", "Savory", "Spicy", "Bitter"]`
Some of our foods can be sweet *and*  spicy or savory *and* bitter
When I initially drill down:

```
foods = Food.search("*", where: flavor: ["Sweet"], aggs: [:flavor])
```
I discover that `foods.aggs` now includes buckets for every single food in the database; not merely the sweet foods!

Instead, I would prefer if `foods.aggs` included only the buckets that match the where clause of `flavor: "Sweet"`

I'm not sure what the phrasing for this would be, maybe it could be configurable with something like `smart_aggs: :drill_down`?

**Comment by zspencer** [comment]
The workaround we wound up using is specifying the where clause on a per-term basis:

```
Food.search("*", where: flavor: ["Sweet"], aggs: { flavor: { where: { flavor: "Sweet" } } })
```

Which ensures that the aggregation uses the filter even if it is being rejected due to `smart_aggs`

**Comment by ankane** [comment]
Thanks for taking this one @zspencer 👍
