### ISSUE TITLE
Multi-Search and Where

### ISSUE THREAD

**Issue by hallmatt** [ankane/searchkick#520]
It looks like there are a couple different ways to get multi-search working. 

I have two models (Page and Machine), and want to search records of both models, so I'm using the following code:

``` ruby
Machine.search("TEST QUERY",  :index_name => Searchkick.client.indices.get_aliases.keys) 
```

This seems to work well, however I'd like to add a where clause that might be different for each model. For example, find all Machine and Page records, but limit the Machines where status = 'New' and active = true. Is this possible?

Love the gem! I've been using the pg_search gem and this knocks that out of the park!

**Comment by hallmatt** [comment]
Is this even possible?

**Comment by hyfen** [comment]
You can use the "_type" key in the where condition. 

```

**Comment by hyfen** [comment]
I think you can use the "_type" key in the where conditions to make this happen: ```where: { or: [[{:"_type" => 'model1', condition: 'value'}, {:"_type" => 'model2', condition: 'value'}]]}```

**Comment by hallmatt** [comment]
@hyfen thanks for the response!

I tried this:

```
Machine.search("*", where: { or: [{:"_type" => 'Machine', condition: {:status => "S"}}, {:"_type" => 'Page', condition: {}}]},  :index_name => Searchkick.client.indices.get_aliases.keys)
```

And get an error saying

```
QueryParsingException[[pages_development_20150922153415957] [missing] filter does not support [status]];
```

So close! I had to take out the double array and make it a single array. Any other ideas? I've been meticulously searching through different issues to try and piece it together.

**Comment by hallmatt** [comment]
I also tried the singular, lowercase model name for both...

**Comment by ankane** [comment]
Keep the double array and take out the `condition` key.

```ruby
Machine.search("*", where: { or: [[{:"_type" => 'Machine', :status => "S"}, {:"_type" => 'Page'}]]}, :index_name => Searchkick.client.indices.get_aliases.keys)
```

**Comment by hallmatt** [comment]
Thanks so much!

**Comment by hallmatt** [comment]
This syntax is working real well, but would now like to boost some fields and use word_start, word_middle, etc. 

I've tried a couple variations, but nothing that seems to work. Here's one I tried:

```
Machine.search("*", fields: [{"model_description" => :word_start}], where: {or: [[{:"_type" => 'machine', :status => "S"}, {:"_type" => 'page'}]]}, :index_name => Searchkick.client.indices.get_aliases.keys)
```

**Comment by hallmatt** [comment]
Perhaps this isn't possible - but could be helpful if it is!
