### ISSUE TITLE
IndexAlreadyExistsException when using Timecop

### ISSUE THREAD

**Issue by jfelchner** [ankane/searchkick#521]
Because `searchkick` uses a timestamp at the end of its index names, when you attempt to test the searchkick behavior while also using Timecop, you regularly run into problems because on every test run, the timestamp is the same.

**Comment by jfelchner** [comment]
I also think that this was due to a recent change because our specs ran fine until recently.

**Comment by ankane** [comment]
One option is to delete the previous index before reindexing with `Model.searchkick_index.delete`.  This has been a feature of Searchkick for a while, so I'm not sure it's due to recent change.
