### ISSUE TITLE
word match

### ISSUE THREAD

**Issue by mastermike14** [ankane/searchkick#523]
Searching by word_start will allow "The Avengers" to show up when searching for "Avengers" but if something is named "Avenger" it will not be in the search results.

**Comment by paritoshbotre** [comment]
@mastermike14 ,
I have tried this, but it's seems working.

Here is the screen shot

![searchkick_example](https://cloud.githubusercontent.com/assets/8109523/12355329/e04c60fe-bbc1-11e5-942b-63bb6aa10faf.png)

Please correct me, if you think I misunderstood your problem.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
