### ISSUE TITLE
Polymorphic search

### ISSUE THREAD

**Issue by th3m4ri0** [ankane/searchkick#524]
Is it possible to do a polymorphic search ? Say I have 3 classes : 
-  ```Human```
- ```Dog```
-  ```Cat```

They all share 3 attributes : 
- ```name:string```
- ```favorite_food:string```
-  ```weight:number```

```Dog``` and ```Cat``` also have a ```fur_color:string``` attribute.  
Is there any way to do a search on this family of classes ?

**Comment by hyfen** [comment]
This will do the trick: ```Human.search("*", index_name: [Human.searchkick_index.name, Dog.searchkick_name.name, Cat.searchkick_index.name])```

**Comment by th3m4ri0** [comment]
Works like a charm ! Thanks @h :ok_hand:
