### ISSUE TITLE
Set custom _index and _id per index

### ISSUE THREAD

**Issue by mmahalwy** [ankane/searchkick#525]
How can I set my own _index and _id inside `search_data`

It doesn't seem to work...

**Comment by ankane** [comment]
No way to do this at the moment.

**Comment by izaban** [comment]
I solve this for the _id by overwriting the search_id method of the Searchkick::Index class. This method is responsible for setting the _id when indexing. Maybe this trick can be added to the docs in the Indexing section?

**Comment by mmahalwy** [comment]
@ankane any luck with this?

@izaban can you show me an example? I'd really appreciate it!

**Comment by ankane** [comment]
The latest version supports a `search_document_id` method for `_id`.

**Comment by mmahalwy** [comment]
Awesome @ankane !
