### ISSUE TITLE
Issue using conversions

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#528]
Hi, i am trying to use conversions in my seach kick .. this is how i set up

searchkick conversions: "followers_tags"

def search_data
...
{
        ...
        followers_tags: {"c++" => 5, "perl" => 6},
    }

when i so .reindex then so a simple search like model.search "c++", i am getting the following error
[nested] nested object under path [followers_tags] is not of nested type]; }]","status":400}

i am not sure why it is not working

**Comment by peddinti** [comment]
I think i figured out the problem ... i think the name always has to be "conversions"
so 
searchkick conversions: "conversions" work! Interesting...

**Comment by ankane** [comment]
Hi @peddinti, glad you got it working.  The conversion field is configurable, so you should be able to use `followers_tags`.  The error message above indicates you needed to run a full reindex - `Model.reindex`.

**Comment by ankane** [comment]
And just found the issue when working on Elasticsearch 2.0 support.  Thanks for reporting!
