### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by vikigenius** [ankane/searchkick#529]
How do i specify the proxy settings (I already have my system proxy environment variables set up)

When i do 

    rake searchkick:reindex CLASS=ClassName
I get a HTTP 403 error, which i am sure is because of the proxy.
How do i resolve this, is there a way to specify the proxy settings in an initializer somewhere?

**EDIT**
I think the problem is that it is searchkick is using my environment proxy settings for localhost connections too.
How do i bypass proxy for localhost?

**Comment by ankane** [comment]
Dup of #530
