### ISSUE TITLE
Autocomplete and search across multiple models

### ISSUE THREAD

**Issue by mishrarohit** [ankane/searchkick#53]
I want to perform autocomplete and search across multiple models. 

One possible way that I can think of is querying different controller actions for each model and then merging the results - Twitter's typeahead.js @twitter supports this. The same should work for showing search results from different models.

I would love to know if there is a better way to do this currently and if not, any direction on how I should go about adding this capability to searchkick.

**Comment by shilpi230** [comment]
@ankane can you please specify what to give in index and what in name ?

**Comment by Tuhaj** [comment]
@shilpi230 for me worked:
```Model1.search("thequery", index_name: [Model1.index.name, Model2.index.name, Model3.index.name], other_options)```

**Comment by zismailov** [comment]
@ankane  how use searchkick. Where each models have where {} parameters ?
Searchkick.search("thequery", [Model1, Model2, Model3], other_options),  
example:
Model1: where: {blocked: 'true'}
Model2: where: {status: 'true'}
Model3: where: {field: 'false'}

**Comment by ankane** [comment]
@zismailov Searchkick is not designed for this.  You'll need to write a custom query in the Elasticsearch DSL - see [Advanced Search](https://github.com/ankane/searchkick#advanced-search).
