### ISSUE TITLE
Search causes 411 content length not specified error

### ISSUE THREAD

**Issue by vikigenius** [ankane/searchkick#530]
I am behind a proxy server.
When i use the search function it throws a 411 error saying content length required.
I saw in some website that we have to disable http chunking, but i do not know how to do that.

Can anyone look into this issue?

**Comment by ankane** [comment]
Searchkick uses [elasticsearch-ruby](https://github.com/elastic/elasticsearch-ruby) under the hood, so I'd see how to use a proxy with it.

**Comment by ankane** [comment]
Cleaning up issues. If you figured this out, I'm sure others would find it useful if you posted how.
