### ISSUE TITLE
searchkick not work with aws elastic search service

### ISSUE THREAD

**Issue by machoph** [ankane/searchkick#532]
Hi guys i think is needed an option for selecting the way to deliver the params (POST, URL) cause right now AWS elasticsearch service only allow post params.

http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html

Thanks again for this amazing gem

oscar

**Comment by ankane** [comment]
Hi Oscar, it's not clear that's the case from the AWS documentation.  What error are you seeing?

**Comment by machoph** [comment]
Hi @ankane sorry here is the error

```Elasticsearch::Transport::Transport::Errors::Forbidden: [403] {"message":"When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/consultants_development_20151013103309683/consultant/_bulk?type=consultant'"}```

as you can see in the new aws elasticsearch service http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html

```Parameters in HTTP POST requests	The service ignores parameters passed in URLs for HTTP POST requests signed with Signature Version 4.```

**Comment by markyj** [comment]
This has been raised on elasticsearch-ruby: https://github.com/elastic/elasticsearch-ruby/issues/226

In essence this isn't an elastic search issue, but checking done by some AWS infrastructure in front of their instances.  Maybe an Elastic Load Balancer?

In that issue, they reference a Japanese site, and from that I got a monkey patch that works for now
<img width="494" alt="aws_patch" src="https://cloud.githubusercontent.com/assets/38937/10480924/f1f24726-72b8-11e5-82d4-fa925a464d06.png">

**Comment by machoph** [comment]
@markyj thanks a lot this just works perfect for me

**Comment by ankane** [comment]
This is fixed in elasticsearch 1.0.14.  Just add this to your Gemfile:

```ruby
gem "elasticsearch", ">= 1.0.14"
```
