### ISSUE TITLE
Specify queue name when using async indexing

### ISSUE THREAD

**Issue by nesrual** [ankane/searchkick#533]
Is there any way to specify the name of the queue being used for async indexing? 

Searchkick defaults to the `searchkick` queue. That works fine with Sidekiq where you can use namespaces, however I am using AWS SQS for queuing and SQS doesn't provide the same functionality.

Is there any way to monkey patch searchkick so each application can use its own SQS queue name?

**Comment by nesrual** [comment]
This is one way to solve/override the queue name:

Create an initializer file `config/initializers/searchkick_queue_settings.rb` containing

    module Searchkick
      class ReindexV2Job
        queue_as 'my_custom_queue_name'
      end
    end

This will create a custom queue name for Searchkick to use.

**Comment by vasilakisfil** [comment]
Thanks mate!
