### ISSUE TITLE
Testing whether index updated

### ISSUE THREAD

**Issue by dv** [ankane/searchkick#535]
I'm trying to write a spec to ensure that after updating a record, the ES index is updated asynchronously.

This was my first try:

```ruby
account = accounts(:a)
new_name = "some-random-name"
expect(Account.search(new_name)).to be_empty

account.update(name: new_name)
expect(Account.search(new_name)).to be_empty # Make sure updates are not run inline

perform_enqueued_jobs do
  account.update(name: new_name)
end

expect(Account.search(new_name)).to contain_exactly(account)
```

In this example, Account has an index using the following line:
```
searchkick callbacks: :async
```

However, this test fails on the last line because the results are empty. The index is never updated, and if I surround the `update` with an `assert_jobs_enqueued` check to see if there's actually a new job, it shows that there was no new job created.

How could I get this to work?

I'm using Sidekiq in case that matters, and run `Account.reindex` as well as `Account.searchkick_index.refresh` before each test. Also, if I run `Account.reindex` in the test somewhere behind the update, it does pass.

**Comment by ankane** [comment]
Does it pass if you run `Account.searchkick_index.refresh` before the last assertion?

**Comment by dv** [comment]
It does not. This fits with the fact that there's no jobs actually run. I tried asserting that using this code:

```ruby
    assert_performed_jobs 1 do
      account.update(name: new_name)
    end

**Comment by dv** [comment]
Found the problem - I'm using transactional fixtures and thus `after_commit` callbacks are never called. I added the gem "test_after_commit" to make the callbacks run even inside a transaction. This would be fixed without the gem in Rails 5.
