### ISSUE TITLE
Facets with stats throwing an exception

### ISSUE THREAD

**Issue by pramodthammaiah** [ankane/searchkick#538]
I have a Product index and a category_name attribute. When I search:

```Product.search "*", facets: [:category_name]```

Everything works fine. However, when I follow the README.md to get stats:

```Product.search "*", facets: {category_name: {stats: true}}```

I get thrown an error:

```Searchkick::InvalidQueryError: [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[ZpZ9nLejTrqeNDPpXVLyMA][products_development_20151028162425372][0]: SearchParseException[[products_development_20151028162425372][0]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"category_name\":{\"terms_stats\":{\"key_field\":\"category_name\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }{[ZpZ9nLejTrqeNDPpXVLyMA][products_development_20151028162425372][1]: SearchParseException[[products_development_20151028162425372][1]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"category_name\":{\"terms_stats\":{\"key_field\":\"category_name\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }{[ZpZ9nLejTrqeNDPpXVLyMA][products_development_20151028162425372][2]: SearchParseException[[products_development_20151028162425372][2]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"category_name\":{\"terms_stats\":{\"key_field\":\"category_name\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }{[ZpZ9nLejTrqeNDPpXVLyMA][products_development_20151028162425372][3]: SearchParseException[[products_development_20151028162425372][3]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"category_name\":{\"terms_stats\":{\"key_field\":\"category_name\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }{[ZpZ9nLejTrqeNDPpXVLyMA][products_development_20151028162425372][4]: SearchParseException[[products_development_20151028162425372][4]: query[ConstantScore(*:*)],from[0],size[100000]: Parse Failure [Failed to parse source [{\"query\":{\"match_all\":{}},\"size\":100000,\"from\":0,\"facets\":{\"category_name\":{\"terms_stats\":{\"key_field\":\"category_name\",\"value_script\":\"_score\",\"size\":100000}}},\"fields\":[]}]]]; nested: ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }]","status":400}```

Any suggestions on what to look into?

**Comment by ankane** [comment]
The meaningful error is at the end:

```
ScriptException[scripts of type [inline], operation [aggs] and lang [groovy] are disabled]; }]
```

It sounds like you'll need to relax the security settings of your ES server to use stats facet.

**Comment by ankane** [comment]
Cleaning up issues
