### ISSUE TITLE
Mistake in the synonyms documentation

### ISSUE THREAD

**Issue by pramodthammaiah** [ankane/searchkick#541]
I was trying to include a CSV file of synonyms and was getting an error when reindexing.
I used ```searchkick synonyms: Proc.new { CSV.read("/some/path/synonyms.csv") }``` as stated in the instructions and go this error:
```
Reindexing Product...
rake aborted!
NoMethodError: undefined method `any?' for #<Proc:0x007fa1f35a3628>

Tasks: TOP => searchkick:reindex:all
```
I found that removing the ```Proc.new``` fixed it:
```searchkick synonyms: CSV.read("/some/path/synonyms.csv") ```

works like a charm. Perhaps the instructions should be updated?

**Comment by ankane** [comment]
My bad @pramodthammaiah - this feature is only available on master but was not marked as such.
