### ISSUE TITLE
1.0 introduces #aggs error

### ISSUE THREAD

**Issue by richmolj** [ankane/searchkick#542]
If you query without specifying aggs, you will get `TypeError: can't dup NilClass`. This is because `response['aggregations']` is `nil` here: https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb#L80. This is different behavior from `facets`, which would return `nil` with no error.

This was relevant to me since my app has an additional level of abstraction parsing the results, and started failing with the 1.0 upgrade. Just wanted to raise the issue to make people aware.

**Comment by ankane** [comment]
Thanks for reporting Lee. This was unintended and is fixed on master.
