### ISSUE TITLE
can't dup NilClass

### ISSUE THREAD

**Issue by dcalixto** [ankane/searchkick#543]
after moving tire to searchkick and change the facets to aggs i got this  can't dup NilClass

the code is:

model:

searchkick

def search_data

    {
    name: name,
    gender:gender,
   category: name,
    colors_name: colors.map(&:name),
    sizes_id: sizes.map(&:id)
  }
  end

  def self.aggs_search(params)
  query = params[:query].presence || "*"
  conditions = {}
  conditions[:price] = params[:price] if params[:price].present?
  conditions[:gender] = params[:gender] if params[:gender].present?
  conditions[:category] = params[:category] if params[:category].present?

 products = Product.search query, where: conditions,
    aggs: [:price],
    aggs: [:gender],
    aggs: [:category]

smart_aggs: true, page: params[:page], suggest: true, highlight: true,
    per_page: 22
  products
end

aggs partial:

<div class="filtro">
    <h2>Genero</h2>
    <ul>
      <% @products.aggs['gender']['terms'].each do |aggs| %>
          <li>
            <%
               gender = Gender.find(aggs['term'])
               params_to_merge = controller.controller_name == GendersController.controller_name ? {id: gender.slug} : {gender_id: aggs['term']}
            %>
            <%= link_to_if params[:id] != gender.slug && params[:gender_id] != aggs['term'].to_s, gender.gender, params.merge(params_to_merge) %> <%= aggs['count'] %>
          </li>
      <% end %>
    </ul>
  </div>

controller:

  @products= Product.search

**Comment by ankane** [comment]
This error should be fixed on the master branch.

```ruby
gem "searchkick", github: "ankane/searchkick"
```

**Comment by dcalixto** [comment]
that's it. @ankane  thank you very much.
