### ISSUE TITLE
Does reindex_async work for has_many associations?

### ISSUE THREAD

**Issue by neojin** [ankane/searchkick#545]
I noticed that `association.reindex_async` works for a `belongs_to` association, but does it work for a `has_many` ?

Example:

```
class PurchaseOrder < ActiveRecord::Base
  belongs_to :customer
  searchkick

  def search_data
    {
      number: number,
      description: description,
      customer_id: customer_id,
      customer_name: customer_name
    }
  end
end

class Customer < ActiveRecord::Base
  has_many :purchase_orders
  after_commit :reindex_purchase_orders

  def reindex_purchase_orders
    purchase_orders.reindex_async
  end
end
```

I get the following: `#<NoMethodError: undefined method 'reindex_async' for #<ActiveRecord::Relation:0x007f845e4e6b98>>`

However, just `reindex` works.

I guess I could do `purchase_orders.each(&:reindex_async)`, but not sure if this is any better in terms of performance.

Thanks!

**Comment by ankane** [comment]
You should use `purchase_orders.each(&:reindex_async)`.

`purchase_orders.reindex` will do something bad (and throws an error in Searchkick 1.0).

**Comment by neojin** [comment]
thank you!
