### ISSUE TITLE
reindex returns Elasticsearch::Transport::Transport::Errors::MovedPermanently: [301]

### ISSUE THREAD

**Issue by slead** [ankane/searchkick#550]
I'm trying to use Searchkick on a new Rails project on Windows 7. I've installed Elasticsearch and confirmed that it's running at http://localhost:9200 

I've added searchkick to a model:

```
class Address < ActiveRecord::Base
    searchkick
end
```

However, `Address.reindex` returns _Elasticsearch::Transport::Transport::Errors::MovedPermanently: [301]_

I tried adding an initializer at \config\initlializers\searchkick.rb...

`Searchkick.client = Elasticsearch::Client.new host: 'localhost:9200'`

... but this had no effect. Am I missing a required step? Thanks for any advice.

**Comment by ankane** [comment]
I haven't seen that error before unfortunately.

**Comment by vsizov** [comment]
@slead Have you found what caused the problem?

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if this is still relevant.
