### ISSUE TITLE
Installing WordNet does not work

### ISSUE THREAD

**Issue by Qqwy** [ankane/searchkick#553]
I am trying out searchkick.

After making sure the basic Elasticsearch worked properly, I wanted to see what WordNet would do. 

I copied the command line instructions that are stated in the guide. The `wn_s.pl` perl file got stored in `/var/lib` without problems. But when I then try to reindex my models (that now have the line `searchkick wordnet: true`), I get the following error:

    Reindexing WorldObject...
    rake aborted!
    Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"access_control_exception","reason":"access denied (\"java.io.FilePermission\" \"/var/lib/wn_s.pl\" \"read\")"},"status":500}
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:228:in `perform_request'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/client.rb:119:in `perform_request'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/index.rb:11:in `create'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/index.rb:134:in `create_index'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/index.rb:155:in `reindex_scope'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/model.rb:51:in `searchkick_reindex'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/tasks.rb:26:in `block (4 levels) in <top (required)>'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/tasks.rb:24:in `each'
    /home/qqwy/.rvm/gems/ruby-2.2.1/gems/searchkick-1.0.1/lib/searchkick/tasks.rb:24:in `block (3 levels) in <top (required)>'
    Tasks: TOP => searchkick:reindex:all

I have tried changing the file permissions of the `/var/lib/wn_s.pl` file so that anyone can read and write to it, but this does not solve the problem.

What is going on?

**Comment by ankane** [comment]
What does `ls -la /var/lib | grep wn_s` return?

**Comment by pratikganvir** [comment]
I am facing exact same issue. The output of the command 'ls -la /var/lib | grep wn_s' in my case is 
-r-xr-xr-x  1 sky           sky           7494480 Jan 24  2007 wn_s.pl

sky is my username.
Please let me know how can I fix this.

**Comment by ankane** [comment]
Be sure the Elasticsearch server is running under your user as well.

**Comment by jgrant29** [comment]
I am having the same issue

**Comment by pratikganvir** [comment]
I figured out that the issue was because elasticsearch did not have
executable rights. I tried assigning rights (But I am not really good at
it) but it didn't work, I finally moved elasticsearch to different location
and specified elasticsearch path to searchkick. It resolved my issue.

**Comment by npow** [comment]
I just ran into this as well. Fixed it by moving `wn_s.pl` into the elasticsearch config folder, which on OSX is `/usr/local/etc/elasticsearch`

**Comment by ankane** [comment]
Cleaning up issues.  As the Elasticsearch error states, this is a filesystem permissions issue.

**Comment by chamnap** [comment]
How to fix this permission issue?

-r--r--r--  1 deploy   deploy   7.2M Jan 23  2007 wn_s.pl

**Comment by kostyay** [comment]
I have the same issue, tried different things:
`-rwxrwxrwx 1 elasticsearch elasticsearch 7494480 Aug  8 03:59 /var/lib/wn_s.pl`

Any ideas how to fix this?

**Comment by kostyay** [comment]
I managed to get it to work.

Find out what is the home dir for elasticsearch, on ubuntu it was `/etc/elasticsearch`
`sudo cp wn_s.pl /etc/elasticsearch`
`sudo chown elasticsearch:elasticsearch /etc/elasticsearch/wn_s.pl`

Create a new initializer in the `config/initializers` directory with the following:
`Searchkick.wordnet_path = '/etc/elasticsearch/wn_s.pl'`

**Comment by chamnap** [comment]
@kostyay, I did the same thing as you do. I was just lazy to install from other directory, and add `initializers`. Maybe the readme file should be updated.

**Comment by mahemoff** [comment]
How does this work when Elasticsearch is on a different server from the client/Rails server? I can only get it working as above, ie with an initializer indicating the correct location. On a separate server, it always fails on /var/lib.

**Comment by chamnap** [comment]
You need to place it on that elastic server as I remembered.

**Comment by mahemoff** [comment]
Thanks - that's what the docs say too and I did it, but it only ever tries to use /var/lib. (Ubuntu 16.04 / ES2.4). I tried in both locations (/etc/elasticsearch and /var/lib owned by elasticsearch user), but same error as OP.

(It worked fine for me on OSX as @kostyay suggested, but that's apparently because the initializer is on the same machine as the server.)

**Comment by techpeace** [comment]
Looks like the `wn_s.pl` file [does indeed need to be located in the config directory|https://github.com/elastic/elasticsearch/issues/16995#issuecomment-193622820].
