### ISSUE TITLE
Cannot connect to elasticsearch over ssl

### ISSUE THREAD

**Issue by bryanvaz** [ankane/searchkick#555]
Just did an update and tried to use searchkick with Searchly's hosted elasticsearch (tried both with the HTTP and HTTPS connetcion), and got a very violent reaction:

    Loading development environment (Rails 4.2.5)
    2.2.3 :001 > Asset.reindex
    ETHON: Libcurl initialized
    Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid.
    Please try ssl_verifypeer instead of disable_ssl_peer_verification.
    ...

Anyone have any insights?

Relevant Gems (under both Rails 4.2.3 and Rails 4.2.5):
  * elasticsearch (1.0.14)
  * elasticsearch-api (1.0.14)
  * elasticsearch-transport (1.0.14)
  * ethon (0.8.0)
  * faraday (0.9.1)
  * ffi (1.9.10)
  * fog-aws (0.7.6)
  * fog-core (1.32.1)
  * fog-json (1.0.2)
  * fog-xml (0.1.2)
  * searchkick (1.0.2)
  * typhoeus (0.8.0)
  * unicorn (5.0.0)

**Comment by ankane** [comment]
Do you have an initializer with `require 'typhoeus/adapters/faraday'`?

**Comment by bryanvaz** [comment]
haven't needed it till today, one sec let me pop that at the top of the searchkick initializer

**Comment by bryanvaz** [comment]
the require tag works. ETHON is now very verbose about its operations.
Should probably put that smack at the top of the searchkick readme now. Was 2 hours of circling and coming across the old typhoeus posts that said that the adapter was a problem but was fixed post faraday 0.8.8 (https://github.com/toptal/chewy/issues/22 and https://github.com/typhoeus/typhoeus/issues/226#issuecomment-9919517).

cheers!

**Comment by ankane** [comment]
It's [here](https://github.com/ankane/searchkick#performance), as well as instructions on how to quiet ethon.

**Comment by bryanvaz** [comment]
awesome sauce, gracias!
