### ISSUE TITLE
Intermediary tables and Aggregation

### ISSUE THREAD

**Issue by caleuanhopkins** [ankane/searchkick#556]
I have a model that has several products, a table that has a list of tags and an intermediary table model that maps the relationship between the products and the tags. They are setup roughly like this:

    products.rb
    ---
    id, title

    tags.rb
    ---
    id, tagname

    tagprodrelation.rb
    ---
    id, product_id, tags_id

I can use searchkick to find a product, but I want the ES aggregation to see the tags through the intermediary relationship mapped out in the `tagprodrelation.rb` table. Through activerecords I pull display tags connected to a product in the view without ES or Searchkick. Any idea how I can configure searchkick to pick up the tags relationship for a product and map them to a "tags" field in ES which can then be used as a aggregation?

**Comment by caleuanhopkins** [comment]
found out how to make this work, anyone wondering about this in the future, please feel to get in touch

**Comment by bricesanchez** [comment]
@caleuanhopkins I've the same problem, could provide us an exemple of how you fix it ?

**Comment by caleuanhopkins** [comment]
@bricesanchez 

model/products.rb

    class Products < ActiveRecord::Base
        has_many :prodtag, :dependent => :destroy
        has_many :tag, through: :prodtag

        searchkick 

        def search_data
            attributes.merge(tags: tag.map(&:tagname))
        end

        Products.reindex
    end

model/tag.rb

    class Tag < ActiveRecord::Base
        has_many :prodtag
        has_many :products, through: :prodtag
    end

model/prodtag.rb

    class Prodtag < ActiveRecord::Base
        belongs_to :products
        belongs_to :tag
    end
