### ISSUE TITLE
Array.to_h doesn't exist in ruby 2.0

### ISSUE THREAD

**Issue by will-r** [ankane/searchkick#559]
...so the transformation of aggregation payload into a hash fails here:

https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L350

Old stuff, I know, but the system ruby is still at 2.0.0p645 on OS X.

Easy workaround is to pass aggregations as a hash.

**Comment by ankane** [comment]
Thanks for reporting @will-r - fixed on master.
