### ISSUE TITLE
Add ability to create named queries (_name)

### ISSUE THREAD

**Issue by jslauthor** [ankane/searchkick#562]
Hello,

How do I add the _name property to a multi-field [{field1: :word_start}, {field2: :word_start}] query. I'm performing autocomplete on several different fields within a record and need to know which field matched so it can be returned to the client. Any help would be appreciated, thanks!

Best,
Leonard

**Comment by jslauthor** [comment]
I'm also seeing two queries per field for the following:

```Model.search @query,
                            fields: [{title: :word_start, name: :title}, {summary: :word_start, name: :summary}],
                            limit: @size```

```
{  
   "query":{  
      "dis_max":{  
         "queries":[  
            {  
               "match":{  
                  "title.word_start":{  
                     "query":"ang",
                     "operator":"and",
                     "boost":10,
                     "analyzer":"searchkick_word_search"
                  }
               }
            },
            {  
               "match":{  
                  "title.word_start":{  
                     "query":"ang",
                     "operator":"and",
                     "boost":1,
                     "analyzer":"searchkick_word_search",
                     "fuzziness":1,
                     "prefix_length":0,
                     "max_expansions":3,
                     "fuzzy_transpositions":true
                  }
               }
            },
            {  
               "match":{  
                  "summary.word_start":{  
                     "query":"ang",
                     "operator":"and",
                     "boost":10,
                     "analyzer":"searchkick_word_search"
                  }
               }
            },
            {  
               "match":{  
                  "summary.word_start":{  
                     "query":"ang",
                     "operator":"and",
                     "boost":1,
                     "analyzer":"searchkick_word_search",
                     "fuzziness":1,
                     "prefix_length":0,
                     "max_expansions":3,
                     "fuzzy_transpositions":true
                  }
               }
            }
         ]
      }
   },
   "size":5,
   "from":0,
   "fields":[  

   ]
}
```

Shouldn't I just see one "match" query for each field? Also the boost value isn't being respected from the model setup:

```fields: ["title^10", "summary^5", "technology^3", "transcript"]```

**Comment by ankane** [comment]
@jslauthor seeing two queries is expected for misspellings.  From the code above, it doesn't look like you're applying any per field boots.
