### ISSUE TITLE
error search 

### ISSUE THREAD

**Issue by renanoronfle** [ankane/searchkick#565]
i try use searchkick, reindex working right but when i search received this error

  ProductCollection Search (9.6ms)  curl http://localhost:9200/product_collections_development/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"anderson","operator":"and","boost":10,"analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"anderson","operator":"and","boost":10,"analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"anderson","operator":"and","boost":1,"analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"anderson","operator":"and","boost":1,"analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":100000,"from":0,"fields":[]}'
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"product_collections_development_20151126155236600","node":"jNOm3ESLTEqdZqoBzr_Ndg","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}}]},"status":500}
from /home/renanoronfle/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/elasticsearch-transport-1.0.14/lib/elasticsearch/transport/transport/base.rb:136:in `__raise_transport_error'

**Comment by ledermann** [comment]
If you have installed Elasticsearch v2.1.0, please see PR #564 (not merged yet).

Workaround: Add `:limit => 1000` to your search query.

**Comment by ankane** [comment]
Thanks for reporting Renan. Fixed in the latest release.

**Comment by hallmatt** [comment]
Thanks for the fix! Worked for me.

**Comment by chamnap** [comment]
It doesn't work for me. I'm not really sure how to deal with it. I have a search results which has 140k records. I'm trying to paginate all of those results. However, it stucks at 101st page with 1000 `limit` or `per_page`. Here is the exception:

> 2016-10-12 04:58:49.455 [DEBUG] Company Search (8.3ms)  curl http://10.240.0.12:9200/companies/_search?pretty -d '{"query":{"filtered":{"query":{"match_all":{}},"filter":{"and":[{"term":{"country":"New Zealand"}}]}}},"size":1000,"from":100000,"fields":[]}' (pid:8516)(dyno:0)
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [100000] but was [101000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"companies_20160913032743217","node":"9iAi2L42RUyss56Qy76YlA","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [100000] but was [101000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}}]},"status":500}

How to deal with this problem?

**Comment by ankane** [comment]
Hey @chamnap, check out #642 for a solution and its implications.

**Comment by chamnap** [comment]
Thanks a lot @ankane!
