### ISSUE TITLE
Faraday::TimeoutError: execution expired when used in combination with AWS ElasticSearch service

### ISSUE THREAD

**Issue by nkaviani** [ankane/searchkick#566]
I am trying to switch my Rails Beanstalk app to use AWS ElasticSearch in place of an EC2 instance running ElasticSearch. However requests from the Rails app seem to get blocked when trying to reach the ES service. Running `curl -XGET $ELASTICSEARCH_URL` returns the expected result:

```
{
    "status" : 200,
    "name" : "Man-Killer",
    "cluster_name" : "085567994644:curatiopv2",
    "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

However, when trying to create an object through the rails app that needs to be indexed by ElasticSearch, I get a `Faraday::TimeoutError: execution expired` error. I don't think timeout is an issue so I wonder why this is failing and if anyone has tried searchkick with AWS ElasticSearch service?

**Comment by nkaviani** [comment]
ah it turned out I needed to have `http` included at the beginning of the `ELATICSEARCH_URL`

**Comment by Startouf** [comment]
@nkaviani My savior. Thank you so much.
