### ISSUE TITLE
Initial rake searchkick:reindex:all on Found fails

### ISSUE THREAD

**Issue by danielrsmith** [ankane/searchkick#569]
Elasticsearch::Transport::Transport::Errors::NotFound: [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index":"_all"}],"type":"index_not_found_exception","reason":"no such index","index":"_all"},"status":404}

This is due to the fact that Found now adds shield by default which returns a 404 when there are no indices on the cluster.  Probably need to add a rescue to the `reindex_scope` method when `clean_indices` fails out, OR to `clean_indices` when `get_aliases` fails.

**Comment by ankane** [comment]
Thanks Daniel, should be fixed now.
