### ISSUE TITLE
Supporting signed requests for AWS ElasticSearch Service?

### ISSUE THREAD

**Issue by nkaviani** [ankane/searchkick#574]
is there any plan to support the signing of requests to elasticsearch aws service with aws credentials?

**Comment by ankane** [comment]
No plans to add this, but feel free to submit a pull request.

**Comment by nkaviani** [comment]
sure ... will look into it. thanks!

**Comment by somazx** [comment]
According to the documentation here https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport:

>You can use any standard Faraday middleware and plugins in the configuration block, for example sign >the requests for the AWS Elasticsearch service:

```
require 'patron'
require 'faraday_middleware/aws_signers_v4'

client = Elasticsearch::Client.new url: 'https://search-my-cluster-abc123....es.amazonaws.com' do |f|
  f.request :aws_signers_v4,
            credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY'], ENV['AWS_SECRET_ACCESS_KEY']),
            service_name: 'es',
            region: 'us-east-1'
end
```

So in an initializer I attempted to do this:
```

require 'patron'
require 'faraday_middleware/aws_signers_v4'
Searchkick.client = Elasticsearch::Client.new url: ENV[AWS_ES_ENDPOINT] do |f|
  f.request :aws_signers_v4,
            credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY'], ENV['AWS_SECRET_ACCESS_KEY']),
            service_name: 'es',
            region: 'us-west-2'
end


```

Note assigning the new client to Searchkick.client. This works in that Searchkick does use this transport client for all future requests. However I still get the following error:

`{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet on resource: ... `

Could this approach potentially work? Or am I totally misguided?

**Comment by somazx** [comment]
The above works. Be sure to update the elasticsearch gem to >= 1.0.15

**Comment by nkaviani** [comment]
awesome thanks Andy.

**Comment by ankane** [comment]
Updated readme - thanks @somazx!

**Comment by hendricius** [comment]
Works like a charm. thank you!

**Comment by UnquietCode** [comment]
Does anyone know if this works without the `patron` adapter? I am using the configuration in the Readme but am not having any luck connecting to my AWS cluster.

**Comment by somazx** [comment]
Ya, that was my mistake, you don't need patron, just Faraday.
