### ISSUE TITLE
Mapping definition for [_routing] has unsupported parameters

### ISSUE THREAD

**Issue by cristian-rivera** [ankane/searchkick#575]
Hello,

I am currently using searchkick to aid in searches across a lot of records. I stumbled across the routing feature but when I run the rake reindex task I am getting this error:
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [_routing] has unsupported parameters:  [path : user_id]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: Mapping definition for [_routing] has unsupported parameters:  [path : user_id]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [_routing] has unsupported parameters:  [path : user_id]"}},"status":400}
```
I am using Elasticsearch 1.7.3 and her is the code within my model:
```
searchkick callbacks: :async, routing: :user_id, index_name: -> { "#{ENV['BASE']}_#{name.tableize.gsub!(/[^0-9A-Za-z]/, '_')}_#{Rails.env}".downcase }
```
I believe I'm following the documentation correctly.

Thanks

**Comment by ankane** [comment]
I'd double check your Elasticsearch version.  This is the error you get for Elasticsearch 2.0, where routing is not currently supported.

**Comment by cristian-rivera** [comment]
Hey Andrew sorry for the mixup. I downgraded my elasticsearch version to 1.7.3 from 2.0 and never restarted my mac, awesome gem btw!
