### ISSUE TITLE
Search in multiple fields with the same term

### ISSUE THREAD

**Issue by williamweckl** [ankane/searchkick#576]
I'm having some headache to search in multiple fields with the same term.

Basically, my problem is exactly the same from this guy: http://stackoverflow.com/questions/32743635/searchkick-not-searching-multiple-terms-when-specify-fields.

How can I do that?

**Cross-fields**

Trying to apply elastic search cross-fields:

```
Item.search(body: {
              query: {
                  "multi_match": {
                      "query": "William Weckl",
                      "type": "cross_fields",
                      "operator": "and",
                      fields: [
                          "name",
                          "last_name",
                      ]
                  }
              }
          }, load: false)
```

Still without success, even if I change operator to `or`.

Elasticsearch query that is being executed:

`curl http://localhost:9200/items_development/_search?pretty -d '{"query":{"multi_match":{"query":"William Weckl","type":"cross_fields","operator":"or","fields":["name","last_name"]}}}'`

Maybe an index problem? How should I configure searchkick to index that?

**My model:**

`searchkick language: "brazilian", word_start: [:name, :last_name]`

Tried to remove the word_start and the language parameter too.

**Comment by bingxie** [comment]
I also found use fields option doesn't work.  

Product.search("abc", fields: [:title]) # doesn't work

Product.search("abc") #work ok

**Comment by williamweckl** [comment]
I customized the query myself. Don't know if is the best way, would be great if `searchkick` could do it without customization. [Here][1] is what I did to solve my problems.

[1]:http://stackoverflow.com/a/34266548/2767026

**Comment by bingxie** [comment]
@williamweckl I think you did in the right way! Thanks for sharing the solution.
