### ISSUE TITLE
undefined method `each' for nil:NilClass on setup aggs

### ISSUE THREAD

**Issue by dcalixto** [ankane/searchkick#578]
Hi, i would like to know what i did wrong, i followed your instructions and rails spitting out this message.

config:
product model:

  def self.aggs_search(params)
  query = params[:query].presence || "*"
  products = Product.search  query,where: {
  name: "product_1"
  },
    aggs: {
        names: {
            terms: { field: "name" }
       }
    },
 order: {price: :asc},
  smart_aggs: false, page: params[:page], suggest: true, highlight: true,
  per_page: 20
  products
end

product controller:
@products = Product.aggs_search(params)

product aggs view:

 <% @products.aggs["names"]["terms"].each do |c| %>
        <li class="list-group-item">
          <%= link_to "#{c['name']} #{c['key']} : #{c['doc_count']}"%>
        </li>
      <% end %>  

thank's

**Comment by ankane** [comment]
In your controller, try adding:

```ruby
logger.debug @products.aggs["names"]
```

to see why it's not working.

**Comment by dcalixto** [comment]
thank's but shows nothing just the same message:
i'm on rails 3.2.22, is the version a issue?

**Comment by ankane** [comment]
@dcalixto what do you mean by the "same message"?  Can you post the message?
