### ISSUE TITLE
Location Boosting by distance

### ISSUE THREAD

**Issue by taltas** [ankane/searchkick#579]
Could be the upgrade to ES 1.x, but it seems the location boosting is no longer working, it seems two things are happening:

1)  It seems that the lat and long are being switched around, see this is in rails:

``` javascript
:boost_by_distance=>{:field=>:location, :origin=>[49.282, -123.12073]}
```

gets converted to this json query:

``` javascript
"function_score": {
          "functions": [
            {
              "gauss": {
                "location": {
                  "scale": "5mi",
                  "origin": [
                    -123.12073,
                    49.282
                  ]
                }
              }
            }
          ],
          "query": {
            "match_all": {

            }
          },
          "score_mode": "sum"
        }
      }
```

Where the lat and the long seemed to be switched... 
2)
Even so, I have tried switching the lat,long around on the rails end to see if that would work, and even though the gem is outputting the correct es query, it did not sort correctly. 

Anyone else having these issue?

**Comment by taltas** [comment]
Further research has shown the the location is being indexed in the wrong order as well aka [long,lat]! Help!

**Comment by ankane** [comment]
Searchkick uses the `[latitude, longitude]` convention (opposite of Elasticsearch).  To clear up any confusion, I plan to have future versions to use `{lat: latitude, lon: longitude}` instead of an array.
