### ISSUE TITLE
Indexing Nested Types

### ISSUE THREAD

**Issue by lewisifer** [ankane/searchkick#581]
Hello,

I apologize if this question has been asked multiple times, but is there any way that you currently support nested types during indexing? If not, is there a work around? For instance, if I have a table Assets, that I'm indexing on, and an Asset can have many Campaigns, I'm currently doing this:

def search_data
   asset_name: name,
   campaign_ids: campaigns.pluck(:id),
   campaign_names: campaigns.pluck(:name)
end

I'd like to keep the campaign_id and campaign_name together like so:

def search_data
   asset_name: name,
  campaign: {campaign_ids: campaigns.pluck(:id),campaign_names: campaigns.pluck(:name)}
end

When I do this, the indexing happens, but I'm not sure how to go about searching on that index.

This is so that I don't have to hope that the ordering is correct in both arrays. Please let me know if this is possible, and thanks a bunch for the help!

Madan.

**Comment by ankane** [comment]
I haven't tried this, but you should be able to do it with a [custom mapping](https://github.com/ankane/searchkick#advanced-mapping).

**Comment by MrHubble** [comment]
@lewisifer were you able to accomplish this with custom mappings?

**Comment by lewisifer** [comment]
Hi MrHubble,

I was not able to, but I found another workaround for my specific problem
and did away with that requirement altogether.
