### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by teodor-pripoae** [ankane/searchkick#582]
Hi,

Is there any option to remove a collection of records ? Something similar to bulk insert.

Thanks,
Teodor

**Comment by ankane** [comment]
No, you'll need to use `Searchkick.client` directly to do this.

**Comment by teodor-pripoae** [comment]
Thanks, I managed to get it working. Is there any technical reason (performance issues ?) why this is not in the gem ? Implementation looks pretty simple:

```ruby
module Searchkick::Index
  def bulk_delete(records)
    records.group_by { |r| document_type(r) }.each do |type, batch|
      response =
        client.bulk(
          index: name,
          type: type,
          body: batch.map { |r| {delete: {_id: search_id(r)}} }
        )
      if response["errors"]
        raise Searchkick::ImportError, response["items"].first["delete"]["error"]
      end
    end
  end
end
```

If you want, I can create a Pull Request.

**Comment by ankane** [comment]
A pull request with one or more tests would be great.

**Comment by teodor-pripoae** [comment]
Ok, sure ! I'll come back tomorrow with a PR.

**Comment by ankane** [comment]
The latest release now has this - was needed for the bulk update feature.
