### ISSUE TITLE
search fields option doesn't work when defined mappings

### ISSUE THREAD

**Issue by bingxie** [ankane/searchkick#584]
I also found use fields option doesn't work.
```
Product.search("abc", fields: [:title]) # doesn't work

Product.search("abc") #works
```
And I have this:
```
searchkick callbacks: :async, merge_mappings: true, mappings: {
      product: {
        properties: {
          title: {type: "string", index: 'analyzed'},
          description: {type: "string", index: 'analyzed'},
          tag_list: {type: "string", index: 'analyzed'},
        }
      }
    }
```

**Comment by ankane** [comment]
This is expected.  If you use custom mappings, you'll need to write custom search queries as well.

**Comment by bingxie** [comment]
ok, I see. Because I also need to specify the analyzer in the query, so where can I find document about custom search query?  Is the elasticsearch official Query DSL document the right place?

**Comment by ankane** [comment]
@bingxie yeah, you'll need to use the Query DSL. Once you know the query you want to write, instructions for how to add it to Searchkick are here: https://github.com/ankane/searchkick#advanced-search
