### ISSUE TITLE
Set custom number of characters to receive results

### ISSUE THREAD

**Issue by kovson** [ankane/searchkick#585]
I've got users Oliver and Olivia and I want my code to return them as a suggest result when only 2 characters are passed as a query. Now it's working only when 4 or more characters are passed.

My code

```
User.search(query, { suggest:true, misspellings: { edit_distance: 2, below: 5 } })
```

```
query = 'oliv'
result = [ "olivia", "oliver"]

query = 'ol'
results = []
```

Is there any way to do it with searchkick?

**Comment by ankane** [comment]
Unfortunately, not that I'm aware of.
