### ISSUE TITLE
Am I sorting by column properly?

### ISSUE THREAD

**Issue by NeMO84** [ankane/searchkick#590]
I am attempting to support searching and sorting by column. I understand I can use the fields setting to set an array of columns to search against. But, I didn't see any example of sorting other than a reference to the fact that it is [supported](https://github.com/ankane/searchkick/blob/aff7c38559377ad0093961535c130adb4fa283e9/README.md#queries). Looking at the Elasticsearch docs, I would think that something like this would be supported:

    Product.search "car", page: 0, per_page: 10, sort: { created_at: { order: "desc" } }

I wasn't able to get the above to work. The pagination values work, but the sorting isn't taking effect.

Should it be different?

**Comment by ankane** [comment]
You'll need to use `order` instead of `sort`.  Unfortunately, Searchkick doesn't throw an error for unrecognized options, but I'd gladly accept a pull request for it.

**Comment by NeMO84** [comment]
Can you provide an example of the correct structure from what I posted above? I can try to create a pull request, but want to confirm the kind of call that should be supported. Also, will be helpful for tests.

**Comment by ankane** [comment]
For the code above, use:

```ruby
Product.search "car", page: 0, per_page: 10, order: {created_at: {order: "desc"}}
```
