### ISSUE TITLE
Suggestions not working on latest version of Elasticsearch (2.1.1)

### ISSUE THREAD

**Issue by abevoelker** [ankane/searchkick#592]
This may be a duplicate of #494 but wanted to open a new issue in case not.

I recently got a new machine (Ubuntu), and checked out a somewhat-stale Rails project where I was using Searchkick 0.9.0 successfully. My new machine didn't have Elasticsearch installed, so I followed the latest install instructions for Ubuntu (which seemed to have changed a little bit with the newer Elasticsearch version since I had installed it on my old PC, which was also Ubuntu).

Anyway, I know my test suite was running fine on the old version of Elasticsearch, but on my new machine I'm running into the same error as #494. No code has changed on the Ruby/Rails side, and I'm still using the same version of Searchkick, so I'm blaming Elasticsearch for now. The issue persisted even after updating to the latest Searchkick version (1.1.2) and updating my "facets" syntax to "aggs" as the README suggests.

I took a look at the Searchkick specs but didn't quickly see how to reproduce the issue there, so I made a barebones Rails app and a Dockerfile mimicking how I installed Elasticsearch that reproduces the problem: https://github.com/abevoelker/searchkick-suggest-bug-repro

This is the version info reported by Elasticsearch:

```
$ curl http://localhost:9200
{
  "name" : "Overkill",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

Hope it helps!

**Comment by abevoelker** [comment]
Nevermind, it seems something to do with searchkick needing at least one record to exist in the database. I'll adjust my specs.

**Comment by muhammadn** [comment]
Hi @abevoelker 

can you share what you did to solve this problem? i am using the latest searchkick 2.1 and elasticsearch 5 and i came across the same error.

`[400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No mapping found for field [job_type.suggest]"}]`

**Comment by muhammadn** [comment]
Okay, i missed that point. I need at least *one record* in the jobs table.
