### ISSUE TITLE
Using searchkick to do personalized recommendations balloons the number of documents in elastic search.

### ISSUE THREAD

**Issue by simonv3** [ankane/searchkick#595]
I don't know if this is expected or not, but we have a model that gets indexed by ES and is personalized for each user of our app ([openfarm](https://github.com/openfarmcc/OpenFarm/)).

Our model looks like this: https://github.com/openfarmcc/OpenFarm/blob/master/app/models/guide.rb

What's happening as a result is that for every guide that gets created, we get the amount of users + guide of new documents in our ES service. This makes sense in a way, but we thought that by nesting the compatibilities within the guide, we'd be avoiding that. 

Is there something we're missing?

**Comment by ankane** [comment]
Nested objects are indexed as separate documents internally, which is what you're seeing. https://www.elastic.co/guide/en/elasticsearch/reference/2.0/nested.html
