### ISSUE TITLE
Deployment using nginx - puma

### ISSUE THREAD

**Issue by VinoyN** [ankane/searchkick#596]
I get this error when deploying with nginx-puma. It works with nginx-unicorn. I am using capistrano 3.4.0

<code>
/var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/searchkick-0.9.0/lib/searchkick/model.rb:7:in `searchkick': Only call searchkick once per model (RuntimeError)
	from /var/www/captain_wholesaler/releases/20160106051917/app/models/spree/variant_decorator.rb:145:in `block in <top (required)>'
	from /var/www/captain_wholesaler/releases/20160106051917/app/models/spree/variant_decorator.rb:1:in `class_eval'
	from /var/www/captain_wholesaler/releases/20160106051917/app/models/spree/variant_decorator.rb:1:in `<top (required)>'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:317:in `depend_on'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:471:in `each'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:471:in `block in eager_load!'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:469:in `each'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:469:in `eager_load!'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/engine.rb:346:in `eager_load!'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application/finisher.rb:56:in `each'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:30:in `run'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/railties-4.2.2/lib/rails/application.rb:352:in `initialize!'
	from /var/www/captain_wholesaler/current/config/environment.rb:5:in `<top (required)>'
	from /var/www/captain_wholesaler/current/config.ru:3:in `require'
	from /var/www/captain_wholesaler/current/config.ru:3:in `block in <main>'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /var/www/captain_wholesaler/current/config.ru:in `new'
	from /var/www/captain_wholesaler/current/config.ru:in `<main>'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/configuration.rb:144:in `load_rackup'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/configuration.rb:97:in `app'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/runner.rb:113:in `load_and_bind'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/single.rb:79:in `run'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/cli.rb:215:in `run'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/gems/puma-2.15.3/bin/puma:10:in `<top (required)>'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/bin/puma:23:in `load'
	from /var/www/captain_wholesaler/shared/bundle/ruby/2.2.0/bin/puma:23:in `<main>'
</code>

**Comment by ankane** [comment]
Sorry Vinoy, I'm not sure what would be causing this. It looks like the `searchkick` method is being loaded into your model twice, but I'm not sure why. I've used it successfully with both Puma and Unicorn.

**Comment by Rynaro** [comment]
I've got the "Only call searchkick once per model", in all of my models today. But my models only call searchkick method one time.
I really don't know, how this happens. I'm only pushed some views files in my server and restarted NGINX passenger.
If I remove searchkick method from my model, the app works again, in pages that don't "searchkicked" models.
In time, I dont have a solution of the problem. But this a case to study.

**Comment by ankane** [comment]
Cleaning up issues
