### ISSUE TITLE
Missing documents

### ISSUE THREAD

**Issue by claudeomusic** [ankane/searchkick#597]
Not sure what's going on here. I had trouble with a search query not returning the proper number of results, so I installed an ES plugin called head to let me browse my ES nodes.

I have a model that has 492973 documents in it, but when I reindex manually (Model.reindex), the plugin shows me that only 7218 docs are in the index (without any errors). Any help is much appreciated! Not really sure what may potentially be causing this

**Comment by claudeomusic** [comment]
Thought I had figured it out so I had closed it, but continuing to see this odd issue. So I was able to narrow down the issue to my defining of the indexes. I have a model called Song I'm trying to index and ,specifically, the index labeled 'performer_name' is causing the issue. But I can't find anything wrong with the way I structured things for that...

```
def search_data
    {
      worktitle:                worktitle,
      alternatetitles:          alternatetitles,
      writer_firstname:         writers.map(&:firstname),
      writer_middlename:        writers.map(&:middlename),
      writer_lastname:          writers.map(&:lastname),
      artists:                  artists.map(&:name), 
      created_at:               created_at,
      date_of_pub:              date_of_pub,
      owner_ids:                writers.map{|x| x.profile.id.to_s},
      performer_name:           performers.map(&:name)
    }
  end
```

**Comment by claudeomusic** [comment]
What causes an index to fail midway without an errors? Is that just elasticsearch running out of memory? It always seems to stop on the 7218th document.  

Appreciate any help!! Really stuck on this one.

**Comment by ankane** [comment]
It's likely something specific to your set up. I'd suggest Googling around for possible answers.
