### ISSUE TITLE
undefined local variable or method `searchkick'

### ISSUE THREAD

**Issue by f7n** [ankane/searchkick#599]
I'm trying to use searchkick along with my Neo4j database and Sinatra. I'm getting this error:

	NameError: undefined local variable or method `searchkick' for Movie:Class
	
	models/movie.rb:4:in `<class:Movie>'
	models/movie.rb:1:in `<top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:7:in `load'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:7:in `block in <top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:6:in `each'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/environment.rb:6:in `<top (required)>'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/app.rb:1:in `require'
	/Users/fin/Documents/uni/4th Year/Honours Project/build-v2/app.rb:1:in `<top (required)>'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:115:in `require'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:115:in `inner_app'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Library/Ruby/Gems/2.0.0/gems/shotgun-0.9.1/lib/shotgun/static.rb:14:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'

Here is my Model file:

	class Movie
	  include Neo4j::ActiveNode
	
	  searchkick
	
	  property :id
	  property :movieID
	  property :title
	  property :year
	  property :imdB
	  property :rtRating
	  property :poster
	end

and the gemfile: 

	source 'https://rubygems.org'
	
	gem 'searchkick'
	gem 'sinatra'
	gem 'neo4j'
	gem 'haml'
	gem 'shotgun'

Just to confirm: I don't need to require this gem anywhere right? Just include it in my gemfile?

**Comment by f7n** [comment]
requiring searchkick produces this error:

`NoMethodError: undefined method `attr_internal' for Searchkick::ControllerRuntime:Module`

**Comment by danielrsmith** [comment]
Based on the codebase the method `searchkick` is added the `ActiveRecord::Base` class only.  From what I can see ActiveRecord is the only ORM supported by this gem.

**Comment by f7n** [comment]
That's frustrating. I was following Neo4j.rb's suggestion from here: https://github.com/neo4jrb/neo4j/wiki/Indexing-VS-Legacy-Indexing#i-really-need-full-text-searches-what-can-i-do

**Comment by danielrsmith** [comment]
Have you looked at: https://github.com/neo4jrb/neo4j-searchkick ?

**Comment by f7n** [comment]
Yeah, it was the first thing I tried, same problem unfortunately. Do you think including ActiveRecord in my gemfile would fix my issue?

**Comment by danielrsmith** [comment]
No, since it is already a dependency of the searchkick gem (look at your Gemfile.lock, I'm sure it's in there).  If you read the article you sent, you will see: "We added the methods it requires for interoperability with the gem and have had a great experience with it so far."  I suggest asking neo4jrb for help.

**Comment by f7n** [comment]
Thank you, I will do that.

**Comment by nguyenchiencong** [comment]
Hi @f7n ,
Did you have any luck integrating searchkick with neo4j? Would you mind sharing how you did it?
Thanks.
