### ISSUE TITLE
Add section on testing w/ Searchkick

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#60]

**Comment by 7h3kk1d** [comment]
I'm using the immediate syncing and the disable_callbacks doesn't seem to stop the indexing. Is there a normal way to disable it while running tests?

**Comment by ankane** [comment]
Calling `Searchkick.disable_callbacks` should completely disable automatic syncing.

**Comment by evanboho** [comment]
@7h3kk1d I ended up just stubbing out the client, which solved all of the issues with very little code:
```
RSpec.configure do |config|
  searchkick_client = Searchkick.client

  config.before(:each) do |example|
    if example.metadata.key?(:searchkick)
      Searchkick.client = searchkick_client
    else
      Searchkick.client = SuperStub.new
    end
  end
end
```

(and `SuperStub` is just a class that returns `self` for `method_missing`)

**Comment by ysyyork** [comment]
@evanboho Can you share your SuperStub code? I tried a stub class return self for method_missing but it complains a lot of errors. I don't know if my SuperStub class implementation if correct. Basically I just override the method_missing method to return self. Thanks

**Comment by evanboho** [comment]
@ysyyork I don't have it in front of me anymore, but I think it was as simple as:
```
class SuperStub
  def method_missing(*args)
    self
  end
end
```

**Comment by ysyyork** [comment]
@evanboho yea I tried this but it failed in some cases. OK, thanks, now I know it should be other issues. I will investigate.

**Comment by josephecombs** [comment]
what a wonderful thread.  thanks @evanboho

**Comment by ankane** [comment]
Going to close this out. I think we have a pretty good start, and happy to add to it/improve it through additional issues/PRs.
