### ISSUE TITLE
search with searchkick in a translation table (with has_many association)

### ISSUE THREAD

**Issue by Loamys** [ankane/searchkick#603]
This is the model I'm indexing:
class Backend::Area < ActiveRecord::Base
  has_many :area_tourism_descriptions	
end

and this is the related model that has a translation table:
class Backend::AreaTourismDescription < ActiveRecord::Base
  belongs_to :area
  belongs_to :tourism_type
  translates :area_tourism_description_text
end

I've tried 2 things:
#1:
def search_data
    data = {}
    data[:area_tourism_type_descriptions] = []
    l = Backend::Language.pluck(:language_abrev)
    i=0
    actual = I18n.locale
    area_tourism_descriptions.each do |property|
      # I18n.locale = l[i]
      property[:locale] = 'es'
      data[:area_tourism_type_descriptions] << property.area_tourism_description_text
      i+=1
    end
    # I18n.locale=actual

   data
end

This returns me an array with ["trans",nil], and if I uncomment [nil,nil] (I have only 2 languages and an area has now only a tourism_type but translated the description to english and spanish).

#2: 
def search_data
    data = {
      area_tourism_type_descriptions: area_tourism_descriptions.pluck(:area_tourism_description_text)
    }
end

And this throws:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: area_tourism_description_text: SELECT area_tourism_description_text FROM "area_tourism_descriptions"  WHERE "area_tourism_descriptions"."area_id" = ?
SQLite3::SQLException: no such column: area_tourism_description_text

What should I do?
Thanks.

**Comment by ankane** [comment]
Looks like there's an error with your `search_data` method (unrelated to Searchkick).  The first step is get ` Backend::Area.first.search_data` working.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by Loamys** [comment]
how can i do that?
I didn't understand!
