### ISSUE TITLE
Reindex seems to create new shards ?

### ISSUE THREAD

**Issue by th3m4ri0** [ankane/searchkick#604]
Hi,
I'm using Bonsai on Heroku.
When I run `heroku run rake searchkick:reindex:all`, I get a timeout error.  
```
Faraday::TimeoutError: Net::ReadTimeout
```
On the Bonsai dashboard, I can see that I'm using all shards : 
<img width="917" alt="capture d ecran 2016-01-16 a 16 40 42" src="https://cloud.githubusercontent.com/assets/2685884/12374644/e5add682-bc6f-11e5-918d-edb216be3cbf.png">
Any idea what's happening ?

**Comment by ankane** [comment]
I believe the default number of shards is 6 (5 primary and 1 replica). You can change this with:

```ruby
searchkick settings: {number_of_shards: 1, number_of_replicas: 0}
```

**Comment by th3m4ri0** [comment]
Thanks !
