### ISSUE TITLE
stopwords

### ISSUE THREAD

**Issue by rishijain** [ankane/searchkick#608]
Is it possible to add a list of words to ignore while searching?

`stopwords: ["a", "an"]`

**Comment by ankane** [comment]
Searchkick uses a common terms query, so there's no need to ignore them. https://www.elastic.co/blog/stop-stopping-stop-words-a-look-at-common-terms-query

**Comment by rishijain** [comment]
@ankane  Thanks for this. Would still need to be able to add stop words for a custom list of words to ignore.

**Comment by ankane** [comment]
No direct support for this right now, so you'd need to filter them out in the `search_data` method.

**Comment by rishijain** [comment]
Got it. Thanks.

**Comment by ericbeansmile** [comment]
@ankane Does Searchkick support stopwords now?
