### ISSUE TITLE
Update only elasticsearch

### ISSUE THREAD

**Issue by tacnoman** [ankane/searchkick#610]
Hello guys.

I want to update only the elasticsearch (without update model). I want to make a rating system with a cronjob in batch (updating the database in each 10 minutes with cronjob), but in every update in searchkick the code run a query too.

My code is:
```ruby
post = Post.search(1, load: false).first
post.qt_positive = post.qt_positive.to_i + 1
post.reindex # Returning nil
```
If I made this, the elasticsearch does not update.
If I remove the "load: false", the database updates too.

How can I do to update only elasticsearch model?

Thanks for this.

**Comment by ankane** [comment]
Searchkick isn't really designed for this.  You'll need to use the `elasticsearch-ruby` client directly by calling `Searchkick.client`.  See the `elasticsearch-ruby` docs on how to use it.

**Comment by tacnoman** [comment]
Thanks man!
