### ISSUE TITLE
Elasticsearch picks wrong data type

### ISSUE THREAD

**Issue by kavitakanojiya** [ankane/searchkick#620]
I have added new boolean column. Now, I didnt reindexed the whole table. But elasticsearch index picks up this column with datatype as 'long'. Is it possible to shed some light why elasticsearch/searchkick picks this `long` datatype ?

Some docs/pointers will be helpful.

**Comment by ankane** [comment]
Datatype selection happens in Elasticsearch, so its docs would be the best place to look.

**Comment by kavitakanojiya** [comment]
Thanks
