### ISSUE TITLE
Add timeout parameter to rake task

### ISSUE THREAD

**Issue by th3m4ri0** [ankane/searchkick#622]
It would be great to be able to force a timeout on the rake task. For example : `rake searchkick:reindex:all timeout=20`

**Comment by ankane** [comment]
Hey @th3m4ri0, what's the use case for this?

**Comment by th3m4ri0** [comment]
Ah! Trying to remember what I was doing back in February.  
I think I had a large DB to reindex, on a free plan with whatever PaaS I used, that would time out before the reindex was actually finished.

**Comment by ankane** [comment]
I'm not sure an extra option is needed. You should be about to set:

```ruby
Searchkick.timeout = 20 # reindex timeout
Searchkick.search_timeout = 5
```

In an initializer.

**Comment by th3m4ri0** [comment]
That's what I ended up doing. The parameter would have allowed me to do this as a temporary workaround for my PaaS limitations, and save me two git commits ("Raise timeout for reindex" & "Revert commit xxxxx")
😜

**Comment by ankane** [comment]
You shouldn't need to revert - those settings can be permanent. Anyways, don't think there's a strong enough case for it.
