### ISSUE TITLE
oped::Errors::CursorNotFound for Model.reindex

### ISSUE THREAD

**Issue by peddinti** [ankane/searchkick#628]
I am trying to reindex my model and why i hit model.reindex i am getting the following error. I am thinking this is because the no. of documents and size of each document is high. I didn't problem running reindex for other models. Can anyone suggest how to work around this? More details on the exception

Moped::Errors::CursorNotFound: The operation: "GET MORE"
failed with error "cursor 6129250988039150877 not found"
from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/moped-1.5.3/lib/moped/node.rb:218:in `get_more'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/moped-1.5.3/lib/moped/cursor.rb:44:in `get_more'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/moped-1.5.3/lib/moped/cursor.rb:29:in `each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/moped-1.5.3/lib/moped/query.rb:76:in `each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/moped-1.5.3/lib/moped/query.rb:76:in `each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/mongoid-3.1.7/lib/mongoid/contextual/mongo.rb:122:in `block in each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/mongoid-3.1.7/lib/mongoid/contextual/mongo.rb:619:in `selecting'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/mongoid-3.1.7/lib/mongoid/contextual/mongo.rb:121:in `each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/mongoid-3.1.7/lib/mongoid/contextual.rb:19:in `each'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/searchkick-1.2.0/lib/searchkick/index.rb:191:in `import_scope'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/searchkick-1.2.0/lib/searchkick/index.rb:160:in `reindex_scope'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/searchkick-1.2.0/lib/searchkick/model.rb:51:in `searchkick_reindex'
        from (irb):10
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
        from /home/ubuntu/resume/shared/bundle/ruby/2.2.0/gems/railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'

**Comment by peddinti** [comment]
hi any update on this?

**Comment by ankane** [comment]
Sorry @peddinti, not a big Mongo user, but maybe someone else will chime in.

**Comment by peddinti** [comment]
I finally found the answer to this. We need to use batch import to avoid cursor timing out as each document is big the cursor times out.
Model.all.in_groups_of(1000, false) do |batch|
  Model.searchkick_index.import(batch)
end
