### ISSUE TITLE
Implementing Count API

### ISSUE THREAD

**Issue by milankubin** [ankane/searchkick#632]
Hi,

I've been looking into extending Searchkick with the ES Count API
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html

An example use case is where paginated results are displayed on one page, but on another page a link is provided with the amount of results for the search query provided.
I have done simple testing and the Count API is a lot quicker in providing a count, cached or uncached.
However, looking into Searchkick's core it didn't seem as simple as I wanted, since the Search API is too tightly hardcoded into the core search functionality.

Would this be a nice to have feature for this gem, or do you think this would be too out of scope?
If the former is true, could you maybe give me some pointers on how I would go about in implementing this without messing up core? I'd love to contribute :) 

Just to clarify, the Count API basically takes the same arguments as the Search API, it's just the URL and result set that differs.

Thanks

**Comment by ankane** [comment]
Hey @milankubin, I appreciate your interest in contributing.  Very sorry for not getting back to you earlier.  I'm not sure I would use this myself, but happy to accept a PR if it doesn't complicate things.  If the count API is the same as the search API, you could probably accomplish this by making changes the `Searchkick::Query#execute` method.  Also, don't forget to add tests.
