### ISSUE TITLE
Can searchkick index on an model instance method?

### ISSUE THREAD

**Issue by waleedasif322** [ankane/searchkick#633]
Hi, I tried to set the searchkick index on an model instance method in various ways but I cannot get it to work:

```RUBY
class Patient < ActiveRecord::Base
  # database columns:
  # t.string :first_name
  # t.string :last_name
  searchkick match: :word_start, searchable: [:name]

  def name
    "#{first_name} #{last_name}"
  end

  # below doesn't work if I use facets or aggs
  def search_data
    {name: "#{first_name} #{last_name}"}
  end
end
```

(I reindex the Patient table after I change the search_data method or the searchkick clause)

I want to be able to search both `first_name` AND `last_name`, and since I have them in separate columns, I want to know if I can setup the search index on a method like above. If there are any other solutions to be able to search both `first_name` and `last_name`, please let me know. 
Adding `  searchkick match: :word_start, searchable: [:first_name, :last_name]` on a model does not search both fields simultaneously. Example: searching my name: "waleed asif" will yield no results, but searching: "waleed" OR "asif" separately will.

Thanks

**Comment by ankane** [comment]
Hey @waleedasif322, Searchkick doesn't currently have a way, but Elasticsearch has a [cross-fields query](https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_queries.html) to accomplish this if someone wants to add it.

**Comment by waleedasif322** [comment]
I ended up searching a `full_name` field instead. Should I close this issue?

**Comment by ankane** [comment]
Yeah, I'll create a new issue for the cross fields feature.
