### ISSUE TITLE
Search by time from datetime field

### ISSUE THREAD

**Issue by sars** [ankane/searchkick#637]
Hi there!

Thanks for this lib!

I'm trying to filter records by time... 
So I have smth like:

``` ruby
def search_data
    {
      created_at: created_at
    }
end
```

Now I need to filter search results so only records created at 18:00 left

I cannot find how to do that... 
Please, suggest me something...

**Comment by asiniy** [comment]
@sars use this solution with `:gte` & `:lte`: https://github.com/ankane/searchkick/issues/640#issuecomment-193584315

@ankane feel free to close this
