### ISSUE TITLE
Ability to specify global index_prefix for all models that use searchkick

### ISSUE THREAD

**Issue by jhirbour** [ankane/searchkick#644]
I know it's possible to add index_prefix on each model. 

Is there a way to specify in the searchkick initializer an index_prefix that all models would then use?

If there isn't would you be open to a PR that implemented this feature?

**Comment by ankane** [comment]
There's no way right now, but I'm open to global options.

**Comment by danielrsmith** [comment]
@ankane should we build this in the same way `Searchkick.index_suffix` was built - with the difference being that the classes version takes precedent?

**Comment by ankane** [comment]
@danielrsmith sounds good to me if you want to create a PR
