### ISSUE TITLE
Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] {"status":"error", "message":"given key is invalid"}

### ISSUE THREAD

**Issue by shoaibmalik786** [ankane/searchkick#646]
I am getting this error when i am trying to run heroku run rake searchkick:reindex CLASS=Product
I have created a searchbox addon on heroku using heroku addons:create searchbox:starter.
I got the url of searchbox 
SEARCHBOX_URL: **[REDACTED]**

I followed the documentation of searchkick gem. Please help me out asap.

Thanks in advance

**Comment by ankane** [comment]
I removed your searchbox url for security. Since anyone could have seen it, you should recreate the add on.

```sh
heroku addons:destroy searchbox:starter
heroku addons:add searchbox:starter
heroku config:add ELASTICSEARCH_URL=`heroku config:get SEARCHBOX_URL`
```

**Comment by ankane** [comment]
Cleaning up issues

**Comment by liulupeng1987** [comment]
when I am running `rake searchkick:reindex CLASS=Api`, I get error below, please help me.
`
rake aborted!
Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] {"status":"error", "message":"given key is invalid"}
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/indices/get_aliases.rb:29:in `get_aliases'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/index.rb:184:in `all_indices'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/index.rb:194:in `clean_indices'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/index.rb:222:in `reindex_scope'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/model.rb:70:in `searchkick_reindex'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/tasks.rb:9:in `block (2 levels) in <top (required)>'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/liulupeng/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => searchkick:reindex
(See full trace by running task with --trace)`

**Comment by mhluska** [comment]
I'm getting the same issue. @ankane the code above to remove and recreate the addon doesn't actually fix the 401 issue. Following the readme seems to lead to this 401 issue.
