### ISSUE TITLE
Net::ReadTimeout when reindexing

### ISSUE THREAD

**Issue by mkralik** [ankane/searchkick#647]
I recently upgraded my elasticsearch from 1.8 to 2.2 (now downgraded to 2.0.2) and problems have started since that time.

When I try to reindex products (40k), I get the Net::ReadTimeout error after 1000 products are reindex (the batch_size is set to 1000 by default).

I tried to set batch_size for searchkick to 1, 100, 200, and even then I get the Net::ReadTimeout error. When it was set to 1, it reindexed almost 20k products, if 100, only 100, if 200 only 200 products when it threw that error and the reindexing stops.

Do you know why this error occurs and how to avoid it? I have tried so many things (increase timeout from 1 to 10 minutes on the server, delete indexes, set the batch_size many times..) and nothing helped.

I have spent on this already few days and am totally stuck, will appreciate any ideas or help.

Thanks a lot for your time, Miroslav

Attachments
Img_1: Fails once 1000 documents are index
![2016-03-14_0042](https://cloud.githubusercontent.com/assets/4296992/13731909/d9d6acf4-e97d-11e5-96a9-6c68e763dde2.png)

Img_2: Products index view
![2016-03-14_0045](https://cloud.githubusercontent.com/assets/4296992/13731934/29af2170-e97e-11e5-9536-b06f02b995de.png)

**Comment by ankane** [comment]
I'd try emailing your ES provider to see if they can provide any insight.
