### ISSUE TITLE
Undocumented feature? search_document_type

### ISSUE THREAD

**Issue by sumitngupta** [ankane/searchkick#658]
Aloha!

I was wondering what the intended purpose of the "search_document_type" protected method was? I imagined if the record defines it that it was intended to be overriden by developers in some way with the `responds_to?` check. 

I've been trying to wrangle a bunch of STI issues and setting that to be my base-class name seems to have done the trick. My main question is if my usage of it is going to screw me in some way in the future since I can't find any public doc's on the method. 

<3 searchkick,
Sumit

**Comment by ankane** [comment]
It's not documented yet, but it's an official feature, so safe to use.

**Comment by sumitngupta** [comment]
Sweet, thanks!  

It feels like the only thing im losing is the ability to use my subclass searches (ex: Dog.search and Cat.search will return nothing because im forcing all records to be indexed with the search_document_type as Animal)  but at present I'm okay with it since it eliminated a lot of really weird side effects I was seeing and the need to do surgery on the search index whenever the `type` was changing on an object (which wasn't working anyways). Going to keep my eye out for a better solution in the end but wanted to be sure I wasn't using an obscure part of the API that would change out from under me. 

Thanks again!
