### ISSUE TITLE
Searching ruby hash inside of attribute

### ISSUE THREAD

**Issue by MadhuKosuriSG** [ankane/searchkick#659]
HI Team,
I am having requirement to perform searching serializer key value inside attribute. i.e 
  Suppose I have model User and its columns.
    {
      first_name: "user first name",
       last_name : " user last name "
      address: "line_1: "This is line one' "
                     "line_2": "This is line-two"
                     "city": "city"  
    }
I want search city inside of address.
Thanks

**Comment by ankane** [comment]
Hey @MadhuKosuriSG, you can use dot notation (see readme) to do this.
