### ISSUE TITLE
Searchkick potentially causing duplicate http requests

### ISSUE THREAD

**Issue by erlandsona** [ankane/searchkick#661]
Gem Versions:
- Rails 4.2.3
- Rack 1.6.4
- Sidekiq 4.1.1
- Unicorn 5.0.1

I'm working on a Rails app with latest searchkick on a model and when we hit the index page for that model /models, I'm showing to separate but mostly equivalent http requests for /models in the logs of all the rails environments Prod, Dev, Staging.

This stops happening when returning 2 or 3 results but when returning more than that the browser seems to be sending multiple requests. However if we return instead Model.first(50) only one request gets registered.

Wondering if anyone else has encountered this type of issue and how it was debugged.

**Comment by bdfinlayson** [comment]
So this appears to be related to implementation of 'misspellings' support in the SearchKick [Query class](https://github.com/ankane/searchkick#misspellings). If too few results are returned with no misspellings a second search is performed with them with:

        def execute_search
          Searchkick.client.search(params)
        end
in https://github.com/ankane/searchkick/blob/e0869bcff7826bd1e70143f62a02aa4679e49f2e/lib/searchkick/query.rb
and https://github.com/ankane/searchkick/blob/19a03896efcc7ba1c6cf233f1ab9b83ce7801a6a/lib/searchkick.rb

**Comment by ankane** [comment]
Thanks for the assist @bdfinlayson 👍
