### ISSUE TITLE
Searches only work if strings, but why?

### ISSUE THREAD

**Issue by ilovemysillybanana** [ankane/searchkick#666]
I was having trouble with using a where clause because no matter where I put it for some reason it would never work, giving me an undefined method error:

> /home/jose/Workspace/sochi/app/controllers/users_controller.rb:11: syntax error, unexpected ',' ...User.search(params[:search]), , where: {available: true} ... ^

After reading through the docs and several issues, I found the problem was with my users controller

`@users = User.search(params[:search]), , where: {available: true}` this doesn't work

But this does:

`@users = User.search "#{params[:search]}", where: {available: true}`

But why, shouldn't these lines be identical in function?

**Comment by chrisgogreen** [comment]
`@users = User.search "#{params[:search]}", where: {available: true}` is the same as

`@users = User.search("#{params[:search]}", where: {available: true})`

if you want to pass an empty argument, the best you can do is nil, like:

`User.search(params[:search], nil , where: {available: true})`

but the problem and the exact reason for the error is that you have a comma immediately following the search `method` call.

**Comment by ankane** [comment]
As @chrisgogreen mentioned, this is a Ruby syntax issue.
