### ISSUE TITLE
Multi-schema issues

### ISSUE THREAD

**Issue by jimmybaker** [ankane/searchkick#667]
I'm considering using searchkick for my app but I'm running into a few issues.

My app is multi-tenant. Each tenant has their own postgres schema.

I'm using the "search_document_id" to uniquely identify elasticsearch records by combining the record id with the tenant's id like so:

```
def search_document_id
  "#{id}-#{tenant_id}"
end
```

The two issues I'm having at the moment are:

1) How do I run index on each schema? Currently Model.reindex destroys the existing records and reindexes. The way I do this now (not using searchkick currently) is to loop over each tenant, scope the database connection to the tenant's schema and import records. Is there a method that I can use to do this with searchkick?

2) After modifying the search_document_id I am getting strange results as you can see from the image below: 

<img width="1256" alt="image 2016-05-01 at 1 26 44 am" src="https://cloud.githubusercontent.com/assets/50668/14940463/067dd974-0f3c-11e6-9db0-1d4039701401.png">

You can see that the query to ES was successful and that it yielded some results. However, if I try to loop over the results it acts like there are none. Calling "count" or "size" returns 0 but you can see that when I called count, it ran a database query for items that DO exist yet returns 0. What's up with that?

Any tips on handling multi-tenant scenarios with searchkick are also welcome!

**Comment by jimmybaker** [comment]
So I found the answer to the first question. The Index class has and import method that I can use to manually index records from each tenant without destroying prior tenant's records. Example:

```
Product.searchkick_index.import(Product.all)
```

I'm still stuck on the second question, but at this point it's not a show stopper. Since the records come back out of order, I'll have to query them myself and specify the order using an array of the id's returned from the searchkick search.

**Comment by ankane** [comment]
Hi Jimmy, check out [this post](https://www.tiagoamaro.com.br/2014/12/11/multi-tenancy-with-searchkick/). You'll want to follow a similar pattern.

**Comment by jimmybaker** [comment]
@ankane - Perfect. Thank you!
