### ISSUE TITLE
How to search for a nil value?

### ISSUE THREAD

**Issue by slead** [ankane/searchkick#673]
TL;DR: What is the syntax to search for a nil value in Searchkick?

In a Rails 4 app, I have related models Applicant and Trademark, with the latter searchable using Searchkick:

```
class Applicant < ActiveRecord::Base
  has_many :trademarks
end

class Trademark < ActiveRecord::Base
  belongs_to :applicant
  searchkick
end
```
I'm trying to find instances of Trademark which do not have an Applicant. Using standard ActiveRecord the below query works, and returns the Trademark without an Applicant:

```
Trademark.where(applicant: nil).count
   (1.7ms)  SELECT COUNT(*) FROM "trademarks" WHERE "trademarks"."applicant_id" IS NULL
 => 1 
```
How can I run the equivalent query with the addition of SearchKick?

```
# these queries run correctly and show that SearchKick is working
Trademark.search "*" # => 7 records
Trademark.search "*", where: {status: "Removed"} # => 5 records

# When trying to search for applicant == nil, the search fails:

# this returns 7 records, instead of the 1 expected result
Trademark.search "*", where: {applicant: nil} 

# this returns 0 records, instead of the 1 expected result
Trademark.search "*", where: {applicant_id: nil}
```
How can I use a where clause for a nil value in SearchKick?

Thanks (and also thanks for writing such an awesome tool)

**Comment by ankane** [comment]
Searching for a `nil` value should work as you have it in the last case (tests are passing).  I'd inspect

```ruby
Trademark.search("*", load: false).response
```

to see if things are out of sync between your database and Elasticsearch. If so, you can reindex.

**Comment by slead** [comment]
Bingo - I needed to reindex the model. Thanks for the fast response
