### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by bsodmike** [ankane/searchkick#674]
Hi @ankane,

Just wanted to check if you've planned for Rails 5 support?  Noticed there was a pessimistic version constraint on AR v4.x.x in the Gemfile.

Cheers!

**Comment by ankane** [comment]
Hi Michael, Searchkick currently works with Rails 5.  The Gemfile is only used for [testing](https://travis-ci.org/ankane/searchkick).  The [gemspec](https://github.com/ankane/searchkick/blob/master/searchkick.gemspec#L21) is pretty liberal, and has no dependency on activerecord.

**Comment by bsodmike** [comment]
Great, thanks!

**Comment by vishesh111** [comment]
does it also works with other rails version ?? ... like < 5
