### ISSUE TITLE
Order by two fields ?

### ISSUE THREAD

**Issue by yurgon** [ankane/searchkick#675]
Hello
How to order/sort by two fields ?

Thx

**Comment by jordanderson** [comment]
You can pass an array to order, like: `order: [{"column1" => :desc}, {"column2" => :desc}]`

**Comment by yurgon** [comment]
its not work

**Comment by ankane** [comment]
Hey @yurgon, the tests for multiple orders pass. Can you create a failing test case for it?

**Comment by ankane** [comment]
Cleaning up issues
