### ISSUE TITLE
Boost a certain Index for Multi Index search

### ISSUE THREAD

**Issue by RyanSnodgrass** [ankane/searchkick#676]
The question I have is how do I boost a certain index? I want to prioritize a model and have those matches brought back first or close to it.

I know [Elasticsearch supports this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-index-boost.html). But I can't find in the Searchkick docs how to do this.

maybe something like this?
```ruby
class HighlyImportant
  searchkick boost: :this_index
  def search_data
    { name: name }
  end
  def name
  end
end
```

Through some Lucene voodoo magic that emphasizes how little I know goes on under the hood, Elasticsearch seems to choose certain indexes and give them very high scores by default.

The hack, and it seems VERY hacky, is to add an `object_importance` field and boost that. It feels especially hacky because of just how much of a factor I have to boost my `HighlyImportant` class over others.

```ruby
# app/models/foo.rb
class Foo
  searchkick
  def search_data
    { name: name,
      object_importance: object_importance }
  end

  def name
  end

  def object_importance
    0
  end
end
```
```ruby
# app/models/bar.rb
class Bar
  searchkick
  def search_data
    { name: name,
      object_importance: object_importance }
  end

  def name
  end

  def object_importance
    0
  end
end
```
```ruby
# app/models/highly_important.rb
class HighlyImportant
  searchkick boost: :this_index
  def search_data
    { name: name,
      object_importance: object_importance }
  end

  def name
  end

  # yes, 10 million is how much importance I have to put on this number
  def object_importance
    10_000_000
  end
end
```
```ruby
results = Searchkick.search('query', boost_by: { object_importance: { factor: 10**15 } }
```

I would like this defined in the index level for me because in my situation, the `HighlyImportant` class will always need to be returned to the top

What else could be causing the Foo and Bar classes to be such a high default score? I've tried blowing away the index, but that didn't changed the scores being returned. I know the Foo and Bar classes have many more entries in the database so maybe that's what is causing it?

**Comment by ankane** [comment]
@RyanSnodgrass Searchkick now has an `indices_boost` option. https://github.com/ankane/searchkick#multiple-indices

However, if you always want one class to score higher than another, I'd use a `multi_search` instead.

**Comment by RyanSnodgrass** [comment]
Thanks for the response @ankane !

[Multi Search](https://github.com/ankane/searchkick#multi-search) ended up being the solution we needed. For those who stumble upon this question, here is the solution we came up with

```ruby
class SearchService
  def self.multi_search(query)
    @query = query
    create_searchable_variables_for_multi_model_search
    Searchkick.multi_search(array_of_searchkick_objects)
    array_of_searchkick_objects.map(&:results).flatten
  end

  private

  def self.array_of_searchkick_objects
    array_of_models.map do |klass|
      instance_variable_get("@#{klass.to_s.downcase}s")
    end
  end

  def self.searchable_fields
    ['name^2', 'description', 'definition']
  end

  def self.create_searchable_variables_for_multi_model_search
    array_of_models.each do |klass|
      instance_variable_set("@#{klass.to_s.downcase}s",
                            klass.search(@query, fields: searchable_fields,
                                                 match: :word_start,
                                                 execute: false))
    end
  end

  def self.array_of_models
    [Report, Dataset, Term, Office, PermissionGroup]
  end
end
```
