### ISSUE TITLE
Geospatial search gives "NoMethodError: undefined method `to_f' for :lat:Symbol"

### ISSUE THREAD

**Issue by slead** [ankane/searchkick#677]
I have a model which has float fields for latitude and longitude, which were calculated using the geocoder gem:

```
puts [Entity.first.latitude, Entity.first.longitude].join(",")
40.7638258,-73.9749381
```

I'm trying to use the geospatial search so I've added the following, modelled after your example:

```
class Entity < ActiveRecord::Base
  geocoded_by :geocode_address
  searchkick locations: ["location"]
  def search_data
    attributes.merge location: {lat: latitude, lon: longitude}
  end
end
```

`Entity.reindex()` returns `NoMethodError: undefined method 'to_f' for :lat:Symbol`

This message is also mentioned in https://github.com/ankane/searchkick/issues/233 but I'm not sure if that's related. Some entities had blank values for latitude/longitude so I tried calculating them all to 0, but the problem persists.

Thanks for any advice.

PS I came up with a workaround which works well enough, but I'd be interested to handle this properly:

```
whereClause = {longitude: {gt: params[:xmin]}, longitude: {lt: params[:xmax]}, latitude: {gt: params[:ymin]}, latitude: {lt: params[:ymax]}}
Entity.search params[:query], where: whereClause
```

**Comment by ankane** [comment]
Hi Stephen, are you on the latest version?  From the error, it sounds like it may be an older version.

**Comment by slead** [comment]
Thanks, I updated searchkick to 1.3 and the problem seems to be fixed.
