### ISSUE TITLE
Partial searches on array of strings not working

### ISSUE THREAD

**Issue by danielschwartz** [ankane/searchkick#678]
Hi,

Imagine a `User` class like this:

``` ruby
class User < ActiveRecord::Base
    searchkick match: :word_middle, searchable: [:email, :name, :usernames]

    ...some class internals

    def search_data
        {
            id: self.id,
            email: self.email,
            name: self.name,
            usernames: permissions.map(&:username)
        }
    end
end
```

If a user has a username `"danielschwartz"` in that array, then searching for the exact username returns no results. If you search with just `"d"` then it works, but as the query string gets more complete, I lose the result at some point.

**Comment by danielschwartz** [comment]
I've fixed this. It was some combination of searchkick options that didn't work well together. Would be awesome to get some descriptions of all the options, how they interact, and what things are necessary to search in specific ways (e.g. you need to do `word_middle: [:field1, :field2]` to be able to do `:word_middle` searches. It's not enough to have `match: :word_middle`. 

Anyways, yeah, just some understanding on how the options API works would be awesome.

**Comment by chamnap** [comment]
@danielschwartz, Can you show me your code? I can't get it working.

```
> Business.search('Rub', fields: [ { technologies: :word_start }]).count
> 0
```

**Comment by chamnap** [comment]
@ankane, Can you help me on this issue please? Does `searchkick` supports on doing partial search on array of string fields? As I tested many times, it doesn't work at all.

**Comment by dklisiaris** [comment]
I had the same issue with partial searches in array of strings, but it turned out that I had forgot some options.
This code worked for me:

```
  # In model
  searchkick match: :word_start,
  searchable: [:search_array],
  word_start: [:search_array]

  def search_data
  {
    search_array: search_array
  }
  end

  # In controller
  Model.search 'some keyphrase'

```

**Comment by ankane** [comment]
Thanks for the assist @dklisiaris :thumbsup:
