### ISSUE TITLE
Rspec _bulk POST call test fails

### ISSUE THREAD

**Issue by jhblacklock** [ankane/searchkick#681]
*elasticsearch (1.0.17)*
*searchkick (1.3.0)*

I have been using searchkick for a while and loving it.  Thanks!  Recently my tests have failed when creating a new object via factory girl.

```
user = FactoryGirl.create(:user)
```

This results in an HTTP call to POST http://localhost:9200/_bulk called from searchkick_index, which was not previously there (or at the least not throwing an unknown external service POST).

I can ignore the request in VCR but was wondering if there is more appropriate workflow for this?

**Comment by jhblacklock** [comment]
Figured out my issue. It was a problem with my rspec syntax and not searchkick.

Thanks!

**Comment by fenec** [comment]
@jhblacklock can you specify what was the problem with your rspec syntax? I have the same issue right now

**Comment by danfrenette** [comment]
Ran into this issue myself. What I recommend is actually going to the section of the README that covers what you need to add to your spec helper, and make sure you're following it to the letter. If you're using factory girl, it might be worth taking a look at that too, but it doesn't cover all use cases.
