### ISSUE TITLE
How can I tell if the search limit was reached?

### ISSUE THREAD

**Issue by slead** [ankane/searchkick#682]
Say I've run the query `Product.search "apples", limit: 10`, which limits the number of results returned.

Is it possible to detect that the limit kicked in, and there were more than 10 results to return? Eg, is there a `thresholdReached` flag or similar?

Thanks

**Comment by ankane** [comment]
Hey @slead, check out the [Searchkick::Result](https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb) object. You can use `total_pages` to see if there's more than 1.
