### ISSUE TITLE
Partial word match

### ISSUE THREAD

**Issue by seemalakishore** [ankane/searchkick#683]
@ankane 
Currently am using elasticsearch service of AWS with searchkick 1.2.0 version for search and autocomplete of Skillset for my application.

I have been trying to match say, "AngularJS" if I start searching with partial word like "Angu" or match "Java" if I search for with "Ja". But the result would not come until I search for "Angula" to get "AngularJS" and similarly "Jav" to get "Java".

I have added word_start: [:name], word_middle: [:name] configurations but no luck.
I have also tried with suggestions, but I dint get any results.

**Comment by chenzeyu** [comment]
I encountered same issue here, say I have 'Singapore' in my DB, and I have to type until 'Singapo' to get Singapore.

I've also set ```word_start```

**Comment by chenzeyu** [comment]
@seemalakishore Got it. 

On Github page, the doc says: ```Product.search "back", fields: [:name], match: :word_start```

However on http://searchkick.org/, it says: ```Product.search "back", fields: [{name: :word_start}]```

The later one works.

**Comment by ankane** [comment]
Hey Chen, thanks following up. What version of Searchkick are you on?

**Comment by chenzeyu** [comment]
Hi ankane, I'm using searchkick 1.3.0 on Rails 5

**Comment by rmcsharry** [comment]
@ankane Am I correct that searchkick does not support partial matching? I don't mean mispellings or fuzziness (like being 1,2 characters away from a word).

I mean actual n-gram matching on word stems.

For example, if I have product table with name field.

Eg:

name: "matt black android phone"
name: "iphone in black"

Searching for 'phon' should return both products because it matches PARTIALLY to a word in both product names.

I think this [ES document page](https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html) explains it better if the above is not clear:

**Comment by rmcsharry** [comment]
It seems that using middel_word works as per this https://github.com/ankane/searchkick/issues/568

**Comment by ankane** [comment]
@seemalakishore, be sure to use `match: :word_start` in your search method as well.

@chenzeyu, either version should work with the latest version of Searchkick.

**Comment by andreasantarl** [comment]
Hi @ankane,

I'm trying to implement a partial text match with Searchkick 3.0.2 and Rails 5.1.4. I've added 
```
searchkick text_middle: [:cip_title]
```
 to my model, and my search method looks like this:   
```
 major_search = CipCode.search(
      search.titleize,
      fields: [{cip_title: :text_middle}],
      operator: 'or'
    )
```

but to no avail. Other ways of structuring my search method also fail, like 
```
    major_search = CipCode.search(
      search.titleize,
      fields: [:cip_title],
      operator: 'or',
      match: :text_middle
    )
```
 I don't get any search results even though it should return matches. For example, I search for 'bio' and 'biology' isn't returned in the results. Am I missing something, or is this feature no longer available in Searchkick 3+?

**Comment by ccoeder** [comment]
@andreasantarl I'm trying to do the same but I did not get a result 😞
