### ISSUE TITLE
Update of a single field of a record

### ISSUE THREAD

**Issue by pedrosfdcarneiro** [ankane/searchkick#685]
Hi everyone :smiley:

I would like to know if it's possible to update just a field of a record instead of reindex the whole record (running `search_data`).

This would important to me because reindexing a record is a slow task as I generate a lot of fields for the record and my goal was updating just a single one.

Thanks in advance.

**Comment by ankane** [comment]
Not currently. One approach is #495. This reduces data sent over the wire, but it sounds like you're looking for an approach that doesn't call `search_data`.  I'm open to suggestions.

**Comment by ankane** [comment]
Searchkick now supports partial reindexing 🎉  See [reference](https://github.com/ankane/searchkick#reference) section.
