### ISSUE TITLE
undefined method `prepend' for Searchkick::Query:Class

### ISSUE THREAD

**Issue by vetalpaprotsky** [ankane/searchkick#686]
After adding gem searchkick to my Gemfile I get this error when I try to delpoy the project:

    /home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/faraday-0.8.9/lib/faraday/request/multipart.rb:4 warning: already initialized constant DEFAULT_BOUNDARY
    DEBUG[eff60d47] 	rake aborted!
    DEBUG[eff60d47] 	NoMethodError: undefined method `prepend' for Searchkick::Query:Class
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/searchkick-1.3.0/lib/searchkick/logging.rb:179:in `(root)'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/searchkick-1.3.0/lib/searchkick.rb:1:in `(root)'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/shared/bundle/jruby/1.9/gems/searchkick-1.3.0/lib/searchkick.rb:12:in `(root)'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/releases/20160622173816/config/application.rb:9:in `(root)'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/releases/20160622173816/Rakefile:1:in `(root)'
    DEBUG[eff60d47] 	/home/deploy/apps/razborki/releases/20160622173816/Rakefile:5:in `(root)'
    DEBUG[eff60d47] 	(See full trace by running task with --trace)
How can I fix it?
searchkick 1.3.0
ruby-2.1.0
rails-4.1.8

**Comment by ankane** [comment]
You'll need to use a Ruby version that supports `Module#prepend` - MRI 2.0+ or JRuby 9000+.

**Comment by devopsdevon** [comment]
Is this issue specific to what the OP was trying to do, or did searchkick start requiring ruby 2.0+ at some point? If so, at what gem revision?

SearchKick does not appear to have a minimum version of Ruby specified, but I wanted to check if 2.0+ is required before posting my own issue using 1.3.1 in a JRuby environment. Thanks!
