### ISSUE TITLE
Order by integer not working correctly

### ISSUE THREAD

**Issue by Radiet** [ankane/searchkick#688]
I have tried to order data by price (price with integer data type)
But the results is 990000, 990000, 9800000, 97200000

Here is my code:
`search( '*', load: false, limit: 30, order: {'price' => 'desc'} )`

**Comment by ankane** [comment]
What does `YourModel.searchkick_index.mapping` return?

**Comment by Radiet** [comment]
The return is
"price" => {"type" => "string", "index" => "not_analyzed", "fields" => {"analyzer" => {"type" => "string"}, " word_start "=> {" type "=>" string "," analyzer "=>" searchkick_word_start_index "}}}

**Comment by ankane** [comment]
It looks like your price field is indexed as a string instead of an integer.

**Comment by Radiet** [comment]
Ohh, how to make it indexed as integer :) ?

**Comment by Radiet** [comment]
Solved,  thanks ankane ^_^
I add this code, and now it's work perfectly
```
searchkick, merge_mappings: true, mappings: {
      myModel: {
        properties: {
          price: {type: "integer"}
        }
      }
    }
```

**Comment by AhmedAliIbrahim** [comment]
My mapping is float and i get incorrect order of results !! any help ?
