### ISSUE TITLE
Multiple Aggs with options

### ISSUE THREAD

**Issue by paulholladay** [ankane/searchkick#689]
In the documentation there a two ways/styles of requesting Aggs that are mentioned.

For simple (multiple) Agg requests:

products = Product.search "chuck taylor", aggs: [:product_type, :gender, :brand]

And for Agg requests with options:

Product.search "wingtips", aggs: {size: {where: {color: "brandy"}}}

My question is - how do we go about declaring multiple aggs with options? We've tried various combinations of the two without success...

For example - this doesn't work...

products = Product.search "chuck taylor", aggs: [:product_type, {size: {where: {color: "brandy"}}}]

Is it a ruby formatting problem? or is it a limitation in the gem?

**Comment by ankane** [comment]
@paulholladay you can do:

```ruby
products = Product.search "chuck taylor", aggs: {product_type: {}, size: {where: {color: "brandy"}}}
```
