### ISSUE TITLE
Searchkick::ImportError - ClusterBlockException

### ISSUE THREAD

**Issue by Macj** [ankane/searchkick#693]
Hi there!
I have Elasticsearch instance on Amazon AWS.
And rails app with Searchkick.
Recently I had an error like this.
Searchkick::ImportError - ClusterBlockException
While try to make reindex for Model with search kick included.

What this error about?

**Comment by ankane** [comment]
Hi Max, I haven't personally come across this error before.  I'd see what Google can find.
