### ISSUE TITLE
max_bytes_length_exceeded_exception

### ISSUE THREAD

**Issue by mbajur** [ankane/searchkick#696]
Hello everyone! 
I'm trying to implement partial matches in my searchkick-enabled app and i've encountered a blocker. I've added `word_start: [:transcript] and `match: :word_start` and when i'm trying to reindex my records, searchkick throws:

```
{"count":5,"exception":["Searchkick::ImportError","{\"type\"=\u003e\"illegal_argument_exception\", \"reason\"=\u003e\"Document contains at least one immense term in field=\\\"transcript\\\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[82, 69, 83, 84, 65, 85, 82, 65, 67, 74, 65, 32, 80, 79, 68, 32, 78, 79, 82, 69, 78, 65, 77, 73, 32, 87, 69, 71, 69, 84]...', original message: bytes can be at most 32766 in length; got 49060\", \"caused_by\"=\u003e{\"type\"=\u003e\"max_bytes_length_exceeded_exception\", \"reason\"=\u003e\"bytes can be at most 32766 in length; got 49060\"}}"]}
Searchkick::ImportError: {"type"=>"illegal_argument_exception", "reason"=>"Document contains at least one immense term in field=\"transcript\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[82, 69, 83, 84, 65, 85, 82, 65, 67, 74, 65, 32, 80, 79, 68, 32, 78, 79, 82, 69, 78, 65, 77, 73, 32, 87, 69, 71, 69, 84]...', original message: bytes can be at most 32766 in length; got 49060", "caused_by"=>{"type"=>"max_bytes_length_exceeded_exception", "reason"=>"bytes can be at most 32766 in length; got 49060"}}
```

I've googled a bit about it and found that thread: https://discuss.elastic.co/t/utf8-encoding-is-longer-than-the-max-length-32766/816

It seems that, to fix that issue, i need to somehow set `ignore_above: 256`. Which is allready set as far as i can see: https://github.com/ankane/searchkick/blob/668b7948df1d84548690633968de0174c539fc9b/lib/searchkick/index.rb#L513

Do you guys have any idea on what can be happening in here? I can say, if that's helpfull in any way, that the `transcript` table contains a text extracted from PDF documents. So there might be something undesired in it i have no idea about.

Anyway - thanks for maintaining searchkick and all the other great gems you're making, they are all amazing and super exciting. Kepp up the good work! :)

**Comment by ankane** [comment]
Hey @mbajur, thanks for the detailed report.  Looks like `ignore_above` was only being set on the dynamic mapping.  Should be fixed on master.

**Comment by mbajur** [comment]
Ok it seems it's fixed. Thanks!
