### ISSUE TITLE
Pagination and highlighting

### ISSUE THREAD

**Issue by mbajur** [ankane/searchkick#697]
I'm trying to implement highlighting feature for **kaminari-paginated** results returned by searchkick. I'm not sure if i'm getting it right but it seems that it's not possible to paginate highlighted results (`with_details()`) in cause of the way the format in which data is returned - as an array of array of results and the details hash.

```
undefined method `page' for #<Array:0x007ff4202f9bc8>
```

Apart from the fact that it's not working for me - i would love to find a solution (even using monkey patching) to return those highlighted data in a way, that would not involve rewriting half of my application. So, instead of returning an array, it would be super great to make it just like pg_search guys are doing it - to attach a `details` virtual attribtue to each object in active_record relation collection. This way, searchkick could became even more seamless during it's integration. Let's take a look how it works in pg_search:

```
first_match = Person.search("Alberta").with_pg_search_highlight.first
first_match.pg_search_highlight # => "Born in rural <b>Alberta</b>, where the buffalo roam."
```

Applying `with_pg_search_highlight` scope adds a `pg_search_highlight` attribtue to each record.

It obviously can't replace the current approach cause it's totally not backwards-compatible but what about passing some additional param to `with_details` or making a separate method for that? I would love to try creating it and i've even tried but failed, i'm affraid i lack some knowledge (and skills) about how searchkick works.

Current approach is tricky for me because my whole app assumes @results is always a classic ActiveRecord::Collection object, no matter if it's happening in api or on frontend controllers. The fact that searchkick returns array of array and details complicates everything and implementing it would involve writing a lot of ifs and would end up with a huge mess in general. Totally not worth it.

Thanks in advance for any clues or hotfixes!

**Comment by ankane** [comment]
One option is to add a method like `searchkick_highlights` to all the objects returned whenever the `highlight` option is passed.  Then you could do:

```ruby
Person.search("Alberta").each do |person|
  p person.searchkick_highlights.name
end
```

The best place to do this would probably be in `Searchkick::Results`.  Does that make sense?

**Comment by mbajur** [comment]
I've made that quick n' dirty monkeypatch and it seems it's working fine. Here is it, in case anyone needs it:

```
module Searchkick
  class Results
    def with_nested_details
      records.each do |r|
        r.transcript_highlights = hits.select { |h| h['_id'] == r.id.to_s }
                                      .map { |h| h['highlight'] }
                                      .map { |k| k.values }
                                      .flatten
      end

      @@self = self

      def records.total_count
        @@self.total_count
      end

      def records.current_page
        @@self.options[:page]
      end

      def records.prev_page
        current_page > 1 ? current_page - 1 : nil
      end

      def records.next_page
        current_page < total_pages ? current_page + 1 : nil
      end

      def records.total_pages
        (total_count.to_f / @@self.options[:per_page]).ceil
      end

      records
    end
  end
end
```

Also, following lines needs to be added to the model:

```
attr_writer :transcript_highlights
def transcript_highlights
  @transcript_highlights || []
end
```

And it can be used like that:

```
Model.search('query').with_nested_details do |r|
  puts r.transcript_highlights
end
```

However, it turned out i need to use "advanced querying" so that whole solution is not usefull for me. 

PS. That code above is probably pretty horrible, any sugestions much apreciated

**Comment by ankane** [comment]
Searchkick now has a `search_highlights` method (see readme) 🎉
