### ISSUE TITLE
Searchkick:reindex

### ISSUE THREAD

**Issue by tballarin** [ankane/searchkick#698]
Hi all,
I have a problem since 2 days when I want to reindex my data 
I get an **"ArgumentError: Malformed version number string 5.0.0-alpha1"** each time I want to reindex
I make the test directly on my controller's and on console

 My searchkick version => 1.3.0

Thanks in advance

**Comment by ankane** [comment]
What version of Ruby are you on?

**Comment by tballarin** [comment]
Actually => ruby 2.0.0p481

I just now downgrade the Gem to 1.2.1 and for moment, I can remake my index

-- 
Thomas Ballarin

Le 10 juillet 2016 à 06:21:27, Andrew Kane (notifications@github.com) a écrit:

What version of Ruby are you on?

**Comment by ankane** [comment]
Thanks for reporting @tballarin. Should be fixed in the latest release.

**Comment by natanio** [comment]
I am having this same issue, on the same ruby and gem versions. What would you suggest?

**Comment by ankane** [comment]
Try upgrading to Searchkick 2.

**Comment by natanio** [comment]
Ah, just noticed the release. Thanks! Got it.
