### ISSUE TITLE
Getting N+1 Query detected

### ISSUE THREAD

**Issue by Xosmond** [ankane/searchkick#699]
The result that i get is used to get another object information, but i can't make includes on an array.

    objective  = Model.search "*" 

Getting N+1 Query detected on the view because this:

    objective.each do |ob|
        ob.another_model_object.name
    end

I wanted to make an include but the results are an array, not an active record object
Is there any solution?

Thanks

**Comment by ankane** [comment]
Searchkick has an `include` option for this.

```ruby
Product.search "milk", include: [:brand, :stores]
```

**Comment by Xosmond** [comment]
Oh great, thanks, we have to create a wiki, this project is big.
