### ISSUE TITLE
Feature Request: Eager loading for multiple models

### ISSUE THREAD

**Issue by reidab** [ankane/searchkick#701]
I'm searching across multiple multiple models and would like to eager-load associations. The current implementation fails when it tries to send `includes` to the wrong model class.

The current implementation of Searchkick's `include` option takes an array of associations to eager load (`Searchkick.search "milk", include: [:brand, :stores]`). What would you say to a PR to optionally accept a hash, like so?

```
Searchkick.search "milk", index_name: [Product, Category], include: {Product => [:brand, :stores]}
```

**Comment by ankane** [comment]
Hey @reidab, I'm open to the idea. I think we'd want another option to accomplish this to keep backward compatibility and not confuse people.

**Comment by tracyloisel** [comment]
@ankane I can help for this feature. I see a way to succeed :
for each model in index_name, build a search query with option `execute: false`, then call Searchkick.multi_search

After reading results.rb#L186 I suggest a new option could be "includes_at", like that

`Search.search "milk", index_name: [Product, Category], includes_at: {product: [:brand,:stores], }

all_search_query = index_name.collect do |domain|
domain.search "milk", include: options[:includes_at].fetch(domain.to_sym), execute: false
end`

then like in https://github.com/ankane/searchkick#multi-search :
`Searchkick.multi_search(all_search_query)`

**Comment by ankane** [comment]
@tracyloisel Thanks for offering to help. You should be able to make the change at results.rb#L186 without the need for `multi_search`.

**Comment by oyeanuj** [comment]
@reidab @tracyloisel Curious, if a PR for this still on your radars?

**Comment by tracyloisel** [comment]
Yes @oyeanuj . Do you need that feature soon ?

**Comment by oyeanuj** [comment]
@tracyloisel yes, that would be amazing!

**Comment by twanies** [comment]
Any updates yet on the status of this pr?
