### ISSUE TITLE
Weird results when searching on an email field

### ISSUE THREAD

**Issue by jwoertink** [ankane/searchkick#706]
I have this model `Member` with an `email` field. This one particular record has an email address of `testmail19@email.com`. 

This doesn't work
```ruby
Member.search("TESTMAIL", per_page: 100).total_count #=> 0
```

This one does
```ruby
Member.search("TESTMAIL19", per_page: 100).total_count #=> 1
```

Here's my model

```ruby
class Member < ActiveRecord::Base
  searchkick({
    word_start: [:name, :email],
    merge_mappings: true,
    mappings: {
      member: {
        properties: {
          name: {type: "string" analyzer: "simple"},
          email: {type: "string" analyzer: "simple"}
        }
      }
    }
  })
end
```

Is there some sort of option where the query has to be a certain length to match or something?

**Comment by ankane** [comment]
If you don't specify a `fields` option, Searchkick will use Elasticsearch's `_all` field, which uses the default index analyzer.

Also, if you use a custom mapping, you'll most likely need to use [custom searching](https://github.com/ankane/searchkick#advanced-search) as well for things to work as expected.

My recommendation would be to remove the custom mapping and use:

```ruby
Member.search "TESTMAIL", fields: [:name, :email], match: :word_start
```

**Comment by jwoertink** [comment]
Just tried that example, and I get the same result 😕 

```ruby
class Member < ActiveRecord::Base
  searchkick
end

m = Member.find(1)
Member.searchkick_index.remove(m)
Member.searchkick_index.store(m)
Member.search("TESTMAIL", fields: [:name, :email], match: :word_start, per_page: 100).total_count #=> 0
Member.search("TESTMAIL19", fields: [:name, :email], match: :word_start, per_page: 100).total_count #=> 1
```

**Comment by ankane** [comment]
You still need `searchkick word_start: [:name, :email]` in your model.  Then, do a full reindex with `Member.reindex`.

**Comment by jwoertink** [comment]
hmm... yeah, still same result. I think I'll try and reproduce outside of my app to make sure it's not something weird going on there. Thanks for the help. I'll close this for now until I can get an exact error.
