### ISSUE TITLE
New feature: Cross fields search

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#707]
https://www.elastic.co/guide/en/elasticsearch/guide/current/_cross_fields_queries.html

**Comment by Schwad** [comment]
@ankane I see that @savayg has referenced this issue on some commits on a fork... Do you think that his changes on that fork would satisfy what you're looking to implement in this issue? :)

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
