### ISSUE TITLE
Heroku SearchBox Reindex issue

### ISSUE THREAD

**Issue by sqlninja** [ankane/searchkick#711]
It seems that using the SearchBox ElasticSearch Heroku Add-on with Searchkick doesn't like 
 `rake searchkick:reindex:all`

I am currently on the Micro plan which allows for 3 indices (which is how many I have), and 200 MB of storage (of which I'm using 5.5 MB)

If I call the reindex all rake task it dies with this output:
```
rake aborted!
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"generation_exception","reason":"reached maximum index count for current plan"}],"type":"generation_exception","reason":"reached maximum index count for current plan"},"status":500}
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-transport-2.0.0/lib/elasticsearch/transport/client.rb:128:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/app/vendor/bundle/ruby/2.3.0/gems/elasticsearch-api-2.0.0/lib/elasticsearch/api/actions/indices/create.rb:84:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/index.rb:11:in `create'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/index.rb:139:in `create_index'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/index.rb:165:in `reindex_scope'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/model.rb:53:in `searchkick_reindex'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/tasks.rb:26:in `block (4 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/tasks.rb:24:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/searchkick-1.3.3/lib/searchkick/tasks.rb:24:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => searchkick:reindex:all
```

The only work-around i have found thus far is to delete the indices from within the Searchbox admin then reindex.

I suspect there is an issue with the name of them, but I'm not sure...

**Comment by ankane** [comment]
Hey @sqlninja, do you have multiple models using Searchkick? Searchkick requires 2 indices per model to allow for zero-downtime reindexing.

**Comment by sqlninja** [comment]
So I have 3 models but I simply ran that rake task to create the indices...
How should I create additional indices?
Also if I don't want to pay for the extra indices, what is the recommendation for managing them?

**Comment by ankane** [comment]
You'll only be able to use one model on the free plan. If you want to use Searchkick for all three, you'll either need to host your own version of Elasticsearch or pay for a plan.

**Comment by sqlninja** [comment]
I'm not on a free plan; it allows for 3 indices now, which would be one per model...
As I mentioned in the OP, I'm using Searchbox.

You closed the issue with no resolution?

**Comment by ankane** [comment]
Searchkick uses 2 indices per model, so you'll need a server that supports 6 indices.  That's the resolution.

**Comment by sqlninja** [comment]
Thanks I guess!
