### ISSUE TITLE
Asynchronous bulk update with Searchkick

### ISSUE THREAD

**Issue by lbalceda** [ankane/searchkick#712]
I'm currently using searchkick in Ruby to set up async callbacks using ActiveJob, and was looking for a way to utilize the callbacks method with symbols :bulk and :async. I know it's possible to do both bulk and async separately but couldn't figure out how to do them together - is there a way to combine batched requests asynchronously?

**Comment by ankane** [comment]
@lbalceda Searchkick doesn't provide this ability. One way to accomplish this is to:

1. Disable search callbacks
2. Add an `after_commit` callback that inserts the item (either just the id or all of the `search_data`) into a Redis queue
3. Have a background process that constantly pulls items off the queue in batches and bulk indexes them

**Comment by lbalceda** [comment]
cool thanks, will try this out

**Comment by jdraths** [comment]
There were times where I wanted to bulk index when an association changes. I.E., the Author's name changes so I wanted to bulk index Books so that all the Author's books now include the Author's updated name. 

I ended up writing a Sidekiq worker to do this since the bulk import method `Book.searchkick_index.import(some_author.books)` is not asynchronous:
```ruby
class SearchWorker
  include Sidekiq::Worker

  def perform(parent_class, parent_id, target_class)
    # parent_class i.e., "Author"
	# target_class i.e., "Book"
	# desired result: parent_class.target_classes, i.e. Author.find(parent_id).books
	model = parent_class.classify.constantize # converts "Author" & "author" 
           # to Author (as a class)
	association = target_class.tableize # converts "Book" & "book" to "books" 
           # (as a string, use send to invoke the method) 
	model.find(parent_id.to_i).send(association).find_in_batches do |batch|
       target_class.classify.constantize.searchkick_index.import(batch)
# I.E. Book.searchkick_index.import(batch_of_books)
    end
  end
end
```

And then I use it like this:
```ruby
class Author < ActiveRecord::Base
  has_many :books

  after_commit :reindex_books

  def reindex_books
    SearchWorker.perform_async(self.class.name, self.id, "Book")
  end
end
```

**Comment by Xosmond** [comment]
For people who came here, I recommend to do the manual way, :async option on callbacks not worked well in my case.

**Comment by ankane** [comment]
Hey @Xosmond, can you explain why that is?
