### ISSUE TITLE
Multilingual search best practices

### ISSUE THREAD

**Issue by Midnighter** [ankane/searchkick#713]
I'm wondering if there are any best practices I should be aware of when it comes to search in a multilingual  application? What I'm envisioning at the moment goes something like this: I have an `Item` class which has descriptions in ten different languages.

``` ruby
class Item < ActiveRecord::Base
    searchkick
    has_many :descriptions
end

class Description < ActiveRecord::Base
    belongs_to :item
    belongs_to :language
end
```

The description has a field `title` and a longer text field, let's call it `full`. What I'm imagining right now is to generate a separate index for each language and use its own stemmer. I would then search over all indexes.

Is this a sound strategy? What do you prefer?

**Comment by ankane** [comment]
@Midnighter I haven't tried something like this, but maybe someone else can weigh in.

**Comment by cireficc** [comment]
I'll note that Elasticsearch seems to be smart enough to choose the correct stemmer when it indexes content, so you might not have to explicitly set the stemmer. For example, I have a `Film` model whose titles are in any of 8 languages; the `title` field is indexed, but the stemmer was never explicitly set. Search is accurate in all languages, including Japanese, Arabic, Chinese, and Russian, all of which have their own unique stemming issues. Elasticsearch just gets it right :+1:

**Comment by fredriksundstrom** [comment]
I’d love to verify that Elasticsearch does automatic stemming for me, but I’m not sure how. Is it possible to, i.e., get the stemmed searchstring to verify it? Sortof like this: http://9ol.es/porter_js_demo.html

Me, for example, are creating a Swedish page. I get one result locally with just Elasticsearch and another with Searchly/Searchbox via Heroku, no matter if I set the language to Swedish or not. So, would be glad to know if Searchly/Searchbox just does automatic stemming – or no swedish stemming at all, no matter the config. :)

**Comment by ankane** [comment]
Hey @fredriksundstrom, see the debugging queries section for how to check tokenization and stemming: https://github.com/ankane/searchkick#debugging-queries

**Comment by cireficc** [comment]
@ankane I looked through that section and tried some debugging on my own `Film` model to determine what stemmer was being chosen in my search queries, but no stemmer information was given in the output (just the *analyzer*).

I also looked through the Elasticsearch documentation for a specific CURL request that might provide that information, but I couldn't find anything useful. Is stemmer information even exposed in ES? I see that you can [override stemming rules](https://www.elastic.co/guide/en/elasticsearch/guide/current/controlling-stemming.html), but I haven't found anything relating to showing which stemmer is chosen when indexing or querying.

**Comment by ankane** [comment]
Cleaning up stale issues
