### ISSUE TITLE
Issue indexing has_and_belongs_to_many relationship

### ISSUE THREAD

**Issue by nrosella** [ankane/searchkick#714]
I'm wondering how I can go about adding a `has_and_belongs_to_many` search for my data. I already have searchkick working nicely in my Rails 5 app but when I try to index the data for :services and :sectors I get nothing.

It doesn't even seem like the `search_data` method gets called. Even if I put a pry binding in there nothing happens.

    class Event < ApplicationRecord
      searchkick text_start: [:title]

      has_many :attendances, dependent: :delete_all
      has_many :users, through: :attendances
      has_and_belongs_to_many :services
      has_and_belongs_to_many :sectors

      def search_data
        {
          title: title,
          sector_name: sectors.map(&:name),
          service_name: services.map(&:name)
        }
      end
    end

Any help would be great.

**Comment by marcamillion** [comment]
Why was this closed? @nrosella you found a solution that works? I am struggling with this too.

Can you share what worked for you please, if you got this working.

Thanks!

**Comment by ckhall** [comment]
ref: https://github.com/ankane/searchkick/issues/920
