### ISSUE TITLE
filtering AND within a field with a array

### ISSUE THREAD

**Issue by joostliketoast** [ankane/searchkick#715]
I am trying to filter items that have all the values that are specified in the array but it only does OR

`Item.search(@query, where: {has_many_object_ids: [0,1,2,9]})`

is there a way to do this? So that it only returns items that have all of the id's.

**Comment by ankane** [comment]
Try the `all` operator.

```ruby
Item.search(@query, where: {has_many_object_ids: {all: [0,1,2,9]}})
```

**Comment by joostliketoast** [comment]
@ankane awesome! worked like charm. Thanks for the help
