### ISSUE TITLE
Indexes with word fields fail to reindex since v1.1.0

### ISSUE THREAD

**Issue by jeroenj** [ankane/searchkick#716]
When upgrading searchkick from v1.0.3 to v1.1.0 it appears that the (explicit) word index is broken.

Given a simbple `Project` model with a `titles` string attribute:

```
class Project < ActiveRecord::Base
  searchkick word: [:title]
end
```

When `Project.reindex` gets called the following exception gets thrown: 

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer [searchkick_word_index] not found for field [word]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_default_]: analyzer [searchkick_word_index] not found for field [word]","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer [searchkick_word_index] not found for field [word]"}},"status":400}
```

When reverting back to v1.0.3 or earlier it works as expected. I've tried to dissect [what exactly has changed](https://github.com/ankane/searchkick/compare/v1.0.3...v1.1.0) but I couldn't exactly point my finger at it. I guess it must be related to the `Added word option` part but I'm not 100% sure

**Comment by ankane** [comment]
Hey @jeroenj, thanks for reporting. I've pushed a fix for the error. The only supported values for the `word` option for indexing are `true` and `false` at the moment, but I'm happy to accept a PR to allow it accept a list of fields like `word_start`, `word_middle`, etc.

**Comment by jeroenj** [comment]
Hi, thanks for the fix. I'll try it out tomorrow.

Wasn't `word: [:field]` supported before? We've been using it since v0.8 if I'm not mistaken.

**Comment by ankane** [comment]
The `word` option was added in `1.1.0`. Extra options don't throw errors, so it was a no-op before.

**Comment by jeroenj** [comment]
Woaw, didn't know that. 😅 

Apparantly we always assumed it worked that way. We're certainly going to look into that. I'd be happy to (try) to contribute the `word` option to accept a list of fields. :)

**Comment by ankane** [comment]
`word` is indexed for all fields by default, which is probably why it didn't make a difference. Searchkick 2.0 will use keyword arguments, so Ruby will throw an error for unrecognized options (breaking change).

**Comment by jeroenj** [comment]
That explains a lot. Thanks. :)
