### ISSUE TITLE
problem using custom fields

### ISSUE THREAD

**Issue by leonardoprg** [ankane/searchkick#719]
Hello guys,

I'm using searchkick on my project, and I have the follow situation,

```
class Report < ApplicationRecord
   # report has a title, summary and document
   searchkick, async: true

    def search_data
      { title: title, summary: summary, content: Yomu.new(document.file_name).text }
    end

end
```

When I run `Report.search('something')` it works well for `title` and `summary`, but it doesn't match any data from `content` string.

Checked the result from `Yomu.new(document.file_name).text` and it's a string  that contains all text from PDF.

any idea why search is ignoring `content`?

Thanks

**Comment by ankane** [comment]
Hi @leonardoprg, try reindexing to make sure the latest search data is in the index.

On a separate note, `async: true` is not a valid option.

**Comment by leonardoprg** [comment]
@ankane 

yes, I tried reindex, the weird part is, I reindex that and try to search for a new value, doesn't works, 
try to search for older one, works.

for example:

`{ title: 'testing' }`
`.search(`test`)` returns correct `testing`

change to  `{ title: 'example' }`
`.search(`exam`)` returns `nothing`
`.search(`test`)` returns `testing`

using `async` or not, 
could be some problem with index (size of the string?) ?


yes sorry xD it's `callbacks: :async`

**Comment by ankane** [comment]
A few things:

1. It sounds like the data is not being reindexed. Be sure your background workers are running if you use `callbacks: :async`.
2. Partial matching is not enabled by default (but sometimes works because of stemming). A better test to see if reindexing is working would be to search for an entire word in the title.
