### ISSUE TITLE
Support for GeoHash grid aggregation

### ISSUE THREAD

**Issue by hyfen** [ankane/searchkick#720]
ElasticSearch supports an aggregation that groups results into geographic buckets. 

Official docs for it here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html; more information about geohashes here: https://en.wikipedia.org/wiki/Geohash

Should just be a matter of adding another section to `lib/searchkick/query.rb` and I think the results will get handled by aggregations() in `lib/searchkick/results.rb` automatically?

**Comment by hyfen** [comment]
(might take a stab at this myself in a few days)

**Comment by will-r** [comment]
This is now very easy to implement with `body_options`:

```
      aggregations = {
        locations: {
          geohash_grid: {
            field: "location",
            precision: 2
          }
        }
...
      @page_views = PageView.search('*', where: criteria, body_options: {aggs: aggregations}, limit: 1, load: false)
      location_data = @page_views.aggs['locations']['buckets']
```

which gives a nice compact array of geohashes and document counts.

The main problem with this approach is that we can't use the searchkick interface for other aggregations, so everything has to be spelled out in full. 

@ankane it would be easy to add a searchkick interface for the aggregation, and only a little harder to test. Would you consider a PR?

**Comment by ankane** [comment]
As @will-r mentioned, `body_options` is the preferred way to do this.
