### ISSUE TITLE
Aws Elasticsearch transport forbidden HELP please 

### ISSUE THREAD

**Issue by jcward10** [ankane/searchkick#721]
I used the initializer from the readme. But I get the error below when trying to reindex. Maybe I'm setting up elasticsearch instance incorrectly. I added my iam arn to the access policy. I have verified that my aws credentials allow me to access aws. I have redacted the to strings. 

    elasticsearch (1.0.15)
      elasticsearch-api (= 1.0.15)
      elasticsearch-transport (= 1.0.15)
    elasticsearch-api (1.0.15)
      multi_json
    elasticsearch-transport (1.0.15)
      faraday
      multi_json
    faraday_middleware-aws-signers-v4 (0.1.5)
      aws-sdk (~> 2.1)
      faraday (~> 0.9)

Anyone have any success with setting up searchkick with aws ES? Please comment with any info to set it up. 

..ib/elasticsearch/transport/transport/base.rb:146:in `__raise_transport_error': [403] {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been<elastic search domain string> The String-to-Sign should have been<shoulda been string> } (Elasticsearch::Transport::Transport::Errors::Forbidden)

**Comment by jcward10** [comment]
WOW you can close this ... I had a `/` at the end of my ELASTICSEARCH_URL and that caused it to break. You can close this issue but it's good to document for other noobs

**Comment by ankane** [comment]
Glad you figured it out @jcward10.

**Comment by nrowegt** [comment]
@jcward10 I just ran into the same, thanks for the solution.

**Comment by vishaltps** [comment]
Bro, you just save my whole day :+1:

**Comment by basicBrogrammer** [comment]
@vishaltps you might have to return the favor when i upgrade to v3 ;)

**Comment by vishaltps** [comment]
@basicBrogrammer Yes sure bro. any time :)
