### ISSUE TITLE
Avoiding IllegalArgumentException where utf > 32766

### ISSUE THREAD

**Issue by mrjlynch** [ankane/searchkick#728]
Solutions for the `IllegalArgumentException` where text is longer than 32766 characters is discussed on [SO](http://stackoverflow.com/questions/24019868/utf8-encoding-is-longer-than-the-max-length-32766). 

One such [solution](http://stackoverflow.com/questions/24019868/utf8-encoding-is-longer-than-the-max-length-32766#answer-30522942) provides three options:
- set "index": "no"
- set "index": "analyze"
- set "index": "not_analyzed" and "ignore_above": 256

How can I set this using searchkick? Is the following correct?

``` ruby
searchkick mappings: {
    product: {
      properties: {
        name: {type: "string", index: "analzye", ignore_above: 256}
      }
    }
  }
```

**Comment by ankane** [comment]
The latest version of Searchkick should set this automatically if you're on Elasticsearch 2.2 or above. You may need to reindex to update the mapping if upgrading from an earlier version of either project.

https://github.com/ankane/searchkick/blob/master/lib/searchkick/index.rb#L551

**Comment by mrjlynch** [comment]
Thanks @ankane, when you say Searchkick sets this automatically, do you mean that default behaviour permits insertion where UTF > 32766?

**Comment by ankane** [comment]
It uses the `ignore_above` option for it.

**Comment by mrjlynch** [comment]
I am using `2.2.1` and I am still getting this error: 

``` ruby
Searchkick::ImportError - {"type"=>"illegal_argument_exception", "reason"=>"Document contains at least one immense term in field=\"html\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[60, 100, 105, 118, 62, 68, 105, 97, 103, 110, 111, 115, 105, 115, 32, 111, 102, 32, 99, 101, 108, 105, 97, 99, 32, 100, 105, 115, 101, 97]...', original message: bytes can be at most 32766 in length; got 47021", "caused_by"=>{"type"=>"max_bytes_length_exceeded_exception", "reason"=>"bytes can be at most 32766 in length; got 47021"}}
```

Do I need to set anything anything else to avoid this error?

**Comment by mrjlynch** [comment]
My error, I forgot to `reindex` my dad

**Comment by mrjlynch** [comment]
Is there a way to customize the `ignore_above` setting?

256 is quite short and is no where close to 32766

**Comment by ankane** [comment]
Not currently.

**Comment by mrjlynch** [comment]
Any chance we could keep this open? I plan to attend to this in the coming weeks with a pull request? Cheers

**Comment by ankane** [comment]
Hey @mrjlynch, you can just create a PR for it.
