### ISSUE TITLE
Standard searching with Types and Mappings

### ISSUE THREAD

**Issue by MrHubble** [ankane/searchkick#729]
I'm wondering whether it's bad practice to create an index for each model as per:

> It's actually quite common (unfortunately) for many Elasticsearch clients to adopt an index per model paradigm as the default for data organization. Sharding this way can be a premature optimization unless your scaling trajectory is well understood. In practice, small sets of data probably won't benefit from any kind of data partitioning. It’s perfectly reasonable to treat an index as analogous to, say, a Postgres database.
> Elasticsearch even supports this kind of internal partitioning with their index “types” feature.
> https://docs.bonsai.io/docs/reducing-shard-usage
> 
> ES makes it very easy to create a lot of indices and lots and lots of shards, but it’s important to understand that each index and shard comes at a cost. If you have too many indices or shards, the management load alone can degrade your ES cluster performance, potentially to the point of making it unusable.
> https://www.loggly.com/blog/nine-tips-configuring-elasticsearch-for-high-performance/
> 
> There is a limit to how many indexes Elasticsearch can cope with. Every shard of every index is a separate Lucene index, which in turn comprises several files. A process cannot have an unlimited number of open files. Also, every shard has its associated control structures in memory. So, while we will let you make as many indexes as you want, there are limiting factors.
> https://www.elastic.co/cloud/as-a-service/pricing

For the reasons above I'm thinking of using `types` rather than one index per model as I am currently doing. The readme states:

> Note: If you use a custom mapping, you'll need to use custom searching as well.

I think the default searching that searchkick offers is great and would enjoy being able to continue to use that rather than custom searching. Would it be possible to implement standard searching with mappings? If yes, where would I look to try and implement? Thanks.

**Comment by ankane** [comment]
Hey @MrHubble, thanks for doing this research. Comparing an index to a Postgres database is unfortunately a flawed comparison. [This article from Elastic](https://www.elastic.co/blog/index-vs-type) outlines the difference well, as types have significant limitations. To summarize:

- Fields need to be consistent across types
- Fields that exist in one type will also consume resources for documents of types where this field does not exist
- Scores use index-wide statistics, so scores of documents in one type can be impacted by documents from other types

Searchkick follows the pattern advocated in the "Which one should I use?" section. It says "Do your documents have similar mappings? If no, use different indices."

**Comment by MrHubble** [comment]
@ankane thanks for taking the time to reply and thanks for the fantastic gem.

The linked article raises some more questions:

**One big index**
>a single large index is more efficient than several small indices: the fixed cost of the Lucene index is better amortized across many documents.

Do you think this suggests that we may be better off using the same index for all of our models? ie 
````rb
class Model1 < ActiveRecord::Base
  searchkick index_name: "one_large_index"
end

class Model2 < ActiveRecord::Base
  searchkick index_name: "one_large_index"
end
````

Would we still be able to use `reindex` on models with one big index?

**One shard per index**
>creating indices that have fewer shards. For instance, instead of folding 5 types into the same index, you could create 5 indices with 1 primary shard each.

I see that searchkick already provides the ability to set the number of shards for an index (ie `searchkick settings: {number_of_shards: 3}`), but I have read that replica shards are also important. If I were to set `number_of_shards: 2`, would one of these shards automatically be created as a replica? If not, is there anyone to do this with searchkick?

**Standard search for custom mappings**
I assume when the article refers to documents with the same mappings then a scenario like this would be suitable:
````rb
class Model1 < ActiveRecord::Base
  def search_data
    {
      cost: cost,
      qty: qty,
      name: name
    }
  end
end

class Model2 < ActiveRecord::Base
  def search_data
    {
      cost: cost,
      qty: qty,
      name: name
    }
  end
end
````

If I have this scenario, would it be possibly to modify the code to use the default searching provided by searchkick or would custom searching be the only possible option?

I ask all of these questions as a number of the hosted elasticsearch solutions (ie Bonsai, SearchBox, etc) have limitations on the number of shards and indices. For example, the Bonsai 50USD a month plan has a restriction of 20 shards.

I originally followed the suggested blog post for multitenancy and had one index per model/tenant combination but this can quickly result in a large number of indices and can become very expensive.

**Comment by ankane** [comment]
I've tried to address your questions below.

1. You won't be able to use `reindex` if two models share the same index (Searchkick just isn't designed for this)
2. You can use `settings: {number_of_replicas: 1}` to control the replicas.
3. You can use the default searching if you're able to replicate Searchkick's mapping functionality with that setup.
