### ISSUE TITLE
distance from one point to another

### ISSUE THREAD

**Issue by gotar** [ankane/searchkick#73]
I have more a question then problem, i try to get distance from given point to another

For example current user location is latX1, latY1, product latX2, latY2, how using searchkick easy got those value is Model.search results? I know Elastic can do that:

http://stackoverflow.com/questions/9295118/return-distance-in-elasticsearch-results

**Comment by jamsi** [comment]
@ankane As this was awhile ago, does searchkick support script_fields?

**Comment by vsingh-cts** [comment]
@ankane  Any update regarding script_fields?. I have a similar problem to get the distance in result set. Thanks.

**Comment by kvivek1115** [comment]
@ankane Any update regarding script_fields?. I have a similar problem to get the distance in result set. Thanks.

**Comment by Theopaps** [comment]
Did anybody figure this one out? I want to show the distance in results but don't know how.
