### ISSUE TITLE
Directional Synonyms

### ISSUE THREAD

**Issue by MK-42** [ankane/searchkick#731]
according to [Elasticsearch: The Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/synonym-formats.html) it is possible to define directional synonyms that are only expanded in one direction.

Is it possible to define such synonyms with searchkick? If yes, how to do that?

I looked into the indexing-code if searchkick and found

```
settings[:analysis][:filter][:searchkick_synonym] = {
   type: "synonym",
   synonyms: synonyms.select { |s| s.size > 1 }.map { |s| s.join(",") }
}
```

what in my understanding is the part that creates the synonym-option for elasticsearch. I found no other references to synonym creation in the code.

Would you like to see the `=>` syntax added to searchkick? If yes I could try to integrate that.

Edit:
as a hotfix, I just removed the `select { |s| s.size > 1 }` and passed the full string "foo => bar,baz" into searchkick

**Comment by ankane** [comment]
@MK-42 I'm happy to accept a PR that allows you to pass an array of strings to `synomyms`.

**Comment by MK-42** [comment]
I just found your
```
# TODO use a snowball stemmer on synonyms when creating the token filter
```
what is actually also something i would need.
I tried stemming with [ruby-stemmer](https://github.com/aurelian/ruby-stemmer), but that gave different stemmings than elasticsearch. Is there any documentation on the stemmer used by elasticsearch?
