### ISSUE TITLE
"or" operator when searching for exact matches

### ISSUE THREAD

**Issue by rohithnp** [ankane/searchkick#732]
`Post.search("something other", fields: [{tag: :exact}], operator: "or"`)

This does not seem to return posts that have something or other in their respective tag field. Is this functionality not expected to work? 

Thanks

**Comment by ankane** [comment]
Hey @rohithnp, the `or` operator won't affect exact matches - the field must match the search term exactly.

**Comment by rohithnp** [comment]
Thanks for the reply. Is this a limitation from Elastic Search or just not something yet implemented?

**Comment by ankane** [comment]
Elasticsearch can do just about anything, but I don't there's an easy way to make this work in Searchkick without significantly complexity.

**Comment by ankane** [comment]
Cleaning up issues
