### ISSUE TITLE
How to do Conditional wheres 

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#734]
How to achieve something like this:

    Contact.search "*" do 
        where: { user_id: params[:user_id] } if params[:user_id].present?
        where: { property_id: Property.where(name: params[:name]).last.id } if params[:name].present?
    end

**Comment by feliperaul** [comment]
One solution I found was to create the where hash beforehand, something like this:

    where_query = {}
    
    where_query[:attribute] = value if params[:attribute].present?
    where_query[:attribute2] = value2 if params[:attribute2].present?
    
    Contact.search "*", where: where_query

It works, I just don't know if this is the recommended approach.

**Comment by ankane** [comment]
@feliperaul That's a solid solution. If the attribute names match the params, you can also do:

```ruby
Contact.search "*", where: params.slice(:attribute1, :attribute2)
```
