### ISSUE TITLE
uninitialized constant Searchkick::Index::Delayed

### ISSUE THREAD

**Issue by mindtonic** [ankane/searchkick#738]
Hello,

Thank you for all of your excellent work on this fantastic gem. It has been incredibly useful for our project.

We are currently upgrading to Rails 5. The specs on our models that employ asynchronous index updates using `searchkick callbacks: :async` are now failing with the error `uninitialized constant Searchkick::Index::Delayed`. It seems as if Searchkick is looking for DelayedJob directly (https://github.com/ankane/searchkick/blob/master/lib/searchkick/index.rb#L99), rather than using ActiveJob. We are using Sidekiq for our background processing.

I was just curious if you had seen this before. We definitely would like to use asynchronous indexing, but don't want to have to install and run DelayedJob just for Searchkick.

Thank you in advance for your time!

```
NameError:
  uninitialized constant Searchkick::Index::Delayed
# [...]/gems/searchkick-1.3.4/lib/searchkick/index.rb:99:in `reindex_record_async'
# [...]/gems/searchkick-1.3.4/lib/searchkick/model.rb:88:in `reindex_async'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:232:in `call'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:232:in `block in conditional'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `block in call'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `each'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
# [...]/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
# [...]/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:354:in `committed!'
```

**Comment by ankane** [comment]
Hey @mindtonic, seems like a load order issue if ActiveJob is installed (seems to not be detecting it). I've added better hooks that should fix this. I'll be pushing out a new release later tonight, or you can give master a shot now.
