### ISSUE TITLE
Facets for HasMany Associations

### ISSUE THREAD

**Issue by nsoufr** [ankane/searchkick#74]
Hey guys,

i have a project model:

``` ruby
  Project < ActiveRecord::Base
     searchkick

     has_many :categories_has_projects
     has_many :categories, through: :categories_has_projects

 end
```

and category model:

``` ruby
  Category < ActiveRecord::Base

     has_many :categories_has_projects
     has_many :projects, through: :categories_has_projects

 end

```

how can i search and declare facets for categories through Project model?

for exemple:

``` ruby
  search = Project.search 'something', 
    facets: [:categories_title] #pseudo code

  # in order to have this in my view
  # sidebar
  # category_A (3) 
  # category_B (5)
  # category_C (3)


```

**Comment by khacluan** [comment]
thanks :+1:

**Comment by cmalpeli** [comment]
@ankane what would the syntax look like if I wanted to index both the name and ID columns of an associated model?

**Comment by ankane** [comment]
@cmalpeli You should be able to use dot notation, like `categories.id`, if you index as:

```ruby
def search_data
  {
    categories: categories.as_json(only: [:id, :name])
  }
end
```

This is relatively untested, but happy to accept a PR if further support is needed.

**Comment by cmalpeli** [comment]
Thanks @ankane that seems to work! 

Follow up, what would be the proper syntax for setting up both aggregations and where clauses matching only the category name now that it's in a nested structure?

```
"categories": [
                  {
                     "id": 749,
                     "name": "Agile"
                  },
                  {
                     "id": 15,
                     "name": "DevOps"
                  }]```

**Comment by ankane** [comment]
You should be able to use dot notation for those as well.

**Comment by viphat** [comment]
I'm wondering if nested object was updated, such as category's name was changed, will searchkick update the data of Project in elasticsearch too?

**Comment by ankane** [comment]
Searchkick won't know unless you tell it. See https://github.com/ankane/searchkick#associations
