### ISSUE TITLE
Autocomplete section of README.md is outdated

### ISSUE THREAD

**Issue by mimikadze** [ankane/searchkick#740]
Seems that typeahead.js version moved far ahead and they've changed syntax and set of params.

Current solution they provided and I can make it work looks like this:

```
<input class="typeahead" type="text" placeholder="Choose the book">

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>

<script>
  var books = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('title'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: '/books/autocomplete?query=%QUERY',
      wildcard: '%QUERY'
    }
  });
  $('.typeahead').typeahead(null, {
    source: books
  });
</script>
```

Works for typeahead.js 0.11.1 which is latest for the moment.

I'm sure it makes sense cause my colleagues stuck with this issue recently. I can make a PR if you consider this useful.

**Comment by ankane** [comment]
Thanks for reporting @mimikadze, a PR would be great.

**Comment by natedrouin** [comment]
This is correct, very outdated.
