### ISSUE TITLE
Job adapter not found

### ISSUE THREAD

**Issue by nicolasmlv** [ankane/searchkick#742]
Hello,

I use `searchkick callbacks: :async`

<details> 
  <summary>`Searchkick::Error: Job adapter not found` appeared when I `user.update(first_name:'bob')` when i updated from  1.3.4 to 1.3.5 :</summary>

       (1.1ms)  COMMIT
    Searchkick::Error: Job adapter not found
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/searchkick-1.3.5/lib/searchkick/index.rb:103:in `reindex_record_async'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/searchkick-1.3.5/lib/searchkick/model.rb:88:in `reindex_async'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:232:in `block in conditional'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `block in call'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `each'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:354:in `committed!'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:87:in `commit_records'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:178:in `commit_transaction'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:264:in `update'
    	from (irb):2
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    	from /Users/nicolas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
    	from bin/rails:4:in `require'
    	from bin/rails:4:in `<main>'

</details>

I think it is from https://github.com/ankane/searchkick/commit/e66ab786b3c347022ce2f90c088e8795c3ac0a78 because my workaround is to put `require 'searchkick/reindex_v2_job'` in application.rb and it works.

**Comment by ankane** [comment]
Hey @nicolasmlv, can you give more info on your setup?

**Comment by jfloff** [comment]
I'm experiencing the same error, and can confirm that the fix @nicolasmlv provided works. 

Which info do you want about the setup?

**Comment by ankane** [comment]
Thanks @jfloff, framework version and stack trace of the error would be a good start.

**Comment by jfloff** [comment]
I'm using searchkick v1.3.5, with rails 4.2.3 and ruby 2.2.5.

Stack trace:
```
Searchkick::Error (Job adapter not found):
  app/controllers/current_user/items_controller.rb:55:in `create'


  Rendered /app/heroku/ruby/bundle/ruby/2.2.5/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (6.0ms)
  Rendered /app/heroku/ruby/bundle/ruby/2.2.5/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.4ms)
  Rendered /app/heroku/ruby/bundle/ruby/2.2.5/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /app/heroku/ruby/bundle/ruby/2.2.5/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (32.0ms)
```

**Comment by ankane** [comment]
Do you have `require 'rails/all'` as the 2nd line in `config/application.rb`? If so, what happens if you add `require "active_job/railtie"` right afterwards?

**Comment by jfloff** [comment]
> Do you have `require 'rails/all'` as the 2nd line in `config/application.rb`?

Yes


> If so, what happens if you add `require "active_job/railtie"` right afterwards?

Got same error (no difference in stack trace)

**Comment by ankane** [comment]
My guess is that `ActiveSupport.on_load(:active_job)` isn't firing, but don't know why.

**Comment by electricdrop** [comment]
Just got the same error. I'm usind Sidekiq as ActiveJob backend. In my `config/application.rb` i have `config.active_job.queue_adapter = :sidekiq`

**Comment by ankane** [comment]
I tried this out on a fresh Rails 5 app and was able to reproduce. Reverted e66ab78 and pushed a new release. Thanks all 💯
