### ISSUE TITLE
Boosted field match method is not respected if it isn't a symbol

### ISSUE THREAD

**Issue by alisaifee** [ankane/searchkick#743]
If I perform a search with
`Product.search('milk', fields: [{"title^5" => :word_start}])`, the query works. However, if I use `Product.search('milk', fields: [{"title^5" => "word_start"}])` I will receive no results.

The issue does not appear if the field name is not boosted.

**Comment by ankane** [comment]
Hey @alisaifee, I think the issue is `fields` expects an array, not a hash.

```ruby
Product.search('milk', fields: [{"title^5" => "word_start"}]
```

I pushed a test to the `word_start_string_boost` branch, and it passes.

**Comment by alisaifee** [comment]
@ankane that was my mistake in the example I provided. I actually had an array of hashes in the test.

**Comment by alisaifee** [comment]
Sorry for they delay, I had mixed up my test case where I hadn't actually added the field I was searching for in the `searchkick word_start: [...]` array.
