### ISSUE TITLE
How to suppress Faraday::ConnectionFailed error.

### ISSUE THREAD

**Issue by rawat22** [ankane/searchkick#745]
When elastic server is down, I am getting this error while creating from any model where I have used search_data to index.
Faraday::ConnectionFailed (Connection refused - connect(2) for "localhost" port 9200)

How to handle this exception? Any suggestion

**Comment by ankane** [comment]
@rawat22 You can rescue this exception just like any other.

**Comment by rawat22** [comment]
Class Event < ActiveRecord::Base

 begin
  searchkick index_name: "event"
  def search_data
  --
  end
 rescue => e
  pp e.to_s
 end

end

I want to rescue in the model level. The above rescue still fails

Not on the save or update like below.. -
begin
 Event.save
rescue
end

**Comment by ankane** [comment]
Hey @rawat22, not sure I follow, but this seems like more general Ruby/Rails question than a Searchkick question.
