### ISSUE TITLE
searchkick.org blacklisted by OpenDNS

### ISSUE THREAD

**Issue by anothermh** [ankane/searchkick#749]
When I go to Google and search for "searchkick" the first result is this repo. The second result is searchkick.org. When I attempt to browse to that site using OpenDNS as my DNS provider, I receive an alert that says "This domain is blocked due to a security threat."

Is that domain officially affiliated with this gem? Is there actually malware hosted there? Can you work to get it unblocked? It's hard for me to say to my colleagues "Let's use this library!" when the site is blocked for malware 👎

**Comment by ankane** [comment]
Thanks for letting me know. Searchkick.org is another version of the readme - no malware included.

**Comment by jdjkelly** [comment]
Came here to report the same thing. Using a corporate network which uses the OpenDNS malware scanner. Corp. IT provided me with these two screenshots - not sure of the source:

<img width="790" alt="virustotal" src="https://cloud.githubusercontent.com/assets/704789/19359543/a843c42e-9148-11e6-889f-bd5a86b28b72.png">
<img width="1375" alt="opendns report" src="https://cloud.githubusercontent.com/assets/704789/19359542/a843c35c-9148-11e6-9856-f933b25057a1.png">

**Comment by ankane** [comment]
I emailed OpenDNS and they were very responsive. This should be fixed now.
