### ISSUE TITLE
Product.reindex vs product.reindex done for all products?

### ISSUE THREAD

**Issue by fikriauliya** [ankane/searchkick#750]
What's the difference between these 2?

`Product.reindex`
and
`Product.find_each { |p| p.reindex }`

**Comment by anothermh** [comment]
From https://github.com/ankane/searchkick#indexing:

"Searchkick uses `find_in_batches` to import documents."

From http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_each:

"The `find_each` method uses `find_in_batches` with a batch size of 1000 (or as specified by the `:batch_size` option)."

So at first glance, it would appear that they're the same. But if you dig a little deeper to https://github.com/ankane/searchkick#reference:

"Reindex more than one record without recreating the index: `some_company.products.each { |p| p.reindex }`"

You can see that indexing one record at a time will UPDATE the existing index. Indexing the entire model (`Product.reindex`) will RECREATE the index.

**Comment by ankane** [comment]
@anothermh's last line sums it up nicely. [This](https://github.com/ankane/searchkick#to-reindex-or-not-to-reindex) describes when you need to recreate the index.

**Comment by fikriauliya** [comment]
Hmm, if that's the case, we should be discourage to run `Product.reindex` multiple time to avoid duplicating the index?

We encountered problem when calling `Product.find_each {|p| p.reindex}` only **without** invoking`Product.reindex` before. `Product.search "keyword"` doesn't work in that case, only `Product.search "*"` does work.

**Comment by ankane** [comment]
The old index is cleaned up as soon as the new one is ready, so not much downside if you have enough space in your cluster.

The behavior you're seeing is expected. When searching for all records (`*`), no custom Searchkick analyzers are used, whereas searching for a term requires you to have Searchkick set up correctly (`Product.reindex`).

**Comment by fikriauliya** [comment]
Thx, understood :).

One last thing: If I have run `Product.reindex` once (to setup Searchkick), could I **just** use `product.reindex` for subsequence reindexing (i.e. never run `Product.reindex` again)?

**Comment by ankane** [comment]
Yes, if you never update your `searchkick` method and none of the data types change in your `search_data` method.

**Comment by MrHubble** [comment]
Should Searchkick use `find_each` rather than `find_in_batches`? I'm basing this question on comments made on [this article](http://www.mikeperham.com/2012/05/05/five-common-rails-mistakes/)

>I tend to use find_each (which calls find_in_batches internally) to gain the benefits of reducing returned result size without having to use a nested block.

>find_each is just like find_in_batches but yields a single instance so you don't need the nested iterator.

>For simple batch processing you can use find_each insted of find_in_batches.

>In your example above, `find_each` instead of `find_in_batches` would save you some code
