### ISSUE TITLE
Error Result window is too large

### ISSUE THREAD

**Issue by qjpioneer** [ankane/searchkick#751]
hi im new in ruby on rails and i try to use this gem but there are some errors 

`[500] {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"movies_development_20161013163708783","node":"8gHRL7S7TU-o7jH2csf1xA","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."}}]},"status":500}`

and I try this

`class Item < ActiveRecord::Base
  searchkick settings: {index: {max_result_window: 100000}}
end`

but it doesn't work

**Comment by chamnap** [comment]
Checkout this, https://github.com/ankane/searchkick/issues/642.

**Comment by ankane** [comment]
@qjpioneer Be sure to reindex after changing the settings.

**Comment by ankane** [comment]
Cleaning up issues
