### ISSUE TITLE
Postgres range support

### ISSUE THREAD

**Issue by chrise86** [ankane/searchkick#753]
Using Rails 5.0.0.1, searchkick 1.3.6 (also tried 1.3.4) and updated to elasticsearch 2.4.1:

```
# models/group.rb

searchkick locations: ['location']

def search_data
  {
    name: name,
    age_range: age_range,
    location: { lat: latitude, lon: longitude }
  }
end
```

Then `Group.reindex` in the console. Sometimes I see `ETHON: Libcurl initialized`, but then nothing. I've left it quite some time and it just eats the RAM and then HDD space - there are only 52 `Group` records :-/

The issue is with the Postgres range type - the `age_range` field is an `int4range`.

**Comment by chrise86** [comment]
My solution was to separate the range out to 2 separate fields:

```
def search_data
  {
    min_age: age_range.try(:first),
    max_age: age_range.try(:last)
  }
end
```

Not sure whether this is something that is "fixable", or a "gotcha" to be documented maybe?

**Comment by ankane** [comment]
Hey @chrise86, for the first example:

1. What happens if you set `searchkick batch_size: 1` on the model and reindex?
2. What does `Group.first(10).map(&:search_data)` return? (change any sensitive info)

**Comment by ankane** [comment]
Cleaning up issues
