### ISSUE TITLE
multi indices search; check which model(s) is(are) found in the result

### ISSUE THREAD

**Issue by Milou121** [ankane/searchkick#755]
Hi All,

I've set up a search in my rails app.

Profiles_controller.rb:

`def index
    query = params[:search].presence || "*"
    @results = User.search(query, index_name: [User.searchkick_index.name, Location.searchkick_index.name, Competence.searchkick_index.name], suggest: true, operator: "or")
  end`

In my view, I'm trying to check if @results is giving back a User, a Location, a Competence, or two or all of them.

In my console, I'm checking this with a query of a Competence ("ruby"). The result I'm getting back is:

$ r = @results.results = 

![image](https://cloud.githubusercontent.com/assets/18393994/19683982/1789bf26-9ab5-11e6-80da-8b2350e0d029.png)

In this case, how can I check if this is a competence (as it is in this example)?

r. (type?)              or anything?

**Comment by ankane** [comment]
Hey @Milou121, there are few ways you can check a class in Ruby.

```ruby
@results.each do |result|
  p result.class.name
  p result.is_a?(Competence)
end
```

**Comment by Milou121** [comment]
Hi @ankane, 

Thanks for your response! I tried to check it with:

`<% if @results.hits.reduce({}, :merge).has_value?("location") == true %>`

but, this is way more efficient!

Is there a way that I can combine the results if the query involves users, locations and competences?

Right now, my view looks like this (only users and locations for now):

`      <% if @results.hits.reduce({}, :merge).has_value?("location") == true %>
      <% @results.each do |location| %>
      <% @users.where(location_id: location.id).each do |user|%>
      <div class="col-xs-12 col-sm-4">
        <%= link_to root_path do %>
        <div class="orange-profile-card">
          <div class="pp-location">
            <%= user.first_name %> <%= user.last_name %>
            <%= location.name %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>

      <% if @results.hits.reduce({}, :merge).has_value?("user") == true %>
      <% @results.each do |user| %>
      <div class="col-xs-12 col-sm-4">
        <%= link_to root_path do %>
        <div class="orange-profile-card">
          <div class="pp-user">
            <%= user.first_name %> <%= user.last_name %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>`

But if a query involves a user's name AND a location's name, it obviously runs an error, saying it can't do " .first_name " on user (NilClass).

Can I fix this with improving the if/else statement, or is there a better way?

Thank you so much already!

**Comment by ankane** [comment]
Hey @Milou121, an if/else statement seems like a fine way. You could also use `user.try(:first_name)`.
