### ISSUE TITLE
Using suggestions with synonymns

### ISSUE THREAD

**Issue by justinboynton** [ankane/searchkick#756]
Hi 

I can't seem to get synonyms to work when also using the suggestions feature. Should they play nice together or is this a known issue?

Thanks
Justin

**Comment by ankane** [comment]
Hey @justinboynton, after a quick [scan of the code](https://github.com/ankane/searchkick/blob/2a506a2465889d324b2cf25379c47ec7d9df938f/lib/searchkick/index_options.rb#L179), it looks like synonyms are not being applied to suggestions. Can you explain more about the behavior you'd like to see?

**Comment by justinboynton** [comment]
Hi @ankane thanks for coming back to me so quickly. I have resolved the issue and it's down to operator error in the set up of our synonyms and nothing to do with having the suggest feature turned on. It would be good to see synonyms applied to the suggested terms i.e also include a synonym in the suggested terms.

**Comment by ankane** [comment]
👍
