### ISSUE TITLE
How can i turn the Searchkick::Results object to ActiveRecord object ?

### ISSUE THREAD

**Issue by chris2233** [ankane/searchkick#758]
we used wice_grid in our project, but wice_grid needs  ActiveRecord object search result ,so how can we turn search result to a ActiveRecord object ?

**Comment by ankane** [comment]
Hey @chris2233, for now, you can call `results.records`, which will return an *unordered* scope of the results. This may go away in Searchkick 2.0 or be renamed `unordered_records`.

**Comment by chris2233** [comment]
@ankane it worked well for now. thanks a lot！
