### ISSUE TITLE
Using `not` with `or`

### ISSUE THREAD

**Issue by chrise86** [ankane/searchkick#760]
Using the following:
```
List.search params[:q],
  where: {
    or: [
      { recipient_id: current_user.id, secret: false },
      { recipient_id: { not: current_user.id }, secret: true },
      { recipient_id: nil }
    ]
  }
```
results in:
```
Searchkick::InvalidQueryError ([400] {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[missing] query does not support [not]","index":"lists_development_20161101100017108","line":1,"col":769}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"lists_development_20161101100017108","node":"itT920nNQnSGhbJlCaEeOQ","reason":{"type":"query_parsing_exception","reason":"[missing] query does not support [not]","index":"lists_development_20161101100017108","line":1,"col":769}}]},"status":400}):
```
Is this query possible? Also, in the readme it suggests the syntax should be:
```
or: [
  [{ recipient_id: current_user.id, secret: false }],
  [{ recipient_id: { not: current_user.id }, secret: true }],
  [{ recipient_id: nil }]
]
```
but it seems to work (or not in this case - due to the `not` issue) either way - which is "correct", or doesn't it matter?

**Comment by ankane** [comment]
If you're trying to do `(recipient_id = current_user.id AND secret = false) OR (recipient_id != current_user.id AND secret = true) OR (recipient_id = nil)`, the syntax you want is:

```ruby
or: [[
  { recipient_id: current_user.id, secret: false },
  { recipient_id: { not: current_user.id }, secret: true },
  { recipient_id: nil }
]]
```

The current syntax for OR queries is pretty confusing.

**Comment by ankane** [comment]
There's now a new `_or` syntax, fwiw.

**Comment by maschwenk** [comment]
@ankane would it make sense to outline the difference between `_or` and `or` somewhere? And potentially include a slightly more complex example just to illustrate how to use it? The difference between the two tripped me up, wasn't sure if `_` was a typo or the real deal.

**Comment by ankane** [comment]
or without an underscore is no longer recommended and has been removed from the docs. We could mention it in upgrade notes.

**Comment by jdraths** [comment]
@ankane I'm curious why you no longer recommend `or`?
[It appears that it is still functional?](https://github.com/ankane/searchkick/blob/6f69dddc16b819387f4014f452d4458105953c6d/lib/searchkick/query.rb#L724)

I'm using it right now for a multi-index search
```ruby
Searchkick.search( "milk", index_name: [Product, Category],
  where: {
    or: [[
      {_id: [1, 2], _type: "product"}, 
      {_id: [3, 4], _type: "category"}
    ]]
  }
)
```

**Comment by ankane** [comment]
Hey @jdraths, the `_or` syntax is more intuitive and can be nested.
