### ISSUE TITLE
unknown setting batch_size with Elasticsearch 5.0

### ISSUE THREAD

**Issue by jbwl** [ankane/searchkick#761]
After upgrading to ES 5.0 with no changes to my searchkick config, I am getting this error on reindexing:

```json
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {
    "error": {
        "root_cause": [{
            "type": "illegal_argument_exception",
            "reason": "unknown setting [index.batch_size] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
        }],
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.batch_size] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    },
    "status": 400
}
```

in my model I have the following:

```ruby
searchkick settings:   { batch_size: 1500, number_of_shards: 1 }
```

**Comment by jbwl** [comment]
Never mind, my mistake

**Comment by adsherpa** [comment]
Would appreciate your fix on this, I am having similar issue with unknown setting

**Comment by mikelkew** [comment]
Just in case you've made the same mistake, the `batch_size` setting should not be within the value for `settings`. It is a searchkick option, not an elasticsearch option. Thus, the correct way to do it (using the example above) would be `searchkick batch_size: 1500, number_of_shards: 1`
