### ISSUE TITLE
Added support for partial reindex

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#766]
Reindex a subset of attributes. Elasticsearch reindexes the entire doc on updates, but we can save time in the `search_data` method and over the wire.

```ruby
class Product
  def search_pricing
    {
      price: price
    }
  end
end
```

and

```ruby
Product.partial_reindex(:search_pricing)
```

**Comment by meetrajesh** [comment]
Looks great!

**Comment by paddingtonsbear** [comment]
@ankane
Any chance we could add the ability to `partial_reindex` a particular record ?

So this 
```ruby
Product.partial_reindex(:method)
``` 
currently works but this
```ruby
product.partial_reindex(:method)
```
 does not. Could the latter also be added, I can send a PR if that would help

**Comment by paddingtonsbear** [comment]
I just submitted a PR https://github.com/ankane/searchkick/pull/771, let me know what you think

**Comment by feliperaul** [comment]
I just noticed this nice feature in the docs and tried using, but I'm getting `undefined method `partial_reindex' ` error. 

I think this is not released yet, right? But it's already in the docs in github.

**Comment by ankane** [comment]
Yeah, it's tagged `[master]` in the docs to indicate it's only available if you use the master branch. Anyways, I just pushed out a new release.
