### ISSUE TITLE
How can I use Delayed Job

### ISSUE THREAD

**Issue by MatayoshiMariano** [ankane/searchkick#769]
Hi, I am using the DelayedJob gem, and I see in the code that searchkick [does it too](https://github.com/ankane/searchkick/blob/30ba080fa35f89fb1984ba7d84e0d732c477d540/lib/searchkick/index.rb#L102-L106), but I do not know how to tell searchkick to use DelayedJob because the class `Searchkick::ReindexV2Job` is always defined. Any ideas?

Thanks!

**Comment by ankane** [comment]
Are you using the DelayedJob adapter for ActiveJob?

**Comment by MatayoshiMariano** [comment]
@ankane Thanks for the fast reply!
No, I am using [this](https://github.com/collectiveidea/delayed_job_active_record) gem for ActiveRecord

**Comment by MatayoshiMariano** [comment]
Sorry, I closed the issue by mistake!

**Comment by ankane** [comment]
Two options are:

1. Configure ActiveJob to use DelayedJob for your entire application
2. Configure that specific job to use DelayedJob (set `Searchkick::ReindexV2Job.queue_adapter = :delayed_job` in an initializer)

**Comment by MatayoshiMariano** [comment]
@ankane Ok, awsome!
Thanks

**Comment by ankane** [comment]
No problem!
