### ISSUE TITLE
Better syntax for highlighting

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#770]
The current syntax for highlighting isn't great (`with_details` method). A few alternatives:

```ruby
Product.search("boom", fields: [:name], highlight: true).each do |product|
  product.search_hit # all hit details
  product.search_highlights[:name]
  product.highlighted_name # may be too intrusive
end
```

**Comment by carolliu** [comment]
I experience a problem in `highlight` function.  searchkick provides default mapping for a string field `searchable` as:
```
"searchable": {
                        "type": "string",
                        "index": "not_analyzed",
                        "fields": {
                           "analyzed": {
                              "type": "string"
                           }
                        },
                        "include_in_all": true,
                        "ignore_above": 256
                     }
```

When I perform `Product.search '*', load:false, highlight: true, fields: ['searchable']`, the query to Elasticsearch is `{"query":{"match_all":{}},"size":1000,"from":0,"highlight":{"fields":{"space_types.searchable.analyzed":{}}},"timeout":"11s"`, which results in no highlight returned.

How can we we remove the added `analyzed` in "space_types.searchable.analyzed" highlight field by https://github.com/ankane/searchkick/blob/c0b0460efa008aed537a248d80f67b5633bbd167/lib/searchkick/query.rb#L612 ?

**Comment by ankane** [comment]
Hey @carolliu, you'll need to [modify the query generated by Searchkick](https://github.com/ankane/searchkick#advanced-search) if you want to highlight the non-analyzed field.
