### ISSUE TITLE
Elasticsearch 5.0 GA support

### ISSUE THREAD

**Issue by MrHubble** [ankane/searchkick#772]
Does Searchkick support Elasticsearch 5.0 GA?

The changelog lists _"Added support for Elasticsearch 5.0 beta"_ for Searchkick version 1.3.5, but [with Elasticsearch 5.0.0 GA released](https://www.elastic.co/blog/elasticsearch-5-0-0-released) I was wondering whether there was anything outstanding for 5.0 GA to be fully supported.

**Comment by ankane** [comment]
Yes, 5.0 is fully supported.
