### ISSUE TITLE
Updating an analyzer setting

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#778]
Is there a way for me to update the default analyzer setting?

I run my ElasticSearch instance on Elastic.co, and they have an upgrade checker you can run prior to updating to their new 5.0 product.  The tool is reporting the following:

```
index.analysis.analyzer.default_index.tokenizer has been replaced by index.analysis.analyzer.default.tokenizer
index.analysis.analyzer.default_index.type has been replaced by index.analysis.analyzer.default.type
jobs_production_20161020224759394
```

Is there a way I can have SearchKick make this update?  Or if I upgrade an reindex will this automatically get changed?  I see this:

[(https://github.com/ankane/searchkick/blob/bf98f61bc9618eef3aa57d557a0f5efb5f8e22fe/lib/searchkick/index_options.rb)](https://github.com/ankane/searchkick/blob/bf98f61bc9618eef3aa57d557a0f5efb5f8e22fe/lib/searchkick/index_options.rb)

**Comment by MrHubble** [comment]
I don't know if it's good advice but the tool gave me the same report and I just upgraded anyway without making changes beforehand. It all seem to go fine but I was also trying to `reindex` afterwards so I'm not sure if I implemented any changes/fixes without knowing.

**Comment by ankane** [comment]
@cmalpeli I don't think there's a way to update that part of mapping. If you do a full reindex with the latest version of Searchkick, it now uses `searchkick_index` as the default analyzer, which should make the warning go away.

**Comment by cmalpeli** [comment]
@ankane thanks - that is what I did and it seemed ok.  thank you for an amazing product!

**Comment by ankane** [comment]
Awesome, thanks :)
