### ISSUE TITLE
Routing + Async, not acting asynchronous

### ISSUE THREAD

**Issue by todddickerson** [ankane/searchkick#780]
Using:

>   searchkick callbacks: :async, routing: true

We were expecting that Elasticsearch would not be hit inline during the creation of the new record but it is still for some reason, causing occasional timeouts for users when model.save is called.

What are possible causes for this?  
- Does routing disable async?  
- Does async not work if there's not a 'searchkick' queue specified in sidekiq?

Additional info: 
Using Sidekiq 4.0.1, Sidekiq Enterprise 1.0.2

**Comment by ankane** [comment]
The `routing` option has no impact on `async`, so guessing it's something else with your set up. Is your `ActiveJob::Base.queue_adapter` set to inline?

**Comment by todddickerson** [comment]
Awesome, that's it - hadn't been using active_job in this app yet, wasn't set at all
