### ISSUE TITLE
Limit of total fields reached in elasticsearch 5+

### ISSUE THREAD

**Issue by Jaroost** [ankane/searchkick#781]
I updated elasticsearch 2.3 to 5.0.2 and I have a really big model with a lots of fields(1000+) that I want to index. 

When I do so, I have this error:

`Limit of total fields [1000] in index [machines_development_20161203100655450] has been exceeded`

I see in the documentation that the limit has been set to the elasticsearch 5+ can we change that limit when using the reindex rake task?

`rake searchkick:reindex:all`

**Comment by Jaroost** [comment]
Just add and it works:
```
 searchkick, settings: { "index.mapping.total_fields.limit": <limit>}
```

**Comment by kishan3** [comment]
Can anyone guide me how to do it? I am using elasticsearch==2.4.0 in python flask project getting same error. 
`from elasticsearch import Elasticsearch
from elasticsearch import helpers

es_repo = Elasticsearch(hosts=[settings.ES_INDEX_URL],
                        verify_certs=True)
`
