### ISSUE TITLE
Creating aggregations on nested JSON column?

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#782]
Is it possible to create aggregations on fields within a JSON structure?

I have a single postgres JSONB column called `custom_field_answers` with key/value pair data like this:

`{"job_seeking_status": "Currently looking", "job_seeking_preference": ["", "Customer service", "Helpdesk"], "permanent_australian_resident": "No"}`

Can I create aggregations on `job_seeking_status`, `job_seeking_preference`, and `permanent_australian_resident`?

Thanks!

**Comment by cmalpeli** [comment]
Further to my above question, how would I index specific values from a JSONB column?

So if I have my `custom_field_answers` column, with the values `{"question_1": "No", "question_2": "some answer"}`

How would I add say, just `custom_field_answers["question_2"]` to the below list of fields:

`["summary^10", "label^10", "location"]`

**Comment by cmalpeli** [comment]
OK, well I see I can use dot notation inside of Fields

`["summary^10", "label^10", "location", "skills", "custom_field_answers.question_1"]`

But still can't seem to get the aggregations syntax working:

` {city: {}, state: {}, skills: {limit:20}, custom_field_answers: {question_1:{}}}`

**Comment by ankane** [comment]
Aggregations aren't currently supported on nested data (as far as I know).

**Comment by cmalpeli** [comment]
I was able to do so doing the following:

`@custom_aggs = MyModel.custom_fields.public_send("#{search_class.name.downcase}_fields_filterable").pluck(:name).map{ |k| "custom_field_answers.#{k}" }`

There is some other stuff going on there, but basically by getting my custom used defined fields, and then all the answers to those custom field question and then doing a `.map` on those worked.

Here I combine the system aggregations with the custom user defined ones:

```def aggs
    [:company, :city, :state, :job_type, :categories].concat(@arr_custom_field_filters)
  end```

Hopefully this will give someone else some ideas on how to solve within their own context.
