### ISSUE TITLE
Custom mapping apparently is being ignored

### ISSUE THREAD

**Issue by ruischnaider** [ankane/searchkick#784]
Hi, 

I'm making a custom map of my model and searchkick apparently is not detecting it.

I'm using:
- elasticsearch (5.0.0)
- searchkick (1.4.0)

in my model i have this:
```
searchkick merge_mappings: true,
             mappings: {
                 product: {
                     properties: {
                         field: {
                             type: 'string'
                         }
                     }
                 }
             }
```

when i get the mapping from elasticsearch with curl, it returns this:
```
{
    "products_development":{
        "mappings":{
            "product":{
                "properties":{
                    "codder":{
                        "type":"text",
                         "fields":{
                              "keyword":{"type":"keyword","ignore_above":256}
                         }
                    }
                }
            }
        }
    }
}
```

What I've missed?

**Comment by rubydog** [comment]
@ankane apparently they are ignored for me as well.

I'm using

`searchkick 2.0.1`
`elasticsearch 1.7.6`

Custom analyser and mappings:

    searchkick merge_mappings: true,
    settings: {
      analysis: {
        analyzer: {
          namegrams: {
            type: "custom",
            tokenizer: "keyword",
            filter: [
              "ngrams_filter"
            ]
          },
          search_ngram: {
            type: "custom",
            tokenizer: "lowercase",
            filter: [
              "truncate_filter"
            ]
          }
        },
        filter: {
          ngrams_filter: {
            type: "ngram",
            min_gram: 2,
            max_gram: 8
          },
          truncate_filter: {
            type: "truncate",
            length: 8
          }
        }
      }
    },
    mappings: {
      meal: {
        properties: {
          name: {
            type: "string",
            index_analyzer: "namegrams",
            search_analyzer: "search_ngram"
          }
        }
      }
    }

When I execute `Searchkick.search(params[:q], index_name: [Meal, Ingredient], indices_boost: {Meal => 100, Ingredient => 1}).results` following query is generated

    curl http://localhost:9200/meals_development%2Cingredients_development/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"lunch","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"lunch","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"lunch","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"lunch","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":1000,"from":0,"indices_boost":{"meals_development_20170108131840208":100,"ingredients_development_20170108131840619":1},"timeout":"11s","_source":false}'


and when I try `Meal.search body: {match: {name: 'lunch'}}` I get

curl http://localhost:9200/meals_development/_search?pretty -d '{"match":{"name":"lunch"}}'
Searchkick::InvalidQueryError: [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[FMOVk3xcRg-RxkmiqWvMRw][meals_development_20170108131840208][0]: SearchParseException[[meals_development_20170108131840208][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"match\":{\"name\":\"lunch\"}}]]]; nested: SearchParseException[[meals_development_20170108131840208][0]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[FMOVk3xcRg-RxkmiqWvMRw][meals_development_20170108131840208][1]: SearchParseException[[meals_development_20170108131840208][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"match\":{\"name\":\"lunch\"}}]]]; nested: SearchParseException[[meals_development_20170108131840208][1]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[FMOVk3xcRg-RxkmiqWvMRw][meals_development_20170108131840208][2]: SearchParseException[[meals_development_20170108131840208][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"match\":{\"name\":\"lunch\"}}]]]; nested: SearchParseException[[meals_development_20170108131840208][2]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[FMOVk3xcRg-RxkmiqWvMRw][meals_development_20170108131840208][3]: SearchParseException[[meals_development_20170108131840208][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"match\":{\"name\":\"lunch\"}}]]]; nested: SearchParseException[[meals_development_20170108131840208][3]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }{[FMOVk3xcRg-RxkmiqWvMRw][meals_development_20170108131840208][4]: SearchParseException[[meals_development_20170108131840208][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"match\":{\"name\":\"lunch\"}}]]]; nested: SearchParseException[[meals_development_20170108131840208][4]: from[-1],size[-1]: Parse Failure [No parser for element [match]]]; }]","status":400}


Where could I be wrong?

Thanks many!

**Comment by ankane** [comment]
Hey @rubydog, you're missing the `query` wrapper around `match`. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html

**Comment by ruischnaider** [comment]
@ankane i already did the `reindex` but it doesnt work anyway.

**Comment by ankane** [comment]
Hey @ruischnaider, the output above suggests it wasn't successful. How have you tried to debug?

**Comment by ruischnaider** [comment]
@ankane i executed the following curl:

`curl http://localhost:9200/products_development/_mapping`

and i tried to change the analyzer too.

**Comment by ankane** [comment]
You should do a bit more than that before claiming it's not working. I'd try:

1. Fork the gem, cloning it locally, and adding it to your Gemfile with the `path` option
2. Search for the method that's not working - `reindex` in this case
3. Use a debugger or print out info (my favorite) until you figure out what's going on
