### ISSUE TITLE
Query is right?

### ISSUE THREAD

**Issue by raphaelcuba** [ankane/searchkick#785]
Hi everyone.

I'm building a query with or clausure:
```ruby
{
  or: [
    [
      {
        'location' => {
          near: {
            lat: -22.9090395,
            lon: -43.1710457
          },
          within: '30km'
        }
      }
    ],
    [
      { 'address.city.slug' => 'sao-paulo' }
    ]
  ]
}
```
The gem returns the following structure:
```javascript
{
  "query":{
    "bool":{
      "must":{
        "match_all":{}
      },
      "filter":[
        {"or":[{"and":[{"term":{"address.city.slug":"sao-paulo"}}]}]},
        {"or":[{"and":[{"geo_distance":{"location":{"lat":-22.9090395,"lon":-43.1710457},"distance":"30km"}}]}]}
      ]
    }
  },
  "size":25,"from":0,
  "sort":[
    {"_score":"desc"},
    {"_geo_distance":{"location":{"lat":-22.9090395,"lon":-43.1710457},"order":"asc","unit":"km"}},
    {"priority":"asc"}
  ],
  "timeout":"11s","fields":[]
}
```

But the elasticsearch doesn't returns any results. Yes, I have results persisted that should be returned. This query must returns the documents that have `address.city.slug` equals `"sao-paulo"` or that was in the `location` defined.
Can anyone help me with this issue that `or` doesn't working? My query is right to my objective or this is a bug?

**Comment by ankane** [comment]
I believe your `or` syntax is off: you should only have 1 value instead the root array. Searchkick recently got a new `_or` syntax that's a bit more intuitive. See the readme for how to use.
