### ISSUE TITLE
Callbacks triggering even if callbacks: false

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#786]
I'm on Rails 4.0.13 and SearchKick 1.4.0, and even if I use `searchkick callbacks: :false` I still get the callback after any save on the model. The only thing that prevents the callback right now if I use `searchkick callbacks: :async` (then the DelayedJob is created and no callbacks).

I'm testing on the console so I can see the yellow output whenever the callback occurs.

Took a look at the source code and couldn't find anything immediately.

**Comment by ankane** [comment]
It looks like you're using the symbol `:false` instead of `false`.

**Comment by feliperaul** [comment]
My mistake @ankane . Thanks
