### ISSUE TITLE
Synonym as an association

### ISSUE THREAD

**Issue by oyeanuj** [ankane/searchkick#788]
Hi @ankane! Firstly, thank you for open-sourcing this - it is immensely helpful.

A question on appropriate way to use synonyms: In my case, I have synonyms as an association in the following way - 

```ruby
class Thing
  #attributes :id, :name
  has_many :synonyms,
  dependent: :destroy
end

class Synonym
  #attributes: :id, :value
  belongs_to: :thing
end
```

At the moment, I have just added synonyms to the `searchkick_data` function:
```ruby
class Thing
  #attributes :id, :name
  has_many :synonyms,
  dependent: :destroy

  searchkick word_start: [ :name, :synonyms]

  def search_data
    {
      name:      name,
      synonyms:  synonyms.map(&:value)
    }
  end


end
```

While this works, it feels hacky looking at how you talk about using synonyms in the Readme. So, I'm wondering if there is an implication of using it this way vs how the readme example shows? 

Alternatively, is there a way to set it up as the Readme example even when synonym is an association (and not read from a file or a finite list)?

Thank you!

**Comment by ankane** [comment]
For dynamic synonyms, I'll use a similar approach, but combine the fields. There may be better ways, but it seems to work fine.

```ruby
class Product
  has_many :tags

  def search_data
    {
      name: "#{name} #{tags.map(&:value).join(" ")}"
    }
  end
end
```

I'll add this to the readme so it feels like "hacky" :)

**Comment by oyeanuj** [comment]
Cool, thank you for the prompt response! I kept them as separate fields since I was using the `name` field as part of the autocomplete results.

So, I guess there is no difference in searching if you set it up as shown in the Readme or as we have discussed here?

**Comment by ankane** [comment]
The main difference is for multi-word queries. Combining them will have better recall. Example:

Search query: `frozen hamburger`
Thing name: `frozen burger`
Synonym/tag: `hamburger`

With separate fields, this returns no results. If you need to use the `name` field in results, I'd create a new `name_tagged` field to search on.

**Comment by ankane** [comment]
Although for autocomplete, separate is likely better, but just know the case above won't be handled well.

**Comment by oyeanuj** [comment]
Got it, thank you! :)

**Comment by yurgon** [comment]
Hello
But anyway I need to reindex after added new synonym
