### ISSUE TITLE
boosting results by filter

### ISSUE THREAD

**Issue by jstultz** [ankane/searchkick#79]
elasticsearch seems to offer a few different ways of altering result scores in more advanced ways than just specifying fields to boost. For example, function score query:

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

I'd like to be able to do something like the location example shown on that page, but a little bit simpler. Say I have a restaurant database, and have the ability to search for restaurants by name or cuisine:

```ruby
Restaurants.search "Italian"
```
is straightforward enough. But users are probably more interested in looking for restaurants near them:

```ruby
Restaurants.search "Italian" where: { location: { near: user_location, within: "15mi" } }
```

but a user might be searching for a specific restaurant that is not nearby; perhaps they are planning a trip. In this case it would be helpful to not simply filter to only those restaurants that are nearby, but to simply increase the relevancy of restaurants nearby, so that a great match on the other side of the country would appear in search results alongside mediocre matches nearby.

It seems it is possible to do this with elasticsearch's function score querying, but it is not clear to me whether it's possible to use this functionality via searchkick. Can someone illuminate this?

**Comment by ankane** [comment]
You can now use `boost_by_distance` to accomplish this.
