### ISSUE TITLE
Search multiple indices (models)

### ISSUE THREAD

**Issue by kesha-antonov** [ankane/searchkick#791]
Hello!

I'm trying to search multiple indices (2-3 models) by same text field ```description```.
Table1 have only field ```description```. Table2 have ```description``` AND field ```user_id```.

So what I'm trying to do is to search by ```description``` both tables and filter out results returned from table2 by ```user_id``` (I need records with certain ```user_ids```)

I've posted question on SO: http://stackoverflow.com/questions/41290396/multi-index-search-with-elasticsearch-with-filtering-by-single-index

And here's my code:

```
r = Searchkick.search( '*',
      index_name: [ CoolModel1, CoolModel2 ],
      body: {
        query: {
          bool: {
            must: {
              match_all: {}
            },
            filter: {
              bool: {
                should: [
                  indices: {
                    indices: ['cool_model2'],
                    query: {
                      terms: {
                        user_id: [117]
                      }
                    },
                    no_match_query: 'none'
                  }
                ]
              }
            }
          }
        }
      }
    )
```

Can you help or give advice? Doing this all day but didn't resolve it by myself.

For example:

Table 1
record1: { description: "test" }
record2: { description: "testtest" }

Table 2
record1: { description: "test", user_id: 1 }
record2: { description: "testtest", user_id: 117 }

My query should return 2 records from Table1 and 1 record from Table 2 (with ```user_id = 117```).

**Comment by kesha-antonov** [comment]
Solved! :)

With this question and digging in official docs
http://stackoverflow.com/questions/21753021/elasticsearch-global-search-different-filter-on-multiple-indexes

**Comment by peresleguine** [comment]
@kesha-antonov what you came up with in the end? Could you please post some code?
