### ISSUE TITLE
search by tag probability

### ISSUE THREAD

**Issue by zealot2007** [ankane/searchkick#792]
Hey guys, 
 I want to search a photo by tag. But I don't know how to deal with when tags with propability.
ie.
  a photo A with tags ["woman", "female", "beauty", "sky"], but the probability is woman: 0.6, femaile: 0.3, beauty: 0.05, sky: 0.05.
Another photo B with tags ['woman', 'sun', 'flower'], but the probability is woman: 0.4, sun: 0.4, flower: 0.2
So when I search 'woman' , I should get [photo A, photo B] since probability of 'woman' in photo A is larger than that of B.
Can you guys give some tips and advice? Any advice is appreciated. Thanks,

**Comment by ankane** [comment]
This is essentially how conversions work. You can try to leverage the [existing conversions interface](https://github.com/ankane/searchkick#keep-getting-better), or dig into the code and do something similar with [advanced search](https://github.com/ankane/searchkick#advanced-search).

**Comment by zealot2007** [comment]
Thanks, @ankane , But in my case, tag probability means correlation with the photo and it will not change as many people search.  Does that mean conversions is not adapt to this?

**Comment by ankane** [comment]
The same approach conversions use should work. I'd dig into the code to see how it works.
