### ISSUE TITLE
multi_field missing in searchkick 2.0.0

### ISSUE THREAD

**Issue by mrjlynch** [ankane/searchkick#796]
I am getting the following error after upgrading to searchkick `2.0.0`. I am using elasticsearch `5.0.0`
```ruby
Searchkick::ImportError:
       {"type"=>"mapper_parsing_exception", "reason"=>"failed to find type parsed [multi_field] for [title]"} on item with id '1'
```

**Comment by mrjlynch** [comment]
I can see this is accounted for in the code: 
```
multi_field =
          if below50
            {
              type: "multi_field",
              fields: dynamic_fields
            }
          else
            dynamic_fields["{name}"].merge(fields: dynamic_fields.except("{name}"))
          end
```

**Comment by ankane** [comment]
It looks like the special cases aren't needed since ES 2 supports that syntax. I've removed it. It seems like Searchkick thinks you're on ES 2. This can happen if you upgrade ES without restarting your web server (since `Searchkick.server_version` gets cached), or could be a potential issue with parsing the server version.

**Comment by cmalpeli** [comment]
@ankane I just started getting this error locally.  I'm on `searchkick 2.3.0` and 5.4 of elastic search.

`Searchkick.server_version` returns `5.4.0`.  Any ideas how to debug this?

**Comment by cmalpeli** [comment]
The date in the field generating the error is a jsonb field:
`{"some_field"=>"some value"}`

I tried a complete reindex as well.

**Comment by cmalpeli** [comment]
Figured it out.  After running the `Model.reindex(async:true)` the new index hadn't been promoted.

Shouldn't that happen automatically?

**Comment by amadeuspagel** [comment]
I get the same error (except with [keyword] instead of [multifield]. What exactly did you do to fix it? I don't know what promoting an index means.
