### ISSUE TITLE
Return records by tag using acts_as_taggable_on

### ISSUE THREAD

**Issue by mrjlynch** [ankane/searchkick#798]
I am using [acts_as_taggable_on](https://github.com/mbleigh/acts-as-taggable-on) and I would like to query by a particular tag. This is normally achieved by: 
```ruby
User.tagged_with('monkey')
```
Or
```ruby
User.includes(:tags).where(tags: {name: 'monkey'})
```

I am struggling to work out a way to do this using Searchkick. 

I am mapping as follows: 
```ruby
def search_data
  attributes.merge(
    tags: tag_list
  )
end
```

**Comment by ankane** [comment]
You can use `tags.map(&:name)` in `search_data` and query with the `where` option.

**Comment by mrjlynch** [comment]
Thanks @ankane, this worked perfectly. I didn't think you could search in that way: 
```ruby
User.search '*', where: {tags: 'monkey'}
```
