### ISSUE TITLE
New feature: Recommendation engine - collaborative filter

### ISSUE THREAD

**Issue by FranciscoCG** [ankane/searchkick#800]
Create an item-item collaborative filter based on users likes (or another metrics like click-thru, rating, etc. ).
For large ecommerce and community sites  boosting searches based on similar user's taste is a must.
https://en.wikipedia.org/wiki/Item-item_collaborative_filtering

This is the classic Amazon's "Users who bought this also bought this others items" but applied to searches (not just individual items)

Similarity matrix can pre-computed and stored into Elastic Search, avoiding Apache Spark complexities.

Here is a similar approach using Solr
http://es.slideshare.net/treygrainger/building-a-real-time-solrpowered-recommendation-engine

**Comment by ankane** [comment]
Hey @FranciscoCG, this would be great if you or someone else wants to give it a shot.

**Comment by jbejar** [comment]
I feel like you would want to use https://qbox.io/blog/building-simple-recommender-systems-for-elasticsearch-1 maybe with aggregations

**Comment by FranciscoCG** [comment]
Thanks @jbejar I've already read this. Its an option. Maybe @ankane can give us some tips about what they do in Instacart ;)

**Comment by Schwad** [comment]
@FranciscoCG is this something you're considering putting a PR together for or just an issue that's being volunteered as an enhancement for anyone who wants to take a stab at it? I agree that it seems like it would be a neat addition btw :)

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
