### ISSUE TITLE
Allow for custom pre and post highlighting tags

### ISSUE THREAD

**Issue by GeorgeKaraszi** [ankane/searchkick#801]
Allow for extra highlighting parameters `pre_tags` and `post_tags` during a search.

Right now the only option available is the `... highlight{ tag: "<strong>" }`. 

Which is terrible since it disallows for custom class additions such as `<strong class='autocomplete'>`.

The result for adding the above looks like: 

`<strong class='autocomplete'>John</strong class='autocomplete'>`

**Comment by ankane** [comment]
Hey @GeorgeKaraszi, it shouldn't be too difficult to detect the tag name to fix the closing tag.

**Comment by ankane** [comment]
Be nicer next time.
