### ISSUE TITLE
Automatically sync tracked conversions

### ISSUE THREAD

**Issue by FranciscoCG** [ankane/searchkick#811]
Is there a way to automatically sync tracked conversions, without reindex the whole model?

I thought to create a model SearchjoySearches and add a: 
` after_commit :reindex_product`

Need to reindex a whole model is expensive, since only a few documents changed when tracking conversions using SearchJoy.

I don't know if report this in Searchjoy or here, please let me know if this is the case to report there instead of here.

**Comment by ankane** [comment]
To make indexing most efficient, you'll want to use bulk operations. I'd recommend an approach that looks like this:

Step 1. Get models with recent conversions (say the past day)

Then, in groups:

Step 2. Bulk retrieve conversions for the group of models (in a single query)
Step 3. Use partial reindexing to only reindex the conversions

**Comment by ankane** [comment]
Here's a rough code example: https://gist.github.com/ankane/09af4746076112fc64f684fcb0d5b6da

**Comment by ankane** [comment]
Added a better example to readme: https://github.com/ankane/searchkick#performant-conversions
