### ISSUE TITLE
Add support for background bulk updates

### ISSUE THREAD

**Issue by ankane** [ankane/searchkick#815]
By queuing ids into Redis

**Comment by MrHubble** [comment]
@ankane 

In the [queuing section](https://github.com/ankane/searchkick#queuing) of the readme, after asking our model to queue the update (`callbacks: :queue`), we set a background job to run the update.

Does this mean we would need to manually queue this job every x minutes to execute the queue? For example, every 10 minutes I run a seperate job:

````rb
#seperate_job.rb
def perform
  Searchkick::ProcessQueueJob.perform_now(class_name: "Product") if Product.search_index.reindex_queue.length > 0
end
````
