### ISSUE TITLE
searchkick ranges only showing items with edge/ endpoints of ranges in the views

### ISSUE THREAD

**Issue by cgude** [ankane/searchkick#816]
Can someone pls point me in the right direction here?  Been trying a numeric range for prices and salaries following the readme and closed/ open issues items closely to construct the ranges properly.  Tried different versions of searchkick also though now Rails 4.2.6 and latest searchkick.  Unlike the other aggs, ranges for me only working for the edge item range when it is a number specified as one of the end points of the range (i.e. if ranges are 10000-20000, 20000-30000 etc., only items which are exactly 10000, 20000 or 30000 will get called in the view when the agg link is clicked on and all other items with numbers in between those range endpoints are ignored and don't show up in the view).  Tried calling .to_s etc on the params but only .to_i and .to_f even give the partial results above.  Otherwise I get an error something like the following error stating number format exception (pasted below).  The main functions of indexing seem to be working fine (show correct count in the range category in the agg view) but when I click on various ranges, does not pass the parameters correctly to the view to show the relevant results that are in that selected range. Pls tell me what I'm doing wrong? Thanks so much. Here is the error I keep getting:

[400] {"error":{"root_cause":[{"type":"number_format_exception","reason":"For input string: "15.0-50.0""}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"jobs_development_20170114194319648","node":"gKOH56YPR5GYONV84-O92A","reason":{"type":"number_format_exception","reason":"For input string: "15.0-50.0""}}]},"status":400}

. . . Tried all different kinds of indexing/ mapping for searchkick including long, double, integer, string but no luck or maybe I've been careless in something.  If someone can shed some light would be grateful.  Thanks for such a great gem to the creator and appreciate this forum!

**Comment by ankane** [comment]
Hey @cgude, it sounds you're trying to pass the string `15.0-50.0` when Elasticsearch expects a number. If you're trying to do a search on the range, you probably need to parse of the range and use `gt` and `lt` before passing it to ES, like:

```ruby
range = "15.0-50.0"
range_start, range_end = range.split("-")
Product.search query, where: {field: {gt: range_start, lt: range_end}}
```

**Comment by cgude** [comment]
Thank you so much this works great.  Have salary mapped as a long in ES/ searchkick and this works well in conditions below.  Not sure what to do in the case where you have a range of x and upwards or below x but I'll figure it out.  Appreciate your help and what a great gem. 
      # conditions[:salary] = params[:salary].to_i if params[:salary].present?
      salary_start, salary_end = params[:salary].split("-") if params[:salary].present?
      conditions[:salary] = {gte: salary_start.to_i, lte: salary_end.to_i}

**Comment by ankane** [comment]
Cool, glad that did it 👍

**Comment by malav1410** [comment]
What if there are multiple range options like "0-1000", "1000-2000", "3000-5000" ? Do i need to add or query in where clause?

**Comment by j-collier** [comment]
@malav1410 You can get the results of all of those queries and then push the results together to display them.
