### ISSUE TITLE
v2.0 upgrade clarification

### ISSUE THREAD

**Issue by oyeanuj** [ankane/searchkick#818]
Hi @ankane! I was trying to upgrade from v1.4.1 to v.2.0.4 and get the following error while accessing a searchable model:

```
ArgumentError - unknown keywords: boost_by:
  searchkick (2.0.4) lib/searchkick/model.rb:9:in `searchkick'
  app/models/concerns/searchable.rb:41:in `block in <module:Searchable>'
  activesupport (4.2.7.1) lib/active_support/concern.rb:120:in `append_features'
  app/models/thing.rb:156:in `<class:Thing>'
  app/models/thing.rb:21:in `<top (required)>'
```

My code is as below:
```rb
class Thing < ActiveRecord::Base
searchkick word_start: [ :name, :description, :synonyms ],
           text_middle: [ :parent ],
           boost_by:   [ :popularity_count ],
           wordnet:    true
 ...
```

I noticed in the code that this was changed in a commit for 2.0 but am not sure what is the recommended way to do the same now?

Also, while going through the documentation, I noticed you have a performance tip that uses `searchable`. I am curious about how it differs in purpose from `search_data`?

Thank you!

**Comment by ankane** [comment]
Hey @oyeanuj, you want to use `boost_by` with the `search_method`:

```ruby
Product.search query, boost_by: [:popularity_count]
```

It was silently being ignored before. `searchable` says what fields in `search_data` can be searched (used in `fields` option). The default is all of the string ones.

**Comment by oyeanuj** [comment]
Firstly, as always, thank you for the quick response :)

Just a few followups:

1. Your suggestion works, and good to know about the past behavior. But do you think it makes sense to also add to `searchkick` method? In my case, it resulted in a slight duplication of code a few times, but also, that is not the end of the world.

2. Thank you for clarification on searchable vs search_data!

3. One more issue. While adding or deleting a model, I see the following error:
```
NoMethodError - undefined method `each_with_object' for nil:NilClass:
  searchkick (2.0.4) lib/searchkick/index.rb:358:in `search_data'
  searchkick (2.0.4) lib/searchkick/index.rb:83:in `block in bulk_index'
  searchkick (2.0.4) lib/searchkick/index.rb:83:in `bulk_index'
  searchkick (2.0.4) lib/searchkick/index.rb:71:in `store'
  searchkick (2.0.4) lib/searchkick/logging.rb:28:in `block in store'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  searchkick (2.0.4) lib/searchkick/logging.rb:27:in `store'
  searchkick (2.0.4) lib/searchkick/index.rb:117:in `reindex_record'
  searchkick (2.0.4) lib/searchkick/model.rb:125:in `reindex'
```

The strange thing is that this model is neither indexed, or nor has a reindex method specified here. It does have associated models indexed.

Any thoughts on what might be going on? Or why is it going in the `search_data` method in this case?

**Comment by ankane** [comment]
1. We could have a `default_search_options` option, but not sure it's needed. You can just as easily create a custom search method on your model to do it.

2. Cool

3. Not sure I follow the situation. It seems to indicate `search_data` is returning `nil` for certain records.

**Comment by oyeanuj** [comment]
Thanks @ankane for your comments. The last question was mistake on my side.

**Comment by strivemag** [comment]
I have problem with this, please give me some explanation if you can @oyeanuj , @ankane  :
``` ruby 
ArgumentError (unknown keywords: autocomplete)
```

My code is:
`app/model/headline.rb`
``` ruby 
class Headline < ApplicationRecord
  searchkick autocomplete: ['title']
end
```
`config/routes.rb`
```ruby
Rails.application.routes.draw do
  resources :headlines do
    collection do
      get :autocomplete
    end
  end
end
```
`app/controllers/headlines_controller.rb`
```ruby
def autocomplete
    render json: Headline.search(params[:query], autocomplete: true, limit: 10).map do |headline|
      { title: headline.title, value: headline.id }
    end
end
```

**Comment by ankane** [comment]
Hey @strivemag, the `autocomplete` option was removed in 2.0. See the [Autocomplete](https://github.com/ankane/searchkick#instant-search--autocomplete) section for what to use instead.

**Comment by strivemag** [comment]
@ankane you made my day, I'm so happy that you replied and helped me, it worked! Thank you!

**Comment by strivemag** [comment]
Hey @ankane , I did it as you told and it worked. But
<img width="1117" alt="screen shot 2017-01-27 at 17 49 04" src="https://cloud.githubusercontent.com/assets/18751336/22369932/f6249e98-e4b8-11e6-885d-6e2594a66af0.png">

But I want to add here things like:
```ruby
<% user.avatar %>
```
![image](https://cloud.githubusercontent.com/assets/18751336/22369993/4324171e-e4b9-11e6-8d69-d9904c5ac696.jpg)
@ankane , @jharding Is there any solution for this?

**Comment by ankane** [comment]
What have you tried so far?
