### ISSUE TITLE
Performance question: OJ and Typhoeus

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#819]
Hello! I'm looking to begin optimizing my ElasticSearch and was digging through the performance section.  Question re: OJ and Typhoeus - does the Searchkick gem automatically use those if the gems are present, or do we need to make any config/code modifications as well.  Thanks!

**Comment by ankane** [comment]
Hey @cmalpeli, adding to them to your Gemfile is all that's needed. I'll make it more clear in the docs. Thanks!
