### ISSUE TITLE
order by datetime object

### ISSUE THREAD

**Issue by MaxDBN** [ankane/searchkick#820]
I'm trying to implement dynamic ordering with searchkick results.

```
    @orders = Order.search(
      where: @filters,
      page: params[:page],
      per_page: 20,
      order: order
    )
```
```
  def order
    return unless Order.count > 0
    column = params[:order_by].present? ? params[:order_by] : "created_at"
    direction = params[:direction].present? ? params[:direction].chomp('ending') : "desc"
    { "#{column}".to_sym => "#{direction}".to_sym }
  end
```

- The _order_by_ parameter can be "created_at" or "departure_datetime".
- The _direction_ parameter is either "ascending" or "descending".

**The results order I get is wrong.**

I thought maybe the [format](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) is wrong so I added this to my model:

```
def search_data
{
    created_at: created_at.strftime("%Y/%m/%d %H:%M:%S),
    departure_datetime: departure_datetime.strftime("%Y/%m/%d %H:%M:%S)
}
end
```

**But the result was even worse...**

Can you please tell me if I'm doing it wrong?

**Comment by ankane** [comment]
Hey @MaxDBN, try `Order.searchkick_index.mapping` to make sure those fields are being mapping correctly. You shouldn't need to use `strftime`.

**Comment by MaxDBN** [comment]
@ankane Thank you for replying.
It shows that created_at & departure_datetime type is date. 
In the database departure_datetime looks like this: "2017-01-25 07:00:00"
created_at looks like this: "2017-01-17 11:35:38.289353"
What should I do? :(

**Comment by ankane** [comment]
Hey @MaxDBN, unfortunately, I don't have the bandwidth to debug app-specific issues. I'd try printing out the result of the `order` method to make sure it's what you expect and use the `debug: true` option to inspect the ES query generated. https://github.com/ankane/searchkick#debugging-queries

If it starts looking like a Searchkick issue, it'd be great if you could add a failing test case to confirm.

**Comment by MaxDBN** [comment]
I suspect that it's a Searchkick issue but I don't think I can write a proper test because for some reason it acts differently on each environment.

Anyway, in case anyone will stumble upon this thread in the future I solved this for myself by using the native sort_by method.

@ankane If you're interested and if you think it can help you I can send the debug output.

**Comment by ankane** [comment]
It's likely a problem with your setup if it's not reproducible in tests.
