### ISSUE TITLE
Will_paginate limit pagination resultset

### ISSUE THREAD

**Issue by FranciscoCG** [ankane/searchkick#822]
Pagination limit not working in will_paginate

apparently 'limit' is overwriting 'per_page'.
Also ':total_entries' doesn't works.

I guess will_paginate gem count all results and paginate according to that. If I do:

`Product.search "*", limit:1000, page: 1, per_page: 100`

then, per_page= 1000 and not 100 as it should be.

At this moment, I just ca do this into views ;(

```
      <% if params[:page].to_i < 100 %>
          <%= will_paginate @feed_items %>
       <% end %>
```

**Comment by ankane** [comment]
Hey @FranciscoCG, `limit` is designed to overwrite `per_page`, as they have the same meaning.

**Comment by FranciscoCG** [comment]
Thanks @ankane, the problems are the number of link produced by will_paginate gem.

Is there a way to limit the result set?

Ex:
p = Product.search "*"
p.count = 1000000
per_page = 10
Total_links = 1000000/10 = 100000 

this is what I need to avoid using will_paginate  :total_entries parameter

In other words; search the whole date but paginate over a limited resultset, i.e the firs 1000 items (1 pages)


`
`Product.search "*", page: page, per_page: per_page
`
 will result in a total of "Total_products/per_page"  links into views, wich cause

**Comment by ankane** [comment]
You'll have to see if there's an option in will_paginate.

**Comment by FranciscoCG** [comment]
Yes, there is ':total_entries'.

Anyway I've solved my use case.  If you like I can create a new issue requesting support for this feature in Searchkick
