### ISSUE TITLE
Should :query be in the list of okay keywords? Problem with body: and pagination.

### ISSUE THREAD

**Issue by jehughes** [ankane/searchkick#824]
Updating to Searchkick 2.1.1 from 1.5.1... ran into an issue with the search call.

This was working:
 ```
 options = {query: @criteria.elasticsearch_query,
              body_options: {sort: searchkick_sort},
              page: params[:page], per_page: 15}
@companies = Company.search options
```
Got the expected results and paging worked fine.

After the gem update, I got the new ArgumentError error. Fair enough, so I updated to:
 ```
 options = {body: {query: @criteria.elasticsearch_query},
              body_options: {sort: searchkick_sort},
              page: params[:page], per_page: 15}
@companies = Company.search options
```
With `body: {}`, the results are correct but the `page: N` and `per_page: N` appear to be ignored.

I temporarily hacked the gem's query.rb file to add `:query` as a valid keyword and it looks like it's back to the old working behavior.

Not sure if `:query` should be a valid keyword or the pagination works differently with the `body: {}` option?

Thanks!

**Comment by ankane** [comment]
Hey @jehughes, you'll need to manually include `size` and `from` in the body, as the `body` option overrides the entire body. The `query` option was removed in 2.0. I've added "Have body play nicely with pagination and other options" to the Searchkick 3 plan. #817

**Comment by jehughes** [comment]
Thanks for clarifying.

+1 for "playing nicely"
