### ISSUE TITLE
Getting different number of records

### ISSUE THREAD

**Issue by Xosmond** [ankane/searchkick#825]
I have a problem getting records.

In this example i have one record in the database and im on test environment. Also i call `Movement.reindex` on "before each" method.

When i call:

`Movement.all # -> Normal way, i get the record always.`

but when i call:

`Movement.search '*" # -> Sometimes I get nothing and sometimes I get the record`

Have you experience something like this?

Update: When i call `Movement.reindex` again after creating the record, now `Movement.search '*" ` works properly, but calling reindex everytime i create a record makes code dirty.

**Comment by ankane** [comment]
Hey @Xosmond, Elasticsearch is "eventually consistent", which is why you're seeing this behavior. You'll need to call `Movement.search_index.refresh` (which `reindex` calls internally) to force a sync.

**Comment by Xosmond** [comment]
Oh i see now. There are a lot of things i don't know, sorry. Thank your for your response.
