### ISSUE TITLE
Will this work with alternative ODM's like Cequel?

### ISSUE THREAD

**Issue by 34code** [ankane/searchkick#828]
Checking to see if Cassandra is supported..

**Comment by ankane** [comment]
Hey @34code, I've been meaning to learn more about Cassandra and figured this was a good opportunity, so I added experimental support on master (with all tests green). A few things to note:

- Everything but inheritance is supported
- Avoid passing `UUID` objects to search data (cast them as strings first with `to_s`)
- Use the `search_id` method to specify a key if you use something other than `id`
- There are no plans to officially support this, so you'll need to fix any issues you encounter

Full example

```ruby
class Product
  include Cequel::Record
  searchkick

  key :subdomain, :text
  column :name, :text

  def search_id
     subdomain
  end
end
```

Cheers!

**Comment by 34code** [comment]
thanks @ankane !! Definitely integrating this.. will let you know if there are any issues and submit any PRs to help add support as needed
