### ISSUE TITLE
Unknown Keywords Fields (Argument Error)

### ISSUE THREAD

**Issue by mastertechrv** [ankane/searchkick#831]
/Users/austinklenk/.rvm/gems/ruby-2.3.1/gems/searchkick-2.1.1/lib/searchkick/model.rb:9:in `searchkick': unknown keywords: fields (ArgumentError)
:fields option doesnt work

I added :fields under the searchkick/model.rb under the list of unkown_keywords = option.keys on line 3 and now it works.

**Comment by ankane** [comment]
Hey @mastertechrv, `fields` is not a valid option for the `searchkick` method. It was silently being ignored before. You'll want to use it with the `Model.search` method.
