### ISSUE TITLE
Showing on autocomplete the number of times it's been searched

### ISSUE THREAD

**Issue by davithss** [ankane/searchkick#833]
Hello guys,

My search is working well with autocomplete and it is recording on searchjoy table as well. 

I'd like to show on autocomplete beside the title how many searches about the title was made.  Any idea how to do that?

Thanks.

**Comment by ankane** [comment]
Hey @davithss, what have you tried?

**Comment by davithss** [comment]
Hi @ankane,
I've tried changing:
```
  def index
    query = params[:title].presence
    @searches = Search.search(query, suggest: true, track: true)
  end

  def autocomplete
    render json: Search.search(params[:term],
                              fields: [{title: :text_start}], # I tried to pass searchjoy results_count here.
                              limit: 10,
                              load: false,
                              misspellings: false).map(&:title).uniq
  end
```

**Comment by davithss** [comment]
@ankane firstly congrats for you and those who helped create this awesome gem.

My alternative for this case was:
```
  def autocomplete
    main_search
    key = @result.map(&:title).uniq
    value = @result.total_count
    render json: ["#{key.first} (#{value} searches)"]
  end

  def main_search
    @result ||= Search.search(params[:term],
                              fields: [{ title: :text_start }],
                              limit: 10,
                              load: false,
                              misspellings: false)
  end
```

**Comment by ankane** [comment]
Hey @davithss, not sure I follow. Are you trying to show the number of results for a given search term, or the number of times it's been searched? The title says the first but the description says the second.

**Comment by davithss** [comment]
Hi @ankane, I'm trying the number of times it's been searched.

**Comment by ankane** [comment]
You can query `Searchjoy::Search` to get the number of times a term has been searched. It'll be the same as any ActiveRecord model.

**Comment by davithss** [comment]
Thank you @ankane. 👍
