### ISSUE TITLE
Enabling async reindex globally

### ISSUE THREAD

**Issue by panasyuk** [ankane/searchkick#834]
Hi there!
Is it possible to enable async reindex globally for each index?
The point is that setting `:async` value to `Searchkick.callbacks_value` using following code:
```ruby
Searchkick.callbacks_value = :async # this method considered to be private`
# or
Searchkick.callbacks(:async)
```
results in assigning some value to thread variable: [(`Thread.current[:searchkick_callbacks_enabled]`)](https://github.com/ankane/searchkick/blob/master/lib/searchkick.rb#L193)

And this causes returning to default value (`nil`) each time application tries to spawn another thread or fork.

For example. If we set up `callbacks_value` to `:async` (in some initializer's code) and then server (say Puma) spawned another 2 workers the we are unable to process reindexing in background due to loss of thread variable's value.

**Comment by ankane** [comment]
Hey @panasyuk, interesting find. I think it's best to set it for each model for now. We could add a global option (which wouldn't be thread-safe) to do this, but I don't see a strong need at the moment.

**Comment by panasyuk** [comment]
@ankane, you see, If we use spree_searchkick gem, then we're trapped in inability of triggering background reindexing for models which are already initialized with searchkick.

**Comment by ankane** [comment]
A few options:

- Try to a place to add it after Puma spawns new threads, but it doesn't look like there's an official hook.
- See if `spree_searchkick` will make it configurable.
- Fork `spree_searchkick` or this gem and add the behavior you want
