### ISSUE TITLE
routing_missing_exception raised when destroying searchkick-enabled instance

### ISSUE THREAD

**Issue by ckuttruff** [ankane/searchkick#835]
Using searchkick version 2.1.1, hitting the following error when destroying an instance that has a searchkick index (with routing enabled).  Do I have something configured incorrectly, because a bit confused about this error or what I have wrong here.  Thanks so much for all your work on this project!

     Searchkick::ImportError:
       {"type"=>"routing_missing_exception", "reason"=>"routing is required for [foo_20170201192813136]/
    [foo]/[1]", "index"=>"foo_20170201192813136"} on item with id '1'

```ruby
# in rspec test (after test index has been created)
foo_instance.destroy!


class Foo

  searchkick(word_start: [:email], callbacks: false, routing: true)
  # fixes test fixtures where proper user is not present
  after_commit :reindex_async, if: -> (cp) { cp.user }

  def search_data
    { email: email,
      user_id: user_id }
  end

  def search_routing
    user_id
  end
```

**Comment by ankane** [comment]
Hey @ckuttruff, my guess is `search_routing` is returning `nil`, which would lead to that error. You should be able to check this with `foo_instance.search_routing`.

**Comment by ckuttruff** [comment]
Thanks so much for the swift response.  I'll close and file this one as \#PEBKAC  :)

Thanks again for all your work on this; such a nice library
