### ISSUE TITLE
Searchkick query without reindexing the data

### ISSUE THREAD

**Issue by Ravi1729** [ankane/searchkick#836]
Hello,

First of all ,thank you very much for this wonderful gem..

In my case, I have data stored in Mongodb and this data is indexed in Elasticsearch through Mongo-connector. How can I query this already indexed data in Elasticsearch  using search kick in my rails application.
If possible can you help to provide any  sample example. I am sorry, I am quite new for this searchkick. :)

Thanks in advance.

**Comment by ankane** [comment]
Hey @Ravi1729, what have you tried?

**Comment by Ravi1729** [comment]
Let's say  my data already indexed in Elasticsearch with name  **bank** .Then I created the model as

`class Post
  searchkick index_name: [bank]
end`

and from the controller I do  **Post.query()**. which returns an error as **Unitialized constant name Post**

Am I doing right?Please help to correct me if I am wrong.

**Comment by ankane** [comment]
It looks like Rails can't find that class (Googling the error is often an effective strategy).

You're probably better off using the Ruby ES client rather than Searchkick if you don't need indexing.
