### ISSUE TITLE
Bulk reindex job wrong parameter

### ISSUE THREAD

**Issue by icecold21** [ankane/searchkick#837]
when doing rake db:migrate, i got
→ bin/rake db:migrate RAILS_ENV=development
rake aborted!
SyntaxError: /Library/Ruby/Gems/2.0.0/gems/searchkick-2.1.1/lib/searchkick/bulk_reindex_job.rb:5: syntax error, unexpected ','
    def perform(class_name:, record_ids: nil, index_name:...

```
module Searchkick
  class BulkReindexJob < ActiveJob::Base
    queue_as :searchkick

    def perform(class_name:, record_ids: nil, index_name: nil, method_name: nil, batch_id: nil, min_id: nil, max_id: nil)

```

Parameter error ?

**Comment by ankane** [comment]
Hey @icecold21, Searchkick needs Ruby 2.1 or greater.
