### ISSUE TITLE
Pagination with size and from

### ISSUE THREAD

**Issue by udiudi** [ankane/searchkick#838]
Hi,

Searchkick: 1.5.0

I have a custom query I'm using for my model, but I can't paginate the results (neither with `page` and `per_page` or with `size` and `from`).

This is my query:
```ruby
@query = {
      size: @per_page,
      from: 0,
      query: {
        bool: {
          must_not: {
            match: {
              user_id: @user.id
            }
          },
          must: [
            {match: { filter1: value1 }},
            {match: { filter2: value2 }}
          ]
        }
      },
      sort: {"created_at": {order: "desc"}}
    }
```

The search itself is like so:
```
Model.search @query
```

but the request to ES still has size=1000 and from=0.

What am I doing wrong?

Thanks!

**Comment by udiudi** [comment]
Ok, so upgrading to 2.1 wasn't as painful as I thought. I upgraded and `size` & `from` work beautifully.

**Comment by ankane** [comment]
For future readers, you need to put it inside the body option.
