### ISSUE TITLE
Exclude, fields options not working

### ISSUE THREAD

**Issue by laltman2** [ankane/searchkick#839]
Have this line in my app:

`Review.search(keyword, exclude: poisonwords, where: {approve: true}, fields: [:title, :comment], misspellings: false)`

With two issues:
1) 'exclude' option seems to just be skipped over, currently does nothing
2) Only searches in 'title' field, results with keywords in the 'comment' field are not being returned.

Hope you can help, thanks!

**Comment by ankane** [comment]
Hey @laltman2, make sure you're on the latest version for `exclude` to work. Use the `debug: true` option to try and figure out why it's not doing what you want with the `comment` field. Searching fields is (very, very) well tested, so it's likely an app-specific issue, not Searchkick.

**Comment by ankane** [comment]
Closing since there was no response.

**Comment by amzurtechnologies** [comment]
Exclude with search keyword "*", not querying. 

results = Interviewer.search "*", where: {status: Interviewer::STATUS_ACCEPT}, exclude: ["Manager"]
  Interviewer Search (34.9ms)  curl http://localhost:9200/interviewers_development/_search?pretty -d '{"query":{"bool":{"must":{"match_all":{}},"filter":[{"term":{"status":"Accept"}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'


Must not condition not added.

results = Interviewer.search "Java, Ruby", where: {status: Interviewer::STATUS_ACCEPT}, exclude: ["Manager"]
  Interviewer Search (91.5ms)  curl http://localhost:9200/interviewers_development/_search?pretty -d '{"query":{"bool":{"must":{"dis_max":{"queries":[{"bool":{"should":[{"match":{"_all":{"query":"Java, Ruby","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"Java, Ruby","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"Java, Ruby","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"Java, Ruby","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}],**"must_not":[{"match_phrase":{"_all":{"query":"Manager","analyzer":"searchkick_search2"}}}]}}]}}**,"filter":[{"term":{"status":"Accept"}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'

**Comment by ankane** [comment]
Hey @amzurtechnologies, think this is a different issue, but fixed here: https://github.com/ankane/searchkick/commit/6ee2d2270a4c474fe289fd5ca45154ca8ad47628

**Comment by amzurtechnologies** [comment]
Thank you @ankane for the quick response.
