### ISSUE TITLE
working with 2 rails apps using same db

### ISSUE THREAD

**Issue by shivamagg** [ankane/searchkick#846]
Hey.

I have two rails apps, first one is the main app where all CRUD takes place on the db and the other is search app which uses searchkick. Both the apps use the same db. 
I am using different apps for the microservices architecture.
Database I am using is neo4j.
As the data modification is taking place in the first app, I am not able to keep index in sync with the database as the search app does not generate any callbacks. 

Can you suggest any way or workaround to resolve this?

Thankyou.

**Comment by ankane** [comment]
Hey @shivamagg, adding Searchkick to both apps should work.

**Comment by shivamagg** [comment]
But that defies the microservices architecture and whole purpose of using another service for search.
Is there a way to trigger callbacks from db instead of the rails app.

**Comment by ankane** [comment]
There is not.
