### ISSUE TITLE
Elasticsearch::Transport::Transport::ServerError

### ISSUE THREAD

**Issue by mrjlynch** [ankane/searchkick#848]
```
An Elasticsearch::Transport::Transport::ServerError occurred in users#update:

 [429] {"error":"Concurrent request limit exceeded. Please consider batching your requests, or contact support@bonsai.io for help.","status":429}
```

Has anyone experienced this error? I will contact Bonsai and report back

**Comment by ankane** [comment]
Hey @mrjlynch, this looks like a limitation with Bonsai.

**Comment by mrjlynch** [comment]
Information about 429 errors can be found [here](https://docs.bonsai.io/docs/troubleshooting-http-error-codes)

Would handling elasticsearch in a background task help solve this issue?

**Comment by ankane** [comment]
If it's due to indexing requests, you'll need to find a way to reduce them. One built-in way would be queuing: https://github.com/ankane/searchkick#queuing
