### ISSUE TITLE
No index found when running in typicode/hotel

### ISSUE THREAD

**Issue by hudadiaz** [ankane/searchkick#849]
When I use [typicode/hotel](https://github.com/typicode/hotel) to start my rails app, I got an error:

`Searchkick::MissingIndexError (Index missing - run MODEL_NAME.reindex)`

This does not happen when I run the app through the terminal normally using `rails s`. I've been told that `hotel` runs in separate environment than my bash, is that the problem?

**Comment by ankane** [comment]
Hey @hudadiaz, it's very likely. This is something you'll need to debug.

**Comment by hudadiaz** [comment]
Could you please give additional info of why you think that's likely the problem?

**Comment by ankane** [comment]
Searchkick uses the environment in the index name. Here's how it's determined: https://github.com/ankane/searchkick/blob/f22aa73d81b2e6d978dbc1cb6526ce82af4df709/lib/searchkick.rb#L68
