### ISSUE TITLE
Use delayed_job for queuing

### ISSUE THREAD

**Issue by jeremylynch** [ankane/searchkick#853]
Thanks for your assistance in #848 @ankane. 

I am currently implementing [Queing](https://github.com/ankane/searchkick#queuing) as per your recommendation. 

However, i notice you only mention redis for this task, could [delayed_job](https://github.com/collectiveidea/delayed_job) be used instead?

**Comment by ankane** [comment]
Hey @jeremylynch, there's a difference between a background job framework like Delayed Job and Searchkick's queuing feature. You can use any background job framework supported by ActiveJob to run `Searchkick::ProcessQueueJob`, but the queuing feature requires Redis.
