### ISSUE TITLE
Field boosters do not return results with special characters (e.g. apostrophes)

### ISSUE THREAD

**Issue by imweijia** [ankane/searchkick#855]
I have many documents with fields that contains special characters such as apostrophes, e.g. an offer with the title `Valentine's Day Special`. 

Without boosters, a search for `Valentines` or `Valentine's` or `Valentine` would return the correct search results. 

However when boosters for those the title field is incorporated, a search of any of the above queries will not return the `Valentine's Day Special` result. 

I've been trying to troubleshoot through the documentation but haven't found a solution yet. Anyone else encountered this problem? Is this a known issue? 

Thanks!

@ankane

**Comment by ankane** [comment]
Hey @imweijia, I added a test case to reproduce. It's passing, so the issue appears to be specific to your app. I'd try doing a full reindex.

**Comment by imweijia** [comment]
@ankane reindexing didn't work. But a workaround with partial word match worked for our case.
```
Offer.search("Valentine's", fields: ["name"], match: :word_middle)
```

**Comment by ankane** [comment]
Thanks for following up. At this point, I don't think it's an issue with Searchkick. Feel free to reproduce with a failing test case or fresh Rails app.
