### ISSUE TITLE
Delay before a record appearing in results after it was indexed? (redirecting to index action after record creation)

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#856]
My `Record` model doesn't use any callback async, its just a simple `searchkick` call after the class declaration. 

In my Records controller, `index` action, instead of using `@records = Record.all`, I'm using `@records = Record.search "*"`

All was fine until I noticed that after creating a new `record` and redirecting to the `index` action (the default is redirect to the `show` action), the recently created record wasn't appearing, but it appeared after a reload. 

I thought it could be some turbolinks caching issue, but no: logs makes very clear that after the `Record Search` finishes, ActiveRecord is NOT loading that recently-created Record ID (it does  after a page reload, so it's not a front-end issue). 

Also, I compared the `curl` in both (after the redirect and after the page reload) and they are the same. 

This is the code in the controller:

```
    if @record.save
        redirect_to records_path
```

Debugging, I added `binding.pry`after the `@records = Record.all` line in the `index` action and found out the following: if I just type @records (to get the result of the search already performed in the previous line), I don't get the new record in the results. But if I manually re-run `@records = Record.search "*"` in the pry console (even before exiting), the new record is returned by searchkick. 

I'm pretty sure about this: `@records.total_count` returns `n`, and as soon as I manually run `@records = Record.search "*"` followed by `@records.total_count` I get n+1. 

In Rails Console it's pretty clear that record was stored and indexed before hitting the `binding.pry` line, since it returns `Record Store (66.2ms)  {"id":21}`; but that `id` doesn't appear in the results in `@records`,  only after I manually run `@records = Record.search "*"`

Is there a delay? Is this normal? I couldn't find anything searching in the issues. 

So using `Record.search "*"` as an alternative to `Record.all` is not really an option after a form submit creating the record?

**Comment by ankane** [comment]
Hey @feliperaul, Elasticsearch is "eventually consistent", which is why the record isn't showing up right away. You can use `Record.search_index.refresh` after the update to force Elasticsearch to flush the data.

**Comment by feliperaul** [comment]
@ankane Thanks ankane. Maybe that's something to consider to add to the readme, even if deep down :)

**Comment by ankane** [comment]
Added. Let me know if it makes sense.
