### ISSUE TITLE
Getting nested hits' ids

### ISSUE THREAD

**Issue by mmahalwy** [ankane/searchkick#857]
If I have model `Verse` which has_many `Translation`s. When indexing:

```
def search_data
    attributes.merge(translations: translations, words: words)
  end
```

How do I get the translation id that caused the hit when searching?

**Comment by ankane** [comment]
Hey @mmahalwy, Searchkick doesn't have any specific features for this. I'd look up how to do it with Elasticsearch and use [Advanced Search](https://github.com/ankane/searchkick#advanced-search).

**Comment by mmahalwy** [comment]
Awesome. Thanks @ankane
