### ISSUE TITLE
Tips for delayed reindexing when performing a bulk import using activerecord-import gem

### ISSUE THREAD

**Issue by paddingtonsbear** [ankane/searchkick#858]
Hey @ankane 

I currently have the following setup
```ruby
# book.rb
class Book < ApplicationRecord
  searchkick(
    callbacks: :async
  )
end

# rake task
# book_import.rb 
books = []
10.times do |i| 
  books << Book.new(:name => "book #{i}")
end
Book.import books
```
and I am looking to delay reindexing till all `books` have been imported and then perform bulk reindex. 

My current solution seems to queue an individual `reindex` background job for each imported `book`. I was wondering if you had any tips on a better approach

**Comment by ankane** [comment]
Hey @paddingtonsbear, you can use bulk callbacks, like:

```ruby
Searchkick.callbacks(:bulk) do
  # do inserts here
end
```

**Comment by paddingtonsbear** [comment]
Thanks
