### ISSUE TITLE
I can't get price ranges on aggregations to work in my view

### ISSUE THREAD

**Issue by basplas** [ankane/searchkick#860]
I'm using `Searchkick` in my `Rails 5` application, without a search-bar but based on `aggregations`. I've tried to use the `ranges` example for a price aggregation, based on the example on [Searchkick's Github page][1]. The clickable `ranges` are nicely shown with the corresponding `doc-count`. But when I click the ranges, I get the following error:

    [400] {"error":{"root_cause":    [{"type":"number_format_exception","reason":"For input string: \"5000.0-*\""}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"projects_development_20170226144434924","node":"MYELJXFWRkK9q-a42FIfug","reason":{"type":"number_format_exception","reason":"For input string: \"5000.0-*\""}}]},"status":400}

Here's my model:

    class Project < ApplicationRecord
      searchkick

      belongs_to :user
      has_many :photos, as: :photoable, dependent: :destroy
      has_and_belongs_to_many :categories
      has_one :photo, as: :photoable

      def search_data
        {
          name: name,
          designer_cost: designer_cost,
          category_name: categories.map(&:name)
        }
      end
    end

Here's my controller:

        search = "*"
        conditions = {}
        conditions[:category_name] = params[:category_name] if params[:category_name].present?
        conditions[:designer_cost] = params[:designer_cost] if params[:designer_cost].present?
        designer_cost_ranges = [{to: 1000}, {from: 1000, to: 5000}, {from: 5000}]

        @projects = Project.search search, where: conditions, aggs: {category_name: {}, designer_cost: {ranges: designer_cost_ranges}}

Here's my view:

    
            <% if @projects.aggs["designer_cost"].present? %>
              <% if @projects.aggs["designer_cost"]["buckets"].count > 0 %>
                <div class="col-md-4">
                  <ul  style="list-style-type:none">
                    <li>
                      <h4>Filter by Budget</h4>
                    </li>

                    <li>
                      <%= link_to "All", need_designer_path, class: "nav-item" %>
                    </li>
                    <% @projects.aggs["designer_cost"]["buckets"].each do |filter| %>
                        <li>
                          <%= link_to "/need_designer?designer_cost=#{filter['key']}", :class => "nav-item" do %>
                              <%= filter["key"] %>
                              <span class="badge">
                              (<%= filter["doc_count"] %>)
                            </span>
                          <% end %>
                        </li>

                    <% end %>
                  </ul>
                </div>
              <% end %>
            <% end %>

Any thoughts on what's going wrong?

  [1]: https://github.com/ankane/searchkick#aggregations

**Comment by ankane** [comment]
Hey @basplas, see #816.

**Comment by basplas** [comment]
Thank you for answering @ankane, but I've tried that answer for my situation and it gives me a list with singel buckets.
What I don't understand is that I literally used the example for Aggregation price ranges from the Git - Readme and that I'm not able to get that to work.
Here's the git-example:
`price_ranges = [{to: 20}, {from: 20, to: 50}, {from: 50}]`
`Product.search "*", aggs: {price: {ranges: price_ranges}}`

**Comment by ankane** [comment]
The problem is with the `where` clause, not the aggs.

**Comment by basplas** [comment]
Very cool! My middle range is working now. Is there a trick to also show the range with an open end?

**Comment by ankane** [comment]
You should be able to figure that one out :)

**Comment by basplas** [comment]
Hahaha, I agree. Thanks!
