### ISSUE TITLE
Disabling Searchkick in specs that don't need it

### ISSUE THREAD

**Issue by tzusman** [ankane/searchkick#862]
The [bullet](https://github.com/flyerhzm/bullet) gem, for example, has this ability:

```
config.around(:each, bullet: true) do |example|
  Bullet.enable = true
  example.run
  Bullet.enable = false
end
```

This is exactly what I'd like to do with Searchkick since most of my specs don't rely on indexed data, and therefore there are a lot of extra writes going to Elasticsearch.

Couldn't find a global enable/disable flag in Searchkick though.

**Comment by ankane** [comment]
Hey @tzusman, you can do:

```ruby
Searchkick.enable_callbacks
# and
Searchkick.disable_callbacks
```

I'll update the test section to reflect this, since it's a good pattern.
