### ISSUE TITLE
Possible bug when querying an index with nested fields

### ISSUE THREAD

**Issue by cheeseandpepper** [ankane/searchkick#864]
I'm having an issue when searching for partial words within an index containing documents with nested fields.  I am able to get hits using CURL, and using the Elasticsearch Gem, but not using Searchkick.

To illustrate this here's the original and 2 additional tests I added locally to the Searchkick 2.1.1 gem.

```
# nested

  def test_nested_search
    store [{name: "Product A", aisle: {"id" => 1, "name" => "Frozen"}}], Speaker
    assert_search "frozen", ["Product A"], {fields: ["aisle.name"]}, Speaker
  end

  def test_nested_search_2
    store [{name: "Product Another Words", aisle: {"id" => 1, "name" => "Frozen"}}], Speaker
    assert_search "Another", ["Product Another Words"], {}, Speaker
  end

  def test_nested_search_3
    store [{name: "Product Another Words", aisle: {"id" => 1, "name" => "Frozen"}}], Speaker
    assert_search "Another Wo", ["Product Another Words"], {}, Speaker
  end
```

The first test is part of the gem.  `test_nested_search_2` passes, while `test_nested_search_3` fails.

For reference, you can see the relevant code below:

Order Model
https://gist.github.com/cheeseandpepper/8363d6a89d9b3da8b00794819d21f412

Mapping
https://gist.github.com/cheeseandpepper/79edd6f346a962a70e12f9984b279155

I'm wondering if there's an issue with my setup, or if there's a bug. Any help is appreciated. Thanks!

**Comment by ankane** [comment]
Hey @cheeseandpepper, see the "Partial Matches" section of the readme.

**Comment by cheeseandpepper** [comment]
Thanks @ankane. We've poured over the documentation and have tried all the matching options, but still cannot match our searches based on the examples provided above. I'll continue to investigate this issue from my end.

**Comment by ankane** [comment]
Example 3 above isn't using partial matching, which is why the test fails.
