### ISSUE TITLE
Regexp filter does not get all items

### ISSUE THREAD

**Issue by phanhaiquang** [ankane/searchkick#867]
Hi,

I have many posts, and I am sure that many of their message contain "a" character.
However, regexp search gives me just a few.

If I use `Post.search("a", load: false).count`, it shows me correct number.
Could you please take a look below code to see if there is anything wrong ?

`Post.search(where: {message: /.*a.*/}, load: false).count`

>   Post Search (38.4ms)  curl ip-addr:443/posts_production/_search?pretty -d '{"query":{"bool":{"must":{"match_all":{}},"filter":[{"regexp":{"message":{"value":".*a.*"}}}]}},"size":1000,"from":0,"timeout":"11s"}'
>  => 3

Version: 2.0.4
Elastic Search provider/version: AWS/5.1

P/S: I replaced `a` with many regexp keyword including `i` modifier, but there is no luck.

Thanks,

**Comment by ankane** [comment]
Hey @phanhaiquang, Elasticsearch doesn't have support for case-insensitive regular expressions. You'll need to use `/.*[aA].*/`.

**Comment by phanhaiquang** [comment]
Thanks a lot for prompt response @ankane 

I tried `/.*[aA].*/`, the result is still the same. I mean, I got only 3 posts.
I tried to use `curl` directly on command line, and also got 3 posts. It means that searchkick works correctly.

But if I got all posts from ES, then one by one match it with `[aA]` by ruby code, it shows me a lot more number of posts. And this number is very similar with the way I run `Post.search("a", load: false)`

It seems that I am misunderstanding something relates to the way the ES works. So that this issue is not related to your great gem, but if you have any tip/doc/spec to help me to understand reason why ES does not return many posts that its message contain [aA] (in field `message` like this case), please point me to!

Thanks a lot for your work !
