### ISSUE TITLE
Support for will_paginate :total_entries option

### ISSUE THREAD

**Issue by FranciscoCG** [ankane/searchkick#868]
Hi Ankane,

I cant't figure out how limit the result set without this option.
Also over 10_000 documents, this will cause links pointing to pages the will return ES errors, due to default limit.

I tried converting searchkick object to to ActiveRecord object and will_paginate works but the solution isn't efficient.

I created a huge array of ids from searchkick object, the create AR object like this:

```
Post.search("*", limit: 10000)
posts_ids = @searchkick_items.map{|p| p.id }
@posts = Post.where(id: posts_ids).paginate(page: params[:page], per_page: 100)
```
Then in views:
`<%= will_paginate @posts %>
`
This solution works but its bad practice since I'm creating a 10_000 elements array (posts_ids)

What we need is:
Post.search("", page: 1, per_page: 10, total_entries: 10000)

Any plans to adding support for this?

https://github.com/ankane/searchkick/issues/725
> When I use Post.search("", page: 1, per_page: 10), it works fine and yields 10 results per page. However, with 10_000 documents, the result will yield 1_000 page links, which is too much. So, I would like to control that number. I can do this through will_paginates :total_entries option. For example, Post.all.paginate(page: 1, per_page: 10, total_entries: 1000) will give me 100 pages, which is acceptable for me. But, unfortunately when I do this with Searchkick: Post.search("", page: 1, per_page: 10, total_entries: 1000), it does not override the total_entries count and gives me 1000 pages. Basically, per_page and the page options work, but why not total_entries? Is there any way I could retrieve 100 pages?

**Comment by ankane** [comment]
Hey @FranciscoCG, can you explain more about what `total_entries` does and how it relates to the other pagination options?

**Comment by FranciscoCG** [comment]
Hey @ankane sure:

`total_entries` As I understand, limit , overwrite,  the number of items over which it will paginate.

Post.count = 10000
Post.all.paginate(page: 1, per_page: 10) will give me 1000 pages
Post.all.paginate(page: 1, per_page: 10, total_entries: 1000) will give me 100 pages


From:
https://github.com/mislav/will_paginate/blob/5d92ee219d4a941a18c0de8a24a11973548495ac/lib/will_paginate/array.rb

  ```
def paginate(options = {})
    page     = options[:page] || 1
    per_page = options[:per_page] || WillPaginate.per_page
    total    = options[:total_entries] || self.length

    WillPaginate::Collection.create(page, per_page, total) do |pager|
      pager.replace self[pager.offset, pager.per_page].to_a
    end
  end

```
https://github.com/mislav/will_paginate/blob/master/lib/will_paginate/collection.rb
```
    def total_pages
      total_entries.zero? ? 1 : (total_entries / per_page.to_f).ceil
    end
```

https://github.com/mislav/will_paginate/blob/5d92ee219d4a941a18c0de8a24a11973548495ac/lib/will_paginate/active_record.rb
```
    module Pagination
      def paginate(options)
        options  = options.dup
        pagenum  = options.fetch(:page) { raise ArgumentError, ":page parameter required" }
        options.delete(:page)
        per_page = options.delete(:per_page) || self.per_page
        total    = options.delete(:total_entries)
...
```

**Comment by ankane** [comment]
Happy to add to the gem if someone wants to create a PR w/ tests.

**Comment by FranciscoCG** [comment]
Thanks @ankane unfortunately I'm newbie to create a PR.

How are the other people deal with this? Or I'm the only one that deals with big numbers?

#725 @kench90  mentioned that solved that converting Searchkick object to Active Record object, but I can't figure out how to do that.

Is there anything I can do in the meantime?

Thanks in advance.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
