### ISSUE TITLE
Support for `relation` parameter when doing range queries over range fields

### ISSUE THREAD

**Issue by dennmart** [ankane/searchkick#869]
When performing a range query on a range datatype (for example, like a `date_range`), there's an additional [`relation` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html#CO173-6) that can be passed to the query. By default, if this parameter is not specified, it will use the "within" option.

I'm finding myself needing to set this parameter to "contains", but this can't currently be done on the gem, as far as I can tell by reading the code. It would be nice to be able to search a range and set additional options to the range as specified in the documentation link above.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
