### ISSUE TITLE
Shared ActiveRecord database and searchkick index between Admin/User app and Model.reindex

### ISSUE THREAD

**Issue by hovancik** [ankane/searchkick#872]
Hi, 
my scenario is like this: 

- 2 apps with shared ActiveRecord DB: User app and Admin app (running separately). 
- I want my user to search on Product on User app (changes to products done in Admin app)

I've set it up this way (both admin and web): 

```
  searchkick callbacks: :async, index_name: -> { "#{name.tableize}-#{I18n.locale}-#{Rails.application.config.app_env}" },
             word_start: [:name, :description, :composition], highlight: [:name]
```

Idea being the index gets updated when Admin makes changes. 

I am getting errors, thought: 

```
Searchkick::InvalidQueryError at /products/search/xxx
=====================================================

> [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"[match] analyzer [searchkick_word_search] not found","index_uuid":"jmuzw5BDR7OK_mv622o_bg","index":"products-cs-development"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"products-cs-development","node":"w_9GUyYCQcCr43STTI-hIQ","reason":{"type":"query_shard_exception","reason":"[match] analyzer [searchkick_word_search] not found","index_uuid":"jmuzw5BDR7OK_mv622o_bg","index":"products-cs-development"}}],"caused_by":{"type":"query_shard_exception","reason":"[match] analyzer [searchkick_word_search] not found","index_uuid":"jmuzw5BDR7OK_mv622o_bg","index":"products-cs-development"}},"status":400}
```

I guess it's because of the fact that Product.reindex was called on Admin, not the User app? 

Is there something I can do?

**Comment by hovancik** [comment]
I have found one more thing: If I run first `Product.reindex` on my User app, and the do subsequent updates via `callbacks: :async`on Admin App, it seems to work. But no idea how reliable that would be, and it doesn't seems to me like a good solution.

**Comment by ankane** [comment]
Hey @hovancik, the way you describe above should lead to reliable indexing. You need to call `Product.reindex` in either the user or admin app at least once to prep the index and prevent the error in your first message.

**Comment by hovancik** [comment]
Thanks, you are right. I must have done some mistake when testing it for the first time. Retried again with new index and it works.
