### ISSUE TITLE
Elasticsearch multi-search minimum-should-match

### ISSUE THREAD

**Issue by seemalakishore** [ankane/searchkick#873]
@ankane 
How can I use multiple queries, in single search call. 

Ex: I have a Post model, which description field indexed. 
If I search for "home, town, city", I would get results of posts which has all three words matched. 
When I use `Post.search "home, town, city", fields["description"]` 

How can I search the 3 words and get the results if at least 2 are match or at least any 1 is matched out of the 3 words.

If I would like to get series results in iteration like initial results match all 3 words, then matching at least any 2 words then final resultset to match at least 1 word

**Comment by ankane** [comment]
Hey @seemalakishore, try the `operator: "or"` option. https://github.com/ankane/searchkick#partial-matches

**Comment by seemalakishore** [comment]
@ankane `operator: "or"` can be used to match any one in the list. That means matching 1 word is sufficient. If I want to match at least 2 or 3 words. If I say at least 2, then the search result should have minimum match of 2 words out of given search terms. 
Here the requirement is if search is text search with 5 words, out of which any 3 can be matched or any 4 can be matched. 

Or we can say how do we achieve minimum should match concept of elasticsearch using searchkick.
[https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html](url)

**Comment by ankane** [comment]
Hey @seemalakishore, there's no special way to do this with Searchkick. You can figure out how to do it with Elasticsearch and use [Advanced Search](https://github.com/ankane/searchkick#advanced-search). As a heads up, what you're looking for is a bit different than Elasticsearch's `minimum_should_match` concept.
