### ISSUE TITLE
Exclude does not work with `match: :word_start`

### ISSUE THREAD

**Issue by tomchipchase** [ankane/searchkick#874]
We've discovered an issue with the excludes when we were attempting to improve our search results.

It seems that `exclude` and `match: :word_start` don't work together as I would expect.

In our case, we want to exclude `eggplant` from our search results if the user is searching for `egg`. However, adding `exclude: ["eggplant"]` from the search also excludes the eggs, and no results are returned.

Here is a failing spec that shows this:

```ruby
def test_egg
  store_names ["eggs", "eggplant"]
  assert_search "egg", ["eggs"], exclude: ["eggplant"], match: :word_start
end
```

```
  1) Failure:
MatchTest#test_egg [/home/tom/src/searchkick/test/match_test.rb:183]:
Expected: ["eggs"]
  Actual: []
```

**Comment by ankane** [comment]
Hey @tomchipchase, thanks for the detailed report 💯  Fixed on master.

**Comment by tomchipchase** [comment]
Great! Thanks for the quick fix!
