### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by alfie-max** [ankane/searchkick#878]
The result i get are not what i expect. 
If `JOURNESI` gave me 2 results, shouldn't `JOURNES` give me atleast that?

![screen shot 2017-03-24 at 14 31 52](https://cloud.githubusercontent.com/assets/8247590/24287760/ed59dc60-10a0-11e7-90c7-cd9ddf8380bd.png)

**Comment by ankane** [comment]
Hey @alfie-max, see the "Partial Matches" section of the readme.

**Comment by andy-harper** [comment]
@ankane 

```

**Comment by feliperaul** [comment]
@andy-harper Did you reindex?

**Comment by alfie-max** [comment]
yea, i did reindex. I checked this in another app and there too i have the same issues.

**Comment by ankane** [comment]
@alfie-max you must also specify `match: :word_start` when you search.
