### ISSUE TITLE
Query results not as expected after upgrading to the latest searchkick version

### ISSUE THREAD

**Issue by sandeepgoud** [ankane/searchkick#880]
Earlier I was using elasticsearch 1.X  and searchkick 0.8.7 which is working well and good. I have upgraded elasticsearch 5 and  searchkick 2.1.1. After upgrading to latest versions, search results not showing properly. If I remove analyzer  and triggering elasticsearch directly I am getting results properly. 

Could you please help out this.

Thanks in advance.

**Comment by ankane** [comment]
Hey @sandeepgoud, have you tried everything in the debugging section? https://github.com/ankane/searchkick#debugging-queries

If so, can you paste the commands and output?

**Comment by sandeepgoud** [comment]
@ankane Thanks for the quick response.

Please find the content structure and commands which i have tried.

This is my Product model:
class Product < ActiveRecord::Base
searchkick callbacks: :async, batch_size: 100
def search_data()
    {
      id: id,
      title: title,
      status: status,
      created_at: created_at,
      tags_name: tags.map(&:name),
    }
  end
end


This is my product controller

class ProductsController < ApplicationController
query = Product.search(search_params[:query],
      offset: offset,
      page: params[:page],
      per_page: params[:per_page] || PER_PAGE,
      operator: "or",
      fields:['title^20', 'tags_name'],
      where: filters,
      order: order_criteria,
      query: random_score,
      load: false,
      execute: false)
    query.execute
end


Tokenizer: Product.search_index.tokens("Emotional Intelligence", analyzer: "searchkick_index")
Result: ["emot", "emotionalintellig", "intellig"]

Tokenizer: Product.search_index.tokens("Emotional Intelligence", analyzer: "searchkick_search")
Result: ["emotionalintellig"]

Tokenizer: Product.search_index.tokens("Emotional Intelligence", analyzer: "searchkick_search2")
Result: ["emot", "intellig"]

When i did curl to elastic search, I did'nt find the same tokens as above.

curl http://localhost:9200/products_development/product/1/_termvectors?fields=tags_name
{"_index":"products_development_20170317171058156","_type":"product","_id":"1","_version":151,"found":true,"took":0,"term_vectors":{"tags_name":{"field_statistics":{"sum_doc_freq":2795,"doc_count":424,"sum_ttf":-1},"terms":{"Emotional Intelligence":{"term_freq":1,"tokens":[{"position":5,"start_offset":42,"end_offset":64}]},"Trying":{"term_freq":1,"tokens":[{"position":4,"start_offset":35,"end_offset":41}]},"cycle":{"term_freq":1,"tokens":[{"position":3,"start_offset":29,"end_offset":34}]},"growing up":{"term_freq":1,"tokens":[{"position":1,"start_offset":9,"end_offset":19}]},"learning":{"term_freq":1,"tokens":[{"position":2,"start_offset":20,"end_offset":28}]},"siblings":{"term_freq":1,"tokens":[{"position":0,"start_offset":0,"end_offset":8}]}}}}}

Please let me know if am missing something.

**Comment by ankane** [comment]
Hey @sandeepgoud, I don't think I'll be able to debug this remotely. One thing I notice is it doesn't look like you're on 2.0+ from the code sample as the `query` option will throw an error.

If you can add a failing test case, I'm happy to look into it more, but going to close for now.

**Comment by kuchlous** [comment]
@ankane , one issue we do not understand is that the term vectors seem to not have the analyzed tokens. The termvector has "Emotional Intelligence" as the term but shouldn't it have ["emot", "emotionalintellig", "intellig"]?
