### ISSUE TITLE
Mutual exclusivity of body queries and other search options.

### ISSUE THREAD

**Issue by tumes** [ankane/searchkick#883]
Hey there! I'm currently working on upgrading to searchkick 2.0+, and I've run into a bit of a hiccup. Disclaimer: I know that the issue may be that I just need to bite the bullet and refactor my searching code, but I wanted to make sure that I'm not missing anything before I make that decision.

The app I'm working on has some code to generate the hash of options for the `search` method that looks like this:

```
incoming_query = "status:pending country:us"
search_query = {
  query: { query_string: { query: incoming_query, default_operator: 'AND' } },
  where: (...),
  includes: [:...],
  order: {...}
}
```

This worked in 1.5.1 because the `query` option was still supported, and did not short-circuit the option handling logic. I attempted to use the new `body` and `body_options` functionality, but from looking at the code, it appears as though `body_options` only supports options which don't require any handling.

So I guess I'm wondering:
1) Was the intention to have raw searches and complex options be mutually exclusive?
2) Am I completely missing some functionality that'll accomplish a search in something like this form?
3) Should I just be restructuring my input to the search method to not rely on something like `query_string`?

I'm all good if the solution is ultimately number 3, I just wanted to run this by you before taking the plunge if I'm just missing something obvious.

Thanks for your attention and for working on the gem!

**Comment by ankane** [comment]
Hey @tumes, that was the intention. You'll most likely need to use `query_string` if you want to allow the user to specify multiple fields and terms in the search box. It should be fairly straightforward to modify the query generated by Searchkick as outlined in the Advanced Search section.

```ruby
Product.search("*", other_options) do |body|
  body[...] = {query_string: ...}
end
```

https://github.com/ankane/searchkick#advanced-search
