### ISSUE TITLE
How to use wordnet on bonsai and heroku

### ISSUE THREAD

**Issue by jeremylynch** [ankane/searchkick#885]
The documentation discusses downloading wordnet and moving `wn_s.pl` to the `/var/lib`. 

However, how can this be achieved on `heroku` using `bonsai elasticsearch`? 

The only resource I have found discussing this is [this one](https://docs.bonsai.io/docs/using-wordnet-with-bonsai). 

The `wordnet_path` is set at `"/var/lib/wn_s.pl"` by default. Is it possible to change this to a directory within rails? ie within `public` or `tmp`?

**Comment by rst0git** [comment]
Hi jeremylynch,

The wordnet_path seem to be hard-coded [here](https://github.com/ankane/searchkick/blob/f22aa73d81b2e6d978dbc1cb6526ce82af4df709/lib/searchkick.rb#L44)

You would be able to specify this path if the line
```
self.wordnet_path = "/var/lib/wn_s.pl"
```
is changed to something like:
```
elf.wordnet_path = ENV['WORDNET_PATH'] ? ENV['WORDNET_PATH'] : "/var/lib/wn_s.pl"
```

**Comment by ankane** [comment]
Thanks for helping out @rst0git 👍
