### ISSUE TITLE
Marshalling results is broken since 2.0.1

### ISSUE THREAD

**Issue by sharshenov** [ankane/searchkick#887]
Singleton methods defined on search results are breaking marshalling:
https://github.com/ankane/searchkick/blob/v2.0.1/lib/searchkick/results.rb#L38
https://github.com/ankane/searchkick/blob/v2.0.1/lib/searchkick/results.rb#L45

```ruby
Marshal.dump(Product.search("*", limit: 3).results)
# causes TypeError: singleton can't be dumped

# That is why rails caching is broken now
Rails.cache.fetch("some_key") { Product.search("*", limit: 3).results }
# causes TypeError: singleton can't be dumped
```

Defining `Product#marshal_dump` and `Product#marshal_load` methods explicitly can make marshalling work again but it feels like a workaround.

```ruby
class Product < ActiveRecord::Base
  searchkick

  def marshal_dump
    attributes
  end

  def marshal_load(data)
    initialize(data)
  end
end
```

**Comment by ankane** [comment]
On master, you can now do:

```ruby
Product.search "*", load: {dumpable: true}
```

I've also made a note to revisit the singleton methods in Searchkick 3.0.

**Comment by ankane** [comment]
Also, big thanks for the detailed report 👍

**Comment by sharshenov** [comment]
Thank you!
