### ISSUE TITLE
Turn off Async for Tests

### ISSUE THREAD

**Issue by chevinbrown** [ankane/searchkick#888]
We run into many issues with async reindexing not completing before some assertions are called. Rather than wrapping blocks with `perform_enqueued_jobs`, it would be nice to be able to turn off async reindexing for the test suite.

**Comment by ankane** [comment]
Hey @chevinbrown, I'd recommend setting background jobs to run inline in tests. ActiveJob has an `:inline` adapter and Sidekick has `Sidekiq::Testing.inline!`.

**Comment by chevinbrown** [comment]
@ankane, that's fine with me! Have you considered any test-helpers, or would you recommend sticking to the normal methods? I'm happy to close per your recommendation. Thanks!

**Comment by ankane** [comment]
In my experience, normal methods are all I've needed.
