### ISSUE TITLE
Is there a "search_data" method for fields to store but not index?

### ISSUE THREAD

**Issue by Spazer9** [ankane/searchkick#890]
I'm trying to avoid having to specifiy an extensive/ugly mappings hash but at the same time be able to specify two arrays of fields.

First one would be the "search_data" which is fields to store AND index. I'd also want to store some fields like a "uuid" but I really don't want to index it.

Anyway to do this?

**Comment by VvanGemert** [comment]
I would like to know the same. I don't get why there is filterable and searchable, but everything is searchable in search_data. And search_data seems to overwrite filterable and searchable.

**Comment by ankane** [comment]
Hey @Spazer9, you can use `searchable` and `filterable` for this.

@VvanGemert if those option didn't work for you, you may have forgotten to reindex after setting them.

**Comment by ankane** [comment]
Cleaning up stale issues
