### ISSUE TITLE
Add db scopes to :async ReindexV2Job

### ISSUE THREAD

**Issue by esiegel** [ankane/searchkick#893]
It would be nice if the library didn't assume a record will be found using the default scope.  Specifically this line in `ReindexV2Job` causes an issue.

```ruby
model.find(id)
```

We are using the ruby library [paranoia](https://github.com/rubysherpas/paranoia), which soft destroys records such that the active record default scope won't include that record.  We would need to query the model like so:

```ruby
model.with_deleted.find(id)
```

Maybe we can reuse searchkick's `search_import` scope or maybe add another.  Or the job could be written in a way to allow overriding.

**Comment by ankane** [comment]
Hey @esiegel, you can use the should_index? method to prevent a record from being indexed. https://github.com/ankane/searchkick#indexing

**Comment by esiegel** [comment]
@ankane I actually **do** want to index the record, and the default implementation of `should_index` is fine as it indexes everything.  I need to be able to search ElasticSearch for these soft destroyed records.

The issue is that during `:async` reindexing the job cannot [find](https://github.com/ankane/searchkick/blob/master/lib/searchkick/reindex_v2_job.rb#L16) the soft destroyed record by id, since the default scope won't include it.  Because of this the job [removes](https://github.com/ankane/searchkick/blob/master/lib/searchkick/reindex_v2_job.rb#L30) the record from Esearch.

Hopefully that makes more sense.

**Comment by ankane** [comment]
Ah, gotcha. It probably makes sense to use `unscoped`, but this would be a breaking change, so best to add it as an option for now.

**Comment by esiegel** [comment]
Sounds good to me

**Comment by afunction** [comment]
My problem is same as @esiegel, I use soft_deletion on my project, and theses deleted records can be searched on administrator panel, I change method `self.load_records` on file `lib/searchkick.rb`:

Can I do that? any problem will happened?

```
# private
  def self.load_records(records, ids)
    records =
      if records.respond_to?(:primary_key)
        # ActiveRecord (ADD unscoped)
        records.unscoped.where(records.primary_key => ids) if records.primary_key
      elsif records.respond_to?(:queryable)
        # Mongoid 3+
        records.queryable.for_ids(ids)
      elsif records.respond_to?(:unscoped) && :id.respond_to?(:in)
        # Nobrainer
        records.unscoped.where(:id.in => ids)
      elsif records.respond_to?(:key_column_names)
        records.where(records.key_column_names.first => ids)
      end

    raise Searchkick::Error, "Not sure how to load records" if !records

    records
  end
```

**Comment by Schwad** [comment]
From Rails Best Practices: https://rails-bestpractices.com/posts/2013/06/15/default_scope-is-evil/

However that said, we use `paranoia` as well.

**Comment by esiegel** [comment]
Opened up a pull request which I should have done ages ago, though i had found my own workaround.  Still need to write some tests.  Hopefully this is good for all and backwards compatible.

**Comment by esiegel** [comment]
Closing issue as flag has been added to master

**Comment by ankane** [comment]
Just fyi, Searchkick 5 (just released) now has an `unscope` option to allow you to index and search records filtered by the default scope. https://github.com/ankane/searchkick/#default-scopes
