### ISSUE TITLE
Version incompatibility!

### ISSUE THREAD

**Issue by mistrikushal** [ankane/searchkick#895]
I am using CI to build and test the app. CI config for searchkick and Elasticsearch are, 

`Elasticsearch 2.4.3`
`Searchkick 2.2.0`

It seems they're compatible with one another. even locally it is working fine but at CI it is saying something like,
`Searchkick::UnsupportedVersionError` `This version of Searchkick requires Elasticsearch 2 or greater`

Is anything missing here ? It was working fine few days back and I am sure no config have been changed.

**Comment by ankane** [comment]
What's the output of `Searchkick.client.info` on the test server?

**Comment by mistrikushal** [comment]
needed to remove elasticsearch from `machine -> services` in circle.yml
