### ISSUE TITLE
multiple elasticsearch servers in same rails app

### ISSUE THREAD

**Issue by shivamagg** [ankane/searchkick#897]
Hey.
Is it possible to set up multiple (precisely two) elasticsearch servers in the rails app (config/initializers/elasticsearch.rb) so that the modifications to data are triggered in both the servers?

I want to use multiple servers as they are for different purposes in the micorservices architecture.

**Comment by ankane** [comment]
Hey @shivamagg, there's no way to do this right now.

**Comment by fschwahn** [comment]
@ankane I had a related problem, I access an external database which has it's own elasticsearch-server. I was able to make the elasticsearch client configurable per model with only a few changes. If you are interested I could clean it up and create a PR - then you can decide if this is worthwhile?

**Comment by ankane** [comment]
Hey @fschwahn, happy to take a look if you want to put a PR together.
