### ISSUE TITLE
Special characters: 'EXECUÇÃO' not matching 'EXECUÇÃO'

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#898]
I started debugging why some queries were not returning matches and found out that some strings copied and pasted from Microsoft Word had different bytes for some chars. 

This took me a long time to figure out since we're talking about visually identical chars; the left one was pasted from word and the right one was typed by me. Searching with the right string does NOT return a result for documents with the left string (they don't match): 

![image](https://cloud.githubusercontent.com/assets/743879/25092630/f00d2a4e-2364-11e7-8036-4b2740756341.png)

I know I should try to sanitize this myself but not only I failed that (even using .mb_chars.tidy_bytes) but I noticed that Searchkick has support for 'special characters', so I'm posting this here to seek help since it appears to me that Searchkick/ES support for 'special characters' should return a match in this situation. 

```
[48] pry(main)> 'EXECUÇÃO' == 'EXECUÇÃO'
=> false
[49] pry(main)> ms_word_string = 'EXECUÇÃO'
=> "EXECUÇÃO"
[50] pry(main)> typed_string = 'EXECUÇÃO'
=> "EXECUÇÃO"
[51] pry(main)> ms_word_string == typed_string
=> false
[52] pry(main)> ms_word_string.bytes
=> [69, 88, 69, 67, 85, 67, 204, 167, 65, 204, 131, 79]
[53] pry(main)> typed_string.bytes
=> [69, 88, 69, 67, 85, 195, 135, 195, 131, 79]
[54] pry(main)> ms_word_string.encoding
=> #<Encoding:UTF-8>
[55] pry(main)> typed_string.encoding
=> #<Encoding:UTF-8>
[56] pry(main)> ms_word_string.mb_chars.tidy_bytes.to_s == typed_string
=> false
[57] pry(main)> ms_word_string.mb_chars.tidy_bytes.to_s.bytes
=> [69, 88, 69, 67, 85, 67, 204, 167, 65, 204, 131, 79]
[58] pry(main)> ms_word_string.encode("UTF-8", "Windows-1252")
=> "EXECUCÌ§AÌƒO" 
[59] pry(main)> ms_word_string.encode("UTF-8", "ISO-8859-1")
=> "EXECUCÌ§AÌ\u0083O"
[60] pry(main)> ms_word_string.valid_encoding?
=> true
```

I already read http://www.justinweiss.com/articles/3-steps-to-fix-encoding-problems-in-ruby/ and many other articles but can't seem to find a way to fix this issue (which means I can't either convert the _broken_ `ms_word_string` to match my `typed_string` and neither get ElasticSearch/Searchkick to return a match). 

In my model I have:
`searchkick language: "brazilian", searchable: [:title, :content]`, and the strings are present in the :title field.

**Comment by feliperaul** [comment]
Digging some more, I finally managed to convert the 'weird' chars to correct chars using Rails mb_char `normalize` method:

```
ms_word_string.mb_chars.normalize(:kc) == typed_string
=> true
```

I'm going to normalize all my strings before saving them to the database.

**Comment by ankane** [comment]
Hey @feliperaul, Searchkick just uses Elasticsearch's ASCII folding - it's not designed for encoding differences. The approach you're taking sounds like the right way to go.

**Comment by feliperaul** [comment]
thanks @ankane
