### ISSUE TITLE
Using aggs to allow multiple options be selected

### ISSUE THREAD

**Issue by jfyzhao** [ankane/searchkick#899]
Hi!

I have aggs working in my app, but currently, you are only able to select one filter for each of the aggs. I essentially want the filters to operate as an AND condition across different aggs and an OR condition within the same agg. For example, currently, if I select a specific size I am able to get the filtered results for that size, but if I select another size, I'm unable to get the results for both the first size OR the second size. Is this possible? I've also tried just adding additional size to the query parameters like so: ?size=1,2 but it isn't working.

Relevant code:
```
conditions = {}
conditions[:includes_tags] = params[:includes_tags] if params[:includes_tags].present?
conditions[:size] = params[:size] if params[:size].present?
products = Product.search query, where: conditions, aggs: {includes_tags: {}, size: { order: {'_term': 'asc'}}}
```

and in my view I have
```
    - if @products.aggs["size"].present?
      - @products.aggs["size"]["buckets"].each do |filter|
        li= link_to "#{filter['key']} (#{filter['doc_count']})", products_path(params.permit(@params).merge(size: filter['key']))
```

**Comment by ankane** [comment]
Hey @jfyzhao, I'm having a hard time following what you're trying to do. Can you add an example that includes products and their attributes, and what you're trying to get Searchkick to return?

**Comment by jfyzhao** [comment]
Hey @ankane thanks for getting back to me!

Basically, I have aggs working to filter my searches, but I can only select one option for each agg.

For example, in my Product model, I have:

```
def self.aggs_search(params)
  query = params[:search].presence || '*'
  conditions = {}
  conditions[:includes_tags] = params[:includes_tags] if params[:includes_tags].present?
  conditions[:size] = params[:size] if params[:size].present?
  products = Product.search query, where: conditions, aggs: {includes_tags: {}, size: { order: {'_term': 'asc'}}}
  products
end
```

and in my controller, I have 
```
  def index
    @products = Product.aggs_search(params)
  end
```

and in my Index view, I have a block like this for filtering sizes (and a similar block for includes_tags,e tc)
```
    - if @products.aggs["size"].present?
      - @products.aggs["size"]["buckets"].each do |filter|
        li= link_to "#{filter['key']} (#{filter['doc_count']})", products_path(params.permit(@params).merge(size: filter['key']))
```

This all works great, but the problem is it only allows me to select one size at a time. I want to be able to select multiple sizes and have Searchkick return products that are any of the sizes. Let me know if that makes sense!

**Comment by ankane** [comment]
You just need to update your view to allow the selection of multiple aggs and pass them to the controller.

**Comment by jfyzhao** [comment]
Oh ok got it - I was trying to modify the query parameters the wrong way and using ```?size=1,2``` instead of ```?size[]=1&size[]=2``` - that's why I thought it was maybe a Searchkick issue not a rails one. Thanks!

**Comment by 8frogs** [comment]
Hello jfyzhao,

I run into the same problem and tried your solution. It works with one filter, but I'am not able to create the parameters as described above.

How do you create the "array-params" like ?size[]=1&size[]=2.

When I manually enter the url in the browser I get the correct results but I'am not able to create the correct params with link_to / url_for.

Could you please give a hint how to edit my code?

Thanx Jochen

**Comment by mikelkew** [comment]
@8frogs just make sure to use an array for the param values as such:
`link_to 'link_text', products_path(size: [1, 2])`
