### ISSUE TITLE
Searching across models

### ISSUE THREAD

**Issue by jfyzhao** [ankane/searchkick#900]
Say I have a Products model that belongs to a Brands model. How do I make it so that the search will match attributes on Product, but also Products that belong to a brand.

Essentially, I want to be able to search for 'Sample Brand Name' and have the search match products belonging to that brand, but also have the search be able to search for Product attributes as normal.

I tried the multiple indexes by adding index_name: [Product, Brand] to the search but this didn't seem to work

**Comment by feliperaul** [comment]
@jfyzhao If I understood correctly, you need to do something like this:

```
class Product < ApplicationRecord

def search_data

    self.attributes.merge({

        brand: self.brand.name

})
```

**Comment by jfyzhao** [comment]
Awesome, that worked great. Thanks @feliperaul !
