### ISSUE TITLE
ElasticSearch 5.3.0 warnings

### ISSUE THREAD

**Issue by ahmetabdi** [ankane/searchkick#902]
When reindexing I get these warnings something to handle in the future?

```
[2017-04-20T10:58:12,115][WARN ][o.e.d.i.m.TypeParsers    ] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
```

**Comment by billnbell** [comment]
Yeah it is filling up my disk. _all is not deprecated yet..

How do I stop it from logging?

**Comment by ankane** [comment]
Hey @ahmetabdi, Searchkick 3, which will be released when Elasticsearch 6 is out, will handle this.

**Comment by gerrywastaken** [comment]
see: https://github.com/ankane/searchkick/issues/954#issuecomment-314699177
