### ISSUE TITLE
in Json api search result with assoicate models data

### ISSUE THREAD

**Issue by rajcybage** [ankane/searchkick#903]
I have 2 models one user and other is post
````
class User < ActiveRecord::Base
  searchkich
  has_many :posts
  def search_data
    attributes.merge(posts)
  end
end

class Post < A::B
   belongs_to :user 
end
``````

Now when I am doing User.search "sut", includes: [:posts]

It only returns 
``````
{
users: {
 id: 1
 name: "sute"
},
}
``````

But My expected result is user with includes posts like

````
users: {
 "id": 1,
 "name": "sute",
posts:[
  {"id": 1, "name": "lol"},{"id":2,"name":"asas"}
]
},
{}
}
````

How can I achieve that

**Comment by ankane** [comment]
Hey @rajcybage, Searchkick returns an array of records, so you can do it the same as you would if you were trying to render json for:

```ruby
User.includes(:posts).to_a
```

**Comment by rajcybage** [comment]
Hi @ankane I did `User.includes(:posts).search "st", fields: [{name: :exact}], includes: :posts` still not getting ?

**Comment by ankane** [comment]
Hey @rajcybage, see my comment above.

**Comment by rajcybage** [comment]
Hi @akane, 

Thank you for your reply. It is also not working `alias_attribute` of user model. and in serializer if I define posts as has_many: :posts it is still not taking ?

thanks again
Rajarshi

**Comment by jkras** [comment]
@rajcybage you may have worked this out but you spelt searchkick wrong in your User model -- see "searchkich"

**Comment by ankane** [comment]
Cleaning up issues.
