### ISSUE TITLE
Multiple models with different fields

### ISSUE THREAD

**Issue by dpgigorro** [ankane/searchkick#904]
Hi all!

I have Product and Post models. Posts have a 'published' column. 

Is it possible to search across the two models but using a kind of "where(published: true)" ? That 'where' should only affect to Posts. I'd like to change that 'where' depending on the role of the user, so a regular user will not be able to find unpublished posts, but an admin/moderator will.

I'm trying something like this, but it doesn't work:

```
Searchkick.search search_param,
                      page: page_number,
                      per_page: per_page,
                      index_name: [Post, Product],
                      where(published: true),
                      sort: {created_at: :desc}
```

**Comment by nuritnt** [comment]
did you find a solution for this?

**Comment by dpgigorro** [comment]
No, I'm sorry.

**Comment by ankane** [comment]
Hey @dpgigorro, you can use an `_or` in your `where` clause for this. It should look something like:

```ruby
where: {_or: [{_type: "post", published: true}, {_type: "product"}]}
```

**Comment by ankane** [comment]
Cleaning up stale issues
