### ISSUE TITLE
Phrase matches don't work with 2.x and ElasticSearch 2.4.4

### ISSUE THREAD

**Issue by jeffreyguenther** [ankane/searchkick#905]
I might be doing something wrong, but it appears phrase matches don't work the same in 2.2.1 as they do in 1.5.1 on ES 2.4.4.

``` ruby
it "returns results where title matches" do
      create_resource_where_name_matches_term

      count = 1

      Resource.reindex
      Resource.searchkick_index.refresh

      options = {}
      options.merge!({match: :phrase})
      options.merge!({fields: Resource.search_fields})
      query = "social entrepreneurs don't have it easy raising capital"
      result = Resource.search(query, options)

      expect(Resource.count).to eq(count)
      expect(result.size).to eq(count)
    end

def create_resource_where_name_matches_term
    resource = create(:resource, :approved, name: "Social entrepreneurs don't have it easy raising capital")

    resource.reindex
    resource
  end
```
This test passes on 1.5.1 but fails on 2.2.1.

Is there any reason why this might be?
Does 2.x require ES 5?

**Comment by jacobsmith** [comment]
@jeffreyguenther Did you ever find a work around with this or investigate any further? I'm running into a similar issue and found this issue while searching.

**Comment by jeffreyguenther** [comment]
Unfortunately, no. I ended up downgrading SearchKick to the latest 1.x.

On new projects, I use ES 5.x and SearchKick 2.x.

**Comment by ankane** [comment]
Hey @jeffreyguenther, I added a test case locally for this and it passes with the latest versions of Searchkick and Elasticsearch, so think it's something with your app.

**Comment by jeffreyguenther** [comment]
The issue is only with SearchKick 2.x and ElasticSearch 2.4.x.

New versions work as expected. ES 5 and SearchKick 2.x play nice together.

**Comment by ankane** [comment]
@jeffreyguenther I just tested with that as well (and committed the test).

**Comment by jeffreyguenther** [comment]
Then it looks like things are good on your end. Unfortunately, I'm not working in the codebase where I originally experienced. It's been handed off to a client @jacobsmith might be able to provide more info if he wants to pursue the bug.

With all my current projects I'm using ES5 and SearchKick 2.x and everything is working as intended. Feel free to close the issue if you'd like.

**Comment by ankane** [comment]
Will close for now, but happy to revisit if there's more info to reproduce.
