### ISSUE TITLE
Doesn't support Kaminari paginate

### ISSUE THREAD

**Issue by nicholas-rockstar** [ankane/searchkick#906]
Hi,

I recently integerated searchkick but I found it is repeatedly giving me error when I try to return paginated result of SearchKick::Results.

@products = Product.search 'chew', page: 0, per_page: 10
paginate @products, status: :ok

This raises the following error.
NoMethodError: undefined method `page' for #<Searchkick::Results:0x007fd10bef8e98>

Thanks for your help, in advance.

Nicholas

**Comment by ankane** [comment]
Hey @nicholas-rockstar,

- What versions of Searchkick and Kaminari are you using?
- Can you paste the backtrace?

**Comment by nicholas-rockstar** [comment]
Hi @ankane 

- Versions of Searchkick and Kaminari I'm using
kaminari (1.0.1)
searchkick (2.2.1)

- Backtrace
  Product Search (113.9ms)  curl http://localhost:9200/products_development/_search?pretty -d '{"query":{"bool":{"must":{"dis_max":{"queries":[{"bool":{"must":{"bool":{"should":[{"match":{"name.word_start":{"query":"c","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}}]}},"should":{"match":{"name.analyzed":{"query":"c","boost":10,"operator":"and","analyzer":"searchkick_word_search"}}}}}]}},"filter":[{"term":{"location_id":2}}]}},"size":10,"from":0,"sort":{"name":"asc"},"timeout":"11s","_source":false}'
Completed 500 Internal Server Error in 157ms (Searchkick: 113.9ms | ActiveRecord: 3.7ms)


  
NoMethodError (undefined method `page' for #<Searchkick::Results:0x007fd10bef8e98>):
  
app/controllers/products_controller.rb:50:in `paginated'

**Comment by ankane** [comment]
Thanks, can you paste the full backtrace?

**Comment by latortuga** [comment]
I ran into this exactly exception and it was because I was doing this:

```ruby
# products is a paginated result set
products = Product.search("*", page: 10, per_page: 10)

# example mistake
if products.page(10).first_page?

# fixed
if products.first_page?
```

The kaminari docs are a bit unclear on this point, but basically you don't need to call `#page` on the searchkick result, you can call the kaminari helper methods directly.
