### ISSUE TITLE
Problem with postgres & spring: PG::ConnectionBad: PQsocket() can't get socket descriptor

### ISSUE THREAD

**Issue by vovimayhem** [ankane/searchkick#910]
I'm working on a legacy-code project running on Rails 3.2.21, and I'm currently isolating problems with rspec, spring & postgres.

Several gems in the project are adding modules to `ActiveRecord::Base` on load phase, and somehow this is attempting a connection before spring's forking of processes.

This causes that whenever I run rspec when the app has been already pre-loaded on spring (due to previously running rspec) to raise the following error:

```
ActiveRecord::StatementInvalid:
  PG::ConnectionBad: PQsocket() can't get socket descriptor:           SELECT tablename
            FROM pg_tables
            WHERE schemaname = ANY (current_schemas(false))
```

I suspect this is no longer the case on Rails >= 4.x, but maybe I'm wrong.

I fixed it on my case changing [`lib/searchkick.rb:210`](https://github.com/ankane/searchkick/blob/f5a2b2e196931c9512cd0e2628a27bc661d46093/lib/searchkick.rb#L210):

```
ActiveSupport.on_load :active_record do
  send :extend, Searchkick::Model
end if defined?(ActiveRecord)
```

Is anyone else experiencing this?

I think, regardless of this causing trouble or not, that the `Searchkick::Model` module must be added to `ActiveRecord::Base` inside this proposed hook.

What do you think?

**Comment by ankane** [comment]
Hey @vovimayhem, thanks for the detailed report 👍  Updated on master.
