### ISSUE TITLE
Keeping index in sync with associations

### ISSUE THREAD

**Issue by shivamagg** [ankane/searchkick#911]
Hey, 
I have a Business model with searchkick enabled on it.
It also has a 'has_one' association with Country model.

```ruby
class Business
   include Neo4j::ActiveNode
   property :name, type: String
   has_one :out, :country, rel_class: :HasCountry
end
```
To keep the index in sync when a new relation with country is updated in the controller method i am doing
`@business.reindex`
as suggested here #118 

```ruby
@business.country = @country
@business.reindex
```
This method sometimes gives the following error
```bash
Searchkick::ImportError ({"type"=>"index_failed_engine_exception", "reason"=>"Index failed for [business#f52298dc-40e2-4f0e-b5aa-0595b2851b59]", "index_uuid"=>"hAHUuXeKQ6-9745Er1RwtA", "shard"=>"2", "index"=>"businesses_development_20170429103558231", "caused_by"=>{"type"=>"already_closed_exception", "reason"=>"translog is already closed", "caused_by"=>{"type"=>"i_o_exception", "reason"=>"Protocol error"}}} on item with id 'f52298dc-40e2-4f0e-b5aa-0595b2851b59')
```

The error appears sometimes and sometimes not. I cant figure out what is causing the error.
Any suggestions?

**Comment by ankane** [comment]
Hey @shivamagg, I'm not familiar with this error, but it sounds like an issue with the Elasticsearch cluster.
