### ISSUE TITLE
Synonyms not working

### ISSUE THREAD

**Issue by ZainW** [ankane/searchkick#912]
current elasticsearch versions: 5.3.2
current searchkick version: 2.2.1

I am trying to alias the names in my db so as a test i am trying `searchkick synonyms: [["Anti-Mage", "am"]]` but it does not work for me

I don't get any errors from the rails console just the search query that returns no matches. I am trying to match Anti-Mage to am or AM as a short form

edit: also tried elasticsearch 5.2.2 still no luck

~~edit: also using rails 5.1 (staring to feel like this may be the issue :(~~

**Comment by ankane** [comment]
Hey @ZainW, be sure to reindex after changing synonyms. If that doesn't work, try the Debugging Queries section in the readme. Synonyms should show up in the tokens. Searchkick is tested with Rails 5.1, so that's not the issue.

**Comment by ZainW** [comment]
Synonyms do show up when i debug
`Model Searchkick Options
{:synonyms=>[["Anti-Mage", "am"]]}`

when i search for "am" it still does not come up with the result of "Anti-Mage", if i search for Anti-Mage or Anti the result does show up

I am running Hero.reindex in my rails console so it should be reindexing just fine but let me know if there is something else i should do

**Comment by ankane** [comment]
Try the `Model.search_index.tokens` code in the Debugging Queries section. Synonyms should show up with the `searchkick_index` analyzer. If they don't, you may need to adjust the synonyms to work better with Searchkick's tokenization.

**Comment by ZainW** [comment]
using that debugging code i do get a return of an array with synonyms that include all variations.

i added a few synoyms and removed my `fields: [:name]` from my search and it worked...

going to keep looking into it because i really only want names to be searched and indexed for performance

**Comment by ankane** [comment]
That's odd. Both the name and _all field should use the same analyzers. Let me know what you find.

**Comment by ZainW** [comment]
Both debug runs are exactly the same (besides the search params showing field: [:name] on one) and the fact that one returns the result im looking for.

well since i made the search_data method only have name in it i guess a full search will pretty much only search that.

I'll continue to try stuff and report back but I'll close this for now until i can come up with something more concrete



synopsis: even if ur db is has caps put synonyms in lower case if u have issues, use search data to make your index as small as u need it to be and take out any fields you may search for if u still have issues

**Comment by ankane** [comment]
Hey @ZainW, it looks like synonyms need to be lowercase to work. I pushed a fix to master.

**Comment by ZainW** [comment]
Thanks so much! I don't mind building off master but when approximately are you thinking of releasing 2.2.2 with the change?
