### ISSUE TITLE
Unexpected stemming/match behaviour

### ISSUE THREAD

**Issue by jprosevear** [ankane/searchkick#914]
I have an Item model with a property 'title' with the value 'Radioactive', such that:
http://localhost:9200/items_development_20170504073131619/_search?pretty=true&q=title:Radioactive

Returns the item.  As well doing a search via Item.search("Radioactive") returns the item.

However Item.search("Radioactive", fields: [:title]) and Item.search("Radioactive", fields: ['title']) do not return the item.  I have tried both snowball and the standard stemmer.  If I change the title simply to "Active", all cases work.

Because the records have associations, using search_data to override the default indexing behavior.

Have another case where a username property with value "TheVision" can't match either (but searching with "TheVisio" will create matches).  Its almost like if there are two words that can be distinct in the search, the matching/stemming works differently, ie 'radio' & 'active'

**Comment by jprosevear** [comment]
Starting to think there is some mismatch with the indexing and search analzyers.

**Comment by jprosevear** [comment]
Yes, an analzyer mismatch is the problem.  If I explicitly do:
``searchkick word: [:title]

or:
``searchkick searchable: [:title]

In the mappings you get:
 ```
         "title": {
            "type": "keyword",
            "fields": {
              "analyzed": {
                "type": "text",
                "analyzer": "searchkick_index"
              }
            },
            "ignore_above": 30000
          }
```
if you just do:
``searchkick

you get
 ```
          "title": {
            "type": "keyword",
            "fields": {
              "analyzed": {
                "type": "text"
              }
            },
            "include_in_all": true,
            "ignore_above": 30000
          },
```

**Comment by ankane** [comment]
Hey @jprosevear, great find and research 👍  This is fixed on master. Will also add a test so this won't happen again - pretty big oversight on my part.
