### ISSUE TITLE
Question about most efficient bulk indexing of a subset of records...

### ISSUE THREAD

**Issue by ckuttruff** [ankane/searchkick#917]
Sorry if I've missed something in the docs (was digging through the source code as well), but I'm wondering what the best way is to index large, specific subsets of table.

Say I have a 10M record table and I just want to bulk reindex the last 1M records, what would be the best way to do that?

I was fumbling around with:
```ruby
Searchkick.callbacks(:bulk) do
  Foo.where("id > ?", some_number).reindex
end
```

But that seems to populate a bunch individual low queue jobs (I have `callbacks: :queue` in my model and the connection pool setup detailed here: https://github.com/ankane/searchkick#queuing )

Sorry again if I missed something in the docs / code; thanks so much for all the work you've done on this.  Really appreciate the gem!

**Comment by ckuttruff** [comment]
Would calling this directly be appropriate?

```ruby
Searchkick::BulkReindexJob.perform_later(
  class_name: 'Foo',
  record_ids: ids_to_reindex,
)
```

**Comment by ankane** [comment]
Hey @ckuttruff, `Foo.where("id > ?", some_number).reindex` should reindex in batches, so no need for `Searchkick.callbacks(:bulk)`.

**Comment by ckuttruff** [comment]
Thanks so much.  Sounds great.  

Appreciate the response and closing
