### ISSUE TITLE
Question: How to search two different terms in two different fields simultaneously 

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#918]
I have a simple search form with 2 inputs like this:
`[Title] [Content]`

I want my users to able to search by `title` (just leave `content` blank), by `content` (just leave `title` blank) or by both at the same time; but, of course, the string in `title` input field shouldn't match something in `content`, and a string in `content` input field shouldn't match something in a `title`. 

In my controller I'm doing checks like this (pseudocode):

```
if params[:title].present? && params[:content].blank?
    Block.search params[:title], fields: [:title]
elsif params[:content].present? && params[:title].blank?
    Block.search params[:content], fields: [:content]
```

The problem arrives when both inputs are filled in. I need to search `fields: [:title]` with `params[:title]` and `fields[:content]` with `params[:content]`. 

My current solution is very convoluted and involves:
1. doing 2 different SearchKick queries (one for title, one for content)
2. calling `.results` on these SearchKick queries
3. Finally calling `Model.where(id: query1.ids & query2.ids)`, being `&` the AND instersection operator (to get only results that were present in both queries). 

Since this seems to be a common scenario, is there a simpler way? I'm asking because this solution loses ordering (I can't retain order by relevance).

**Comment by ankane** [comment]
Hey @feliperaul, there's no way right now (besides manually changing the ES query), but happy to accept a PR for it.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.
