### ISSUE TITLE
Issue in README with word match

### ISSUE THREAD

**Issue by jwoertink** [ankane/searchkick#919]
In the README, there's a section talking about autocomplete that has this code

`Movie.search "jurassic pa", match: :word_start`

Running code like this throws an error: `Must specify fields`. Adding `fields: [:title]` to that works.

```ruby
class Movie < ApplicationRecord
  searchkick word_start: [:title]
end

Move.search "jurassic pa", fields: [:title], match: :word_start
```

**Comment by ankane** [comment]
Great catch, thanks @jwoertink 👍
