### ISSUE TITLE
Indexing attachments

### ISSUE THREAD

**Issue by syamilmj** [ankane/searchkick#92]
Hi there,

First of all thank you for this great gem.

Is there a way to index rich text documents with this, e.g PDF, MS Word, text etc?

Cheers

**Comment by vokshirg** [comment]
Any other variants for this day? 
I've used mapper attachments plugin with ES 2.4.0 

But now with ES 5.0.0 I'm trying to use [ingest-attachment](https://www.elastic.co/guide/en/elasticsearch/plugins/current/ingest-attachment.html) but have troubles with custom mapping. Could anybody help? Thanks

**Comment by icortex** [comment]
Hey @vokshirg I'm trying to do it with ingest-attachment but haven't been able to make it work. What about you?

**Comment by vokshirg** [comment]
@icortex, now i'm just indexing all documents through [Yomu](https://github.com/yomurb/yomu), therefore you don't need  any manipulations with ingest-attachment
