### ISSUE TITLE
how to index on a habtm association change

### ISSUE THREAD

**Issue by ckhall** [ankane/searchkick#920]
```
class User
  searchkick searchable: [:name]
  has_and_belong_to_many :tags # join table -> tags_users

  def search_data
    { name: name,
      tags: tags.map(&:id)
    }
  end

  def name
    "#{fname} #{lname}"
  end
end

class Tag
  has_and_belongs_to_many :users
end
```

I understand for has_many/belongs_to associations, I can add a after_commit callback to reindex the associated model, however, wrt habtm, the only thing changes is the addition of a record in the join table, so for the use case where a user is added to an existing tag, i don't see how an after_commit on tag model would do anything.  is there a way to handle this?  thanks.

**Comment by sheehan1102** [comment]
I am having the same issue. Any updates on this?

**Comment by jprosevear** [comment]
Can you make the many-many table a :through you just do an after_commit callback on that table?

http://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many

**Comment by ankane** [comment]
Exactly what @jeroenvisser101 said.

> You should use has_many :through if you need validations, callbacks or extra attributes on the join model.
