### ISSUE TITLE
Manually add Searchkick's custom analyzers to elastic search server.

### ISSUE THREAD

**Issue by ashishmax31** [ankane/searchkick#921]
Is there any way to manually add searchkick's custom analyzers to the elastic search server?
I'm using logstash to index my data to the elastic search server(ie I'm not using Searchkick's `Model.reindex` method to index my model.)
Searching on my model now throws `org.elasticsearch.index.query.QueryShardException: [match] analyzer [searchkick_search] not found`
Any help regarding this will be much appreciated.
Thanks

**Comment by ankane** [comment]
Hey @ashishmax31, you should probably write custom queries for this instead of Searchkick generated ones. If you really want to use Searchkick analyzers, you can find them in the source code.
