### ISSUE TITLE
Catching exception in reindex

### ISSUE THREAD

**Issue by Babdus** [ankane/searchkick#923]
Recently I had a case, when for some reason my app couldn't connect to elasticsearch. This caused in not reindexing the data which was created or updated in this period. My solution was to catch this exception and start jobs for reindexing them in future. So my question is, what is your approach in catching exceptions while reindex, should I override some of your functions and how? Or more generally, how do you recommend dealing with fallbacks?

**Comment by ankane** [comment]
Hey @Babdus, if you use the `async` option for callbacks, jobs will be retried if they fail. I'd also like to do this for the `queue` option in the future.

**Comment by Babdus** [comment]
Thanks @ankane, the asynchronous method helped me in many ways, first of all, the app is not crashing because of elasticsearch problem. But it still does not retry failed jobs automatically. Maybe it needs some special config of jobs somewhere?

**Comment by ankane** [comment]
It depends on which ActiveJob adapter you use. I'd recommend Sidekiq, which retries 25 times by default. https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

**Comment by Babdus** [comment]
Thank you! I am using Resque now for many jobs and it would not be easy to shift on Sidekiq, do you know if it is possible with Resque also?

**Comment by ankane** [comment]
I think you can find that out :)
