### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by flaviolpgjr** [ankane/searchkick#926]
Hello my friends, I have a little doubt, I have a table, with the fields race and name, I only have a search field on my front end, suppose that on this table I have the dog named sid, and chow chow, With the searchkick is it possible in my search field I search sid chow chow, and he bring such a record?

**Comment by cmalpeli** [comment]
Have you read the readme on `search_data`.  Make sure those fields are set to be indexed and it should work.  You can also control things like boosting if you want to put more priority over race or name.

**Comment by flaviolpgjr** [comment]
search_data, do not define only when you want to use synonym?

**Comment by flaviolpgjr** [comment]
Would you have an example, how do I index my fields?

**Comment by cmalpeli** [comment]
Here is an example of how we use `search_data` to control what fields on a model are indexed:


```
def search_data
    {
      id: id,
      title: title,
      company: company,
      description: description,
      categories: categories.map(&:name),
      location: location,
      location_geo: {lat: latitude, lon: longitude},
      created_at: created_at,
      updated_at: updated_at,
      city: city,
      state: state }
  end
```

**Comment by flaviolpgjr** [comment]
Thanks, but from what I've been reading, I'll have to use multi_match, custom query with cross_fields
