### ISSUE TITLE
Exclude ids from has_many

### ISSUE THREAD

**Issue by sofianegargouri** [ankane/searchkick#928]
I have this model:

    class Recipe < ApplicationRecord
      enum meal_type: [:entrance, :meal, :dessert, :baby]
      searchkick
    
      has_many :recipe_ingredients
      has_many :ingredients, through: :recipe_ingredients
    
      scope :search_import, -> {includes(:recipe_ingredients)}
      scope :with_ingredient_ids, -> (ids) {joins(:recipe_ingredients).where('recipe_ingredients.ingredient_id IN (?)', ids)}
      scope :without_ingredient_ids, -> (ids) {joins(:recipe_ingredients).where('recipe_ingredients.ingredient_id NOT IN (?)', ids)}
    
      def search_data
        attributes.merge({
                             ingredient_ids: ingredients.pluck(:id)
                         })
      end
    end

And I'm trying to get recipes without specific ingredients, just like that:

    class SearchController < ApplicationController
      def index
        @recipes = Recipe.search params[:query], where: search_params
      end
    
      private
      def search_params
        p = {
            ingredient_ids: {},
            total_time: {}
        }
        p[:ingredient_ids][:all] = params[:with_ingredient_ids] if params[:with_ingredient_ids].present?
        p[:ingredient_ids][:not] = params[:without_ingredient_ids] if params[:without_ingredient_ids].present?
        p[:total_time][:lte] = params[:max_preparation_time] if params[:max_preparation_time].present?
        p[:total_time][:gt] = params[:min_preparation_time] if params[:min_preparation_time].present?
        p
      end
    end

I can't achieve the result I expect. Am I doing it right ?

**Comment by jprosevear** [comment]
Do you have an example item from you elasticsearch index?  One possible issue is that I don't see how you are indexing total_time.

**Comment by sofianegargouri** [comment]
What do you need ?

**Comment by jprosevear** [comment]
The json of an item in your index.

**Comment by cireficc** [comment]
@sofianegargouri I think your query is wrong. I can filter only favorite users ("following") and also exclude blocked users with the following setup:

```ruby

@where = {
  id: {}
}
# ... more search parameters

@where[:id][:in] = current_user.favorite_users.ids
@where[:id][:not] = current_user.blocked_users.ids
```

It looks like your `p[:ingredient_ids][:all] =` should be `p[:ingredient_ids][:in] = `. Maybe try that?

**Comment by ankane** [comment]
Cleaning up issues. Thanks for helping out @jprosevear and @cireficc
