### ISSUE TITLE
Searchkick.callbacks(false) ignored in rspec tests?

### ISSUE THREAD

**Issue by ckuttruff** [ankane/searchkick#929]
I have a simple block like so in my rspec test:

```ruby
Searchkick.callbacks(false) do
  # create indexed record
end
```

And when I assert that the count of indexed records is 0 (since I haven't explicitly called the reindex function), it still reindexes the record.  Even tried disabling callbacks in the models toplevel model configuration and with the method mention here: (https://github.com/ankane/searchkick#rspec)
But it seems to reindex right away regardless.

I have callbacks set as async and am inlining my sidekiq calls so they're running right away (but wouldn't expect them too with the callback(false) block I have.

Looking through the code now, but wondering if you might be able to shed light on this?  I'm on the latest 2.3.0 version

Thanks!

**Comment by ankane** [comment]
Hey @ckuttruff, I ran some tests with async callbacks enabled, and couldn't reproduce.

**Comment by ckuttruff** [comment]
Will investigate; it may have been a timing issue based on some configuration quirks. 

Thanks, closing for now.

Btw been reading through the code a lot tp better understand the functionality.  Really clean and I very much appreciate the UI and thorough documentation. 

Great work!
