### ISSUE TITLE
Faraday Error when when updating a record via sidekiq.

### ISSUE THREAD

**Issue by nsantiago2719** [ankane/searchkick#930]
I have been experiencing an faraday error whenever a record is updated through sidekiq. When I checked the log file it says that it fails on reindex of searchkick. So I tried to reindex in console to see if reindex is working and it is. Now I've come to conclusion that searchkick might be needed to included in Gemfile first but it's not. Any idea why?

**Comment by ankane** [comment]
Hey @nsantiago2719, what's the exact error message and backtrace you're seeing?

**Comment by nsantiago2719** [comment]
@ankane here's the error message and the backtrace.

Error Message: `no implicit conversion of nil into String`
Backtrace:
```/home/laz/bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/signers/v4.rb:117:in `+'
/home/laz/bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/signers/v4.rb:117:in `signature'
/home/laz/bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/signers/v4.rb:107:in `authorization'
/home/laz/bundle/ruby/2.3.0/gems/aws-sdk-core-2.7.7/lib/aws-sdk-core/signers/v4.rb:59:in `sign'
/home/laz/bundle/ruby/2.3.0/gems/faraday_middleware-aws-signers-v4-0.1.5/lib/faraday_middleware/request/aws_signers_v4.rb:56:in `call'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/middleware.rb:9:in `call'
/home/laz/bundle/ruby/2.3.0/gems/faraday-0.10.1/lib/faraday/rack_builder.rb:139:in `build_response'
/home/laz/bundle/ruby/2.3.0/gems/faraday-0.10.1/lib/faraday/connection.rb:377:in `run_request'
/home/laz/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:23:in `block in perform_request'
/home/laz/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:261:in `perform_request'
/home/laz/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/laz/bundle/ruby/2.3.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/home/laz/bundle/ruby/2.3.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/bulk.rb:95:in `bulk'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/indexer.rb:18:in `perform'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/logging.rb:126:in `perform'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/indexer.rb:11:in `queue'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/index.rb:484:in `bulk_index_helper'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/index.rb:72:in `store'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/logging.rb:28:in `block in store'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/logging.rb:27:in `store'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/index.rb:122:in `reindex_record'
/home/laz/bundle/ruby/2.3.0/gems/searchkick-2.1.1/lib/searchkick/model.rb:125:in `reindex'
/var/www/edukasyon-p6/releases/20170609111615/app/models/school.rb:231:in `reindex_school'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:242:in `block in simple'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `block in call'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `each'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:456:in `call'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_commit_callbacks'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:354:in `committed!'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:87:in `commit_records'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:178:in `commit_transaction'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
/home/laz/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
/var/www/edukasyon-p6/releases/20170609111615/app/workers/search_boost_worker.rb:26:in `perform'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:167:in `execute_job'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:139:in `block (5 levels) in process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:90:in `block in call'
/home/laz/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/execution_wrapper.rb:76:in `wrap'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/rails.rb:89:in `call'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:135:in `block (4 levels) in process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/laz/bundle/ruby/2.3.0/gems/rollbar-2.14.0/lib/rollbar/plugins/sidekiq/plugin.rb:11:in `call'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/logging.rb:10:in `call'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:134:in `block (3 levels) in process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/logging.rb:32:in `with_context'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:183:in `stats'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:131:in `block in process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq.rb:35:in `block in '
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:126:in `process'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:82:in `process_one'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/processor.rb:70:in `run'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:17:in `watchdog'
/home/laz/bundle/ruby/2.3.0/gems/sidekiq-4.2.10/lib/sidekiq/util.rb:26:in `block in safe_thread'```

**Comment by ankane** [comment]
It looks like an issue with missing AWS credentials. See how the backtrace starts with `aws-sdk-core/signers/v4.rb`.

**Comment by nsantiago2719** [comment]
@ankane, that's why I'm confused because the re-index works or everything works in console or even in searching. But that problem shows up if it came from sidekiq.

**Comment by ankane** [comment]
Cleaning up issues
