### ISSUE TITLE
Searchkick.search doesn't allow suggestions

### ISSUE THREAD

**Issue by ledermann** [ankane/searchkick#932]
Doing a multi-model search with `suggest` option seems not to be possible:

````ruby
irb(main):027:0> Searchkick.search("foobar", suggest: true).suggestions
  Search (28.4ms)  curl http://localhost:9200/_all/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"foobar","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"foobar","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"foobar","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"foobar","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'
RuntimeError: Pass `suggest: true` to the search method for suggestions
	from (irb):27
irb(main):028:0>
````

Is this intended? 

All of my models contain a definition like this:

````ruby
searchkick word_start: [ :full_text ],
           highlight:  [ :full_text ],
           suggest:    [ :full_text ],
           callbacks:  :async,
           language:  'german'
````

How can I do a multi-model search **with** suggestions?

**Comment by ankane** [comment]
Hey @ledermann, this was never implemented. If you use master, you can now do `suggest: [:full_text]` to achieve this.

**Comment by ledermann** [comment]
Thanks for your fast response and fix. I have tried it, but there are still issues.

This works fine:
```ruby
Searchkick.search('foobar', suggest: [:full_text], index_name: [Model1]).suggestions.count 
# => 2 
```

But this (using one more index) fails:
```ruby
Searchkick.search('foobar', suggest: [:full_text], index_name: [Model1, Model2]).suggestions.count 
# => 0
```

Maybe the problem is in my head :) but I expect to get **more** suggestions if more indexes are used. Am I wrong? BTW: Both models have the same index definition (see first post) and the index is refreshed.

**Comment by ankane** [comment]
More models => more suggestions makes intuitive sense to me. I haven't worked with Elasticsearch suggestions in a long time, so not sure what the issue is. If you find it, let me know (or even better, submit a fix).
