### ISSUE TITLE
kaminari 1.0.1 page_entries_info(results) ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by teohm** [ankane/searchkick#934]
The latest kaminari (v1.0.1) has changed `Kaminari::ActiveRecordRelationMethods#entry_name` to accept a new optional `options` argument. See: https://github.com/kaminari/kaminari/blob/v1.0.1/kaminari-activerecord/lib/kaminari/activerecord/active_record_relation_methods.rb#L6-L9

And kaminari view helper `page_entries_info(results)` is now calling `Searchkick::Results#entry_name` by passing in this `options` argument. See: https://github.com/kaminari/kaminari/blob/v1.0.1/kaminari-core/lib/kaminari/helpers/helper_methods.rb#L104

But because `Searchkick::Results#entry_name` does not accept argument, it raises error: 
https://github.com/ankane/searchkick/blob/master/lib/searchkick/results.rb#L130-L132

```
ArgumentError: wrong number of arguments (given 1, expected 0)
```

-------
Proposed solution:

I propose to modify `Searchkick::Results#entry_name` to match `Kaminari::ActiveRecordRelationMethods#entry_name` implementation:

```
   def entry_name(options = {})
      default = options[:count] == 1 ? model_name.human : model_name.human.pluralize
      model_name.human(options.reverse_merge(default: default))
    end
```

What do you think?

**Comment by ankane** [comment]
Hey @teohm, thanks for the detailed report and proposed fix 💯 

I've added an extra conditional for backward compatibility, which can probably be removed in Searchkick 3, as well as tests.

**Comment by teohm** [comment]
@ankane sweet, looks great! 👍
