### ISSUE TITLE
Stemming not working with word_start autocomplete

### ISSUE THREAD

**Issue by pawneetdev** [ankane/searchkick#935]
```
def autocomplete
		mcas = Mca.search(params[:term], {
			fields: ["name"],
			match: :word_start,
			limit: 10,
			load: false,
			misspellings: {below: 5}
		})
end
```

When I use word_start match, stemming does not work but when I remove word_start, stemming works flawlessly. I have tried both "english" and "porter2" stemmer.

**Comment by ankane** [comment]
Hey @pawneetdev, Searchkick doesn't do stemming for partial matches/autocomplete. Happy to accept an option for it, but will need to maintain backward compatibility.

**Comment by pawneetdev** [comment]
Okay. Thanks.
There is one more thing. Sorry I am not opening another ticket for the same.

**Comment by ankane** [comment]
There's no convenience option for it, but you can always use [Advanced](https://github.com/ankane/searchkick#advanced) features to do anything Elasticsearch is capable of.
