### ISSUE TITLE
N+1 queries with nested aggregations

### ISSUE THREAD

**Issue by jfyzhao** [ankane/searchkick#936]
Hi,

I'm trying to remove some n+1 queries from a left nav with aggregations. Let's say I have a model Product that I have a bunch of aggregations on, including one on Brand, where Product belongs_to Brand. I'm running into an issue where I'm getting n+1 queries when displaying the Brand aggregations, and I'm unable to call includes(:brand) on the result of the filtered set since it is a  #<Searchkick::Results> collection instead of an ActiveRecord one. Any insight on whether this is possible to do? 

Adding includes to the Product.search query like shown in the documentation does not work for this case with displaying the aggregations in the view and needing to use an includes.

**Comment by ankane** [comment]
Hey @jfyzhao, if the `includes` option doesn't work for your use case, you'll need do it in Ruby.

1. Get a list of all brand ids you need - `brand_ids = [...]`
2. Get all brands in one query and index by id - `brands = Brand.find(brand_ids).index_by(&:id)`
3. Use this hash to retrieve each brand - `brand = brands[1]`

**Comment by jfyzhao** [comment]
Got it, just wanted to make sure there wasn't a possible way to call includes on the Searchkick::Results collection. Thanks!

**Comment by ankane** [comment]
The `includes` option calls the `includes` method on the underlying relation. https://github.com/ankane/searchkick/blob/0422c616c2198775ee93c59019b468054125a013/lib/searchkick/results.rb#L211
