### ISSUE TITLE
.search_highlights is returning only the first highlight and discarding all others

### ISSUE THREAD

**Issue by feliperaul** [ankane/searchkick#937]
Searchkick's readme has a link to [elastic search highlight documention](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_highlighted_fragments) for highlight feature.

There it states clearly that the maximum number of fragments to return is set by `number_of_fragments` param, and *it defaults to 5 (FIVE)*. 

The problem is Searchkick is apparently discarding all but the first highlight result, making the feature much less useful. 

Using `debug: true` in my search I could confirm that ES is returning a JSON with multiple highlights.

But [this line](https://github.com/ankane/searchkick/blob/0422c616c2198775ee93c59019b468054125a013/lib/searchkick/results.rb#L44) of code in Searchkick::Results#results is actually getting only the FIRST result (see *v.first* in the line below: 

```
highlights = Hash[hit["highlight"].map { |k, v| [(options[:json] ? k : k.sub(/\.#{@options[:match_suffix]}\z/, "")).to_sym, v.first] }]
``` 

Is this intended behavior? I didn't see anything in the docs. Also, is it possible to customize `number_of_fragments` ?

Searchkick 2.3.0

**Comment by ankane** [comment]
Hey @feliperaul, you can use the `response` method to get the entire Elasticsearch response. To customize the number of fragments, you'll need to modify the query generated by Searchkick (see the readme for how to do this).

**Comment by feliperaul** [comment]
@ankane Thanks for the quick reply, but I still don't get it why we are discarding all highlights but the first one. 

I think `.first` should be removed from the method, and we should add `.first` if we want to get only the first one.

**Comment by ankane** [comment]
Hey @feliperaul, Searchkick isn't "discarding" the other highlights. The `search_highlights` method is designed to only return the first one.
