### ISSUE TITLE
Question: How to search result of comparision

### ISSUE THREAD

**Issue by wgkoro** [ankane/searchkick#938]
There are some data sets in Elastic Search like below.
```ruby
{
  name: "AAA",
  ordered_date: "2017-01-01 00:00:00",
  custom_date: "2017-06-02 23:10:10"
},
{
  name: "BBB",
  ordered_date: "2017-02-02 10:00:00",
  custom_date: "2017-04-01 20:00:00"
}
```

I want to sort by larger date between "ordered_date" and "custom_date". 
```ruby
# want to search like this...
search({
  order: { max: [ :ordered_date, :custom_date] }
})
```

Is it possible to do it with searchkick?
If yes, how can I write queries?

**Comment by ankane** [comment]
Hey @wgkoro, the `order` option supports all Elasticsearch sorting features. You can use the link in the readme to see if it's possible.
