### ISSUE TITLE
Bound box issue

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#939]
I see searchkick supports the following:

`Restaurant.search "sushi", where: {location: {top_left: {lat: 38, lon: -123}, bottom_right: {lat: 37, lon: -122}}}`

However when attempting to use `top_right` and `bottom_left` instead I get an error:

`Elasticsearch error: Unknown where operator: :top_right`

According to the ElasticSearch docs these should be supported:
https://www.elastic.co/guide/en/elasticsearch/guide/current/geo-bounding-box.html

`These coordinates can also be specified as bottom_left and top_right.`

Would I need a custom mapper?

**Comment by ankane** [comment]
Hey @cmalpeli, these were never implemented, but happy to accept a PR.

**Comment by cmalpeli** [comment]
@ankane thanks! Will try and set aside some time to do this :)

**Comment by fuelxc** [comment]
PR for this: https://github.com/ankane/searchkick/pull/1064
