### ISSUE TITLE
Feature request: add option to disable misspellings automatic second search

### ISSUE THREAD

**Issue by cireficc** [ankane/searchkick#942]
Referring to [this part of the README](https://github.com/ankane/searchkick#misspellings), and [this code](https://github.com/ankane/searchkick/blob/master/lib/searchkick/query.rb#L82).

Searchkick automatically launches a second search if there are < 5 results. I want to have misspellings enabled, but some fields be exact matches (e.g. a `catalog_number` like **MA-A1**). That all works fine and dandy if I set the setting `misspellings: false` in the search. However, that makes it so **no** fields can have misspellings *at all*, which kind of defeats the purpose of fuzzy matches for the other fields I want (`title`, `description`, etc.).

I would like an option where I can simply disable that second, automatic search, without disabling misspellings entirely. I think it's fairly unfortunate that Searchkick assumes that < 5 results means a search failed. For my use case, having one exact match is actually preferred, or even have two or three matches. However, I can't have that, because Searchkick will automatically relaunch the search with misspellings enabled. That means I can't search by catalog number because I get results for **MA-A2, MA-A3, MF-A1, MF-A2**, etc. because of the misspellings; where I should have exactly one result when searching for **MA-A1**, I get over a hundred even though I have `fields: [..., {catalog_number: :exact }]`.

Can we add an option to disable the second automatic misspellings search? Perhaps as `misspellings: {edit_distance: 2, disable_retry: true}`. I'm not sure what the API would look like, but I would really like to have this option.

**Comment by ankane** [comment]
Hey @cireficc, Searchkick only retries if you use the below option, which is configurable.

**Comment by cireficc** [comment]
Well, I feel like an idiot now. To get the results that I wanted, I needed to set `edit_distance` alongside `below`. I guess I was just too tired when reading the README, because it's fairly obvious upon rereading it. Sorry for wasting your time!
