### ISSUE TITLE
Mapping text value errors 

### ISSUE THREAD

**Issue by koalabear974** [ankane/searchkick#943]
Hi everyone!
I have a really weird error from the indexing of my data by searchkick.
Basically I'm trying to add a custom mapping to specify one column as a text type and not keyword. And when running reindex I have this error:
`Searchkick::ImportError: {"type"=>"mapper_parsing_exception", "reason"=>"failed to parse", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Mixing up field types: class org.elasticsearch.index.mapper.KeywordFieldMapper$KeywordFieldType != class org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType on field summary"}} on item with id '123'`

I tried a lot of things: 
- Change analyzer
- Update searchkick and elasticsearch, and tried different versions
- Try exactly the same queries and mapping via Kibana console (where it actually does work, no problem indexing the same data as the mapping is complaining about)
- Look up the code behind mapping text type field

I really can't find why elasticsearch or searchkick does not want to index my data as text.

If you have any idea on what I can try It would be a huge help. 
Thanks a lot!

**Comment by ankane** [comment]
Hey @koalabear974, not familiar with this error unfortunately, but don't think it's a Searchkick issue.
