### ISSUE TITLE
Moving out from Hashie

### ISSUE THREAD

**Issue by faizalzakaria** [ankane/searchkick#944]
Hi guys,

Wondering if we could move out from Hashie ? Because
- Hashie is known to be slow
- Hashie has pre-defined reserved methods, e.g: `key`.
- There is none in documentation saying that we shouldn't use reserved keys from Hashie.
- Overhead, hidden bugs.

Thanks.

**Comment by ankane** [comment]
Hey @faizalzakaria, I appreciate the suggestion, but no plans to remove it right now. You can use the `response` method if you want to avoid Hashie.
