### ISSUE TITLE
Multi-index search Searchkick.search with index_name not returning result

### ISSUE THREAD

**Issue by frankliu81** [ankane/searchkick#949]

**Comment by frankliu81** [comment]
Trying to get Searchkick.search to work by specifying an index_name.  Model.search is returning results, but Searchkick.search with the index_name is returning no hit.

I have a Control model, which I have added the searchkick method as such:

control.rb

```
class Control < ActiveRecord::Base
searchkick filterable: [:process_walkthrough_id, :objective_id, :audit_id],
    searchable: [:number, :description, :who_performs,
                 :frequency, :control_type, :prevent_detect,
                 :ts_attribute_values, :title]

  def search_data
    {
      number: number,
      description: description,
      who_performs: who_performs,
      frequency: frequency,
      control_type: control_type,
      prevent_detect: prevent_detect,
      ts_attribute_values: ts_attribute_values,
      title: title,
      process_walkthrough_id: process_walkthrough_id,
      objective_id: objective_id,
      audit_id: audit_id
    }
  end

```
After a Control.reindex, I can search in the console, and get the results:

In the console,

```
[4] pry(#<SearchController>)> Control.search('frank')
=> #<Searchkick::Results:0x007fec66841f20
 @klass=
  Control(id: integer, number: string, description: text, who_performs: string, frequency: string, control_type: string, prevent_detect: string, process_walkthrough_id: integer, created_at: datetime, updated_at: datetime, position: integer, method: string, state: string, title: string, origin_id: integer, origin_updated_at: datetime, owner_id: integer, clone_source_id: integer, attribute_values: text, ts_attribute_values: text, passed: boolean),
 @options=
  {:page=>1,
   :per_page=>1000,
   :padding=>0,
   :load=>true,
   :includes=>nil,
   :json=>false,
   :match_suffix=>"analyzed",
   :highlighted_fields=>[],
   :misspellings=>true},
 @response=
  {"took"=>47,
   "timed_out"=>false,
   "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0},
   "hits"=>
    {"total"=>3,
     "max_score"=>3.0604475,
     "hits"=>
      [{"_index"=>"controls_development_20170704124142273",
        "_type"=>"control",
        "_id"=>"29",
        "_score"=>3.0604475},
       {"_index"=>"controls_development_20170704124142273",
        "_type"=>"control",
        "_id"=>"27",
        "_score"=>3.0604475},
       {"_index"=>"controls_development_20170704124142273",
        "_type"=>"control",
        "_id"=>"28",
        "_score"=>3.0604475}]}}>
```


Eventually, I want to be able to search across multiple indices, right now I am just rying with one, so using the Searchkick method with the same term, while specifying the index_name as the readme suggests.  However, no results are returned.

```
[5] pry(#<SearchController>)> Searchkick.search('frank', index_name: [Control])
=> #<Searchkick::Results:0x007fec6561d6f0
 @klass=nil,
 @options=
  {:page=>1,
   :per_page=>1000,
   :padding=>0,
   :load=>true,
   :includes=>nil,
   :json=>false,
   :match_suffix=>"analyzed",
   :highlighted_fields=>[],
   :misspellings=>true},
 @response=
  {"took"=>2,
   "timed_out"=>false,
   "_shards"=>{"total"=>5, "successful"=>5, "failed"=>0},
   "hits"=>{"total"=>0, "max_score"=>nil, "hits"=>[]}}>
```

**Comment by frankliu81** [comment]
I have found that if I simply have:
```
class Control < ActiveRecord::Base
searchkick

```
instead of:

```
class Control < ActiveRecord::Base
searchkick filterable: [:process_walkthrough_id, :objective_id, :audit_id],
    searchable: [:number, :description, :who_performs,
                 :frequency, :control_type, :prevent_detect,
                 :ts_attribute_values, :title]
  
  def search_data
    {
      number: number,
      description: description,
      who_performs: who_performs,
      frequency: frequency,
      control_type: control_type,
      prevent_detect: prevent_detect,
      ts_attribute_values: ts_attribute_values,
      title: title,
      process_walkthrough_id: process_walkthrough_id,
      objective_id: objective_id,
      audit_id: audit_id
    }
  end

```

Then the search returns fine:
[4] pry(main)> Searchkick.search('frank', index_name: [Control])
  Search (457.7ms)  curl https://search-projects-spike-4keip2fcwu6m6uqvgfanadng4e.us-west-2.es.amazonaws.com:443/controls_development/_search?pretty -d '{"query":{"dis_max":{"queries":[{"match":{"_all":{"query":"frank","boost":10,"operator":"and","analyzer":"searchkick_search"}}},{"match":{"_all":{"query":"frank","boost":10,"operator":"and","analyzer":"searchkick_search2"}}},{"match":{"_all":{"query":"frank","boost":1,"operator":"and","analyzer":"searchkick_search","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}},{"match":{"_all":{"query":"frank","boost":1,"operator":"and","analyzer":"searchkick_search2","fuzziness":1,"prefix_length":0,"max_expansions":3,"fuzzy_transpositions":true}}}]}},"size":1000,"from":0,"timeout":"11s","_source":false}'

How do I make multi-index search work when I specify filterable, searchable, and search_data?

**Comment by ankane** [comment]
@frankliu81 not sure I follow completely, but try specifying the `fields` option when you search, as `searchable` disables the `_all` field by default.

**Comment by frankliu81** [comment]
@ankane Thanks, searchable does disable the `_all` field by default.  If I use the `fields` option when I search, ie. `fields=[:description]`, I do get the correct result up.

A couple of things:  

1. If I am doing a project wide search across like ten models, let's say the Control model has title and description searchable, and the Objective model has name and description searchable, would I just specify `fields: [:name, description, :title]` as an unique merge of all the available fields?  But I don't really need to search for title in Objective for example.

2. It would be nice if I can search across all searchable fields automatically instead of listing each of them out (ie. all fifty fields).  I think what I would want is the fields I specify in searchable to be available in the`_all` field, and everything else being excluded, instead of the `_all` field just being disable.  That way, the query would still be simply against the `_all` field.  Instead of this giant query (like 12 kb of text with only the searchabel_fields from three models).  Does searchkick supports this?

 ```
  @search_results = Searchkick.search(params[:search], search_params)
  @search_count = @search_results.total_entries

...

def searchable_indices
    [Control, Risk, Objective]
  end

  def searchable_fields
    fields = []

    searchable_indices.each do |index|
      fields.concat(index.searchkick_options[:searchable])
    end

    fields
  end

  def search_params
      {
        limit: 1_000,
        page: params[:page],
        per_page: 25,
        where: { audit_id: @audit.id },
        # multi-index search
        fields: searchable_fields,
        index_name: searchable_indices
      }

```

**Comment by frankliu81** [comment]
@ankane I like how simple the multi-index search code looks compared to the multi_search code which accomplishes the same thing.
https://github.com/ankane/searchkick/issues/951#issuecomment-313436805

The big drawback though, is that since I'm replacing an existing search implementation, I would like the order of the search results to be grouped and in the order of the model specified in 'searchable_indices' above (ie. results for Controls should come before Risk ... etc.)  This would be the default behavior for multi-search, but is there a way to accomplish this with multi-index search?

**Comment by ankane** [comment]
@frankliu81 to answer your questions above:

1. Yes, a unique merge of all fields should work
2. No, Searchkick doesn't support this right now

As for sorting by index, you could use the `indices_boost` option.
