### ISSUE TITLE
Merge the array of results of multi_search into a single set of results

### ISSUE THREAD

**Issue by frankliu81** [ankane/searchkick#951]
In the Multi Search section,

fresh_products = Product.search("fresh", execute: false)
frozen_products = Product.search("frozen", execute: false)
Searchkick.multi_search([fresh_products, frozen_products])

We are rendering the results from different models in a single table with pagination.

Is there an easy way to merge the array of search results from multi_search into a single result set, so it can be passed to kaminari for pagination:

```
# @search_results is a merge of fresh_products, frozen_products ... etc and respond to
# currrent_page, next_page
  <%= paginate @search_results %>

```

**Comment by ankane** [comment]
Hey @frankliu81, you can do a single search across multiple indices to get all results together (see Multiple Indices section of readme).

**Comment by frankliu81** [comment]
@arkane, thanks, looking into searching across multiple indices as well with https://github.com/ankane/searchkick/issues/949, but working out issues with searching across multiple indices when searchable fields are specified.  

It seems like both searching across multiple indices and multi_search could work, but with multi_search I need to do a bit of work to merge the results together if I want to paginate, for example:

```
    def index
        #elasticsearch multi search, group into a single set of search_results
        indices = [Control, Objective, Risk]
        search_batch = batch_multiple_searches(sanitize_query_string(params[:search]), indices)
        Searchkick.multi_search(search_batch)

        @search_results_arr = []
        search_batch.each do |search_results_per_model|
          # skip if response is nil (a nil response can happen with a missing index)
          # no results would return [] for hits
          next if search_results_per_model.response['hits'].nil?

          # searchkick delegate to_arr to the results, and would return and array of active records
          # objects matching the search
          @search_results_arr.concat(search_results_per_model)
        end

        @search_results = Kaminari.paginate_array(@search_results_arr).page(params[:page])
        @search_count = @search_results.total_count
   end

   def batch_multiple_searches(term, indices)
     indices.map do |index|
       index.search(term, search_params.merge(execute: false))
     end
   end

```

**Comment by ankane** [comment]
Cleaning up stale issues
