### ISSUE TITLE
How setup index quality?

### ISSUE THREAD

**Issue by Radzhab** [ankane/searchkick#952]
I use this gem, but i dont like indexing by default. 
```
prod = Post.search "pr", fields: [:title] // find n-elements
prod = Post.search "prog", fields: [:title] // not found elements
prod = Post.search "program", fields: [:title] // find n-elements
```

How increase quality of indexing?

**Comment by ankane** [comment]
Hey @Radzhab, check out the Partial Matches section of the readme for how to change.

**Comment by Radzhab** [comment]
Partial Matches doesn't solve my issue. I want search any word match in string, but this 7 options doesn't allow it.  I want combine word_start+word_middle+word_end options. How make it?

```
:word # default
:word_start
:word_middle
:word_end
:text_start
:text_middle
:text_end

```
