### ISSUE TITLE
ES 5 Nested Query

### ISSUE THREAD

**Issue by marcnit** [ankane/searchkick#953]
I am using ElasticSearch 5.5 and seams that the nested query/filter doesn't work.

According to the searchkick Documentation, for nested Objects must use dot notation:

Eg. User.search "san", fields: ["address.city"], where: {"address.zip_code" => 12345}

I set it on my application:

AvailableDay.search("*", fields: ["location", "day", "available_hours.date"], where: {"available_hours.date"=>{:gte=>"2017-07-10"} }

This search results the next request on ES: 

_search?pretty -d '{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": [
        {
          "range": {
            "available_hours.date": {
              "from": "2017-07-10",
              "include_lower": true
            }
          }
        }
      ]
    }
  },
  "size": 1000,
  "from": 0,
  "timeout": "11s",
  "_source": false
}
'
And doesn't return the fields that would match.

RESULT:
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    **"total": 0,**
    "max_score": null,
    "hits": []
  }
}

According to the ES Documentation, the nested query for ES 5.5 (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html) need to pass the path.

Eg:  "query": {
        "nested" : {
            "path" : "obj1",
            "score_mode" : "avg",
            "query" : {
                "bool" : {
                    "must" : [
                    { "match" : {"obj1.name" : "blue"} },
                    { "range" : {"obj1.count" : {"gt" : 5}} }
                    ]
                }
            }
        }
    }

So that I changed the curl command to the next one:
_search?pretty -d '{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": [
        {
          "nested": {
            "path": "available_hours",
            "query": {
              "range": {
                "available_hours.date": {
                  "gte": "05/08/2017",
                  "format": "dd/MM/yyyy"
                }
              }
            }
          }
        }
      ]
    }
  }
}
'

and i get the expected results:

{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    **"total": 50,**
    "max_score": 1,
    "hits": [
      { ... }
  }
}

**Comment by ankane** [comment]
Hey @marcnit, it looks like you used a different date range in the example that works.

**Comment by ankane** [comment]
Cleaning up stale issues
