### ISSUE TITLE
Elasticsearch 5.5.0 deprecation warnings

### ISSUE THREAD

**Issue by jbwl** [ankane/searchkick#954]
When I index a model using Searchkick gem 2.3.1 on Elasticsearch 5.5.0, the following deprecation warnings are being shown in the ES deprecation log:

`Expected a boolean [true/false] for property [index] but got [analyzed]`

`field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.`

**Comment by ankane** [comment]
Hey @jbwl, thanks for reporting 👍  On master, I fixed the first and added an `_all` option to get rid of the 2nd.

```ruby
class Product
  searchkick _all: false
end
```

**Comment by jbwl** [comment]
Thank you for the quick fix!

**Comment by ankane** [comment]
Had most of it on a branch :)
