### ISSUE TITLE
Model.reindex with refresh issue

### ISSUE THREAD

**Issue by dreyks** [ankane/searchkick#955]
Seems that ElasticSearch does not honor the `refresh_interval` under `1s` anymore, so for my test suite I came up with a solution using monkeypatching that looks roughly like this

```ruby
module IndexAutoRefresher
  def reindex(*args, **kwargs)
    super(*args, **kwargs.update(refresh: true))
  end
  
  module CLassMethods
    def reindex(*args, **kwargs)
      super(*args, **kwargs.update(refresh: true))
    end
  end
end

Searchkick.models.each do |model|
  model.prepend IndexAutoRefresher
  model.singleton_class.prepend IndexAutoRefresher::ClassMethods
end
```
Now whenever my tests use `Model.reindex` or `Model.first.reindex` or anything like that, it gets refreshed immediately

But there is one issue: `Model.reindex` which turns into `Model.reindex(refresh: true)` (which kinda does not make sense because the refresh is done anyways, but I'm monkeypatching a global solution) and the `refresh: true` gets propagated to `Searchkick::Index#reindex_scope` which does not expect it as a keyword (obviously)

So the solution would be to change `refresh = options.fetch(:refresh, !scoped)` for `refresh = options.delete(:refresh, !scoped)` in [here](https://github.com/ankane/searchkick/blob/9c957ffd9a6bc5c356ead1ea445cac2e9b6d4369/lib/searchkick/model.rb#L56)

I can make this change if you approve it

**Comment by ankane** [comment]
Hey @dreyks, sounds like you're looking for an `always_refresh` option to use in testing?

**Comment by dreyks** [comment]
yup, something like this

**Comment by danilvoe** [comment]
@ankane How to use the parameter **always_refresh** ?

It is necessary that the data in the index be updated immediately, without delays.

**Comment by ankane** [comment]
Hey @danilvoe, no one has added this yet.
