### ISSUE TITLE
Randomize searchkick results

### ISSUE THREAD

**Issue by sharma-saurabh** [ankane/searchkick#957]
I'm using Searchkick to search through user records. I'm getting the same order for the results every time. I have gone through the documentation but could not find anything. Following is the implementation I'm using.

`search_params = {}`
`search_params[:where] = where     #where holds all the conditions for the search`
`search_params[:order] = {user_id: :desc}`
`user_matches = User.search "*", search_params`

**Comment by ankane** [comment]
Hey @sharma-saurabh, not sure I understand what you're trying to do. If you use the `order` option, results will be ordered the same way.
