### ISSUE TITLE
Results score scoped (where clause)

### ISSUE THREAD

**Issue by vgsantoniazzi** [ankane/searchkick#960]
Hi guys,

I have a question and I didn't find any answer for scoring with context. For example.

If I have `cars` (indexed), these cars have `user_id` and all my queries use `where: { user_id: user.id }`. But if I add more users with more cars, the score becomes larger (tf/idf) and I cannot set a `min_score`. 

How can I make the `_score` fixed by the user (where) and not for all documents?

**Comment by ankane** [comment]
Hey @vgsantoniazzi, you'll need to modify the query generated by Searchkick (essentially, do this yourself with ES syntax). You can find instructions in the readme.
