### ISSUE TITLE
Problem with multiple applications

### ISSUE THREAD

**Issue by giovaneperlin** [ankane/searchkick#962]
Hi.

I have multiple apps (almost identical) that have tables with the same name. My problem is that when i run **"mina production "rake[searchkick:reindex:all]""** on one app it **overwrites** the indexes on elasticsearch for the other apps, so the other apps loose the search function D:

How do i solve this? Please help!

**Comment by ankane** [comment]
Hey @giovaneperlin, you can use the `index_prefix` option to namespace indexes. Example from readme:

```ruby
class Product < ActiveRecord::Base
  searchkick index_prefix: "app_name"
end
```

If you use master, you can set it globally with:

```ruby
Searchkick.index_prefix = "app_name"
```

**Comment by giovaneperlin** [comment]
Thank you man. Saved my life.
