### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by liulupeng1987** [ankane/searchkick#969]
I use gem searchkick on my project. It works well on development environment and heroku.

Then I want to deploy my website to a linode server. I install elasticsearch on linode server. But I don't know how to make the searchkick function work.

  In searchkick document (deployment section), there were 3 choices, 

- heroku, 
- Amazon Elasticsearch Service
- Other

Regarding the Other solution. Can I do as follows?
1. Create an initializer config/initializers/elasticsearch.rb with:
`ENV["ELASTICSEARCH_URL"] = "http://localhost:9200"`

2. Where shall I run below command? On production terminal? or Local terminal? Will my method works?
`rake searchkick:reindex CLASS=Product`

I use ruby on rails, I am very new to be a coder. 

I hope I didn't bring trouble to you.

**Comment by Mavvie** [comment]
> Create an initializer config/initializers/elasticsearch.rb with:

No need, it should default to that!

> Where shall I run below command? On production terminal? or Local terminal? Will my method works?

Generally what I do is `cd` into your project directory (with cap it might be something like `/var/www/<project>/current`, and run `bundle exec rake searchkick:reindex CLASS=Product RAILS_ENV=production`

This is assuming you have:

1. Gotten your rails app working apart from the searchkick code paths

2. Have ElasticSearch running (if not, you'll have to install it. It's pretty simple)


The disadvantage with running your own server is that if services die, or the computer restarts, the services might not start up again. If you want your app to be reliable, I'd suggest sticking to heroku/AWS. If you're doing it for a learning experience though, then setting up your own server is great!

**Comment by liulupeng1987** [comment]
Hi，Mavvie
your method works. Thanks very much!

best regards,
Lupeng Liu
