### ISSUE TITLE
Allow AND *and* OR searches

### ISSUE THREAD

**Issue by jongold** [ankane/searchkick#97]
Hey - just trying to replicate functionality we had using Tire - would be great users could specify whether searches should be partial or not via the syntax.

e.g, with partial: true
"ruby design"
vs.
"ruby AND design"

As far as I can tell operators don't have any affect on the search =/

**Comment by cars10** [comment]
Any updates on this?

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest **and** someone wants to add this, please reply and we can continue to discussion.

**Comment by weilandia** [comment]
Is there a way to accomplish this without parsing the query string?  For example, passing an array where each individual item is and AND query, but separately it is an OR query?

i.e.
`["ruby method", "js function"]`

**Comment by weilandia** [comment]
I'm interested and giving this a shot, possibly using the [simple query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html), but would be helpful to get some context on some of the roadblocks making it [still not possible](https://github.com/ankane/searchkick/issues/213) in 2016 and some suggestions on where to start.
