### ISSUE TITLE
Keyword aggregations?

### ISSUE THREAD

**Issue by cmalpeli** [ankane/searchkick#970]
I recently tried upgrading to 5.5.1 and began receiving the following error:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [city] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true....`

I have aggregations on some fields like 'city', 'state', 'company name' etc.

I found the following article on this subject, and it sounds like I should be using keyword fields instead for this?

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/fielddata.html

How do I define keyword fields?  For a field like 'company' I need it to be both a searchable field, as well as an aggregation.  Any help would be appreciated!

**Comment by cmalpeli** [comment]
OK - I think I have this figured out via custom mappings like so:

`searchkick locations: ["location_geo"], 
            callbacks: :async, 
            merge_mappings: true, 
            mappings: {
                job: {
                  properties: {
                    city: { type: "text", fields: { keyword: { type: "keyword" } } },
                    state: { type: "text", fields: { keyword: { type: "keyword" } } },
                    country: { type: "text", fields: { keyword: { type: "keyword" } } },
                    job_type: {
                      type: "text",
                      fields: {
                        keyword: {
                          type: "keyword"
                        }
                      }
                    }
                  }
                }
              }`

I have two follow up questions:

1. `city`, `state`, `country` all work fine as they are properties of the Job Model.  However `job_type` is a custom method on the model, what is the syntax for using that in a custom mapping?

2. So far I have noticed that I didn't need to use custom searching even though I am using custom mapping.  Is that due to the use of `merge mappings`?

**Comment by cmalpeli** [comment]
The solution for Questions #1 appears to be that you need to define the fields not only in the custom mapper, but in `search_data` as well.

**Comment by will-r** [comment]
I think with recent (2017ish) searchkicks this is handled for us, but you need to delete and rebuild indexes so that the latest automatic mappings are used.

The default mapping for a text field is now something like:

```
"status"=> {
  "type"=>"keyword",
    "fields"=> {
      "analyzed"=>{
         "type"=>"text",
         "analyzer"=>"searchkick_index"
        }
      },
    "include_in_all"=>true,
    "ignore_above"=>30000
  }
}

```

Which meets the elasticsearch recommendation that we analyse text fields but aggregate or search against keyword fields. You can fine-tune this in a declarative way by adding `:filterable` and `:searchable` options, as [described very briefly](https://github.com/ankane/searchkick#searchable-fields) in the readme.

**Comment by ankane** [comment]
Thanks for the assist @will-r 👍
