### ISSUE TITLE
reindexing doesn't happen automatically in an engine

### ISSUE THREAD

**Issue by gotno** [ankane/searchkick#971]
using rails 4.2.8 and searchkick 1.4.0 in an app mounted as an engine within a rails app:

with a pretty minimal setup in the model (we use the class method from our search controller):
```ruby
searchkick word_start: [
  :first_name,
  :last_name,
  :email,
  :phone,
  :company,
], callbacks: :async

def self.index_search(query:)
  search(
    query || '*',
    fields: [:first_name, :last_name, :email, :phone, :company],
    match: :word_start,
    where: { test_account: false },
    order: { created_at: :desc },
    limit: 20,
    misspellings: false
  )
end

def search_data
  {
    first_name: first_name,
    last_name: last_name,
    created_at: created_at,
    email: email,
    phone: phone,
    test_account: test_account,
    company: company
  }
end
```
searchkick does not reindex on model creation or updates. i was forced to add:
```ruby
after_commit :reindex_search
def reindex_search
  Account.reindex
end
```

the only thing i can think of is that this has something to do with this app being mounted as an engine, but i question that assumption because i can't find anyone else experiencing the same issue. i'm happy to provide more details.

**Comment by ankane** [comment]
Hey @gotno, it looks like you're using async callbacks in the first part but synchronous in the 2nd. Are you sure jobs aren't just being queued?

**Comment by gotno** [comment]
ah, @ankane, you're right. my `reindex_search` method should also be async. that doesn't fix the primary issue, however, that reindexing is not happening automatically as described in the readme. without the `after_commit` hook, reindexing does not occur.

is there anything i can do to gain a better insight into why this might be?

**Comment by gotno** [comment]
alright, embarrassing, this is totally my fault. i'm using sidekiq for background jobs and i didn't have searchkick listed in the available queues, so nothing was being processed.
