### ISSUE TITLE
Augmentation to `#search_data` ineffective in browser

### ISSUE THREAD

**Issue by jayqui** [ankane/searchkick#975]
Hi, I am experiencing some really weird behavior and I'm wondering if I can get any insights here.

Basically, the search is doing what I expect in a test file, but not in the browser.

## The Issue ##
The expected behavior is that I should be able to search for a full name with a space in it. This works in my test, but not in browser.

### account.rb ###
    class Account
      searchkick word_start: [
        :first_name,
        :last_name,
        :name, # <======================== key line
        :email,
        :phone,
        :company,
      ], callbacks: :async

      def self.index_search(query:)
        search(
          query || '*',
          fields: [
            :first_name,
            :last_name,
            :name, # <======================== key line
            :email,
            :phone,
            :company,
          ],
          match: :word_start,
          where: { test_account: false },
          order: { created_at: :desc },
          limit: 20,
          misspellings: false,
        )
      end

      def search_data
        {
          first_name: first_name,
          last_name: last_name,
          name: "#{first_name} #{last_name}", # <======================== key line
          created_at: created_at,
          email: email,
          phone: phone,
          test_account: test_account,
          company: company
        }
      end
    end

### account_test.rb - ALL OF THESE PASS ###
    class AccountTest < ActiveSupport::TestCase
      describe "::index_search" do
        let(:account_0) do
          FactoryGirl.create(:account, company: "Xyz Consulting")  # name: "Testy McTesterson"
        end
        let(:account_1) do
          FactoryGirl.create(:account, first_name: "Bob") # name: "Bob McTesterson"
        end
        let(:search) do
          Account.index_search(query: query)
        end

        before :all do
          account_0 and account_1 # instantiate
          Searchkick.disable_callbacks
          Account.reindex
        end

        describe "when there are spaces in the string" do
          let(:query) { "xyz con" }

          it "finds all and only the appropriate records" do
            assert_equal [account_0.id], search.map(&:id)
          end
        end

        describe "when the query matches the full name" do
          let(:query) { "bob mct" }

          it "finds all and only the appropriate records" do
            assert_equal [account_1.id], search.map(&:id)
          end
        end
      end
    end

**Note:** when I comment out the three 'key lines' from  `account.rb`, the second of those tests fails. So the `name:` in the `#search_data` method seems to be working.

### search_controller.rb (essentially) ###

    class SearchController < ApplicationController
      def index
        puts "params[:query]: #{params[:query]}"
        puts "custom_search.map(&:first_name): #{custom_search.map(&:first_name)}"
        puts "custom_search.map(&:last_name): #{custom_search.map(&:last_name)}"
      end

      private

      def custom_search
       Account.index_search(query: params[:query])
      end
    end

## The Complication ##

Nonetheless, in the browser, it doesn't seem to be working. With the above code, searching via the browser, I can't reproduce the success.

When I search for `"bob "`, the output in my server console is

    params[:query]: bob
    custom_search.map(&:first_name): ["Bob"]
    custom_search.map(&:last_name): ["McTesterdorff"]

but as soon as I search for `"bob m"`, `"bob mct"`, or `"bob mctesterdorff"`, I get empty results (respecitvely):

    params[:query]: bob m
    custom_search.map(&:first_name): []
    custom_search.map(&:last_name): []

    params[:query]: bob mct
    custom_search.map(&:first_name): []
    custom_search.map(&:last_name): []

    params[:query]: bob mctesterdorff
    custom_search.map(&:first_name): []
    custom_search.map(&:last_name): []

Do you all have any idea what's up?

**Comment by ankane** [comment]
Hey @jayqui, I'm not sure what the issue is, but it doesn't sounds like an issue with Searchkick, so going to close.
