### ISSUE TITLE
[Howto] Two orders on same table

### ISSUE THREAD

**Issue by kesha-antonov** [ankane/searchkick#978]
Hello! @ankane Thanks for the awesome searchkick!

Is it possible to do something like this?

```
rel1 = Model.where(field_1: true).order(created_at: :asc)
rel2 = Model.where(field_1: false).order(created_at: :desc)
rel = Model.from_sql("#{rel1.to_sql} UNION #{rel2.to_sql} as models")
```

In other words: I need to search 1 model for 2 queries with different conditions and different order.

Thanks!

UPDATE

OK. I know how to get different records for different conditions. But how to apply different orders?

**Comment by ankane** [comment]
Hey @kesha-antonov, in the example above, you should be able to do 2 separate searches and combine them together in Ruby.

```
rel1 = Model.search(where: {field_1: true}, order: {created_at: :asc}))
rel2 = Model.search(where: {field_1: false}, order: {created_at: :desc})
rel = rel1.results + rel2.results
```

**Comment by kesha-antonov** [comment]
@ankane Thank you! Yeah, I'm doing search this way right now.
I thought maybe I could do it with one ```Model.search``` or chain them ```Model.search(...).search(...)```

But anyway the above is the right way, it's OK!
