### ISSUE TITLE
Parallel Reindexing doesn't work with UUID

### ISSUE THREAD

**Issue by tjku** [ankane/searchkick#983]
When I try to do `Product.reindex(async: true)`, this bug occures:

```
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function min(uuid) does not exist
LINE 1: SELECT MIN("products"."id") FROM "products"
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT MIN("products"."id") FROM "products"
```
Without `async: true`, reindexing works just fine so I assume this is because of using `MIN` function by parallel reindexing. Is this a bug caused by UUID? How can I use parallel reindexing when model has UUID as a primary key?

Apart from this, UUID works as expected in my project. I'm using it by enabling extension `uuid-ossp`.

I am using PostgreSQL 9.6.2, ElasticSearch 5.5.2, Ruby 2.3.1 and Rails 4.2.7.1.

**Comment by ankane** [comment]
Hey @tjku, thanks for the detailed report 👍   All fixed now.
