### ISSUE TITLE
Fetching results in random order with a :where clause using searchkick and rails 5.1

### ISSUE THREAD

**Issue by marvindanig** [ankane/searchkick#984]
This is probably a simple thing, but I can't seem to get my head around it:

I want elasticsearch to return:

```
    @random_books   = Book
                        .includes(:cover)
                        .includes(:author)
                        .search("*",
                          where: { status: :published },
                          body: {
                            query: {
                              function_score: {
                                random_score: {
                                  seed: seed
                                }
                              }
                            }
                          },
                          page: params[:random],
                          per_page: 12)



```

The results returned do not honor the `where: {status: :published}` clause. How do I syntax up this query? Asked this one on [SO](https://stackoverflow.com/questions/46045531/fetching-results-in-random-order-with-a-where-clause-using-searchkick-and-rails) as well.

**Comment by ankane** [comment]
Hey @marvindanig, if you use the `body` option, it overrides all the other options. See the screenshot below for the relevant section of the readme.

![screen shot 2017-09-06 at 12 46 40 am](https://user-images.githubusercontent.com/220358/30100202-e6fe160a-929c-11e7-9ae6-50571d6989ef.png)

**Comment by marvindanig** [comment]
Oooh! Thank you @ankane for pointing me at right direction. Here's the right way of writing this:

```
    seed = Time.zone.now.to_i

    @random_books   = Book
                        .includes(:cover)
                        .includes(:author)
                        .search("*",
                          body: {
                            query: {
                              function_score: {
                                query: {
                                  match: { status: :published }
                                  },
                                random_score: {
                                  seed: seed
                                }
                              }
                            }
                          },
                          page: params[:random],
                          per_page: 12)

```

**Comment by ankane** [comment]
Devs will now see a warning if they use the `body` option and other incompatible options.

**Comment by marvindanig** [comment]
Ow. Looks like this warning is produced on `production` mode as well. I'll get the incompatible options within the `body` option next to get around this, but may be it should be noted somewhere in the docs.

**Comment by ankane** [comment]
Hey @marvindanig, this is noted in the docs fwiw. See the screenshot I posted on Sep 6.
