### ISSUE TITLE
Dynamic partial indexes for custom fields

### ISSUE THREAD

**Issue by hashwin** [ankane/searchkick#986]
I am trying to incorporate custom user-defined fields into searchkick, and for the most part it works. The problem is I am not able to do partial searches these fields as I do not know in advance what they will be called. So I cannot put them into the ```searchkick text_middle:``` implementation in the model.

Any ideas on how I can get this working? Is there some kind of wildcard to allow any name nested under a particular attribute?

**Comment by Xtinct** [comment]
Faced same problem earlier, here's my solution:
```
  searchkick(index_name: -> {Apartment::Tenant.current},
    merge_mappings: true,
    mappings: {
      _default_:   {
        dynamic_templates: [
          string_template: {
            match: '*',
            match_mapping_type: "*",
            mapping: {
              fields: {
                analyzed: {
                  index: :analyzed,
                  type: :text,
                  analyzer: :searchkick_search
                },
                for_filter: {
                  type: :text,
                  index: :analyzed,
                  analyzer: :searchkick_for_filter_index
                }
              },
              type: :keyword,
              ignore_above: 256
            }
          }
        ],
        properties: {
          creation_time: {
            type: :date,
            fields: {
              analyzed: {
                type: :date
              }
            }
          }
        }
      },
    },
    settings: {
      analysis: {
        analyzer: {
          searchkick_for_filter_index: {
            type: :custom,
            tokenizer: :keyword,
            filter: [
              :lowercase,
              :asciifolding,
              :searchkick_edge_ngram
            ]
          }
        }
      }
    })
```
The idea is to use dynamic templates to match every field passed to elasticsearch. `for_filter` field uses custom analyzer which filters content with edge_ngram filter(which corresponds to *_start fields). You will need to use `searchkick_ngram` if you want to use text middle search. To actually use it, `match` option should have `for_filter` as a value OR searched field should have `for_filter` suffix (I.e ` where: { "your_field.for_filter" => 'some_value'}`) .Here's an example of how i use it:
```Searchkick.search(term.downcase, default_options(drop_term: true).merge(fields: [field], aggs: Hash[field, {limit: 20}] , match: :for_filter, misspellings: false))```
This method has cons though. All of the values will be treated as string to actually make this working. If you need some static fields to have concrete data type, you can define them if `properties` section.

**Comment by hashwin** [comment]
Hi @Xtinct, thanks for the suggestion and detailed explanation.
Seems like it would work, though I'm having trouble actually getting the data into elastic without searchkick trying to create the default mapping for the fields. Is there any way to stop this mapping?

As for different field types, I think you could get around this by prefixing the data type in the field name when data is collected in seachkick.

**Comment by ankane** [comment]
Hey @Xtinct, thanks for the assist 👍 

@hashwin you can remove the `merge_mapping` option and Searchkick will not use its own mapping.

**Comment by hashwin** [comment]
@ankane Removing the merge_mapping option does not seem to work. The generated index mapping still seems to contain all the fields that should be covered by the dynamic template. Since I am working with a lot of custom user-defined fields, this is causing me to hit limits on the number of fields in elastic - potentially leading to mapping explosion when I hit larger datasets.

I am digging further, but if you know how to completely stop the auto-mapping please let me know!

**Comment by hashwin** [comment]
One thing to note that is the mapping I need looks correct at this point:
https://github.com/ankane/searchkick/blob/master/lib/searchkick/index_options.rb#L342
This is before the data is imported.

But after the data is imported, the mapping contains much more based on the data that is imported where it should just be using the dynamic templates that are defined in the original mapping.

**Comment by hashwin** [comment]
I guess this is not a problem per se with searchkick since it looks like elasticsearch itself is generating those indices. Gonna look into restructuring my data to prevent mapping explosion...
