### ISSUE TITLE
Partial reindex on a subset of records and merge it with existing index

### ISSUE THREAD

**Issue by frankliu81** [ankane/searchkick#987]
From the readme:

Attempting to reindex with a scope now throws a Searchkick::DangerousOperation error to keep your from accidentally recreating your index with only a few records.

Product.where(color: "brandy").reindex # error!
If this is what you intend to do, use:

Product.where(color: "brandy").reindex(accept_danger: true).

What if I have many organizations in my record sets, and for a particular model, I want to reindex the data just for a specific organization (ie. by organization_id), and merge the reindexed data for that organization with the index for the particular model?  Is this doable?

**Comment by ankane** [comment]
Hey @frankliu81, try upgrading. Version 2.0 removed this limitation.
