### ISSUE TITLE
Not indexing large documents

### ISSUE THREAD

**Issue by ifritz7** [ankane/searchkick#988]
I am new to searchkick. I set it up in the model. When I search, it only returns smaller documents. The elasticsearch gem indexes and searches with no issue. Is there a document size limit or something?

**Comment by ankane** [comment]
Hey @ifritz7, very large documents aren't included in the `_all` field. Try specifying `fields` when you search to get around this.

**Comment by ankane** [comment]
Cleaning up stale issues
