### ISSUE TITLE
How to find out the time that was spent on indexing?

### ISSUE THREAD

**Issue by danilvoe** [ankane/searchkick#992]
Time spent on the search is clear how to find out, the time spent on indexing is of interest.

**Comment by rafaelsales** [comment]
On synchronous indexing I use `Benchmark.measure`

**Comment by ankane** [comment]
Hey @danilvoe, Searchkick has ActiveSupport notifications you can hook into for this. See https://github.com/ankane/searchkick/blob/master/lib/searchkick/logging.rb
