### ISSUE TITLE
Own method in search_import

### ISSUE THREAD

**Issue by yurgon** [ankane/searchkick#993]
Hello
How to add own method to scope search_import ?
Thx

**Comment by mikelkew** [comment]
You can just write your own rules for the search_import scope as mentioned in the [docs here](https://github.com/ankane/searchkick#indexing).

If you need to control which records are indexed by calling a method (as opposed to the conditions possible in a scope), you can also use the `should_index?` method mentioned in the same section of the docs.

**Comment by yurgon** [comment]
Thank you, Mikel
I have array filed with categories ids in Product model
Don't understand how to add categories to index through search_import scope

**Comment by mikelkew** [comment]
It depends on what you want to do with the categories, but on first impression I'm not sure if adding them to the scope is the right approach.

You could start with:
` scope :search_import, -> { includes(:categories) }`

and then index the relation using something roughly along the lines of:

```ruby
# Specify product fields to index, e.g.
PRODUCT_FIELDS = %i[
  id
  name
  description
]

# use search_data to add other fields
def search_data
  as_json(only: PRODUCT_FIELDS).merge(search_data_fields)
end

# define additional fields and data you want here
def search_data_fields
  {
    categories: categories.as_json(only: [:id, :name])
  }
end
```

Just a rough example without knowing exactly what you want to achieve.

**Comment by yurgon** [comment]
Product model and Categories model dont have relationI
I use method to get categories for a product like this:

```
def categories
    if self.category_product && !self.category_product.empty?
      Category.joins(:category_products).where(category_products:{main_id: self.category_product})
    end
  end
```

**Comment by mikelkew** [comment]
Hmm, in that case it makes it a bit tricky to eager load the categories in the scope. You could still include the categories in the search data using your categories method, but it'll most likely result in n+1 queries unless you create an actual relation between the models and use it in the scope.

**Comment by yurgon** [comment]
Yeah
Thanks

**Comment by rafaelsales** [comment]
Shouldn't this be closed?
