### ISSUE TITLE
How would I translate this to .search

### ISSUE THREAD

**Issue by spacerobotTR** [ankane/searchkick#995]
How would I translate this statement to a searchkick search?

@projects = Project.joins(:proj_status)

I was trying something like this:

@projects = Project.search("*").joins(:proj_status)

but I have been getting errors that joins is an undefined method.

Any thoughts or ideas are appreciated.

**Comment by ankane** [comment]
Hey @spacerobotTR, you can't use `joins` with Searchkick.
