### ISSUE TITLE
How can I make case insensitive exact searches?

### ISSUE THREAD

**Issue by pawneetdev** [ankane/searchkick#997]
The exact search is case sensitive, I suppose. The documentation mentions that it is case-insensitive.
https://github.com/ankane/searchkick#exact-matches

Can I use it to find case-insensitive strings or I will have to reindex the data with lowercase strings?

**Comment by ankane** [comment]
Hey @pawneetdev, looks like it is case-sensitive. I've updated the docs. The easiest thing to do would be to add a lowercase version to `search_data`.
