### ISSUE TITLE
Multiple Indices text search for models that has `searchable` specified only finds data if `fields` search attribute is given

### ISSUE THREAD

**Issue by rafaelsales** [ankane/searchkick#999]
```ruby
class Foo < ActiveRecord::Base
  searchkick searchable: [:name, :phone]
end

class Bar < ActiveRecord::Base
  searchkick searchable: [:name, :phone]
end

Foo.create(name: 'One Foo', phone: '11')
Foo.create(name: 'Two Foo', phone: '12')
Bar.create(name: 'One Bar', phone: '21')
Bar.create(name: 'Two Bar', phone: '22')

> Foo.search('11', misspellings: false).results.count
=> 1 # returns "One Foo"

> Searchkick.search('11', index_name: [Foo, Bar], misspellings: false).results.count
=> 0 # Unexpected!

> Searchkick.search('11', index_name: [Foo, Bar], fields: [:phone], misspellings: false).results.count
=> 1 # returns "One Foo"
```

This seems to be related to the custom `searchable` provided on the mapping, because removing it fixes the issue, i.e., don't need to pass `fields` attribute on the `search`

**Versions:**
searchkick (2.3.2)
elasticsearch (5.0.4)
elasticsearch-api (5.0.4)
elasticsearch-transport (5.0.4)
ElasticSearch 5.6.1 installed via homebrew

**Comment by rafaelsales** [comment]
@ankane if you agree that we shouldn't have to provide the `fields` in this case, I'm willing to work on a PR. Let me know...

**Comment by ankane** [comment]
@rafaelsales if all values passed to the index_name option are models and they all have searchable option, then it would make sense to not have to provide fields option.

**Comment by ankane** [comment]
Cleaning up stale issues
